### ISSUE TITLE
Warning "ignoring pragma" during compile

### ISSUE THREAD

**Issue by vgfl** [weidai11/cryptopp#1001]
scrypt.cpp:307: warning: ignoring ‘#pragma omp parallel’ [-Wunknown-pragmas]
  307 |     #pragma omp parallel num_threads(threads)
      | 
scrypt.cpp:314: warning: ignoring ‘#pragma omp for’ [-Wunknown-pragmas]
  314 |         #pragma omp for

**Comment by noloader** [comment]
This is a well known GCC bug. Also see https://stackoverflow.com/q/12842306/608639 and https://gcc.gnu.org/bugzilla/show_bug.cgi?id=53431.
