### ISSUE TITLE
More safe memory management

### ISSUE THREAD

**Issue by ujos** [weidai11/cryptopp#1002]
Some classes like `HashFilter` and `StringSource` require pointer to be passed into classes constructor. That pointer later is owned by those classes.

This approach is error prone:

1. User can have a pointer owned by `std::unique_ptr` and if they forget to call `std::unique_ptr::release` after class is constructed, that will cause double free error after both (class object and smart pointer) go out of scope.
2. If user does not use `std::uqniue_ptr` and they pass the raw pointer to the class constructor and constructor throws an exception, who is responsible to release memory pointed by passed pointer?

I'd like to ask you to change/overload the classes constructor and accept `std::unique_ptr` by value instead of raw pointer. That solves all the mentioned problems above. 

```cpp
class HashFilter
{
public:
  HashFilter(StringSink* ptr);

#if __cplusplus >= 201103
  HashFilter(std::unique_ptr<StringSink> ptr) : HashFilter(ptr.get()) { ptr.release(); }
#endif
};
```

The benefits of new constructor are:

* The intent is more obvious now.
 a) Everyone who use this constructor know, here they are going to move an ownership.
 b) The object passed must be allocated on the heap and will be destroyed with the delete operator

* It is more user friendly now for those who use C++ features:

### Before

```cpp
std::string calculated_hmac;
auto sink   = std::make_unique<StringSink>(calculated_hmac);
auto filter = std::make_unique<HashFilter>(hmac, sink.get());
sink.release(); // if I forget to call it, I get a double free bug
```

### After
```cpp
std::string calculated_hmac;
auto sink   = std::make_unique<StringSink>(calculated_hmac);
auto filter = std::make_unique<HashFilter>(hmac, std::move(sink));
```

**Comment by expnkx** [comment]
please no. unique_ptr is harmful. It is not zero cost

**Comment by ujos** [comment]
@expnkx If you write the code as it has to be written, it looks the same as if you use `std::unique_ptr`.

**Comment by expnkx** [comment]
> @expnkx If you write the code as it has to be written, it looks the same as if you use `std::unique_ptr`.

No true. Putting unique_ptr as interface is always a mistake.

**Comment by ujos** [comment]
> https://youtu.be/rHIkrotSwcc?t=1147

I respect Chandler Carruth but the code he presented on the left side has nothing to code on the right side. 

In his code he does not care about exceptions. Also the code on the right does more - it cares about ownership, that is why it is bigger.

Please compare:

* No unique_ptr: https://gcc.godbolt.org/z/haa7zM
* With unique_ptr: https://gcc.godbolt.org/z/1efar6

I'm going to submit the bug report to the gcc as we do not need code in lines 13-16 as pointer is empty after we get control from the `foo` function.

**Comment by expnkx** [comment]
> > https://youtu.be/rHIkrotSwcc?t=1147
> 
> I respect Chandler Carruth but the code he presented on the left side has nothing to code on the right side.
> 
> In his code he does not care about exceptions. Also the code on the right does more - it cares about ownership, that is why it is bigger.
> 
> Please compare:
> 
> * No unique_ptr: https://gcc.godbolt.org/z/haa7zM
> * With unique_ptr: https://gcc.godbolt.org/z/1efar6

yours is a terrible example.
why not just use int instead of new int?

**Comment by ujos** [comment]
> why not just int p=3;????

I'm not sure I understand your question

**Comment by expnkx** [comment]
> > why not just int p=3;????
> 
> I'm not sure I understand your question

Why put data on heap if you can just define them in the register?

**Comment by ujos** [comment]
I used `int` as it is trivial type so we can focus on the heap allocation only and ASM code is not bloated with things not related to the topic.

**Comment by expnkx** [comment]
> I used `int` as it is trivial type so we can focus on the heap allocation only and ASM code is not bloated with things not related to the topic.

Not a trivial type does not change the fact defining type with new is a problem, no matter you use unique_ptr or not

**Comment by ujos** [comment]
I've opened the [ticket on GCC Bugzilla](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=98840) regarding `std::unique_ptr` "zero-cost".

**Comment by noloader** [comment]
@ujos,

Crypto++ predates C++11 and `std::unique_ptr`. We would lose some platforms, like OS X and Solaris, by requiring C++11. Apple is especially notorious for shipping a partial implementation of C++11. It is more like C++03 masquerading as C++11.

Internally, when needed, the library uses `smart_ptr`. It manages resources without worrying about ownership. Also see [smartptr.h](https://github.com/weidai11/cryptopp/blob/master/smartptr.h).

The library used to use a fair amount of `std::shared_ptr` but we gutted them for `smart_ptr`.

**Comment by ujos** [comment]
@noloader What if to add the `#ifdef __cplusplus` constructor overload?

**Comment by noloader** [comment]
On Wed, Jan 27, 2021 at 5:39 AM Dmytro Ovdiienko <notifications@github.com>
wrote:

> @noloader <https://github.com/noloader> What if to add the #ifdef
> __cplusplus constructor overload?
>
It is not accurate for most Apple platforms, including Clang compilers. It
is completely missing on most Microsoft compilers.

In the bigger picture, complicating the ABI is not something I want to do.
Taking a {ptr,len} is about as simple as things get.

**Comment by ujos** [comment]
> It is completely missing on most Microsoft compilers

MSVC++ defines this macro if `/Zc:__cplusplus` parameter is defined. 

For the rest of compilers I used this macro is accurate with some minor drift. Please see [Feature testing article](https://en.cppreference.com/w/cpp/feature_test)

**Comment by ujos** [comment]
> In the bigger picture, complicating the ABI is not something I want to do.

I do not think it brakes ABI. I thought about some inline constructor which is available for C++11 enabled compilers.

```cpp  
class HashFilter
{
public:
#if __cplusplus >= 201103
  HashFilter(std::unique_ptr<StringSink> ptr) : HashFilter(ptr.get()) { ptr.release(); }
#endif
};
```


  | C++98 | C++11 | Notes
-- | -- | -- | --
gcc | 199711 | 201103 |  
clang | 199711 | 201103 |  
msvc++ | 199711 | 201402 | The   compiler does not support standards switches for C++98, C++03, or C++11.

**Comment by expnkx** [comment]
> ```c++
> std::unique_ptr<StringSink> ptr
> ```

std::unique_ptr<StringSink> ptr is slow since it is passed by StringSink** by API. Not pass it by the register.
Raw pointer is just fine tbh.

**Comment by ujos** [comment]
I’m 99% sure it’s going to be inlined. There will be no function call.

Best regards
Dima
________________________________

**Comment by ujos** [comment]
Crypto++ is a C++ library. The approach used in the constructor is more C than C++. The user code is ugly and error prove because of that. See

https://stackoverflow.com/a/62092711

Best regards
Dima
________________________________

**Comment by ujos** [comment]
> std::unique_ptr ptr is slow since it is passed by StringSink** by ABI. Not pass it by the register.
> Raw pointer is just fine tbh.

The optimization you are talking about makes no sense comparing to the fact that I have allocate memory in the heap and pass it to the HashFilter.

**Comment by expnkx** [comment]
> Crypto++ is a C++ library. The approach used in the constructor is more C than C++. The user code is ugly and error prone because of that. See https://stackoverflow.com/a/62092711

C++ library does not mean you should use every C++ feature nor it is an OOP language. C features are fine tbh.

**Comment by expnkx** [comment]
> I’m 99% sure it’s going to be inlined. There will be no function call.

inline in C++ has nothing to do with what you understand. inline means the compiler should not violate ODR. https://devblogs.microsoft.com/oldnewthing/20200521-00/?p=103777

**Comment by expnkx** [comment]
> > std::unique_ptr ptr is slow since it is passed by StringSink** by ABI. Not pass it by the register.
> > Raw pointer is just fine tbh.
> 
> The optimization you are talking about makes no sense comparing to the fact that I have allocate memory in the heap and pass it to the HashFilter.

BTW constructors will forbid RVO which is very problematic. C++20 designated initializer is good but it will stop working when you define custom copy/move constructors.

**Comment by ujos** [comment]
@expnkx I do not understand what are you talking about. 

I define one more constructor which is delegating constructor. It just implements what I already have to do all of the time when I use Crypto++ library (e.g. I have this code already and I'd like to move it to `HashFilter`):

1. It calls `HashFilter` constructor 
2. After `HashFilter` is executed it calls `std::unique_ptr::release`

The benefits of this constructor are:

* The intent is more obvious now. 
a) Everyone who use this constructor know that here they are going to pass an ownership. 
b) The object passed must be allocated on the heap and will be destroyed with the `delete operator`

* It is more user friendly now for those who use C++ features.

This constructor has zero overhead If you do not believe me, try https://gcc.godbolt.org/.

What you are doing is called **premature optimization**.

**Comment by expnkx** [comment]
> @expnkx I do not understand what are you talking about.
> 
> I define one more constructor which is delegating constructor. It just implements what I already have to do all of the time when I use Crypto++ library (e.g. I have this code already and I'd like to move it to `HashFilter`):
> 
> 1. It calls `HashFilter` constructor
> 2. After `HashFilter` is executed it calls `std::unique_ptr::release`
> 
> The benefits of this constructor are:
> 
> * The intent is more obvious now.
>   a) Everyone who use this constructor know that here they are going to pass an ownership.
>   b) The object passed must be allocated on the heap and will be destroyed with the `delete operator`
> * It is more user friendly now for those who use C++ features.
> 
> This constructor has zero overhead If you do not believe me, try https://gcc.godbolt.org/.
> 
> What you are doing is called **premature optimization**.

What you are doing is that you completely failed to understand how C++ works.
https://gcc.godbolt.org/z/aGnbM3

The constructors generate 15 more instructions just because of constructors. Constructors will forbid return-value-optimizations which is really annoying.

**Comment by ujos** [comment]
> https://gcc.godbolt.org/z/aGnbM3

I have no idea why do you use `std::string`. Replace it with `std::unique_ptr` and you will get identical assembly output.

**Comment by expnkx** [comment]
> > https://gcc.godbolt.org/z/aGnbM3
> 
> I have no idea why do you use `std::string`. Replace it with `std::unique_ptr` and you will get identical assembly output.
> 
> If you replace gcc with clang, you will get exactly the same assembly output using `std::string`

I am just using std::string as an example. std::unique_ptr would create issues too.
clang would fail either when it gets even a little bit complicated, like invoke non-pure functions etc.
