### ISSUE TITLE
Out of source build

### ISSUE THREAD

**Issue by kpyrkosz** [weidai11/cryptopp#1006]
Building out of source is not supported. Running
```
mkdir build
cd build
make -f ../GNUmakefile
```
Ends with
```
cp: cannot stat 'adhoc.cpp.proto': No such file or directory
grep: config_ver.h: No such file or directory
make: *** No rule to make target 'cryptlib.o', needed by 'libcryptopp.a'.  Stop.
```

**Comment by noloader** [comment]
Thanks @kpyrkosz.

Yeah, out-of-tree builds are not supported. Also see [Install.txt](https://github.com/weidai11/cryptopp/blob/master/Install.txt).

The work around is a in-tree build. To go back to a pristine state, use `make distclean`.

It looks like Install.txt fails to state the fact. I'll get it added.

**Comment by kpyrkosz** [comment]
Are there plans to add out of source builds? That would greatly help in building multiple configurations at once, in parallel or for different architectures. Vast majority of projects support such mode out of the box.

**Comment by noloader** [comment]
@kpyrkosz,

No, there are no plans to build out-of-tree.
