### ISSUE TITLE
win32 lib link error in vs2015&2019

### ISSUE THREAD

**Issue by kissdish** [weidai11/cryptopp#1008]
1>cryptlib.lib(integer.obj) : error LNK2019: unresolved external symbol ___std_reverse_trivially_swappable_1  referenced in function "void __cdecl std::reverse<unsigned char *>(unsigned char * const,unsigned char * const)" (??$reverse@PAE@std@@YAXQAE0@Z)
1>cryptlib.lib(integer.obj) : error LNK2019: unresolved external symbol ___std_reverse_copy_trivially_copyable_1 referenced in function "class stdext::checked_array_iterator<unsigned char *> __cdecl std::reverse_copy<unsigned char const *,class stdext::checked_array_iterator<unsigned char *> >(unsigned char const *,unsigned char const *,class stdext::checked_array_iterator<unsigned char *>)" (??$reverse_copy@PBEV?$checked_array_iterator@PAE@stdext@@@std@@YA?AV?$checked_array_iterator@PAE@stdext@@PBE0V12@@Z)

x64 is no any trouble but link x86 static library show above error

**Comment by noloader** [comment]
Visual Studio 2005 needs SP1.

Visual Studio 2019 should be OK. Our CI tests and manual don't experience the problem.

**Comment by kuzmenko-andrey** [comment]
This problem reproduced on my build too. I've used Visual Studio 2019 and the problem reproduces with msbuild on azure.

**Comment by noloader** [comment]
MSDN has a similar error at https://social.msdn.microsoft.com/Forums/sqlserver/en-US/0898b305-f1d7-4808-a8a4-db56a2589280/two-similar-versions-of-vs2015-one-raises-stdreversetriviallyswappable4-linking-issues-?forum=vcgeneral.

Maybe you can try some of the workarounds.

**Comment by kuzmenko-andrey** [comment]
it is not possible to update redistributive on azure, but /MT or /MTd did not help

**Comment by noloader** [comment]
That's unfortunate. You should probably get Microsoft support involved for VS2015 and Azure.

When Microsoft releases its Build Tools for VS2019, I will be able to look at the issue.

**Comment by LongJohnBronze** [comment]
We ran into the same issue. The errors are due to incompatible STL versions. cryptlib selects the latest platform toolset while our projects used VS2015. Altering cryptlib's .vcxproj file to set the PlatformToolset to v140 fixed the errors.
