### ISSUE TITLE
macOS 11.2.1: ld: symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by devharsh** [weidai11/cryptopp#1009]
* State the operating system and version (Ubutnu 17 x86_64, Windows 7 Professional x64, etc)
macOS Big Sur 11.2.1

* State the version of the Crypto++ library (Crypto++ 7.0, Master, etc)
8.4.0

* State how you built the library (Makefile, Cmake, distro, etc)
make -j 4
sudo make install

* Show a typical command line (the output of the compiler for cryptlib.cpp)
c++ -DNDEBUG -g2 -O3 -fPIC -pthread -pipe -c cryptlib.cpp

* Show the link command (the output of the linker for libcryptopp.so or cryptest.exe)
libtool -static -o libcryptopp.a cryptlib.o cpu.o integer.o 3way.o adler32.o algebra.o algparam.o allocate.o arc4.o aria.o aria_simd.o ariatab.o asn.o authenc.o base32.o base64.o basecode.o bfinit.o blake2.o blake2b_simd.o blake2s_simd.o blowfish.o blumshub.o camellia.o cast.o casts.o cbcmac.o ccm.o chacha.o chacha_avx.o chacha_simd.o chachapoly.o cham.o cham_simd.o channels.o cmac.o crc.o crc_simd.o darn.o default.o des.o dessp.o dh.o dh2.o dll.o donna_32.o donna_64.o donna_sse.o dsa.o eax.o ec2n.o eccrypto.o ecp.o elgamal.o emsa2.o eprecomp.o esign.o files.o filters.o fips140.o fipstest.o gcm.o gcm_simd.o gf256.o gf2_32.o gf2n.o gf2n_simd.o gfpcrypt.o gost.o gzip.o hc128.o hc256.o hex.o hight.o hmac.o hrtimer.o ida.o idea.o iterhash.o kalyna.o kalynatab.o keccak.o keccak_core.o keccak_simd.o lea.o lea_simd.o luc.o mars.o marss.o md2.o md4.o md5.o misc.o modes.o mqueue.o mqv.o nbtheory.o oaep.o osrng.o padlkrng.o panama.o pkcspad.o poly1305.o polynomi.o pssr.o pubkey.o queue.o rabbit.o rabin.o randpool.o rc2.o rc5.o rc6.o rdrand.o rdtables.o rijndael.o rijndael_simd.o ripemd.o rng.o rsa.o rw.o safer.o salsa.o scrypt.o seal.o seed.o serpent.o sha.o sha3.o sha_simd.o shacal2.o shacal2_simd.o shake.o shark.o sharkbox.o simeck.o simon.o simon128_simd.o skipjack.o sm3.o sm4.o sm4_simd.o sosemanuk.o speck.o speck128_simd.o square.o squaretb.o sse_simd.o strciphr.o tea.o tftables.o threefish.o tiger.o tigertab.o ttmac.o tweetnacl.o twofish.o vmac.o wake.o whrlpool.o xed25519.o xtr.o xtrcrypt.o xts.o zdeflate.o zinflate.o zlib.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: algebra.o has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: dh.o has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: eprecomp.o has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: polynomi.o has no symbols
ranlib libcryptopp.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcryptopp.a(algebra.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcryptopp.a(dh.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcryptopp.a(eprecomp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcryptopp.a(polynomi.o) has no symbols
c++ -o cryptest.exe -DNDEBUG -g2 -O3 -fPIC -pthread -pipe adhoc.o test.o bench1.o bench2.o bench3.o datatest.o dlltest.o fipsalgt.o validat0.o validat1.o validat2.o validat3.o validat4.o validat5.o validat6.o validat7.o validat8.o validat9.o validat10.o regtest1.o regtest2.o regtest3.o regtest4.o ./libcryptopp.a 

* Show the exact error message you are receiving (copy and paste it); or
* Clearly state the undesired behavior (and state the expected behavior)
Undefined symbols for architecture x86_64:
  "CryptoPP::ProxyFilter::IsolatedFlush(bool, bool)", referenced from:
      vtable for CryptoPP::SimpleProxyFilter in hashTest-30cbcf.o
...
  "non-virtual thunk to CryptoPP::BufferedTransformation::GetMaxWaitObjectCount() const", referenced from:
      vtable for CryptoPP::Sink in hashTest-30cbcf.o
      vtable for CryptoPP::Bufferless<CryptoPP::Filter> in hashTest-30cbcf.o
      vtable for CryptoPP::Unflushable<CryptoPP::Filter> in hashTest-30cbcf.o
      vtable for CryptoPP::SimpleProxyFilter in hashTest-30cbcf.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by noloader** [comment]
`hashTest-30cbcf` is not part of Crypto++.

You should ask questions on the mailing list.

**Comment by devharsh** [comment]
I am unable to compile this example HMAC code (https://cryptopp.com/wiki/HMAC) as it throws a symbol not found an error. I am using Apple clang version 12.0.0 (clang-1200.0.32.29), could this be an issue as on the document page it says only upto Apple Clang 9.3 is supported?

**Comment by devharsh** [comment]
getting the same issue for Crypto++ 8.4.0 on Ubuntu VM
$ g++ --version
g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

/usr/bin/ld: /tmp/cczO6BH2.o: in function `CryptoPP::IteratedHashWithStaticTransform<unsigned int, CryptoPP::EnumToType<CryptoPP::ByteOrder, 1>, 64u, 20u, CryptoPP::SHA1, 0u, false>::HashEndianCorrectedBlock(unsigned int const*)':
hashMAC.cpp:(.text._ZN8CryptoPP31IteratedHashWithStaticTransformIjNS_10EnumToTypeINS_9ByteOrderELi1EEELj64ELj20ENS_4SHA1ELj0ELb0EE24HashEndianCorrectedBlockEPKj[_ZN8CryptoPP31IteratedHashWithStaticTransformIjNS_10EnumToTypeINS_9ByteOrderELi1EEELj64ELj20ENS_4SHA1ELj0ELb0EE24HashEndianCorrectedBlockEPKj]+0x32): undefined reference to `CryptoPP::SHA1::Transform(unsigned int*, unsigned int const*)'
/usr/bin/ld: /tmp/cczO6BH2.o: in function `CryptoPP::Unflushable<CryptoPP::Filter>::Flush(bool, int, bool)':
hashMAC.cpp:(.text._ZN8CryptoPP11UnflushableINS_6FilterEE5FlushEbib[_ZN8CryptoPP11UnflushableINS_6FilterEE5FlushEbib]+0x42): undefined reference to `CryptoPP::DEFAULT_CHANNEL[abi:cxx11]'
collect2: error: ld returned 1 exit status

**Comment by noloader** [comment]
Please ask questions on the mailing list.

**Comment by devharsh** [comment]
figured it out.. I was using -lcrypto flag instead of -lcryptopp.. thank you for your time 👍
