### ISSUE TITLE
eccrypto.h duplicated within itself?

### ISSUE THREAD

**Issue by denisbider** [weidai11/cryptopp#101]
Is there any reason why eccrypto.h appears to contain two copies of itself - with second copy starting from line 337?

https://github.com/weidai11/cryptopp/blob/master/eccrypto.h#L338

**Comment by noloader** [comment]
Thant is weird... It was not present in [eccrytpo.h 5.6.2](https://www.cryptopp.com/docs/ref562/eccrypto_8h_source.html). I'm guessing its from the VM copy/paste fiasco experienced around the time we released 5.6.3 (i.e., its my fault).

Do you want to handle it, or do you want me to clear it?

**Comment by DevJPM** [comment]
> I'm kinda befuddled we did not get a warning or a compile failure from it

It's a complete copy, including the double-include guard. So the #ifndef CRYPTOPP_ECCRYPTO_H "saw" that CRYPTOPP_ECCRYPTO_H was already defined (line 2) and so it didn't ever actually include the second copy of the file. -> No Harm could have been caused by this :)

**Comment by denisbider** [comment]
The files are *mostly* identical, but not completely. Diff:

```
--- a/eccrypto-bottom.cpp
+++ b/eccrypto-top.cpp
@@ -1,9 +1,12 @@
+// eccrypto.h - written and placed in the public domain by Wei Dai^M
+^M
+//! \file eccrypto.h^M
+//! \brief Classes and functions for Elliptic Curves over prime and binary fields^M
+^M
 #ifndef CRYPTOPP_ECCRYPTO_H
 #define CRYPTOPP_ECCRYPTO_H

-/*! \file
-*/
-
+#include "config.h"^M
 #include "cryptlib.h"
 #include "pubkey.h"
 #include "integer.h"
@@ -298,9 +301,9 @@ struct ECIES
        virtual ~ECIES() {}
 #endif

-#if (CRYPTOPP_GCC_VERSION >= 40500) || (CRYPTOPP_CLANG_VERSION >= 20800)
-} __attribute__((deprecated ("ECIES will be changing in the near future due to (1) an implementation bug and (2) an int
erop issue")));
-#elif (CRYPTOPP_GCC_VERSION)
+#if (CRYPTOPP_GCC_VERSION >= 40500) || (CRYPTOPP_CLANG_VERSION >= 30000) ^M
+} __attribute__((deprecated ("ECIES will be changing in the near future due to (1) an implementation bug and (2) an int
erop issue.")));^M
+#elif (CRYPTOPP_GCC_VERSION )^M
 } __attribute__((deprecated));
 #else
 };
```
The bottom version has `CRYPTOPP_CLANG_VERSION >= 20800`, whereas the top version has `CRYPTOPP_CLANG_VERSION >= 30000`.

The bottom part version appears to be more recent, so I removed the bottom part but applied this update to the top part.
