### ISSUE TITLE
[Bug] Possible copy-paste error in bench3.cpp:429

### ISSUE THREAD

**Issue by Scr3amer** [weidai11/cryptopp#1013]
I am a total beginner in crypto so I can definitely be wrong. I was exploring the source code to understand how to properly use the library and RFC6979 to sign a buffer and I noticed something in the file bench3.cpp

https://github.com/weidai11/cryptopp/blob/1a5346c6c797b585dbc761c0d5c93c0073dee843/bench3.cpp#L429

It is written
    
    ECDSA_RFC6979<ECP, SHA1>::Verifier spub2(spriv);
   
But it feels to me it should be spriv2 instead of spriv.

Am I missing something ?

**Comment by noloader** [comment]
> Am I missing something ?

It does not matter for the benchmarks.

> to understand how to properly use the library and RFC6979 to sign a buffer

The wiki is stuffed full of examples. https://www.cryptopp.com/wiki/Elliptic_Curve_Digital_Signature_Algorithm#Signers_and_Verifiers
