### ISSUE TITLE
Remove `*.cxx` from `.gitignore`

### ISSUE THREAD

**Issue by smessmer** [weidai11/cryptopp#1024]
See https://github.com/noloader/cryptopp-cmake/issues/66

I copied the cryptopp project into a subdirectory of my own project and `add_subdirectory` to crypto++ to use it as a dependency using `cryptopp-cmake`. Probably a somewhat common setup.
When trying to build my project, I got weird errors with missing `test_....cxx` files when trying to build my project. Turns out, this is because the `TestPrograms/**.cxx` files were missing from my repository because the crypto++ .gitignore (https://github.com/weidai11/cryptopp/blob/master/.gitignore#L6 ) prevented them from being added.

I assume other people will run into this issue as well and it's somewhat hard to figure out. Is it possible to remove `*.cxx` from the crypto++ `.gitignore`?

**Comment by noloader** [comment]
This should be cleared at [Commit c15aeaa7b5cd](https://github.com/weidai11/cryptopp/commit/c15aeaa7b5cd).

I hope this does not come back to bite us in the ass.
