### ISSUE TITLE
Source code organization

### ISSUE THREAD

**Issue by SoftCircuits** [weidai11/cryptopp#1028]
### Crypto++ Issue Report

Could you please reorganize the source code layout so that the core library source files have their own folder? It appears the source code is dumped in with test programs, benchmark programs, and other things that I'm not sure what they are.

Some people want to be able to build the files as part of their project rather than using your provided project files. Shouldn't this be easy to do?

Also, I tried building the library using cryptdll.vcproj that was inside vs2005.zip (using Visual Studio 2019). I got 907 warnings and one error.

**Comment by noloader** [comment]
Please have discussions on the Crypto++ Users List at http://groups.google.com/forum/#!forum/cryptopp-users.
