### ISSUE TITLE
Heap Corruption on Windows

### ISSUE THREAD

**Issue by damaex** [weidai11/cryptopp#103]
I'm facing a heap corruption if i compile the actual git Version on Windows x86 (using Visual Studio 2015 on Win10), see the minimal code example below!

```c++
#include <iostream>

#if defined(WIN32)
#include <windows.h>
#endif

#include "cryptopp/cryptlib.h"
#include "cryptopp/hex.h"
#include "cryptopp/sha.h"
#include "cryptopp/sha3.h"
#include "cryptopp/secblock.h"
#include "cryptopp/oids.h"
#include "cryptopp/asn.h"
#include "cryptopp/osrng.h"
#include "cryptopp/pwdbased.h"
#include "cryptopp/integer.h"
#include "cryptopp/aes.h"
#include "cryptopp/gcm.h"
#include "cryptopp/filters.h"
#include "cryptopp/eccrypto.h"
#include "cryptopp/dsa.h"
#include "cryptopp/queue.h"

int main(int argc, char* argv[]) {
    CryptoPP::OID CURVE = CryptoPP::ASN1::brainpoolP512r1();
    CryptoPP::AutoSeededRandomPool rng(true, 64);
    //everything fine
    CryptoPP::ECDH < CryptoPP::ECP >::Domain dh(CURVE);
    //heap corruption

    CryptoPP::SecByteBlock privatKey(dh.PrivateKeyLength()), publicKey(dh.PublicKeyLength());
    dh.GenerateKeyPair(rng, privatKey, publicKey);

    std::string priKey, pubKey;

    CryptoPP::HexEncoder hex(new CryptoPP::StringSink(priKey));
    hex.Put(privatKey.data(), privatKey.size());
    hex.MessageEnd();

    CryptoPP::HexEncoder hex2(new CryptoPP::StringSink(pubKey));
    hex2.Put(publicKey.data(), publicKey.size());
    hex2.MessageEnd();

    std::cout << "Private Key: " << priKey << std::endl << "Public Key: " << pubKey;

    return 0;
}
```

(link against *cryptlib.lib* and *ws2_32.lib*)

If i get it right the problem is the assignment in line 464 in the file *eccrypto.cpp* which happens to execute line 2951 in *integer.cpp*.

And there the **reg** value looks like this:

    reg	{m_alloc={...} m_size=3435973836 m_ptr=0x00000002 {???} }
    CryptoPP::SecBlock<unsigned int,CryptoPP::AllocatorWithCleanup<unsigned int,1> >

This then happens to be deallocated and there the heap corruption appears (see the m_ptr)!

All self tests with the cryptest.exe run through by the way.

**Comment by noloader** [comment]
Thanks @damaex . So I have good news and bad news.

The good news is I cannot duplicate it under GCC 5 or Visual Studio 2013. The bad news is I don't have Visual Studio 2015 to test on. My trial has expired.

-----

> All self tests with the cryptest.exe run through by the way.

Here's what I did to test it. I opened `test.cpp` and I added the following to the top of the file with the other includes:

    #include "oids.h"
    #include "eccrypto.h"

Then, inside `main`, *after* the `_CRTDBG_LEAK_CHECK_DF` and *before* the `RegisterFactories`, I added this:

    CryptoPP::OID CURVE = CryptoPP::ASN1::brainpoolP512r1();
    CryptoPP::AutoSeededRandomPool rng(true, 64);
    //everything fine
    CryptoPP::ECDH < CryptoPP::ECP >::Domain dh(CURVE);
    //heap corruption
    return 0;

The test ran fine and did not report any memory errors.

Can you perform the same test?

-----

This begs the question... How did you get to Visual Studio 2015? Did you run `VCUpgrade` on the VS2005 solution and project files? Or did you use the solution and project files from `vs2010.zip`?

-----

I don't want to dismiss this report prematurely because Microsoft is still cutting in support for C++11, and this could be due to one of their changes.

**Comment by DevJPM** [comment]
> All self tests with the cryptest.exe run through by the way.

Well. The Self-Tests should test for this case and in fact I think they do.

`CryptoPP::ECDH < CryptoPP::ECP >::Domain dh(CURVE);`

The code actually constructs `ECDH<ECP>::Domain ecdhc(ASN1::secp192r1());` in validat2.cpp

@damaex  Is your issue reproducable when using other curves (such as Brainpool P-256, NIST P-256)?

@noloader, I don't know if you want to hear that, but I guess he just installed VS 2015 community edition and then registered it with Microsoft (it doesn't even need to be a @outlook or @hotmail or something adress).

**Comment by noloader** [comment]
> I don't know if you want to hear that, but I guess he just installed VS 2015 community edition and then registered it with Microsoft (it doesn't even need to be a @outlook or @hotmail or something adress).

Microsoft has my account locked, and there's nothing I can do. I tried to have it unlocked three or four years ago, but there are no support paths. Unless, of course, you can provide a support path to have the account unlocked.

But thanks for your input.

**Comment by noloader** [comment]
@damaex - were you able to duplicate the results within the cryptest program?

**Comment by damaex** [comment]
First of all, i used the projects from the *vs2010.zip* and changed the platformtoolset to v140.

Now i tried as you said and started the changed test in *test.cpp* from within the *cryptest* solution. No problem occurred there.

Then i updated Visual Studio 2015 to **Update 1**, still same problem on my mini test solution which has just 2 projects (the test console application project and the cryptlib project). Then i tried different curves and it appears on all of them. My minimal example shrinked to:

````c++
int main(int argc, char* argv[]) {
	CryptoPP::ECDH<CryptoPP::ECP>::Domain ecdhc(CryptoPP::ASN1::secp192r1());
	return 0;
}
````

Which, as said, still crashes in my project. But now (with Update 1) in file words.h in line 11 with *unhandled exception: read access violation on value X*.

I'm using Visual Studio 2015 since last years summer (never had a problem) and this problem occurred shortly before christmas 2015 after an git pull update from cryptopp (github).

Next step:
If i create a new solution with new console project and add cryptlib everything works fine with my example so it is probably one stupid setting in the project which i'm unable to find, damn it.

So, now i created the projects related to cryptopp new and readded them to the solution. Now it's working, except the CppUnitTest project, which is still crashing with the above message.

In the end it looks like the problem is not related to cryptopp itself, more to the projects setting depending on it. But it's still strange that i always end up at the same position with the same error message, even if i try different tests or functions.

**Comment by noloader** [comment]
> more to the projects setting depending on it. But it's still strange that i always end up at the same position with the same error message, even if i try different tests or functions.

Of course... 

My guess is the *new* solution you created is using a different C++ Runtime. That's why I was interested in test results from the cryptest program.

*If* its related to C++ Runtimes, then have a look at [Dynamic Runtime Linking](https://www.cryptopp.com/wiki/Visual_Studio#Dynamic_Runtime_Linking) on the [Visual Studio](https://www.cryptopp.com/wiki/Visual_Studio) wiki page.

The short of it is: Crypto++ uses static runtime linking (`/MT` and `/MTd`), while your new projects likely use dynamic runtime linking (`/MD` and `/MDd`). Or maybe Crypto++ and your project use the same, but Qt or MFC is using a different one.

**Comment by damaex** [comment]
All these i checked, and the entire solution uses /MTd.

Right now it looks like the problem happens to be linking openssl and cryptopp in the same executable. Which with the same build process worked for already 2 years.

**Comment by noloader** [comment]
>  linking openssl and cryptopp in the same executable. Which with the same build process worked for already 2 years

Oh, that's kind of interesting... If you don't mind me asking, why do you use both?

(I realize OpenSSL provides TLS; but its not clear to me what it lacks such that you would need Crypto++).

**Comment by damaex** [comment]
Basically i'm using Crypto++ for all encryption (what is the main part) because i like the c++ way, but i need openssl for sqlcipher and some other small stuff.

**Comment by noloader** [comment]
@damaex - so is there anything we can do here to help you or other users?

**Comment by noloader** [comment]
It appears there's nothing to do here for us.
