### ISSUE TITLE
"Broken module found" on Clang 7

### ISSUE THREAD

**Issue by smessmer** [weidai11/cryptopp#1031]
### Crypto++ Issue Report

When updating the [CryFS](https://github.com/cryfs/cryfs) dependency from CryptoPP 8.2 to 8.5, I get a compiler error on Clang 7. It only happens on Clang 7 and only happens when optimizations are enabled. 

Error message:
```
Alias must point to a definition
void (%"class.CryptoPP::IteratedHashBase"*)* @_ZN8CryptoPP16IteratedHashBaseImNS_18HashTransformationEED1Ev
Alias must point to a definition
void (%"class.CryptoPP::IteratedHashBase.266"*)* @_ZN8CryptoPP16IteratedHashBaseIjNS_18HashTransformationEED1Ev
LLVM ERROR: Broken module found, compilation aborted!
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```
Full build log: https://pastebin.com/BpF3CZP9

CryptoPP version: 8.5
OS: Happens on both Ubuntu 18.04 and 20.04
Compiler: Error happens on Clang 7. Newer versions of Clang don't trigger the error and neither GCC 7 or later. I haven't tested older Clang or GCC versions.
Build settings: Happens with build settings `RelWithDebInfo` and `Release`. Building with `Debug` doesn't trigger the error.

In case this doesn't repro when building only CryptoPP, the steps to repro would be to take the https://github.com/cryfs/cryfs/tree/feature/cryptopp850 branch from CryFS (which is the branch with the CryptoPP upgrade) and build CryFS.

**Comment by noloader** [comment]
This looks like https://reviews.llvm.org/D24682. Can you update the compiler?

**Comment by smessmer** [comment]
I'm using clang 7.0.1-12, which is the newest version of clang 7 available on Ubuntu 18.04 or 20.04. I'm using thin-lto, I'm not using bitcode. The issue happens with CryptoPP 8.5 only, CryptoPP 8.2 builds fine.

It could indeed be a compiler bug. Is there maybe a way to workaround it in the crypto++ library?

**Comment by noloader** [comment]
You will probably have to skip LTO. We know there's problems on several platforms.  We also know there's bad link optimizations when LTO is used. Also see https://www.cryptopp.com/wiki/Link_Time_Optimization.

**Comment by noloader** [comment]
I installed `clang-7` on Ubuntu 20.

The build is OK with just Clang-7. The self tests are OK with just Clang-7.

```
 CXX=clang++-7 make -j 12
```

This causes a link problem.

```
CXX=clang++-7 CXXFLAGS="-DNDEBUG -g2 -O3 -flto=thin" make -j 12
...
/usr/bin/ld: ./libcryptopp.a: error adding symbols: archive has no index; run ranlib to add one
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [GNUmakefile:1450: cryptest.exe] Error 1
```

I think you are going to have to forgo LTO.

**Comment by smessmer** [comment]
Thanks, disabling LTO fixed it.

**Comment by yuanfang-chen** [comment]
Newest report is here https://bugs.llvm.org/show_bug.cgi?id=49009.

The workaround is to move `virtual IteratedHashBase::~IteratedHashBase();` definition to `iterhash.cpp` .
