### ISSUE TITLE
License wording problem

### ISSUE THREAD

**Issue by sobczyk** [weidai11/cryptopp#1036]
Clarify "GPL3" mentioned in `gf2n_simd.cpp`

The file header states that:
> //    optimization so the IACR paper is useful.  However, the code is GPL3
> //    and toxic for some users of the library...

And some lawyers think the cryptopp code is GPL3...

Maybe wording change would be helpful, like

> However, the **IACR** code ... and toxic for some users of the library, **so it was not used here**`

**Comment by noloader** [comment]
Thanks, done.
