### ISSUE TITLE
Changes in Speck/Simon 128 with OFB/OCS mode from Cryptopp8.0 to Cryptopp8.5

### ISSUE THREAD

**Issue by ISMaxM** [weidai11/cryptopp#1037]
I updated Cryptopp from version 8.0 to 8.5 and some of my tests failed.  The result of Speck/Simon 128 with OFB/OCS modes changed.

There's no tests of theses modes in the Speck/Simon tests files.

**Comment by noloader** [comment]
Sorry about that @ISMaxM,

That sounds like the bug we fixed at [GH #1010](https://github.com/weidai11/cryptopp/issues/1010). The 1010 issue was against HIGHT, but it applied to any cipher or mode using `AdditiveCipherTemplate::ProcessData`.

I don't have Simon or Speck test vectors for OFB mode. The authors only provide ECB mode and CTR mode.
