### ISSUE TITLE
Crypto++ 8.6 fails tests with g++ -O0 -m32 (GCC version 8.3.0)

### ISSUE THREAD

**Issue by RazviOverflow** [weidai11/cryptopp#1040]
### Crypto++ 8.6 does not pass building tests when compiled with g++ -O0 -m32 

* State the operating system and version (Ubuntu 17 x86_64, Windows 7 Professional x64, etc)
```
$ uname -a
Linux rdp05 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux

$ lsb_release -a
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

$ lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
Address sizes:       36 bits physical, 48 bits virtual
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               58
Model name:          Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
Stepping:            9
CPU MHz:             2892.725
CPU max MHz:         3200.0000
CPU min MHz:         1600.0000
BogoMIPS:            6385.53
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            6144K
NUMA node0 CPU(s):   0-3
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm arat pln pts
```
* Version of GCC
```
$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 8.3.0-6' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.3.0 (Debian 8.3.0-6)
```
* State the version of the Crypto++ library (Crypto++ 7.0, Master, etc)
I'm using Crypto++ 8.5 (https://github.com/weidai11/cryptopp/commit/d4975aa6081947b3bbdd73818bc9825550574dd3))
* State how you built the library (Makefile, Cmake, distro, etc)
The commands I use to build and compile the library are:
```
$ export CXXFLAGS="-DNDEBUG -g2 -O0"
$ export CXX="g++ -m32"
$ make -j 4 
$ make test (<- this one fails)
```
* Show the exact error message you are receiving (copy and paste it)
```
$ make test
[...]
Oops!  Not all tests passed.
Seed used was 1621409054
```

```
$ ./cryptext.exe tv all
[...]
Tests complete. Total tests = 11260. Failed tests = 23.
SOME TESTS FAILED!
```
```
$ ./cryptext.exe tv lea
[...]
Test FAILED.
Skipping to next test.

Tests complete. Total tests = 90. Failed tests = 21.
SOME TESTS FAILED!
```
* Clearly state the undesired behavior (and state the expected behavior)
There are several tests that fail when I build and compile the library with g++ -m32 -O0. Surprisingly enough, there are no problems, that is, all the tests are passing, when I build and compile it with any other optimization flag g++ -m32 -O{1|2|3|s|fast}. As stated above, I'm using a x86_64 machine and the target is x86_32 (-m32).

**Comment by noloader** [comment]
Thanks @RazviOverflow,

I'm having trouble setting up a test environment. Ubuntu 17 repos are missing release files so I can't install or update software. Ubuntu 18 is missing some ia32-lib/i386 packages, so I can't get everything installed I need.

Do you have any suggestions for a test environment?

**Comment by noloader** [comment]
Thanks again @RazviOverflow,

So it looks like Ubuntu 18 also needed `gcc-multilib`, `gcc-7-multilib`, `g++-multilib`, and `g++-7-multilib`.

Testing at `-O0` produces the error, but `-O1` is OK. That looks like a compiler bug. Unfortunately I can't pinpoint what is wrong with the compiler. I won't be able to help with it.

I believe you have two choices. First, you can compile at `-O1` instead of `-O0`. Second, you can define `CRYPTOPP_DISABLE_LEA_SIMD` to avoid the SSSE3 code paths for the problem build.

A third choice, report the problem to the GCC folks, is not an option. If I am not mistaken, GCC 7 is no longer supported, so it will not be fixed.

The problem also looks a little larger than LEA. It looks like there is one failed self test for SIMON-128, and one failed self test for SM4. Because of the additional problems, I would probably avoid `-O0`.

**Comment by RazviOverflow** [comment]
Hello @noloader. 

Sorry for my late response.

As you already figured out, I needed to install gcc-multilib, gcc-7-multilib, g++-multilib, and g++-7-multilib in order to be able to cross compile on my Debian 10. Nothing else was needed.

Just like you said, there are a couple of tests outside the LEA test vector that also fail, SIMON-128 and SM4.

I was using `O0` because I wanted to benchmark the performance of the library with all 6 optimizations flags I earlier mentioned, but I will skip now that I know the problem is unlikely to be solved.

Thank you for your help and support.

**Comment by noloader** [comment]
> I was using O0 because I wanted to benchmark the performance of the library with all 6 optimizations flags I earlier mentioned, but I will skip now that I know the problem is unlikely to be solved.

To get a baseline, use `-DCRYPTOPP_DISABLE_ASM`. That ensures you get all C++ code.

**Comment by RazviOverflow** [comment]
By the way, you said GCC 7 is no longer supported, which is true, but I'm using GCC 8.3.0. Do you think it is worth trying a newer or the latest GCC version?

**Comment by noloader** [comment]
> I'm using GCC 8.3.0. Do you think it is worth trying a newer or the latest GCC version?

I'll probably be able to duplicate your results with GCC 8.3.

The problem we are going to encounter is, I won't be able to find a reproducer for a GCC bug report. About all you can do is give the GCC folks instructions to reproduce the issue using the entire library. But the GCC folks rarely work on bugs like that.

**Comment by RazviOverflow** [comment]
All right. 

Even though my problem persists, I consider this issue closed since it is a problem related to GCC rather than Crypto++.

Thank you.
