### ISSUE TITLE
ChaCha20 IV key is not installed correctly

### ISSUE THREAD

**Issue by goodwinxp** [weidai11/cryptopp#1042]
Its happens because use(1) pointer to IV key, that was obtained from the function(2). This(2) function return(3) a pointer to the data in a local variable(4), which was destroyed after exit from function(2).
At this moment(1), the pointer already indicates data different from the set IV key.

Code snippet:
```
            using namespace CryptoPP;
            SecByteBlock key(ChaCha::KEYLENGTH_MULTIPLE), iv(ChaCha::IV_LENGTH);
            AutoSeededRandomPool prng;
            prng.GenerateBlock(key, key.size());
            prng.GenerateBlock(iv, iv.size());
            const AlgorithmParameters params = MakeParameters(Name::Rounds(), 8)
                (Name::IV(), ConstByteArrayParameter(iv, 8, true));
            ChaCha::Encryption encryptor;
            encryptor.SetKey(key, key.size(), params);
```
(1) https://github.com/weidai11/cryptopp/blob/1124a3d1fe8ac0c59acaf75f087ee4bd44a8b0bf/strciphr.cpp#L39
(2) https://github.com/weidai11/cryptopp/blob/1124a3d1fe8ac0c59acaf75f087ee4bd44a8b0bf/cryptlib.cpp#L107
(3) https://github.com/weidai11/cryptopp/blob/1124a3d1fe8ac0c59acaf75f087ee4bd44a8b0bf/cryptlib.cpp#L118
(4) https://github.com/weidai11/cryptopp/blob/1124a3d1fe8ac0c59acaf75f087ee4bd44a8b0bf/cryptlib.cpp#L109

Operating system and version: Windows 7/Windows 10. x86/64 both.
Version of the Crypto++ library: master
Built the library: CMake

**Comment by noloader** [comment]
Thanks @goodwinxp,

The `iv` byte array only exists at `SecByteBlock iv(ChaCha::IV_LENGTH);`. The `ConstByteArrayParameter(iv, 8, true)` and `ConstByteArrayParameter ivWithLength;` are shallow copies. They only hold a pointer and length, which points back to `SecByteBlock iv(ChaCha::IV_LENGTH);`.

**Comment by goodwinxp** [comment]
@noloader thanks for your explain, but i use **deep** copy in `ConstByteArrayParameter` for pass IV key. If i use shallow copy then IV key is correct after exit from `SimpleKeyingInterface::GetIVAndThrowIfInvalid`
If i use **deep** copy then `ConstByteArrayParameter ivWithLength;` hold deep copied data and return pointer on `m_block`, but it will be destroyed after exiting the function cause its local variable. Thus, incorrect data will be used as a IV key.
Unfortunately, i have no idea how to demonstrate this issue by code. I used debugging for investigate this issue.
