### ISSUE TITLE
Can you simplify the use of the library?

### ISSUE THREAD

**Issue by tracer1808** [weidai11/cryptopp#1051]
I don't know if this is the place for this topic, but I recently noticed this Crypto++ wrapper:
https://www.codeproject.com/Articles/89935/SpaceCrypto-A-Simple-Crypto-Wrapper

and I must agree the code in this library is fairly complicated for a beginner to use. For example, 

```
CryptoPP::SHA1 sha1;
std::string source = "ABC123";  
std::string hash = "";
CryptoPP::StringSource(source, true, new CryptoPP::HashFilter(sha1, new CryptoPP::HexEncoder(new CryptoPP::StringSink(hash))));
```

This is just way to much for a simple hash function to use as there are so many types and functions involved (`CryptoPP::SHA1`, `CryptoPP::StringSource`, `CryptoPP::HashFilter`, `CryptoPP::HexEncoder`, `CryptoPP::StringSink`). 

I would suggest you to try and simplify the usage of this library with more direct methods like:

```
sha1.HashString("input string");
sha1.HashFile("inputFile.dat");
sha1.HashBytes(&someData); 
```

where you can eventually have default arguments or many different overloads of these methods. Similarly with the symetric and asimetric algorithms, providing direct methods to Encrypt/Decrypt strings, files and bytes (streams), create key pairs etc. In essence, a base class with these virtual functions could probably do the trick.

**Comment by noloader** [comment]
You might find [Botan](https://github.com/randombit/botan) better suites your taste.
