### ISSUE TITLE
pem-com.h missing from PEM pack archive

### ISSUE THREAD

**Issue by mariosangiorgio** [weidai11/cryptopp#106]
I'm trying to use the PEM pack available on the wiki https://www.cryptopp.com/wiki/PEM_Pack but it's missing the pem-com.h file.

Would it be possible to update it? I understand the PEM pack is not officially part of Crypto++ but I thought someone might have it since it's hosted on the official wiki

**Comment by noloader** [comment]
> Would it be possible to update it? 

Done. Thanks for reporting.

The new ZIP has been uploaded. The missing file was even dated October 19, like the other PEM ones.

**Comment by pravic** [comment]
Why PEM support is not a part of library?

**Comment by anonimal** [comment]
@pravic I believe that questions are encouraged to be sent to the [mailing list](https://cryptopp.com/#lists) instead of github.
