### ISSUE TITLE
GenerateRandomWithKeySize() crashing

### ISSUE THREAD

**Issue by Ou7law007** [weidai11/cryptopp#1063]
It took me a while to narrow it down to these two things: (each cause a crash independently from each other)
1. If you call GenerateRandomWithKeySize() from a constructor. (creating void init method solves it)
2. This one is weirder, GenerateRandomWithKeySize() crashes if std::this_thread::sleep_for(std::chrono::seconds(2)); is called before it. If you call std::this_thread::sleep_for(std::chrono::microseconds(1));, it DOES NOT crash. I'm not sure at which x std::chrono::seconds(x) it doesn't crash or crash, I just tried the 2 above and the first crashes and the second doesn't!!!!
In my case, the call to sleep was even in a different function not even directly before GenerateRandomWithKeySize()

Compiler: msvc LLVM - clang-cl x64 for and on Windows 10 my windows and compiler are up to date
Using Visual Studio 2019 (v142) instead of LLVM does not solve the problem

Cheers

**Comment by noloader** [comment]
We don't really support LLVM on Windows. There are too many problems with it (as you can see). Uri and I have spent way too much time submitting bug reports that are not acted upon and trying to work around the problems.

You should file bug reports with the LLVM folks at https://bugs.llvm.org.

**Comment by Ou7law007** [comment]
Did you miss this part "Using Visual Studio 2019 (v142) instead of LLVM does not solve the problem"?
Other than that, and since https://github.com/weidai11/cryptopp/issues/147#issuecomment-854126230 was fixed, CryptoPP in LLVM has been working really well for me.

**Comment by noloader** [comment]
Based on your comments in (2), it sounds like you have a race condition in your code.
