### ISSUE TITLE
ChaCha and incorrect result when using AVX2

### ISSUE THREAD

**Issue by noloader** [weidai11/cryptopp#1069]
Reported on the mailing list at [Flipped bit in chacha encrypted file, avx vs sse](https://groups.google.com/g/cryptopp-users/c/07GHmO6UOEk). The following test script produces different results pivoting around AVX2. The test data file `run_459_file_76.bin` is significant.

```bash
#!/usr/bin/env bash

make distclean &>/dev/null

CXXFLAGS="-DNDEBUG -g2 -O3 -std=c++17" make -j 5

wget -O main.cxx --quiet https://raw.githubusercontent.com/austin-clifton/cryptopp-chacha-asm-test/main/src/main.cpp

wget -O run_459_file_76.bin --quiet https://github.com/austin-clifton/cryptopp-chacha-asm-test/blob/main/run/run_459_file_76.bin?raw=true

sed -i 's/cryptopp\///g' main.cxx

g++ -DNDEBUG -g2 -O3 -std=c++17 -I. main.cxx ./libcryptopp.a -o main.exe

./main.exe
```

Here are the results from several different machines. I believe the C++ and SSE2 one `8F16077454F8477594CAD4304126B0A6F30C8C4D2536E2441FFFD320656E1DF1` is correct. The AVX2 one is incorrect.

```txt
Core i7-8700 (Intel, AVX2, no SHA):
sha256: 0FC0FADCDF82770086C9DA8513A16FC785620D7B1C187CDD828E433EB0979847
encsha: 6FBEE484EE64A2AB02235DDF29CA0B61EE3B811D227C2729836D3BD6161C9B18

Celeron J3455 (Intel, no AVX, SHA):
sha256: 0FC0FADCDF82770086C9DA8513A16FC785620D7B1C187CDD828E433EB0979847
encsha: 8F16077454F8477594CAD4304126B0A6F30C8C4D2536E2441FFFD320656E1DF1

Ryzen 3 3300U (AMD, AVX2, SHA)
sha256: 0FC0FADCDF82770086C9DA8513A16FC785620D7B1C187CDD828E433EB0979847
encsha: 6FBEE484EE64A2AB02235DDF29CA0B61EE3B811D227C2729836D3BD6161C9B18

CRYPTOPP_DISABLE_ASM:
sha256: 0FC0FADCDF82770086C9DA8513A16FC785620D7B1C187CDD828E433EB0979847
encsha: 8F16077454F8477594CAD4304126B0A6F30C8C4D2536E2441FFFD320656E1DF1
```

**Comment by noloader** [comment]
We lifted the AVX2 implementation from Botan. See [chacha_avx.cpp](https://github.com/weidai11/cryptopp/blob/master/chacha_avx.cpp).

The bug is kind of difficult to tickle. Austin Clifton , the fellow who posted the issue, had to jump through some hops to get a partial reproducer. The files of interest are from his github are:

* [main.cpp](https://raw.githubusercontent.com/austin-clifton/cryptopp-chacha-asm-test/main/src/main.cpp)
* [run_459_file_76.bin](https://github.com/austin-clifton/cryptopp-chacha-asm-test/blob/main/run/run_459_file_76.bin?raw=true)

The data file `run_459_file_76.bin` is hashed with SHA256, then encrypted with ChaCha.

Ping @randombit.

**Comment by randombit** [comment]
Sorry @noloader there was a carry bug here which was fixed in https://github.com/randombit/botan/commit/a30ca750648bdb28f7d78ad8b6a17821e8917eb2
```
--- a/src/lib/stream/chacha/chacha_avx2/chacha_avx2.cpp
+++ b/src/lib/stream/chacha/chacha_avx2/chacha_avx2.cpp
@@ -23,10 +23,12 @@ void ChaCha::chacha_avx2_x8(uint8_t output[64*8], uint32_t state[16], size_t rou
    const __m256i state2 = _mm256_broadcastsi128_si256(_mm_loadu_si128(state_mm + 2));
    const __m256i state3 = _mm256_broadcastsi128_si256(_mm_loadu_si128(state_mm + 3));
 
-   const __m256i CTR0 = _mm256_set_epi32(0, 0, 0, 0, 0, 0, 0, 4);
-   const __m256i CTR1 = _mm256_set_epi32(0, 0, 0, 1, 0, 0, 0, 5);
-   const __m256i CTR2 = _mm256_set_epi32(0, 0, 0, 2, 0, 0, 0, 6);
-   const __m256i CTR3 = _mm256_set_epi32(0, 0, 0, 3, 0, 0, 0, 7);
+   const uint32_t C = 0xFFFFFFFF - state[12];
+
+   const __m256i CTR0 = _mm256_set_epi32(0, 0,     0, 0, 0, 0, C < 4, 4);
+   const __m256i CTR1 = _mm256_set_epi32(0, 0, C < 1, 1, 0, 0, C < 5, 5);
+   const __m256i CTR2 = _mm256_set_epi32(0, 0, C < 2, 2, 0, 0, C < 6, 6);
+   const __m256i CTR3 = _mm256_set_epi32(0, 0, C < 3, 3, 0, 0, C < 7, 7);
```

My bad should have let you know when I found it.

**Comment by noloader** [comment]
Thanks @randombit. I hope I did not miss the change in the past.

The change tested OK. Cleared at [Commit 20962baf4440](https://github.com/weidai11/cryptopp/commit/20962baf4440).
