### ISSUE TITLE
Add one line code to allow the data sink created on stack

### ISSUE THREAD

**Issue by asbai** [weidai11/cryptopp#1078]
If I understand correctly, the data sink in crypto++ needs to be created in the heap every time it is used. Just like this:

```C++
// ...
		StreamTransformationFilter iDecryptor(*pDec, new StringSink(stResult));  // <-- new sink every time
		iDecryptor.Put(static_cast<const BYTE*>(pData), nByteSize);
		iDecryptor.MessageEnd();

// ... use stResult
```

Frequent new and delete operations have a certain degree of performance damage to the processing of a **large number of small packets in a multi-threaded environment**. 

We can add a simple function to the Filter class:
```C++
BufferedTransformation* Deprive(void) { return m_attachment.release(); } 
```

To eliminate all these new and delete operations:
```C++
// ...
		ByteExSink skResult(btResult);  // <--- create on stack
		StreamTransformationFilter iDecryptor(*pDec, &skResult);
		try
		{
			iDecryptor.Put(static_cast<const BYTE*>(pData), nByteSize);
			iDecryptor.MessageEnd();
		}
		catch (...)
		{
			iDecryptor.Deprive(); // <--- prevent member_ptr delete it
			throw;
		}
		iDecryptor.Deprive(); // <--- prevent member_ptr delete it
// ...
```

In our single-threaded test, the above optimization can bring about 8.5% performance improvement. The performance of multi-threaded testing can be increased by about 30%.

**Comment by noloader** [comment]
```
char buf[512];
ArraySink sink(buf, sizeof(buf)); // <---- create ArraySink ON STACK, NOT ON HEAP
StreamTransformationFilter iDecryptor(*pDec, &sink);
```

In this case, use a `Redirector`:

```
char buf[512];
ArraySink sink(buf, sizeof(buf));
StreamTransformationFilter iDecryptor(*pDec, new Redirector(sink));
```

The `Redirctor` stops the ownership chain. Dosc at https://www.cryptopp.com/wiki/Redirector.
