### ISSUE TITLE
`WINVER` usage fails when not defined with `-Wundef`

### ISSUE THREAD

**Issue by mattfbacon** [weidai11/cryptopp#1084]
- OS: Arch Linux
- Version: main branch
- How built: CMake
- Example command line for CryptoPP source file:
```bash
/usr/lib/ccache/bin/g++ -DCMAKE_INTDIR=\"Debug\" -march=skylake -O2 -pipe -Wall -Wextra -Wno-unknown-pragmas -Wcpp -Wshadow -Wundef -fno-common -Wconversion -Wno-enum-compare -frtti -fexceptions -fdiagnostics-color -g -fno-omit-frame-pointer -fstack-protector-strong -O0 -ggdb3 -Werror -Wfatal-errors -Wno-error=cpp -Wno-error=pedantic -finstrument-functions -fsanitize=address -fsanitize=undefined -fsanitize=leak -D_GLIBCXX_DEBUG -fPIC -std=gnu++20 -MD -MT lib/cryptopp/cryptopp/CMakeFiles/cryptopp-object.dir/Debug/xts.cpp.o -MF lib/cryptopp/cryptopp/CMakeFiles/cryptopp-object.dir/Debug/xts.cpp.o.d -o lib/cryptopp/cryptopp/CMakeFiles/cryptopp-object.dir/Debug/xts.cpp.o -c /home/matt/Desktop/code/cpp/stag/lib/cryptopp/cryptopp/xts.cpp
```
- Example command line for linking: Not provided because the link stage is not reached
- Error message (one of many):
```
In file included from /home/matt/Desktop/code/cpp/stag/lib/cryptopp/cryptopp/config_asm.h:26,
                 from /home/matt/Desktop/code/cpp/stag/lib/cryptopp/cryptopp/config_align.h:25,
                 from /home/matt/Desktop/code/cpp/stag/lib/cryptopp/cryptopp/config.h:22,
                 from /home/matt/Desktop/code/cpp/stag/lib/cryptopp/cryptopp/pch.h:14,
                 from /home/matt/Desktop/code/cpp/stag/lib/cryptopp/cryptopp/xts.cpp:10:
/home/matt/Desktop/code/cpp/stag/lib/cryptopp/cryptopp/config_os.h:85:40: error: "WINVER" is not defined, evaluates to 0 [-Werror=undef]
   85 | # if !defined(_USING_V110_SDK71_) && ((WINVER >= 0x0602 /*_WIN32_WINNT_WIN8*/) || \
```

- Expected behavior: macro is checked for being defined before it's used, so the program compiles properly
- Undesired behavior: the program compiles without `-Wundef`, but creates warnings (errors with `-Werror`) with it.

This seems relatively easy to fix, so I'll probably make a PR.

**Comment by noloader** [comment]
Thanks @mattfbacon,

Correct me if I am wrong, but undefined macros evaluate to 0. That is consistent with the use `WINVER >= 0x0602`. `0` will never be greater than `0x0602`, so the code path is not activated.

Perhaps I am missing something?

**Comment by mattfbacon** [comment]
You are correct that they evaluate to zero. However it is generally considered good practice to not evaluate undefined macros. That said, having looked through the codebase, it seems like more trouble than it's worth to add `defined` checks everywhere. Additionally, it appears that, as long as the source files are compiled without `-Wundef`, the header files can be included in a project with `-Wundef` enabled. I rewrote my `CMakeLists.txt` and it compiles just fine. I'm going to close this.
