### ISSUE TITLE
Unable to save file with PEM-Pack feature

### ISSUE THREAD

**Issue by apolo49** [weidai11/cryptopp#1089]
Executive Summary
---

* OS - Windows 11 Home x64
* Version - Crypto++ 1.8.0#1
* Build - VCPKG
* Error Message:
```
Unhandled exception at 0x7536EA32 in <name>.exe: Microsoft C++ exception: CryptoPP::FileStore::OpenErr at memory location 0x0058F83C.
```

---

Description
---

This exception occurs in files.cpp after line 91: `m_stream = m_file.get()`
This results in me being unable to create files using FileSource - in my case at least.
The exception in question isn't captured by try/catch and instead just errors and crashes.

My relevant code:
```
void dCrypto::RSAKeyPair::saveKeys()
{
	CryptoPP::FileSource fspub("./ire.pub", true);
	CryptoPP::FileSource fspriv("./ire.priv", true);
	try {
		PEM_Save(fspub, this->publicKey);
		PEM_Save(fspriv, this->privateKey);
	}
	catch (CryptoPP::FileStore::OpenErr &e) {
		std::cout << strerror(errno) << "\n";
		std::cout << e.what() << std::endl;
		exit(-1);
	}

}
```

Stacktrace, line by line:
* `dCrypto::RSAKeyPair::saveKeys` - line 20 - `CryptoPP::FileSource fspub("./ire.pub", true);`
* [`files.h`](../blob/master/files.cpp#L109-L110) - line 109/110 - `FileSource(const char *filename, bool pumpAll, BufferedTransformation *attachment = NULLPTR, bool binary=true)
		: SourceTemplate<FileStore>(attachment) {SourceInitialize(pumpAll, MakeParameters(Name::InputFileName(), filename)(Name::InputBinaryMode(), binary));}`

* [`filters.h`](../blob/master/filters.h#L1418) - line 1418 - `IsolatedInitialize(parameters);`

* [`files.cpp`](../blob/master/files.cpp#L92) - line 92 - closes module `FIleStore::StoreInitialize`

I have tried making the files one at a time and not initialising the FileSources until the other has completed, but neither works and still results in the same exception.
I have also tried downgrading (through vcpkg) to 8.2.0-2 and 8.5.0, however neither solves the issue.

---

I am unsure whether this is an issue with PEM-Pack or Crypto++, however all the files seem to be Crypto++ files and are not included with PEM-Pack, so I concluded (correct or not) that this is most likely a Crypto++ issue.

**Comment by apolo49** [comment]
As an update, FileSink works as an alternative. However I still feel this issue is valid and should be address as it's either deprecated functionality or just not working.
I have not tested on other OSs or architectures.

**Comment by noloader** [comment]
Use a `FileSink`, not a `FileSource`.

Also see https://www.cryptopp.com/wiki/FileSink

**Comment by apolo49** [comment]
This seems to be avoiding broken functionality; this shouldn't be closed as this is still an issue when the intended use and functionality is broken.

**Comment by noloader** [comment]
What's broken? The best I can tell, you are using a `Source` where you should be using a `Sink`. The only thing that is broken is the test program.
