### ISSUE TITLE
version 8.6.0 FTBFS on armhf

### ISSUE THREAD

**Issue by gcsideal** [weidai11/cryptopp#1094]
OS is Linux, distribution is Ubuntu Jammy and Debian Sid.
cryptopp is official 8.6.0
Build is tried with Debian packaging tools, below Makefile is used.
Failing compiler invocation is the following.

```
g++ -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -pthread -g -O2 -ffile-prefix-map=/home/gcs/compile/libcrypto++-8.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -DNDEBUG -march=armv7-a -Wa,--noexecstack -c aes_armv4.S
cc1: error: '-mfloat-abi=hard': selected architecture lacks an FPU
```

It should build and provide the object file.
CPU is 'ARMv7 Processor rev 2 (v7l)', gcc --version displays:
gcc (Debian 11.2.0-13) 11.2.0

Proposed patch by Steve Langasek (steve.langasek@ubuntu.com) and confirmed fixing this issue on Debian/Sid:
```
--- a/GNUmakefile
+++ b/GNUmakefile
@@ -1174,11 +1174,11 @@
 # Also see https://www.cryptopp.com/wiki/Cryptogams.
 ifeq ($(IS_ARM32)$(IS_LINUX),11)
   ifeq ($(CLANG_COMPILER),1)
-    CRYPTOGAMS_ARMV4_FLAG = -march=armv7-a -Wa,--noexecstack
-    CRYPTOGAMS_ARMV4_THUMB_FLAG = -march=armv7-a -mthumb -Wa,--noexecstack
+    CRYPTOGAMS_ARMV4_FLAG = -march=armv7-a+fp -Wa,--noexecstack
+    CRYPTOGAMS_ARMV4_THUMB_FLAG = -march=armv7-a+fp -mthumb -Wa,--noexecstack
   else
-    CRYPTOGAMS_ARMV4_FLAG = -march=armv7-a -Wa,--noexecstack
-    CRYPTOGAMS_ARMV4_THUMB_FLAG = -march=armv7-a -Wa,--noexecstack
+    CRYPTOGAMS_ARMV4_FLAG = -march=armv7-a+fp -Wa,--noexecstack
+    CRYPTOGAMS_ARMV4_THUMB_FLAG = -march=armv7-a+fp -Wa,--noexecstack
   endif
   SRCS += aes_armv4.S sha1_armv4.S sha256_armv4.S sha512_armv4.S
 endif

**Comment by gcsideal** [comment]
Missed that the original bug report notes this might affect armel as well. I'm not yet tested building on that architecture.
You can read details at: https://bugs.debian.org/1001995

**Comment by noloader** [comment]
Thanks @gcsideal,

I'm plan on getting to this over the holidays in the US. This will need more testing than usual because older platforms and Clang need to be tested in addition to the latest Debian and GCC.

**Comment by gcsideal** [comment]
> I plan on getting to this over the holidays in the US. This will need more testing than usual because older platforms and Clang need to be tested in addition to the latest Debian and GCC.

Take your time. armel is not affected by this. If you need any help, please message me.

**Comment by noloader** [comment]
@gcsideal,

I can't duplicate it on Debian 10 or Debian 11.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```

And:
```
$ make aria.o aria_simd.o aes_armv4.o
g++ -DNDEBUG -g2 -O3 -fPIC -pthread -c aria.cpp
g++ -DNDEBUG -g2 -O3 -fPIC -pthread -march=armv7-a -mfpu=neon -c aria_simd.cpp
g++ -DNDEBUG -g2 -O3 -fPIC -pthread -march=armv7-a -Wa,--noexecstack -c aes_armv4.S
```
But:
```
$ gcc --version
gcc (Debian 10.2.1-6) 10.2.1 20210110
Copyright (C) 2020 Free Software Foundation, Inc.
```
I see you are using GCC 11.

Do you know how I can duplicate the issue?

**Comment by gcsideal** [comment]
> Do you know how I can duplicate the issue?

I've created an armhf chroot for you. But first, my GnuPG key fingerprint is 'A0DF 7E0D 3851 E0EE 45C0 0BC8 ACE1 F33C B933 BBBB' as you can check in the keyring of Debian.
You can download the tarball: https://people.debian.org/~gcs/armhf_bookworm.tar.xz and its detached GPG signature: https://people.debian.org/~gcs/armhf_bookworm.sig
For additional safety, various hashes of the tarball is available and clearsigned: https://people.debian.org/~gcs/armhf_bookworm_info.txt.asc
While not tested on a clean system, I believe on Debian 11 all you need to do is install the qemu-system-arm package first. Then you unpack the tarball and can chroot into it. Under the /root/compile directory you will find the unpacked source tree. Tested that dpkg-buildpackage compiles what it can and then fails with the issue reported.

Please download the tarball in the next few days, I can't store that long.

**Comment by noloader** [comment]
@gcsideal,

> Please download the tarball in the next few days, I can't store that long.

Got it, thanks. Give me a couple of days to look at things.

**Comment by noloader** [comment]
Hi @gcsideal,

Ok, the good news. I've got things cleaned up. You will need the patch below. The patch was produced with `git diff`. You can apply it to all Crypto++ builds for Debian, and not just armel. You won't need the patch after the next release.

Now, the bad side. armel does not have NEON, and we can't detect that in the makefiles. To the makefiles, armel and armhf look the same. To work around that, for armel, add `CRYPTOPP_DISABLE_ARM_NEON` to disable the NEON code paths. I think it is best to remove the NEON code paths because armel does not have the unit and there's no need to carry around the code.

There were more changes in the makefile then needed for your problem. It was easier for me to give you the full change set rather than trying to pick out pieces.

The patch: [cryptopp-armel-armhf.diff.zip](https://github.com/weidai11/cryptopp/files/8027169/cryptopp-armel-armhf.diff.zip)

**Comment by gcsideal** [comment]
> The patch against Crypto++ 8.6: [cryptopp-armel-armhf.diff.zip](https://github.com/weidai11/cryptopp/files/8027169/cryptopp-armel-armhf.diff.zip)

I'm not entirely sure how the NEON code path goes with wrong compiler flags. Tried your patch and I still get the same error on armhf:
g++ -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -pthread -g -O2 -ffile-prefix-map=/home/gcs/compile/libcrypto++-8.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -DNDEBUG -march=armv7-a -Wa,--noexecstack -c aes_armv4.S
cc1: error: '-mfloat-abi=hard': selected architecture lacks an FPU
Will check if I applied it wrong or what, confused at the moment.

**Comment by noloader** [comment]
Thanks @gcsideal,

Yeah, I'm having trouble, too. Here's what I am seeing:

```
++ -DNDEBUG -g2 -O3 -fPIC -pthread -march=armv7-a -mfpu=auto -Wa,--noexecstack -c aes_armv4.S
cc1: sorry, unimplemented: -mfpu=auto not currently supported without an explicit CPU.
cc1: error: -mfloat-abi=hard: selected processor lacks an FPU
g++ -DNDEBUG -g2 -O3 -fPIC -pthread -march=armv7-a -mfpu=auto -Wa,--noexecstack -c sha1_armv4.S
GNUmakefile:1595: recipe for target 'aes_armv4.o' failed
make: *** [aes_armv4.o] Error 1
make: *** Waiting for unfinished jobs....
cc1: sorry, unimplemented: -mfpu=auto not currently supported without an explicit CPU.
cc1: error: -mfloat-abi=hard: selected processor lacks an FPU
GNUmakefile:1695: recipe for target 'sha1_armv4.o' failed
```

GCC really screwed the pooch on this one.

**Comment by noloader** [comment]
@gcsideal,

I got a Debian Qemu/Chroot installed for armhf. I was able to duplicate the problem locally.

I opened a GCC Issue at [Cannot select -march=armv7-a using GCC 11](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=104455). I should have some something soon.

**Comment by noloader** [comment]
@gcsideal,

I think the problem here is a GCC or Debian bug. I left the reason in [Debian Issue 1001995](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1001995) . I'm not going to add `+fp` since we are not using fp or neon in those source files. I am not going to set that precedent.

Instead, we will forgo using `-march=armv7-a` when the compiler signals it is available.

I've got another patch/diff for you. It is based against Crypto++ 8.6, so it should apply cleanly for you.
