### ISSUE TITLE
Using CryptoPP::ArraySource results in missing symbol CryptoPP::DEFAULT_CHANNEL

### ISSUE THREAD

**Issue by b0bh00d** [weidai11/cryptopp#1095]
Windows 10 Professional x64
Crypto++ 8.7.0 master
Built using Visual Studio 2019 project "cryptdll" (part of the "crypttest" solution), debug & release

After using the Visual Studio project to build the DLL, I then try to link to this Crypto++ DLL build in Qt Creator with:

```
cryptopp {
    DEFINES += USE_ENCRYPTION
    DEFINES += CRYPTOPP

    SOURCES += Crypto.cpp
    HEADERS += Crypto.h

    win32 {
        INCLUDEPATH += M:\Projects\cryptopp
        LIBS += -lcryptopp
        CONFIG(debug, debug|release) {
            LIBS += -LM:\Projects\cryptopp\x64\DLL_Output\Debug
        } else {
            LIBS += -LM:\Projects\cryptopp\x64\DLL_Output\Release
        }
    }
}
```

This results in the following link error:

```Crypto.obj:-1: error: LNK2001: unresolved external symbol "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const CryptoPP::DEFAULT_CHANNEL" (?DEFAULT_CHANNEL@CryptoPP@@3V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@B)```

The link line being used in Qt Creator:

```link /NOLOGO /DYNAMICBASE /NXCOMPAT /DEBUG /SUBSYSTEM:WINDOWS "/MANIFESTDEPENDENCY:type='win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' publicKeyToken='6595b64144ccf1df' language='*' processorArchitecture='*'" /MANIFEST:embed /OUT:deploy\debug\ClipNet.exe @N:\Temp\ClipNet.exe.15540.2578.jom```

This error only appears when I declare CryptoPP::ArraySource in my code, with even just ```CryptoPP::ArraySource as;```.  If I comment this out, all other Crypto++ code links without error.

I also tried moving the project over to Visual Studio in hopes it might be a difference in the IDEs, but I received the same link error with DEFAULT_CHANNEL.

Thanks for any help here.

**Comment by noloader** [comment]
Please ask questions on the mailing list. Please reserve the bug tracker for library bugs.
