### ISSUE TITLE
SHA1 returns wrong result on ARM release mode compile

### ISSUE THREAD

**Issue by PassMark** [weidai11/cryptopp#1096]
V8.6 of Cryptopp seems to be returning a wrong SHA1 value when used in release mode on ARM platforms on 64bit with Visual Studio.

Speculation is that hardware acceleration on ARM is broken in some subtle way and hardware acceleration isn't used in debug mode.

32bit ARM compile is OK,
Debug mode ARM compile is OK.
x86 compile is OK in all permutations.

Test code and example output is attached.

Summary of output is also below

```
SHA-Test-x64-debug.exe
Message: abc
Digest: A9993E364706816ABA3E25717850C26C9CD0D89D
Success
Message: abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq
Digest: 84983E441C3BD26EBAAE4AA1F95129E5E54670F1
Success

SHA-Test-x64-release.exe
Message: abc
Digest: A9993E364706816ABA3E25717850C26C9CD0D89D
Success
Message: abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq
Digest: 84983E441C3BD26EBAAE4AA1F95129E5E54670F1
Success

SHA-Test-ARM64-release.exe
Message: abc
Digest: 54EC777E5DAB79DC6BD3C7CE43C289E19FEFFCEC
Failed comparison, expected A9993E364706816ABA3E25717850C26C9CD0D89D
Message: abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq
Digest: 2810B286725876151057E5B3FACF3F1C0B8873FB
Failed comparison, expected 84983E441C3BD26EBAAE4AA1F95129E5E54670F1

```

[SHA-ARM64-Release-Fail.txt](https://github.com/weidai11/cryptopp/files/7772788/SHA-ARM64-Release-Fail.txt)
[ConsoleApplication1.txt](https://github.com/weidai11/cryptopp/files/7772789/ConsoleApplication1.txt)

**Comment by noloader** [comment]
Thanks @PassMark,

Ugh, I've seen that type of result in the past. I don't see anything wrong with your test program. It is probably a compiler bug. What compiler version are you using?

Try this. It disables global optimizations for the source file. Add it to `sha.cpp`:

```c++
// VS2017 and global optimization bug. TODO, figure out when
// we can re-enable full optimizations for VS2017. Also see
// https://github.com/weidai11/cryptopp/issues/1096
#if (_MSC_VER >= 1910)
# ifndef CRYPTOPP_DEBUG
#  pragma optimize("", off)
#  pragma optimize("ts", on)
# endif
#endif
```

We had to do the same for AES at https://github.com/weidai11/cryptopp/blob/master/rijndael.cpp#L91.

**Comment by PassMark** [comment]
> disables global optimizations

We tried this, but it didn't fix the problem. So it still busted.

Visual Studio Compiler version is
Microsoft (R) C/C++ Optimizing Compiler Version 19.24.28316 for ARM64

**Comment by noloader** [comment]
Thanks @PassMark,

In your case, two more things to try.

First, disable global optimizations in `sha_simd.cpp`:

```
// VS2017 and global optimization bug. TODO, figure out when
// we can re-enable full optimizations for VS2017. Also see
// https://github.com/weidai11/cryptopp/issues/1096
#if (_MSC_VER >= 1910)
# ifndef CRYPTOPP_DEBUG
#  pragma optimize("", off)
#  pragma optimize("ts", on)
# endif
#endif
```

If that does not work, then disable all optimizations for the sha files:

```
#if (_MSC_VER >= 1910)
# ifndef CRYPTOPP_DEBUG
#  pragma optimize("", off)
# endif
#endif
```

Looking at [Microsoft docs](https://docs.microsoft.com/en-us/cpp/preprocessor/optimize?view=msvc-170), I wonder if the compiler is having problems related to the frame pointer. You might try this, too:

```
#if (_MSC_VER >= 1910)
# ifndef CRYPTOPP_DEBUG
#  pragma optimize("", off)
#  pragma optimize("y", on)
# endif
#endif
```
Sorry I can't help much. I don't have a test rig to test things myself.

**Comment by PassMark** [comment]
We tried those additional suggestions. They didn't fix the problem.

Further we strongly suspect that the ECDSA [Elliptic Curve Digital Signature Algorithm] makes use of the broken SHA function and as a result it is also broken and returns false results on ARM 64bit with Visual Studio.

The whole thing is moderately serious. Because the functions don't fail with an error, but just quietly return the wrong result, a lot of higher level code which depends on Crypto breaks in very subtle ways. e.g. bad hashes might effect the security of hashed passwords, code signing, file caching, and a 100 other things.

**Comment by noloader** [comment]
Sorry to hear that @PassMark.

It sounds like you we should disable SHA instrinsics on Microsoft platforms. `CRYPTOPP_DISABLE_ARM_SHA` is the define of interest (from [`config_asm.h:300`](https://github.com/weidai11/cryptopp/blob/master/config_asm.h#L301)). Maybe something like:

```diff
$ git diff
diff --git a/config_asm.h b/config_asm.h
index 8f442bbe..a634e214 100644
--- a/config_asm.h
+++ b/config_asm.h
@@ -311,6 +311,11 @@
 # endif  // Platforms
 #endif

+// Buggy Microsoft compiler, https://github.com/weidai11/cryptopp/issues/1096
+#if defined(_MSC_VER)
+# undef CRYPTOPP_ARM_SHA1_AVAILABLE
+#endif
+
 // ARMv8 and SHA-512, SHA-3. -march=armv8.2-a+crypto or above must be present
 // Requires GCC 8.0, Clang 11.0, Apple Clang 12.0 or Visual Studio 20??
 #if !defined(CRYPTOPP_ARM_SHA3_AVAILABLE) && !defined(CRYPTOPP_DISABLE_ARM_SHA)
```

Do you know is AES, SHA-256 and PMULL have troubles?

You should probably file a bug with Microsoft. I don't have a MSDN account so I can't file bugs (or whatever account is needed nowadays).

**Comment by noloader** [comment]
@PassMark,

I'm curious... What does your test rig look like? You said you have a Surface Pro laptop. What else is needed?

I bought one of those Surface ARM tablets a few years ago. I also bought a new copy of Visual Studio Pro. I could not do any development on the tablet, despite what those Channel9 videos claimed. it was a waste of $1500. I'm not going to do that again. Microsoft cannot be trusted.

**Comment by PassMark** [comment]
Test machine is a Surface Pro X laptop. I think the higher end SQ2 model are still available for sale if you look around. But they are getting a bit old now and haven't been updated in a while. Plus they aren't cheap.

We've had direct discussions with Microsoft and Qualcomm, who both claim Windows 10 for ARM should be feature equivalent to x86 Windows. And it is 95% true. The problem is when you encounter something in that 5%.

Anyway, one of the things in the 5% at the moment is Visual Studio itself. Comically, you can't compile ARM code on a ARM machine with Visual Studio. So you need to compile the ARM code on a x86 machine and then manually move the binary file across for testing. Getting VS to compile ARM assembler files was also a bit tricky, but doable.

While we think there is some possibility that the problem in a bug in the Crypto++ code for ARM hardware acceleration for SHA, it could also be a compiler bug. But I suspect the SHA hardware in the newer ARM chips hasn't got much testing. So there is a small chance it could even be a hardware bug in the silicon.

Has anyone confirmed if SHA1 on ARM with hardware acceleration on 64bit Release mode on Linux works? As if that worked, it probably rules out a hardware bug. We haven't done this test.

For the moment we are going to fall back to the older Cryptopp release which didn't have hardware acceleration, but did work.

**Comment by noloader** [comment]
Thanks @PassMark,

> Has anyone confirmed if SHA1 on ARM with hardware acceleration on 64bit Release mode on Linux works?

Yes. It works for both Linux, OS X (Apple M1) and iOS (iPads). I personally test them. (But I don't have an iPhone to test on, so some of iOS is incomplete).

I have not tested Windows ARM64 port. I don't have a test rig.

Your symptoms - Ok in Debug, fail in Release - is usually (1) undefined behavior or (2) compiler bug. I don't believe we have undefined behavior. We are mindful of UB and actively hunt for it on Unix, Linux and OS X. I think it is another compiler bug like [GH #1096](https://github.com/weidai11/cryptopp/issues/1096). I doubt it is a hardware bug.

And I don't think I mentioned this... hardware acceleration is active in both Debug and Release builds. The one exception to the rule is Android emulators. We disable ASM when building for an emulator since the emulators don't emulate the hardware acceleration we use.

> For the moment we are going to fall back to the older Crypto++ release which didn't have hardware acceleration, but did work.

Ack. You can also use the latest Crypto++ and simply define `CRYPTOPP_DISABLE_ASM`. That disables all hardware acceleration, and only uses C++ code.

Another thing you might try... Build Crypto++ from the Command Line using a Visual Studio Command Prompt. I prefer it nowadays. Also see [Nmake (Command Line)](https://cryptopp.com/wiki/Nmake_(Command_Line)) on the Crypto++ wiki.

**Comment by noloader** [comment]
@PassMark,

I disabled Microsoft ARM64 SHA-1 and SHA-2 hardware acceleration until we can get to the bottom of things.

Also see [Commit 66d73d6d8b95](https://github.com/weidai11/cryptopp/commit/66d73d6d8b95). The commit was rather big. I forgot I had another change staged when I committed this change. The important part is in `config_asm.h`:

```diff
// Buggy Microsoft compiler, https://github.com/weidai11/cryptopp/issues/1096
#if defined(_MSC_VER)
# undef CRYPTOPP_ARM_SHA1_AVAILABLE
# undef CRYPTOPP_ARM_SHA2_AVAILABLE
#endif
```

**Comment by PassMark** [comment]
Microsoft has released an updated version of Visual Studio (for ARM) that seems to fix the compiler issue.

We have tested VS2022 (17.1.0) and VS2019 (16.11.13) and both seem to be working now, generating correct SHA1 hashes in ARM 64bit release mode.

BUT, to actually build the code in these new VS releases a new arm_simd.h file is required. See attached.

[arm_simd_new.txt](https://github.com/weidai11/cryptopp/files/8528353/arm_simd_new.txt)

**Comment by noloader** [comment]
Thanks @PassMark.

I'm not sure what is going on, but Firefox cannot download `arm_simd_new.txt`. Can you paste the `cat` of the file?

**Comment by chausner** [comment]
@noloader This is a diff of the file @PassMark posted with the one in the repo:

```diff
--- "a/.\\arm_simd.h"
+++ "b/.\\arm_simd.h"
@@ -316,11 +316,21 @@ inline uint64x2_t PMULL_HIGH(const uint64x2_t a, const uint64x2_t b)
 ///  <tt>a</tt> and the remaining bytes in <tt>b</tt>. VEXT_U8 is provided
 ///  as GCC inline assembly due to Clang and lack of support for the intrinsic.
 /// \since Crypto++ 8.0
-inline uint64x2_t VEXT_U8(uint64x2_t a, uint64x2_t b, unsigned int c)
+inline uint64x2_t VEXT_U8a(uint64x2_t a, uint64x2_t b, unsigned int c)
 {
 #if defined(_MSC_VER)
-    return vreinterpretq_u64_u8(vextq_u8(
-        vreinterpretq_u8_u64(a), vreinterpretq_u8_u64(b), c));
+    /*const uint64x2_t a2 = a;
+    const uint64x2_t b2 = b;
+    const unsigned int c2 = c;
+    const __n128 largeBitNumber1 = vreinterpretq_u8_u64(a2);
+    const __n128 largeBitNumber2 = vreinterpretq_u8_u64(b2);
+    const __n128 largeBitNumber3 = vextq_u8(largeBitNumber1, largeBitNumber2, c);
+    return vreinterpretq_u64_u8(largeBitNumber3);*/
+    //This was a test, the VC compiler needs c to be constant
+    //Terminating the program if this code ever hits
+    quick_exit(0x80070005);
+    uint64x2_t d= { 0 };
+    return d;
 #else
     uint64x2_t r;
     __asm__ ("ext   %0.16b, %1.16b, %2.16b, %3   \n\t"
```
