### ISSUE TITLE
TestRandomPool asserts on VS2022 with a debug build

### ISSUE THREAD

**Issue by dgm3333** [weidai11/cryptopp#1103]
This is probably not a major issue given it only occurs on a debug test on a depreciated function but I can't see it's been reported elsewhere

Running Win10 64 pro
Crypto latest (unmodified direct from git) = Library version (library): 870, header version (app): 870
Visual Studio 2022 *debug build* after opening via cryptest.sln
NB the release build works fine

using local windows debugger to run cryptest

fails:-
pass=TestRandomPool() && pass;

at assert:-
// If this assert fires, then outString == inString. You could experience a
// performance hit. Also see https://github.com/weidai11/cryptopp/issues/1088'
CRYPTOPP_ASSERT(outString != inString);

with output:-
Testing OldRandomPool generator...

Assertion failed: C:\Users\usr\source\repos\cryptopp\strciphr.cpp(249): CryptoPP::CFB_CipherTemplate<class CryptoPP::AbstractPolicyHolder<class CryptoPP::CFB_CipherAbstractPolicy,class CryptoPP::CFB_ModePolicy> >::ProcessData

This is the callstack at the point of assert failure:-
>	KernelBase.dll!00007ff886af90d2()	Unknown
 	cryptest.exe!CryptoPP::CFB_CipherTemplate<CryptoPP::AbstractPolicyHolder<CryptoPP::CFB_CipherAbstractPolicy,CryptoPP::CFB_ModePolicy>>::ProcessData(unsigned char * outString, const unsigned char * inString, unsigned __int64 length) Line 249	C++
 	cryptest.exe!CryptoPP::StreamTransformation::ProcessString(unsigned char * inoutString, unsigned __int64 length) Line 1061	C++
 	cryptest.exe!CryptoPP::OldRandomPool::Stir() Line 138	C++
 	cryptest.exe!CryptoPP::OldRandomPool::GenerateIntoBufferedTransformation(CryptoPP::BufferedTransformation & target, const std::string & channel, unsigned __int64 size) Line 151	C++
 	cryptest.exe!CryptoPP::RandomNumberStore::TransferTo2(CryptoPP::BufferedTransformation & target, unsigned __int64 & transferBytes, const std::string & channel, bool blocking) Line 1241	C++
 	cryptest.exe!CryptoPP::BufferedTransformation::TransferMessagesTo2(CryptoPP::BufferedTransformation & target, unsigned int & messageCount, const std::string & channel, bool blocking) Line 656	C++
 	cryptest.exe!CryptoPP::BufferedTransformation::TransferAllTo2(CryptoPP::BufferedTransformation & target, const std::string & channel, bool blocking) Line 702	C++
 	cryptest.exe!CryptoPP::SourceTemplate<CryptoPP::RandomNumberStore>::PumpAll2(bool blocking) Line 1444	C++
 	cryptest.exe!CryptoPP::Source::PumpAll() Line 1383	C++
 	cryptest.exe!CryptoPP::Source::SourceInitialize(bool pumpAll, const CryptoPP::NameValuePairs & parameters) Line 1421	C++
 	cryptest.exe!CryptoPP::RandomNumberSource::RandomNumberSource(CryptoPP::RandomNumberGenerator & rng, int length, bool pumpAll, CryptoPP::BufferedTransformation * attachment) Line 1520	C++
 	cryptest.exe!CryptoPP::Test::Test_RandomNumberGenerator(CryptoPP::RandomNumberGenerator & prng, bool drain) Line 449	C++
 	cryptest.exe!CryptoPP::Test::TestRandomPool() Line 666	C++
 	cryptest.exe!CryptoPP::Test::ValidateAll(bool thorough) Line 45	C++
 	cryptest.exe!CryptoPP::Test::Validate(int alg, bool thorough) Line 943	C++
 	cryptest.exe!CryptoPP::Test::scoped_main(int argc, char * * argv) Line 401	C++
 	cryptest.exe!main(int argc, char * * argv) Line 1095	C++
 	[External Code]

**Comment by noloader** [comment]
We are testing the fix. I'm going to close this issue.

**Comment by noloader** [comment]
I merged the changes into master last night. You should test master now.
