### ISSUE TITLE
I phasing this "clang: error: no such file or directory: 'cryptlib.lib'" in visual studio.

### ISSUE THREAD

**Issue by devliya** [weidai11/cryptopp#1108]
I am developing the .so file in visual studio. when i am trying to build the project it’s give the error which is below. below is my output log.
```
Build started...

1>------ Build started: Project: SharedObject2, Configuration: Debug ARM ------

1>ANDROID_HOME=C:\\Microsoft\AndroidSDK\25

1>ANT_HOME=C:\Program Files\Microsoft Visual Studio\2022\Community\Apps\apache-ant-1.9.3

1>JAVA_HOME=C:\Program Files\Android\jdk\jdk-8.0.302.8-hotspot\jdk8u302-b08

1>NDK_ROOT=C:\\Microsoft\AndroidNDK\android-ndk-r21e

1>pch.h

1>SharedObject2.cpp

1>clang: error: no such file or directory: 'cryptlib.lib'

1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Application Type\Android\3.0\Android.Common.targets(119,5): error MSB6006: "clang.exe" exited with code 1.

1>Done building project "SharedObject2.vcxproj" -- FAILED.

========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

have put the folder of cryptopp library folder inside the project folder. and also i have added the

> Additional Include Directories

in the property>C/C++>General of project into visual studio project property. in this I have add the path of include header files.

also add the Additional Library Directories

> Additional Library Directories

in the property>Linker>General of project into visual studio project property.in this i have add the .lib file path.

and also add the Input

> Additional Dependencies

in the property>Linker>Input of project into visual studio project property. here i write the name of .lib file. which is “cryptlib.lib”.

https://github.com/weidai11/cryptopp this is the link where i downloaded the crypto++ library. in this project there is one file which is “cryptlib.vcxproj” using this file i have build the .lib file. then this whole project folder i have put in my project and use this lib file in my project which is i have mention above. i am developing the dynamic shared library(android). can i use this cryptlib.lib file in the development of dynamic shared library(android) ?

Please anyone help me to solve this error why i am getting clang error ? please help.

**Comment by noloader** [comment]
Please do not ask questions in the bug tracker. Please ask questions on the Crypto++ Users List at http://groups.google.com/forum/#!forum/cryptopp-users.

**Comment by devliya** [comment]
> Please do not ask questions in the bug tracker. Please ask questions on the Crypto++ Users List at http://groups.google.com/forum/#!forum/cryptopp-users.

Okay, Thanks for the reply.

**Comment by devliya** [comment]
> Please do not ask questions in the bug tracker. Please ask questions on the Crypto++ Users List at http://groups.google.com/forum/#!forum/cryptopp-users.

@noloader  Hi, I am posting the question. but question was not posting. it is deleted automatically at a time. please help.
