### ISSUE TITLE
Implementation of  PKCS #1 RSA PSS with Cryptopp

### ISSUE THREAD

**Issue by christian5011** [weidai11/cryptopp#1111]
Hi,
I'm trying to implement [CKM_RSA_PKCS_PSS from PKCS#11](https://www.cryptsoft.com/pkcs11doc/v220/group__SEC__12__1__10__PKCS____1__RSA__PSS.html) using Cryptopp 8.6 but it seems that there is not a signer implementation in Cryptopp than can do exactly this.
Botan implemented this mechanism with the [PSSR_Raw](https://botan.randombit.net/doxygen/classBotan_1_1PSSR__Raw.html) PK_Signer class after an issue was opened ([see issue](https://github.com/randombit/botan/issues/1211)).
The closest I've been able to get was using the following RSA signer template in cryptopp:
`RSASS<PSS, SHA256>::Signer`
which is the equivalent to the Botan [normal PSSR implementation](https://botan.randombit.net/doxygen/classBotan_1_1PSSR.html) without message recovery, and also seems to be following the mechanism [CKM_SHA256_RSA_PKCS_PSS from PKCS#11](https://www.cryptsoft.com/pkcs11doc/v230/group__SEC__11__1__17__PKCS____1__RSA__PSS__SIGNATURE__WITH__SHA__1____SHA__256____SHA__384__OR__SHA__512.html#CKM_SHA256_RSA_PKCS_PSS).

The problem is that the _"PKCS #1 RSA PSS_" mechanism does not compute the hash over the given message, it assumes the input/message it's a **pre-hashed buffer**, but the signer in cryptopp always hashes the message.
 As stated in the mechanism definition:

> _"The PKCS #1 RSA PSS mechanism, denoted [CKM_RSA_PKCS_PSS](https://www.cryptsoft.com/pkcs11doc/v220/group__SEC__12__1__9__PKCS____1__RSA__PSS__MECHANISM__PARAMETERS.html#CKM_RSA_PKCS_PSS), is a mechanism based on the RSA public-key cryptosystem and the PSS block format defined in PKCS #1. It supports single-part signature generation and verification without message recovery. This mechanism corresponds only to the part of PKCS #1 that involves block formatting and RSA, given a hash value; it does not compute a hash value on the message to be signed."_

And also Botan documentation states in the description of the PSSR_Raw class:

> _"This accepts a pre-hashed buffer"_

Is there any way to implement this signature scheme with Cryptopp?

Thanks,
Christian

**Comment by noloader** [comment]
See https://www.cryptopp.com/wiki/Adding_a_Hash. In the future please ask questions on the mailing list.
