### ISSUE TITLE
clang++-14 warning

### ISSUE THREAD

**Issue by KayEss** [weidai11/cryptopp#1114]
I've been testing out the new clang++-14 compiler and gives a new warning in the RSA implementation (I'm using `-Werror` so it shows as an error):

```
rsa.cpp:162:20: error: use of bitwise '|' with boolean operands [-Werror,-Wbitwise-instead-of-logical]
        if (n.IsEven() || e.IsEven() | d.IsEven())
                          ^~~~~~~~~~~~~~~~~~~~~~~
                                     ||
rsa.cpp:162:20: note: cast one or both operands to int to silence this warning
```

I'm building with an older cryptopp, but I see this line is unchanged in current `master` <https://github.com/weidai11/cryptopp/blob/6a3b34f555ebf29a46b6c143a0063f474a635ed7/rsa.cpp#L162>.

The warning looks legit to me and that it's just a simple typo. Do you want a PR for this or just fix yourselves?

**Comment by noloader** [comment]
Thanks @KeyEss.

That's the first time I've seen that warning. It looks like the bitwise OR predates Crypto++ 5.6.0. Its been there a while...

It should be cleared at [Commit 9d055394d939](https://github.com/weidai11/cryptopp/commit/9d055394d939).

**Comment by KayEss** [comment]
Cool, great :-)
