### ISSUE TITLE
CPUID64 assembly noncompliant with Windows x64 ABI

### ISSUE THREAD

**Issue by Myriachan** [weidai11/cryptopp#1116]
The [`CPUID64` function in `x64dll.asm`](https://github.com/weidai11/cryptopp/blob/master/x64dll.asm#L1999) modifies a nonvolatile register (`rbx`) but does not use `proc frame`.

Sample fix:

```
CPUID64	PROC FRAME
    ;; preserve per ABI
    mov 	[rsp+8], rbx
.savereg rbx, 8
.endprolog	
    ;; eax = func
    mov 	rax, rcx
    ;; ecx = subfunc
    mov 	rcx, rdx
    ;; query
    cpuid
    ;; save
    mov 	[r8+0],  eax
    mov 	[r8+4],  ebx
    mov 	[r8+8],  ecx
    mov 	[r8+12], edx
    ;; return value
    mov 	rax, 1
    ;; restore
    mov 	rbx, [rsp+8]
    ret
CPUID64	ENDP
```

**Comment by noloader** [comment]
Thanks @Myriachan.

> ... but does not use proc frame.

I don't see that in the docs at Microsoft's [x64 software conventions](https://docs.microsoft.com/en-us/cpp/build/x64-software-conventions).

Stepping back a bit, this was intended to be a leaf function without a red zone. It does not call other functions and does not use exceptions.

But if the `push` onto the stack is worrying you, how about if we save `rbx` to another volatile register like `r9`. `r9` is scratch and we can blow it away. And we won't be using any stack space.

**Comment by Myriachan** [comment]
> I don't see that in the docs at Microsoft's [x64 software conventions](https://docs.microsoft.com/en-us/cpp/build/x64-software-conventions).

From that page:

> Every function that allocates stack space, calls other functions, _saves nonvolatile registers_, or uses exception handling must have a prolog whose address limits are described in the unwind data associated with the respective function table entry, and epilogs at each exit to a function. 

The whole design is that the stack can always be unwound deterministically using the metadata in the `.pdata` and `.xdata` sections.  In order to unwind, the OS needs to know how to find the previous values of nonvolatile registers.

> But if the push onto the stack is worrying you, how about if we save rbx to another volatile register like r9. r9 is scratch and we can blow it away. And we won't be using any stack space.

As far as I know, there isn’t a way in the metadata to say that a nonvolatile register’s original value can be found in another register.  So it has to be written to the stack somewhere.

Writing to the function’s parameter shadow like this (`[rsp+8]`) avoids needing to allocate stack memory, but it still needs the metadata to specify where to find the old value of `rbx`.

An alternative way to do this would be to add a `.pushreg rbx` after that `push rbx`, but I don’t know whether it is legal to not allocate the next 32-byte parameter shadow if you aren’t calling anything.  It would be simpler this way.  Note that this solution would still require moving the `mov rax, 1` because `pop rbx` needs to be part of the official epilog.

The way that epilogs work in x64 Windows is that the unwinder reads the instruction opcodes at `rip` to see whether it matches a known pattern, and if so, can unwind by simulating these instructions.  It does mean, though, that the function epilog has a very strict format, and writing to `rax` Isn’t one of the allowed opcodes.

Overall, this sort of issue is very minor.  It means that a debugger would not be able to produce a call stack if a debuggee or crash dump happened to be in the middle of this function.  But CPUID shouldn’t be crashing, either.

**Comment by Myriachan** [comment]
`Salsa20_OperateKeystream` also has an issue with the ABI.  The `call`s within the function modify `rsp` outside the prolog.  In the ABI, modifying `rsp` outside the prolog is only legal if the function uses a frame pointer.

Because it looks like this code does not touch `rbp`, it might as well be the frame pointer.  Then saving `rbp` in the prolog, setting it to `rsp` (possibly with an offset), and restoring at exit is enough.

The fact that there are `call` instructions pointing to another part of the function actually doesn't break anything, except that it modifies `rsp`.  By using a frame pointer, the OS will just think that it's a function that does `alloca`-type stuff, and unwind correctly.

**Comment by noloader** [comment]
Thanks again @Myriachan,

> Overall, this sort of issue is very minor. It means that a debugger would not be able to produce a call stack if a debuggee or crash dump happened to be in the middle of this function. But CPUID shouldn’t be crashing, either.

Ok, that explains a lot. I encountered a problem with backtraces before at [GH # 872](https://github.com/weidai11/cryptopp/issues/872). I'm guessing the backtrace problem had something to do with what you pointed out.

One last question... Does the discussion of saving RBX apply even with fastcall?

**Comment by noloader** [comment]
Thanks again @Myriachan.

This should be cleared at [Commit e6f1f8131974](https://github.com/weidai11/cryptopp/commit/e6f1f8131974).
