### ISSUE TITLE
Undefined symbols for architecture arm64:   "CryptoPP:

### ISSUE THREAD

**Issue by wimvandenborre** [weidai11/cryptopp#1120]
Hey,

When compiling I get a bunch of Undefined symbols for architecture arm64:
  "CryptoPP: errors.

I'm using xcode 13.3.1 on mac 12.3.1, using the latest 8.6 lib.

**Comment by noloader** [comment]
### ask questions on the mailing list.

**Comment by codeworse** [comment]
Have the same issue. How to solve it?

**Comment by wteng** [comment]
Have the same issue. How to solve it?
