### ISSUE TITLE
Add support for EC-GDSA and EC-KCDSA

### ISSUE THREAD

**Issue by DevJPM** [weidai11/cryptopp#113]
There recently was [a question over at Crypto.SE about the speed of ECGDSA vs ECKCDSA vs ECDSA](http://crypto.stackexchange.com/q/31853/23623). The question showed a general lack of implementation of the former two schemes and so I though to bring it up here.

I'm hereby proposing to adding support for ECGDSA (EC German DSA) and ECKCDSA (EC Korean Certificate DSA) for Crypto++.

Note that once you've finished ECGDSA you can easily do ECKCDSA with the gained knowledge because they are both highly similar.

The strategy proposal for implementors:
1) Identify where the signature / verification logic for ECDSA is situated at
2) Copy, rename and adapt the relevant classes
3) Provide a new file (add it to the same place where ECDSA is) to allow people to use the new algorithms

As for the certificate hashing part, you need to assume that the certificate is prepended to the message to be signed.

The following ressources may be useful for the implementation:
1) [Siemens' original specification](https://www.teletrust.de/fileadmin/files/oid/ecgdsa_final.pdf) (GDSA only + many test vectors)
2) [BSI's TR-03111](https://www.bsi.bund.de/SharedDocs/Downloads/EN/BSI/Publications/TechGuidelines/TR03111/BSI-TR-03111_pdf.pdf;jsessionid=1DE78E2010CFB9DBB5FCF76DBDB035DE.2_cid368?__blob=publicationFile&v=1) (ECGDSA + ECKCDSA no test vectors)
3) [KCDSA's original specification](http://grouper.ieee.org/groups/1363/P1363a/contributions/kcdsa1363.pdf) (KCDSA only + including one test vector)

If nobody picks it up until I have finished my current ECPE work, I'll do it after wards.

**Comment by noloader** [comment]
@DevJPM, Are you targeting the next release for these changes? If so, would you like the 5.7 tag added?

**Comment by noloader** [comment]
ECGDSA was added at [Commit cecf719fcd8cde07](https://github.com/weidai11/cryptopp/commit/cecf719fcd8cde0724567d4b38360daae52b4597).

**Comment by noloader** [comment]
ECGDSA was added at [Commit cecf719fcd8cde07](https://github.com/weidai11/cryptopp/commit/cecf719fcd8cde0724567d4b38360daae52b4597).

**Comment by noloader** [comment]
ECGDSA was added at [Commit cecf719fcd8cde07](https://github.com/weidai11/cryptopp/commit/cecf719fcd8cde0724567d4b38360daae52b4597). The commit includes keys, signing algorithm and self tests over prime fields. [Commit 379e76d27d976095](https://github.com/weidai11/cryptopp/commit/379e76d27d976095b44fbbdf672898a756278ded) added the benchmark code.

I was not sure about the OID and serialization support, so that will be hit or miss. If anyone is interested, they can add the self test for binary fields.

**Comment by noloader** [comment]
Closing.

**Comment by cgebe** [comment]
EC-KCDSA is added too? As far as I searched it isn't.

**Comment by noloader** [comment]
@cgebe,

> EC-KCDSA is added too?

No. Only ECGDSA  was added.

As far as I know there is no interest or need for EC-KCDSA at the moment.

**Comment by cgebe** [comment]
That is a pity. Unfortunately,  I am not in the right person who can take care of the implementation. However, I would be very happy about a C++ version of EC-KCDSA. Can I open another issue specifically for EC-KCDSA?

**Comment by noloader** [comment]
> Can I open another issue specifically for EC-KCDSA?

Yes, feel free.

It probably won't make it into Crypto++ 6.0. I've got OCB mode to finish and then ed25519 signatures. Once they are done we need to release to clear a couple of CVE's and clean-up some ABI breaks.

**Comment by cgebe** [comment]
No hurry! thank you very much, appreciate that!  :two_hearts:crypto++
