### ISSUE TITLE
Hex input type with odd char for sha3_256

### ISSUE THREAD

**Issue by bbap-7fat** [weidai11/cryptopp#1130]
OS: CentOS release 6.8
Crypto version: cryptopp_8.2.0

Currently, I use below code to deal with hex string input to get sha3-256 output

```
    std::string my_hash_function(const std::string& hexInput) {
        // convert heximal string input to text string
        std::string decoded = "";
        StringSource(hexInput, true, new HexDecoder(new StringSink(decoded)));
    
        // get hash output based on a text string input
        SHA3_256 sha256;
        std::string hash = "";
        StringSource(decoded, true, new HashFilter(sha256, new HexEncoder(new StringSink(hash), false)));
        return hash;
    }
```
And in this case, odd number of heximal input will be incorrect. It seems to drop last char.
```
e.g. my_hash_function(4'h048b)  = 1f73f9a3c025885ba2cfab356a7ffba1731423018b6eea5ab6be7693d369fa3e
e.g. my_hash_function(5'h048be) = 1f73f9a3c025885ba2cfab356a7ffba1731423018b6eea5ab6be7693d369fa3e
```

They will get the same result. I would like to know how to get correct hash result based on hex string input instead of converting it to text string in advance?

thanks

**Comment by chausner** [comment]
Usually, hex digits are padded to two characters, so strings of odd character count are not supported. If you still want to allow unpadded hex strings, you could just manually prefix it with a "0" if the length is odd, i.e. "048be" -> "0048be".
