### ISSUE TITLE
GCC 11: AES-GCM: make check fails on amd64 without CLMUL support

### ISSUE THREAD

**Issue by v1ne** [weidai11/cryptopp#1132]
OS: Ubuntu 20.04 LTS
Version: master@9ea66ce4d97d59d61e49c93f5af191107ebd1925
CPU: amd64 without CLMUL support
Compiler: GCC 11.1.0
How I built the library: `make -j8 static`

## How to reproduce

* `git checkout --depth=1 https://github.com/weidai11/cryptopp.git`
* Get a computer with an amd64 CPU without CLMUL support or apply the following patch to disable it on any modern amd64 CPU (Haswell or later; AES-NI, SSE3/4, AVX can stay enabled):
```diff
diff --git a/cpu.cpp b/cpu.cpp
index ec107db..084566d 100644
--- a/cpu.cpp
+++ b/cpu.cpp
@@ -721,6 +721,7 @@ void DetectX86Features()
        g_hasAVX2 &= g_hasAVX;

 done:
+       g_hasCLMUL &= 0;

 #if defined(_SC_LEVEL1_DCACHE_LINESIZE)
        // Glibc does not implement on some platforms. The runtime returns 0 instead of error.
```
* Build: `make -j8 static`
* Run tests: `make check`

## Expected behaviour

`make check` passes

## Actual behaviour

`make check` fails multiple AES-GCM test vectors. In many cases, there is garbage added to the ciphertext:

>2K tables:
>Testing AuthenticatedSymmetricCipher algorithm AES/GCM.
>...
>incorrectly encrypted: >42831EC2217774244B7221B784D0D49CE3AA212F2C02A4E035C17E2329ACA12E21D514B25466931C7D8F6A5AAC84AA051BA30B396A0AAC973D58E091473F5985**4F0F49EB03A109A614FEC26D366402C7**
>
>AlgorithmType: AuthenticatedSymmetricCipher
>Ciphertext: 42831ec2217774244b7221b784d0d49ce3aa212f2c02a4e035c17e2329aca12e 21d514b25466931c7d8f6a5aac84aa051ba30b396a0aac973d58e091473f5985

In contrast, 64k AES/GCM tables always succeed.
Please find the raw output of a failing `make check` attached.

## Further details
I had these tests **fail** on VMs with the following CPU flags:
* `hasSSE2 == 1, hasSSSE3 == 0, hasSSE4.1 == 0, hasSSE4.2 == 0, hasAVX == 0, hasAVX2 == 0, hasAESNI == 0, hasCLMUL == 0, hasRDRAND == 0, hasRDSEED == 0, hasSHA == 0, isP4 == 1`
* `hasSSE2 == 1, hasSSSE3 == 1, hasSSE4.1 == 1, hasSSE4.2 == 1, hasAVX == 1, hasAVX2 == 1, hasAESNI == 1, hasCLMUL == 0, hasRDRAND == 1, hasRDSEED == 1, hasSHA == 0, isP4 == 0`

I had these tests **succeed** on VMs with the following CPU flags:
* `hasSSE2 == 1, hasSSSE3 == 0, hasSSE4.1 == 0, hasSSE4.2 == 0, hasAVX == 0, hasAVX2 == 0, hasAESNI == 0, hasCLMUL == 1, hasRDRAND == 0, hasRDSEED == 0, hasSHA == 0, isP4 == 0`
* `hasSSE2 == 1, hasSSSE3 == 1, hasSSE4.1 == 1, hasSSE4.2 == 1, hasAVX == 1, hasAVX2 == 1, hasAESNI == 1, hasCLMUL == 1, hasRDRAND == 1, hasRDSEED == 1, hasSHA == 0, isP4 == 0`

Further observations:
* clang 13.0.1 works
* gcc 9 works
* gcc 10 works
* gcc 11 works if `g++ … -O0 gcm.cpp` is used
* gcc 11 `g++ … -O1 gcm.cpp` makes the tests fail
* gcc11 works if in addition to CLMUL=0, SSE2 support is disabled, too
* gcc11 works if SSE2 support is only disabled in gcm.cpp:414 (`switch(2*(m_buffer.size()>=64*1024)+ HasSSE2() …)`) → It's probably the "SSE2 and 2K tables" case that's broken in gcm.cpp's `AuthenticateBlocks()` (or GCC 11 miscompiles it)

**Comment by v1ne** [comment]
BTW, I can make the tests work if I mark `AS_REG_7` (r10) as clobbered:
```diff
diff --git a/gcm.cpp b/gcm.cpp
index 380dc78..045977a 100644
--- a/gcm.cpp
+++ b/gcm.cpp
@@ -725,7 +725,7 @@ size_t GCM_Base::AuthenticateBlocks(const byte *data, size_t len)
                 ATT_PREFIX
                     :
                     : "c" (data), "d" (len/16), "S" (hashBuffer), "D" (s_reductionTable)
-                    : "memory", "cc", "%eax"
+                    : "memory", "cc", "%eax", "%xmm0", "%xmm1", "%xmm2", "%xmm3", "%xmm4", "%xmm5", "%ebx","%r10"
             #if CRYPTOPP_BOOL_X64
                     , "%ebx", "%r11"
             #endif
```

I guess the inline assembly blocks should list all the registers they clobber, which is why I added all the SIMD registers and ebx (which is clobbered unconditionally) for good measure. But it's the "%r10" that makes the difference in my example.

**Comment by noloader** [comment]
Thanks @v1ne,

That's an interesting find. Thanks for tracking it down. Do you want to make a pull request?

Out of morbid curiosity, where did you find a processor with AESNI but without CLMUL? I thought all processors with AESNI included CLMUL (called AES New Instructions in Intel literature).

**Comment by v1ne** [comment]
> That's an interesting find. Thanks for tracking it down. Do you want to make a pull request?

Sure. Created.

> Out of morbid curiosity, where did you find a processor with AESNI but without CLMUL? I thought all processors with AESNI included CLMUL (called AES New Instructions in Intel literature).

Well, the CPUs of our servers very probably support these instructions, but their support gets disabled along the way by a hypervisor or the Linux kernel, I guess. It's a pretty artificial setup, I must admit. (:
