### ISSUE TITLE
Comparison of uninitialized SecByteBlock raises an assertion

### ISSUE THREAD

**Issue by BogdanGureev** [weidai11/cryptopp#1138]
When the SecByteBlock is created but the memory is never initialized, the comparison works correctly but the assertion is raised

OS: `Windows 10 x64 Home 21H2`
Version: `Crypto++ 8.6.0`
Build: `Visual Studio 2015`
Configuration: `Debug x64`
Runtime library: `Multi-threaded Debug (/MTd)`
Test application: Simply added the Win32 console project to the `crypttest` solution and add the `cryptlib.lib` library as a dependency. Then build and run.

Test case:
```
#include <iostream>

#include "secblock.h"

int main()
{
	CryptoPP::SecByteBlock b1, b2;
	std::cout << "EQ: " << ( b1 == b2 ) << std::endl;
	return 0;
}
```

Output:
```
Assertion failed: misc.cpp(220): CryptoPP::VerifyBufsEqual
Assertion failed: misc.cpp(221): CryptoPP::VerifyBufsEqual
EQ: 1
Press any key to continue . . .
```

**Comment by noloader** [comment]
This is expected behavior. If you want initialized memory, then use one of the `SecByteBlock` overloads. See https://www.cryptopp.com/wiki/SecBlock .

**Comment by BogdanGureev** [comment]
> If you want initialized memory, then use one of the `SecByteBlock` overloads

I don't need any memory. I don't see assertions for the `count` parameter in `VerifyBufsEqual` but there is the requirement for memory to be allocated that is weird.

So, if my code allows the default-constructed `SecByteBlock`, I need to use the following wrapper instead of a simple comparison operator.
```
equal( const CryptoPP::SecByteBlock & _left, const CryptoPP::SecByteBlock & _right )
{
  if ( _left.empty() && _right.empty() )
    return true;

  if ( _left.empty() || _right.empty() )
    return false;

  return _left == _right;
}
```
If this is expected behavior, it would be nice to be well-documented in the wiki, maybe with the code sample
