### ISSUE TITLE
Can't build Crypto++ for arm64 iphone simulator

### ISSUE THREAD

**Issue by jnavarrom** [weidai11/cryptopp#1151]
### Crypto++ Issue Report

* State the operating system and version (macOS monterrey: 12.5.1, chip Apple M1 Max)
* State the version of the Crypto++ library (master)
* State how you built the library (makefile)

Hello

 `setenv-ios.sh` script fails if we use `IOS_SDK` `iPhoneSimulator` and `IOS_CPU` `arm64`

```
% source TestScripts/setenv-ios.sh iPhoneSimulator arm64
Using positional arg, IOS_SDK=iPhoneSimulator
Using positional arg, IOS_CPU=arm64
Configuring for iPhoneSimulator (arm64)
IOS_SDK and IOS_CPU are not valid. Please fix them
```

**Comment by noloader** [comment]
Cleared with [PR #1150](https://github.com/weidai11/cryptopp/pull/1150).

Thank you very much.
