### ISSUE TITLE
Possible Typo in Ed25519 Wiki Page

### ISSUE THREAD

**Issue by u20n** [weidai11/cryptopp#1157]
I'm not sure if the github issue tracker is the place to report this, but there's a typo in ed25519 wiki page, under the Message Verification section.

```
StringSource(signature+message, true, new SignatureVerificationFilter(verifier,
             NULLPTR, THROW_EXCPETION)));
```
where `THROW_EXCPETION` should be `THROW_EXCEPTION`. This may be a non-issue, but I'm not sure where else to report this.

**Comment by noloader** [comment]
Thanks, fixed.
