### ISSUE TITLE
In `GNUMakefile`, wrong dependency for `blake2b_simd.o`

### ISSUE THREAD

**Issue by abdes** [weidai11/cryptopp#1164]
### Crypto++ Issue Report
Crupto++ 8.7.0

In the GNUMakefile:

```
# SSE, NEON or POWER7 available
blake2s_simd.o : blake2s_simd.cpp
	$(CXX) $(strip $(CPPFLAGS) $(CXXFLAGS) $(BLAKE2S_FLAG) -c) $<

# SSE, NEON or POWER8 available
blake2b_simd.o : blake2s_simd.cpp
	$(CXX) $(strip $(CPPFLAGS) $(CXXFLAGS) $(BLAKE2B_FLAG) -c) $<
```

`blake2b_simd.o` should depend on `blake2b_simd.cpp`

**Comment by noloader** [comment]
Hmmm.... I'm not seeing that in Master: https://github.com/weidai11/cryptopp/blob/master/GNUmakefile#L1642

**Comment by abdes** [comment]
That’s great news.
I was not y it sing master…

Let’s close it then.
