### ISSUE TITLE
 byte order of crc32

### ISSUE THREAD

**Issue by Pumaly** [weidai11/cryptopp#1184]
the  byte order of crc32 does not match。

CRC32 crc32;
StringSource(plain, true, new HashFilter(crc32, new HexEncoder(new StringSink(dst))));
The general result is 6D8A7EF2，but F2A78E6D.

void CRC32::TruncatedFinal(byte *hash, size_t size)
{
	ThrowIfInvalidTruncatedSize(size);

	m_crc ^= CRC32_NEGL;
	for (size_t i=0; i<size; i++)
		hash[i] = GetCrcByte(i);

	Reset();
}

**Comment by noloader** [comment]
Please ask questions on the mailing list.

**Comment by Pumaly** [comment]
the location of this code should has judge for Little-Endian？
