### ISSUE TITLE
'Variable is not used' warnings in VS 2022

### ISSUE THREAD

**Issue by irwir** [weidai11/cryptopp#1185]
Cryptopp master branch, Visual Studio 2022.
There were multiple warning when compilng a project with cryptopp library:

> Warning	C5264	'CryptoPP::INFINITE_TIME': 'const' variable is not used	\cryptopp\cryptlib.h	130

This is because the variable gets defined every time the header was included,
A simple fix is to move the definition of `CryptoPP::INFINITE_TIME` to cryptlib.cpp while the header file has only this declaration:
`extern const unsigned long INFINITE_TIME;`

**Comment by noloader** [comment]
@irwir,

The warning complains about just `const`. Can you try building with `static const`. If that does not work, can you try with just `static`?

**Comment by irwir** [comment]
`INFINITE_TIME` variable is never used in the library or mentioned in comments.
Hence the warnings are valid and should not be ignored or disabled.
An external variable should be safe enough (and thread safe) because of being a constant.

`static unsigned long INFINITE_TIME = ULONG_MAX;`
compiles quietly, but makes a modifiable value.

> #define INFINITE_TIME ULONG_MAX
is a good option if the value has to be in the library.

**Comment by noloader** [comment]
@irwir,

Here's another possibility. Visual Studio 2017 support's C++17's inline variable. We may be able to declare the variable as inline. Once declared inline, it behaves like an inlined function. We should not get diagnostics for it.

Also see [Microsoft C/C++ language conformance by Visual Studio version](https://learn.microsoft.com/en-us/cpp/overview/visual-cpp-language-conformance) and [P0386R2, Inline Variables](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0386r2.pdf).

**Comment by irwir** [comment]
> Did `static const` achieve the goal of squashing the warning?

No, it did not.

> Visual Studio 2017 support's C++17's inline variable.

Ability to build the library in old C++ compilers might be more valuable than a fix for this tiny issue.

**Comment by noloader** [comment]
@irwir ,

Does `constexpr` resolve the issue under Visual Studio? If so, we can probably use it instead.

**Comment by noloader** [comment]
@irwir,

I cannot get this warning to trigger using Visual Studio 2022 from a Developer Prompt. The `/w35264` drops C5264 down to warning level 3:

![image](https://user-images.githubusercontent.com/3538226/212786610-d150dfcd-87c4-449b-a9aa-b75b6ac1fcee.png)

I am using `cl.exe` version:

```cmd
c:\Users\Jeff\Desktop\cryptopp-fork>cl.exe
Microsoft (R) C/C++ Optimizing Compiler Version 19.33.31630 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.
```

Can you please test the `constexpr` when you have a moment?

**Comment by noloader** [comment]
Ok, this was cleared via [Pull Request #1186](https://github.com/weidai11/cryptopp/pull/1186).

Good luck will all the Visual Studio warnings due to C5264.
