### ISSUE TITLE
Anyone had success compiling the library with clang-cl?

### ISSUE THREAD

**Issue by ValeV008** [weidai11/cryptopp#1192]
On wiki it says that on Windows, clang is not officially supported ([source](https://www.cryptopp.com/wiki/Compilers)). Still, I am curious if there are some unofficial ways of making it compilable with clang-cl?

Thanks.

**Comment by ValeV008** [comment]
For future generations, seem like adding "#define CRYPTOPP_DISABLE_ASM 1" to file config.h seems to do the trick. Don't forget to test it.

**Comment by noloader** [comment]
Please ask questions on the mailing list.

**Comment by vovus** [comment]
the way i have done it with vcpkg, self-tests all passed - https://github.com/microsoft/vcpkg/issues/37227
