### ISSUE TITLE
Fatal Error compiling under MSVC with avx2 enabled (/arch:AVX2) 

### ISSUE THREAD

**Issue by krawq** [weidai11/cryptopp#1198]
OS: Windows 11 x64
Cryptopp version : Last vcpkg available version 8.7.0#3
Build: Last MSVC (2022 17.5) x64
Error : `\include\cryptopp\misc.h(83): fatal error C1083: Cannot open include file: 'x86intrin.h': No such file or directory`

issue with this:

```
#if defined(__BMI__)
# include <x86intrin.h>
# include <immintrin.h>
#endif  // GCC and BMI
```
The x86intrin.h header is not provided by MSVC.
The `_BMI_ `variable is not specific to GCC because the qsimd.h header file on MSVC defines this:

```
#  ifdef __AVX2__
// MSVC defines __AVX2__ with /arch:AVX2
#    define __F16C__                        1
#    define __RDRND__                       1
#    define __FMA__                         1
#    define __BMI__                         1          **>> Here its set to 1**
#    define __BMI2__                        1
#    define __MOVBE__                       1
#    define __LZCNT__                       1
#  endif
```

Fix : 
```
#if defined(__BMI__)
#if defined(__GNUC__)
# include <x86intrin.h>
#endif
# include <immintrin.h>
#endif  // GCC and BMI
```

**Comment by noloader** [comment]
> The _BMI_ variable is not specific to GCC because the qsimd.h header file on MSVC defines this

Hmmm... that's new.

I'll get it fixed this weekend.

**Comment by noloader** [comment]
Thanks again @krawq.

This should be cleared at [Commit ddb8f36e8894](https://github.com/weidai11/cryptopp/commit/ddb8f36e8894).
