### ISSUE TITLE
Make 3des

### ISSUE THREAD

**Issue by GeneThomas** [weidai11/cryptopp#1200]
Thanks for your library, I like the architecture.

Triple DES is a useful cipher, based on the ancient DES which is good thing for ciphers. It is used in the payments industry https://en.wikipedia.org/wiki/EMV . Presently it is difficult to find “3DES” in your library. 

Please have a 3des.h with class TDES commented as “3DES” that supports 128 bit or 192 bit keys (2 key or 3 key versions)

* State the version of the Crypto++ library (Crypto++ 7.0, Master, etc)
8.7.0

**Comment by itamar124812** [comment]
The triple des is already implemented in the des.h header.
You can read about how to use it here - https://www.cryptopp.com/wiki/TripleDES#3-Key_TripleDES.

**Comment by itamar124812** [comment]
> [GeneThomas](/GeneThomas)

#The triple des is already implemented in the des.h header.
You can read about how to use it here - https://www.cryptopp.com/wiki/TripleDES#3-Key_TripleDES.

**Comment by noloader** [comment]
Please ask questions on the mailing list.
