### ISSUE TITLE
Crush on RPI Only when we are using gdb to debug

### ISSUE THREAD

**Issue by kenkit** [weidai11/cryptopp#1201]
https://github.com/weidai11/cryptopp/blob/a21bab3255dd3c7708d8af4cc065e3e2464db48a/cpu.cpp#L1140

Hi, I'm running a raspberry pi 4B 8GB version.  When I run the program normally it runs without issue, but when I load it through gdb it crushes when running ``CPU_ProbePMULL(),  CPU_ProbeAES() CPU_ProbeSHA1() CPU_ProbeSHA256() `` .
I had to comment out those functions for debugging to be possible.
Cryptopp is built into a shared library which my app loads on demand.

**Comment by noloader** [comment]
I don't know what "crush" is. 

The probes are expected. If an instruction is not supported, then a SIGILL is saised and trapped to deactivate the feature.

Please ask questions on the mailing list in the future.
