### ISSUE TITLE
improve CRC32C_Update_SSE42 for x86-64.

### ISSUE THREAD

**Issue by pawelsopensource** [weidai11/cryptopp#1202]
hi,
the x86-64 provides crc32q instruction (aka _mm_crc32_u64) which consumes 8 bytes at once. with this opcode CRC32C_Update_SSE42() works ~2x faster on my machine (amd ryzen7 1700 3GHz).

**Comment by pawelsopensource** [comment]
```
void CRC32C_Update_SSE42(const byte *s, size_t n, word32& c)
{
    word32 u = c; // no need to update cache memory in each loop cycle
    for(; !IsAligned<uint64_t>(s) && n > 0; s++, n--)
        u = _mm_crc32_u8(u, *s);
    uint64_t q = u; // crc32q result is stored on 64-bits (zero-extended)
#if defined(__GNUC__) || defined(__clang__)
    #pragma GCC unroll 8
#endif
    for(; n >= 8; s+=8, n-=8)
        q = _mm_crc32_u64(q, *reinterpret_cast<const uint64_t*>(s));
    u = static_cast<word32>(q);
    for(; n > 0; s++, n--)
        u = _mm_crc32_u8(u, *s);
    c = u;
}
```

**Comment by noloader** [comment]
Thanks @pawelsopensource .

Looking at the source at https://github.com/weidai11/cryptopp/blob/master/crc_simd.cpp#L151, I'm wondering why we were/are predicated on the 32-bit version.

It was probably related to porting the C++ version to intrinsics.

**Comment by noloader** [comment]
```C
    for(; n >= 8; s+=8, n-=8)
        q = _mm_crc32_u64(q, *reinterpret_cast<const uint64_t*>(s));
```
You are probably going to get better code generation by chaining the `_mm_crc32_u64` together. Also see [Commit c40b43346b66](https://github.com/weidai11/cryptopp/commit/c40b43346b66).

Prior to c40b43346b66, the code generated used 3 or 4 intermediate stores, if I recall correctly.

**Comment by pawelsopensource** [comment]
> ```c
>     for(; n >= 8; s+=8, n-=8)
>         q = _mm_crc32_u64(q, *reinterpret_cast<const uint64_t*>(s));
> ```
> 
> You are probably going to get better code generation by chaining the `_mm_crc32_u64` together. Also see [Commit c40b43346b66](https://github.com/weidai11/cryptopp/commit/c40b43346b66).
> 
> Prior to [c40b433](https://github.com/weidai11/cryptopp/commit/c40b43346b66455462e38d2b338200559eccdc16), the code generated used 3 or 4 intermediate stores, if I recall correctly.

chaining looks like a workaround for 'word32& c' updating (stores). my version uses local variable (register) for current crc state and updates the result at the end. clang-16/gcc-11 loops unrolling seem to produce quite optimal code.

**Comment by pawelsopensource** [comment]
patch looks fine.
64-bit path with manual 4x loop unroll improves CRC32C_Update_SSE42 from 3635MiB/s to 7072MiB/s on my machine (according to ./cryptest.exe b 5 3). manual 8x loop unroll gives 7663MiB/s, better 64B L1 data cache utilization and less loops?.

**Comment by noloader** [comment]
Thanks @pawelsopensource.

This should be cleared at [Commit ee247f86a289](https://github.com/weidai11/cryptopp/commit/ee247f86a289).

I did not add the GCC extension for loop unrolling. Would you mind carrying that patch locally?

**Comment by pawelsopensource** [comment]
one more minor change, _mm_crc32_u64 result needs a cast to fix msvc warning:
crc_simd.cpp(170): warning C4244: '=': conversion from 'unsigned __int64' to 'CryptoPP::word32', possible loss of data

**Comment by pawelsopensource** [comment]
crc32 opcode can store result in 64-bit (register) but only lower 32-bits are used because it's still a crc32 algorithm. cast is safe.
https://www.felixcloutier.com/x86/crc32

**Comment by noloader** [comment]
Ok, lets see if we can get away with it.

Cleared at [Commit e1c149f9a435](https://github.com/weidai11/cryptopp/commit/e1c149f9a435).

**Comment by pawelsopensource** [comment]
problem was in line 170:  v = _mm_crc32_u64(....

**Comment by pawelsopensource** [comment]
someone could use https://clang.llvm.org/docs/DiagnosticsReference.html#wshorten-64-to-32 and -Werror, so please just do the correct cast:
v = (word32)_mm_crc32_u64(...
