### ISSUE TITLE
Reading RSA keys across platforms between CryptoPP and Python,  not in asn1Spec

### ISSUE THREAD

**Issue by srinivasramanujan** [weidai11/cryptopp#1205]
I have an application written in C++ using CryptoPP is trying to communicate with Python. If Python generates the Key, CryptoPP won't import it and gives a BER Decode Error, and also if I generate the key in CryptoPP it won't import in Python.

This may also need to be used on Android, IoS, and Java. So I need a method that can work across platforms.

In python I use the rsa module    pip install rsa
I am using size as 4096 bits

import rsa
def generate_keys(name,size):
    (pub, priv) = rsa.newkeys(size)
    with open(name + 'pub_key.pem', 'wb') as p:
        p.write(pub.save_pkcs1('PEM'))
    with open(name + 'priv_key.pem', 'wb') as p:
        p.write(priv.save_pkcs1('PEM'))

def load_keys(name):
    with open(name + 'pub_key.pem', 'rb') as p:
        pub = rsa.PublicKey.load_pkcs1(p.read())
    with open(name + 'priv_key.pem', 'rb') as p:
        priv = rsa.PrivateKey.load_pkcs1(p.read())
    return priv, pub

In CryptoPP I compiled with the PEM Pack and try to load the certificate:

CryptoPP:RSA::PublicKey publicKey1;
CryptoPP::FileSource publicKeySource(publicKeyFileName.c_str(), true);
CryptoPP::PEM_Load(publicKeySource, publicKey1);

This throws the BER Decode Error. 

If instead I generate the keys in CryptoPP and try to use them in Python:

void generate_keys(std::string name)
{
    try{
        std::string privateKeyFileName = name+"privatekey.pem";
        std::string publicKeyFileName = name+"publickey.pem";    

        // Generate private key
        CryptoPP::AutoSeededRandomPool rng;
        CryptoPP::InvertibleRSAFunction params;
        params.GenerateRandomWithKeySize(rng, 4096);
        CryptoPP::RSA::PrivateKey privateKey1(params);
        

        // Save private key to PEM file
        CryptoPP::FileSink privateKeyFile(privateKeyFileName.c_str());
        CryptoPP::PEM_Save(privateKeyFile, privateKey1);

        // Extract public key from private key
        CryptoPP::RSA::PublicKey publicKey1(privateKey1);
        

        // Save public key to PEM file
        CryptoPP::FileSink publicKeyFile(publicKeyFileName.c_str());
        CryptoPP::PEM_Save(publicKeyFile, publicKey1);
        
 
    }
    catch(...)
    {
        std::cout<<"Error generating PEM keys";
    }
}

Traceback (most recent call last):
  File "pytest.py", line 280, in <module>
    TEST_PRIV_KEY, TEST_PUB_KEY = load_keys('test')
  File "pysec.py", line 25, in load_keys
    pub = rsa.PublicKey.load_pkcs1(p.read())
  File "Python\Python39\lib\site-packages\rsa\key.py", line 124, in load_pkcs1
    return method(keyfile)
  File "Python39\lib\site-packages\rsa\key.py", line 330, in _load_pkcs1_pem
    return cls._load_pkcs1_der(der)
  File "Python\Python39\lib\site-packages\rsa\key.py", line 297, in _load_pkcs1_der
    (priv, _) = decoder.decode(keyfile, asn1Spec=AsnPubKey())
  File "Python\Python39\lib\site-packages\pyasn1\codec\ber\decoder.py", line 1581, in __call__
    value, substrate = concreteDecoder.valueDecoder(
  File "Python\Python39\lib\site-packages\pyasn1\codec\ber\decoder.py", line 609, in valueDecoder
    component, head = decodeFun(head, componentType, **options)
  File "Python\Python39\lib\site-packages\pyasn1\codec\ber\decoder.py", line 1618, in __call__
    raise error.PyAsn1Error(
pyasn1.error.PyAsn1Error: <TagSet object, tags 0:32:16> not in asn1Spec: <Integer schema object, tagSet <TagSet object, tags 0:0:2>>

**Comment by noloader** [comment]
On Wed, Apr 19, 2023 at 10:02 AM srinivasramanujan ***@***.***>
wrote:
>
> I have an application written in C++ using CryptoPP is trying to
communicate with Python. If Python generates the Key, CryptoPP won't import
it and gives a BER Decode Error.
>
> In python I use the rsa module pip install rsa
> I am using size as 4096 bits
>
> import rsa
> def generate_keys(name,size):
> (pub, priv) = rsa.newkeys(size)
> with open(name + 'pub_key.pem', 'wb') as p:
> p.write(pub.save_pkcs1('PEM'))
> with open(name + 'priv_key.pem', 'wb') as p:
> p.write(priv.save_pkcs1('PEM'))
>
> def load_keys(name):
> with open(name + 'pub_key.pem', 'rb') as p:
> pub = rsa.PublicKey.load_pkcs1(p.read())
> with open(name + 'priv_key.pem', 'rb') as p:
> priv = rsa.PrivateKey.load_pkcs1(p.read())
> return priv, pub
>
> In CryptoPP I compiled with the PEM Pack and try to load the certificate:
>
> CryptoPP:RSA::PublicKey publicKey1;
> FileSource publicKeySource(publicKeyFileName.c_str(), true);
> PEM_Load(publicKeySource, publicKey1);
>
> This throws the BER Decode Error.
>
> If instead I generate the keys in CryptoPP and try to use them in Python:
>
> void generate_keys(std::string name)
> {
>   using namespace CryptoPP;
>
>   try{
>
>     std::string privateKeyFileName = name+"privatekey.pem";
>     std::string publicKeyFileName = name+"publickey.pem";
>
>     // Generate private key
>     AutoSeededRandomPool rng;
>     InvertibleRSAFunction params;
>     params.GenerateRandomWithKeySize(rng, 4096);
>     RSA::PrivateKey privateKey1(params);
>
>     // Save private key to PEM file
>     FileSink privateKeyFile(privateKeyFileName.c_str());
>     PEM_Save(privateKeyFile, privateKey1);
>
>     // Extract public key from private key
>     RSA::PublicKey publicKey1(privateKey1);
>
>     // Save public key to PEM file
>     FileSink publicKeyFile(publicKeyFileName.c_str());
>     PEM_Save(publicKeyFile, publicKey1);
>
>   }
>   catch(...)
>   {
>     std::cout<<"Error generating PEM keys";
>   }
> }
>
> Traceback (most recent call last):
> File "pytest.py", line 280, in
> MASTER_PRIV_KEY, MASTER_PUB_KEY = security.load_keys('master')
> File "pysec.py", line 25, in load_keys
> pub = rsa.PublicKey.load_pkcs1(p.read())
> File "Python\Python39\lib\site-packages\rsa\key.py", line 124, in
load_pkcs1
> return method(keyfile)
> File "Python39\lib\site-packages\rsa\key.py", line 330, in _load_pkcs1_pem
> return cls._load_pkcs1_der(der)
> File "Python\Python39\lib\site-packages\rsa\key.py", line 297, in
_load_pkcs1_der
> (priv, _) = decoder.decode(keyfile, asn1Spec=AsnPubKey())
> File "Python\Python39\lib\site-packages\pyasn1\codec\ber\decoder.py",
line 1581, in call
> value, substrate = concreteDecoder.valueDecoder(
> File "Python\Python39\lib\site-packages\pyasn1\codec\ber\decoder.py",
line 609, in valueDecoder
> component, head = decodeFun(head, componentType, **options)
> File "Python\Python39\lib\site-packages\pyasn1\codec\ber\decoder.py",
line 1618, in call
> raise error.PyAsn1Error(
> pyasn1.error.PyAsn1Error: <TagSet object, tags 0:32:16> not in asn1Spec:
<Integer schema object, tagSet <TagSet object, tags 0:0:2>>

Crypto++ keys format are either (1) PKCS #1 for public keys, and (1) PKCS
#8 for private keys. They have worked for about the last 30 years. I doubt
something suddenly changed to break things.

I suspect the problem is DER vs. PEM encoding.From the Python traceback, it
looks like you are trying to read a PEM encoded key using a ASN.1/DER
routine.

    File "Python\Python39\lib\site-packages\rsa\key.py", line 297, in
_load_pkcs1_der

So you should save the Crypto++ key using a DER encoding. Or, you can
continue to PEM encode the key, but you need to use a Python PEM routine to
read it.

You might want to have a look at
https://www.cryptopp.com/wiki/Keys_and_Formats and
https://www.cryptopp.com/wiki/PEM_Pack . The short of it is, one of these
will likely work with Python:

    RSA::PublicKey publicKey1(privateKey1);
    publicKey1.Save(...); // DER encoded subjectPublicKeyInfo

Or:

    RSA::PublicKey publicKey1(privateKey1);
    publicKey1.DEREncodePublicKey(...); // DER encoded RSA public key

Jeff

**Comment by noloader** [comment]
Please stop asking questions in our bug tracker. Please use the mailing list.
