### ISSUE TITLE
Strange check

### ISSUE THREAD

**Issue by irwir** [weidai11/cryptopp#1206]
https://github.com/weidai11/cryptopp/blob/899dea907103075cf7e68b16dc81aadd4ce83749/integer.cpp#L3525
By definition `nbytes` should be 1 or greater.

**Comment by noloader** [comment]
Thanks @irwir.

Yeah, something looks a little sideways.

Looking at it:

```C++
if (nbytes)
    buf[0] = (byte)Crop(buf[0], nbits % 8);
```

It looks like the intention is to keep the low order bits, and mask-out the upper bits.

I'm wondering if it should not be:

```C++
if (nbits % 8)
    buf[0] = (byte)Crop(buf[0], nbits % 8);
```

@mouse07410, any thoughts?

**Comment by irwir** [comment]
https://github.com/weidai11/cryptopp/blob/899dea907103075cf7e68b16dc81aadd4ce83749/integer.cpp#L3522
It might make more sense if instead of questionable `nbits/8 + 1` it was more obvious `(nbits + 7)/8`

**Comment by noloader** [comment]
So the description of `Randomize` says (https://github.com/weidai11/cryptopp/blob/master/integer.h#L447):

The random integer created is uniformly distributed over <tt>[0, 2<sup>bitCount</sup>]</tt>.

If someone passes 0 bits, then the the caller should get either 0 or 1 because 2^0 = 1. If we switch to `(nbits + 7)/8`, then we can only return 0. But I am not sure the existing method handles that properly, either.

Lt me look at it some more.

**Comment by noloader** [comment]
Yeah, we don't handle that case properly now:

```
$ cat test.cxx
#include <iostream>
#include <iomanip>
#include "integer.h"
#include "osrng.h"

int main(int argc, char* argv[])
{
    using namespace CryptoPP;

    AutoSeededRandomPool prng;
    Integer n;

    for (size_t i=0; i<128; i++)
    {
      n.Randomize(prng, 0);
      std::cout << (n==0 ? "0" : "1") << " ";
    }
    std::cout << std::endl;
    return 0;
}

$ g++ -o test.exe -g2 -O3 test.cxx ./libcryptopp.a
$ ./test.exe
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
```

**Comment by irwir** [comment]
https://github.com/weidai11/cryptopp/blob/899dea907103075cf7e68b16dc81aadd4ce83749/gf2n.cpp#L82-L89
Without digging too deep into the code, my guess is that the check for nbytes is to be removed.
`nbits % 8` is for shift count for bit mask. If zero bits were requested, `Crop` will return 0.

**Comment by irwir** [comment]
> The random integer created is uniformly distributed over [0, 2<sup>bitCount</sup>].

[0, 2<sup>bitCount</sup>[
Or like this: [0, 2<sup>bitCount</sup>-1]

**Comment by noloader** [comment]
This should be cleared at [Commit 6ac6668b2976](https://github.com/weidai11/cryptopp/commit/6ac6668b2976).
