### ISSUE TITLE
Deterministic DSA and ECDSA Signatures

### ISSUE THREAD

**Issue by noloader** [weidai11/cryptopp#121]
We've had some suggestions/requests to add deterministic DSA and ECDSA signatures to the library. [RFC 6769](https://tools.ietf.org/html/rfc6979) discusses the reasons for them in-depth. The abbreviated version is:
- hardening - ensure **_`k`**_ is not accidentally weak
- testability - repeatable results to ensure proper operation
- compatibility - completely compatible with existing schemes

I think its a good idea, especially on resource constrained devices, like IoT gadgets. (I'm not sure how much signing they will do, but they will be able to do it if needed)

The mailing list discussion is available at [Deterministic DSA and ECDSA Signatures](https://groups.google.com/forum/#!topic/cryptopp-users/t-EaRGNLn4s).

A thread on the [TLS Working Group](https://www.ietf.org/mail-archive/web/tls/current/msg19111.html) mailing list is also discussing the change in the context of the IETF and TLS. The [CFRG](http://irtf.org/cfrg) may provide feedback or make a recommendation.

If we decide to move forward, I believe the way to approach this is similar to a new <strike>signature encoding method</strike> `SignatureScheme`. To that end, the library has an interface for this operation in <strike>`pubkey.h`</strike> `gfpcrypt.h` by way of <strike>[`PK_DeterministicSignatureMessageEncodingMethod`](http://www.cryptopp.com/docs/ref/class_p_k___deterministic_signature_message_encoding_method.html)</strike> [`DL_Algorithm_GDSA`](https://www.cryptopp.com/docs/ref/class_d_l___algorithm___g_d_s_a.html). Expand the inheritance diagram for the best view.

This ticket tracks the request and the progress.

**Comment by DevJPM** [comment]
@noloader I don't think this is the right approach.

a) You can't influence the generation of the `k` if you have a message encoding class.
b) We don't want to change message encoding here, but k generation.

For discrete logarithm (DL) based signature schemes, `k` is generated [here](https://github.com/weidai11/cryptopp/blob/master/pubkey.h#L1439), in `DL_SignerBases`'s `SignAndRestart()` function.

Changing the method of generation would be simplest there, however it's highly delicate as many classes depend on this one.

So I see a few options:

1) Don't do deterministic <Input favorite DL signature method> at all and leave things like they are
2) Change the interface of SignAndRestart()
3) Introduce a `protected` variable into `DL_SignerBase` that toggles the different code paths
4) Add a compile-time option in config.h and force the decision at compile-time.
5) Introduce another template parameter to `DL_SignerBase` to handle flags.

I have to admit, 4) sounds best.

**Comment by denisbider** [comment]
Either 2, 3, or 5 sounds best to me.

1 (no change) means the library gets left behind. Might as well not maintain it.

4 (compile-time option) sounds like a cop-out - too afraid to change interface to serve recognized requirements.

**Comment by denisbider** [comment]
In many cases, I have found, the highly articulated abstractions of Crypto++ hinder usage, understanding, and maintenance. They are bewildering to face.

But this is a devil that has to be wrangled. If the abstractions do not fit requirements, they have to change.

**Comment by droark** [comment]
Ahhh, I probably should've looked at this before I made my PR. :) Anyway, I just submitted an implementation of 6979 that I [originally created for Armory](https://github.com/etotheipi/BitcoinArmory/commit/9b25d493eb1fa99a31dd7000ac3bb7f4aeb9a6eb). I basically spent days hacking through the source and just created a DL_SignerImpl child that implemented the algorithm. I doubt it's the nicest solution for somebody trying to pick up Crypto++. It seems to work fine, though. I'd love to see it get merged but I totally understand if the team has a different plan in mind.

**Comment by droark** [comment]
Also, regarding the five options that are presented, I also think 2, 3 & 5 sound best. I suppose the final answer depends on how much refactoring the team wants to do. Seriously, I remember hacking through the codebase for at least two days before I was able to start writing a patch. The only nice thing was that I was able to borrow some code and just change one line such that it hopped into the 6979-specific code. (Then again, there were scary comments that didn't seem attached to reality. The codebase really could use a fair bit of cleaning.)

**Comment by mouse07410** [comment]
Am I the only one who thinks that option 5 is the best one?

**Comment by droark** [comment]
Well, 5 is probably the best if one just wants code that works. It's a horribly ugly solution, though, or at least, it perpetuates an ugly solution.

**Comment by denisbider** [comment]
Crypto++ has historically solved this kind of problem with template parameters, though. It doesn't seem ugly to me, unless we accept that a lot of other things Crypto++ does with template parameters is ugly.

**Comment by droark** [comment]
It's ugly when you're trying to trace the code from scratch and understand what exactly is going into everything. :) But anyway....

**Comment by denisbider** [comment]
Yeah, figuring out what code is used for what is a general problem with current Crypto++ design. It seems to me the library tries to be too clever about reusing things.

I don't see an easy and compelling fix given this existing design, however. :-/

**Comment by droark** [comment]
Hello. I played with the code a bit today and settled on a design. It's basically option 5 (more templates). It's not ideal but it does seem to work. As a bonus, I don't have to create new files; I can just stick everything into pubkey.h. I'll submit a new version in a few days. I'm just going to rewrite everything from scratch to ensure that there are no legal issues with the original Armory code.

Thanks.

**Comment by noloader** [comment]
@droark - can you reach out to me off-list so we can start working on the integration of this pr?
You can reach me at noloader, gmail account.

@denisbider, @DevJPM - do you guys want to be CC'd on this? Your feedback would probably be very helpful.

**Comment by mouse07410** [comment]
And as usually, we want BouncyCastle to pick it, if it's not there. Interoperability is a good thing to have! ;-)

Sent from my iPad

On Feb 28, 2016, at 07:15, Jeffrey Walton <notifications@github.com<mailto:notifications@github.com>> wrote:


@droark<https://github.com/droark> - can you reach out to me off-list so we can start working on the integration of this pr?
You can reach me at noloader, gmail account.

@denisbider<https://github.com/denisbider>, @DevJPM<https://github.com/DevJPM> - do you guys want to be CC'd on this? Your feedback would probably be very helpful.

**Comment by DevJPM** [comment]
@noloader yes please. I'll do my best to provide feedback.

**Comment by noloader** [comment]
I've started adding the commits for the Test Vectors. See, for example, [Commit 75555369d96457ae](http://github.com/weidai11/cryptopp/commit/75555369d96457ae79c060076fcbc3cfa584ece2). We can test them with:

* `./cryptest.exe tv all` (all test vectors)
* `./cryptest.exe tv dsa_rfc6979`
* `./cryptest.exe tv ecdsa_rfc6979`

I'm still working on the ECDSA test file.

I expect Doug's check-in will be available soon.

**Comment by noloader** [comment]
I pinged Wei about the names. Here is the message transcript:

> [JW] What do you recommend when we _lack_ a unique name for the Object Registry? I.e., DSA vs DSA with Deterministic Signatures? As far as I know, there is no SCAN-like name representing and differentiating them.
> [WD] We just have to make up a name
> [JW] OK, thanks. I've been trying to follow http://www.weidai.com/scan-mirror/sig.html, but none of them look too appealing. In the absence of purview, how is DDSA (Deterministic-DSA) or DSA-IETF/SHA1 (or maybe DSA-DET/SHA1)?
> [WD] Maybe DSA-RFC6979/SHA1? there is already DSA-1363
> [WD] Assuming that's the right RFC number

**Comment by noloader** [comment]
I got to speak with RFC 6979's author. TP liked `DSA-RFC6979/SHA1`, so I think that's what we should eventually use here. He did not make a recommendation given the landscape and choices, but it was an approval of sorts given the circumstances.

**Comment by mouse07410** [comment]
Very nice. 

Do we want DSA-rfc6979/SHA256 as well (or instead of...)?

**Comment by noloader** [comment]
> Do we want DSA-rfc6979/SHA256 as well (or instead of...)?

Yes, from SHA-1 through SHA-512 (and eventually SHA-3, I imagine).

**Comment by droark** [comment]
Thanks for the update, everyone, and sorry about being MIA. Been busy with this & that. I'll fold all this into the code I'll be writing next week.

**Comment by noloader** [comment]
A new branch was created for this task: [det-sig](http://github.com/weidai11/cryptopp/tree/det-sig). The patch has been merged into it at [Commit 875ea750fafbeb23](http://github.com/weidai11/cryptopp/commit/875ea750fafbeb23b7c889dacc7e15365d53cc20).

**Comment by noloader** [comment]
Cleared at [Commit 7e427805174b9fc6](http://github.com/weidai11/cryptopp/commit/7e427805174b9fc672caf838f9e456a09be32043).

**Comment by EduardoMiravalls** [comment]
I know this has been closed for a long time, but... what happened with `ecdsa_rfc6979.txt` test vector file?

**Comment by noloader** [comment]
@EduardoMiravalls,

There is none at the moment.

I looked into adding some EC-based test vector files some time ago. I seem to recall (if my memory serves me) that they were trickier to instantiate through a factory method. An aggravating circumstance was/is, a lot of the algorithmic names are not standardized.

The test framework reads the text file via `datatest.cpp` and finds the `AlgorithmType` and `Name` in the text file. Then the machinery tries to locate a factory for it. It is easy to do with, say `AlgorithmType=SymmetricCipher` and `Name=ARIA/ECB`.

The problem with EC is, we don't have something that handles the field. For example, in the case of ECDSA, we would have `AlgorithmType=Signature` and `Name=ECDSA/SHA-1`. But where is the field? Do we do `Name=ECDSA/SHA-1/secp160r1` or is there another way to handle the name?

What I've been doing is either (1) add a `TestData/*.dat` file and read the data directly knowing the parameters like `ECDSA/SHA-1` and `secp160r1`; and (2) skip the file and just hard code the test into one of the `validate-XXX.cpp` files. Deterministic ECDSA took the second approach.

The gap is not too large, and we can probably hack something together.

**Comment by EduardoMiravalls** [comment]
Ahh, so I should be looking in `validat2.cpp`, thank you!

I tried grepping the code base for some of the examples of RFC6979 for ECDSA, but I was only finding the DSA examples, and the first comments in this issue confused me. I was thinking the test vectors got deleted or something.
