### ISSUE TITLE
Elimination of cryptest.vcxproj.user

### ISSUE THREAD

**Issue by irwir** [weidai11/cryptopp#1213]
This file is silently creataed by VS. In most cases such automatically generated files could be safely removed.
Stackoverflow [discussion ](https://stackoverflow.com/questions/13015265/vcxproj-in-source-control#13015434) includes MSDN link.

**Comment by noloader** [comment]
@irwir,

Agreed, but `cryptest.vcxproj.user` is special. It sets up the IDE for debugging:

```xml
﻿<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <LocalDebuggerCommandArguments>v</LocalDebuggerCommandArguments>
  </PropertyGroup>
</Project>
```

Without out that option, running `cryptest.exe` under the debugger simply exits with the help message.

We're going to keep that one.

**Comment by irwir** [comment]
Thanks for the explanation. In that case the file has to stay and the issue to be closed.
Additionally, running the `cryptest` solution in the current VS 2022 debug 64-bit build got this:
1. Compiler warning

> validat2.cpp(1177,69): warning C4244: 'argument': conversion from 'CryptoPP::word' to 'long', possible loss of data

2. Quite a few asserts. Is this by design? The first one:

> Assertion failed: D:\e\tmp\d\tmp\cryptopp-master\integer.cpp(4451): CryptoPP::a_times_b_mod_c

**Comment by irwir** [comment]
Total number of fired asserts is several dozens - such as zero values or empty strings. Of course, these would be seen only in debug builds.
