### ISSUE TITLE
implementing request to add new build system: scons

### ISSUE THREAD

**Issue by SeanTolstoyevski** [weidai11/cryptopp#1225]
Hi Crypto++ Developers,

I would like to add [scons](https://scons.org/doc/4.0.0/HTML/scons-user.html) support to cryptopp as well as makefile support. Scons is written in python programming language and has a very understandable and simple structure.

Integration of one of the modern build systems like Scons can solve all build problems under Windows. Additionally, it's written with python syntax, which is pretty straightforward according to a makefile. It doesn't have its own syntax like Cmake or Makefile. For example, someone who is familiar with the compiler toolset for iOS can quickly implement Scons for iOS.

Now let me talk about a problem of developers working / having to work on Windows.
One of the current compilation issues is that even with MinGW64 installed on the Windows machine, it is not possible to compile the project without opening Git Bash or working on a tool like MSYS2.
With scons support, users can compile by installing python and scons on their machines if they wish. Tools like Git Bash are not needed.

Before I go into more details, I'd like to know if this is reasonable. If accepted, I can take over the maintenance of the Scons scripts (at least I will for MSVC and MinGW64 on Windows).

**Comment by noloader** [comment]
You are welcomed to use Scons. Lots of folks use alternate build systems.

You can share it on your GitHub. We can put together a [wiki page](https://www.cryptopp.com/wiki/) on it.

But please, make it clear you are supporting it.
