### ISSUE TITLE
Can't compile Windows vs2019 c2238 c2059 c2143 errors 

### ISSUE THREAD

**Issue by Clydeston** [weidai11/cryptopp#1229]
Hello had this working on a separate project using vcpkg on windows vs2019 v142 build tools, but since I've switched to a different project I'm now getting these errors below. I've seen a few other issues saying this might be a compiler bug, but it compiles  on a different project with identical settings? Any help appreciated.
`Error	C2238	unexpected token(s) preceding ';'	seckey.h	56	`
`Error	C2059	syntax error: 'constant'	seckey.h	56	`
`Error	C2143	syntax error: missing ';' before '}'	seckey.h	56	`

I've tried changing my cpp versions but the error still remains.

**Comment by Clydeston** [comment]
Any help at all this? Using latest release 8.8.0

**Comment by noloader** [comment]
Please contact the vcpkg folks. I have no idea what they are doing.

Or, use [Visual Studio](https://www.cryptopp.com/wiki/Visual_Studio) or [MSBuild](https://www.cryptopp.com/wiki/MSBuild_(Command_Line)).
