### ISSUE TITLE
C4996 warning due to std::reverse_copy on Microsoft platforms

### ISSUE THREAD

**Issue by noloader** [weidai11/cryptopp#123]
We recently cut-in [little-endian Integers](https://github.com/weidai11/cryptopp/commit/f8091d9a156bbd9cd8aa7fa4bc7cda7a934ad64e). On Microsoft platforms, use of ***`std:reverse_copy`*** is causing a C4996 warning:

```
1>c:\Program Files\...\VC\include\algorithm(2184): warning C4996: 'std::_Reverse_copy': Function call with parameters that may be unsafe - this call relies on the caller to check that the passed values are correct. To disable this warning, use -D_SCL_SECURE_NO_WARNINGS. See documentation on how to use Visual C++ 'Checked Iterators'
1>          c:\...\VC\include\algorithm(2168) : see declaration of 'std::_Reverse_copy'
1>          integer.cpp(2898) : see reference to function template instantiation '_OutIt std::reverse_copy<const byte*,unsigned char*>(_BidIt,_BidIt,_OutIt)' being compiled
1>          with
1>          [
1>              _OutIt=unsigned char *,
1>              _BidIt=const byte *
1>          ]
```

The offending code is:

```
Integer::Integer(const byte *encodedInteger, size_t byteCount, Signedness s, ByteOrder o)
{
    if(o == LITTLE_ENDIAN_ORDER)
    {
        SecByteBlock block(byteCount);
        std::reverse_copy(encodedInteger, encodedInteger+byteCount, block.begin());

        Decode(block.begin(), block.size(), s);
        return;
    }
    ...
}
```
I think we need to find a Microsoft overload that allows us to specify the destination buffer size. Or we need to use the library's [ByteReverse from misc.h](https://github.com/weidai11/cryptopp/blob/master/misc.h#L1718):

    template <class T>
        void ByteReverse(T *out, const T *in, size_t byteCount);

**Comment by DevJPM** [comment]
@noloader I don't think `ByteReverse<>` is the right choice here.

`ByteReverse<>` iterates over all the objects of type `T` and individually byte reverses them.

So {1,2,3,4} would still be {1,2,3,4}. 

`std::reverse_copy` OTOH takes your list and reverses it, e.g. it makes {1,2,3,4} to {4,3,2,1}, which is what we need here.

Luckily Microsoft already proposed a fix [on MSDN](https://msdn.microsoft.com/de-de/library/ttcz0bys.aspx).

If you look at the second code sample, in the last line. `checked_array_iterator` apparently can be used to fix the warning. All we have to do would be to replace the `block.begin()` by `checked_array_iterator<byte*>(block.begin(),byteCount)`

**Comment by noloader** [comment]
> However, it appears to be the case that GCC (and other compilers) may not support 

Yeah, we should probably split things here (as much as I dislike doing it):

```
// I believe 14.10 is the version we need/want
#if (CRYPTOPP_MSC_VERSION >= 1410)
    std::reverse_copy(encodedInteger, encodedInteger+byteCount, 
        stdext::make_checked_array_iterator(block.begin(), block.size()));
#else
    std::reverse_copy(encodedInteger, encodedInteger+byteCount, block.begin());
#endif
```

**Comment by noloader** [comment]
How about a plain old [`reverse`](http://msdn.microsoft.com/en-us/library/bcc5299d.aspx):

```
$ cat git.diff 
diff --git a/integer.cpp b/integer.cpp
index 3a67010..2cdc201 100644
--- a/integer.cpp
+++ b/integer.cpp
@@ -2894,8 +2894,8 @@ Integer::Integer(const byte *encodedInteger, size_t byteCount, Signedness s, Byt
     
 	if(o == LITTLE_ENDIAN_ORDER)
 	{
-		SecByteBlock block(byteCount);
-		std::reverse_copy(encodedInteger, encodedInteger+byteCount, block.begin());
+		SecByteBlock block(encodedInteger, byteCount);
+		std::reverse(block.begin(), block.begin()+block.size());
         
 		Decode(block.begin(), block.size(), s);
 		return;
```

**Comment by noloader** [comment]
>     // I believe 14.10 is the version we need/want. I believe that's
>     //   when Microsoft cut-in the safer functions.
>     #if (CRYPTOPP_MSC_VERSION >= 1410)

It looks like this was introduced in VS2008. I think the test should be:

#if (CRYPTOPP_MSC_VERSION >= 1500)
    std::reverse_copy(encodedInteger, encodedInteger+byteCount, 
        stdext::make_checked_array_iterator(block.begin(), block.size()));
#else
    std::reverse_copy(encodedInteger, encodedInteger+byteCount, block.begin());
#endif

In the absence of a patch, I'm going to use the MSC guard so that folks enduring an audit won't encounter trouble.

**Comment by noloader** [comment]
Also see [Commit f45813bd129c1d58](http://github.com/weidai11/cryptopp/commit/f45813bd129c1d58d4dd7a5e9fa3735f70293688)

**Comment by JanFellner** [comment]
I wanted to link this pretty old issue with a new one that arises out of the changes beeing made
https://github.com/weidai11/cryptopp/issues/1250
VS 2022 17.8 seems not to really love the make_checked_array_iterator
As i have no deeper understanding about the changes made here and how to test them...
Maybe one of the authors of this change can take a look.
