### ISSUE TITLE
__asm__ volatile missing clobbered registers

### ISSUE THREAD

**Issue by jowehrli** [weidai11/cryptopp#124]
When I was running the test suite compiled with Clang and some optimisation passes, I had an error.

After some research, I found that the asm volatile didn't have the clobbered registers setted ([link](http://www.codeproject.com/Articles/15971/Using-Inline-Assembly-in-C-C)) in the file *rdrand.cpp*.

I am not an expert with asm inlining but I think you must specify the register, especially if you put the byte representation.

I have modify the following line in the function *GCC_RRA_GenerateBlock*:

```c
       __asm__ volatile(
#if CRYPTOPP_BOOL_X64 || CRYPTOPP_BOOL_X32
	".byte 0x48, 0x0f, 0xc7, 0xf0;\n"  // rdrand rax
#else
	".byte 0x0f, 0xc7, 0xf0;\n"        // rdrand eax
#endif
	"setc %1; "
	: "=a" (val), "=qm" (rc)
	:
	: "cc"
        );
```
to

```c
        __asm__ volatile(
#if CRYPTOPP_BOOL_X64 || CRYPTOPP_BOOL_X32
			".byte 0x48, 0x0f, 0xc7, 0xf0;\n"  // rdrand rax
#else
			".byte 0x0f, 0xc7, 0xf0;\n"        // rdrand eax
#endif
			"setc %1; "
			: "=a" (val), "=qm" (rc)
			:
#if CRYPTOPP_BOOL_X64 || CRYPTOPP_BOOL_X32
			: "cc","rax"
#else
			: "cc","eax"
#endif
        );
```

**Comment by noloader** [comment]
> I am not an expert with asm inlining but I think you must specify the register, especially if you put the byte representation.

I think you are probably right... RDSEED, should probably have the same.

Do you want to make a pull request? It will ensure you appear at [Contributors](http://github.com/weidai11/cryptopp/graphs/contributors)

**Comment by noloader** [comment]
@jowehrli,

> Clang and some optimisation passes, I had an error...

If you don't mind me asking, how did you get into this situation? The library should be using intrinsics for modern Clang and GCC. That code is a fallback for early compilers that lack the instrinsic, like GCC 4.6. But the instruction is probably not available on old iron providing GCC 4.6, so the code should never be executed.

**Comment by noloader** [comment]
@jowehrli, Fixed at [Commit b0fb7471](https://github.com/weidai11/cryptopp/commit/b0fb747182e3b83f0713b6d1f1531515efacc1e1).

I tired to get you attribution, but Git is an absolutely miserable tool. It makes the simplest tasks hard. I can't keep reverting commits trying to get Git to accept your handle.

**Comment by jowehrli** [comment]
@noloader 

Sorry for the delay, I was working on something else.

I'm using Cryptopp on an Mac and I run it with:

*make -j7 CXXFLAGS="-std=c++11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.2 -O0"*

Then, I run the test suite with: *make test*.

Thank you for the quick response.

**Comment by noloader** [comment]
@jowehrli: I had to ask about how Clang's integrated assembler handling of *output operands* and *clobbered list*. Also see [Does Integrated Assembler need Output Operands listed as Clobbered?](http://lists.llvm.org/pipermail/cfe-users/2016-January/000865.html) on the CFE-Users mailing list.

**Comment by noloader** [comment]
@jowehrli, I did not get any answers on the CFE-Users mailing list, so I re-posted on the LLVM-dev mailing list. I did not get any answers there, either.

According to the GCC's [Extended-Asm](https://gcc.gnu.org/onlinedocs/gcc/Extended-Asm.html):

> 6.44.3.2 Clobbers
>
> While the compiler is aware of changes to entries listed in the output operands...
>
> Clobber descriptions may not in any way overlap with an input or output operand...

From that paragraph, we are not allowed to use a register as an output operand and list it as clobbered. That explains the broken GCC compile.

But I'm not clear on what's supposed to happen on Clang. One thing I know is I experienced a similar issue and I suspected Clang was generating bad code around the use of ***`CPUID`***.

Can you locate a canonical reference on the subject?

**Comment by jowehrli** [comment]
@noloader I will look into it.

**Comment by noloader** [comment]
@jowehrli,

We are moving towards our 5.6.4 release; see [Call for Testers using Master](http://groups.google.com/forum/#!topic/cryptopp-users/CCjEvVV2KHs) on the mailing list.

I have a few questions:

(1) Can you duplicate this on Master?
(2) Do you have more information?
(3) Can we close it?

**Comment by noloader** [comment]
Closing this report.

**Comment by jowehrli** [comment]
Hi,

(1) Can you duplicate this on Master?

No I have tested this with the latest version, and it seems to be ok (pass
all the test with ./cryptext.exe v).

(2) Do you have more information?

This kind of bug appears randomly because it is depending on the
instruction below. If no instructions are using the same register, the
program will work (in this case, that's what I noticed).

(3) Can we close it?

If you never encounter this bug, I guess you can.

Greetings,

Wehrli Johan

2016-09-09 18:32 GMT+02:00 Jeffrey Walton <notifications@github.com>:
