### ISSUE TITLE
Unable to link using MSYS2 Clang64 toolchain

### ISSUE THREAD

**Issue by Steveice10** [weidai11/cryptopp#1241]
**Operating System**: Windows 11 Pro x64

**Crypto++ version**: 8.9.0 (and master)

**Build method**: Makefile

Using the included Makefile build in an MSYS2 Clang64 environment, I am unable to build executables using Crypto++ due to the following error:

```
g++ -o cryptest.exe -g2 -O3 -fPIC -pthread -pipe adhoc.o test.o bench1.o bench2.o bench3.o datatest.o dlltest.o fipsalgt.o validat0.o validat1.o validat2.o validat3.o validat4.o validat5.o validat6.o validat7.o validat8.o validat9.o validat10.o regtest1.o regtest2.o regtest3.o regtest4.o ./libcryptopp.a
ld.lld: error: undefined symbol: XGETBV64
>>> referenced by cpu.cpp:400
>>>               libcryptopp.a(cpu.o):(CryptoPP::XGetBV(unsigned int))
>>> referenced by cpu.cpp:400
>>>               libcryptopp.a(cpu.o):(CryptoPP::DetectX86Features())

ld.lld: error: undefined symbol: CPUID64
>>> referenced by cpu.cpp:464
>>>               libcryptopp.a(cpu.o):(CryptoPP::CpuId(unsigned int, unsigned int, unsigned int*))
>>> referenced by cpu.cpp:464
>>>               libcryptopp.a(cpu.o):(CryptoPP::DetectX86Features())
>>> referenced by cpu.cpp:464
>>>               libcryptopp.a(cpu.o):(CryptoPP::DetectX86Features())
>>> referenced 6 more times
g++: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [GNUmakefile:1511: cryptest.exe] Error 1
```

This example is from the cryptest.exe produced by Crypto++ for testing, but this also occurs in any other project I attempt to link with the produced Crypto++ static library.

This error did not occur in 8.7.0, which was the version I was using previously.

This also occurs with alternative build systems like CMake, so it's not limited to just the included Makefile build.

**Comment by abdes** [comment]
If this may help: https://blog.conan.io/2022/10/13/Different-flavors-Clang-compiler-Windows.html

**NOTE:**
Currently, we only include the `x64dll.asm` and `x64masm.asm` if `MSVC` is defined. That is not the case if the compiler is `Msys2 Clang`.

When exactly are these 2 files expected to be included in the source list?

**Comment by noloader** [comment]
I can't duplicate this. When I build with `g++` everything is Ok. The library compiles, links and executes its self tests Ok.

When I attempt to build with CLANG64 using `CXX=clang64++`, I get a file not found (the compiler) and the build fails. 

What compiler name are you using besides `g++`?

**Comment by Steveice10** [comment]
Just the default g++ is what I’m using. My reproduction steps are simply open MSYS2 Clang64 and run ‘git clone https://github.com/weidai11/cryptopp && cd cryptopp && make’.

**Comment by noloader** [comment]
> Just the default g++ name is what I’m using. 

Ok, thanks.

> In CLANG64 this points to clang++. 

I'm seeing different results for the CLANG64 environment:

```
$ command -v g++
/usr/bin/g++

$ ls -Al $(command -v g++)
-rwxr-xr-x 4 Jeffrey Walton None 1637882 Sep 14 04:43 /usr/bin/g++

$ g++ --version
g++ (GCC) 13.2.0
```

> Do you have the clang64 compiler toolchain installed?

I don't know. Do you know what its called or the package name?

I tried running `make` with `CXX=clang64++`, but it fails with a "file not found".

-----

I do run `pacman -Syu` when I open a MSYS2 prompt to update all packages. Maybe you need the latest packages, too?

**Comment by Steveice10** [comment]
> I don't know. Do you know what its called or the package name?

In MSYS2 you can install the toolchain for a particular environment using pacboy (installed using pacman -S pactoys). For example ‘pacboy -S toolchain:p cmake:p’ installs the standard toolchain for your current environment and a cmake build created against it.

You can see some of this setup in the actions used by cryptopp-cmake here, which also has this problem, albeit using the msys2 setup action instead: https://github.com/abdes/cryptopp-cmake/blob/master/.github/workflows/cmake-build.yml#L286

I am guessing you are in the CLANG64 environment but using the toolchain installed from a different environment. In order to reproduce the issue it should be building using clang.

**Comment by noloader** [comment]
> In MSYS2 you can install the toolchain

So this is what I have installed:

```
$ pacman -Q | grep -E 'clang|gcc|g\+\+'
clang 11.0.0-5
gcc 13.2.0-2
gcc-libs 13.2.0-2
mingw-w64-x86_64-gcc 13.2.0-2
mingw-w64-x86_64-gcc-ada 13.2.0-2
mingw-w64-x86_64-gcc-fortran 13.2.0-2
mingw-w64-x86_64-gcc-libgfortran 13.2.0-2
mingw-w64-x86_64-gcc-libs 13.2.0-2
mingw-w64-x86_64-gcc-objc 13.2.0-2
mingw-w64-x86_64-libgccjit 13.2.0-2
```

If its missing a package, then please tell me what it is.

> I am guessing you are in the CLANG64 environment

Yes. I do a Start -> MSYS2 -> CLANG64 in this case, since we are talking about Clang64.

![msys2-environment](https://github.com/weidai11/cryptopp/assets/3538226/199a0732-7479-4a7b-89ca-e089eab95a0d)

> but using the toolchain installed from a different environment

Yeah, so I don't know about this. Naively, it seems like the environments should keep themselves separated from one another. Otherwise, what's the point of providing different environments?

**Comment by Steveice10** [comment]
> So this is what I have installed

The clang64 environment packages should all start with ‘mingw-w64-clang-x86_64’, e.g. ‘mingw-w64-clang-x86_64-clang’. If you run pacboy like I mentioned it installs the toolchain with all the environment-specific packages.

**Comment by noloader** [comment]
Ok, thanks. It looks like I can install yet another Clang on this machine:

```
$ pacman -S mingw-w64-clang-x86_64-clang
resolving dependencies...
looking for conflicting packages...

Packages (19) mingw-w64-clang-x86_64-compiler-rt-17.0.1-1
              mingw-w64-clang-x86_64-crt-git-11.0.0.r198.g93ca95b32-1
              mingw-w64-clang-x86_64-expat-2.5.0-1  mingw-w64-clang-x86_64-gettext-0.21.1-2
              mingw-w64-clang-x86_64-headers-git-11.0.0.r198.g93ca95b32-1
              mingw-w64-clang-x86_64-libc++-17.0.1-1  mingw-w64-clang-x86_64-libffi-3.4.4-1
              mingw-w64-clang-x86_64-libiconv-1.17-3  mingw-w64-clang-x86_64-libunwind-17.0.1-1
              mingw-w64-clang-x86_64-libwinpthread-git-11.0.0.r198.g93ca95b32-1
              mingw-w64-clang-x86_64-libxml2-2.11.5-1  mingw-w64-clang-x86_64-lld-17.0.1-1
              mingw-w64-clang-x86_64-llvm-17.0.1-1  mingw-w64-clang-x86_64-llvm-libs-17.0.1-1
              mingw-w64-clang-x86_64-winpthreads-git-11.0.0.r198.g93ca95b32-1
              mingw-w64-clang-x86_64-xz-5.4.4-1  mingw-w64-clang-x86_64-zlib-1.3-1
              mingw-w64-clang-x86_64-zstd-1.5.5-1  mingw-w64-clang-x86_64-clang-17.0.1-1

Total Download Size:    156.35 MiB
Total Installed Size:  1103.49 MiB

:: Proceed with installation? [Y/n] Y
```

Do you know what the compiler name is? I'm still getting a "command not found":

```
$ mingw-w64-clang-x86_64-clang++ --version
-bash: mingw-w64-clang-x86_64-clang++: command not found
```

**Comment by Steveice10** [comment]
The exe should just be "clang++.exe" in the environment's PATH. Specifically it's at `/clang64/bin/clang++.exe`.

Also if it helps, I'm not sure if the inclusion of CPUID64 and XGETBV64 in this environment is intentional or not, but I don't see the file they come from `x64dll.asm` referenced at all in the `GNUmakefile`.

**Comment by noloader** [comment]
> Also if it helps, I'm not sure if the inclusion of CPUID64 and XGETBV64 in this environment is intentional or not, but I don't see the file they come from x64dll.asm referenced at all in the GNUmakefile.

Clang is supposed to get into the code path located at <https://github.com/weidai11/cryptopp/blob/master/cpu.cpp#L434>. It is not supposed to get into the code path for CPUID64 and XGETBV64.

**Comment by Steveice10** [comment]
Wouldn't it be just because of this? https://github.com/weidai11/cryptopp/blob/master/config_cpu.h#L206

WIN32 is available under MSYS2 clang.

**Comment by noloader** [comment]
> Wouldn't it be just because of this? https://github.com/weidai11/cryptopp/blob/master/config_cpu.h#L206

So that is supposed to be for the version of Clang that Microsoft distributes as part of their Build Tools and Visual Studio. It is not supposed to be for MSYS/MinGW/Cygwin.

I think the problem starts further back, sometime around <https://github.com/weidai11/cryptopp/blob/master/config_ver.h#L55>.

**Comment by noloader** [comment]
@Steveice10,

Git [Commit 19f0e3aa1e63](https://github.com/weidai11/cryptopp/commit/19f0e3aa1e63) a try. It tested good for me under MSYS2's CLANG64 environment.

**Comment by Steveice10** [comment]
Seems to have worked, thanks!
