### ISSUE TITLE
misc.h IncrementCounterByOne (output, input, size) 

### ISSUE THREAD

**Issue by GeorgeMatveev** [weidai11/cryptopp#126]
It seems that code in IncrementCounterByOne has minor but very important bug which I've already
fixed in my branch:

```
inline void IncrementCounterByOne(byte *output, const byte *input, unsigned int size)
{
	assert(output != NULL); assert(input != NULL); assert(size < INT_MAX);
	
	int i, carry;
	for (i=int(size-1), carry=1; i>=0 && carry; i--)
		carry = ((output[i] = input[i+1]) == 0);
	memcpy_s(output, size, input, i+1);
}
```

**Comment by noloader** [comment]
Thanks @GeorgeMatveev. Please forgive my ignorance.... What is the bug? (Its not obvious to me looking at the code that was posted.

**Comment by GeorgeMatveev** [comment]
In the master branch code we have now:

carry = ((output[i] = input[i]+1) == 0);

g++ will complain about wrong conversion.
You take next element and assign it to previous thus Incrementing counter by one,
as name of the function/method suggest.

Following will fix it:

carry = ((output[i] = input[i+1]) == 0);

Best regards,
George Matveev

**Comment by noloader** [comment]
Thanks @GeorgeMatveev. Let me write some test cases to see if I can reproduce it and ensure I follow what you are reporting. Hold tight.

**Comment by noloader** [comment]
Thanks again @GeorgeMatveev. I am not able to duplicate the issue with the test program below. Would you be able to provide the test data you used? Thanks again.

Here's the meat and potatoes of the test program:

    static const size_t SIZE = 16;
    SecByteBlock b1(SIZE), b2(SIZE);
    memset(b1, 0x00, SIZE), b1[SIZE - 1] = 0xff;
    ...
    IncrementCounterByOne(b2, b1, 16);

And here's the output I am seeing:

```
$ ./test.exe
  b: 000000000000000000000000000000ff
b+1: 00000000000000000000000000000100
```

-----

```
$ cat test.cxx 
#include <iostream>
#include <algorithm>
using namespace std;

#include "integer.h"
#include "misc.h"
using namespace CryptoPP;

// g++ -DNDEBUG -g2 -O2 -I . test.cxx ./libcryptopp.a -o test.exe
void display(byte val)
{
	const char f = cout.fill('0');
	const int w = cout.width(2);
	cout << std::hex << (((unsigned int)(val)) & 0xff);
	cout.width(w);
	cout.fill(f);
}

int main(int argc, char* argv[])
{
	//Integer x("0x000000000000000000000000000000ff");
	//cout << "  x: " << std::hex << x << endl;
	//cout << "x+1: " << std::hex << x+1 << endl;

	static const size_t SIZE = 16;
	SecByteBlock b1(SIZE), b2(SIZE);
	memset(b1, 0x00, SIZE), b1[SIZE - 1] = 0xff;
	
	cout << "  b: ";
	for_each(b1.begin(), b1.end(), display);
	cout << endl;
	
	IncrementCounterByOne(b2, b1, 16);
	
	cout << "b+1: ";
	for_each(b2.begin(), b2.end(), display);
	cout << endl;

	return 0;
}
```

**Comment by noloader** [comment]
Also, if I change the "meat and potatoes" test code to use the maximum value of a block:

	memset(b1, 0xff, SIZE);
	
	cout << "  b: ";
	for_each(b1.begin(), b1.end(), display);
	cout << endl;
	
	IncrementCounterByOne(b2, b1, SIZE);
	
	cout << "b+1: ";
	for_each(b2.begin(), b2.end(), display);
	cout << endl;

Then I see the following, which I believe is expected:

```
$ ./test.exe
  b: 000000000000000000000000000000ff
b+1: 00000000000000000000000000000100
  b: ffffffffffffffffffffffffffffffff
b+1: 00000000000000000000000000000000
```

**Comment by GeorgeMatveev** [comment]
I understand you like writing code :-)
We are using libcryptopp in a project where maven is used. I have not much say about using that ... tool. Here's what I got after running mvn clean install in cryptopp dir:

[ERROR] /usr/bin/ld: cannot find -lcryptest-1.0-SNAPSHOT
[ERROR] collect2: error: ld returned 1 exit status
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] cryplib ............................................ SUCCESS [ 29.151 s]
[INFO] cryptopp563 ........................................ SUCCESS [  0.057 s]
[INFO] cryptest ........................................... FAILURE [  7.636 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 37.387 s
[INFO] Finished at: 2016-01-29T11:13:59+01:00
[INFO] Final Memory: 15M/220M

As you can see cryptest ........................................... FAILURE [  7.636 s]
with the code that you have now in master branch!
Sorry about disappointing you :-)

Br,
George Matveev

**Comment by noloader** [comment]
@GeorgeMatveev,

Please perform the following:

```
git clone https://github.com/weidai11/cryptopp.git cryptopp-test
cd cryptopp-test
make cryptest.exe
./cryptest.exe v
./cryptest.exe tv all
```

Then report back.

If all the self tests pass, then the problem lies somewhere else.

-----

> We are using libcryptopp in a project where maven is used. 

Unfortunately, I know nothing about Maven, its repos, or its plugins. Maybe you can get help using it on the Crypto++ or Maven mailing list?

> As you can see cryptest ........................................... FAILURE [ 7.636 s]

Unfortunately, that does not really tell us much.

I suspect you have two copies of Crypto++. The first is provided by Ubuntu, and the second is provided by Maven. You are mixing and matching them between compile-time and runtime, leading to runtime crashes. I suspect it because of things like:

    [ERROR] /usr/bin/ld: cannot find -lcryptest-1.0-SNAPSHOT

You have to be very careful with ***`-l<some lib>`***.

I'm guessing the easiest thing to do would be remove the distro's copy of Crypto++ so you can't accidentally use it. Or, use the distro's copy exclusively and stop using the Maven repo.

**Comment by GeorgeMatveev** [comment]
Hi,
appreciate your quick replies very much!
Here's what I got after building from cryptopp code tree and running ./cryptest.exe v:
***
...

All tests passed!

Test ended at Fri Jan 29 15:18:48 2016

Which means my feelings about ... maven are (very) well founded.

Have a nice weekend!
/George

**Comment by noloader** [comment]
>>     [ERROR] /usr/bin/ld: cannot find -lcryptest-1.0-SNAPSHOT
>> You have to be very careful with `-l<some lib>`.

> Which means my feelings about ... maven are (very) well founded.

Yeah, this gets a lot of folks... You need two or three things to make things work when there are two or more copies of the library lying around. Each scenario is slightly different.

One thing that is ***not*** obvious... At ***`make cryptest.exe`*** step, Crypto++ itself links against the static library. It does not mess with ***`L`*** and ***`-l`***. You can see it in [the makefile, line 533](http://github.com/weidai11/cryptopp/blob/master/GNUmakefile#L534):

```
cryptest.exe: libcryptopp.a $(TESTOBJS) | public_service
	$(CXX) -o $@ $(CXXFLAGS) $(TESTOBJS) ./libcryptopp.a $(LDFLAGS) $(LDLIBS)
```

I'm guessing you might be able to work around it by setting a `LD_LIBRARY_PATH` to ensure the Crypto++ you build is linked at runtime. If Maven puts its output artifacts in `.../lib/cryptopp`, then perform:

    export LD_LIBRARY_PATH=".../lib/cryptopp:$LD_LIBRARY_PATH"
    maven-make (or whatever its called)
