### ISSUE TITLE
How can I compile for windows with mingw?

### ISSUE THREAD

**Issue by lincolningaroca** [weidai11/cryptopp#1276]
I have tried to compile the library in a Windows environment but I have not succeeded, so far I have tried several ways but it gives me an error, any suggestions on how I can do it, thanks in advance, I have Windows 11 and Qt creator installed, precisely to use it in I want to compile the library in that environment.

**Comment by FrankSapone** [comment]
Hi Lincoln,

I have not tested it, but it appears you would open the MSYS2 MinGW console and run 'make -f GNUmakefile' from the project directory.  The makefile appears to have MinGW specific things in it.
