### ISSUE TITLE
Nuget packages

### ISSUE THREAD

**Issue by zabulus** [weidai11/cryptopp#129]
Do you plan to add nuget packages for msvc builds?

**Comment by noloader** [comment]
> Do you plan to add nuget packages for msvc builds?

No. As far as I know, there's no interest in them.

Personally, I have no interest in fulfilling these types of requirements (from [Creating and Publishing a Package](https://docs.nuget.org/create/creating-and-publishing-a-package)):

> Create an account at NuGet.org
> 
> Head over to http://nuget.org/ and register for an account. Once you do that, use the Upload Package UI to upload your package to the NuGet Gallery

You might take the discussion to the [User Group](https://groups.google.com/forum/#!forum/cryptopp-users) to see if there is any interest there.

**Comment by zabulus** [comment]
> Personally, I have no interest in fulfilling these types of requirements (from Creating and Publishing a Package):

Not sure I understood the problem correctly. Registration or manual uploading concern you? Just curious.

Though I understand your position, thanks.
