### ISSUE TITLE
setenv-embedded.sh and GNUmakefile-cross

### ISSUE THREAD

**Issue by crosswalking** [weidai11/cryptopp#134]
This is not a bug of crypto++ but rather a configuration issue in the files setenv-embedded.sh and GNUmakefile-cross. There is an `ARM_EMBEDDED_SYSROOT` setting which should not be used when cross-compiling on Linux (e.g. on desktop Ubuntu) for BeagleBone Black.

The issue is described at [Linking error when compiling crypto++ for armhf](http://stackoverflow.com/questions/31698241/linking-error-when-compiling-crypto-for-armhf), and I posted an answer on that webpage.

My solution was simply to remove the `--sysroot` option from line 68 in the file GNUmakefile-cross. My solution is not ideal, of course. It is just a shortcut.

**Comment by noloader** [comment]
I think this another Ubuntu problem, similar to [g++-arm-linux-gnueabi cannot compile a C++ program with --sysroot](https://bugs.launchpad.net/ubuntu/+source/gcc-defaults-armel-cross/+bug/1375071). It might be a Debian problem if it is coming from upstream.

When cross-compiling, we expect the following (using ARMHF):

* `SYSROOT` is `/usr/arm-linux-gnueabihf`
* `INCLUDEDIR` is `/usr/arm-linux-gnueabihf/include`
* `LIBDIR` is `/usr/arm-linux-gnueabihf/lib`
* `BINDIR` is `/usr/arm-linux-gnueabihf/bin`

How someone managed to turn `LIBDIR` into `/usr/arm-linux-gnueabihf/usr/arm-linux-gnueabihf/lib/` (i.e., `$SYSROOT/$SYSROOT/lib` is a mystery. But in all fairness, building GCC is not a trivial task.

You should probably file a bug report with Ubuntu.

**Comment by noloader** [comment]
I'm going to close this since it looks like a configuration problem with the distro toolchain.
