### ISSUE TITLE
File validat1.cpp compilation issue with NO_OS_DEPENDENCE defined

### ISSUE THREAD

**Issue by jcnarlo** [weidai11/cryptopp#141]
In file validat1.cpp, line 890 the following code needs to be changed

from:
    ```#if NO_OS_DEPENDENCE```
to:
    ```#ifdef NO_OS_DEPENDENCE```

The reason is that in `config.h` when `NO_OS_DEPENDENCE` is defined, it is not set to anything, so during compilation of `validat1.cpp`, the preprocessor does not  have a value to use.

**Comment by noloader** [comment]
Thanks, @jcnarlo. I'm not sure how that managed to slip by our testing. We specifically test for OS Independence and exercise the macro in [`cryptest.sh`](http://github.com/weidai11/cryptopp/blob/master/cryptest.sh).

What platform did you experience the problem, and what was the problem?

------

> the preprocessor does not have a value to use...

In this case, the preprocessor uses the value 0.

The real question is, what breaks next...

-----

```
$ grep NO_OS_DEPENDENCE *.h *.cpp
config.h:// #define NO_OS_DEPENDENCE
config.h:// This macro will be ignored if NO_OS_DEPENDENCE is defined.
config.h:#ifndef NO_OS_DEPENDENCE
config.h:#endif	// NO_OS_DEPENDENCE
validat1.cpp:#if NO_OS_DEPENDENCE
validat1.cpp:#endif // NO_OS_DEPENDENCE
```

-----

> the following code needs to be changed

If you work up a pull request, then I'd be happy to check it in. Otherwise, I can do it. But I prefer you receive the credit at [Crypto++ Contributors](http://github.com/weidai11/cryptopp/graphs/contributors).

**Comment by noloader** [comment]
@jcnarlo , So I had some time to run this through our test infrastructure. It resulted in a few issues specifically related to `NO_OS_DEPENDENCE`. You should be able to duplicate the results below with:

```
export CXXFLAGS="-DNDEBUG -g2 -O2 -DNO_OS_DEPENDENCE`
make
```

I think we need to take a close look at what's going on.

-----

```
Testing started: Tue Mar  1 23:52:58 EST 2016
Testing finished: Wed Mar  2 00:55:16 EST 2016

28 configurations tested

20 errors detected. See cryptest-result.txt for details

18106:validat1.cpp:905:2: error: ‘AutoSeededRandomPool’ was not declared in this scope
18109:validat1.cpp:905:23: error: expected ‘;’ before ‘prng’
18112:validat1.cpp:910:26: error: ‘prng’ was not declared in this scope
18115:validat1.cpp:941:64: error: ‘OS_GenerateRandomBlock’ was not declared in this scope
18119:validat1.cpp:969:2: error: ‘AutoSeededX917RNG’ was not declared in this scope
18122:validat1.cpp:969:23: error: expected primary-expression before ‘>’ token
18125:validat1.cpp:969:25: error: ‘prng’ was not declared in this scope
18128:validat1.cpp:1005:64: error: ‘OS_GenerateRandomBlock’ was not declared in this scope
18131:make: *** [validat1.o] Error 1
18133:ERROR: failed to make cryptest.exe
18272:validat1.cpp:905:2: error: ‘AutoSeededRandomPool’ was not declared in this scope
18275:validat1.cpp:905:23: error: expected ‘;’ before ‘prng’
18278:validat1.cpp:910:26: error: ‘prng’ was not declared in this scope
18281:validat1.cpp:941:64: error: ‘OS_GenerateRandomBlock’ was not declared in this scope
18285:validat1.cpp:969:2: error: ‘AutoSeededX917RNG’ was not declared in this scope
18288:validat1.cpp:969:23: error: expected primary-expression before ‘>’ token
18291:validat1.cpp:969:25: error: ‘prng’ was not declared in this scope
18294:validat1.cpp:1005:64: error: ‘OS_GenerateRandomBlock’ was not declared in this scope
18298:make: *** [validat1.o] Error 1
18300:ERROR: failed to make cryptest.exe
31343:20 errors detected. See cryptest-result.txt for details
```

**Comment by noloader** [comment]
@jcnarlo, ignore the last comment... I fat fingered the change of the define, which caused the tests to fail.

Anyway, the following tested OK:

```
$ git diff
diff --git a/validat1.cpp b/validat1.cpp
index 94c3c45..345281d 100644
--- a/validat1.cpp
+++ b/validat1.cpp
@@ -887,7 +887,7 @@ bool TestOS_RNG()
        return pass;
 }
 
-#if NO_OS_DEPENDENCE
+#ifdef NO_OS_DEPENDENCE^M
 bool TestAutoSeeded()
 {
        return true;
```

Would you like to make the PR?

**Comment by noloader** [comment]
Cleared at [Commit 73fd1ac80ed01a5b](http://github.com/weidai11/cryptopp/commit/73fd1ac80ed01a5bbb1919b0bb31df2d8532edaa)
