### ISSUE TITLE
crypto++ and crypto++-562 are in conflict

### ISSUE THREAD

**Issue by PartTimeLegend** [weidai11/cryptopp#144]
When performing a package update. Is this a package mirror issue?

**Comment by noloader** [comment]
> When performing a package update. Is this a package mirror issue?

Its hard to say. We've tried to retain ABI compatibility, but I'm also aware of some fixes and enhancements that could affect it.

Do you have a distro and particular problem in mind?

-----

Also, if the disto's followed the advice on the wiki at [config.h | Recommendations](htts://cryptopp.com/wiki/Config.h#5.6.3_Recommendations), then it likely did break compatibility. In this case, the application or program should be recompiled against the version of the library installed.

You can also link to the static library, and avoid the breaking changes:

    # Pretend Crypto++ is installed in $PWD/cryptopp
    g++ -g2 -O2 -I $PWD foo.cpp $PWD/cryptopp/libcryptopp.a -o foo.exe

**Comment by PartTimeLegend** [comment]
My distro is BlackArch.

**Comment by noloader** [comment]
> My distro is BlackArch.

Thanks. What problem are you seeing?

Also, would you have a contact for the package maintainer? I keep a list of them and contact them on occasion.

**Comment by noloader** [comment]
I'm not sure there's anything we can do here. Closing ticket.
