### ISSUE TITLE
AEAD interface doesn't support offline AEAD algorithms

### ISSUE THREAD

**Issue by DevJPM** [weidai11/cryptopp#145]
Our AEAD interface `AuthenticatedSymmetricCipherBase` (defined in `authenc.h`) doesn't support AEAD modes of operation that aren't online, i.e. offline ciphers.

For those of you, how don't know what "online" and "offline" mean in this context:

> A cipher is colled online if the encryption of the i-th input block M_i depends only on the blocks M_1,...,M_{i-1} and only constant size-state is used from the processing of one block to the next. We call an AEAD scheme online if its encryption algorithm is an online cipher and its decryption algorithm is its inverse operation. Schemes that are not online are called offline.

Now most modern ciphers are online (yay!), but there's one particularly interesting class of ciphers that are proven to be _always_ offline: _fully nonce misuse resistant authenticated encryption schemes_. If you use one of those schemes and re-use the nonce, all an attacker can tell is whether you encrypted the same message whereas with other modes the attacker can either recover keys, partial keys (the authentication key in GCM) or at least deduce information about the plaintext (the xor of the plaintexts).

Now the only place in our API where encrypted data can be given out is `ProcessData()` which also takes the input data. This works fine with online ciphers but fails with offline ciphers, as they tend to rely on the _complete_ plaintext before encryption can be started.

An example:
We can't add [GCM-SIV](https://tools.ietf.org/html/draft-gueron-gcmsiv-01) to our library because of this. GCM-SIV literally is "fully two-pass" (not "two-pass" like CCM and EAX), so you first input the AAD and the data (it performs a variation of GHASH on it), it will calculate the counter for CTR from that and then you can start to actually encrypt and output data.

The design problem:
`AuthenticatedSymmetricCipherBase` inherits from `AuthenticatedSymmetricCipher` (defined in `cryptlib.h`) which would support offline schemes if the data is supplied in one chunk via `EncryptAndAuthenticate()`. However, `AuthenticatedSymmetricCipher` also inherits from `MessageAuthenticationCode` and from `StreamTransformation` and it is the latter that brings us into trouble because it introduces the `ProcessData()` function to which `EncryptAndAuthenticate()` defaults.

The solution proposals:
1.  Don't do anything and just continue life without offline AEAD schemes.
2. Add a new (independent) class in `cryptlib.h`: `AuthenticatedOfflineSymmetricCipher` that features methods to deal with two-pass schemes
3. Add a new (inherited) class in `cryptlib.h`: `AuthenticatedOfflineSymmetricCipher` that features methods to deal with two-pass schemes and inherits from `AuthenticatedSymmetricCipher`
4. Patch the existing `AuthenticatedSymmetricCipher` to add methods to deal with offline ciphers

(4) sounds like the best choice to me that would inflict the least amount of work.

Whenever I wrote "add methods to deal with it" I actually meant the following: Add a method `bool IsOnline() const` that returns true if the scheme is online, add a method `void InputPlaintext(const byte* Plaintext, const size_t Size)` (similar to `Update()`) to feed the plaintext into the scheme, add a method `void RunOfflineTransformations(bool DeferIfPossible = true)` which will do the offline operations in one run (which is maximally efficient but only done if `DeferIfPossible=false`) and which will signalise that the plaintext has been fully inputted. Finally we'd add `size_t OutputCiphertext(byte* Ciphertext, const size_t size)` which will either output the buffered encryptions (created from `RunOfflineTransformations(false)`) or will do the encryptions on-the-fly for the amount of ciphertext requested, the function will return the number of written bytes (i.e. if the return value is smaller than the requested value, then the tag can be requested).

The default behavior would be for `IsOnline()` to return `true`, for `ProcessData()` to throw if `IsOnline()==false` or work as before if `IsOnline==true`, for `InputPlaintext()` to just save the plaintext into a buffer (if `IsOnline()==true`), for `OutputCiphertext()` to just output the buffer or run the on-line encryption (if `IsOnline()==true`) and for `RunOfflineTransformations()` to do nothing if `true` is passed (besides updating state maybe?) and to run the online encryption if `false` is passed. Any cases I left unspecified here would just throw something like `not implemented`. Additionally the following (similarly named) states should be added accordingly: `State_ReceivingPlaintext`, `State_GivingCiphertext`

Impact of the changes:
- Changes to `AuthenticatedSymmetricCipher` (or adding a new class)
- Changes to `AuthenticatedSymmetricCipherBase` (or adding a new class)
- Changes to `AuthenticatedEncryptionFilter` to support `IsOnline()==false`
- Changes to `AuthenticatedDecryptionFilter` to support `IsOnline()==false`

**Comment by denisbider** [comment]
I cannot testify as to the best choice between 2, 3, and 4. However, I think not supporting offline ciphers would be the inferior choice. Full resistance to nonce reuse is a valuable property. It may be that something like AES-GCM-SIV will become a de facto standard.

**Comment by noloader** [comment]
Also see [AEAD Comparison](http://cryptopp.com/wiki/AEAD_Comparison) on the Crypto++ wiki.

**Comment by DevJPM** [comment]
@noloader the "offlineness" of CCM (CTR + CBC-MAC) is a different one from the one modes like GCM-SIV use.

CCM "only" requires the length(s) to be known in advance (which already formally disqualifies it from being online) and our API already deals with this by having `NeedsPrespecifiedLengths()` and `PrespecifyLength()`. The remainder of the CCM encryption *is* "online" as you can advance the CBC-MAC with each block you feed in and directly output the CTR encryption of the block.

GCM-SIV (my main example for a "fully offline" mode) on the other hand requires you to *know* the whole plaintext before it can even start outputting anything, because it first calculates a variant of GMAC on the plaintext and uses the tag to create the counter for CTR mode which then encrypts the plaintext.

**Comment by smlu** [comment]
Here is an updated draft of AES-GCM-SIV: [https://tools.ietf.org/html/draft-irtf-cfrg-gcmsiv-06](https://tools.ietf.org/html/draft-irtf-cfrg-gcmsiv-06)
([https://www.imperialviolet.org/2017/05/14/aesgcmsiv.html](https://www.imperialviolet.org/2017/05/14/aesgcmsiv.html))
