### ISSUE TITLE
Crypto++ FIPS certificates moved to Historical Validation List

### ISSUE THREAD

**Issue by denisbider** [weidai11/cryptopp#149]
The Crypto++ FIPS certificates have been moved to the [Historical Validation List](http://csrc.nist.gov/groups/STM/cmvp/documents/140-1/140val-historical.htm):

> After 2015, the use of the RNGs specified in FIPS 186-2, [ANSI X9.31] and the 1998 version of [ANSI X9.62] are disallowed. Therefore, all the RNG implementations that were previously validated are non-compliant, and any algorithms reliant on the output of these RNGs are also non-compliant. Modules that include an RNG as a FIPS Approved algorithm have been moved to this list. The modules on this list are not to be used for procurement by federal agencies. Please see CMVP Notice dated 11-24-2015 for more details. This does not mean that the overall FIPS-140 certificate has been revoked, rather it indicates that the certificate and the documentation posted with it do not accurately reflect how the module can be used in FIPS mode. Agencies may make a risk determination on whether to continue using the modules on this list based on their own assessment of where and when the RNG is used by the module.
> 
> Vendors who would like to update their modules and have them returned to the Validated FIPS 140-1 and FIPS 140-2 Cryptographic Modules list will need to contact an accredited lab to prepare a submission package for CMVP."_

As far as I know, Crypto++ does not have vendors willing to do this.

Given the current situation, I suggest that the Crypto++ project reduce complexity and remove FIPS 140-2 support from the library.

**Comment by noloader** [comment]
@denisbider - How should we tag this?

**Comment by denisbider** [comment]
No idea about tagging. Just wanted to inform everyone.

**Comment by noloader** [comment]
I'm going to so see what the options are. We had some offline discussions about switching from an `AutoSeededX917RNG` to `AutoSeededRandomPool`. The advice was to stop using `AutoSeededX917RNG` and use `AutoSeededRandomPool` because `AutoSeededRandomPool` calls into `CryptGenRandom` which has some Microsoft validations.

However, when I looked at the sources, I came across this from [`osrng.h`, line 230 or so](https://www.cryptopp.com/docs/ref/osrng_8h_source.html#l00234):

```
  245 #if CRYPTOPP_ENABLE_COMPLIANCE_WITH_FIPS_140_2
  246 typedef AutoSeededX917RNG<AES> DefaultAutoSeededRNG;
  247 #else
  248 typedef AutoSeededRandomPool DefaultAutoSeededRNG;
  249 #endif
```

The typedef for `DefaultAutoSeededRNG` was not a death knell, but this was:

```
$ grep -IR 'AutoSeededX917RNG<AES>' *
...
dlltest.cpp:	AutoSeededX917RNG<AES> rng;
fipsalgt.cpp:	AutoSeededX917RNG<AES> m_rng;
```

So there's no way we can sidestep it.

**Comment by noloader** [comment]
So I to to chat with Wei about this. Here was his response:

> The fact that dlltest.cpp and fipsalgt.cpp use the deprecated generators don't matter, i think. those are just the self tests.
> I suggest we still update the security policy to use NonblockingRng. that calls the Microsoft RNG directly. Not AutoSeededRandomPool actually neither of those files are even part of the FIPS DLL.
> fipsalgt.cpp was written to provide the test lab with test data. dlltest.cpp is just a sample application.
> We can still go with the original plan and let people keep using Crypto++ as a FIPS validated module.

**Comment by denisbider** [comment]
You might be able to "Vendor Affirm" a recompilation, but I'm not sure the project can do that for changes to the library to which the certificate applies. I don't think it would be possible to get 5.6.3 or 5.7.0 FIPS certified without undergoing re-certification, which someone would have to pay for. If there's any chance to salvage the existing FIPS certificate, it would have to be based on 5.3.0, with any changes restricted to e.g. removal of disapproved RNG.

**Comment by noloader** [comment]
According to NIST's [NOTICES page](http://csrc.nist.gov/groups/STM/cmvp/notices.html):

> The CMVP is adopting a five year validation sunsetting policy, effective February 1, 2017. The CMVP will move all validation entries with most recent validation dates** prior to February 1, 2012 and all FIPS 140-1 validation entries from the Active Validation Lists to the Historical Validation List. The Historical Validation List is not to be used for procurement by federal agencies. To maintain compliance with FISMA, agencies that use modules on the Historical List must make a risk management decision whether to continue to use these modules or replace them with compliant modules from the Active Validation Lists. 

We are updating the Security Policy now. I'm not sure if that will be enough to get us moved back to active. If its strictly ***"most recent validation dates"***, then it won't affect things much. Crypto++ will still be validated, and it will still be on the Historical list.

**Comment by noloader** [comment]
I don't believe there's anything else we can do here. It seems like the path forward costs money, but the project is not economically charged. If it were a few hundred dollars then I would pay for it out of pocket. I can't justify spending 10's of thousands.
