### ISSUE TITLE
Need to deactivate FIPS code paths for Windows Store apps

### ISSUE THREAD

**Issue by noloader** [weidai11/cryptopp#167]
We need to deactivate FIPS code paths for Windows Store apps. They are causing a number of issues due to missing APIs. The following is from a VS2012 x64 Cross Developer Command Prompt.

```
cl.exe /nologo /W4 /D_MBCS /Zi /TP /EHsc /MD /FI winapifamily.h /DWINAPI_FAMILY=WINAPI_FAMILY_APP /c fipstest.cpp
fipstest.cpp
C:\Program Files (x86)\Windows Kits\8.0\include\um\combaseapi.h(1205) : error C3861: 'CoCreateInstanceFromApp': identifier not found
C:\Program Files (x86)\Windows Kits\8.0\include\um\combaseapi.h(1226) : error C3861: 'CoCreateInstanceFromApp': identifier not found
fipstest.cpp(285) : error C3861: 'GetModuleFileNameW': identifier not found
fipstest.cpp(288) : error C3861: 'GetModuleHandleW': identifier not found
fipstest.cpp(293) : error C3861: 'GetModuleFileNameA': identifier not found
fipstest.cpp(302) : error C3861: 'GetModuleHandleA': identifier not found
NMAKE : warning U4010: 'fipstest.obj' : build failed; /K specified, continuing ...
```

This is part of the port to the new managed Windows platforms. Also see [Issue 143: Support for Universal Windows Platform (UWP)](http://github.com/weidai11/cryptopp/issues/143).

Also see [Native code for Windows Phone 8](http://msdn.microsoft.com/en-us/library/windows/apps/jj681687%28v=vs.105%29.aspx) on MSDN, [Supported Win32 APIs for Windows Phone 8](https://msdn.microsoft.com/en-us/library/windows/apps/jj662956%28v=vs.105%29.aspx) on MSDN, [Conditional compilation with preprocessor directives](http://msdn.microsoft.com/en-us/library/windows/apps/jj714084%28v=vs.105%29.aspx) on MSDN, [Platform defined macros for windows store app](https://social.msdn.microsoft.com/Forums/en-US/3965645c-978c-4148-b32c-1853f7fd22b3/platform-defined-macros-for-windows-store-app?forum=winappswithnativecode) on Microsoft Social and [Dual-use Coding Techniques for Games](https://blogs.msdn.microsoft.com/chuckw/2012/09/17/dual-use-coding-techniques-for-games-part-1/).

**Comment by zabulus** [comment]
IMHO, fipstest.cpp should be fully disabled for UWP. And same for FIPS stuff in cryptodll.

**Comment by noloader** [comment]
I tried to remove `fipstest.cpp` some time ago, buts its like a ganglion tumor. Its burrowed in just enough to make it painful to remove.

The cryptodll is a [FIPS DLL](http://www.cryptopp.com/wiki/FIPS_DLL). Without FIPS there's no reason for it to exist. Removing `cryptdll` and `dlltest` projects would suit my taste just fine. The general feelings are to keep it, however.

**Comment by noloader** [comment]
Now open on the Crypto++ mailing list: [Windows Phone, Windows Store and testing](https://groups.google.com/forum/#!topic/cryptopp-users/B0g1BHtxP3U).

**Comment by noloader** [comment]
The `windows-store` branch was merged into `master`. This issue is now resolved.

Git does not provide a log entry for the merger (or I cannot find it), so I don't have a record to offer for the transaction.
