### ISSUE TITLE
Need performance based counter for TimerBase on Windows Phone and Windows Store

### ISSUE THREAD

**Issue by noloader** [weidai11/cryptopp#168]
`GetThreadTimes` is not available on Windows Phone and Windows Store. We need a performance based counter for TimerBase (or use the default low-res `clock()`).

This is part of the port to the new managed Windows platforms. Also see [Issue 143: Support for Universal Windows Platform (UWP)](http://github.com/weidai11/cryptopp/issues/143).

Also see [Native code for Windows Phone 8](http://msdn.microsoft.com/en-us/library/windows/apps/jj681687%28v=vs.105%29.aspx) on MSDN, [Supported Win32 APIs for Windows Phone 8](https://msdn.microsoft.com/en-us/library/windows/apps/jj662956%28v=vs.105%29.aspx) on MSDN, [Conditional compilation with preprocessor directives](http://msdn.microsoft.com/en-us/library/windows/apps/jj714084%28v=vs.105%29.aspx) on MSDN, [Platform defined macros for windows store app](https://social.msdn.microsoft.com/Forums/en-US/3965645c-978c-4148-b32c-1853f7fd22b3/platform-defined-macros-for-windows-store-app?forum=winappswithnativecode) on Microsoft Social and [Dual-use Coding Techniques for Games](https://blogs.msdn.microsoft.com/chuckw/2012/09/17/dual-use-coding-techniques-for-games-part-1/).

**Comment by zabulus** [comment]
I suggest using http://en.cppreference.com/w/cpp/chrono/high_resolution_clock if available as underlying implementation of the TimerBase class. Not just only for Windows Store applications.

**Comment by DevJPM** [comment]
@zabulus the problem with `std::chrono::high_resolution_clock` is that it's from C++11 and thus VS2012+ exclusive and we still want to support VS2010 and (somewhat) VS2008 and VS2005 (?).

However, IIRC windows store apps require VS2012+ anyways to be built, so it may work for this specific use-case.

**Comment by zabulus** [comment]
I see that ```ThreadUserTimer``` is used in ```DeriveKey``` function implementation. It used for counting time that hashing (?) must take, to avoid too fast key generation. Correct me if understood it wrong.
I wonder what can cause high kernel time consumption, that specific ```ThreadUserTimer``` timer implementation is used? As I see, functions called in ```DeriveKey``` doesn't use kernel level calls. Or I am wrong?

> @zabulus the problem with std::chrono::high_resolution_clock is that it's from C++11 and thus VS2012+ exclusive and we still want to support VS2010 and (somewhat) VS2008 and VS2005 (?).
However, IIRC windows store apps require VS2012+ anyways to be built, so it may work for this specific use-case.

Indeed, that what I meant:
> if available

**Comment by noloader** [comment]
@zabulus, @DevJPM 

> I see that ThreadUserTimer is used in DeriveKey function implementations. 

Exactly. That's mostly the reason we want to ensure there's something available.

> It is used for counting time that hashing (?) must take, to avoid too fast key generation.

I believe its more a usability thing, and the time limit is an escape mechanism. Grinding a password or passphrase for N seconds results in different iteration counts. On a server, you can perform 30,000 or 50,000 iterations in a blink of an eye. On a mobile device, you will take seconds to 10's of seconds.

**Comment by zabulus** [comment]
I suggest a more simple solution.
For windows store application only make ```typedef TimerBase ThreadUserTime``` and undefine ```ThreadUserTime``` completely. It will make code a lot easier to understand. What do you think?

**Comment by noloader** [comment]
Now open on the Crypto++ mailing list: [Windows Phone, Windows Store and testing](https://groups.google.com/forum/#!topic/cryptopp-users/B0g1BHtxP3U).

**Comment by noloader** [comment]
The `windows-store` branch was merged into `master`. This issue is now resolved.

Git does not provide a log entry for the merger (or I cannot find it), so I don't have a record to offer for the transaction.
