### ISSUE TITLE
Use std::call for singleton implementation

### ISSUE THREAD

**Issue by zabulus** [weidai11/cryptopp#173]
Start of discussion in comments for commit https://github.com/weidai11/cryptopp/commit/b1a7ada564e629ed8697dc7009b1caed581975c8
cc @noloader

**Comment by zabulus** [comment]
> From a quick glance at the features, it looks like std::call_once is part of <mutex>. What do you think about CRYPTOPP_CXX11_MUTEX added to config.h and config.recommend?

I think we should not do such fine-grain separation. Mutex is a part of threading api surface. It is sufficient to check only for threading.

**Comment by noloader** [comment]
@zabulus  - where are yoiu with respect to a patch?

**Comment by zabulus** [comment]
Haven't started yet. I have lack of time for a couple of weeks.

**Comment by noloader** [comment]
A couple of items to report.... First, I implemented the standard [double-checked locking pattern](http://preshing.com/20130930/double-checked-locking-is-fixed-in-cpp11/).

Second, we still need atomics for the thread fences, so we depend upon `CRYPTOPP_CXX11_ATOMICS` for feature availability.

Third, mutex and locks depend upon C++11 Synchronization, so I added `CRYPTOPP_CXX11_SYNCHRONIZATION`. Atomics is not a proper subset of Synchronization - there are some minor differences in compiler versions between mutex and atomics.

Atomics branch, [misc.h](https://github.com/weidai11/cryptopp/blob/atomics/misc.h) and [Singletone::Ref](http://github.com/weidai11/cryptopp/blob/atomics/misc.h#L257) is the function of interest.
