### ISSUE TITLE
Missing Git tags

### ISSUE THREAD

**Issue by nmontmarquette** [weidai11/cryptopp#18]
Add missing git tags for a few of the latest releases:
- 5.4
- 5.5.2
- 5.6.0
- 5.6.1
- 5.6.2

Adding 5.6.2 tag:
```
git checkout 789f81f048c9bc472c7e7596f49b02eadd6fc1fd
git tag -a v5.6.2 -m 'version 5.6.2'
```

**Comment by noloader** [comment]
@nmontmarquette - This is on my TODO list.

**Comment by noloader** [comment]
@nmontmarquette - we are one step closer with the tags; see [Release Versioning](http://cryptopp.com/wiki/Release_Versioning)

**Comment by noloader** [comment]
Done.

We don't have a commit number, but it was announced at https://groups.google.com/d/msg/cryptopp-users/2tZ_AiJAwOk/5td086URCAAJ.
