### ISSUE TITLE
CBC_CTS_Encryption::ProcessLastBlock does not work inplace

### ISSUE THREAD

**Issue by berendeanicolae** [weidai11/cryptopp#185]
As CBC_CTS_Encryption inherits CBC_Encryption and CBC_Encryption::ProcessData allows the two buffers to be the same, I think CBC_CTS_Encryption::ProcessLastBlock should allow it too.
Or if not, an assert to check that are not the same would be useful.

**Comment by noloader** [comment]
@berendeanicolae - Is this a bug or a feature? Do you have simple test program to duplicate the issue?

Are you experiencing a core dump with `make CXXFLAGS=-DDEBUG -g2 -O1`? Or are you seeing incorrect results? If its one of those two, then its definitely a bug.

Do you have a patch or diff to recommend?

**Comment by berendeanicolae** [comment]
I would say it's a bug because it's not working as I expected. The documentation doesn't state that ProcessLastBlock should work inplace (it doesn't state anything regarding this issue). But regarding [ProcessData](https://www.cryptopp.com/docs/ref/class_stream_transformation.html#a26feabde21bc4d1783195969733e3bb0) it says "Either inString == outString, or they must not overlap".

Here is a code snippet which duplicates the issue http://pastebin.com/nFdN0U8B

**Comment by noloader** [comment]
From the looks of it under GDB, it appears none of `tmp` is being encrypted (if I am parsing things correctly):

```
(gdb) x/70b src
0x7ad100:	0xbf	0x6c	0xd1	0xec	0x30	0x09	0xc3	0x46
0x7ad108:	0x6f	0xf1	0x88	0x8a	0x2a	0x31	0x0a	0xa1
0x7ad110:	0x10	0x11	0x12	0x13	0x14	0x15	0x16	0x17
0x7ad118:	0x18	0x19	0x1a	0x1b	0x1c	0x1d	0x1e	0x1f
0x7ad120:	0x20	0x21	0x22	0x23	0x24	0x25	0x26	0x27
0x7ad128:	0x28	0x29	0x2a	0x2b	0x2c	0x2d	0x2e	0x2f
0x7ad130:	0x30	0x31	0x32	0x33	0x34	0x35	0x36	0x37
0x7ad138:	0x38	0x39	0x3a	0x3b	0x3c	0x3d	0x3e	0x3f
0x7ad140:	0x5f	0xe6	0x94	0xd2	0xe0	0x22
(gdb) x/70b tmp
0x7ad1a0:	0x00	0x01	0x02	0x03	0x04	0x05	0x06	0x07
0x7ad1a8:	0x08	0x09	0x0a	0x0b	0x0c	0x0d	0x0e	0x0f
0x7ad1b0:	0x10	0x11	0x12	0x13	0x14	0x15	0x16	0x17
0x7ad1b8:	0x18	0x19	0x1a	0x1b	0x1c	0x1d	0x1e	0x1f
0x7ad1c0:	0x20	0x21	0x22	0x23	0x24	0x25	0x26	0x27
0x7ad1c8:	0x28	0x29	0x2a	0x2b	0x2c	0x2d	0x2e	0x2f
0x7ad1d0:	0x30	0x31	0x32	0x33	0x34	0x35	0x36	0x37
0x7ad1d8:	0x38	0x39	0x3a	0x3b	0x3c	0x3d	0x3e	0x3f
0x7ad1e0:	0x40	0x41	0x42	0x43	0x44	0x45
(gdb) where
#0  main (argc=1, argv=0x7fffffffea58) at test.cxx:51
(gdb) l
46	  encryption.ProcessLastBlock(src + 48, src + 48, 22);
47	
48	  decryption.ProcessData(src, src, 48);
49	  decryption.ProcessLastBlock(src + 48, src + 48, 22);
50	
51	  assert(!memcmp(tmp, src, bufferSize));
52	
53	  delete[] src;
54	  delete[] dst;
55	  delete[] tmp;
```

I'll need to investigate it a little further later tonight.

**Comment by berendeanicolae** [comment]
I removed from the snippet some lines that are not required to reproduce the bug.
`
	memcpy(tmp, src, bufferSize); // backup src

	encryption.ProcessData(src, src, 48); // inplace encryption
	encryption.ProcessLastBlock(src + 48, src + 48, 22); // inplace encryption for last 2 blocks

	decryption.ProcessData(src, src, 48); // inplace decryption - works OK
	decryption.ProcessLastBlock(src + 48, src + 48, 22); // inplace decryption for last 2 blocks - only first block is correctly decrypted

	assert(!memcmp(tmp, src, bufferSize));
`

**Comment by berendeanicolae** [comment]
@noloader 

I've found the bug. I'm working on a fix

**Comment by noloader** [comment]
@berendeanicolae, 

> I've found the bug. I'm working on a fix

One thing to keep in mind is you are responsible for managing the blocks when calling `ProcessData` and `ProcessLastBlock`. This looks odd because I'm used to seeing 16-byte blocks operated upon:

```
ProcessData(src, src, 48)
```

This looks wrong because a 22-byte block is not a multiple of 16:

```
decryption.ProcessLastBlock(src + 48, src + 48, 22);
```

But I need to get into it further and see how the machinery works together.

**Comment by berendeanicolae** [comment]
@noloader 

> One thing to keep in mind is you are responsible for managing the blocks when calling ProcessData and ProcessLastBlock. This looks odd because I'm used to seeing 16-byte blocks operated upon:

From what I've seen in the source, ProcessData repeatedly encrypts blocks of BlockSize() until it finishes the whole size i've given to it.

> This looks wrong because a 22-byte block is not a multiple of 16:

Please keep in mind that ProcessLastBlock is used to correctly encrypt the last two blocks using ciphertext stealing. ProcessLastBlock is given the last 2 blocks (BlockSize() + what's left) to encrypt.

I've pushed a commit which solves the problem on my machine. Tomorrow I will test it to make sure everything is ok

**Comment by noloader** [comment]
> I've pushed a commit which solves the problem on my machine. Tomorrow I will test it to make sure everything is ok

OK, thanks.

Please be sure we have a self test that covers it. I'm not finding one, which may explain why this has gone uncovered for so long:

```
$ grep CBC_CTS_Encryption validat*.cpp bench*.cpp test.cpp
$
```

If you have access to a Unix or Linux machine, then please run [`cryptest.sh`](http://www.cryptopp.com/wiki/Release_process#Test_Script). You will get better results if Valgrind is installed.

**Comment by berendeanicolae** [comment]
I've run some tests and they seem to work fine - [pastebin](http://pastebin.com/3ubfLwGS). I've only tested on Windows x64 debug and release - unfortunately I do not have a linux machine.

> Please be sure we have a self test that covers the issue. I'm pretty sure we have tests, but I'm less sure about the "same buffer" requirement:

I've looked into the tests but I there seem to be a lot of classes involved. There's only a set of tests (encryption and decryption) for each ExternalCipher. I do not know how to check if it's done inplace or not.

**Comment by noloader** [comment]
> I've only tested on Windows x64 debug and release - unfortunately I do not have a linux machine.

OK, under Windows, you usually install Oracle's [Virtual Box](http://www.virtualbox.org/wiki/Downloads). Then, create a new VM and [install a distro like Ubuntu](http://www.google.com/search?q=virtualbox+install+linux+on+Windows).

**Comment by berendeanicolae** [comment]
Hello,

If CBC_CTS does not need to work in-place, this issue may be closed.
The issue was that all primitives except CBC_CTS, do work in-place (but it may have been intentionally designed so).

**Comment by noloader** [comment]
> If CBC_CTS does not need to work in-place, this issue may be closed.

Closing issue. Thanks.
