### ISSUE TITLE
SONAME not found in libcryptopp.so

### ISSUE THREAD

**Issue by DONGChuan** [weidai11/cryptopp#207]
Hi.

I'm using 5.6.3 currently. And can not find SONAME any more. (In 5.6.2, it exists). I used this command to check soname:

`objdump libcryptopp.so -x | grep soname
`
And used the following commands to build:

```
make -j 25
make -j 25 test
make install
make libcryptopp.a libcryptopp.so cryptest.exe
```

**Comment by noloader** [comment]
> I'm using 5.6.3 currently. And can not find SONAME any more. (In 5.6.2, it exists).

Hmmm.... It sounds like you were using a distribution's version of 5.6.2 (or even 5.6.3). I'm guessing the distro provided a SONAME'd lib when they cutover from GNUmakefile (supplied by the library) to Autotools (used by distro).

Sometime after 5.6.3, we added `SONAME` support for Linux. Here was the Pull Request: [PR 65, Linux shared-object library versioning](http://github.com/weidai11/cryptopp/pull/65/).

Can you investigate it further on your side of things?

**Comment by noloader** [comment]
@DONGChuan, were you able to isolate the issue as described above?

**Comment by DONGChuan** [comment]
@noloader Sorry for late. I m quite new about it. I tried HAS_SOLIB_VERSION=1 and SOLIB_VERSION_SUFFIX before build. But still with 

`objdump libcryptopp.so -x | grep soname `

I can not find SONAME

**Comment by noloader** [comment]
> objdump libcryptopp.so -x | grep soname

Try `grep -i`. I believe the section name is [`DT_SONAME`](http://flint.cs.yale.edu/cs422/doc/ELF_Format.pdf):

```
make libcryptopp.so
...

$ objdump -p libcryptopp.so | grep SONAME
```

  SONAME               libcryptopp.so.5.6

Here's the full output:

```
$ objdump -p libcryptopp.so

libcryptopp.so:     file format elf64-x86-64

Program Header:
    LOAD off    0x0000000000000000 vaddr 0x0000000000000000 paddr 0x0000000000000000 align 2**21
         filesz 0x00000000003672d9 memsz 0x00000000003672d9 flags r-x
    LOAD off    0x00000000003672e0 vaddr 0x00000000005672e0 paddr 0x00000000005672e0 align 2**21
         filesz 0x00000000000401e0 memsz 0x00000000000446d8 flags rw-
 DYNAMIC off    0x00000000003a2138 vaddr 0x00000000005a2138 paddr 0x00000000005a2138 align 2**3
         filesz 0x0000000000000210 memsz 0x0000000000000210 flags rw-
    NOTE off    0x0000000000000190 vaddr 0x0000000000000190 paddr 0x0000000000000190 align 2**2
         filesz 0x0000000000000024 memsz 0x0000000000000024 flags r--
EH_FRAME off    0x000000000030c680 vaddr 0x000000000030c680 paddr 0x000000000030c680 align 2**2
         filesz 0x000000000000b0f4 memsz 0x000000000000b0f4 flags r--
   STACK off    0x0000000000000000 vaddr 0x0000000000000000 paddr 0x0000000000000000 align 2**4
         filesz 0x0000000000000000 memsz 0x0000000000000000 flags rw-

Dynamic Section:
  NEEDED               libstdc++.so.6
  NEEDED               libm.so.6
  NEEDED               libgcc_s.so.1
  NEEDED               libpthread.so.0
  NEEDED               libc.so.6
  SONAME               libcryptopp.so.5.6
  INIT                 0x0000000000190fe8
  FINI                 0x00000000002dadfc
  INIT_ARRAY           0x00000000005672e0
  INIT_ARRAYSZ         0x0000000000000048
  FINI_ARRAY           0x0000000000567328
  FINI_ARRAYSZ         0x0000000000000008
  GNU_HASH             0x00000000000001b8
  STRTAB               0x0000000000045cb8
  SYMTAB               0x0000000000012880
  STRSZ                0x00000000000ac8b3
  SYMENT               0x0000000000000018
  PLTGOT               0x00000000005a4720
  PLTRELSZ             0x0000000000006fc0
  PLTREL               0x0000000000000007
  JMPREL               0x000000000018a028
  RELA                 0x00000000000f6ab8
  RELASZ               0x0000000000093570
  RELAENT              0x0000000000000018
  VERNEED              0x00000000000f69c8
  VERNEEDNUM           0x0000000000000005
  VERSYM               0x00000000000f256c
  RELACOUNT            0x00000000000001dd

Version References:
  required from libm.so.6:
    0x09691a75 0x00 09 GLIBC_2.2.5
  required from libgcc_s.so.1:
    0x0b792650 0x00 08 GCC_3.0
  required from libc.so.6:
    0x06969194 0x00 10 GLIBC_2.14
    0x09691a75 0x00 06 GLIBC_2.2.5
  required from libpthread.so.0:
    0x09691a75 0x00 03 GLIBC_2.2.5
  required from libstdc++.so.6:
    0x02297f89 0x00 11 GLIBCXX_3.4.9
    0x0297f871 0x00 07 GLIBCXX_3.4.21
    0x0297f865 0x00 05 GLIBCXX_3.4.15
    0x08922974 0x00 04 GLIBCXX_3.4
    0x056bafd3 0x00 02 CXXABI_1.3
```

**Comment by DONGChuan** [comment]
@noloader Hi Thanks for all these helps. I just find that the latest commit, so the master branch you showed above, it works perfectly with SONAME.

But if you download latest release/tag CRYPTOPP_5_6_3! NO SONAME at all! @noloader  So it will be fixed back in the next release 5.6.4 in the future?

**Comment by noloader** [comment]
> But if you download latest release/tag CRYPTOPP_5_6_3! NO SONAME at all! 

Right...

> [JW] Sometime after 5.6.3, we added SONAME support for Linux. Here was the pull request: PR 65: Linux shared-object library versioning...
> [JW] If you want a versioned library, then you need to work from GitHub Master at the moment. It will be in the 5.6.4 ZIP when it arrives...

**Comment by noloader** [comment]
@DONGChuan,

W are getting ready to release [Crypto++ 5.6.4](http://www.cryptopp.com/release564.html). Its effectively going through the "release candidate" testing. If there are no issues or complaints, we will tag the RC as the release.
