### ISSUE TITLE
ECIES uses byte count, and not bit count, for label size

### ISSUE THREAD

**Issue by noloader** [weidai11/cryptopp#21]
This issue was originally investigated and reported by Jesse Wilson and Daniele Perito at [Problem with the way gfpcrypt HMAC's the encoding parameters' length in DHAES_MODE](https://groups.google.com/forum/#!msg/cryptopp-users/vR8GSL8wxPA/Bf9koUDyZ88J). Since that time, David Hook of the Bouncy Castle project investigated further and found another interop issue: Crypto++'s ECIES should use a bit count for the label, and not a byte count.

The issue was confirmed by cross referencing both P1363, revision 13 and subsequent P1363 2000 publications.

This report creates an actionable item for tracking.

**Comment by DevJPM** [comment]
Does this actually change the interface (the user needs to supply bit
counts rather than byte counts?) or is it only some in-library only
thing needed for proper following of the specification?

BR

JPM

Am 30.07.2015 um 08:50 schrieb Jeffrey Walton:

**Comment by noloader** [comment]
> Does this actually change the interface (the user needs to supply bit counts rather than byte counts?) 

Theoretically speaking, I don't believe it changes the interface. All we need to do is:

    diff --git a/gfpcrypt.h b/gfpcrypt.h
    index 0590254..1537b31 100644
    --- a/gfpcrypt.h
    +++ b/gfpcrypt.h
    @@ -454,7 +454,7 @@ public:
     		if (DHAES_MODE)
     		{
     			byte L[8] = {0,0,0,0};
    -			PutWord(false, BIG_ENDIAN_ORDER, L+4, word32(encodingParameters.size()));
    +			PutWord(false, BIG_ENDIAN_ORDER, L, word64(8 * encodingParameters.size()));
     			mac.Update(L, 8);
     		}
     		mac.Final(ciphertext + plaintextLength);
    @@ -483,7 +483,7 @@ public:
     		if (DHAES_MODE)
     		{
     			byte L[8] = {0,0,0,0};
    -			PutWord(false, BIG_ENDIAN_ORDER, L+4, word32(encodingParameters.size()));
    +			PutWord(false, BIG_ENDIAN_ORDER, L, word64(8 * encodingParameters.size()));
     			mac.Update(L, 8);
     		}
     		if (!mac.Verify(ciphertext + plaintextLength))

But in practice, it creates a lot of troubles because we should support:

  * Original behavior
  * Conforming behavior
  * Bouncy Castle interop for downlevel clients

**Comment by noloader** [comment]
> But in practice, it creates a lot of troubles because we should support:
>
> * Original behavior
> * Conforming behavior
> * Bouncy Castle interop for downlevel clients

(1) For original behavior, I was thinking a `ECIES_COMPAT` class for Crypto++ users. This was formerly `ECIES`.

(2) For conforming behavior, I was thinking `ECIES`. This is the new, conforming behavior. Maybe it could be called `ECIES_P1363`???

(3) For Bouncy Castle interop, we could make a patch available for download (not part of the library, per David Hook's request), called something like `ECIES_BC_COMPAT`. This is for downlevel clients who need to interop with an older version of BC.

Regarding (3), I think its a good idea to accommodate David's request because the goal is to get users to use an updated, contemporary version of the library. But I also feel we should provide the users a choice. In this case, they have to work a bit for their choice, and I'm fine with that. (If they have to expend energy on ***A*** (BC Upgrade) or ***B*** (Crypto++ patch), then maybe that will swing them to ***A***. If we make ***B*** to easy, then they will always select ***B***).

**Comment by DevJPM** [comment]
Am 31.07.2015 um 07:17 schrieb Jeffrey Walton:
>
>     But in practice, it creates a lot of troubles because we should
>     support:
>
>       * Original behavior
>       * Conforming behavior
>       * Bouncy Castle interop for downlevel clients
>
> (1) For original behavior, I was thinking a |ECIES_COMPAT| class for
> Crypto++ users. This was formerly |ECIES|.
>
Sounds good.
>
> (2) For conforming behavior, I was thinking |ECIES|. This is the new,
> conforming behavior. Maybe it could be called |ECIES_P1363|???
>
I'd say we call the main ECIES template class ECIES and create a typedef
ECIES_P1363 for the instantiation which comes P1363's version closest
(we have 3-4 options to choose here). This would also maybe enable us
(or the user) to change be sure that  ECIES_P1363 will be compatible
with P1363 and the ECIES version would allow to change the hash function
(while it's fixed via typedef for ECIES_P1363).
>
> (3) For Bouncy Castle interop, we could make a patch available for
> download (not part of the library, per David Hook's request), called
> something like |ECIES_BC_COMPAT|. This is for downlevel clients who
> need to interop with an older version of BC.
>
> Regarding (3), I think its a good idea to accommodate David's request
> because the goal is to get users to use an updated, contemporary
> version of the library. But I also feel we should provide the users a
> choice. In this case, they have to work a bit for their choice, and
> I'm fine with that. (If they have to expend energy on */A/* (BC
> Upgrade) or */B/* (Crypto++ patch), then maybe that will swing them to
> */A/*. If we make */B/* to easy, then they will always select */B/*).
>
Sounds like a good plan to me.

BR

JPM

**Comment by noloader** [comment]
>> (2) For conforming behavior, I was thinking |ECIES|. This is the new,
>> conforming behavior. Maybe it could be called |ECIES_P1363|???
>>
> I'd say we call the main ECIES template class ECIES and create a typedef
> ECIES_P1363 for the instantiation which comes P1363's version closest
> (we have 3-4 options to choose here). 

I was thinking the same thing. But I'm not sure its the best strategy for the transition. Effectively, we a re pulling the rug out from underneath someone: they have code that compiles and runs, but it has an unexplained failure.

If we specifically avoid placing an ECIES name in the library for, say, 6 months or a year, then the compile breaks and people know where to start looking.

After a year, we can then perform the `typedef`. Six months or a year is just a blip on the radar....

**Comment by mouse07410** [comment]
I think it's one of those few cases when it is acceptable and even desirable to change the behavior, despite the inconvenience of potentially pulling the rug from underneath somebody,

I have a working ECIES compatibility setup between Crypto++ and BC, so I'll be able to test the changes. I'll let Dave know.

Sent from my iPad

On Jul 31, 2015, at 15:45, Jeffrey Walton <notifications@github.com<mailto:notifications@github.com>> wrote:


(2) For conforming behavior, I was thinking |ECIES|. This is the new,
conforming behavior. Maybe it could be called |ECIES_P1363|???

I'd say we call the main ECIES template class ECIES and create a typedef
ECIES_P1363 for the instantiation which comes P1363's version closest
(we have 3-4 options to choose here).

I was thinking the same thing. But I'm not sure its the best strategy for the transition. Effectively, we a re pulling the rug out from underneath someone: they have code that compiles and runs, but it has an unexplained failure.

If we specifically avoid placing an ECIES name in the library for, say, 6 months or a year, then the compile breaks and people know where to start looking.

After a year, we can then perform the typedef. Six months or a year is just a blip on the radar....

**Comment by noloader** [comment]
I was revisiting some of the issues here. P1363A allows Crypto++ to write either a bit count or a byte count, so Crypto++ is conforming (i.e., its not a bug on the Crypto++ side of things). However, I think from a security engineering POV, its is a security/usability bug because interop does not work.

If we hard code a change from bit count to byte count, then we could create the same problem all over again. So this problem seems to be [reducing to choice](https://www.youtube.com/watch?v=XypdR-dGj98)...

Its fairly evident to me that we need a parameter the specifies `bool BIT_COUNT`. ***`ECIES_ORIG`*** will use ***`BIT_COUNT = true`***, while ***`ECIES_XXX`*** will use ***`BIT_COUNT = false`*** and interop with Bouncy Castle.

We can then typedef ***`ECIES_XXX`*** to plain old ***`ECIES`***. 

As far as the name, maybe ***`ECIES_BC`*** would be a good choice? The BC can denote either *"Bouncy Castle"* or *"Bit Count"*.

**Comment by noloader** [comment]
> The ***`ECIES_XXX`*** scheme also allows us to add ISO/IEC's variant of ECIES in the future.

We ordered [ISO/IEC 18033-2:2006, Encryption algorithms, Part 2: Asymmetric ciphers](http://www.amazon.com/ISO-IEC-18033-2-Information-technology/dp/B000XYT4A0), so we should be able to add the ECIES variant.

**Comment by mouse07410** [comment]
See #216 to address BouncyCastle compatibility. Your https://github.com/weidai11/cryptopp/issues/21#issuecomment-126568087 is also recommended.

**Comment by noloader** [comment]
@mouse07410, @DevJPM,

I'm looking at the ECIES branch and this issue has not been resolved. There seems to be no material difference other than label size.

Do you know what's going on with it? Or maybe more correctly, why the code in the PR is ***not*** performing this:

```
if (DHAES_MODE)
{
    byte L[8] = {0,0,0,0,0,0,0,0};
    PutWord(false, BIG_ENDIAN_ORDER, L, word64(8 * encodingParameters.size()));
    mac.Update(L, 8);
}
```

**Comment by mouse07410** [comment]
@noloader what PR? There is `ecies` branch, and I just checked `gfpcrypt.h` file. This code certainly is there, around lines 535 and such. What needed change was `eccrypto.h` file that *said* that `DHAES` should be set to `true` in the comments, but did not actually *do* that. I fixed it.

And I regularly test my fork that has this code merged against the current BC GitHub code. It always works.

Please double-check and comment.

**Comment by noloader** [comment]
Thanks @mouse07410 ,

This is from David Hook's email from July 2015 when we were hashing things out :

> On Wed, Jul 15, 2015 at 7:23 PM, David Hook <dgh@cryptoworkshop.com> wrote:
> ...
> its:
>
> BC: one bug
>   - Label should be 8 octets
>
> Crypto++: one bug
>   - Length specified in bits
>
> Kind of figures neither of us would be 100%...

I can't find where `word64(8 * encodingParameters.size())` is used. It is not clear to me how its writing bits rather than bytes. Here's what I see form the dev-branch in [gfpcrypt:535](https://github.com/weidai11/cryptopp/blob/ecies/gfpcrypt.h#L529):

```
if (DHAES_MODE)
{
    byte L[8] = {0,0,0,0,0,0,0,0};
    PutWord(false, BIG_ENDIAN_ORDER, L, word64(encodingParameters.size()));
    mac.Update(L, 8);
}
```

**Comment by noloader** [comment]
@mouse07410,

> And I regularly test my fork that has this code merged against the current BC GitHub code. It always works.

We don't have any test vectors which actually test against Bouncy Castle data.

The closest we have is `ValidateECP()`. It basically performs a pairwise consistency check using `CryptoSystemValidate`. It generates a key pair and then round trips data through encryption and decryption.

We now have `ValidateLegacyECIES`. The data was generated using Crypto++ 5.6.2.

**Comment by mouse07410** [comment]
@noloader I'm pretty certain that this bug has been fixed by BouncyCastle before v1.54, because otherwise Crypto++ code wouldn't be able to interoperate with BC at all when they appear to disagree about the parameters length by a factor of 8. 

The only bug that affected interoperability (when the quantity of the transferred data <<2^32) was Crypto++ not using DHAES mode. To ensure that ECIES can handle data blobs of size >= 2^32 not only the `eccrypto.h` but also `gfpcrypt.h` was necessary.

**Comment by noloader** [comment]
@mouse07410,

I'd prefer be *"certain"* rather than *"pretty sure"*. Can you provide test data from your Bouncy Castle tests?

The test vectors are the easy part. The implementation and sorting out the incompatibilities was the hard part.

**Comment by mouse07410** [comment]
These were done in a hurry - but they (should) conform to what you asked:

> write a test program with Bouncy Castle _1.55_ that:
>
>  * uses ECP field
>  * uses curves secp256r1, secp384r1, secp512r1
>
>   * creates an ECIES object
>   * generates a private key
>   * save the private key to disk in PKCS#8
>
>  * creates a public key from the private key
>  * encrypts the 3 character string "abc"
>  * writes the resulting ciphertext to disk

I would not bet that the keys were stored in PKCS#8 format - but you can decode them with
```
 /************************************************************/
 /* Read and decode EC private and public keys             /**/
 ECIES<ECP>::PrivateKey  ecRPrKey;                         /**/
                                                           /**/
 string efn = CURVE_NAME + "-priv.hex";                    /**/
 FileSource fspp(efn.c_str(), true, new HexDecoder);       /**/
 ecRPrKey.BERDecode(fspp.Ref());                           /**/
 /************************************************************/
```

And here's the promised test-vectors: 
[ecies-testvec.zip](https://github.com/weidai11/cryptopp/files/491471/ecies-testvec.zip)

Let me know if you're happy with these. ;-)

**Comment by mouse07410** [comment]
Forgot to add:
```
SHA256(ecies-testvec.zip)= b6ccb74e0254e8af59c92887ecca778ef83e73c13a982273767f3f9028251dd4
```

:-)

**Comment by noloader** [comment]
Cleared at [Commit c3e2e0fb25fd](http://github.com/weidai11/cryptopp/commit/c3e2e0fb25fd1fa25e3a6e8eadb9ef78e8158be9).
