### ISSUE TITLE
Need to detect ARM64 for Windows

### ISSUE THREAD

**Issue by noloader** [weidai11/cryptopp#213]
According to Microsoft ([here](http://answers.microsoft.com/en-us/windows/forum/windows_10-win_upgrade/which-edition-of-windows-10-will-support-arm64/d2c3396e-3a69-40a3-a3a7-4ec7db9e5c51?auth=1) and [here](http://blogs.windows.com/windowsexperience/2015/03/18/windows-10-iot-powering-the-internet-of-things/)), the company will support ARMv8/Aarch64 (ARM-64) in upcoming version of Windows 10. Additionally, Microsoft has [already supplied previews](http://www.zdnet.com/article/microsoft-rolls-out-windows-10-redstone-build-14267-to-fast-ring-testers/) so I'm guessing tool support is in place.

`config.h` has the following placeholder for Microsoft's Aarch64/ARM64 support. However, we [don't know what the defines are to detect it](http://stackoverflow.com/q/37244202/608639):

```
// Requires ARMv8 and ACLE 2.0.
// Microsoft plans to support ARM-64, but its not clear how to detect it.
// TODO: Add MSC_VER and ARM-64 platform define when available
#if !defined(CRYPTOPP_BOOL_ARM_CRC32_INTRINSICS_AVAILABLE) && !defined(CRYPTOPP_DISABLE_ASM)
# if defined(__ARM_FEATURE_CRC32) || defined(_M_ARM64)
#  define CRYPTOPP_BOOL_ARM_CRC32_INTRINSICS_AVAILABLE 1
# endif
#endif

// Requires ARMv8 and ACLE 2.0.
// Microsoft plans to support ARM-64, but its not clear how to detect it.
// TODO: Add MSC_VER and ARM-64 platform define when available
#if !defined(CRYPTOPP_BOOL_ARM_CRYPTO_INTRINSICS_AVAILABLE) && !defined(CRYPTOPP_DISABLE_ASM)
# if defined(__ARM_FEATURE_CRYPTO) || defined(_M_ARM64)
#  define CRYPTOPP_BOOL_ARM_CRYPTO_INTRINSICS_AVAILABLE 1
# endif
#endif
```

**Comment by noloader** [comment]
According to [What’s new in Visual Studio Tools for Windows 10 Preview](http://jiangsheng.net/2015/03/24/whats-new-in-visual-studio-tools-for-windows-10-preview/), ARM-64 may be somehow tied to `WINAPI_FAMILY_ONECORE_APP`.

I found `WINAPI_FAMILY_ONECORE_APP` when browsing Microsoft's port of OpenSSL on GitHub. In particular, the commit titled [Adding Win10 Universal Platform support](http://github.com/Microsoft/openssl/commit/3e8a22c4c880cad92f36aa29f0c75d118e11f362).

**Comment by Myriachan** [comment]
Most likely, _M_ARM64 will just always support crypto intrinsics.  For runtime detection of whether the intrinsics are present, you can do: IsProcessorFeaturePresent with PF_ARM_V8_CRYPTO_INSTRUCTIONS_AVAILABLE and PF_ARM_V8_CRC32_INSTRUCTIONS_AVAILABLE.

**Comment by noloader** [comment]
Closing. Microsoft is shutting down its gadget business.  Also see [Microsoft exec says Windows 10 Mobile is no longer a 'focus'](https://www.engadget.com/2017/10/08/microsoft-exec-says-windows-10-mobile-is-no-longer-a-focus/).

If we come across the define we will be sure to add it.
