### ISSUE TITLE
Clang link errors when linking against Kovri

### ISSUE THREAD

**Issue by anonimal** [weidai11/cryptopp#232]
The following link errors occur **only** with clang when linking against [Kovri](https://github.com/monero-project/kovri). Tested on Arch, Ubuntu 14.04/15.10 and OSX 10.9.5 (clang 3.8.0, 3.6.0, 3.6.2, Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn), respectively).

I've only tested against 0b8cea5 and ```CRYPTOPP_5_6_3```. Note: linkage is successful when building against the latest tag.

```bash
$ git clone --recursive https://github.com/monero-project/kovri
$ git checkout 368bfdc  # current HEAD (for reference)
$ cd kovri/ && export CC=clang CXX=clang++ && make -j4 dependencies && make -j4
```

Linux:
```
../../libkovri-core.a(AES.cpp.o):(.data.rel.ro._ZTVN8CryptoPP16BlockCipherFinalILNS_9CipherDirE1ENS_8Rijndael3DecEEE[_ZTVN8CryptoPP16BlockCipherFinalILNS_9CipherDirE1ENS_8Rijndael3DecEEE]+0xa8): undefined reference to `CryptoPP::Rijndael::
Dec::AdvancedProcessBlocks(unsigned char const*, unsigned char const*, unsigned char*, unsigned long, unsigned int) const'
../../libkovri-core.a(AES.cpp.o):(.data.rel.ro._ZTVN8CryptoPP16BlockCipherFinalILNS_9CipherDirE1ENS_8Rijndael3DecEEE[_ZTVN8CryptoPP16BlockCipherFinalILNS_9CipherDirE1ENS_8Rijndael3DecEEE]+0x120): undefined reference to `non-virtual thunk t
o CryptoPP::Rijndael::Dec::AdvancedProcessBlocks(unsigned char const*, unsigned char const*, unsigned char*, unsigned long, unsigned int) const'
../../libkovri-core.a(AES.cpp.o):(.data.rel.ro._ZTVN8CryptoPP12ClonableImplINS_16BlockCipherFinalILNS_9CipherDirE1ENS_8Rijndael3DecEEES4_EE[_ZTVN8CryptoPP12ClonableImplINS_16BlockCipherFinalILNS_9CipherDirE1ENS_8Rijndael3DecEEES4_EE]+0xa8)
: undefined reference to `CryptoPP::Rijndael::Dec::AdvancedProcessBlocks(unsigned char const*, unsigned char const*, unsigned char*, unsigned long, unsigned int) const'
../../libkovri-core.a(AES.cpp.o):(.data.rel.ro._ZTVN8CryptoPP12ClonableImplINS_16BlockCipherFinalILNS_9CipherDirE1ENS_8Rijndael3DecEEES4_EE[_ZTVN8CryptoPP12ClonableImplINS_16BlockCipherFinalILNS_9CipherDirE1ENS_8Rijndael3DecEEES4_EE]+0x118
): undefined reference to `non-virtual thunk to CryptoPP::Rijndael::Dec::AdvancedProcessBlocks(unsigned char const*, unsigned char const*, unsigned char*, unsigned long, unsigned int) const'
```

OSX 10.9.5:
```
Undefined symbols for architecture x86_64:
  "CryptoPP::Rijndael::Dec::AdvancedProcessBlocks(unsigned char const*, unsigned char const*, unsigned char*, unsigned long, unsigned int) const", referenced from:
      vtable for CryptoPP::BlockCipherFinal<(CryptoPP::CipherDir)1, CryptoPP::Rijndael::Dec> in libkovri-core.a(AES.cpp.o)
      vtable for CryptoPP::ClonableImpl<CryptoPP::BlockCipherFinal<(CryptoPP::CipherDir)1, CryptoPP::Rijndael::Dec>, CryptoPP::Rijndael::Dec> in libkovri-core.a(AES.cpp.o)
  "non-virtual thunk to CryptoPP::Rijndael::Dec::AdvancedProcessBlocks(unsigned char const*, unsigned char const*, unsigned char*, unsigned long, unsigned int) const", referenced from:
      vtable for CryptoPP::BlockCipherFinal<(CryptoPP::CipherDir)1, CryptoPP::Rijndael::Dec> in libkovri-core.a(AES.cpp.o)
      vtable for CryptoPP::ClonableImpl<CryptoPP::BlockCipherFinal<(CryptoPP::CipherDir)1, CryptoPP::Rijndael::Dec>, CryptoPP::Rijndael::Dec> in libkovri-core.a(AES.cpp.o)
```

Kovri's build is [successful](https://travis-ci.org/monero-project/kovri/builds/147921883) with gcc5/6.

I don't develop exclusively with clang so please forgive me if the solution is simple. Since building against the latest tagged crypto++ release is successful, I imagine that there is something newer that may be running amuck.

**Comment by noloader** [comment]
`Rijndael::Enc::AdvancedProcessBlocks` is available when `CRYPTOPP_BOOL_X64 || CRYPTOPP_BOOL_X32 || CRYPTOPP_BOOL_X86` are defined. `Rijndael::Dec::AdvancedProcessBlocks` is available when `CRYPTOPP_BOOL_AESNI_INTRINSICS_AVAILABLE` (AES-NI) is defined. Also see [`rijndael.h`](https://github.com/weidai11/cryptopp/blob/master/rijndael.h).

I'm guessing (and its purely a guess), Crypto++ is being built ***without*** AES-NI support. Then, the application (like Krovi), is being built *with* AES-NI support. They key is the library and the application must both be built with the same flags. In some cases, the same compiler and same C++ runtime must be used, too.

For Clang, try adding `-march=native` or `-maes` to your `CXXFLAGS`.

I kinda expected this to be a bigger problem than shows up in the field because distros like Debian compile with SSE2 enabled but not much more. Debian's Crypto++ library will lack `Rijndael::Dec::AdvancedProcessBlocks`, while users with a modern processor will have `Rijndael::Dec::AdvancedProcessBlocks` enabled because AES-NI is available.

-----

> I imagine that there is something newer that may be running amuck.

Yeah, that could be, too. If something got knocked loose, then it was either (1) `config.h`, where defines like `CRYPTOPP_BOOL_AESNI_INTRINSICS_AVAILABLE` are set-up; or (2) `rijndael.{h|cpp}`, where defines like `CRYPTOPP_BOOL_AESNI_INTRINSICS_AVAILABLE`, are consumed.

I want to make some changes because Clang is so difficult to work with. The changes are staged in the [cpu branch](), but Clang is even more broken at the moment.

-----

> Tested on Arch, Ubuntu 14.04/15.10 and OSX 10.9.5 (clang 3.8.0, 3.6.0, 3.6.2, Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn), respectively)....

OK, I actually have OSX 10.9 and Apple LLVM version 6.0 (clang-600.0.57). The [test results](http://cryptopp.com/wiki/cryptest.sh) from yesterdays' run against Master look OK to me (see below). However, the [test script](http://cryptopp.com/wiki/cryptest.sh) only test static linking. It does not test dynamic linking.

Maybe you are hitting this bug caused by the GCC 5 ABI change: http://developers.redhat.com/blog/2015/02/05/gcc5-and-the-c11-abi/ .

```
$ ssh 172.16.4.3
...

$ clang++ --version
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.4.0

$ cd cryptopp
$ tail -55 cryptest-result.txt 
43 configurations tested
  - debug, default CXXFLAGS
 - release, default CXXFLAGS
 - debug, DISABLE_ASM
 - release, DISABLE_ASM
 - debug, c++03
 - release, c++03
 - debug, c++11
 - release, c++11
 - debug, gnu++11
 - release, gnu++11
 - debug, MAINTAIN_BACKWARDS_COMPATIBILITY
 - release, MAINTAIN_BACKWARDS_COMPATIBILITY
 - debug, INIT_PRIORITY
 - release, INIT_PRIORITY
 - debug, NO_UNALIGNED_DATA_ACCESS
 - release, NO_UNALIGNED_DATA_ACCESS
 - debug, NO_BACKWARDS_COMPATIBILITY_562
 - release, NO_BACKWARDS_COMPATIBILITY_562
 - debug, NO_OS_DEPENDENCE
 - release, NO_OS_DEPENDENCE
 - debug, USE_FIPS_202_SHA3
 - release, USE_FIPS_202_SHA3
 - debug, -O3 optimizations
 - release, -O3 optimizations
 - debug, -O5 optimizations
 - release, -O5 optimizations
 - debug, -Os optimizations
 - release, -Os optimizations
 - debug, -Ofast optimizations
 - release, -Ofast optimizations
 - debug, dead code strip
 - release, dead code strip
 - Darwin, c++03, libc++ (LLVM)
 - Darwin, c++03, libstdc++ (GNU)
 - Darwin, c++11, libc++ (LLVM)
 - Darwin, c++11, libstdc++ (GNU)
 - Darwin, Intel multiarch, c++03
 - Darwin, Intel multiarch, c++11
 - Darwin, c++03, Malloc Guards
 - Darwin, c++11, Malloc Guards
 - AES, RDRAND and RDSEED
 - GCC compiler
 - Xcode Clang compiler

************************************************

No failures detected
************************************************

No warnings detected
************************************************

Testing started: Tue Jul 26 15:55:25 EDT 2016
Testing finished: Tue Jul 26 18:12:45 EDT 2016
```

**Comment by anonimal** [comment]
Perfect guess @noloader, and thank you for the timely response.

```CXXFLAGS="-maes -march=native"``` appears to solve the issue for OSX and 15.10.

I haven't yet tried the others but I imagine the solution will stand across the board.

**Comment by noloader** [comment]
> CXXFLAGS="-maes -march=native" appears to solve the issue for OSX and 15.10.
>
> I haven't yet tried the others but I imagine the solution will stand across the board.

Oh, that gets much better... IoT is a priority, so the ARM and MIPS gadgets have been getting lots of testing lately. Checkout [ARM (Command Line)](https://cryptopp.com/wiki/Arm_(Command_Line)), where we try to select appropriate option.

**Comment by anonimal** [comment]
@noloader thanks for the tips. I'll keep them in mind when we officially support ARM.

Update: the ```CXXFLAGS``` solution is confirmed to work for the remaining clang versions I mentioned (though I've only tested on x86-64).

**Comment by noloader** [comment]
> Update: the CXXFLAGS solution is confirmed to work for the remaining clang versions I mentioned (though I've only tested on x86-64).

Yeah, I kind of thought that was the issue.

You can safely add `-mrdrnd` and `-mrdseed` too, just like you added `-maes`. All the implementation details and conditionals are in the CPP file. RDRAND and RDSEED does not cross pollinate like AES.

**Comment by anonimal** [comment]
Before I look at the code, would you recommend these switches for gcc as well?

Re: this issue remaining open, should we make a note somewhere in the documentation or let this thread do the explaining if someone does a search for help?

**Comment by noloader** [comment]
> Before I look at the code, would you recommend these switches for gcc as well?

Yes, you can enable `-maes`, `-mrdrnd` and `-mrdseed` for all compilers that accept GCC style options. That includes Comeau, GCC, Clang, and Intel ICPC. We guard the code in the CPP files with functions like `HasAESNI()`, `HasRDRAND()` and `HasRDSEED()`.

For other, *down-level hardware*, the best you can do is `-march=native`. For example, I test on a DL360 5th Generation server with dual Xeon's. That means `-march=native` expands to `-msse2`, `-msse3` and `-mssse3`.

Related, you can determine which `-mXXX` option is safe by examining `/proc/cpuinfo`. For example, here's crom a Core i7 2nd gen:

```
$ cat /proc/cpuinfo 
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 42
model name	: Intel(R) Core(TM) i7-2760QM CPU @ 2.40GHz
...
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush
dts mmx fxsr sse sse2 ss syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts nopl xtopology
tsc_reliable nonstop_tsc aperfmperf eagerfpu pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic
popcnt aes xsave avx hypervisor lahf_lm ida arat epb xsaveopt pln pts dtherm
...
```

Solaris and Sun's CC compiler is odd man out. Though its compiler is quasi-GCC, it does ***not*** accept `-maes`. For  SunCC you can `-xarch=aes`, but it [will *not* define `__AES__` in the preprocessor](http://stackoverflow.com/q/37772269/608639). For Sun, our test script gathers the CPU flags, and then manually sets preprocessor defines. You can see it in [cryptest.sh](http://github.com/weidai11/cryptopp/blob/master/cryptest.sh#L3710):

```
if [[ ("$IS_SOLARIS" -ne "0") && ("$SUNCC_121_OR_ABOVE" -ne "0") ]]; then
	ISAINFO=$(isainfo -v 2>/dev/null)
	if [[ ($(echo "$ISAINFO" | "$GREP" -c "sse2") -ne "0") ]]; then PLATFORM_CXXFLAGS+=("-D__SSE2__"); fi
	if [[ ($(echo "$ISAINFO" | "$GREP" -c "sse3") -ne "0") ]]; then PLATFORM_CXXFLAGS+=("-D__SSE3__"); fi
	if [[ ($(echo "$ISAINFO" | "$GREP" -c "ssse3") -ne "0") ]]; then PLATFORM_CXXFLAGS+=("-D__SSSE3__"); fi
	if [[ ($(echo "$ISAINFO" | "$GREP" -c "sse4.1") -ne "0") ]]; then PLATFORM_CXXFLAGS+=("-D__SSE4_1__"); fi
	if [[ ($(echo "$ISAINFO" | "$GREP" -c "sse4.2") -ne "0") ]]; then PLATFORM_CXXFLAGS+=("-D__SSE4_2__"); fi
	if [[ ($(echo "$ISAINFO" | "$GREP" -c "aes") -ne "0") ]]; then PLATFORM_CXXFLAGS+=("-D__AES__"); fi
	if [[ ($(echo "$ISAINFO" | "$GREP" -c "pclmulqdq") -ne "0") ]]; then PLATFORM_CXXFLAGS+=("-D__PCLMUL__"); fi
	if [[ ($(echo "$ISAINFO" | "$GREP" -c "rdrand") -ne "0") ]]; then PLATFORM_CXXFLAGS+=("-D__RDRND__"); fi
	if [[ ($(echo "$ISAINFO" | "$GREP" -c "rdseed") -ne "0") ]]; then PLATFORM_CXXFLAGS+=("-D__RDSEED__"); fi
	if [[ ($(echo "$ISAINFO" | "$GREP" -c "avx") -ne "0") ]]; then PLATFORM_CXXFLAGS+=("-D__AVX__"); fi
	if [[ ($(echo "$ISAINFO" | "$GREP" -c "avx2") -ne "0") ]]; then PLATFORM_CXXFLAGS+=("-D__AVX2__"); fi
	if [[ ($(echo "$ISAINFO" | "$GREP" -c "bmi") -ne "0") ]]; then PLATFORM_CXXFLAGS+=("-D__BMI__"); fi
	if [[ ($(echo "$ISAINFO" | "$GREP" -c "bmi2") -ne "0") ]]; then PLATFORM_CXXFLAGS+=("-D__BMI2__"); fi
fi
```


-----

> should we make a note somewhere in the documentation or let this thread do the explaining if someone does a search for help?

Both are fine with me. Google has already indexed the issue, so the thread is available. You can edit wiki pages like [Advanced Encryption Standard](http://www.cryptopp.com/wiki/Advanced_Encryption_Standard) and [RDRAND](http://cryptopp.com/wiki/Rdrand) if you'd like.

**Comment by anonimal** [comment]
Great, thanks for clarifying.
