### ISSUE TITLE
Suggested by code analyzer

### ISSUE THREAD

**Issue by irwir** [weidai11/cryptopp#235]
Pass by const reference for better perfrormance:
File _ecp.cpp_, line 348
`int operator-(const ZIterator& it2) {return int(it-it2.it);}`	
File _integer.cpp_, line 372
`	Word operator-(const Word& a)`

Another subject.
File _algebra.h_
`template <class T> class EuclideanDomainOf : public `AbstractEuclideanDomain<T>

Base class' protected member is redeclared as private:
`mutable Element result;`
It should have no effect with public inheritance.

**Comment by noloader** [comment]
> Suggested by code analyzer

What analyzer is producing the results? How can I get access to it?

**Comment by irwir** [comment]
There are options.
Free
[cppcheck](http://cppcheck.sourceforge.net/)
Visuzl Studio built-in; just get Community edition.
And Coverity services (never used it myself though).

Not so free, but available for limited trial: [PVS-Studio](http://www.viva64.com/en/pvs-studio-download/).

I would say that every analyzer has specifics and for the best results try all accessible at least from time to time.

**Comment by noloader** [comment]
> There are options...

What are you using to produce the findings you are reporting?

> And Coverity services (never used it myself though)....

We use Coverity's [free scanning service for open source projects](https://scan.coverity.com/projects/cryptopp). We don't hide anything, and the reports are world readable. I make [regular announcements when scan results are available](http://groups.google.com/forum/#!searchin/cryptopp-users/coverity$20scan)

**Comment by irwir** [comment]
The results are from the one which is not free.

**Comment by noloader** [comment]
> The results are from the one which is not free.

OK, thanks.

**Comment by irwir** [comment]
Closed without a word about the code itself?

**Comment by noloader** [comment]
> Closed without a word about the code itself?

I can't duplicate the results. I'm still unclear on the tool you are using. I've asked you for the name twice. I don't mean to sound harsh, but I have other things to do than dance with folks.

**Comment by irwir** [comment]
Sorry, _duplicate_ what? 
It was very surprising that instead of discussing quality of code the topic swerved to the subject of the tool name (besides, only one non-free analyzer was mentioned by me; so actually you have the answer).

Analyzers only suggest, it is the programmer who decides if the findings are valid and useful.
The name of the tool is completely irrelevant in that sense, because it is possible to find these issues just by looking at the code.

As for the first two changes, standard way of passing objects to operations is by constant reference, not by value. Do I need to explain why it is more efficient?
For the third issue - relationship between access modifiers and proper usage is defined by language standards. So re-declaration as private would have no effect.
