### ISSUE TITLE
SHA3 FIPS 202 Deprecation messages

### ISSUE THREAD

**Issue by kwentzell** [weidai11/cryptopp#240]
When using sha3.h on your repository I get the following warnings:

warning: 'SHA3_512' is deprecated (declared at ../../cryptopp-90f9d1a/sha3.h:84): SHA-3 will be changing in the future due to FIPS 202 finalization [-Wdeprecated-declarations]
     CryptoPP::SHA3_512 sha512;
                        ^

However, if I use cryptopp563, I don't get the warning. 

Wasn't this already finalized in 2015? Or weren't these changes included in your repository? I'm confused.

Thanks in advance!

**Comment by kwentzell** [comment]
Ahh, found the explanation in your comments ;-): https://github.com/weidai11/cryptopp/commit/920b23d884e684864ec6b7e79129a59ea9df5442

**Comment by noloader** [comment]
@kwentzell,

Also see the [Keccak dev-branch](http://github.com/weidai11/cryptopp/compare/keccak) and [Keccak dev-branch]() on the mailing list.

`Keccak` is available on the dev-branc. If there's no negative feedback, then it will be merged into Master soon. It will be available in the next release ZIP.

`SHA3` takes on conforming behavior with NIST's FIPS 202 specification for SHA-3.

**Comment by noloader** [comment]
Also see [Issue 262: Need better design for Keccak](https://github.com/weidai11/cryptopp/issues/262).

**Comment by kwentzell** [comment]
Thanks @noloader ! I'll check it out.
