### ISSUE TITLE
Cross compiling for android with c++11

### ISSUE THREAD

**Issue by polmr** [weidai11/cryptopp#243]
In case there's any interest to it: cross-compiling with toolchain android-ndk-r12b adding the c++11 flag fails. 

Steps to reproduce:

```
export ANDROID_NDK_ROOT=~/tools/android-ndk-r12b
export CXXFLAGS=-std=c++11
. ./setenv-android.sh 
make -f GNUmakefile-cross

arm-linux-androideabi-g++ -std=c++11 -march=armv5te -mtune=xscale -mthumb -msoft-float -funwind-tables
-fexceptions -frtti -DANDROID --sysroot=~/tools/android-ndk-r12b/platforms/android-21/arch-arm
-Wa,--noexecstack -I!/tools/android-ndk-r12b/sources/cxx-stl/stlport/stlport/ -c cryptlib.cpp
In file included from filters.h:21:0,
                from cryptlib.cpp:20:
secblock.h: In member function 'void CryptoPP::AllocatorBase<T>::construct(U*, Args&& ...)':
secblock.h:67:66: error: 'forward' is not a member of 'std'
    void construct(U* ptr, Args&&... args) {::new ((void*)ptr) U(std::forward<Args>(args)...);}
                                                                 ^
secblock.h:67:83: error: expected primary-expression before '>' token
    void construct(U* ptr, Args&&... args) {::new ((void*)ptr) U(std::forward<Args>(args)...);}
                                                                                  ^
GNUmakefile-cross:262: recipe for target 'cryptlib.o' failed
make: *** [cryptlib.o] Error 1
```

**Comment by polmr** [comment]
I believe that moving from STL PORT to GNU STL might solve this.

**Comment by noloader** [comment]
This is a known issue with STLport; see [AOSP Issue 216331: STLport does not support C++11](https://code.google.com/p/android/issues/detail?id=216331).

The AOSP folks have to say (from the bug report):

> stlport has been a dead project since long before C++11 existed, so there isn't any update we can take. We shouldn't be rejecting C++11 with stlport outright because you *can* use stlport with C++11, you just can't use any of the new library features. Things like range based for loops, auto, constexpr, and so on are still fine with stlport.
> 
> Understood that not everyone is comfortable with the GPL.
> 
> The solution here is libc++. Unfortunately its implementation in the NDK isn't 100% ready yet, but it's my main priority right now. r13 will have an up to date libc++, and hopefully in r14 we'll have fixed up the support library the backs it.
