### ISSUE TITLE
Make a Example of using Crypto++ as a basis of a Executable compressor.

### ISSUE THREAD

**Issue by AraHaan** [weidai11/cryptopp#251]
I by far find Crypto++ beeter with Encrypting things better than the current Executable compressors 1 of them being UPX. It would be nice forsomeone to make a example project that would work as a executable compressor and/or encryptor.

**Comment by noloader** [comment]
You should probably make this request on the [Crypto++ User List](http://groups.google.com/forum/#!forum/cryptopp-users).
