### ISSUE TITLE
Cmake lacks -march=native for compilers which support it

### ISSUE THREAD

**Issue by noloader** [weidai11/cryptopp#273]
At [Commit 9280850b2609153b](http://github.com/weidai11/cryptopp/commit/9280850b2609153b60c072378acbbf4ccc75b359) we enabled `VERBOSE=1` by default. Its revealing less than ideal `CXXFLAGS` with a basic or default configuration information:

```
Scanning dependencies of target cryptopp-object
...
[  0%] [  1%] Building CXX object CMakeFiles/cryptopp-object.dir/cpu.cpp.o
/usr/bin/c++ -fPIC -o CMakeFiles/cryptopp-object.dir/cpu.cpp.o -c /home/jwalton/cryptopp/cpu.cpp
Building CXX object CMakeFiles/cryptopp-object.dir/cryptlib.cpp.o
/usr/bin/c++ -fPIC -o CMakeFiles/cryptopp-object.dir/cryptlib.cpp.o -c /home/jwalton/cryptopp/cryptlib.cpp
...
```

**Comment by FloriansGit** [comment]
See also this discussion: https://cmake.org/pipermail/cmake/2016-May/063379.html

But you can always check for the availability/support of an compiler option by adding something like:

```
include(CheckCXXCompilerFlag)
CHECK_CXX_COMPILER_FLAG("-march=native" COMPILER_OPT_ARCH_NATIVE_SUPPORTED)

```

**Comment by noloader** [comment]
Thanks @FloriansGit. Sorry about the delay in getting back to you. We were putting out a CVE fire yesterday.

Since you have a GitHub, what do you think about cloning and making a Pull Request? I would be happy to merge your changes since the files are not performing as expected *and* they are not being maintained by anyone.

Here's how to do it:

```
git clone https://github.com/weidai11/cryptopp cryptopp-cmake
cd cryptopp-cmake

git checkout -b cmake
<make whatever changes you like>
git commit -m "Fix Cmake (Issues 268, 273, 276)"

git fork
git push FloriansGit feature

# I get this message
git pull-request

**Comment by FloriansGit** [comment]
Ok, I'm working on it. And I will do also some testing with CMake 2.8.5.

I've seen other settings/checks like `CRYPTOPP_NO_UNALIGNED_DATA_ACCESS` in your GNU `makefiles` that are not there in the `CMakeLists.txt`. Am I correct that it was just not yet transferred?

But I think I will do just the changes for this ticket and then we can discuss how/if I should proceed further aligning the CMake with the GNU makefile settings.

**Comment by noloader** [comment]
Cleared at [Commit d03938b7eee2f09e](https://github.com/weidai11/cryptopp/commit/d03938b7eee2f09e4f9acfb84d18b7feeed2cfad).
