### ISSUE TITLE
CMake produces artifacts without debugging information

### ISSUE THREAD

**Issue by noloader** [weidai11/cryptopp#276]
Sigh...

```
cryptopp-build$ rm -rf * && CXX=/opt/solstudio12.2/bin/CC cmake ../cryptopp
cryptopp-build$ make
Scanning dependencies of target cryptopp-object
[  1%] Building CXX object CMakeFiles/cryptopp-object.dir/cryptlib.cpp.o
CC: Warning: -xchip=native detection failed, falling back to -xchip=generic
[  2%] Building CXX object CMakeFiles/cryptopp-object.dir/cpu.cpp.o
CC: Warning: -xchip=native detection failed, falling back to -xchip=generic
...
```

And then

```
(dbx) where
=>[1] CryptoPP::Baseline_Multiply2(0x23e64d0, 0x240b6f0, 0x240b7b0, 0x240b7b0, 0xa, 0x23dcbc8), at 0x182fac7 
  [2] CryptoPP::RecursiveMultiply(0x0, 0x0, 0x0, 0x0, 0x0, 0x0), at 0x1846067 
  [3] CryptoPP::AsymmetricMultiply(0x0, 0x0, 0x0, 0x0, 0x0, 0x0), at 0x18473a0 
  [4] CryptoPP::PositiveMultiply(0x0, 0x0, 0x0, 0x0, 0x0, 0x0), at 0x1855167 
  [5] CryptoPP::Multiply(0x0, 0x0, 0x0, 0x0, 0x0, 0x0), at 0x18551da 
  [6] CryptoPP::Integer::Times(0x0, 0x0, 0x0, 0x0, 0x0, 0x0), at 0x18552c3 
  [7] CryptoPP::StringToInteger<char>(0x0, 0x0, 0x0, 0x0, 0x0, 0x0), at 0x1862e12 
  [8] CryptoPP::Integer::Integer(0x0, 0x0, 0x0, 0x0, 0x0, 0x0), at 0x184c9f5 
  [9] ValidateBBS(0x0, 0x0, 0x0, 0x0, 0x0, 0x0), at 0x11b6dcb 
  [10] ValidateAll(0x0, 0x0, 0x0, 0x0, 0x0, 0x0), at 0x108bf07 
  [11] Validate(0x0, 0x0, 0x0, 0x0, 0x0, 0x0), at 0xcdb7fe 
  [12] main(0x0, 0x0, 0x0, 0x0, 0x0, 0x0), at 0xca2e7a 
(dbx) 
```

**Comment by geoffbeier** [comment]
Did you try

cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ../cryptopp

?

**Comment by noloader** [comment]
Thanks Geoff. I'm aware of `-DCMAKE_BUILD_TYPE`. Unfortunately, that solution does not scale. We somehow have to tell every user of CMake to do it.

It would be better if CMake, in the absence of a setting like `CXXFLAGS='-DNDEBUG -g2 -O2` or ``-DCMAKE_BUILD_TYPE`, would select a reasonable default.

Also, lack of `-DNDEBUG` is probably a vulnerability for a security library. Without `-DNDEBUG` `asserts` are in effect. `assert` raises `SIGABRT` which means sensitive information is probably written to the filesystem. On some platforms, like Apple, Windows, Fedora, Red Hat, Debian and Ubuntu, the sensitive information is shipped to a third party through services like Windows Error Reporting and Apport.

**Comment by geoffbeier** [comment]
Does something like this:

https://gist.github.com/geoffbeier/e9dcb0f623153ecdf042f14728eb878a

get you default behavior you consider reasonable?

**Comment by FloriansGit** [comment]
Probably something like the following would help:

http://stackoverflow.com/questions/30540697/can-i-make-cmake-always-generate-debugging-symbols

And it's pretty common to select a default (in the surrounding build script or in your CMake itself), if no build-type for makefile generators is set. Something like:

```
if (NOT CMAKE_CONFIGURATION_TYPES AND NOT CMAKE_BUILD_TYPE)
    set(CMAKE_BUILD_TYPE RelWithDebInfo)
endif()
```

**Comment by noloader** [comment]
Last call for CMake patches before removing it from the library and adding it to the patch page. If you have something to add, then now is the time to do it.

Also see [Remove CMake from GitHub; add it to Patch Page on wiki?](https://groups.google.com/forum/#!topic/cryptopp-users/PKlz8-ClXOU) and [Commit 1c740b0a097aecaa](https://github.com/weidai11/cryptopp/commit/1c740b0a097aecaa66044036c0d2c54220eda5d5).
