### ISSUE TITLE
MARS max keysize is limited at 32 bytes - breaks CryFS

### ISSUE THREAD

**Issue by mouse07410** [weidai11/cryptopp#278]
Some products (like https://github.com/cryfs/cryfs.git) want to utilize keys longer than 256 bits. However `mars.h` sets the cap at 32 bytes, even though the original algorithm sets it at 56 bytes.

There is no reason for us to set that limitation (we aren't NIST, after all), so I request that it is removed.

**Comment by noloader** [comment]
> There is no reason for us to set that limitation (we aren't NIST, after all), so I request that it is removed.

PR?

**Comment by DevJPM** [comment]
Note: it may not be trivial to remove that limitation, depending on whether Wei expected the limit to be lifted back in the days when he implemented it and whether there is more code / constants required when the key size is increasing.

**Comment by mouse07410** [comment]
1. PR is here: https://github.com/weidai11/cryptopp/pull/281

2. Regarding 

> it may not be trivial to remove that limitation

Turns out it is.

> whether there is more code / constants required when the key size is increasing

there is no change.

3. 

> Please include test cases

This is the most difficult part. I'll what I can do, but my IBM Research contacts are long gone.

**Comment by noloader** [comment]
OK, thanks.

For completeness, I believe I broke that at [Commit 9767221125a27a5b](http://github.com/weidai11/cryptopp/commit/9767221125a27a5bca8b98b4a67a86aac05162a0). I think used wikipedia as a reference, and not the IBM paper; or maybe I used the original submission paper, and not the updated one. I don't recall now...

**Comment by mouse07410** [comment]
I screwed up - 448 bits equals to **56** bytes, not 58. :-(

Please see https://github.com/weidai11/cryptopp/pull/282

*At least I caught it before others had a chance to be hit by it.*

**Comment by noloader** [comment]
> At least I caught it before others had a chance to be hit by it.

Lol... Those test vectors are looking better and better :)
