### ISSUE TITLE
Add tweakable block ciphers, Threefish and Skein to Crypto++

### ISSUE THREAD

**Issue by DevJPM** [weidai11/cryptopp#279]
Skein is the hash function from Schneier, Fergueson and Lucks from the final round of the SHA-3 competition.

This issue is here to track the progress of the implementation of Skein and its underlying mode UBI and the underlying tweakable block cipher Threefish.

With the implementation I largely orientated at the BLAKE2 implementation for Skein and at Serpent with Threefish. The new interfaces add a fixed-size tweak-value (including new instances of a bunch of helper classes) which defaults to all-zero if the overloaded function isn't used.

Note: All the additional inputs and features of Skein are supported (excluding crazy modes like PRNG and PBKDF) but tree-hashing is unsupported, because I couldn't come up with a nice interface yet and the library traditionally didn't support tree-hashing.

Status:
- **UBI**: Straight hashing passes all test vectors, MAC-mode still needs verification, as test vector implementation into cryptest and addition to the benchmark suite are to-be-done. **Note:** Skein itself is just a "simple" instance of UBI.
- **Threefish**: Passes all provided test vectors, testing is part of `cryptest.exe v` and working, implementation (for now) is taken from the Skein3Fish project using the fully unrolled version. Reduction in code size (to not have a 150kB source file) and addition of XMM (for better perfomance on 32-bit platforms) implementation to follow

**Comment by noloader** [comment]
> Add tweakable block ciphers, Threefish and Skein ...

We have a dev-branch set-up for you at `skein`. I'd give you admin on the branch if Git allowed it, but I can't.

Experiment with the tweak at the design level. Try an few different designs ad see which one feels right. We can change it later if its not working out.

**Comment by DevJPM** [comment]
@noloader 
> We have a dev-branch set-up for you at skein. I'd give you admin on the branch if Git allowed it, but > I can't.

I already forked this branch, so I can PR against it, which I'll do as soon as the automated testing of Skein is ready.

> Experiment with the tweak at the design level. Try an few different designs ad see which one feels right. We can change it later if its not working out.

The design I'm using right now, which feels most natural to me, is to overload the `ProcessAndXorBlock()` functions with an additional tweak parameter, as you normally change the tweak with each block execution (much like an XOR mask). I've also overloaded the `AdvancedProcessBlocks()` function. From the hierarchy,  `TweakableBlockCipher` sits in between `BlockCipher` and `Threefish` which makes sense as this allows any tweakable block cipher to be used as standard cipher (w/ a zero tweak) no problem and very intuitively.
(If this doesn't make sense, wait one or two days and you'll see the code :) )

**Comment by noloader** [comment]
> >   We have a dev-branch set-up for you at skein. I'd give you admin on the branch if Git allowed it, but > I can't.
> 
> I already forked this branch, so I can PR against it, which I'll do as soon as the automated testing of Skein is ready.

OK, thanks. Do you perform regular pulls on Master? I.e., Are you using the latest sources?

(Merging something that's not sync'd is an awful task).

**Comment by DevJPM** [comment]
@noloader for dev'ing right now I'm using a copy of from around July, for the PR I'll use the copy I made quickly after you created the skein branch.

**Comment by noloader** [comment]
> for dev'ing right now I'm using a copy of from around July, for the PR I'll use the copy I made quickly after you created the skein branch.

Perfect, thanks.

Also, I can help with the BSD/Linux/Unix/Solaris integrations, if needed.

**Comment by noloader** [comment]
Threefish was added.
