### ISSUE TITLE
BlumBlumShub validation fails under ARMEL (likely others)

### ISSUE THREAD

**Issue by noloader** [weidai11/cryptopp#31]
László Böszörményi of Debian helped with some cross validation testing. Building the library under a ARMEL/chroot on Debian x86_64 produces the following results:

    BlumBlumShub validation suite running...
    
    passed    49ea2cfdb01064a0bbb92af101dac18a94f7b7ce
    FAILED    53171c6887956cea5d3b
    cryptest.exe: integer.cpp:2210: void CryptoPP::MultiplyTop(CryptoPP::word*, CryptoPP::word*, const word*, const word*, const word*, size_t):
    Assertion `c3 >= 0 && c3 <= 2' failed.
    uncaught target signal 6 (Aborted) - core dumped
    Aborted

The assert is due lack of `-DNDEBUG`, and it is expected in this case.

Böszörményi tried both Crypto++ 5.6.1 with patches (which effectively makes it roughly 5.6.2) and Crypto++ 5.6.3. The results were reproduced under 5.6.3 RC1 candidate as well.

-----

The following configurations *fail* to reproduce the issue. Each configuration is tested after a `make clean` to ensure artifacts don't cross pollinate.

 * `export CXXFLAGS="-DDEBUG -g3 -Og"`
 * `export CXXFLAGS="-g3 -Og"`
 * `export CXXFLAGS="-g3 -O1"`

The issue can be reproduced with:

 * `export CXXFLAGS="-g3 -O2"`
 * `export CXXFLAGS="-g3 -O3"`

The presence of `-DDEBUG` tells the makefile to enlist GXXLIB's debug and concept checks. In this case, two additional defines are defined: `-D_GLIBCXX_DEBUG` and `-D_GLIBCXX_CONCEPT_CHECKS`.

The presence of `-O3` tells the makefile to add `-DCRYPTOPP_NO_UNALIGNED_DATA_ACCESS`, which forbids unaligned data access (which is undefined behavior in C/C++). The ***`_NO_`*** define ensures `CRYPTOPP_ALLOW_UNALIGNED_DATA_ACCESS` is *not* defined. *Aligned data access* is effect all the time on this platform, regardless of `-DCRYPTOPP_NO_UNALIGNED_DATA_ACCESS`. It can be verified by inspecting the head of `cryptest.exe v` output and the message  (similar to) *"unaligned data access is not allowed..."*. The results have been verified with UBsan, Asan and Valgrind.

**Comment by noloader** [comment]
This has been a challenging issue. Its been challenging because it only shows up on this particular platform (ARMEL under QEMU within a Debian chroot environment). Its even more challenging because GDB does not work as expected (breakpoints are not honored, and I can't get backtraces with either `bt` or `bt full`).

We have a workaround for the issue. Effectively, this gets added to the top of `integer.cpp`:

    #if __ARMEL__ && (CRYPTOPP_GCC_VERSION >= 50200) && (CRYPTOPP_GCC_VERSION < 50300) && __OPTIMIZE__
    # define WORKAROUND_ARMEL_BUG 1
    #endif
	
    #if WORKAROUND_ARMEL_BUG
    # pragma GCC push_options
    # pragma GCC optimize("O1")
    #endif

And this gets added at the end of `intger.cpp`:

    #if WORKAROUND_ARMEL_BUG
    # pragma GCC pop_options
    #endif

**Comment by mouse07410** [comment]
This workaround has been successfully tested on the Macports clang-3.6 and gcc-5.2.

**Comment by noloader** [comment]
This might be due to [`-fdefer-pop`](http://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html) or [`-free`](http://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html). (I'm revisiting these optimizations problems while search for a solution to Debian's last issue of a hang in `sha.cpp`.

**Comment by noloader** [comment]
Also see [Commit 3941be18891a6a87](http://github.com/weidai11/cryptopp/commit/3941be18891a6a87626b7c70f715ca91c61c08c3)

**Comment by noloader** [comment]
Also see [Integer union removal and Integer dev-branch testing](http://groups.google.com/forum/#!topic/cryptopp-users/uVdM4bwxCFk). It details the history of this change.

An example of the hang is [Issue 31: BlumBlumShub validation fails under ARMEL (likely others)](http://github.com/weidai11/cryptopp/issues/31). We also experienced similar trouble on other non-mainstream platforms, and the trouble moved around as both the code and compiler changed.

And see the related [Issue 274: Solaris, integer.cpp and "Types cannot be declared in anonymous union"](http://github.com/weidai11/cryptopp/issues/274).
