### ISSUE TITLE
Coverity findings CID 171217-171280: Resource leak (RESOURCE_LEAK)

### ISSUE THREAD

**Issue by noloader** [weidai11/cryptopp#310]
Coverity Scan under Windows reports the following. There are approximately 80 similar findings. It appears the pattern is causing problems under Windows. Unix, Linux and OS X did not produce a finding.

```
    2. Condition this->IsNegative(), taking true branch.
    3. Condition this->WordCount() == 0, taking true branch.
3921        if (IsNegative() && WordCount()==0)   // avoid -0
    4. alloc_fn: Storage is returned from allocation function Zero. [show details]
    5. noescape: Resource CryptoPP::Integer::Zero() is not freed or pointed-to in operator =.
    CID 171218 (#1 of 1): Resource leak (RESOURCE_LEAK)
    6. leaked_storage: Failing to save or free storage allocated by CryptoPP::Integer::Zero() leaks it.
3922                *this = Zero();
3923        return *this;
```

Drilling into `(5) noescape`:

```
    1. noescape: CryptoPP::Integer::operator =(CryptoPP::Integer const &) does not free or save its parameter t.

3049 Integer& Integer::operator=(const Integer& t)
3050 {
3051   if (this != &t)
3052   {
3053     if (reg.size() != t.reg.size() || t.reg[t.reg.size()/2] == 0)
3054       reg.New(RoundupSize(t.WordCount()));
3055     CopyWords(reg, t.reg, reg.size());
3056     sign = t.sign;
3057   }
3058   return *this;
3059 }
```

**Comment by noloader** [comment]
First attempt at clearing the issue: [Commit afe391571bbefbb5](http://github.com/weidai11/cryptopp/commit/afe391571bbefbb53e150f2dd39d13bfb3501fdd).

**Comment by denisbider** [comment]
It is honestly not clear to me how all of these unpredictable, obscure, and difficult to address false positives are worth it. Has Coverity ever uncovered an actual issue, or have all the changes done to the code been to address its bogus detections? It seems to me it's overwhelmingly the latter, and in this case, it seems to me it's not worth using. Given that time is scarce as-is, servicing this finicky automated code connoisseur takes time away from other efforts (including perhaps ones that might result in bug detection), and offers a false sense of safety (given the number of difficult false positives it finds, this tool better find all bugs, but it doesn't).

**Comment by noloader** [comment]
Thanks @denisbider,

I think you are right on a lot of levels. Its an awful to get so many false positives, and its awful to be in the position of tradeoffs.

To Coverity's credit, it has helped us to track down three obscure issues. We got similar results from other tools, like Valgrind and the uninitialized read in the compression gear. And the analysis tools are getting better in general. In older days, Coverity may have produced 250 false positives :)

Now the interesting thing here is, Wei's code was probably good:

```
const Integer &Integer::Zero()
{
	return Singleton<Integer>().Ref();;
}
```

However, Microsoft compilers were generating bad code in response to it, and it resulted in this after running `cryptest.exe v` or `cryptest.exe tv all`:

```
...
Data: <class CryptoPP::> 63 6C 61 73 73 20 43 72 79 70 74 6F 50 50 3A 3A
{798887} normal block at 0x00AB0658, 8 bytes long.
Data: <  :   : > 18 B9 3A 00 B8 B9 3A 00
The program '[3444] cryptest.exe' has exited with code 0 (0x0).
```

Anchoring the integer on a static variable cleared the issue. So I think we may have dumb lucked into an alternate way to do things fixes an subtle issue we were not aware existed. 

Cutting down on the noise is important because it generates questions like this: [Memory leak in Crypto++ examples?](https://groups.google.com/forum/#!topic/cryptopp-users/UaQVF02ti6o)

**Comment by noloader** [comment]
We cleared this with the cited commit. Closing the issue.

**Comment by denisbider** [comment]
> However, Microsoft compilers may have been generating bad code in response to it.

I don't think they did. What you quoted (I think you edited it out later) is a memory leak detection. This looks like another false positive, and is common when using static objects that hold memory, especially if they're in #pragma init_seg (lib).

I don't think there was any type of issue. However, if you had changed this to use function-scope statics, then there would be a (potentially serious) issue.
