### ISSUE TITLE
Crypto++ on omnet++

### ISSUE THREAD

**Issue by hajji7777** [weidai11/cryptopp#313]
Hi every one.

When i want to import Crypto++ folder(or zip file), i found the Omnet++ wizard :

![crypto import](https://cloud.githubusercontent.com/assets/22495486/19016275/3b5ddee2-880d-11e6-8170-68b323af85ba.png)

Please help me to choose the right choice.

**Comment by noloader** [comment]
Please don't file bugs for user discussions.

**Comment by hajji7777** [comment]
I asked, 3 weeks ago, for help from omnet++ community group, but i had no answer until now!
I thought crypto++ community could help me.
