### ISSUE TITLE
Clang 3.6.2: gcm.cpp:143:25: error: use of undeclared identifier '_mm_clmulepi64_si128'

### ISSUE THREAD

**Issue by anonimal** [weidai11/cryptopp#320]
Built against tag `CRYPTOPP_5_6_4`, only confirmed on FreeBSD (haven't tested elsewhere).

Log (cryptopp at the bottom):
https://build.getmonero.org/builders/kovri-all-freebsd64/builds/10/steps/compile/logs/stdio

I wanted to get this issue submitted before I left. I'll be back (Tuesday) to test any patches.

https://github.com/weidai11/cryptopp/blob/CRYPTOPP_5_6_4/cpu.h#L112 ?

**Comment by noloader** [comment]
I believe this was cleared under [Issue 206](http://github.com/weidai11/cryptopp/issues/206). Its available in [Crypto++ 5.6.5](http://github.com/weidai11/cryptopp/releases/tag/CRYPTOPP_5_6_5).

I'll leave it open so you can test it. Feel free to close it or point out a bad platform.

**Comment by anonimal** [comment]
Thanks @noloader, fixed! Note: I looked at tags before opening this issue (*two* hours after tag was released) but didn't see the new tag (I could've sworn I was working on a fresh pull, my fault!)

**Comment by noloader** [comment]
@anonimal,

Don't sweat it. I think you opened the report around the time I was pushing the release.  If we did not catch those CVEs, then we would not have released a new version.
