### ISSUE TITLE
CMake build system is missing from 5.6.5 zip (cryptopp565.zip)

### ISSUE THREAD

**Issue by alonbl** [weidai11/cryptopp#325]
Hi,
Any reason why 5.6.4 contained cmake buildsystem and the 5.6.5 excluded it?
Isn't cmake should be used over the proprietary build?
Thanks!
Alon

[1] https://www.cryptopp.com/cryptopp565.zip

**Comment by alonbl** [comment]
zip is also missing from soureforge mirrors I believe.

**Comment by noloader** [comment]
This is by design. We removed it at [Commit e1fa9b26a838a233](e1fa9b26a838a233949b55ca9672181edef6f289).

**Comment by alonbl** [comment]
Thanks!
Reverting cmake back to proprietary for Gentoo.

**Comment by noloader** [comment]
Last call for CMake patches before removing it from the library and adding it to the patch page. If you have something to add, then now is the time to do it.

Also see [Remove CMake from GitHub; add it to Patch Page on wiki?](https://groups.google.com/forum/#!topic/cryptopp-users/PKlz8-ClXOU) and [Commit 1c740b0a097aecaa](https://github.com/weidai11/cryptopp/commit/1c740b0a097aecaa66044036c0d2c54220eda5d5).
