### ISSUE TITLE
crypto-dev support

### ISSUE THREAD

**Issue by exception0x876** [weidai11/cryptopp#335]
Hello,

I've got pretty low performance on transfers with AES-256-CBC on Marvell Armada 375 (Dual-core Cortex A9) using Tahoe-LAFS, which in turn uses pycryptopp, which in turn uses cryptopp.

There is a hardware crypto module available, and there is a kernel driver for it. The device is exposed as /dev/crypto (known as crypto-dev).

I've tested openSSL and its performance is greater while using crypto-dev. Is it possible to add crypto-dev support to cryptopp?

Thank you.

**Comment by noloader** [comment]
@exception0x876,

Please forgive my ignorance... Is that the BSD's device? Or does the Armada 375 have special circuits providing AES?

The reason I ask is, I know ARMv8 has CRC and Crypto extensions; but as far as I know ARMv7 and cpus like the A9 does not provide it.

**Comment by exception0x876** [comment]
Thanks for your reply.

The device has so called "Security Acceleration Engines" - you can see them on the block diagram here http://www.marvell.com/embedded-processors/armada-300/assets/ARMADA_375_SoC-01_product_brief.pdf

A bit more details on page 53rd here http://www.marvell.com/embedded-processors/armada-xp/assets/ARMADA-XP-Functional-SpecDatasheet.pdf

Just to confirms it is available on my system, here is the line from dmesg

[    3.471796] marvell-cesa f1090000.crypto: CESA device successfully registered

**Comment by noloader** [comment]
> The device has so called "Security Acceleration Engines" 

Ack, thanks.

I'd be interested in it, too. We started on some of the specialized ARM implementations. The holdup is the comment a few items down in [Issue 297: Separate AES from Rijndael; Support Rijndael 192-bit and 256-bit block sizes](https://github.com/weidai11/cryptopp/issues/297#issuecomment-249084087).

**Comment by noloader** [comment]
We added Andy Polyakov/Cryptogams implementation for AES, SHA-1 and SHA-256. You should see about the same performance as OpenSSL.

Also see https://www.cryptopp.com/wiki/Cryptogams .
