### ISSUE TITLE
Remove VC++ 5.0/6.0 support

### ISSUE THREAD

**Issue by noloader** [weidai11/cryptopp#342]
Crypto++ currently supports VC++ 5.0/6.0 support from the mid 1990's. Its caused us to keep code like the following from `sha.cpp`:

```
static void X86_SHA256_HashBlocks(word32 *state, const word32 *data, size_t len
#if defined(_MSC_VER) && (_MSC_VER == 1200)
	, ...	// VC60 workaround: prevent VC 6 from inlining this function
#endif
	)
```

We would like to remove VC++ 5.0/6.0 support for the upcoming Crypto++ 5.7 release. Its part of a general cleanup to help with long term maintenance. Crypto++ will continue to support the early .Net compilers (VS.Net 2002 (7.0) and VS.Net 2003 (7.1)). The .Net compilers are a good choice because they are mostly conforming.

WD has no preference on the move.

**Comment by noloader** [comment]
Most of the VC++ 5.0 and 6.0 cruft was removed at [Commit ba75834ae9b3846a](http://github.com/weidai11/cryptopp/commit/ba75834ae9b3846a19291c8c281626dd0a891779).

**Comment by noloader** [comment]
Most of the VC++ 5.0 and 6.0 cruft was removed at [Commit ba75834ae9b3846a](http://github.com/weidai11/cryptopp/commit/ba75834ae9b3846a19291c8c281626dd0a891779).

**Comment by noloader** [comment]
Most of the VC++ 5.0 and 6.0 cruft was removed at [Commit ba75834ae9b3846a](http://github.com/weidai11/cryptopp/commit/ba75834ae9b3846a19291c8c281626dd0a891779).

**Comment by noloader** [comment]
Most of the VC++ 5.0 and 6.0 cruft was removed at [Commit ba75834ae9b3846a](http://github.com/weidai11/cryptopp/commit/ba75834ae9b3846a19291c8c281626dd0a891779).

We got cleaned up the remainder of the dummy parameters at [Commit 86b89cd18b9df59e](https://github.com/weidai11/cryptopp/commit/86b89cd18b9df59eee1d2562a94d80665241b392).

**Comment by AraHaan** [comment]
I support this.
