### ISSUE TITLE
Default Socket::Listen backlog value is ancient and much too low

### ISSUE THREAD

**Issue by denisbider** [weidai11/cryptopp#349]
The default Socket::Listen backlog value is 5, most likely because this was the maximum supported 20 years ago in Windows Sockets 1:

https://github.com/weidai11/cryptopp/blob/master/socketft.h#L75

This should be SOMAXCONN on Windows. Not sure about similar magic values on other platforms.

A value as low as 5 will cause connections to be dropped if an application needs to handle many incoming connections at the same time, and users will complain about these dropped connections.

**Comment by noloader** [comment]
It looks like [`SOMAXCONN`](http://pubs.opengroup.org/onlinepubs/9699919799/functions/listen.html) is Posix. Its supposed to be available in `<sys/socket.h>`.

Do you feel like making the change? I'll get it tested in the next round of testing.

**Comment by denisbider** [comment]
I've made the change. No preference on label.

**Comment by noloader** [comment]
Thank @denisbider .
