### ISSUE TITLE
Evaluate advanced tool-assisted security checking

### ISSUE THREAD

**Issue by DevJPM** [weidai11/cryptopp#350]
Google has recently published [project wycheproof](https://github.com/google/wycheproof), which is a tool / library for testing implementations for common cryptographic attacks (it's in Java though). We at least should think about hacking together a thin wrapper and applying this tool on Crypto++.

Additionally there are a bunch of tools for verification of constant-timedness of code which we maybe should also evaluate to use.

- https://github.com/oreparaz/dudect which is a tool that basically fuzzy-tests the code and checks if it runs in constant time (by literally measuring the execution time), the effort needed for integration should be quite low (the relevant paper is: https://eprint.iacr.org/2016/1123 )

- https://github.com/agl/ctgrind which is a patch to valgrind that changes the uninitialised-memory-access-detection-engine to detect control decisions made upon secret data, the integration effort is probably quite high here because the patches are several years old

- https://github.com/imdea-software/verifying-constant-time which is a modified version of Clang LLVM (AFAICT) that runs through "test-cases" and verifies constant-timeness on an assembly level (AFAICT), the relevant paper should be https://www.usenix.org/system/files/conference/usenixsecurity16/sec16_paper_almeida.pdf

**Comment by noloader** [comment]
Also see [Testing C and C++ libraries](http://groups.google.com/d/msg/wycheproof-users/w75p2dw-Thw/gQgzf-dWDgAJ) on the wycheproof-users mailing list.

**Comment by noloader** [comment]
The project wycheproof folks cam back with an answer at  [Testing C and C++ libraries](http://groups.google.com/d/msg/wycheproof-users/w75p2dw-Thw/gQgzf-dWDgAJ):



On Fri, Dec 23, 2016 at 7:37 AM, Daniel Bleichenbacher <...> wrote:
> On Fri, Dec 23, 2016 at 7:03 AM, <...> wrote:
>>
>> ...
>> I'd like to evaluate C libraries and C++ libraries. README.md does not
>> mention them by name, but does state "We are converting as many tests into
>> sets of test vectors to simplify porting the tests to other languages".
>>
>> How would one go about testing a C or C++ library? Is there a documented
>> procedure or guidlines available somewhere?
>>
>> Looking at the sources, I'm guessing JNI wrappers that provide entry
>> points used by the test classes, like AesEaxTest, are needed. I'm less clear
>> on how to avoid a SE Provider, which WycheproofRunner seems to rely on.
>>
>> Thanks in advance,
>
> One of the goals of the project is trying to avoid rewriting tests for each
> library.
> Very helpful for this goal are common interfaces: JCA is such a common
> interface and the reason for starting the project in Java.
> For libraries that do not have a common interface at least the test vector
> can be reused. Hence, we try to use a much test vectors as possible.
> For C/C++ we might define an interface for the tests and rewrite them it
> just hasn't been done yet.
>
> We test part of boringSSL through conscrypt. Though these tests tell more
> about the quality of conscrypt than the quality of boringSSL.
> Thus I think writing JNI wrappers just for testing a library is overkill.

So it looks lik its a dead-end at the moment.
