### ISSUE TITLE
Sourceforge link to 5.6.5 is bad: no 5.6.5 release file on sourceforge.

### ISSUE THREAD

**Issue by grahamc** [weidai11/cryptopp#353]
https://sourceforge.net/projects/cryptopp/files/cryptopp/ has no 5.6.5 release whereas https://cryptopp.com/release565.html links to it.

**Comment by noloader** [comment]
You should use either the website's original download or the GitHub download.

We're in the process of sun-setting Sourceforge due to the malware/adware insertion. Its not a trusted distribution channel. The process will be complete very soon.

**Comment by grahamc** [comment]
I'm fine with that, but this is a bug report that the webpage links to nowhere.

**Comment by noloader** [comment]
Subversion commit 608 sync'd SVN with GitHub 5.6.5. The files should be present now.
