### ISSUE TITLE
Crypto++ should provide a pkg-config for users and distros

### ISSUE THREAD

**Issue by noloader** [weidai11/cryptopp#36]
See [How to change the include file path with autotools?](http://stackoverflow.com/q/32805772)

We invited the Debian, Fedora and Macport maintainers to comment and provide general advice.

**Comment by noloader** [comment]
A number of distros were invited to comment on this, but none of them took interest. Closing this issue.

**Comment by nvinacur** [comment]
This library has like 20 years and is not able to compile with cmake and not even provide support for pkg-config. The documentation is super bad organized. I guess your library is super cool but provide support for people using it in the same way as all the important libraries do.
