### ISSUE TITLE
Apple Clang 6.0 and numeric_limits<word128>::max() returns 0

### ISSUE THREAD

**Issue by noloader** [weidai11/cryptopp#364]
Testing on OS X 10.9 using Apple Clang 6.0. `cryptest.sh` reveals `TestRounding()` is failing one test case:

```
try
{
    const word128 h = ((word128)W64LIT(0xffffffffffffffff)) << 64U;
    const word128 v = h | (word128)W64LIT(0xfffffffffffffff9), b=0x08;
    word128 r=RoundUpToMultipleOf(v, b);
    fail = true;
}
catch(const Exception&)
{
    fail = false;
}
```

Here's the debug session with `const word128 m = std::numeric_limits<word128>::max();` added for instrumentation.

```
Breakpoint 1, TestRounding () at validat0.cpp:456
456                     const word128 h = ((word128)W64LIT(0xffffffffffffffff)) << 64U;
(gdb) n
457                     const word128 v = h | (word128)W64LIT(0xfffffffffffffff9), b=0x08;
(gdb)
458                     const word128 m = std::numeric_limits<word128>::max();
(gdb)
459                     word128 r=RoundUpToMultipleOf(v, b);
(gdb) p v
$1 = 0xfffffffffffffffffffffffffffffff9
(gdb) p m
$2 = 0x00000000000000000000000000000000
```

The tests were put in place after [Issue 360](https://github.com/weidai11/cryptopp/issues/360).

**Comment by anonimal** [comment]
>Testing on OS X 10.9

10.9 reached end of life last year. Will cryptopp continue 10.9 support? Does cryptopp have any 10.10+ machine(s) available to do testing on?

**Comment by noloader** [comment]
> 10.9 reached end of life last year. Will cryptopp continue 10.9 support?

Yes, we support as far back as we reasonably can. OS X is a great example of why. Apple abandoned the platform, so the only way for users to stay up to date is to use up-to-date libraries.

Projects like Brew, Fink and MacPorts are a great help. But they depend on projects like Botan, Crypto++ and OpenSSL maintaining libraries for them to use.

> Does cryptopp have any 10.10+ machine(s) available to do testing on?

I do not. I have OS X 10.5, 10.8 and 10.9. I believe Uri tests on OS X 10.10 or 10.11.

We also have gaps in testing on iPhones and iPads. I have 5 iPads, 1 iPhone and 1 iPod. All of them are older and abandoned by Apple. I think the latest OS I can test is iOS 8 or iOS 9.

I have no devices for testing Apple watch and Apple TV.

I'm not sure what other users have, but testing is welcomed on all of them.

**Comment by anonimal** [comment]
Ok. I have 10.12 to test on (also 10.10 and 10.11) but not the rest. I'm watching the repo and keep up when I can. If any OSX 10.10+ issues catch my eye then I'll see what I can do. If you happen to remember to ping me for 10.12 testing then I'll keep an eye out for that too.

**Comment by mouse07410** [comment]
I was testing on Mac OS X 10.9, 10.10, and 10.11. Now I'm testing on 10.12, and am about to lose my only remaining 10.11 machine soon.

But I still think it is beneficial to maintain compatibility with the older OS (and to a lesser extent - older building systems).

Sent from my iPad

On Jan 15, 2017, at 16:04, Jeffrey Walton <notifications@github.com<mailto:notifications@github.com>> wrote:


@anonimal<https://github.com/anonimal>, @mouse07410<https://github.com/mouse07410>

10.9 reached end of life last year. Will cryptopp continue 10.9 support?

Yes, we support as far back as we reasonably can. OS X is a great example of why. Apple abandoned the platform, so the only way for users to stay up to date is to use up-to-date libraries.

Projects like Brew, Fink and MacPorts are a great help. But they depend on projects like Botan, Crypto++ and OpenSSL maintaining libraries for them to use.

Does cryptopp have any 10.10+ machine(s) available to do testing on?

I do not. I have OS X 10.5, 10.8 and 10.9. I believe Uri tests on OS X 10.10 or 10.11.

We also have gaps in testing on iPhones and iPads. I have 5 iPads, 1 iPhone and 1 iPod. All of them are older and abandoned by Apple. I think the latest OS I can test is iOS 8 or iOS 9.

I have no devices for testing Apple watch and Apple TV.

I'm not sure what other users have, but testing is welcomed on all of them.

**Comment by noloader** [comment]
@anonimal , @mouse07410,

The issue appears to be bound to Apple Clang. Testing LLVM Clang is OK.

How does the program perform on some of the later OS X's? You can compile it with `c++ -Wall test.cxx -o test.exe`.

```
$ cat test.cxx
#include <iostream>
#include <limits>

int main(int argc, char* argv[])
{
#if (__SIZEOF_INT128__ >= 16)
    std::cout << "__int128 is available" << std::endl;
#else
    std::cout << "__int128 is not available" << std::endl;
#endif

    unsigned __int128 m = std::numeric_limits<unsigned __int128>::max();
    if (m == 0)
        std::cout << "numeric_limits<unsigned __int128>::max() is 0" << std::endl;
    else
        std::cout << "numeric_limits<unsigned __int128>::max() is not 0" << std::endl;

    return 0;
}
```

**Comment by noloader** [comment]
I believe this was cleared at [Commit b274f062022eeb86](https://github.com/weidai11/cryptopp/commit/b274f062022eeb8622e801ea88bcc981a3d46bc8).

`RoundUpToMultipleOf` and `RoundDownToMultipleOf` are tricky functions. We want them to be minimal so they are fast. The library also uses unsigned types or non-negative values. However, that does not mean users are doing the same.

We added more documentation and some asserts to help folks use the functions as intended, and not operate outside the bounds.

**Comment by noloader** [comment]
I believe this was cleared at [Commit b274f062022eeb86](http://github.com/weidai11/cryptopp/commit/b274f062022eeb8622e801ea88bcc981a3d46bc8) (Clang and GCC) and [Commit 1d391c190d8c4869](http://github.com/weidai11/cryptopp/commit/1d391c190d8c48699a44ab569a1da3dcd3e77b9d) (MSVC).

`RoundUpToMultipleOf` and `RoundDownToMultipleOf` are tricky functions. We want them to be minimal so they are fast. The library also uses unsigned types or non-negative values, so the library's use is safe. However, that does not mean users are doing the same.

We added more documentation and some asserts to help folks use the functions as intended, and not operate outside the bounds.
