### ISSUE TITLE
Crash in SHA under iOS 5.1.1

### ISSUE THREAD

**Issue by noloader** [weidai11/cryptopp#37]
$ . ./setenv-ios.sh
    $ make -f GNUmakefile-cross 
    clang++ -DNDEBUG -g2 -Os -mios-version-min=5.1 -DCRYPTOPP_NO_UNALIGNED_DATA_ACCESS -DCRYPTOPP_DISABLE_ASM
    -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk
    -stdlib=libc++ -c cryptlib.cpp
    ...

    JWs-iPad:~/cryptopp563 root# ./cryptest.exe tv sha
    Using seed: 1443896312     
    
    Testing MessageDigest algorithm SHA-1.
    ...
    Testing MessageDigest algorithm SHA-224.
    ...
    Testing MessageDigest algorithm SHA-256.
    ...
    Testing MessageDigest algorithm SHA-384.
    ...Abort trap: 6

**Comment by mouse07410** [comment]
Sure seems like alignment issue. Was it built with “make aligned” or such?


On Oct 3, 2015, at 14:19 , Jeffrey Walton <notifications@github.com<mailto:notifications@github.com>> wrote:
JWs-iPad:~/cryptopp563 root# ./cryptest.exe tv sha

Using seed: 1443896312

Testing MessageDigest algorithm SHA-1.
...
Testing MessageDigest algorithm SHA-224.
...
Testing MessageDigest algorithm SHA-256.
...
Testing MessageDigest algorithm SHA-384.
...Abort trap: 6


—
Reply to this email directly or view it on GitHub<https://github.com/weidai11/cryptopp/issues/37>.

--
Uri Blumenthal
uri@mit.edu<mailto:uri@mit.edu>

**Comment by noloader** [comment]
> Sure seems like alignment issue. Was it built with “make aligned” or such?

Yes. iOS always builds with `CRYPTOPP_NO_UNALIGNED_DATA_ACCESS`.

**Comment by noloader** [comment]
This could be related to [Issue 47, Hang in SHA with Debian Sid, GCC 5.2 and Core2 Duo hardware](http://github.com/weidai11/cryptopp/issues/47) and [Issue 46, Remove implementation of ResizeBuffer() from headers](http://github.com/weidai11/cryptopp/pull/46).

**Comment by noloader** [comment]
This appears to be a iPad1/iOS 5.1 issue. It could be related to later versions of Xcode and older iPads or something similar.

It can't be duplicated using iPad2's with iOS 6 and iOS 8.
