### ISSUE TITLE
Homebrew package broken

### ISSUE THREAD

**Issue by smessmer** [weidai11/cryptopp#370]
I've tried installing cryptopp using "brew install cryptopp" on two Macs already, one of them was newly setup, so there's nothing strange going on in the system.
On both computers, the install just stalls in the make step and doesn't continue from there. I've kept it running for hours, and there was no CPU usage.

    me-mbp:~$ brew install cryptopp
    ==> Using the sandbox
    ==> Downloading https://github.com/weidai11/cryptopp/archive/CRYPTOPP_5_6_5.tar.gz
    Already downloaded: /Users/me/Library/Caches/Homebrew/cryptopp-5.6.5.tar.gz
    ==> make shared all CXX=clang++

I have MacOS Sierra 10.12.3.

I also tried to get into interactive homebrew and call `make --help` from the shell, but even `make --help` hangs the same way. I'm not sure whether this is an issue with homebrew or with cryptopp, but since this only happens with the cryptopp package (other homebrew packages install fine), I report it here.

**Comment by noloader** [comment]
@smessmer,

I'm not familiar with Brew (I use MacPorts on occasion). I think you can test the Crypto++ distribution with:

```
# Fetch
wget https://github.com/weidai11/cryptopp/archive/CRYPTOPP_5_6_5.zip
unzip -aoq cryptopp-test
cd cryptopp-test
# Build
CXX=clang++ make all -j 4
# Test
./cryptest.exe v
./cryptest.exe tv all
```

If that tests OK, then I would reach out to the Brew folks. If there's something we can do to help them, then we would be happy to entertain it.

-----

Here are some other folks who use Macs: @mouse07410, @anonimal. They may have some insight.

**Comment by anonimal** [comment]
@smessmer I *cannot* reproduce this issue.

```bash
$ brew install cryptopp
Updating Homebrew...
...
==> Using the sandbox
==> Downloading https://github.com/weidai11/cryptopp/archive/CRYPTOPP_5_6_5.tar.gz
==> Downloading from https://codeload.github.com/weidai11/cryptopp/tar.gz/CRYPTOPP_5_6_5
######################################################################## 100.0%
==> make shared all CXX=clang++
==> ./cryptest.exe v
==> make install PREFIX=/usr/local/Cellar/cryptopp/5.6.5
_  /usr/local/Cellar/cryptopp/5.6.5: 259 files, 23.7M, built in 1 minute 14 seconds
```
```bash
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.12.1
BuildVersion:   16B2555
```
```bash
$ brew --version
Homebrew 1.1.8
Homebrew/homebrew-core (git revision dfdd; last commit 2017-01-27)
```
Note: I don't use brew for cryptopp (we use a git submodule) so I don't think I can be of much more help in terms of brew usage.

**Comment by noloader** [comment]
@smessmer,

Do you need anymore help from us with this issue?

**Comment by noloader** [comment]
@smessmer,

We opened a discussion on the Homebrew discussion list at [Crypto++ Homebrew package broken](https://groups.google.com/forum/#!topic/homebrew-discuss/aDF2gMeLeWA).

**Comment by noloader** [comment]
@smessmer,

There is a discussion on the Homebrew discussion list at [Crypto++ Homebrew package broken](https://groups.google.com/forum/#!topic/homebrew-discuss/aDF2gMeLeWA).

**Comment by tdsmith** [comment]
Hi; I'm a Homebrew maintainer. I can't repro either. Can you share the output of `brew install -vd cryptopp` and `brew gist-logs cryptopp`?

Thanks for the email; opening an issue on the Homebrew/homebrew-core tracker is probably the best way to communicate with the Homebrew project.

**Comment by noloader** [comment]
Thanks @tdsmith.

Off topic, I have a PowerMac G5 running OS X 10.5 available for testing if you need it. We use it for testing Crypto++ on a big-endian processor. If you want access, then send your SSH or authorized_keys to *noloader, gmail account*.

**Comment by tdsmith** [comment]
Thanks but I think we'll pass; supporting just one architecture causes enough trouble to keep us busy. :)

**Comment by noloader** [comment]
We seem to have lost @smessmer interest. I'm going to close this for now.

Thanks for the help @tdsmith. Let me know if I can return the favor.

**Comment by smessmer** [comment]
Sorry, was busy last week. If none of you can reproduce it, the only remaining possible cause is a problem with my xcode build environment. I'll investigate further.

**Comment by smessmer** [comment]
It really seems to have been a broken xcode installation. I re-installed xcode, ran xcode-select, and now it works. Thanks for your help!

**Comment by mialuyao** [comment]
> @smessmer I _cannot_ reproduce this issue.
> 
> ```
> $ brew install cryptopp
> Updating Homebrew...
> ...
> ==> Using the sandbox
> ==> Downloading https://github.com/weidai11/cryptopp/archive/CRYPTOPP_5_6_5.tar.gz
> ==> Downloading from https://codeload.github.com/weidai11/cryptopp/tar.gz/CRYPTOPP_5_6_5
> ######################################################################## 100.0%
> ==> make shared all CXX=clang++
> ==> ./cryptest.exe v
> ==> make install PREFIX=/usr/local/Cellar/cryptopp/5.6.5
> _  /usr/local/Cellar/cryptopp/5.6.5: 259 files, 23.7M, built in 1 minute 14 seconds
> ```
> 
> ```
> $ sw_vers
> ProductName:    Mac OS X
> ProductVersion: 10.12.1
> BuildVersion:   16B2555
> ```
> 
> ```
> $ brew --version
> Homebrew 1.1.8
> Homebrew/homebrew-core (git revision dfdd; last commit 2017-01-27)
> ```
> 
> Note: I don't use brew for cryptopp (we use a git submodule) so I don't think I can be of much more help in terms of brew usage.

I met a problem shows "No available formula with the name "cryptopp". Did you mean cryptol? ". How can I solve it? Thank you!

**Comment by noloader** [comment]
@mialuyao,

> I met a problem shows "No available formula with the name "cryptopp". Did you mean cryptol? ". How can I solve it? Thank you!

You should probably contact the Homebrew folks.

**Comment by mouse07410** [comment]
I'm pretty sure Macports has cryptopp package. We don't deal with package distros, sorry, so I doubt you'll get help here how to craft a Homebrew recipe for cryptopp.

But it's simple enough to build from the source, wifi is rusty I'm doing on all of my platforms.

**Comment by Alvov1** [comment]
Yep. Managed to build the library using cryptopp-cmake package. Works fine

https://github.com/abdes/cryptopp-cmake
