### ISSUE TITLE
loader lock on WinXP

### ISSUE THREAD

**Issue by aj3423** [weidai11/cryptopp#373]
Is windows xp still supported? This very simple dll static linking to libcryptopp cannot be loaded on xp, there's a **loader lock** problem.

    #include <windows.h>

    #define CRYPTOPP_ENABLE_NAMESPACE_WEAK 1
    #include "cryptopp/md5.h"

    CryptoPP::Weak::MD5 _md5;

    BOOL WINAPI DllMain(HINSTANCE hInstance, DWORD reason, PVOID pvReserved) {
	    switch(reason) {
	    case DLL_PROCESS_ATTACH:
		    MessageBox(0, "DllMain", "", 0);
		    break;
	    }
	    return TRUE;
    }

Load this dll with `regsvr32 my_dll.dll` (regsvr32 calls loadlibrary), it will hang **regsvr32** process and the MessageBox in **DllMain** won't be executed. I dumped the process with **windbg**, here's the output:

    BLOCKING_THREAD:  000000e8
    
    DEFAULT_BUCKET_ID:  APPLICATION_HANG_HungIn_LoaderLock
    
    PRIMARY_PROBLEM_CLASS:  APPLICATION_HANG_HungIn_LoaderLock
    
    LAST_CONTROL_TRANSFER:  from 7c92df3c to 7c92e4f4
    
    FAULTING_THREAD:  00000000
    
    STACK_TEXT:  
    0007dde4 7c92df3c 7c9546b0 00000744 00000000 ntdll!KiFastSystemCallRet
    0007dde8 7c9546b0 00000744 00000000 00000000 ntdll!NtWaitForSingleObject+0xc
    0007de14 7c95452b 00000768 00000000 7c946405 ntdll!RtlpInitializeTimerThreadPool+0xe1
    0007de58 7c94d6c9 00000000 0007de8c 7c95327e ntdll!RtlpInitializeWorkerThreadPool+0x1c
    0007de64 7c95327e 00000000 0009f834 00000768 ntdll!RtlpAcquireWorker+0x16
    0007de8c 7c821205 0009f834 00000768 00b52b20 ntdll!RtlRegisterWait+0x93
    0007deb4 00b4b4b8 0009f834 00000768 00b52b20 kernel32!RegisterWaitForSingleObject+0x6f
    0007df24 00b6077e 0007df98 0009f650 0007df64 MSVCR120D!Concurrency::details::SchedulerBase::SchedulerBase+0x388 [f:\dd\vctools\crt\crtw32\concrt\schedulerbase.cpp @ 147]
    0007df34 00b608f7 0007df98 a284c84b 00b3c0e1 MSVCR120D!Concurrency::details::ThreadScheduler::ThreadScheduler+0x1e [f:\dd\vctools\crt\crtw32\concrt\threadscheduler.cpp @ 26]
    0007df64 00b4d33c 0007df98 0007df74 0007df88 MSVCR120D!Concurrency::details::ThreadScheduler::Create+0x67 [f:\dd\vctools\crt\crtw32\concrt\threadscheduler.cpp @ 34]
    0007df7c 00b4e64a 0007df98 a284c887 00aef754 MSVCR120D!Concurrency::details::SchedulerBase::CreateWithoutInitializing+0x1c [f:\dd\vctools\crt\crtw32\concrt\schedulerbase.cpp @ 285]
    0007dfa8 00b4d22b 1011ec30 00000000 0007dfc4 MSVCR120D!Concurrency::details::SchedulerBase::GetDefaultScheduler+0x8a [f:\dd\vctools\crt\crtw32\concrt\schedulerbase.cpp @ 654]
    0007dfb8 00b28045 0007dff8 0007dfec 00b39760 MSVCR120D!Concurrency::details::SchedulerBase::CreateContextFromDefaultScheduler+0xb [f:\dd\vctools\crt\crtw32\concrt\schedulerbase.cpp @ 571]
    0007dfc4 00b39760 0007e02c 00bcfef0 a24183ef MSVCR120D!Concurrency::details::SchedulerBase::CurrentContext+0x15 [f:\dd\vctools\crt\crtw32\concrt\schedulerbase.h @ 399]
    0007dfec 00b3b483 ffffffff 0007e004 00000000 MSVCR120D!Concurrency::details::LockQueueNode::LockQueueNode+0x40 [f:\dd\vctools\crt\crtw32\concrt\rtlocks.cpp @ 619]
    0007e018 00a125e9 0007e074 7c92d7ec 7c9333f6 MSVCR120D!Concurrency::critical_section::lock+0x13 [f:\dd\vctools\crt\crtw32\concrt\rtlocks.cpp @ 1026]
    0007e058 00a1295e 101e3294 00000000 0007e078 MSVCP120D!mtx_do_lock+0x99 [f:\dd\vctools\crt\crtw32\stdcpp\thr\mutex.c @ 67]
    0007e068 10048710 101e3294 0007e194 0007e088 MSVCP120D!_Mtx_lock+0xe [f:\dd\vctools\crt\crtw32\stdcpp\thr\mutex.c @ 153]
    0007e078 10049617 101e3294 101e3294 0007e094 my_dll!std::_Mtx_lockX+0x10 [g:\vs\vc\include\thr\xthread @ 68]
    0007e088 10041a80 0007e0b4 0007e0d0 10046d1b my_dll!std::_Mutex_base::lock+0x17 [g:\vs\vc\include\mutex @ 41]
    0007e094 10046d1b 101e3294 a2851cf1 cccccccc my_dll!std::lock_guard<std::mutex>::lock_guard<std::mutex>+0x20 [g:\vs\vc\include\mutex @ 184]
    0007e0d0 10001eb4 cc00cccc 0007e0e4 00aeebba my_dll!CryptoPP::Singleton<CryptoPP::Integer,CryptoPP::NewObject<CryptoPP::Integer>,0>::Ref+0xcb [g:\cryptopp\misc.h @ 296]
    0007e0dc 00aeebba 0007e128 1011ea13 1018b264 my_dll!CryptoPP::`anonymous namespace'::`dynamic initializer for 's_zero''+0x24 [g:\cryptopp\integer.cpp @ 3031]
    0007e0e4 1011ea13 1018b264 1018b390 0007e0d8 MSVCR120D!_initterm+0x1a [f:\dd\vctools\crt\crtw32\startup\crt0dat.c @ 955]
    0007e128 1011ed0c 10000000 00000001 00000000 my_dll!_CRT_INIT+0xc3 [f:\dd\vctools\crt\crtw32\dllstuff\crtdll.c @ 295]
    0007e16c 1011ec4f 10000000 00000001 00000000 my_dll!__DllMainCRTStartup+0xac [f:\dd\vctools\crt\crtw32\dllstuff\crtdll.c @ 502]
    0007e180 7c92118a 10000000 00000001 00000000 my_dll!_DllMainCRTStartup+0x1f [f:\dd\vctools\crt\crtw32\dllstuff\crtdll.c @ 472]
    0007e1a0 7c93c4da 1011ec30 10000000 00000001 ntdll!LdrpCallInitRoutine+0x14
    0007e2a8 7c936351 00000000 c0150008 00000000 ntdll!LdrpRunInitializeRoutines+0x344
    0007e554 7c9364b3 00000000 000947f8 0007e848 ntdll!LdrpLoadDll+0x3e5
    0007e7fc 7c801bbd 000947f8 0007e848 0007e828 ntdll!LdrLoadDll+0x230
    0007e864 01001dbe 000341a6 00000000 00000008 kernel32!LoadLibraryExW+0x18e
    0007ff1c 010024bf 01000000 00000000 000205ee regsvr32!wWinMain+0x741
    0007ffc0 7c817067 00000018 00000000 7ffda000 regsvr32!wWinMainCRTStartup+0x198
    0007fff0 00000000 01002327 00000000 78746341 kernel32!BaseProcessStart+0x23

Seems these two line causes the problem but I don't see why.    
g:\cryptopp\misc.h @ 296
g:\cryptopp\integer.cpp @ 3031

This dll works fine on **Win10**, but hangs on **WinXP**.
Development environment:  Win10-pro-64bit,  VisualStudio2013-Update5, CryptoPP-5.6.5(**/MDd**)
Testing environment: WinXP-pro-sp3

**Comment by noloader** [comment]
> ```
> BOOL WINAPI DllMain(HINSTANCE hInstance, DWORD reason, PVOID pvReserved) {
>     switch(reason) {
>     case DLL_PROCESS_ATTACH:
> 	    MessageBox(0, "DllMain", "", 0);
> 	    break;
>     }
>     return TRUE;
> }
> ```

I don't believe you are allowed to call `MessageBox` in `DLLmain`. `MessageBox` is from `user32.dll`, and it may not be loaded.

There are a handful of things you can do in the `DLLmain` function. One of them is call functions from `kernel32.dll` as long as it does not load other DLLs. Also see [Dynamic-Link Library Best Practices](https://msdn.microsoft.com/en-us/library/windows/desktop/dn633971(v=vs.85).aspx) on MSDN.

Maybe `OutputDebugString` would be a better choice.

-----

> Seems these two line causes the problem but I don't see why.
> g:\cryptopp\misc.h @ 296
> g:\cryptopp\integer.cpp @ 3031

This looks like Microsoft's bugs. It seems Microsoft claims to be C++11, but they did not bother implementing some features on platforms they now consider deprecated by fiat (even before they were deprecated).

1. [runtime crash with static std::mutex](https://connect.microsoft.com/VisualStudio/feedback/details/808030/runtime-crash-with-static-std-mutex).
2. [Visual C++ 2015 runtime broken on Windows Server 2003 (C++11 magic statics)](https://connect.microsoft.com/VisualStudio/feedback/details/1789709/visual-c-2015-runtime-broken-on-windows-server-2003-c-11-magic-statics)

We are currently tracking it at [Issue 372: CryptoPP::Singleton::Ref() crashes on MSVC11/12](https://github.com/weidai11/cryptopp/issues/372). The 372 issue is tricky because we can't do something like `#if _MSC_VER <= 1300` or `_WIN32_WINNT < 0x600`. The compile time platform may be different than the runtime platform. Its all-or-nothing when we make the decision.

And based on feedback from folks like @MarcelRaad and @aj3423, there are a non-trivial number of folks supporting it for their users.

------

> Is windows xp still supported?

I'm happy to support it in Crypto++. I believe projects like Crypto++ and OpenSSL should provide rich platform support because companies like Apple, Microsoft and Oracle practice the abondon-ware model of software development. That is, users need us to provide them with up-to-date software because the OEMs do not.  The OEMs supply defective software and then walk away.

In this case, the problem seems to be Microsoft.

**Comment by denisbider** [comment]
>  The OEMs supply defective software and then walk away.

I don't think this is a reasonable judgment to make, for the simple reason that the Crypto++ project does not support Crypto++ 4.x versions either. The 4.x versions are similar in age as Windows XP and Windows Server 2003. If someone experienced a problem with those versions, and wanted support, I expect they would be told something like: "Get the f out of here, please upgrade to a recent version."

Microsoft only expects the same thing. In fact, they support versions of Windows back to Windows Vista, which was released over 10 years ago, in November 2006. At about the same time, Crypto++ 5.4 was released.

What would this project say if someone came forth with a bug in Crypto++ 5.4, which was released December 2006? Would the bug be patched for them? Or would you point them to the latest Crypto++ release?

**Comment by aj3423** [comment]
It seems to be WinXP's bug, but unfortunately I have to support it. I replaced the Singleton implementation with the old version 5.6.3's, not thread safe but it's not a problem for my project.
Thanks.

**Comment by noloader** [comment]
@denisbider,

Its kind of apple and oranges. Microsoft OSes are closed source, while projects like Crypto++ and OpenSSL are open source.

In the case of Microsoft OSes, the company holds the copyright, and it has the rights for nearly a century. Microsoft won't release the source code into the public domain so we can fix it, so they retain the responsibility, too.

Bits don't wear out like a car part. It was defective when it was released; and it did not rot over time.  Microsoft earned hundreds of millions of dollars on selling the defective software. In this case, responsibility lies with Microsoft to fix their defective software. They should have put some of the money away to cover future costs related to the defects.

Microsoft does not decide when the OS is obsolete. Rather, the market does. Their fiat means nothing to me. I did not agree to it when I bought the OSes, and I do not agree to it now. I do not agree to any changes to the terms of my purchase and use after the fact.

I'd be happy to branch former Crypto++ release and backport fixes. I actually asked WD about setting up the project that way so we could do it to help individuals and distros. It was decided it was not a good idea.

**Comment by denisbider** [comment]
I don't think it's fair to say that Windows XP/2003 was "defective when it was released" in a way that matters to this issue. The issue has more moving parts than that. Windows XP/2003 had partial support for a feature which was new at that time, and is supported more fully in later Windows versions. Visual Studio 2015 happens to make the design choice where it requires full support of this feature in order to provide magic statics.

You are talking about "defects", but really, your point is that Microsoft ought to be supporting Windows XP/2003 indefinitely. Well, they do. It's called Windows 10/2016.

**Comment by noloader** [comment]
I believe we cleared this issue at [Commit 46c9cc725cf325f2](https://github.com/weidai11/cryptopp/commit/46c9cc725cf325f2990056526a00848a11d37fa8).

The commit added `CRYPTOPP_CXX11_DYNAMIC_INIT` to pickup [Dynamic Initialization and Destruction with Concurrency]() conformance. We use the C++11 version if `CRYPTOPP_CXX11_ATOMICS`, `CRYPTOPP_CXX11_SYNCHRONIZATION` and `CRYPTOPP_CXX11_DYNAMIC_INIT` are defined. Microsoft platforms have an additional restriction of Windows Vista or above.

**Comment by noloader** [comment]
I believe we cleared this issue at [Commit 46c9cc725cf325f2](http://github.com/weidai11/cryptopp/commit/46c9cc725cf325f2990056526a00848a11d37fa8).

The commit added `CRYPTOPP_CXX11_DYNAMIC_INIT` to pickup [Dynamic Initialization and Destruction with Concurrency]() conformance. We use the C++11 version if `CRYPTOPP_CXX11_ATOMICS`, `CRYPTOPP_CXX11_SYNCHRONIZATION` and `CRYPTOPP_CXX11_DYNAMIC_INIT` are defined. Microsoft platforms have an additional restriction of Windows Vista or above.

Here are the related bug reports for the commit:

* [Issue 372, Singleton::Ref() crashes on MSVC11/12](http://github.com/weidai11/cryptopp/issues/372)
* [Issue 373, Loader lock on WinXP](http://github.com/weidai11/cryptopp/issues/373)
* [Issue 389, Race condition in InitializeInteger::InitializeInteger](http://github.com/weidai11/cryptopp/issues)
* [Issue 391, Crash in NonblockingRng::GenerateBlock](http://github.com/weidai11/cryptopp/issues/391)

**Comment by noloader** [comment]
I believe we cleared this issue at [Commit 46c9cc725cf325f2](http://github.com/weidai11/cryptopp/commit/46c9cc725cf325f2990056526a00848a11d37fa8).

The commit added `CRYPTOPP_CXX11_DYNAMIC_INIT` to pickup [Dynamic Initialization and Destruction with Concurrency]() conformance. We use the C++11 version if `CRYPTOPP_CXX11_ATOMICS`, `CRYPTOPP_CXX11_SYNCHRONIZATION` and `CRYPTOPP_CXX11_DYNAMIC_INIT` are defined. Microsoft platforms have an additional restriction of Windows Vista or above.

Here are the related bug reports for the commit:

* [Issue 372, Singleton::Ref() crashes on MSVC11/12](http://github.com/weidai11/cryptopp/issues/372)
* [Issue 373, Loader lock on WinXP](http://github.com/weidai11/cryptopp/issues/373)
* [Issue 389, Race condition in InitializeInteger::InitializeInteger](http://github.com/weidai11/cryptopp/issues)
* [Issue 391, Crash in NonblockingRng::GenerateBlock](http://github.com/weidai11/cryptopp/issues/391)
