### ISSUE TITLE
OS_NO_DEPENDENCE in osrng.h, NO_OS_DEPENDENCE everywhere else

### ISSUE THREAD

**Issue by mattiaslinnap** [weidai11/cryptopp#377]
osrng.h checks for a preprocessor define named OS_NO_DEPENDENCE:
```
#if !defined(OS_NO_DEPENDENCE) && defined(OS_RNG_AVAILABLE)
```

But config.h optionally defines NO_OS_DEPENDENCE, and all other files use this variant:
```
// Define this if you want to disable all OS-dependent features,
// such as sockets and OS-provided random number generators
// #define NO_OS_DEPENDENCE
```

This name difference seems like a typo in osrng.h.

**Comment by noloader** [comment]
c22f3228fb5c25d2Yeah, that looks like a typo. Cleared at [Commit ](https://github.com/weidai11/cryptopp/commit/c22f3228fb5c25d23d5eeb811202b76f3cca2468)
