### ISSUE TITLE
ECDSA examples not working

### ISSUE THREAD

**Issue by targetnull** [weidai11/cryptopp#381]
I'm trying to use ecdsa to sign and verify messages, but the [example at your official site](https://www.cryptopp.com/wiki/User_Guide:_eccrypto.h) is not working. The `ECPrivateKey ` and `ECPublicKey ` are not declared and nowhere to be found, there is no type named ECPrivateKey in the latest 5.6.5 source.

I tried to replace them with `DL_PublicKey_EC` but it is a template, which requires a class type inside. Does anyone know how to make it work? Thanks.

P.S. I'm using ubuntu 16.04, building from source. I'm sure I have it installed correctly because the [RSA example](https://www.cryptopp.com/wiki/User_Guide:_rsa.h) can run successfully.

**Comment by targetnull** [comment]
and one more minor question, how am I supposed to get the public key in byte array format? I need to put it into a uint8_t array so that it could be transferred on the internet.

**Comment by noloader** [comment]
> I'm trying to use ecdsa to sign and verify messages, but the example at your official site is not working. The ECPrivateKey and ECPublicKey are not declared and nowhere to be found, there is no type named ECPrivateKey in the latest 5.6.5 source...

[User Guide: eccrypto.h](https://www.cryptopp.com/wiki/User_Guide:_eccrypto.h) is a somewhat dated document. Its part of Denis Bider's guide to Crypto++ for the library from the 3.0 and 4.0 days. It was a great document back in the day. Back then, I think it was the only documentation for the library. I'm not sure how much applies (or does not apply) today.

Nowadays, you might try [Elliptic Curve Cryptography](https://www.cryptopp.com/wiki/Elliptic_Curve_Cryptography). Its kind of the landing page for the elliptic curve gear, and links to specific implementations, like Elliptic Curve Diffie-Hellman Key Agreement (ECDH), Elliptic Curve Integrated Encryption Scheme (ECIES) and Elliptic Curve Digital Signature Algorithm (ECDSA). The page also has some notes that apply to elliptic curves in general.

I think [Elliptic Curve Digital Signature Algorithm](https://www.cryptopp.com/wiki/Elliptic_Curve_Digital_Signature_Algorithm) wiki (from the landing page) page will be more helpful to you.

-----

> and one more minor question, how am I supposed to get the public key in byte array format?

See [Keys and Formats](https://www.cryptopp.com/wiki/Keys_and_Formats) on the Crypto++ wiki. You will need to know the presentation format that meets your needs. When in doubt, just use `Load` and `Save`.

**Comment by targetnull** [comment]
Hi, @noloader your suggestion works and I can convert both keys to byte arrays, but I still can't load a string(or byte array) to a PublicKey, more specifically, a `ECDSA<ECP, SHA1>::PublicKey`. It cast an error saying **BER decode error**. However, the document of DER Encode only has examples that saves the public key into a file, rather than a string. It didn't work when I tried to pass a `StringSink/StringSource` to `publicKey.DEREncode` method. Is there any way to load PublicKey from string rather than a file? Thanks
