### ISSUE TITLE
[BUG] VC 2005 x64: _aligned_free failed

### ISSUE THREAD

**Issue by asbai** [weidai11/cryptopp#384]
If we do something like this:
`new RSAES< OAEP<CryptoPP::SHA1> >::Decryptor(*thRng, nKeyLen);`

_aligned_free will be failed on the x64 target compiled by VC 2005:
```
Integer Integer::Plus(const Integer& b) const
{
	Integer sum((word)0, STDMAX2(reg.size(), b.reg.size()));
	// ...
	return sum; // <--- here
}
```

because, `if (T_Align16 && size*sizeof(T) >= 16)` is false so `UnalignedAllocate` is used in sum's constructor, but under the destructor,  `if (T_Align16 && size*sizeof(T) >= 16)` is ture, so `AlignedDeallocate` launched.

If I change line 
`typedef SecBlock<word, AllocatorWithCleanup<word, CRYPTOPP_BOOL_X86> > IntegerSecBlock;` 
to 
`typedef SecBlock<word, AllocatorWithCleanup<word, true> > IntegerSecBlock;`
then every thing is fine.

Could I use this as a temporarily workaround fix ?

This bug only occur in MSW VC2005 x64. It's fine under MSW VC2005 x86 or Linux GCC x64/x86.

**Comment by noloader** [comment]
> Could I use this as a temporarily workaround fix ?

Yes, its already in [Master](https://github.com/weidai11/cryptopp/blob/master/integer.h#L30):

```
// Always align, http://github.com/weidai11/cryptopp/issues/256
typedef SecBlock<word, AllocatorWithCleanup<word, true> > IntegerSecBlock;
```
