### ISSUE TITLE
Build Broken

### ISSUE THREAD

**Issue by VSRonin** [weidai11/cryptopp#388]
Windows 7, MSVC 2013
```
rdrand.cpp(289) : error C2664: 'int _rdseed32_step(unsigned int *)' : cannot convert argument 1 from 'unsigned __int64 *' to 'unsigned int *'
        Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
```

the line is:
```c++
while(!_rdseed32_step(reinterpret_cast<unsigned long long*>(output))) {}
```

use `_rdseed64_step` or `reinterpret_cast<unsigned long*>` instead?

**Comment by noloader** [comment]
Thanks @VSRonin. 

My bad, I dropped the ball. I was testing under Visual Studio 2012, not 2013. Sorry about that.

> `while(!_rdseed32_step(reinterpret_cast<unsigned long long*>(output))) {}`

Use `word32*`.

So you feel like a making a pull request? Or do you want me to check it in?

**Comment by noloader** [comment]
Thanks again @VSRonin,

Cleared at [Commit 19df272d906b60b1](https://github.com/weidai11/cryptopp/commit/19df272d906b60b140505930e826a5144bceaabf).

**Comment by noloader** [comment]
Thanks again @VSRonin,

Cleared at [Commit 19df272d906b60b1](https://github.com/weidai11/cryptopp/commit/19df272d906b60b140505930e826a5144bceaabf).

**Comment by VSRonin** [comment]
Thanks to you for the quick fix
