### ISSUE TITLE
MAC Benchmark

### ISSUE THREAD

**Issue by hajji7777** [weidai11/cryptopp#396]
Hi,
I did the global benchmark: “cryptest.exe b 3 2.0 > benchmark.html”.
I want to know how to do a benchmark of the all MAC(message authentication code) algorithms: HMAC, CMAC, GMAC, VMAC, … , and its variants (HMAC: HMAC-SHA-1, HMAC-SHA-224, HMAC-SHA-256, HMAC-SHA-384 and HMAC-SHA-512).
I added some lines, in bench1.cpp file, to have all the MAC statistics, but the Benchmark stopped with an exception message (“CryptoPP::Exception caught: ObjectFactoryRegistry: could not find factory for algorithm HMAC(SHA265)”).
I want to do a performance comparison to choose the right MAC algorithm for my Ad Hoc network(OLSR protocol).
Thanks in advance.

**Comment by noloader** [comment]
Please ask questions on the  [Crypto++ user list](https://groups.google.com/forum/#!forum/cryptopp-users).

**Comment by hajji7777** [comment]
Ok Jeff.
Thank you a lot for your support.

2017-03-25 0:13 GMT+00:00 Jeffrey Walton <notifications@github.com>:
