### ISSUE TITLE
linux Assembler error: no such instruction

### ISSUE THREAD

**Issue by owen200008** [weidai11/cryptopp#400]
version 5.6.5
gcc 4.9.4
#395 solve this problem？
I must disable DISABLE_NATIVE_ARCH to make success

-----

1.cmake -DDISABLE_NATIVE_ARCH=TRUE
2.make -f Makefile

**Comment by owen200008** [comment]
1.cmake -DDISABLE_NATIVE_ARCH=TRUE
2.make -f Makefile

**Comment by noloader** [comment]
Please run the GNU makefile to see if the problem is with the library or Cmake:

```
make -f GNUMakefile
```

If its not a problem with the library, then its an issue with Cmake. You can try the latest `CMakefileList.txt` by:

```
cd cryptopp
wget https://raw.githubusercontent.com/weidai11/cryptopp/master/CMakeLists.txt -O CMakeLists.txt
```

If its still a problem with the latest `CMakeLists.txt`, then please provide:

1. The platform
2. The version of GCC
3. The version of GAS
4. The version of Cmake
5. The full output of make'ing

**Comment by owen200008** [comment]
make -f GNUMakefile have the error 
{standard input}: Assembler messages:
{standard input}:1800: Error: no such instruction: `shrx %ecx,%ebx,%edx'
{standard input}:1825: Error: no such instruction: `shlx %r12d,%r13d,%r13d'

**Comment by owen200008** [comment]
wget the https://raw.githubusercontent.com/weidai11/cryptopp/master/CMakeLists.txt
rm -rf CMakeCache*
cmake .
make -f Makefile have the error
[  0%] Building CXX object CMakeFiles/cryptopp-object.dir/cryptlib.cpp.o
In file included from /root/github/cryptopp/cryptlib.cpp:19:
/root/github/cryptopp/misc.h: In function ‘unsigned int CryptoPP::TrailingZeros(CryptoPP::word32)’:
/root/github/cryptopp/misc.h:732: error: ‘_tzcnt_u32’ was not declared in this scope
/root/github/cryptopp/misc.h: In function ‘unsigned int CryptoPP::TrailingZeros(CryptoPP::word64)’:
/root/github/cryptopp/misc.h:763: error: ‘_tzcnt_u64’ was not declared in this scope
/root/github/cryptopp/misc.h: In function ‘bool CryptoPP::IsPowerOf2(const T&) [with T = unsigned int]’:
/root/github/cryptopp/misc.h:874: error: ‘_blsr_u32’ was not declared in this scope
/root/github/cryptopp/misc.h: In function ‘bool CryptoPP::IsPowerOf2(const T&) [with T = long unsigned int]’:
/root/github/cryptopp/misc.h:881: error: ‘_blsr_u64’ was not declared in this scope
make[2]: *** [CMakeFiles/cryptopp-object.dir/cryptlib.cpp.o] Error 1
make[1]: *** [CMakeFiles/cryptopp-object.dir/all] Error 2
make: *** [all] Error 2

**Comment by noloader** [comment]
Please provide the following:

1. The platform
2. The version of GCC
3. The version of GAS
4. The version of Cmake
5. The full output of make'ing

Providing just an error message or CMake with its hidden output is not useful (to me).

**Comment by noloader** [comment]
Last call for CMake patches before removing it from the library and adding it to the patch page. If you have something to add, then now is the time to do it.

Also see [Remove CMake from GitHub; add it to Patch Page on wiki?](https://groups.google.com/forum/#!topic/cryptopp-users/PKlz8-ClXOU) and [Commit 1c740b0a097aecaa](https://github.com/weidai11/cryptopp/commit/1c740b0a097aecaa66044036c0d2c54220eda5d5).
