### ISSUE TITLE
[Debug ok, Release no] Help with electron native module

### ISSUE THREAD

**Issue by pkoutsovasilis** [weidai11/cryptopp#401]
Hello and really KUDOS 👍  for this nice library

I try to include cryptopp in my native electron (node js) module and i observed something weird. When i use the debug version of the library the following code works but when i build against the release version i get an "Electron has stopped working error". I attach the vcxproj of the module and my code. I really cant tell what is the matter and i would really like your help. If your require more info, i would gladly provide them :)

Addon vcxproj, vcxproj.filters, binding.sln
[build.zip](https://github.com/weidai11/cryptopp/files/945148/build.zip)

Command to issue the compilation of cryptlib.lib
"C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" cryptlib.vcxproj /p:configuration="Release" /p:platform="Win32"

Partial Code (Ommited for bravety, i can upload the whole addon.cpp file if you need it)
[code.zip](https://github.com/weidai11/cryptopp/files/945173/code.zip)

Regards

**Comment by noloader** [comment]
Please ask questions on the [Crypto++ user list](https://groups.google.com/forum/#!forum/cryptopp-users).
