### ISSUE TITLE
Solaris 10 and SIGBUS crashes in cryptest.exe

### ISSUE THREAD

**Issue by noloader** [weidai11/cryptopp#403]
See [Coredump in cryptest.exe on Solaris 10](https://groups.google.com/d/msg/cryptopp-users/OYaByDEbSI0/624NTaBmBQAJ) on the mailing list and [Pull Request 402](https://github.com/weidai11/cryptopp/pull/402). Multiple self tests fail when `data` is read as a `word64`. Alignment appears to be OK.

The unusual thing is, `memcpy`-out the `data` parameter to a `word64` clears some of the issues. But the debugger shows the `data` parameter is aligned (from the core dump):

```
Testing MessageDigest algorithm SHA-384.
..signal BUS (invalid address alignment) in CryptoPP::SHA512::Transform at line 1762 in file "sha.cpp"
 1762           R( 0); R( 1); R( 2); R( 3);^M
(dbx) where
=>[1] CryptoPP::SHA512::Transform(state = 0x101167a08, data = 0xffffffff7fffa68c), line 1762 in "sha.cpp"
  [2] CryptoPP::SHA384::Transform(digest = 0x101167a08, data = 0xffffffff7fffa68c), line 85 in "sha.h"
  [3] CryptoPP::IteratedHashWithStaticTransform<unsigned long,CryptoPP::EnumToType<CryptoPP::ByteOrder,1>,128U,64U,CryptoPP::SHA384,48U,0>::HashEndianCorrectedBlock(this = 0x101167950, data = 0xffffffff7fffa68c), line 165 in "iterhash.h"
  [4] CryptoPP::IteratedHashBase<unsigned long,CryptoPP::HashTransformation>::HashMultipleBlocks(this = 0x101167950, input = 0xffffffff7fffa68c, length = 2852U), line 94 in "iterhash.cpp"
...
```

**Comment by noloader** [comment]
Merged PR.

**Comment by kvirund** [comment]
> But the debugger shows the data parameter is aligned (from the core dump)

`data` is aligned to 4, but not aligned to 8 bytes:

```
>>> print(0xffffffff7fffa68c % 8)
4
>>> print(0xffffffff7fffa68c % 4)
0
>>> 
```

**Comment by noloader** [comment]
Arg... I'm not sure why I made the leap that an address that ends in 0xc is aligned for a 64-bit type on SPARC.

The [Solaris 64-bit Developer’s Guide](https://docs.oracle.com/cd/E19455-01/806-0477/806-0477.pdf) does state (p. 54):

* ABI Features: SPARC V9
   * ...
   * All data types are now aligned to their size

Maybe `-xmemalign=4i` will clear the issue for you.

**Comment by noloader** [comment]
@kvirund,

> Maybe `-xmemalign=4i` will clear the issue for you.

I can't test the option on my Intel machine:

```
$ CXX=/opt/developerstudio12.5/bin/CC gmake CXXFLAGS="-DDEBUG -g3 -O0 -D__SSE2__ -D__SSE3__ -D__SSSE3__ -xarch=ssse3 -m64 -native -KPIC -template=no%extdef -xmemalign=4i"
/opt/developerstudio12.5/bin/CC -DDEBUG -g3 -O0 -D__SSE2__ -D__SSE3__ -D__SSSE3__ -xarch=ssse3 -m64 -native -KPIC -template=no%extdef -xmemalign=4i -c cryptlib.cpp
CC: Warning: Option xmemalign=4i is not available on x86/x64 Solaris platform, ignored
```

Can you provide remote access to the machine you are having trouble on?

**Comment by noloader** [comment]
@kvirund,

Can you test [commit [cd65ce873a1d8b74](https://github.com/weidai11/cryptopp/commit/cd65ce873a1d8b74) and port it to `CMakefileList.txt`:

```
$ git diff  12b5074..cd65ce8
diff --git a/GNUmakefile b/GNUmakefile
index db1713f..dc987bc 100755
--- a/GNUmakefile
+++ b/GNUmakefile
@@ -21,6 +21,8 @@ IS_X64 := $(shell uname -m | $(EGREP) -i -c "(_64|d64)")
 IS_PPC := $(shell uname -m | $(EGREP) -i -c "ppc|power")
 IS_ARM32 := $(shell uname -m | $(EGREP) -i -c "arm")
 IS_ARM64 := $(shell uname -m | $(EGREP) -i -c "aarch64")
+IS_SPARC := $(shell uname -m | $(EGREP) -i -c "sparc")
+IS_SPARC64 := $(shell uname -m | $(EGREP) -i -c "sparc64")

 IS_SUN := $(shell uname | $(EGREP) -i -c "SunOS")
 IS_LINUX := $(shell $(CXX) -dumpmachine 2>&1 | $(EGREP) -i -c "Linux")
@@ -346,6 +348,10 @@ CXXFLAGS += -KPIC
 endif
 # Add to all Solaris
 CXXFLAGS += -template=no%extdef
+# http://github.com/weidai11/cryptopp/issues/403
+ifneq ($(IS_SPARC)$(IS_SPARC64),00)
+CXXFLAGS += -xmemalign=4i
+endif
 SUN_CC10_BUGGY := $(shell $(CXX) -V 2>&1 | $(EGREP) -c "CC: Sun .* 5\.10 .* (2009|2010/0[1-4])")
 ifneq ($(SUN_CC10_BUGGY),0)
 # -DCRYPTOPP_INCLUDE_VECTOR_CC is needed for Sun Studio 12u1 Sun C++ 5.10 SunOS_i386 128229-02 2009/09/21 and was fixed in May 2010
```

**Comment by noloader** [comment]
@kvirund,

We recently received access to the [OpenCSW compile farm](https://www.opencsw.org/extend-it/signup/to-upstream-maintainers/). The farm provides access to Solaris 9 through 11 on x86 and Sparc hardware.

I believe all the unaligned memory issues are cleared. Also see [Issue 691, GetAlignmentOf returns 4 on Sparc when T=word64](https://github.com/weidai11/cryptopp/issues/691), which is the wrap-up bug report we used to nail it.

**Comment by kvirund** [comment]
Thank you very much!
