### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by SolarAquarion** [weidai11/cryptopp#407]
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c cryptlib.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c cpu.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c integer.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c seal.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c gzip.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c fips140.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c twofish.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c eprecomp.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c dsa.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c dh.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c filters.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c vmac.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c hrtimer.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c blake2.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c fipstest.cpp
In file included from fipstest.cpp:9:
In file included from ./dll.h:37:
./pkcspad.h:86:53: warning: instantiation of variable
      'CryptoPP::PKCS_DigestDecoration<CryptoPP::SHA1>::decoration' required here, but
      no definition is available [-Wundefined-var-template]
  ...return HashIdentifier(PKCS_DigestDecoration<H>::decoration, PKCS_DigestDecorati...
                                                     ^
./pubkey.h:596:19: note: in instantiation of member function
      'CryptoPP::PKCS1v15_SignatureMessageEncodingMethod::HashIdentifierLookup::HashIdentifierLookup2<CryptoPP::SHA1>::Lookup'
      requested here
        return L::Lookup();
                  ^
./pubkey.h:1989:26: note: in instantiation of member function
      'CryptoPP::TF_ObjectImplBase<CryptoPP::TF_SignerBase,
      CryptoPP::TF_SignatureSchemeOptions<CryptoPP::TF_SS<CryptoPP::RSA,
      CryptoPP::PKCS1v15, CryptoPP::SHA1, int>, CryptoPP::RSA,
      CryptoPP::PKCS1v15_SignatureMessageEncodingMethod, CryptoPP::SHA1>,
      CryptoPP::InvertibleRSAFunction>::GetHashIdentifier' requested here
class CRYPTOPP_NO_VTABLE PK_FinalTemplate : public BASE
                         ^
fipstest.cpp:577:3: note: in instantiation of function template specialization
      'CryptoPP::SignatureKnownAnswerTest<CryptoPP::RSASS<CryptoPP::PKCS1v15,
      CryptoPP::SHA1> >' requested here
                SignatureKnownAnswerTest<RSASS<PKCS1v15, SHA1> >(
                ^
./pkcspad.h:37:20: note: forward declaration of template entity is here
        static const byte decoration[];
                          ^
1 warning generated.
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c rc5.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c mars.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c md4.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c osrng.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c queue.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c xtrcrypt.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c gf256.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c cmac.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c authenc.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c des.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c idea.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c gcm.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c squaretb.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c xtr.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c emsa2.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c sha.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c network.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c eax.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c tea.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c gf2_32.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c tigertab.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c square.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c dessp.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c algparam.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c elgamal.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c mqueue.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c zlib.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c dh2.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c strciphr.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c iterhash.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c ecp.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c marss.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c adler32.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c wait.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c safer.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c base32.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c wake.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c gf2n.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c default.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c rc2.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c chacha.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c oaep.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c ida.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c shark.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c md5.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c shacal2.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c base64.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c arc4.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c misc.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c ripemd.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c camellia.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c pubkey.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c zdeflate.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c trdlocal.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c salsa.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c luc.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c ttmac.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c crc.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c mqv.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c bfinit.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c whrlpool.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c asn.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c rw.cpp
rw.cpp:17:19: warning: unused variable 'CRYPTOPP_RW_USE_OMP' [-Wunused-const-variable]
static const bool CRYPTOPP_RW_USE_OMP = false;
                  ^
1 warning generated.
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c cast.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c tiger.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c rng.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c zinflate.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c pssr.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c algebra.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c rdrand.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c pkcspad.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c rc6.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c channels.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c basecode.cpp
In file included from basecode.cpp:16:
./basecode.h:103:6: warning: private field 'm_padding' is not used
      [-Wunused-private-field]
        int m_padding, m_bitsPerChar, m_outputBlockSize;
            ^
1 warning generated.
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c blumshub.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c polynomi.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c ec2n.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c dll.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c poly1305.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c md2.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c gfpcrypt.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c esign.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c gost.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c casts.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c modes.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c sha3.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c panama.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c nbtheory.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c socketft.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c ccm.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c eccrypto.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c cbcmac.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c rdtables.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c rsa.cpp
In file included from rsa.cpp:4:
In file included from ./rsa.h:14:
./pkcspad.h:86:53: warning: instantiation of variable
      'CryptoPP::PKCS_DigestDecoration<CryptoPP::SHA1>::decoration' required here, but
      no definition is available [-Wundefined-var-template]
  ...return HashIdentifier(PKCS_DigestDecoration<H>::decoration, PKCS_DigestDecorati...
                                                     ^
./pubkey.h:596:19: note: in instantiation of member function
      'CryptoPP::PKCS1v15_SignatureMessageEncodingMethod::HashIdentifierLookup::HashIdentifierLookup2<CryptoPP::SHA1>::Lookup'
      requested here
        return L::Lookup();
                  ^
./pubkey.h:1989:26: note: in instantiation of member function
      'CryptoPP::TF_ObjectImplBase<CryptoPP::TF_SignerBase,
      CryptoPP::TF_SignatureSchemeOptions<CryptoPP::TF_SS<CryptoPP::RSA,
      CryptoPP::PKCS1v15, CryptoPP::SHA1, int>, CryptoPP::RSA,
      CryptoPP::PKCS1v15_SignatureMessageEncodingMethod, CryptoPP::SHA1>,
      CryptoPP::InvertibleRSAFunction>::GetHashIdentifier' requested here
class CRYPTOPP_NO_VTABLE PK_FinalTemplate : public BASE
                         ^
./pkcspad.h:37:20: note: forward declaration of template entity is here
        static const byte decoration[];
                          ^
1 warning generated.
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c tftables.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c sosemanuk.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c 3way.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c rabin.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c keccak.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c serpent.cpp
clang++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -fPIC -Wall -c aria.cpp
aria.cpp:288:21: error: always_inline function '_mm_shuffle_epi8' requires target
      feature 'ssse3', but would be inlined into function 'UncheckedSetKey' that is
      compiled without support for 'ssse3'
                const __m128i w = _mm_shuffle_epi8(_mm_loadu_si128((const __m12...
                                  ^
aria.cpp:298:5: error: always_inline function '_mm_shuffle_epi8' requires target
      feature 'ssse3', but would be inlined into function 'UncheckedSetKey' that is
      compiled without support for 'ssse3'
                                _mm_shuffle_epi8(_mm_loadu_si128((const __m128i...
                                ^
aria.cpp:566:5: error: always_inline function '_mm_shuffle_epi8' requires target
      feature 'ssse3', but would be inlined into function 'ProcessAndXorBlock' that is
      compiled without support for 'ssse3'
                                _mm_shuffle_epi8(_mm_load_si128((const __m128i*...
                                ^
3 errors generated.
make: *** [GNUmakefile-cross:266: aria.o] Error 1

**Comment by noloader** [comment]
That's kind of interesting. I could not get Clang to accept the arch switch:

```
clang++ -march=x86-64 ...
```

What version of Clang, and what OS?

**Comment by SolarAquarion** [comment]
Clang-svn and ArchLinux

**Comment by noloader** [comment]
Thanks @SolarAquarion,

Fixed at [Commit 554b7a2747178c4](https://github.com/weidai11/cryptopp/commit/554b7a2747178c4).

Sorry about not catching it sooner. I've got my Crypto++ clone integrating with Travis, but its not working at the moment. The job starts but never runs. Eventually it just times out.
