### ISSUE TITLE
Salsa20 sample from wiki does not decrypt original plaintext message

### ISSUE THREAD

**Issue by beauhefley** [weidai11/cryptopp#409]
I have tried to implement Salsa20 in some code to learn more about cryptography. But, my code didn't end up outputting original plaintext. After many failed changes, I tried copy and pasting the whole sample code and compiling it (and of course, changed the includes). I got the same problem. I originally used the crypto++ from my package manager (apt on ubuntu 17.04), and tried many times cloning the library from github and compiling it from source, but no luck. Can anyone try compiling this sample please?

My build commands (using ubuntu's crypto++):
`g++ code.cpp -lcrypto++`

My build commands (using the one I built):
`g++ code.cpp libcryptopp.a` (I tried again pasting the code into the top of the repository, didn't touch includes here)

All the times I tried, I got something like:
`Plaintext: My Plaintext!! My Dear plaintext!!
Ciphertext: �ߡ[�j�V�S0j=���
                             ��������z^M
Plaintext Again: 1�ߡ[�j�V�S0j=���
                                   

SALSA!

     ...20...`

And here in base64, if that helps:
`UGxhaW50ZXh0OiBNeSBQbGFpbnRleHQhISBNeSBEZWFyIHBsYWludGV4dCEhCkNpcGhlcnRleHQ6IDfQTw3P/Z2fqWW3jn7WRXe85+36Z1YxgyMXmPWKz93wpDMKUGxhaW50ZXh0IEFnYWluOiAAAAAAAAAxAAAAAAAAADfQTw3P/Z2fqWW3jn7WRXe85+36CgoKU0FMU0EhCgogICAgIC4uLjIwLi4uCg==`

Sample from here [https://www.cryptopp.com/wiki/Salsa20](url)

**Comment by davidbsp** [comment]
I have the same issue.

**Comment by noloader** [comment]
@beauhefley, @davidbsp,

The example was not good. I replaced it with some new example code. I also showed you how to resynchronize an encryptor so you can use the encryptor  for both encryption and decryption.

I'll get to the Sosemanuk example shortly. But its just going to be a copy/paste of ChaCha20. That's the good thing about the library. All stream ciphers use the same `SymmetricCipher` interface, so copy/paste works all day long.
