### ISSUE TITLE
Just built the library, but a few questions...

### ISSUE THREAD

**Issue by SoftCircuits** [weidai11/cryptopp#413]
I just downloaded and built the library. Two questions:

1. It appears to be a fantastic library with tons of functionality, but the release version is nearly 30MB. Have project files been made available for limited functionality. Or perhaps a guide on figuring out which files I'd need? (I'm looking for a good hash--probably HD5--and encryption/decryption--probably AES.)

2. I'm getting some warnings under Visual Studio 2017. Are these known issues?

>d:\users\jonathan\desktop\cryptopp\wait.h(159): warning C4589: Constructor of abstract class 'CryptoPP::WaitObjectsTracer' ignores initializer for virtual base class 'CryptoPP::Tracer'  
>d:\users\jonathan\desktop\cryptopp\wait.h(159): note: virtual base classes are only initialized by the most-derived type  
>d:\users\jonathan\desktop\cryptopp\wait.h(159): warning C4589: Constructor of abstract class 'CryptoPP::WaitObjectsTracer' ignores initializer for virtual base class 'CryptoPP::Tracer'  
>d:\users\jonathan\desktop\cryptopp\wait.h(159): note: virtual base classes are only initialized by the most-derived type  
>d:\users\jonathan\desktop\cryptopp\wait.h(159): warning C4589: Constructor of abstract class 'CryptoPP::WaitObjectsTracer' ignores initializer for virtual base class 'CryptoPP::Tracer'  
>d:\users\jonathan\desktop\cryptopp\wait.h(159): note: virtual base classes are only initialized by the most-derived type  
>d:\users\jonathan\desktop\cryptopp\wait.h(159): warning C4589: Constructor of abstract class 'CryptoPP::WaitObjectsTracer' ignores initializer for virtual base class 'CryptoPP::Tracer'  
>d:\users\jonathan\desktop\cryptopp\wait.h(159): note: virtual base classes are only initialized by the most-derived type

**Comment by noloader** [comment]
> ... the release version is nearly 30MB. Have project files been made available for limited functionality. 

No. The linker should discard unused symbols from the library.

> I'm getting some warnings under Visual Studio 2017. Are these known issues?

This is a Microsoft bug. Also see [Crypto++ Issue 214](http://github.com/weidai11/cryptopp/issues/214) and [Microsoft Connect Issue 1581706](http://connect.microsoft.com/VisualStudio/feedback/details/1581706).

-----

In the future, please have discussions on the [mailing list](https://groups.google.com/forum/#!forum/cryptopp-users).

**Comment by SoftCircuits** [comment]
Strange. I'm using Visual Studio 2017 and the issue persists.
