### ISSUE TITLE
BLAKE2 produces wrong hashes for non-default digest sizes

### ISSUE THREAD

**Issue by c0ff** [weidai11/cryptopp#415]
The constructor `BLAKE2_Base(bool treeMode, unsigned int digestSize)` uses an incorrect initialization block and produces wrong results if either treeMode or digestSize differ from default.
The patch is here:
[blake2-init-patch.zip](https://github.com/weidai11/cryptopp/files/991589/blake2-init-patch.zip)

In essense it replaces
`UncheckedSetKey(NULL, 0, g_nullNameValuePairs);`
with
`UncheckedSetKey(NULL, 0, MakeParameters(Name::DigestSize(), (int)digestSize)(Name::TreeMode(), treeMode, false));`

**Comment by noloader** [comment]
Thanks @c0ff.

Can you test this against master? I'm tied up at the moment with other testing.

```
git clone https://github.com/weidai11/cryptopp-fix
cd cryptopp-fix

./cryptest.sh
```

`cryptest.sh` is our test script from hell, and it torture tests the library under different configurations. On a modern desktop, like a 5th gen or 6th gen, it will take a couple of hours to run.

**Comment by c0ff** [comment]
Adjusted and tested the patches against master: [blake2-init-and-test-patches.zip](https://github.com/weidai11/cryptopp/files/991767/blake2-init-and-test-patches.zip)

Though, I only did a short test with `cryptest.exe v 74` and `cryptest.exe v 75`.

After applying blake2-test.patch:
  Without blake2-init.patch:
    [failed_blake2s.txt](https://github.com/weidai11/cryptopp/files/991768/failed_blake2s.txt)
    [failed_blake2b.txt](https://github.com/weidai11/cryptopp/files/991770/failed_blake2b.txt)

  With blake2-init.patch:
    [passed_blake2s.txt](https://github.com/weidai11/cryptopp/files/991773/passed_blake2s.txt)
    [passed_blake2b.txt](https://github.com/weidai11/cryptopp/files/991774/passed_blake2b.txt)

**Comment by c0ff** [comment]
The new test vectors were generated with pyblake2 which uses 'BLAKE2 reference source code package' by Samuel Neves.

**Comment by noloader** [comment]
Thanks @c0ff.

> Adjusted and tested the patches against master: blake2-init-and-test-patches.zip

Do you want to make a [Pull Request](https://help.github.com/articles/creating-a-pull-request/) (see [Creating a pull request](https://help.github.com/articles/creating-a-pull-request/))? If you do, then you become [contributor](https://github.com/weidai11/cryptopp/graphs/contributors). I like to see folks get credit for their work, so I'd like to see you make one. It also relieves me from maintaining a separate file with a list of contributors.

If you don't want to, then that's fine, too. I'll drop your patch by hand and push it.

----
> The new test vectors were generated with pyblake2 which uses 'BLAKE2 reference source code package' by Samuel Neves.

Cool, thanks. That's good provenance.

**Comment by c0ff** [comment]
Ok, will try to make a Pull Request then, I need to get used to it anyway :)

**Comment by noloader** [comment]
> Ok, will try to make a Pull Request then, I need to get used to it anyway :)

Just an FYI... The GitHub instructions for updating your clone from Wei's are kind of borked. They create a lot of unnecessary merges. Use these instructions instead: [Keeping A GitHub Fork Updated](https://robots.thoughtbot.com/keeping-a-github-fork-updated).

**Comment by noloader** [comment]
Cleared with [Pull Request 416](https://github.com/weidai11/cryptopp/pull/416).
