### ISSUE TITLE
armv7l/aarch64: error: ‘HasRDRAND’ was not declared in this scope

### ISSUE THREAD

**Issue by anonimal** [weidai11/cryptopp#419]
Built against 35451f3

Build logs:

[armv7l | GCC 5.4.0 | Ubuntu Xenial](https://build.getmonero.org/builders/kovri-all-ubuntu-arm7/builds/321/steps/compile/logs/stdio)
[aarch64 | GCC 6.2.1 | Debian 8](https://build.getmonero.org/builders/kovri-all-debian-arm8/builds/306/steps/compile/logs/stdio)

Successful build logs for remaining platforms:

https://github.com/monero-project/kovri/pull/639

**Comment by noloader** [comment]
Thanks @anonimal.

The GNUmakefile does not build IA32 specific source files on ARM. It removes them (near [line 525](https://github.com/weidai11/cryptopp/blob/master/GNUmakefile)):

```
# Need RDRAND for X86/X64/X32
ifeq ($(IS_X86)$(IS_X32)$(IS_X64),000)
  SRCS := $(filter-out rdrand.cpp, $(SRCS))
endif
```

Do you know why CMake is building IA32 stuff on Arm?

**Comment by anonimal** [comment]
>Do you know why CMake is building IA32 stuff on Arm?

Well, AFAICT, I don't see any place in the recipe that discriminates against building files based on architecture (only APPEND'ing based on platform/compiler).  With some minor refactoring, we could list all source files to be built and fine-tune as appropriate. Would this be a solution to this issue (#419)?

**Comment by noloader** [comment]
Well, here's where I'm at with trying to make the changes:

```
$ git diff CMakeLists.txt
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 841fdab..e44dcb3 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -294,6 +294,7 @@ list(REMOVE_ITEM cryptopp_SOURCES
                ${CMAKE_CURRENT_SOURCE_DIR}/integer.cpp
                ${CMAKE_CURRENT_SOURCE_DIR}/pch.cpp
                ${CMAKE_CURRENT_SOURCE_DIR}/simple.cpp
+               ${CMAKE_CURRENT_SOURCE_DIR}/rdrand.cpp^M
                ${CMAKE_CURRENT_SOURCE_DIR}/winpipes.cpp
                ${CMAKE_CURRENT_SOURCE_DIR}/cryptlib_bds.cpp
                ${cryptopp_SOURCES_TEST}
@@ -305,6 +306,11 @@ set(cryptopp_SOURCES
                ${cryptopp_SOURCES}
                )

+# http://github.com/weidai11/cryptopp/issues/419^M
+if (${ARCHITECTURE_ID} STREQUAL "X86" OR ${ARCHITECTURE_ID} STREQUAL "X32" OR ${ARCHITECTURE_ID} STREQUAL "X64" )^M
+       list(APPEND cryptopp_SOURCES ${CMAKE_CURRENT_SOURCE_DIR}/rdrand.cpp)^M
+endif()^M
+^M
 if(MINGW OR WIN32)
        list(APPEND cryptopp_SOURCES ${CMAKE_CURRENT_SOURCE_DIR}/winpipes.cpp)
 endif()
```

Unfortunately:

```
$ cmake .
CMake Error at CMakeLists.txt:310 (if):
  if given arguments:

    "STREQUAL" "X86" "OR" "STREQUAL" "X32" "OR" "STREQUAL" "X64"

  Unknown arguments specified
```

**Comment by anonimal** [comment]
>CMake Error at CMakeLists.txt:310 (if):
  if given arguments:
    "STREQUAL" "X86" "OR" "STREQUAL" "X32" "OR" "STREQUAL" "X64"
  Unknown arguments specified

@noloader Putting quotes around `${ARCHITECTURE_ID}` solves that problem. After that will come:

```
CMakeFiles/cryptest.dir/validat1.cpp.o: In function `CryptoPP::Test::TestRDRAND()':
/home/anonimal/cryptopp/validat1.cpp:937: undefined reference to `CryptoPP::RDRAND::RDRAND()'
/home/anonimal/cryptopp/validat1.cpp:941: undefined reference to `typeinfo for CryptoPP::RDRAND'
CMakeFiles/cryptest.dir/validat1.cpp.o: In function `CryptoPP::Test::TestRDSEED()':
/home/anonimal/cryptopp/validat1.cpp:1042: undefined reference to `CryptoPP::RDSEED::RDSEED()'
/home/anonimal/cryptopp/validat1.cpp:1046: undefined reference to `typeinfo for CryptoPP::RDSEED'
CMakeFiles/cryptest.dir/regtest1.cpp.o: In function `CryptoPP::DefaultObjectFactory<CryptoPP::RandomNumberGenerator, CryptoPP::RDSEED>::CreateObject() const':
/home/anonimal/cryptopp/factory.h:36: undefined reference to `CryptoPP::RDSEED::RDSEED()'
CMakeFiles/cryptest.dir/regtest1.cpp.o: In function `CryptoPP::DefaultObjectFactory<CryptoPP::RandomNumberGenerator, CryptoPP::RDRAND>::CreateObject() const':
/home/anonimal/cryptopp/factory.h:36: undefined reference to `CryptoPP::RDRAND::RDRAND()'
```

on an X86_64 system. Will text on ARM soon.

**Comment by noloader** [comment]
@anonimal,

We went with an end-around. We avoid the problem by always building RDRAND and RDSEED, even on platforms that don't have it like ARM and MIPS. We don't have to worry about Cmake providing incorrect or incomplete information.

Also see [Commit 1b1c32d7cf88](https://github.com/weidai11/cryptopp/commit/1b1c32d7cf883078e0da02aaa38981f81c639cf3)

**Comment by anonimal** [comment]
Thanks @noloader.

**Comment by noloader** [comment]
@anonimal ,

No problem. Here's what it looks like when running the self tests. Trying `RDRAND` and `RDSEED` on ARM, MIPS and PPC is now expected:

```
...
Testing AutoSeeded RandomPool generator...

passed:  100000 generated bytes compressed to 100020 bytes by DEFLATE
passed:  discarded 10000 bytes
passed:  IncorporateEntropy with 128 bytes
passed:  GenerateWord32 and Crop

Testing AutoSeeded X917 generator...

passed:  100000 generated bytes compressed to 100020 bytes by DEFLATE
passed:  discarded 10000 bytes
passed:  IncorporateEntropy with 128 bytes
passed:  GenerateWord32 and Crop

Testing RDRAND generator...

RDRAND generator not available, skipping test.

Testing RDSEED generator...

RDSEED generator not available, skipping test.

CRC-32 validation suite running...

passed   00000000   ""
passed   43beb7e8   "a"
passed   c2412435   "abc"
...
```

**Comment by yuriks** [comment]
Just as a FYI: You can use [CheckSymbolExists](https://cmake.org/cmake/help/v3.9/module/CheckSymbolExists.html) or [CheckCSourceCompiles](https://cmake.org/cmake/help/v3.9/module/CheckCSourceCompiles.html) to do feature testing like this. In addition to checking for the instructions directly, you can also implement custom architecture detection [like we did in our project](https://github.com/citra-emu/citra/blob/343bbfdabc33630b3913aab39a2b30947dfbfbc2/CMakeLists.txt#L38-L72).

**Comment by noloader** [comment]
Last call for CMake patches before removing it from the library and adding it to the patch page. If you have something to add, then now is the time to do it.

Also see [Remove CMake from GitHub; add it to Patch Page on wiki?](https://groups.google.com/forum/#!topic/cryptopp-users/PKlz8-ClXOU) and [Commit 1c740b0a097aecaa](https://github.com/weidai11/cryptopp/commit/1c740b0a097aecaa66044036c0d2c54220eda5d5).
