### ISSUE TITLE
Add Gzip Filename, Filetime and Comment support

### ISSUE THREAD

**Issue by noloader** [weidai11/cryptopp#420]
This is a tracking issue to document Filename, Filetime and Comment support for Gzip.

Also see [Add Filename, Filetime and Comment support to Gzip?](https://groups.google.com/forum/#!topic/cryptopp-users/FB8b02N5utI) on the mailing list and [Pull Request 418](https://github.com/weidai11/cryptopp/pull/418).

**Comment by noloader** [comment]
@c0ff,

When running a ***Debug*** build of `cryptest.exe v`, I'm seeing a failure:

```
Testing Compressors and Decompressors...

FAILED:   Gunzip: length check error
FAILED:  128 zips and unzips
passed:  128 deflates and inflates
passed:  128 zlib decompress and compress
```

The code responsible for the failure is located in [`validat0.cpp : 187`](https://github.com/weidai11/cryptopp/blob/master/validat0.cpp#L187).

Now, this __could__ mean our dumb fuzzing has uncovered a gap/bug/crash. Or, things may be working as expected and we are incorrectly reporting *`FAILED:   Gunzip: length check error`*.

In either case, would you mind looking at it?

**Comment by c0ff** [comment]
Ok, will do

**Comment by c0ff** [comment]
I merged with the upstream and apart from a pair of empty line formatting conflicts, one looks like a bug:

<<<<<<< HEAD
	AttachedTransformation()->PutWord32(m_filetime, LITTLE_ENDIAN_ORDER);	// time stamp
=======
	AttachedTransformation()->PutWord32(m_filetime, BIG_ENDIAN_ORDER);	// time stamp
>>>>>>> upstream/master

The RFC says GZIP uses little-endian order. And in your commit it is big-endian for some reason.

**Comment by c0ff** [comment]
Indeed with LITTLE_ENDIAN_ORDER:

```
Testing Compressors and Decompressors...

passed:  128 zips and unzips
passed:  128 deflates and inflates
passed:  128 zlib decompress and compress

```

**Comment by c0ff** [comment]
You commit 591b13934336a73edcc429f27d340a5fb91d51c6 seems to be the problem.
First of all it changes only the writing side, but not the reading. And then it contradicts the RFC.

**Comment by c0ff** [comment]
I was too fast on conclusions, sorry. Enabled DEBUG and CRYPTOPP_COVERAGE - got assert in CryptoPP::Inflator::DecodeBody. So will stop spamming until I get it right.

**Comment by noloader** [comment]
> You commit 591b139 seems to be the problem. First of all it changs only the writing side, but not the reading - that's why the tests fail. And then it contradicts the RFC.

Crap, you are right. I stopped reading at the second paragraph/third diagram of section 2.

Let me back that out...

**Comment by noloader** [comment]
> I was too fast on conclusions, sorry. Enabled DEBUG and CRYPTOPP_COVERAGE - got assert in CryptoPP::Inflator::DecodeBody.

Those are expected with bad data. When testing a run of 128, you usually see 2 or 3 of them.

Asserts are controlled by `-DDEBUG` or `-DCRYPTOPP_DEBUG`. You can suppress them with the following (which still enables the extended validation):

```
CXXFLAGS="-DNDEBUG -DCRYPTOPP_DEBUG -g2 -O3 ..."
```

**Comment by c0ff** [comment]
The assert I get is quite interesting:
Assertion failed: zinflate.cpp(560): CryptoPP::Inflator::DecodeBody
					// TODO: this surfaced during fuzzing. What do we do???
					CRYPTOPP_ASSERT(m_distance < COUNTOF(distanceExtraBits));

But it only appears if I compile with /Zi but link without /DEBUG - according to MSDN this is an incorrect combination of flags:
https://msdn.microsoft.com/en-us/library/958x11bc.aspx
`However, /Zi does imply /debug; `

So this is not a problem with the code.

**Comment by c0ff** [comment]
I used nmake file, not the projects. Uncommented debug CXXFLAGS and got the assert, as LDFLAGS were left unchanged.

**Comment by noloader** [comment]
> I used nmake file, not the projects

Man, +1. I thought I was the only guy who used it. I love that namke file.

**Comment by noloader** [comment]
@c0ff, I removed about 6 intermediate comments from the thread. I accidentally whacked the one where you said the commit broke things, but the one that cites it is still there. Sorry about that.

**Comment by c0ff** [comment]
@noloader No problem.
I've taken a look at #159 - nope, sorry. I'm more of an ex-Linux kind of guy and I try no to touch ms-specific stuff. At my job we use scons/python-based build system for everything, including CryptoPP. We even generate vcproject files with it - much easier to make configuration changes this way.
