### ISSUE TITLE
/root/testdir/cryptopp/rdrand.cpp:345: Error: no such instruction: `rdseed rax'

### ISSUE THREAD

**Issue by owen200008** [weidai11/cryptopp#431]
some one have this error？
/root/testdir/cryptopp/rdrand.cpp:345: Error: no such instruction: `rdseed rax'
clone the newest version same error when build。
use gcc 7.1  gcc 4.9 is same

**Comment by owen200008** [comment]
use the command 
mkdir build && cd build
cmake ..

**Comment by owen200008** [comment]
use the gcc 4.4.7 it compile success.

**Comment by noloader** [comment]
Thanks @owen200008.

Its kind of unusual `rdrand` does not cause an error first. What does the following do:

```
rm -f rdrand.o
make CXXFLAGS="-DNDEBUG -g2 -O2" rdrand.o
```

**Comment by owen200008** [comment]
what can i do to solve？ now i can not compile the lib and dll~

**Comment by noloader** [comment]
@owen200008,

We need more information.

**Comment by owen200008** [comment]
what can i supply？
the error msg
/root/testdir/cryptopp/rdrand.cpp: Assembler messages:
/root/testdir/cryptopp/rdrand.cpp:345: Error: no such instruction: `rdseed rax'
/root/testdir/cryptopp/rdrand.cpp:345: Error: no such instruction: `rdseed rax'
make[2]: *** [CMakeFiles/cryptopp-object.dir/rdrand.cpp.o] Error 1
make[1]: *** [CMakeFiles/cryptopp-object.dir/all] Error 2

**Comment by owen200008** [comment]
i just clone the newest version to the testdir
and run the command
mkdir build && cd build
cmake ..
75% compile the rdrand.cpp says the error.

**Comment by owen200008** [comment]
w make the SSE4 SSSE3 SHA ANI DISABLE is also the error

**Comment by noloader** [comment]
@owen200008,

Please provide the output of the following.

```
rm -f rdrand.o
make CXXFLAGS="-DNDEBUG -g2 -O2" rdrand.o
```

**Comment by owen200008** [comment]
it do't have the file rdrand.o 
in the build dir it have follow file and dir:
CMakeCache.txt  CMakeFiles  cmake_install.cmake  cryptopp-config-version.cmake  CTestTestfile.cmake  Makefile  TestData  TestVectors

i run the make CXXFLAGS="-DNDEBUG -g2 -O2" rdrand.o in the build is the same error

**Comment by owen200008** [comment]
[root@MiWiFi-R1CM-srv build]# find ./ -name "rd*"
./CMakeFiles/cryptopp-object.dir/rdtables.cpp.o

**Comment by owen200008** [comment]
[root@MiWiFi-R1CM-srv build]# find ./ -name "rd*"
./CMakeFiles/cryptopp-object.dir/rdtables.cpp.o

**Comment by noloader** [comment]
@owen200008,

Please visit [Bug Report](https://www.cryptopp.com/wiki/Bug_Report) and provide the information requested. There's not much we can do when you are withholding important information. We need to know the OS, the compiler, and the output of the compile command.

**Comment by owen200008** [comment]
make cryptest.exe -j4 have the same error。
rdrand.cpp: Assembler messages:
rdrand.cpp:345: Error: no such instruction: `rdseed rax'
rdrand.cpp:345: Error: no such instruction: `rdseed rax'
make: *** [rdrand.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by noloader** [comment]
@owen200008,

The error alone is not enough. Please provide the requested information.

**Comment by owen200008** [comment]
what is the requested information?
os : centos(Linux MiWiFi-R1CM-srv 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux)
compiler: gcc 7.1.0 gcc 4.9.4
compile command:
git clone cryptopp to testdir
cd testdir && mkdir build && cd build
cmake ..
make

error:
/root/testdir/cryptopp/rdrand.cpp: Assembler messages:
/root/testdir/cryptopp/rdrand.cpp:345: Error: no such instruction: rdseed rax' /root/testdir/cryptopp/rdrand.cpp:345: Error: no such instruction:rdseed rax'
make[2]: *** [CMakeFiles/cryptopp-object.dir/rdrand.cpp.o] Error 1
make[1]: *** [CMakeFiles/cryptopp-object.dir/all] Error 2

**Comment by noloader** [comment]
@owen200008,

> what is the requested information?

I've asked for the compile command several times.

I'd also like to see the CPU features, but we have not gotten that far. I've got two machines with `rdrand` and without `rdseed`, but I cannot duplicate the issue. Hence the reason I want to see how you are compiling things.

**Comment by owen200008** [comment]
Sorry. I'm not familiar to report infomation。 also english is not familiar too。 I hope you would excuse me。
I run the centos in the VMware
my cpu is E3-1231 v3

**Comment by owen200008** [comment]
My totally compile command only follow:
git clone cryptopp to testdir
cd testdir && mkdir build && cd build
cmake ..
make

the totolly error:
 Building CXX object CMakeFiles/cryptopp-object.dir/rdrand.cpp.o
/root/testdir/cryptopp/rdrand.cpp: Assembler messages:
/root/testdir/cryptopp/rdrand.cpp:345: Error: no such instruction: `rdseed rax'
/root/testdir/cryptopp/rdrand.cpp:345: Error: no such instruction: `rdseed rax'
make[2]: *** [CMakeFiles/cryptopp-object.dir/rdrand.cpp.o] Error 1
make[1]: *** [CMakeFiles/cryptopp-object.dir/all] Error 2
make: *** [all] Error 2

**Comment by noloader** [comment]
We need to see the compile command. For example, here's from a machine with `rdrand` and without `rdseed`:

```
$ rm -f rdrand.o
$ make CXXFLAGS="-DNDEBUG -g2 -O2" rdrand.o
g++ -DNDEBUG -g2 -O2 -c rdrand.cpp
$
```

We may also need to see the cpu features:

```
$ cat /proc/cpuinfo | fold -w 80
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 58
model name      : Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
stepping        : 9
cpu MHz         : 2594.000
cache size      : 256 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov
pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe pni dtes64 monitor ds_
cpl vmx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 x2apic popcnt aes xsave osxsa
ve avx f16c rdrand lahf_lm ida arat epb xsaveopt pln pts dtherm fsgsbase smep er
ms
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:
```

**Comment by owen200008** [comment]
you are so kind~ thanks!

[root@MiWiFi-R1CM-srv jemalloc]# cat /proc/cpuinfo | fold -w 80
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 60
model name      : Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz
stepping        : 3
cpu MHz         : 3392.149
cache size      : 8192 KB
physical id     : 0
siblings        : 2
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov
pat pse36 clflush dts mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm const
ant_tsc arch_perfmon pebs bts xtopology tsc_reliable nonstop_tsc aperfmperf unfa
ir_spinlock pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt
tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm ida arat xsa
veopt pln pts dts fsgsbase bmi1 avx2 smep bmi2 invpcid
bogomips        : 6784.29
clflush size    : 64
cache_alignment : 64
address sizes   : 42 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 60
model name      : Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz
stepping        : 3
cpu MHz         : 3392.149
cache size      : 8192 KB
physical id     : 0
siblings        : 2
core id         : 1
cpu cores       : 2
apicid          : 1
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov
pat pse36 clflush dts mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm const
ant_tsc arch_perfmon pebs bts xtopology tsc_reliable nonstop_tsc aperfmperf unfa
ir_spinlock pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt
tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm ida arat xsa
veopt pln pts dts fsgsbase bmi1 avx2 smep bmi2 invpcid
bogomips        : 6784.29
clflush size    : 64
cache_alignment : 64
address sizes   : 42 bits physical, 48 bits virtual
power management:

processor       : 2
vendor_id       : GenuineIntel
cpu family      : 6
model           : 60
model name      : Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz
stepping        : 3
cpu MHz         : 3392.149
cache size      : 8192 KB
physical id     : 1
siblings        : 2
core id         : 0
cpu cores       : 2
apicid          : 2
initial apicid  : 2
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov
pat pse36 clflush dts mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm const
ant_tsc arch_perfmon pebs bts xtopology tsc_reliable nonstop_tsc aperfmperf unfa
ir_spinlock pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt
tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm ida arat xsa
veopt pln pts dts fsgsbase bmi1 avx2 smep bmi2 invpcid
bogomips        : 6784.29
clflush size    : 64
cache_alignment : 64
address sizes   : 42 bits physical, 48 bits virtual
power management:

processor       : 3
vendor_id       : GenuineIntel
cpu family      : 6
model           : 60
model name      : Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz
stepping        : 3
cpu MHz         : 3392.149
cache size      : 8192 KB
physical id     : 1
siblings        : 2
core id         : 1
cpu cores       : 2
apicid          : 3
initial apicid  : 3
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov
pat pse36 clflush dts mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm const
ant_tsc arch_perfmon pebs bts xtopology tsc_reliable nonstop_tsc aperfmperf unfa
ir_spinlock pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt
tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm ida arat xsa
veopt pln pts dts fsgsbase bmi1 avx2 smep bmi2 invpcid
bogomips        : 6784.29
clflush size    : 64
cache_alignment : 64
address sizes   : 42 bits physical, 48 bits virtual
power management:

**Comment by owen200008** [comment]
[root@MiWiFi-R1CM-srv cryptopp]# g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-pc-linux-gnu/7.1.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ../configure --enable-checking=release --enable-languages=c,c++ --disable-multilib
Thread model: posix
gcc version 7.1.0 (GCC)

[root@MiWiFi-R1CM-srv cryptopp]# make CXXFLAGS="-DNDEBUG -g2 -O2" rdrand.o
g++ -DNDEBUG -g2 -O2 -c rdrand.cpp
rdrand.cpp: Assembler messages:
rdrand.cpp:345: Error: no such instruction: `rdseed rax'
rdrand.cpp:345: Error: no such instruction: `rdseed rax'
make: *** [rdrand.o] Error 1

**Comment by noloader** [comment]
@owen200008,

Here's the code that's causing the problem (from [`rdrand.cpp : 345`]()):

```
#elif defined(GCC_RDSEED_ASM_AVAILABLE) && (CRYPTOPP_GCC_VERSION >= 40600)
    __asm__ __volatile__
    (
        INTEL_NOPREFIX
        ASL(1)
        AS1(rdseed rax)
        ASJ(jnc,   1, b)
        ATT_NOPREFIX
        : "=a" (*reinterpret_cast<word64*>(output))
        : : "cc"
);
```

Rejecting the code in the inline assembly block is new behavior. It looks like something has changed in the assembler. The assembler is part of [Binutils](https://www.gnu.org/software/binutils/).

What version of Binutils does the distro provide?

```
$ as --version
GNU assembler (GNU Binutils for Ubuntu) 2.26.1
Copyright (C) 2015 Free Software Foundation, Inc.
```

For now, you should be able to delete the block. Something like:

```
$ git diff rdrand.cpp
diff --git a/rdrand.cpp b/rdrand.cpp
index b591407..293db6f 100644
--- a/rdrand.cpp
+++ b/rdrand.cpp
@@ -69,12 +69,12 @@
 #    define GCC_RDSEED_ASM_AVAILABLE 1
 #  endif
 # elif defined(CRYPTOPP_GCC_VERSION)
-#  if defined(__RDRND__) && (CRYPTOPP_GCC_VERSION >= 40600) && !defined(__OPTIMIZE__)
+#  if defined(__RDRND__) && (CRYPTOPP_GCC_VERSION >= 40600)^M
 #    define ALL_RDRAND_INTRIN_AVAILABLE 1
 #  else
 #    define GCC_RDRAND_ASM_AVAILABLE 1
 #  endif
-#  if defined(__RDSEED__) && (CRYPTOPP_GCC_VERSION >= 40600) && !defined(__OPTIMIZE__)
+#  if defined(__RDSEED__) && (CRYPTOPP_GCC_VERSION >= 40600)^M
 #    define ALL_RDSEED_INTRIN_AVAILABLE 1
 #  else
 #    define GCC_RDSEED_ASM_AVAILABLE 1
@@ -132,17 +132,6 @@ inline void RDRAND32(void* output)
         : "=a" (*reinterpret_cast<word32*>(output))
         : : "cc"
     );
-#elif defined(GCC_RDRAND_ASM_AVAILABLE) && (CRYPTOPP_GCC_VERSION >= 40600)
-    __asm__ __volatile__
-    (
-        INTEL_NOPREFIX
-        ASL(1)
-        AS1(rdrand eax)
-        ASJ(jnc,   1, b)
-        ATT_NOPREFIX
-        : "=a" (*reinterpret_cast<word32*>(output))
-        : : "cc"
-    );
 #elif defined(GCC_RDRAND_ASM_AVAILABLE) && (CRYPTOPP_GCC_VERSION >= 30200)
     __asm__ __volatile__
     (
@@ -174,17 +163,6 @@ inline void RDRAND64(void* output)
         : "=a" (*reinterpret_cast<word64*>(output))
         : : "cc"
     );
-#elif defined(GCC_RDRAND_ASM_AVAILABLE) && (CRYPTOPP_GCC_VERSION >= 40600)
-    __asm__ __volatile__
-    (
-        INTEL_NOPREFIX
-        ASL(1)
-        AS1(rdrand rax)
-        ASJ(jnc,   1, b)
-        ATT_NOPREFIX
-        : "=a" (*reinterpret_cast<word64*>(output))
-        : : "cc"
-    );
 #elif defined(GCC_RDRAND_ASM_AVAILABLE) && (CRYPTOPP_GCC_VERSION >= 30200)
     __asm__ __volatile__
     (
@@ -289,17 +267,6 @@ inline void RDSEED32(void* output)
         : "=a" (*reinterpret_cast<word32*>(output))
         : : "cc"
     );
-#elif defined(GCC_RDSEED_ASM_AVAILABLE) && (CRYPTOPP_GCC_VERSION >= 40600)
-    __asm__ __volatile__
-    (
-        INTEL_NOPREFIX
-        ASL(1)
-        AS1(rdseed eax)
-        ASJ(jnc,   1, b)
-        ATT_NOPREFIX
-        : "=a" (*reinterpret_cast<word32*>(output))
-        : : "cc"
-    );
 #elif defined(GCC_RDSEED_ASM_AVAILABLE) && (CRYPTOPP_GCC_VERSION >= 30200)
     __asm__ __volatile__
     (
@@ -331,17 +298,6 @@ inline void RDSEED64(void* output)
         : "=a" (*reinterpret_cast<word64*>(output))
         : : "cc"
     );
-#elif defined(GCC_RDSEED_ASM_AVAILABLE) && (CRYPTOPP_GCC_VERSION >= 40600)
-    __asm__ __volatile__
-    (
-        INTEL_NOPREFIX
-        ASL(1)
-        AS1(rdseed rax)
-        ASJ(jnc,   1, b)
-        ATT_NOPREFIX
-        : "=a" (*reinterpret_cast<word64*>(output))
-        : : "cc"
-    );
 #elif defined(GCC_RDSEED_ASM_AVAILABLE) && (CRYPTOPP_GCC_VERSION >= 30200)
     __asm__ __volatile__
     (
```

**Comment by noloader** [comment]
I have not been able to duplicate this in a VM. What hardware are you using, and what is the OS?

The closest I have is Debian 8 with GCC 7. I can't get Fedora 25 or 26 to provide GCC 7.

```
$ gcc-7 --version
gcc-7 (Debian 7-20170226-1) 7.0.1 20170226 (experimental) [trunk revision 245744]
Copyright (C) 2017 Free Software Foundation, Inc.

$ as --version
GNU assembler (GNU Binutils for Debian) 2.28
Copyright (C) 2017 Free Software Foundation, Inc.
```

**Comment by owen200008** [comment]
meeting. 15m later

**Comment by owen200008** [comment]
[root@MiWiFi-R1CM-srv jemalloc]# as -version
GNU assembler version 2.20.51.0.2-5.44.el6 20100205
Copyright 2009 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or later.
This program has absolutely no warranty.
This assembler was configured for a target of `x86_64-redhat-linux'.

**Comment by owen200008** [comment]
it compile success like your change code。
i use CentOS release 6.5 (Final) 
Linux MiWiFi-R1CM-srv 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
hardware is normal。

**Comment by noloader** [comment]
CentOS 6 ships with GCC 4.4. Where did GCC 7 come from?

**Comment by owen200008** [comment]
download make self  4.9.4 and  7.1

**Comment by owen200008** [comment]
the newest version also have the error。 how can i solve the error？
except change code by myself
need to update as version？

**Comment by noloader** [comment]
> the newest version also have the error。 how can i solve the error？
> except change code by myself need to update as version？

Rebuild your compiler, and ensure it includes assembler support for the IA-32 latest instructions. Don't remove any instructions.

You won't be so lucky at the next check-in. The next check-in is a change that will provide additional support, like AVX and SHA. Its intended to support distros like Debian and Fedora.

**Comment by noloader** [comment]
Last call for CMake patches before removing it from the library and adding it to the patch page. If you have something to add, then now is the time to do it.

Also see [Remove CMake from GitHub; add it to Patch Page on wiki?](https://groups.google.com/forum/#!topic/cryptopp-users/PKlz8-ClXOU) and [Commit 1c740b0a097aecaa](https://github.com/weidai11/cryptopp/commit/1c740b0a097aecaa66044036c0d2c54220eda5d5).

**Comment by dj-on-github** [comment]
I have someone reporting a similar problem with GCC 7.1. on quickrdrand : https://github.com/dj-on-github/quickrdrand/issues/1
