### ISSUE TITLE
depreceated calls

### ISSUE THREAD

**Issue by AlexDvorak** [weidai11/cryptopp#443]
In file included from default.cpp:13:
./default.h:146:43: warning: 'DefaultDecryptor' is deprecated [-Wdeprecated-declarations]
        class MACBadErr : public DefaultDecryptor::Err {public: MACBadErr() : DefaultDecryptor::Err("DefaultDecryptorWithMAC: MAC check failed") {}};
                                                 ^
./default.h:57:7: note: 'DefaultDecryptor' has been explicitly marked deprecated here
class DefaultDecryptor : public ProxyFilter
      ^
./default.h:161:18: warning: 'DefaultDecryptor' is deprecated [-Wdeprecated-declarations]
        DefaultDecryptor::State CurrentState() const;
                        ^
./default.h:57:7: note: 'DefaultDecryptor' has been explicitly marked deprecated here
class DefaultDecryptor : public ProxyFilter
      ^
2 warnings generated.

**Comment by noloader** [comment]
This was tracked under [Issue 345, Update DefaultEncryptor, DefaultEncryptorWithMAC and friends](https://github.com/weidai11/cryptopp/issues/345), and cleared at [Commit bfbcfeec7ca7](https://github.com/weidai11/cryptopp/commit/bfbcfeec7ca7a0487978391803496a1d4aada37c).
