### ISSUE TITLE
Attempt to support GCC's -fdevirtualize

### ISSUE THREAD

**Issue by noloader** [weidai11/cryptopp#45]
GCC offers `-fdevirtualize` option, which appears to be similar to Microsoft's `__declspec(novtable)`. See [Options That Control Optimization](http://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html)

**Comment by Zireael-N** [comment]
I typed a long post about my observations, but then I had an idea, that basically was right. Made a pull request

---
> Third, I've seen problems with inlining functions. I had to move a few functions out-of-line because of crashes. I can't explain why it avoids the crash.

That was the culprit.

---
> Fourth, I've never tried `-fdevirtualize`

It's [a part of -O2](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html). :)

**Comment by noloader** [comment]
>> Fourth, I've never tried -fdevirtualize
> It's a part of -O2. :)

OK< thanks. That's good to know.

I'm trying to track down a rare crash in SHA. The only person experiencing it is a Debian maintainer who regularly uses Sid. I've tried to duplicate it but I cannot. I think I might ask him to try `-fno-devirtualize`.

**Comment by noloader** [comment]
Zireael - how do you want us to give you credit in the Readme and source files? Is "Zireael-N N" OK, or do you want something else?

By the way, your fix cleared that obscure hang on Debian that I was chasing for weeks.

**Comment by Zireael-N** [comment]
> By the way, your fix cleared that obscure hang on Debian that I was chasing for weeks.

Glad to hear that!

> Is "Zireael N" OK, or do you want something else?

Just "Zireael" is enough.

I've also updated the bug report on GCC's bugzilla. Hopefully, they'll look into that.

**Comment by noloader** [comment]
>> By the way, your fix cleared that obscure hang on Debian that I was chasing for weeks.
> Glad to hear that!

I got confirmation from the Debian folks today. It cleared the issue.

Thanks again. I owe you a cold beer if you make it to my area. Baltimore MD/Washington DC or New York.

**Comment by Zireael-N** [comment]
Haha, I wish I could! I'm not from the US.
