### ISSUE TITLE
undefined symbol: _ZN8CryptoPP8Rijndael3EncC2Ev

### ISSUE THREAD

**Issue by Earlz** [weidai11/cryptopp#453]
I'm receiving this error. I'm using a custom makefile for building CryptoPP. The symbol referened is `CryptoPP::Rijndael::Enc::Enc()`. I found it here:

```
#if CRYPTOPP_BOOL_X64 || CRYPTOPP_BOOL_X32 || CRYPTOPP_BOOL_X86
struct Locals
{
	word32 subkeys[4*12], workspace[8];
	const byte *inBlocks, *inXorBlocks, *outXorBlocks;
	byte *outBlocks;
	size_t inIncrement, inXorIncrement, outXorIncrement, outIncrement;
	size_t regSpill, lengthAndCounterFlag, keysBegin;
};

const size_t s_aliasPageSize = 4096;
const size_t s_aliasBlockSize = 256;
const size_t s_sizeToAllocate = s_aliasPageSize + s_aliasBlockSize + sizeof(Locals);

Rijndael::Enc::Enc() : m_aliasBlock(s_sizeToAllocate) { }
#endif
```

I tried removing these guards, but the error persists. Exact compiler flags are simply `-DNDEBUG -fPIC`

Furthermore, I'm linking it only as a static library, making this dynamic lookup bit even more confusing

My own code is not referencing this enc::enc() bit, it is only using the external public interfaces as AES

**Comment by Earlz** [comment]
Furthermore, I'm linking it only as a static library, making this dynamic lookup bit even more confusing

**Comment by noloader** [comment]
@Earlz,

Thanks for the report. I cannot duplicate working from Crypto++ 5.6.5 release ZIP or Master on x86_64. I _think_ this duplicates your build, but I am not sure about the compiler or platform:

```
$ make -j 9 CXXFLAGS="-DNDEBUG -fPIC"
g++ -DNDEBUG -fPIC -c cryptlib.cpp
g++ -DNDEBUG -fPIC -c cpu.cpp
g++ -DNDEBUG -fPIC -c integer.cpp
g++ -DNDEBUG -fPIC -c 3way.cpp
g++ -DNDEBUG -fPIC -c adler32.cpp
g++ -DNDEBUG -fPIC -c algebra.cpp
...
```

Is `Rijndael::Enc` the only missing symbol, or are there more of them? You can get other missing symbols with:

```
$ echo _ZN8CryptoPP8Rijndael3EncC2Ev | c++filt
CryptoPP::Rijndael::Enc::Enc()
```

What version of Crypto++ are you using? What platform are you building on? What compiler are you using?

**Comment by Earlz** [comment]
Sorry, it actually was a local problem, I had -lcryptopp cryptopp/cryptopp.a, so it was trying to link my dynamic system version instead of my locally compiled version. Now I'm fighting a different problem `undefined reference to vtable for CryptoPP::AlgorithmParametersTemplate<int>` and other vtable errors

**Comment by noloader** [comment]
> I had -lcryptopp cryptopp/cryptopp.a, so it was trying to link my dynamic system version instead of my locally compiled version.

Lol... Yeah, dynamic link sucks on Linux. Its amazing its so broken 20 or 30 years after he problems surfaced. Linux really needs to move to install names like Apple does. That half ass, broken RPATHS and SONAMES does not cut it.

I mean, WTF... Those who want to inject, interpose or swizzle should have to do something special. For the rest of the world, things should "just work" without aggravation like you experienced.
