### ISSUE TITLE
amd64: OpenBSD/Clang 3.8.0 without -march=native: error: needs target feature pclmul

### ISSUE THREAD

**Issue by anonimal** [weidai11/cryptopp#468]
[Without `-march=native`](https://github.com/weidai11/cryptopp/files/1247921/OpenBSD_cryptopp_without-native.txt).

**Comment by noloader** [comment]
For this issue, we were failing at the statements below because OpenBSD uses `amd64`, not `x86_64`.

```
execute_process(COMMAND ${SHELL_CMD} "${CMAKE_CXX_COMPILER} -dumpmachine 2>&1"
	COMMAND ${GREP_CMD} "x86_64"
	OUTPUT_VARIABLE CRYPTOPP_X86_64
OUTPUT_STRIP_TRAILING_WHITESPACE)
```

We needed another one to detect `amd64`:

```
execute_process(COMMAND ${SHELL_CMD} "${CMAKE_CXX_COMPILER} -dumpmachine 2>&1"
	COMMAND ${GREP_CMD} "amd64"
	OUTPUT_VARIABLE CRYPTOPP_AMD64
	OUTPUT_STRIP_TRAILING_WHITESPACE)
```

And then:

```
if ("${CRYPTOPP_X86_64}" STREQUAL "1")
	set(CRYPTOPP_AMD64 "1")
endif()
```

**Comment by anonimal** [comment]
Fix confirmed in https://github.com/noloader/cryptopp/commit/d05c5089b8485e588405dc07d464b417151f90d6 😄 Thank you.

**Comment by noloader** [comment]
Cleared at [PR 469](https://github.com/weidai11/cryptopp/pull/469).
