### ISSUE TITLE
[Request] GPG-sign rebased and merge commits

### ISSUE THREAD

**Issue by anonimal** [weidai11/cryptopp#470]
Hi @noloader,

I'm not sure if this question was supposed to go the mailing list, and I don't mean to make extra work for you, but I've noticed a trend where rebased (or appear-to-be rebased) commits (and merge commits) are not GPG-signed. "Normal" commits appear to be signed since #290.

Will you consider signing rebased and merge commits?

**Comment by noloader** [comment]
> Will you consider signing rebased and merge commits?

I have no idea how to do it.

If Git ever un-fucks their workflows so that the task can be accomplished without much fuss, then I'd be happy to do it. But I doubt they are going to un-fuck things anytime soon. Engineers are driving requirements in that project.  They are not capable of translating a simple workflow into a one or two step procedure.

**Comment by anonimal** [comment]
- For rebase: `$ git rebase -S`
- As for merge commits on github, we have a big clunky script which does that - but it's geared to signing pull requests (I should clean it up and throw it on gist). I'll keep my eyes peeled for a solution.

**Comment by noloader** [comment]
@anonimal,

How does this look: [5c6a32ba0f6a](https://github.com/weidai11/cryptopp/commit/5c6a32ba0f6abd6e4fbacf6b483ec2e36df63b15). I basically copied the files by hand from my testing fork into Wei's repo, and them checked them in from Wei's repo. After the official check-in, I reset my testing fork to Wei's repo.

If this is OK with you, then its OK by me.

**Comment by anonimal** [comment]
>How does this look: 5c6a32ba0f6a

I'm not sure, was this commit un-signed when it was originally checked-in?

>The inmates are running the asylum.

🤣

**Comment by anonimal** [comment]
>The procedure is three steps: copy, commit, push. If this is OK with you, then its OK by me.

IMHO, whatever works for you so long as the final outcome is a signed commit in weidai11/cryptopp master 👍

**Comment by noloader** [comment]
> IMHO, whatever works for you so long as the final outcome is a signed commit in weidai11/cryptopp master 

Ack, done.
