### ISSUE TITLE
CMake: avoid egrep when possible, remove egrep from DumpMachine

### ISSUE THREAD

**Issue by anonimal** [weidai11/cryptopp#476]
😡 I specifically said here https://github.com/weidai11/cryptopp/pull/471#issuecomment-325076354 that `egrep` does not work (i.e.., now we're back to inline build errors) but `egrep` was then reintroduced in https://github.com/weidai11/cryptopp/commit/19cabcf15df5ea63cd7b0ceb03f2c1eac30f0e92#diff-af3b638bc2a3e6c650974192a53c7291R105.

Can you please change `egrep` to `grep -E` or drop `egrep` all-together?

**Comment by noloader** [comment]
Oh, sorry about that. Let's just drop `egrep` and use `grep`.

(I don't trust CMake in this area, so I want to expand everything).

**Comment by anonimal** [comment]
>Is that OK?

I'd rather CMake and MSYS/MinGW be usable but yes, that sounds ok to me. Thanks.

**Comment by noloader** [comment]
> I'd rather CMake and MSYS/MinGW be usable but yes, that sounds ok to me. 

Forgive my ignorance... Are you saying `grep ... -E ${pattern}` *does not* work? I.e., its not usable?

`grep -E` is Posix, so we should be safe using it. See *The Open Group Base Specifications*, [grep](http://pubs.opengroup.org/onlinepubs/009695399/utilities/grep.html).

**Comment by noloader** [comment]
Try this one out: [Commit 238154966c4cb](https://github.com/weidai11/cryptopp/commit/238154966c4cb3d98e6251fca85898f083c292f8). It accomplishes two tasks:

1. Fixes `CMakeLists.txt` (yet again) by removing all uses of `egrep`
2. Fixes use of variables due to CMake policy violations (also see [How to use variable and avoid CMP0054 policy violations?](https://stackoverflow.com/q/45900159/608639))

Can you verify things are working as expected?

**Comment by anonimal** [comment]
>Forgive my ignorance... Are you saying grep ... -E ${pattern} does not work? I.e., its not usable?

No, I was complaining about CMake/MSYS/MinGW 😊 

>To remove ambiguity, here is what I would like to change things to:

Yes, that works. I didn't PR extended-regexp for that block because there was no use-case at the time.

>Can you verify things are working as expected?

This does not work because you missed the [one line](https://github.com/weidai11/cryptopp/blob/238154966c4cb3d98e6251fca85898f083c292f8/CMakeLists.txt#L129) that resolves this issue... 😄

**Comment by noloader** [comment]
> > Can you verify things are working as expected?
>
> This does not work because you missed the one line that resolves this issue... 

Ugh... Take two...

**Comment by anonimal** [comment]
>Commit 7e7de550e9f5.

Resolved! Thank you.

**Comment by noloader** [comment]
Sigh, it broke Solaris. NetBSD and OS X look good, so it looks like its an isolated incident.

I think we need to switch to `egrep` for Solaris only. That is, swap `grep` for `egrep` on Solaris.

I wonder why Oracle is not Posix compliant.

-----

```
...
-- Detecting CXX compile features
-- Detecting CXX compile features - done
grep: illegal option -- E
Usage: grep [-c|-l|-q] -bhinsvw pattern file . . .
grep: illegal option -- E
Usage: grep [-c|-l|-q] -bhinsvw pattern file . . .
grep: illegal option -- E
Usage: grep [-c|-l|-q] -bhinsvw pattern file . . .
grep: illegal option -- E
Usage: grep [-c|-l|-q] -bhinsvw pattern file . . .
grep: illegal option -- E
Usage: grep [-c|-l|-q] -bhinsvw pattern file . . .
grep: illegal option -- E
Usage: grep [-c|-l|-q] -bhinsvw pattern file . . .
grep: illegal option -- E
Usage: grep [-c|-l|-q] -bhinsvw pattern file . . .
grep: illegal option -- E
Usage: grep [-c|-l|-q] -bhinsvw pattern file . . .
grep: illegal option -- E
Usage: grep [-c|-l|-q] -bhinsvw pattern file . . .
grep: illegal option -- E
Usage: grep [-c|-l|-q] -bhinsvw pattern file . . .
grep: illegal option -- E
Usage: grep [-c|-l|-q] -bhinsvw pattern file . . .
grep: illegal option -- E
Usage: grep [-c|-l|-q] -bhinsvw pattern file . . .
grep: illegal option -- E
Usage: grep [-c|-l|-q] -bhinsvw pattern file . . .
grep: illegal option -- E
Usage: grep [-c|-l|-q] -bhinsvw pattern file . . .
-- Looking for pthread.h
-- Looking for pthread.h - found
...
```
