### ISSUE TITLE
cryptest: armv7l: undefined references for NEON, PMULL, and DetectArmFeatures

### ISSUE THREAD

**Issue by anonimal** [weidai11/cryptopp#480]
On two of our machines:

[cryptest-result_armv7l-rev2.txt](https://github.com/weidai11/cryptopp/files/1262507/cryptest-result_armv7l-rev2.txt)

```
processor       : 0
model name      : ARMv7 Processor rev 2 (v7l)
BogoMIPS        : 50.00
Features        : half thumb fastmult vfp edsp thumbee vfpv3 tls idiva idivt vfpd32 lpae 
CPU implementer : 0x56
CPU architecture: 7
CPU variant     : 0x2
CPU part        : 0x584
CPU revision    : 2
```

[cryptest-result_armv7l-rev4.txt](https://github.com/weidai11/cryptopp/files/1262508/cryptest-result_armv7l-rev4.txt)

```
processor       : 0
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 50.52
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 4
```

Possibly related to https://github.com/monero-project/kovri/issues/699?

**Comment by noloader** [comment]
OK, for this one, it looks like something is bent in the test that uses `PLATFORM_CXXFLAGS`. That used to be an important test when using "single sources". Its a non-sequitur now that we use "base+simd".

When `CXXFLAGS` lacks `-fpu=neon`, `__ARM_FEATURE_NEON` is not defined, so most of the NEON code paths are removed. However, with the borked `PLATFORM_CXXFLAGS` it results in:

```
ln -sf libcryptopp.so.6.0.0 libcryptopp.so
ln -sf libcryptopp.so.6.0.0 libcryptopp.so.6.0
validat1.o: In function `CryptoPP::HasNEON()':
/home/anonimal/cryptopp/cpu.h:289: undefined reference to `CryptoPP::DetectArmFeatures()'
/home/anonimal/cryptopp/cpu.h:292: undefined reference to `CryptoPP::g_ArmDetectionDone'
/home/anonimal/cryptopp/cpu.h:292: undefined reference to `CryptoPP::g_hasNEON'
validat1.o: In function `CryptoPP::HasPMULL()':
/home/anonimal/cryptopp/cpu.h:304: undefined reference to `CryptoPP::DetectArmFeatures()'
/home/anonimal/cryptopp/cpu.h:306: undefined reference to `CryptoPP::g_ArmDetectionDone'
/home/anonimal/cryptopp/cpu.h:306: undefined reference to `CryptoPP::g_hasPMULL'
collect2: error: ld returned 1 exit status
GNUmakefile:786: recipe for target 'cryptest.exe' failed
make: *** [cryptest.exe] Error 1
ERROR: failed to make cryptest.exe
```

I'll need to get that cleaned up.

**Comment by noloader** [comment]
OK, ARMv8-a `PMULL` was missing a guard. It was added at [Commit b2693c4327c8](https://github.com/weidai11/cryptopp/commit/b2693c4327c89f0d5c43d7050833ff95d6d7015c).

The ARMv7-a NEON code is still bent. I'm looking at it now.

By the way, if you need an ARMv8 machine, then you can (1) buy one or (2) use the GCC compile farm. For (1) LeMaker HiKey and Pine64 are good choices. They are inexpensive dev-boards with the optional Crypto. In contrast, RPI3's are ARMv8, but they lack the optional Crypto. Avoid RPI3 for testing.

For (2), you should sign up for a [GCC Compile Farm](https://gcc.gnu.org/wiki/CompileFarm) account. Hosts `gcc113.fsffrance.org` through `gcc118.fsffrance.org` are ARMv8. GCC113-GCC116 _lack_ the optional Crypto. GCC117 and GCC118 have the optional Crypto.

If you decide for the compile farm account, then it takes 6 to 9 months to get approved. The admins seem to batch requests and approve a group of them at once.

**Comment by anonimal** [comment]
>By the way, if you need an ARMv8 machine

Thanks for the info! We have an ARMv8 machine in our arsenal but it's currently offline/being swapped out. Another ARMV8 would be good to have regardless.

>b2693c4
>c079abd

Fixed! Thank you @noloader.

[cryptest-result_armv7l-rev2.txt](https://github.com/weidai11/cryptopp/files/1265055/cryptest-result_armv7l-rev2.txt)
[cryptest-result_armv7l-rev4.txt](https://github.com/weidai11/cryptopp/files/1265056/cryptest-result_armv7l-rev4.txt)

**Comment by noloader** [comment]
> Thanks for the info! We have an ARMv8 machine in our arsenal but it's currently offline/being swapped out. Another ARMV8 would be good to have regardless.

I tell you what... Send me you SSH public key. I'll add it to my authorized_keys file and see if you can log-in and test under the account.

My account was obtained for the Crypto++ project, and not for me as an individual. As long as you comply with the farm's rules, like open source only and and no more than half cpu cores, we should be OK.

**Comment by anonimal** [comment]
>As long as you comply with the farm's rules, like open source only and and no more than half cpu cores, we should be OK.

Excellent! No problem, will do. Thank you.

**Comment by anonimal** [comment]
Hi @noloader I've sent two emails, did they get through? I'm getting `Permission denied (publickey)` so I'm wondering if you ever received the emails or if something else is amiss.

**Comment by noloader** [comment]
> I'm wondering if you ever received the emails or if something else is amiss.

It looks like the emails are not getting through.

I found three messages in spam, but they were older. They were not the ones with the SSH key.

Can you add it as a comment here?

**Comment by anonimal** [comment]
JFTR: @noloader and I have resolved this internally. Thanks again, @noloader.
