### ISSUE TITLE
cryptopp Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by boaerosuke** [weidai11/cryptopp#488]
cryptopp gives an error if it installed with macports or brew on a mac 10.12.5.
The error says Undefined symbols for architecture x86_64. There is also a deprecation hint regarding libstdc++

How can I rebuild the source in order to let it use libc++ instead of libstdc++?

```
err: clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
Undefined symbols for architecture x86_64:

"CryptoPP::HashFilter::HashFilter(CryptoPP::HashTransformation&, CryptoPP::BufferedTransformation*, bool, int, std::string const&, std::string const&)", referenced from:
      _main in test.cpp.1.o

...
ld: symbol(s) not found for architecture x86_64
```

**Comment by noloader** [comment]
> err: clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9

Please show a typical compile command. While you are at it, you may as well you how you are going to link.

**Comment by noloader** [comment]
@boaerosuke,

Is there anything else we can help with here?

**Comment by noloader** [comment]
Closing. I don't think there's a Crypto++ bug here.
