### ISSUE TITLE
CentOS 6.6 x64 make error

### ISSUE THREAD

**Issue by yokarno** [weidai11/cryptopp#494]
I make cryptopp 5.6.5 on CentOS 6.6 x64, but always show error below: 

```
g++ -DNDEBUG -g2 -O2 -fPIC -march=native -pipe -c cryptlib.cpp
In file included from cryptlib.cpp:19:
misc.h: In function ‘unsigned int CryptoPP::TrailingZeros(CryptoPP::word32)’:
misc.h:680: error: ‘_tzcnt_u32’ was not declared in this scope
misc.h: In function ‘unsigned int CryptoPP::TrailingZeros(CryptoPP::word64)’:
misc.h:711: error: ‘_tzcnt_u64’ was not declared in this scope
misc.h: In function ‘bool CryptoPP::IsPowerOf2(const T&) [with T = unsigned int]’:
misc.h:821: error: ‘_blsr_u32’ was not declared in this scope
misc.h: In function ‘bool CryptoPP::IsPowerOf2(const T&) [with T = long unsigned int]’:
misc.h:828: error: ‘_blsr_u64’ was not declared in this scope
make: *** [cryptlib.o] Error 1
```

Can anyone tell me how to resolve it ? thanks .

**Comment by noloader** [comment]
> Can anyone tell me how to resolve it ? thanks .

I think the problem here is kind of a new trend. We usually see it on OpenBSD VMs, where they have newer hardware and compilers but an ancient GPL-2 linker.

According to Intel at their [Intrinsic Guide](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_tzcnt_u32), the header for `_tzcnt_u32` is `<immintrin.h>`. We guard based on `__BMI__`, so everything is good on our end.

For now open `misc.h`, move down to [around line 70](https://github.com/weidai11/cryptopp/blob/master/misc.h#L69) and delete the problematic block.

You might also be able to add `-mno-bmi` to your `CXXFLAGS`.

**Comment by yokarno** [comment]
Thanks @noloader

I'm not taking classes with Guozht together, it's just a mere coincidence. I just want to use cryptopp on different system

 I have solved the errors on CentOS 6.6 , but on CentOS 5.8 x86, it shows the error below:

g++ -DNDEBUG -g2 -O3 -DCRYPTOPP_DISABLE_SSE4 -pthread -pipe -c cpu.cpp
In file included from cpu.h:38,
                 from cpu.cpp:12:
/usr/lib/gcc/i386-redhat-linux/4.1.2/include/emmintrin.h:34:3: error: #error "SSE2 instruction set not enabled"

do you have any suggestion about this ?

**Comment by noloader** [comment]
```
g++ -DNDEBUG -g2 -O3 -DCRYPTOPP_DISABLE_SSE4 -pthread -pipe -c cpu.cpp
In file included from cpu.h:38,
                 from cpu.cpp:12:
... emmintrin.h:34:3: error: #error "SSE2 instruction set not enabled"
```

Yeah, this is our bug. No SSE4 does not mean no SSE2.

It does not show up on CentOS 5 x86_64 because SSE2 is part of the core instruction set. On i586 it is optional.

I'm going to need a little time to clear this.

**Comment by noloader** [comment]
@yokarno,

Would you try the following patch?

```
$ git diff
diff --git a/GNUmakefile b/GNUmakefile
index 0d9bb02..1882b6f 100755
--- a/GNUmakefile
+++ b/GNUmakefile
@@ -198,6 +198,11 @@ endif  # -DCRYPTOPP_DISABLE_SSSE3
 endif  # -DCRYPTOPP_DISABLE_ASM
 endif  # CXXFLAGS

+ifeq ($(findstring -DCRYPTOPP_DISABLE_ASM,$(CXXFLAGS)),)
+  ifeq ($(IS_X86),1)
+    CPU_FLAG = -msse2
+  endif
+endif
 ifeq ($(findstring -DCRYPTOPP_DISABLE_SSSE3,$(CXXFLAGS)),)
   HAVE_SSSE3 = $(shell echo | $(CXX) -x c++ $(CXXFLAGS) -mssse3 -dM -E - 2>/dev/null | $(GREP) -i -c __SSSE3__)
   ifeq ($(HAVE_SSSE3),1)
@@ -940,6 +945,10 @@ aria-simd.o : aria-simd.cpp
 blake2-simd.o : blake2-simd.cpp
        $(CXX) $(strip $(CXXFLAGS) $(BLAKE2_FLAG) -c) $<

+# SSE2 on i586
+cpu.o : cpu.cpp
+       $(CXX) $(strip $(CXXFLAGS) $(CPU_FLAG) -c) $<
+
 # SSE4.2 or ARMv8a available
 crc-simd.o : crc-simd.cpp
        $(CXX) $(strip $(CXXFLAGS) $(CRC_FLAG) -c) $<
```

**Comment by noloader** [comment]
The change tested OK under Debian 8 i686 (which is not exactly CentOS 5 i586) and Fedora 24 x86_64.

Also see [Commit 502fdc61c908](https://github.com/weidai11/cryptopp/commit/502fdc61c908).

**Comment by yokarno** [comment]
Yes , I got it and it works, but still have other file need to add -msse2, I have upload the file(changed the extension name for upload).
I also found that if I use the last version (the whole code package) before you committed GNUmakefile today, it works OK.

[GNUmakefile.txt](https://github.com/weidai11/cryptopp/files/1297931/GNUmakefile.txt)

**Comment by noloader** [comment]
@yokarno,

I'm setting up a CentOS 5.5 i586 machine now. I should have more results shortly.
