### ISSUE TITLE
AssignFromHelperClass is horrible

### ISSUE THREAD

**Issue by jwakely** [weidai11/cryptopp#5]
The uses of Hack_DefaultValueFromConstReferenceType and Hack_GetValueIntoConstReference are undefined behaviour, and quite foul.

If the VC60 workaround is still needed (VC6 in 2015, really?) the sane way to do it would be:

	typename decay<R>::type value;
	if (!m_source.GetValue(name, value))
		throw InvalidArgument(std::string(typeid(T).name()) + ": Missing required parameter '" + name + "'");
	(m_pObject->*pm)(value);

with the following added as private members of `AssignFromHelperClass`:

	template <class R> struct decay { typedef R type; };
	template <class R> struct decay<const R&> { typedef R type; };

If you really must support VC6 then do it with `#if` not by using the same horrible code for compilers that aren't totally broken.

**Comment by jwakely** [comment]
If VC6 support isn't needed it's probably simpler to just change the type of the `pm` argument to `void (T::*)(const R&)` and then `R` is already the object type and you don't need the `decay` trait to extract the object type from the reference type.

**Comment by noloader** [comment]
Jonathan, can you provide a quick patch with the proposed changes?

I've surveyed folks on dropping support for older platforms, and there is consensus the ancient workarounds can go. That includes VC 5.0 and 6.0 support. We're still not clear on where to draw the line, but VC 5.0/6.0 clearly falls outside it.
