### ISSUE TITLE
CpuId

### ISSUE THREAD

**Issue by phy0292** [weidai11/cryptopp#501]
Sorry, I write these you may seem very difficult, because I use the Chinese, in the use of Google translated into English.

In __BORLANDC__, if there is __asm in the function, it looks like everything is normal when it is compiled in debug mode. However, when compiled in the release mode, the function parameters and local variable positioning are completely wrong because of optimization.
So join __declspec (naked)
And completely by their own control and determine the location of parameters and local variables. as follows:
---------------------
#ifdef __BORLANDC__
__declspec( naked ) bool CpuId(word32 func, word32 subfunc, word32 output[4])
{
	__asm
	{
		push ebp
		mov ebp, esp
		push ebx
		push edi
		mov eax,[ebp + 8]	//func
		mov ecx,[ebp + 12]	//subfunc
		cpuid
		mov edi, [ebp + 16]	//output
		mov [edi], eax
		mov [edi+4], ebx
		mov [edi+8], ecx
		mov [edi+12], edx
		pop edi
		pop ebx
		pop ebp
		mov eax, 1
		ret
	}
}
#else
#endif

**Comment by noloader** [comment]
@phy0292,

There's a preview tab you can use to view the formatting of the bug reports before you submit them. (If that's the reason for the double submit).
