### ISSUE TITLE
Cmake Compile Error

### ISSUE THREAD

**Issue by Guozht** [weidai11/cryptopp#505]
```
[root@localhost Crytppp]# make
[  1%] Building CXX object CMakeFiles/cryptopp-object.dir/cryptlib.cpp.o
In file included from /root/Desktop/cryptopp-CRYPTOPP_5_6_5/cryptlib.cpp:19:
/root/Desktop/cryptopp-CRYPTOPP_5_6_5/misc.h: In function ‘unsigned int CryptoPP::TrailingZeros(CryptoPP::word32)’:
/root/Desktop/cryptopp-CRYPTOPP_5_6_5/misc.h:680: error: ‘_tzcnt_u32’ was not declared in this scope
/root/Desktop/cryptopp-CRYPTOPP_5_6_5/misc.h: In function ‘unsigned int CryptoPP::TrailingZeros(CryptoPP::word64)’:
/root/Desktop/cryptopp-CRYPTOPP_5_6_5/misc.h:711: error: ‘_tzcnt_u64’ was not declared in this scope
/root/Desktop/cryptopp-CRYPTOPP_5_6_5/misc.h: In function ‘bool CryptoPP::IsPowerOf2(const T&) [with T = unsigned int]’:
/root/Desktop/cryptopp-CRYPTOPP_5_6_5/misc.h:821: error: ‘_blsr_u32’ was not declared in this scope
/root/Desktop/cryptopp-CRYPTOPP_5_6_5/misc.h: In function ‘bool CryptoPP::IsPowerOf2(const T&) [with T = long unsigned int]’:
/root/Desktop/cryptopp-CRYPTOPP_5_6_5/misc.h:828: error: ‘_blsr_u64’ was not declared in this scope
make[2]: *** [CMakeFiles/cryptopp-object.dir/cryptlib.cpp.o] Error 1
make[1]: *** [CMakeFiles/cryptopp-object.dir/all] Error 2
make: *** [all] Error 2
[root@localhost Crytppp]# 
```

**Comment by Guozht** [comment]
@noloader **Can you help me**

**Comment by noloader** [comment]
Two things here.

First, CMake is a failed experiment and we are in the process of removing it. You should not use it. Instead, use the `GNUmakefile` on Unix & Linux; or use the Visual Studio project files on Windows.

Second, it looks like your assembler is too old to assemble the BMI instructions. You should update your assembler or stop using `-march=native`.

Please refer back to your previous bug reports. You have already been told these things. If you need additional help, then ask on the mailing list. Stop asking questions in the library's issue tracker.

**Comment by noloader** [comment]
Last call for CMake patches before removing it from the library and adding it to the patch page. If you have something to add, then now is the time to do it.

Also see [Remove CMake from GitHub; add it to Patch Page on wiki?](https://groups.google.com/forum/#!topic/cryptopp-users/PKlz8-ClXOU) and [Commit 1c740b0a097aecaa](https://github.com/weidai11/cryptopp/commit/1c740b0a097aecaa66044036c0d2c54220eda5d5).
