### ISSUE TITLE
Remove CMake from library sources

### ISSUE THREAD

**Issue by noloader** [weidai11/cryptopp#506]
This is a change control item. It tracks removal of CMake from the GitHub sources.

CMake is no longer supported by the project. CMake is still available on the wiki at [CMake](https://www.cryptopp.com/wiki/CMake). It is now maintained by the community.

The reasons for the removal can be found at [CMake Removal](https://www.cryptopp.com/wiki/CMake#CMake_Removal) on the CMake wiki page.

**Comment by noloader** [comment]
Completed.

**Comment by anonimal** [comment]
🎉 🎈 🎂 

Successful removal of the tumor 🤣
