### ISSUE TITLE
Verify conformance with FIPS 186-4, Change Notice, Item 5

### ISSUE THREAD

**Issue by noloader** [weidai11/cryptopp#51]
Reference [FIPS 186-3 Change Notice (2-28-12)](http://csrc.nist.gov/groups/ST/toolkit/documents/FIPS186-3_ChangeNotice041012.pdf). From 5, *Processing Step Error in the Secret Number Generation for ECDSA*:

> In Appendices B.5.1 and B.5.2, processing step 1 (i.e., N = len(q)) is incorrect. This change notice specifies the following change to step 1: “N = len(n),” ; i.e., “q” is changed to “n”
>
> This change may be significant if the cofactor is greater than one; for the NIST-recommended curves, the cofactor is one, so in this case, both values produce the same value for N.

A cofactor of 2 and 4 are common. Crypto++ optionally operates on ANSI X9.62 and WTLS curves, and some of them have a cofactor that is quite large. The curves are optional because its a [free community patch](https://cryptopp.com/wiki/Object_Identifiers).

**Comment by DevJPM** [comment]
Am 30.10.2015 um 22:54 schrieb Jeffrey Walton:
>
> Reference FIPS 186-3 Change Notice (2-28-12)
> <http://csrc.nist.gov/groups/ST/toolkit/documents/FIPS186-3_ChangeNotice041012.pdf>:
>
> From 5, /Processing Step Error in the Secret Number Generation for ECDSA/
>
>     In Appendices B.5.1 and B.5.2, processing step 1 (i.e., N =
>     len(q)) is incorrect. This change notice specifies the following
>     change to step 1: “N = len(n),” ; i.e., “q” is changed to “n”
>
>     This change may be significant if the cofactor is greater than
>     one; for the NIST-recommended curves, the cofactor is one, so in
>     this case, both values produce the same value for N.
>
Done.
We're not affected / have already mitigated.
See for reference:
https://groups.google.com/d/msg/cryptopp-users/ZcRXQvlpIAo/-uqv9HeKBgAJ

**Comment by noloader** [comment]
Thanks JPM.
