### ISSUE TITLE
ECIES is deprecated

### ISSUE THREAD

**Issue by chfast** [weidai11/cryptopp#510]
In v5.6.5 I'm getting the warning that ECIES struct has been deprecated. Is there any replacement?

**Comment by noloader** [comment]
@chfast,

> In v5.6.5 I'm getting the warning that ECIES struct has been deprecated. Is there any replacement?

Yes, see [`ECIES`](https://www.cryptopp.com/docs/ref/struct_e_c_i_e_s.html) in the manual.

Switching to Master might be a good idea, too. The 5.6.5 release is about a year old and it has a bunch of bug fixes, including 2 minor CVEs. Master is 6.0 and generally stable with an occasional break. We usually catch the breaks quickly.

You can also find the mailing list at [Crypto++ User Group](https://groups.google.com/forum/#!forum/cryptopp-users).

**Comment by chfast** [comment]
I packaged cryptopp for Hunter package manager: https://docs.hunter.sh/en/latest/packages/pkg/cryptopp.html.

It is bad practice there to have unreleased versions of packages there. Can you make any release soon? Can be beta-like.

**Comment by noloader** [comment]
@chfast,

If you are a packager/maintainer, then email me at *noloader, gmail account*. You can email me directly in the future. I'll also provide my home and cell numbers in case you need to talk.

You can also file bugs and use the mailing list. But as a packager/maintainer you get the extra benefits if you want them.

> Can you make any release soon?

Yeah, I want to release 6.0 soon. I have three tasks left. First is finishing some Power8 crypto. Second is ed25519 signatures. Third is OCB mode.
