### ISSUE TITLE
Create CRYPTOPP_NO_CPU_FEATURE_PROBES to disable SIGILL probes

### ISSUE THREAD

**Issue by anonimal** [weidai11/cryptopp#511]
As suggested in https://github.com/monero-project/kovri/issues/699, though I'm unsure of the scope (any/all SIGILL probing?).

**Comment by noloader** [comment]
Cleared at [Commit 6102333fc3c1](https://github.com/weidai11/cryptopp/commit/6102333fc3c1c73c8c5b05e7cd568ac681741c9d).

**Comment by anonimal** [comment]
Thank you! 👍

**Comment by anonimal** [comment]
Note: this apparently doesn't resolve monero-project/kovri#699. Will post there.

**Comment by anonimal** [comment]
Update: https://github.com/weidai11/cryptopp/commit/6102333fc3c1c73c8c5b05e7cd568ac681741c9d resolved this issue but the remaining implementation issue was caused by (shockingly, and no one could have predicted this) ...CMake! Referencing https://github.com/monero-project/kovri/issues/699#issuecomment-330942786.

**Comment by anonimal** [comment]
Referencing https://github.com/weidai11/cryptopp/issues/506#issuecomment-330387539.
