### ISSUE TITLE
mac GNUmakefile-cross distclean is some unknown action

### ISSUE THREAD

**Issue by owen200008** [weidai11/cryptopp#514]
in distclean it have the rm -rf $(DOCUMENT...) it will delete other application data but it have no permission so it will show a lot of message. is it normal?

**Comment by noloader** [comment]
That's from the `make docs` recipe in the regular `GNUmakefile`. It should not be present in `GNUmakefile-cross`. Cleared at [Commit 69a40e992ccd](https://github.com/weidai11/cryptopp/commit/69a40e992ccd)
