### ISSUE TITLE
Add OCB mode

### ISSUE THREAD

**Issue by noloader** [weidai11/cryptopp#515]
This is a change control item. We will use it to track the addition of OCB mode.

**Comment by noloader** [comment]
We are deferring on the cut-in at the moment. The implementation is rather messy. We will re-open once we cleanup the implementation.

Also see [OCB with 128-bit block sizes coming down the pike](https://groups.google.com/forum/#!topic/cryptopp-users/alCrCcPKv3A) on the mailing list.

**Comment by deknos** [comment]
OCB3 is also not patented anymore and provides AEAD as far as i know. please implement this

**Comment by Ou7law007** [comment]
@noloader 
I'm also here for OCB3/1.
There's even a wiki page for it and it specifies a header file "#include <cryptopp/ocb.h>" https://www.cryptopp.com/wiki/OCB_Mode

Inside "Modes of Operation", up top, it says that OCB is available and in the bottom it says in production, understandable but I can't find the header file anywhere! https://www.cryptopp.com/wiki/Modes_of_Operation

I remember looking for OCB inside these same docs about a year ago, it was also the same thing, so I'm not sure if that's a mistake or not.
