### ISSUE TITLE
CMake throws exception because of undefined reference in CryptoPP

### ISSUE THREAD

**Issue by Azer0s** [weidai11/cryptopp#516]
I am getting this error:

    CMakeFiles/Athena.dir/Startup/main.cpp.o: In function `CryptoPP::ClonableImpl<CryptoPP::BlockCipherFinal<(CryptoPP::CipherDir)0, CryptoPP::Rijndael::Enc>, CryptoPP::Rijndael::Enc>::ClonableImpl()':
    /home/dev/workspace/Athena/lib/cryptopp/simple.h:26: undefined reference to `CryptoPP::Rijndael::Enc::Enc()'
    collect2: error: ld returned 1 exit status
    CMakeFiles/Athena.dir/build.make:434: recipe for target 'Athena'

when I try to link CryptoPP to my programm.

This is my CMakeLists.txt:

    cmake_minimum_required(VERSION 3.8)
    project(Athena)
    
    set(CMAKE_CXX_STANDARD 17)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pthread -fpermissive -Wno-deprecated -Wno-int-to-pointer-cast -Wno-deprecated-declarations")
    
    include_directories(lib/SQLiteCpp/include)
    add_subdirectory(lib/SQLiteCpp)
    
    include_directories(lib/cryptopp)
    add_subdirectory(lib/cryptopp)
    
    include_directories(lib/json/src)
    add_subdirectory(lib/json)
    
    set(SOURCE_FILES
        Startup/main.cpp)
    
    add_executable(Athena ${SOURCE_FILES})
    target_link_libraries(Athena SQLiteCpp sqlite3 pthread dl cryptopp)

Here are my includes:

```cpp
#include "modes.h" // For CTR_Mode
#include "filters.h" //For StringSource
#include "aes.h" // For AES

```

I already tried linking cryptopp by find_package, by find_library and I even tried writing a script to download and make cryptopp manually. I am really out of ideas and I´m also pretty sure that it´s not my code (I pasted in an example from the cryptopp wiki).

**Comment by noloader** [comment]
Crypto++ does not support CMake. We have Makefile and MSBuild files so there's no reason to have CMake try to recreate them. Also see [CMake](https://www.cryptopp.com/wiki/CMake) on the wiki.

You should build Crypto++ with the [Makefile](https://www.cryptopp.com/wiki/GNUmakefile) or [MSBuild](https://www.cryptopp.com/wiki/MSBuild_(Command_Line)), and then use CMake's `ExternalProject_Add`.

The mailing list is located at [Crypto++ Users](https://groups.google.com/forum/#!topic/cryptopp-users/os_HzBmPDNs). Please ask questions on the mailing list.

**Comment by Azer0s** [comment]
Thanks for the quick response! Could you explain how I'd do said things?
