### ISSUE TITLE
Google Group is down

### ISSUE THREAD

**Issue by noloader** [weidai11/cryptopp#519]
Google is displaying a "Banned Content" for our group at http://groups.google.com/forum/#!forum/cryptopp-users. We don't know why it was banned or how to fix it. Google did not tell us what was wrong or the offending content; and they did not tell us how to fix it. The group's messages in my Inbox are not offensive by any stretch of the imagination.

We have been through Google's Help Pages, followed some articles and then submitted feedback in the "No, this did not help" box. We also tried to contact Google though their Contacts page. But I doubt that's going to be enough to fix the problem. Google is using those endless-labyrinth-of-webpages-that-lead-to-nowhere to avoid us talking to someone or getting real help from the company.

I've opened a question on the Web Apps stack exchange at [How to view list of offensive items in Banned Google Group?](https://webapps.stackexchange.com/q/110690/72479) It attempts to gather more information about what is going on and how to fix it since Google is not providing information or a contact to learn more.

If anyone has a contact at Google so we can actually talk to someone or really report the problem, then please email me at ***noloader, gmail*** account.

**Comment by denisbider** [comment]
In my experience, when Google stops liking you for any arbitrary reason, including a bug or oversight, remedies are difficult to come around. If you've been paying them $$$$, they might have some kind of customer support. Buy if you're a casual user, you can consider yourself f-ed.

Google's whole business model is built on everything being handled by systems, and them having as little personal interaction with anyone as possible. It's not that they don't want you to *reach* their support, it's that they don't *have* support that could be reached.

**Comment by noloader** [comment]
It looks like out mailing list was restored sometime around late Wednesday night (OCT 11, 2017) or early Thursday morning (OCT 12, 2017).

Closing.
