### ISSUE TITLE
Borland and "E2268 Call to undefined function log"

### ISSUE THREAD

**Issue by noloader** [weidai11/cryptopp#520]
From [Problem building Crypto++ with C++Builder XE5 - EMBARCADERO - RAD Studio 12.0](https://groups.google.com/forum/#!topic/cryptopp-users/QGJNGD-2Pgs):

> ```
> nbtheory.cpp(1026,90): error E2268: E2268 Call to undefined function 'log'
> nbtheory.cpp(1033,90): error E2268: E2268 Call to undefined function 'log' 
> 
> [bcc32 Fatal Error] adhoc.cpp(1): F1009 Unable to open input file 'adhoc.cpp'
>  
> [TLIB Warning] Warning: library was too large for page size, rebuilt with page size 1024
> ```
> 
> But I got a lot of errors when I build the .exe
> 
> ```
> [bcc32 Error] bench1.cpp(64): E2268 Call to undefined function 'log'
> [bcc32 Error] bench1.cpp(100): E2268 Call to undefined function 'log'
> [bcc32 Warning] bench1.cpp(407): W8012 Comparing signed and unsigned values
> [bcc32 Error] factory.h(104): E2040 Declaration terminated incorrectly
> [bcc32 Error] factory.h(105): E2451 Undefined symbol 's_registry'
> [bcc32 Error] factory.h(105): E2357 Reference initialized with 'undefined', needs lvalue of type 'ObjectFactoryRegistry<RandomNumberGenerator,0>'
> [bcc32 Error] factory.h(104): E2040 Declaration terminated incorrectly
> [bcc32 Error] factory.h(105): E2451 Undefined symbol 's_registry'
> [bcc32 Error] factory.h(105): E2357 Reference initialized with 'undefined', needs lvalue of type 'ObjectFactoryRegistry<NIST_DRBG,0>'
> [bcc32 Error] factory.h(104): E2040 Declaration terminated incorrectly
> [bcc32 Error] factory.h(105): E2451 Undefined symbol 's_registry'
> [bcc32 Error] factory.h(105): E2357 Reference initialized with 'undefined', needs lvalue of type 'ObjectFactoryRegistry<HashTransformation,0>'
> [bcc32 Error] factory.h(104): E2040 Declaration terminated incorrectly
> [bcc32 Error] factory.h(105): E2451 Undefined symbol 's_registry'
> [bcc32 Error] factory.h(105): E2357 Reference initialized with 'undefined', needs lvalue of type 'ObjectFactoryRegistry<AuthenticatedSymmetricCipher,0>'
> [bcc32 Error] factory.h(104): E2040 Declaration terminated incorrectly
> [bcc32 Error] factory.h(105): E2451 Undefined symbol 's_registry'
> [bcc32 Error] factory.h(105): E2357 Reference initialized with 'undefined', needs lvalue of type 'ObjectFactoryRegistry<MessageAuthenticationCode,0>'
> [bcc32 Error] factory.h(104): E2040 Declaration terminated incorrectly
> [bcc32 Error] factory.h(105): E2451 Undefined symbol 's_registry'
> [bcc32 Error] factory.h(105): E2357 Reference initialized with 'undefined', needs lvalue of type ObjectFactoryRegistry<SymmetricCipher,0>'
> ```

**Comment by noloader** [comment]
No more feedback. Closing.

**Comment by tanzislam** [comment]
I'm still getting the compilation errors in `nbtheory.cpp` (regarding the use of `::log()`) in the latest master using `bcc32.exe`:

>**bcc32.exe -DCRYPTOPP_DISABLE_ASM -DCRYPTOPP_NO_CXX11 nbtheory.cpp**

```
Embarcadero C++ 7.30 for Win32 Copyright (c) 1993-2017 Embarcadero Technologies, Inc.
nbtheory.cpp:
Warning W8041 misc.h 738: Negating unsigned value in function TrailingZeros(unsigned int)
Warning W8012 nbtheory.cpp 79: Comparing signed and unsigned values in function TrialDivision(const Integer &,unsigned int)
Warning W8012 nbtheory.cpp 83: Comparing signed and unsigned values in function TrialDivision(const Integer &,unsigned int)
Warning W8012 misc.h 563: Comparing signed and unsigned values in function CryptoPP::bool SafeConvert<int,unsigned int>(int,unsigned int &)
Warning W8066 nbtheory.cpp 507: Unreachable code in function MihailescuProvablePrime(RandomNumberGenerator &,unsigned int)
Error E2268 nbtheory.cpp 1024: Call to undefined function 'log' in function FactoringWorkFactor(unsigned int)
Error E2268 nbtheory.cpp 1031: Call to undefined function 'log' in function DiscreteLogWorkFactor(unsigned int)
*** 2 errors in Compile ***
```


This also happens using the Clang-based `bcc32c.exe`:

>**bcc32c.exe -DCRYPTOPP_DISABLE_ASM -DCRYPTOPP_NO_CXX11 nbtheory.cpp**

```
Embarcadero C++ 7.30 for Win32 Copyright (c) 2012-2017 Embarcadero Technologies, Inc.
nbtheory.cpp:
nbtheory.cpp:1024:77: error: no member named 'log' in the global namespace
  ...(unsigned int)(2.4 * std::pow((double)n, 1.0/3.0) * std::pow(::log(doubl...
                                                                  ~~^
nbtheory.cpp:1031:77: error: no member named 'log' in the global namespace
  ...(unsigned int)(2.4 * std::pow((double)n, 1.0/3.0) * std::pow(::log(doubl...
                                                                  ~~^
2 errors generated.
```

In the Google Groups message thread, Jeffrey Walton [suggested](https://groups.google.com/d/msg/cryptopp-users/QGJNGD-2Pgs/3cNYp2PLAQAJ) adding:

```cpp
#ifdef __BORLANDC__
    using std::log
#endif
```

I was able to resolve the issue with that (plus a `;` at the end of the `using`-declaration) and removing the `::` from the `::log` to make it an unqualified lookup (which should be safe because all current callers of `::log()` provide a `double` argument type, same as `log()` in C).
