### ISSUE TITLE
Does the #error directive in cryptopp/dll.h apply to non-windows systems?

### ISSUE THREAD

**Issue by guneemwelloeux** [weidai11/cryptopp#523]
Hello,

Creating a translation unit (via abi-compliance-checker https://lvc.github.io/abi-compliance-checker/) of all the header files from cryptopp yields the following error:

abicc includes all headers in the same source file, in an apparently non-deterministic order, and this is the main reason for this error.

From there, there are 2 solutions that I can think of:
- Remove the dll.h altogether from the binary+headers package I provide (only for Linux-based systems anyways, so I don't really care about this header)
- Patch the header to only trigger the error on Windows systems.

Since the error message mentions DLLs, I imagine that it only applies to Windows-based systems. Is that a correct assumption?
If so, shouldn't the inclusion of the file be subject to a check of the target OS of the build (ifdef WIN32, or something similar)?

I am attaching the log file from ABICC where one can see the contents of the compiled file, as well as the command line for compiling it.
[log1.txt](https://github.com/weidai11/cryptopp/files/1418992/log1.txt)

**Comment by noloader** [comment]
Please forgive my ignorance. What is the bug that's being reported?

**Comment by guneemwelloeux** [comment]
The issue is that the dll.h header, if included on Linux, will raise a complication error, while the DLL concept is a Windows only thing. In my opinion this shouldn't be the case.
