### ISSUE TITLE
Setting CXXFLAGS on command line prevents Makefile from adding -fPIC

### ISSUE THREAD

**Issue by etremel** [weidai11/cryptopp#525]
I recently attempted to download and install Crypto++ 5.6.5 onto my Ubuntu 16.04 system using the directions provided in Readme.txt and Install.txt. However, if I specify CXXFLAGS on the command line when invoking `make`, as recommended in Install.txt, the build fails because `-fPIC` was not included in the compiler flags. It seems like setting the CXXFLAGS variable on the command line prevents Crypto++'s Makefile from adding any flags to it, rather than simply overwriting the default "starting" flags as is intended.

Specifically, I tried doing the following, based on the recommendation under "If you want to build using C++11" in Install.txt:

    make CXXFLAGS="-std=c++11" static dynamic cryptest.exe

The terminal output printed many lines of the form 

    g++ -std=c++11 -c cryptlib.cpp
    g++ -std=c++11 -c cpu.cpp
    g++ -std=c++11 -c integer.cpp

indicating that `-std=c++11` was the *only* compiler flag being applied, then eventually failed with 

    /usr/bin/ld: cryptlib.o: relocation R_X86_64_32 against `.bss' can not be used when making a shared 
    object; recompile with -fPIC
    cryptlib.o: error adding symbols: Bad value
    collect2: error: ld returned 1 exit status

However, if I just call `make static dynamic cryptest.exe`, I see output lines of this form:

    g++ -DNDEBUG -g2 -O2  -fPIC -march=native -pipe -c cryptlib.cpp
    g++ -DNDEBUG -g2 -O2  -fPIC -march=native -pipe -c cpu.cpp 
    g++ -DNDEBUG -g2 -O2  -fPIC -march=native -pipe -c integer.cpp

showing that in addition to the default flags `-DNDEBUG -g2 O2`, the Makefile was able to add `-fPIC` and other flags. The build then completes successfully, which is not surprising since `/usr/bin/ld` recommended compiling again with `-fPIC`.

Notes: I'm using GNU Make 4.1, gcc/g++ 7.2, and running 64-bit Ubuntu 16.04.

**Comment by noloader** [comment]
> if I specify CXXFLAGS on the command line when invoking make, as recommended in Install.txt, the build fails because -fPIC was not included in the compiler flags.
>
>     make CXXFLAGS="-std=c++11" static dynamic cryptest.exe

This is GNU make behavior. When `CXXFLAGS` is to the right of the `make` command, then GNU's make does not allow us to modify a variable. If you place `CXXFLAGS` is to the left of the `make` command, then `make` allows us to change it (its just another defined variable).

It has something to do with user choice and freedoms.

**Comment by noloader** [comment]
We added additional examples at [Commit 6fb90f2b0c83](https://github.com/weidai11/cryptopp/commit/6fb90f2b0c831315d52a69388231fceef8532413).

**Comment by etremel** [comment]
Thanks for clarifying this; I didn't know about that important distinction in where `make` variables are set. The new examples in Install.txt are much better, since they make it clear that the "normal" case is to set the `CXXFLAGS` variable before the `make` invocation, while setting it on the right side is a special case that will override all the Makefile's choices.

**Comment by noloader** [comment]
@etremel,

That applies to all Make variables, and not just `CXXFLAGS` or `CFLAGS`. Also see Make's [Catalogue of Rules](https://www.gnu.org/software/make/manual/html_node/Catalogue-of-Rules.html#Catalogue-of-Rules). It lists a bunch of variables a makefile can augment or you can override.
