### ISSUE TITLE
Linker warning due to global weak symbol access when using -fvisibility=hidden

### ISSUE THREAD

**Issue by triplef** [weidai11/cryptopp#526]
I’m compiling cryptopp as a static library using clang on macOS with `-fvisibility=hidden` and the `visibility ("default")` attribute as [explained in the Wiki](https://www.cryptopp.com/wiki/Debug_Symbols#Symbol_visibility). The target application linking the library is also using hidden symbol visibility. This fixed most linker warnings due to visibility mismatch, however I am still getting the following warnings when linking:

```
ld: warning: direct access in function 'CryptoPP::GetValueHelperClass<CryptoPP::DL_PublicKey<CryptoPP::ECPPoint>, CryptoPP::DL_PublicKey<CryptoPP::ECPPoint> >::GetValueHelperClass(CryptoPP::DL_PublicKey<CryptoPP::ECPPoint> const*, char const*, std::type_info const&, void*, CryptoPP::NameValuePairs const*)' from file 'libcryptopp.a(dll.o)' to global weak symbol 'typeinfo name for CryptoPP::DL_PublicKey<CryptoPP::ECPPoint>' from file 'myclass.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'CryptoPP::GetValueHelperClass<CryptoPP::DL_PublicKey<CryptoPP::ECPPoint>, CryptoPP::DL_PublicKey<CryptoPP::ECPPoint> >::GetValueHelperClass(CryptoPP::DL_PublicKey<CryptoPP::ECPPoint> const*, char const*, std::type_info const&, void*, CryptoPP::NameValuePairs const*)' from file 'libcryptopp.a(dll.o)' to global weak symbol 'typeinfo name for CryptoPP::DL_PublicKey<CryptoPP::ECPPoint>' from file 'myclass.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'bool CryptoPP::NameValuePairs::GetThisObject<CryptoPP::DL_PublicKey<CryptoPP::ECPPoint> >(CryptoPP::DL_PublicKey<CryptoPP::ECPPoint>&) const' from file 'libcryptopp.a(dll.o)' to global weak symbol 'typeinfo for CryptoPP::DL_PublicKey<CryptoPP::ECPPoint>' from file 'myclass.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'bool CryptoPP::NameValuePairs::GetThisObject<CryptoPP::DL_PublicKey<CryptoPP::ECPPoint> >(CryptoPP::DL_PublicKey<CryptoPP::ECPPoint>&) const' from file 'libcryptopp.a(dll.o)' to global weak symbol 'typeinfo name for CryptoPP::DL_PublicKey<CryptoPP::ECPPoint>' from file 'myclass.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
```

The code compiled to "myclass.o" above is using the following imports from cryptopp:

```
#include <cryptopp/filters.h>
#include <cryptopp/osrng.h>
#include <cryptopp/eccrypto.h>
#include <cryptopp/ecp.h>
#include <cryptopp/base64.h>
#include <cryptopp/base32.h>
#include <cryptopp/sha.h>
#include <cryptopp/hex.h>
```

I assume the above warnings are due to missing `CRYPTOPP_DLL` attributes for some classes or functions, but I’ve been unable to track down the right classes/functions. I’d very much appreciate any help to fix these warnings. Thank you!

**Comment by noloader** [comment]
`CRYPTOPP_DLL` applies to the [FIPS DLL on Windows](https://www.cryptopp.com/wiki/FIPS_DLL). All symbols are exported from the shared object on Linux.

If you want to try to use symbol visibility, then you should add `CRYPTOPP_DLL` where you need it.

**Comment by triplef** [comment]
According to the following article in the wiki, `CRYPTOPP_DLL` can also be used to make symbols public on other platforms:
https://www.cryptopp.com/wiki/Debug_Symbols#Symbol_visibility (c.f. last paragraph)

My issue is that I cannot seem to track down the right symbols to make visible based on the warnings above. Any help would be appreciated.

**Comment by noloader** [comment]
> My issue is that I cannot seem to track down the right symbols to make visible based on the warnings above.

Sorry, I don't know. I've never experienced the issue. You might take a look at some of the template defines in [`config.h` : 840](https://github.com/weidai11/cryptopp/blob/master/config.h#L839) or so.

If you want something that has a reduced footprint, then *don't* use the Crypto++ shared object. It has all symbols because nothing can be discarded by the linker.

To reduce a footprint, you should provide a wrapper shared object that offers your API. Adorn your API with `MYLIB_DLL` and provide the visibility. Then, link to the static version of the Crypto++ library. Compile the Crypto++ library and your program with `-ffunction-sections` and `-fdata-sections`. Finally, link with `-Wl,--gc-sections` or `-Wl,-dead_strip` to tell the linker to discard unused symbols.

Also see ['make lean' target?](https://groups.google.com/d/msg/cryptopp-users/SaORS7dHSZ0/xBcCGs5cEQAJ) on the mailing list. It went through most of the exercise; but it used a program instead of a shared object.

**Comment by triplef** [comment]
Thank you! Using `make lean` fixed the issue.
