### ISSUE TITLE
aes.h double semicolon

### ISSUE THREAD

**Issue by vgfl** [weidai11/cryptopp#532]
aes.h contains:

DOCUMENTED_TYPEDEF(Rijndael, AES);

Which expands into something ending in two ';'.

gcc 7.2.0 -Wall -Wextra hates it...

Thanks,

Vincent

**Comment by noloader** [comment]
Cleared at [Commit d28e813ac36b](https://github.com/weidai11/cryptopp/commit/d28e813ac36b12ec269c69fff528744f0cfe4738).
