### ISSUE TITLE
Why doesn't this give correct result

### ISSUE THREAD

**Issue by kenkit** [weidai11/cryptopp#534]
```
std::string decoded2;
std::string first_20="1ACC64E9510C32CE8E34";

StringSource ssv(first_20, true /*pumpAll*/,
    new HexDecoder(
        new StringSink(decoded2)
    ) // HexDecoder
); // StringSource
boost::algorithm::to_lower(decoded2);

StringSource ss( decoded2, true,

    new Base32Encoder(
        new StringSink(hash_sink)
    ) // Base64Decoder
); // StringSource
std::cout<<"encoded raw:"<<hash_sink<<std::endl;
//I get  "DMGGJ4MTBS3N7DTW" which is wrong
//instead of "DLGGJ2KRBQZM5DRU"
```

**Comment by denisbider** [comment]
Which exact version of Base32 do you expect Crypto++ to implement? Does it actually implement that version?

If there is a discrepancy, what are the arguments in favor of implementing the version you want it to implement?

**Comment by kenkit** [comment]
I thought the same version is compatible with  pythons  `base64.b32encode(sys.stdin.readline().strip('\n').decode('hex')).lower()`

**Comment by denisbider** [comment]
Is that an expectation you had prior to testing, and seeing it's not the same Base32? (In that case, it's a design choice that could be argued.) Or is it an expectation you had after studying the implementation?

There are many versions of Base32. None of them seems like obviously the best one.

**Comment by kenkit** [comment]
I'm working on something and I thought the functions were the same, aren't they ?
If they are not atleast it's good to know that I should find another way to decode the value.
I'm new to crypto. I don't intend you to implement a new decoder, maybe point me to the right direction if you can. Thanks in advance

**Comment by kenkit** [comment]
if you know of a way I can do that or a function, I will be very happy as I've come so far, that code is the only thing that has me stuck on my project.I use crytopp in all of my projects have never tried other libs for cryptography.

**Comment by denisbider** [comment]
You can initialize the Crypto++ Base32 implementation to use a different alphabet than the default. If you need help with that, see:

https://github.com/weidai11/cryptopp/blob/master/base32.h#L45

In general, usage questions should go to the Crypto++ mailing list:

https://www.cryptopp.com/#lists

GitHub issues are for reports of issues with the library. Closing.
