### ISSUE TITLE
More semicolons to remove for gcc-7.2.0 -pedantic compatibility

### ISSUE THREAD

**Issue by vgfl** [weidai11/cryptopp#537]
/usr/local/cryptopp565/filters.h:1000:64: error: extra ';' [-Wpedantic]
 DOCUMENTED_TYPEDEF(StringSinkTemplate<std::string>, StringSink);
                                                                ^
/usr/local/cryptopp565/filters.h:1284:46: error: extra ';' [-Wpedantic]
 DOCUMENTED_TYPEDEF(StringSource, ArraySource);

Please remove the final semicolons in the distrib. Thanks!
Vincent

**Comment by noloader** [comment]
Cleared at [Commit 32154a150faa](https://github.com/weidai11/cryptopp/commit/32154a150faa).
