### ISSUE TITLE
Add SM3 hash function

### ISSUE THREAD

**Issue by noloader** [weidai11/cryptopp#541]
SM3 is a Chinese national hash function. See [SM3 Hash function](https://tools.ietf.org/html/draft-shen-sm3-hash). We recently received some private emails asking for several Chinese algorithms. The email also pointed out US and some European algorithms have good coverage in the library.

**Comment by noloader** [comment]
Cleared at [Commit 5267723a4923](https://github.com/weidai11/cryptopp/commit/5267723a4923)

**Comment by hanlulugeren** [comment]
Hope CryptoPP better.
