### ISSUE TITLE
Compilation error with g++: impossible register constraint in ‘asm’

### ISSUE THREAD

**Issue by EduardoMiravalls** [weidai11/cryptopp#554]
Hello, I'm experiencing a compilation error with master, `commit `1a7f19cdde7c84c88f96c5a5125447a9f4df0025.

I've tried dropping to `-O2`  as suggested in #553 but it does not fix the error.

I just compiled with `make `and the compilation aborted in `gcm-simd.cpp`. Here is the error

```
$ make
g++ -DNDEBUG -g2 -O3 -fPIC -DCRYPTOPP_DISABLE_SHA -pthread -pipe -mssse3 -mpclmul -c gcm-simd.cpp
gcm-simd.cpp: In function ‘void CryptoPP::GCM_Xor16_SSE2(CryptoPP::byte*, const CryptoPP::byte*, const CryptoPP::byte*)’:
gcm-simd.cpp:442: error: impossible register constraint in ‘asm’
gcm-simd.cpp:448: error: impossible register constraint in ‘asm’
make: *** [gcm-simd.o] Error 1
```

I'm running Red-Hat 6.7 and the compilers I have are

```
$ as --version
GNU assembler version 2.20.51.0.2-5.43.el6 20100205
Copyright 2009 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or later.
This program has absolutely no warranty.
This assembler was configured for a target of `x86_64-redhat-linux'.
```

```
$ g++ --version
g++ (GCC) 4.4.7 20120313 (Red Hat 4.4.7-16)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
$ ld --version
GNU ld version 2.20.51.0.2-5.43.el6 20100205
Copyright 2009 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
```

Thank you.

**Comment by noloader** [comment]
> `error: impossible register constraint in ‘asm’`

Yeah, I've seen that before. Here's the ASM. There's not much to it. Below is from [`gc,-simd.cpp`](https://github.com/weidai11/cryptopp/blob/master/gcm-simd.cpp#L435):

```
#if CRYPTOPP_SSE2_INTRIN_AVAILABLE || CRYPTOPP_SSE2_ASM_AVAILABLE
// SunCC 5.10-5.11 compiler crash. Move GCM_Xor16_SSE2 out-of-line, and place in
// a source file with a SSE architecture switch. Also see GH #226 and GH #284.
void GCM_Xor16_SSE2(byte *a, const byte *b, const byte *c)
{
# if CRYPTOPP_SSE2_ASM_AVAILABLE && defined(__GNUC__)
    asm ("movdqa %1, %%xmm0; pxor %2, %%xmm0; movdqa %%xmm0, %0;"
         : "=m" (a[0]) : "xm"(b[0]), "xm"(c[0]));
# else  // CRYPTOPP_SSE2_INTRIN_AVAILABLE
    _mm_store_si128(M128_CAST(a), _mm_xor_si128(
        _mm_load_si128(CONST_M128_CAST(b)),
        _mm_load_si128(CONST_M128_CAST(c))));
# endif
}
#endif
```

The constraint it is talking about is the part ` : "=m" (a[0]) : "xm"(b[0]), "xm"(c[0]));`. The `x` is a SSE register, and the `m` is memory. I wonder if two memory expressions is giving the older tool chain problems. Or maybe, the toolchain wants the output constraint to be `xm`.

Give me some time to find a machine with GCC 4.4. I think I have one somewhere.

**Comment by EduardoMiravalls** [comment]
Great, thanks.

I believe CentOS 6 comes with gcc 4.4.7, maybe you can use it in a vm?

**Comment by noloader** [comment]
OK, going back to [Wei's code](https://github.com/weidai11/cryptopp/blob/789f81f048c9bc472c7e7596f49b02eadd6fc1fd/gcm.cpp#L63) before we started fiddling with things:

```
asm ("movdqa %1, %%xmm0; pxor %2, %%xmm0; movdqa %%xmm0, %0;" : "=m" (a[0]) : "m"(b[0]), "m"(c[0]));
```

I was able to duplicate it with CentOS 5 (Binutils 2.17). This clears the issue under CentOS:

```
: "=xm" (a[0]) : "m"(b[0]), "m"(c[0]));
```

I'm going to check-in the one shown above with output operand of `xm`. The GCC folks tell us to provide GCC with as many alternatives as possible, so we are consistent with their best practices.

**Comment by noloader** [comment]
Cleared at [Commit 9c80a706c871](https://github.com/weidai11/cryptopp/commit/9c80a706c871).

**Comment by noloader** [comment]
Ugh, this broke GCC 4.8/4.9 on Core2's:

```
g++ -DDEBUG -g3 -O0 -fPIC -pthread -pipe -D_GLIBCXX_DEBUG -c gcm.cpp
gcm-simd.cpp: In function ‘void CryptoPP::GCM_Xor16_SSE2(CryptoPP::byte*, const byte*, const byte*)’:
gcm-simd.cpp:448:1: internal compiler error: Max. number of generated reload insns per insn is achieved (90)

 }
 ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
```

**Comment by EduardoMiravalls** [comment]
Mind if I ask why did it specifically affect Core2s?
FYI, I've just pulled your latest commits and it compiles OK on my setup.

**Comment by noloader** [comment]
> Mind if I ask why did it specifically affect Core2s?

The Core2 machine is what I have for testing on real hardware. The issue probably affects other machines, too. It is likely tied to a few versions of Binutils, which supplies the assembler.
