### ISSUE TITLE
Enable compiler warnings

### ISSUE THREAD

**Issue by EduardoMiravalls** [weidai11/cryptopp#555]
Hello CryptoPP mantainers: maybe it's already been answered already, but I haven't found it anywhere: why does CyproPP's makefile not enable compiler warnings?

Some header files give warnings If I `#include` them, mostly signed and unsigned comparisons.
I've seen that you have started fixing warnings in commit 5f083d652e4fb9698e0e22d3629311749d4142a6 and commit ba98c2bfb92eedd541622a2d904a6d4b35b5dd71 in the code,  but if you compile the library with `-Wall ` I still get a lot of warnings.

I don't know if all compilers support `-Wall`, so maybe simply adding `CXXFLAGS += -Wall` may break the compilation for some environments, but at least both `g++ ` and `clang `support that option.

Thank you, and happy new year!

**Comment by noloader** [comment]
> I haven't found it anywhere: why does CyproPP's makefile not enable compiler warnings?

[`cryptest.sh`](https://github.com/weidai11/cryptopp/blob/master/cryptest.sh) performs the testing that can generate a lot of noise. It uses `-Wall`, `-Wextra` and others. Search the script for the word "elevated".

> I've seen that you have started fixing warnings

It is an on-going effort.

> Some header files give warnings ...

If you have specific instances we can fix them.

**Comment by EduardoMiravalls** [comment]
Thanks for your quick response. I agree that some warnings are very verbose and pollute the compile logs, that's why I'm trying to fix them.

> If you have specific instances we can fix them.

Well, I don't know if they are fixed in master, but at least from version 5.6.5 I get a warning in line 218 of `seckey.h`

```
libs/cryptopp565/seckey.h: In static member function ‘static size_t CryptoPP::VariableKeyLength<D, N, M, Q, IV_REQ, IV_L>::StaticGetValidKeyLength(size_t) [with unsigned int D = 16u, unsigned int N = 0u, unsigned int M = 2147483647u, unsigned int Q = 1u, unsigned int IV_REQ = 4u, unsigned int IV_L = 0u]’:
libs/cryptopp565/seckey.h:304:   instantiated from ‘size_t CryptoPP::SimpleKeyingInterfaceImpl<BASE, INFO>::GetValidKeyLength(size_t) const [with BASE = CryptoPP::HMAC_Base, INFO = CryptoPP::HMAC<CryptoPP::SHA256>]’
libs/cryptopp565/seckey.h:218: warning: comparison of unsigned expression < 0 is always false
```

Without c++11 support, the only work around I found is the one I give in this SO answer https://stackoverflow.com/a/47871053 , but I don't know if it works for all compilers.

**Comment by noloader** [comment]
>  but at least from version 5.6.5 I get a warning in line 218 of seckey.h

You should consider working from Master. It is mostly stable with an occasional break. We usually catch the breaks quickly.

Master also has lots of new algorithms, and almost all hardware acceleration we can find. I'm working on Power8 SHA at the moment.

> Without c++11 support, the only work around I found is the one I give in this SO answer https://stackoverflow.com/a/47871053

Yeah, I'm familiar with those. Clang has `-Wno-tautological-compare` but GCC gas nothing.

In modern compilers we control it with:

```
// Issue 340
#if CRYPTOPP_GCC_DIAGNOSTIC_AVAILABLE
# pragma GCC diagnostic push
# pragma GCC diagnostic ignored "-Wconversion"
# pragma GCC diagnostic ignored "-Wsign-conversion"
#endif

...

// Issue 340
#if CRYPTOPP_GCC_DIAGNOSTIC_AVAILABLE
# pragma GCC diagnostic pop
#endif
```

Unfortunately, from my notes in `config.h`:

```
// Need GCC 4.6/Clang 1.7/Apple Clang 2.0 or above due to "GCC diagnostic {push|pop}"
#if (CRYPTOPP_GCC_VERSION >= 40600) || (CRYPTOPP_LLVM_CLANG_VERSION >= 10700) || (CRYPTOPP_APPLE_CLANG_VERSION >= 20000)
	#define CRYPTOPP_GCC_DIAGNOSTIC_AVAILABLE 1
#endif
```

So we are not going to be able to help with GCC 4.4 or 4.5.

**Comment by noloader** [comment]
Related, our VM with the website and wiki is CentOS 7. We enable SCL ports so we can get Python 2.7 and PHP 7. Maybe you can do similar with Red Hat and update the compiler to GCC 4.6 so `pragma GCC diagnostic {push|pop}` is available.

**Comment by EduardoMiravalls** [comment]
Ok, I'll have a look at that, thanks.

**Comment by noloader** [comment]
@EduardoMiravalls,

If I were wearing your shoes, then I would take this approach to testing. It is kind of needed because of that old compiler and the library's inability to easily manage warnings. Since we can't easily manage them we side step the issue with older compilers.

Setup another VM with something more modern. Maybe Debian 8 or Fedora 26 or CentOS 7. Then, run your testing on the newer platform. You can  crank up warnings like you want. You also have access to the sanitizers. Test everything under the newer platform and know that it applies to older platforms.

And to be clear, there are some warnings we live with but suppress. Uri (@mouse07410 ) wants to clear them but we usually spend resources on more interesting things, like fixing bugs and Power8 AES or SHA. As a compromise we used pragmas to manage them.

**Comment by noloader** [comment]
@EduardoMiravalls,

Is there anything else we can do here? If not, can we close it?

**Comment by EduardoMiravalls** [comment]
Yeah, thank you.
