### ISSUE TITLE
How to generate AES key if I can't use std::byte since I can't use C++17?

### ISSUE THREAD

**Issue by zavodnyrichard** [weidai11/cryptopp#556]
Hi. I want cross-compile my project, that use CryptoPP using [MXE](http://mxe.cc/) (MinGW). The problem is **std::byte**, which is C++17 functionality. Since MXE only supports C++11 I need some alternative.

The key generation and encryption looks something like this:
```
byte key[32];
randomGenerator.GenerateBlock(key, sizeof(key));

CryptoPP::StringSource keyToString(key, sizeof(key), true, new CryptoPP::StringSink(aesKey));
CryptoPP::AES::Encryption aesEncryptor((byte*)aesKey.c_str(), aesKey.length());
```

But I'm getting lot of errors, that obviously mean, that compiler can't understand what "byte" is and mark it as undefined reference.

**Comment by noloader** [comment]
Please see [std::byte](https://www.cryptopp.com/wiki/std::byte) on the Crypto++ wiki.
