### ISSUE TITLE
Minor debug text output issue - duplicated 0x in pointer values

### ISSUE THREAD

**Issue by jmccabe** [weidai11/cryptopp#557]
This is fairly trivial, but I thought I'd mention it anyway.
Where pointer values are being put into the oss ostringstream in fipstest.cpp, the output has two lots of 0x (at least, it does when built with MinGW). For example:

```
Crypto++ DLL integrity check may fail. Expected module base address is **0x0x**42900000, but module loaded at **0x0x**63500000.
```

The issue is that std::hex used on a pointer value already includes the 0x, but the code in fipstest.cpp adds the 0x into the debug string too, e.g.

```
std::ostringstream oss;
oss << "Crypto++ DLL integrity check may fail. Expected module base address is 0x";
oss << std::hex << g_BaseAddressOfMAC << ", but module loaded at 0x" << h << ".\n";
OutputDebugStringA(oss.str().c_str());
```
This can be replicated using a really simple test program, built with mingw:

```
#include <iostream>
int main() {

    const void* g_BaseAddressOfMAC = reinterpret_cast<void*>(0x42900000);
    std::cout << std::hex << "0x" << g_BaseAddressOfMAC << std::endl;

    const int* ptr = reinterpret_cast<int*>(100);
    const int val = 100;
    std::cout << std::hex << "0x" << ptr << std::endl;
    std::cout << std::hex << "0x" << val << std::endl;
    return 0;
}
```

Output is:

0x0x42900000
0x0x64
0x64

I did say trivial, but maybe someone would like to check and/or fix it when it's convenient.

**Comment by noloader** [comment]
Thanks @jmccabe, 

I never paid it much mind. Do you want to make a PR, or do you want us to clear it?

**Comment by jmccabe** [comment]
Hi, you're welcome. I'm easy; I could do a PR if you think that would be best, but i haven't got the facilities to make sure it works as expected with a non-mingw tool chain, so it may be better for someone more well equipped and familiar to just throw it in at some convenient time. Hope that's OK.
John

**Comment by noloader** [comment]
@jmccabe,

OK, thanks. Let me run through [MSBuild (Command Line) | Building FIPS DLL](https://www.cryptopp.com/wiki/MSBuild_(Command_Line)#Building_FIPS_DLL) and see what the output looks like.

**Comment by noloader** [comment]
@jmccabe,

I think what happened is, it has been a cosmetic bug for years. Using MSBuild things work as expected so I don't get to see the [incorrect] message. It basically flew under the radar.

I'll just clear it by removing the unneeded `0x` prefix. At worse a hex output will be missing the prefix which won't affect base16 readability. But double prefix is like a dagger in the eye.

Thanks again.

**Comment by noloader** [comment]
Cleared at [Commit bfc2b5f02d2b](https://github.com/weidai11/cryptopp/commit/bfc2b5f02d2b).
