### ISSUE TITLE
LeakSanitizer crash on Travis

### ISSUE THREAD

**Issue by noloader** [weidai11/cryptopp#564]
Our [Travis Asan test is now failing](https://travis-ci.org/noloader/cryptopp/jobs/328664087). The failure first surfaced at [Build #722](https://travis-ci.org/noloader/cryptopp/builds/328664082). It uses Clang 5.0 on Linux.

```
...
Testing KDF algorithm HKDF(SHA-1).
....
Testing KDF algorithm HKDF(SHA-256).
...
Testing KDF algorithm HKDF(SHA-512).
.....
Testing KDF algorithm HKDF(Whirlpool).
.....
Tests complete. Total tests = 7751. Failed tests = 0.
==2871==LeakSanitizer has encountered a fatal error.
==2871==HINT: For debugging, try setting environment variable LSAN_OPTIONS=verbosity=1:log_threads=1
==2871==HINT: LeakSanitizer does not work under ptrace (strace, gdb, etc)
```

-----

Here are the build system details.

```
Build system information
Build language: cpp
Build group: stable
Build dist: trusty
Build id: 328664082
Job id: 328664087
Runtime kernel version: 4.14.12-041412-generic
travis-build version: d08e1022d
Build image provisioning date and time
Tue Dec  5 20:11:19 UTC 2017
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
Cookbooks Version
7c2c6a6 https://github.com/travis-ci/travis-cookbooks/tree/7c2c6a6
git version
git version 2.15.1
bash version
GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)
gcc version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
...
```

**Comment by noloader** [comment]
It just occurred to me... This is a Sanitizer crash. We don't have a finding and we can't fix it.

**Comment by Kojoley** [comment]
FYI: I was enabling ASAN on Travis builds for one of my repositories and stuck into the same problem, it looks like the cause is https://github.com/travis-ci/travis-ci/issues/9033.

**Comment by Kojoley** [comment]
I am sorry but there is no good fix and it is up for maintainer to decide how to deal with the issue.

There is three options:
  - Disable LSAN (`ASAN_OPTIONS=detect_leaks=0`).
  - Use Travis VM's instead of containers (`sudo: required`).
  - Pray that Travis team will return privileges so `ptrace` could be used again.
