### ISSUE TITLE
MinGW cannot compile the library due to missing symbol MinGW _hypot

### ISSUE THREAD

**Issue by noloader** [weidai11/cryptopp#57]
make
    ...
    g++ -DNDEBUG -std=c++03 -g3 -O1  -march=native -pipe -c nbtheory.cpp
    In file included from nbtheory.cpp:14:0:
    c:\mingw\include\math.h: In function 'float hypotf(float, float)':
    c:\mingw\include\math.h:635:30: error: '_hypot' was not declared in this scope
         { return (float)(_hypot (x, y)); }
                                  ^

**Comment by IlyaBizyaev** [comment]
I had same problem, and replaced _hypot with hypot.
But then, after some time, the problem disappeared, and I replaced it back :smile:

**Comment by noloader** [comment]
Thanks for the fix Ilya. I wanted to file a report in case other stumble upon it.
