### ISSUE TITLE
i686-w64-mingw32: sha-simd: error: inlining failed in call to always_inline '__m128i _mm_sha1nexte_epu32(__m128i, __m128i)'

### ISSUE THREAD

**Issue by anonimal** [weidai11/cryptopp#573]
Complete system/build information: https://build.getmonero.org/builders/kovri-all-win32/builds/768/steps/compile/logs/stdio

TL;DR: 

- Tag `CRYPTOPP_6_0_0`
- `i686-w64-mingw32`
- `gcc 6.2.0`
- `make CXXFLAGS="-march=native -DCRYPTOPP_NO_CPU_FEATURE_PROBES=1"   static`

```
In file included from C:/msys32/mingw32/lib/gcc/i686-w64-mingw32/6.2.0/include/immintrin.h:71:0,
                 from sha-simd.cpp:16:
C:/msys32/mingw32/lib/gcc/i686-w64-mingw32/6.2.0/include/shaintrin.h: In function 'void CryptoPP::SHA1_HashMultipleBlocks_SHANI(CryptoPP::word32*, const word32*, size_t, CryptoPP::ByteOrder)':
C:/msys32/mingw32/lib/gcc/i686-w64-mingw32/6.2.0/include/shaintrin.h:53:1: error: inlining failed in call to always_inline '__m128i _mm_sha1nexte_epu32(__m128i, __m128i)': target specific option mismatch
 _mm_sha1nexte_epu32 (__m128i __A, __m128i __B)
 ^~~~~~~~~~~~~~~~~~~
sha-simd.cpp:236:43: note: called from here
         E1 = _mm_sha1nexte_epu32(E1, MSG1);
                                           ^
```

**Comment by noloader** [comment]
Sounds like we are missing the `-msha` flag.

**Comment by anonimal** [comment]
From the shell:

```bash
$ echo $(echo | g++ -x c++ -march=native -DCRYPTOPP_NO_CPU_FEATURE_PROBES=1 -msse4.2 -msha -dM -E - 2>/dev/null | grep -i -c __SHA__)
1
```

```bash
$ echo $(g++ -xc -c /dev/null -Wa,-v -o/dev/null 2>&1 | grep -c "GNU assembler")
1
```

```bash
$ echo $(g++ -xc -c /dev/null -Wa,-v -o/dev/null 2>&1 | grep -c -E "GNU assembler version (2\.2[4-9]|2\.[3-9]|[3-9])")
1
```

**Comment by noloader** [comment]
@anonimal,

I'm wondering if the results you show above are similar to that one Android issue we worked on. In the Android issue I seem to recall a different shell was being used then we expected.

**Comment by coneiric** [comment]
@noloader I'm pretty new to make's internals, and not a windows dev, so please excuse any noobishness.

Could the problem be coming from the win32's shell and grep having a different behavior? 

Thinking something similar to the non-POSIX shell/grep used by Solaris from [GNUmakefile : 25](https://github.com/weidai11/cryptopp/blob/master/GNUmakefile#L25):
```
# Solaris provides a non-Posix shell at /usr/bin
ifneq ($(wildcard /usr/xpg4/bin),)
  GREP ?= /usr/xpg4/bin/grep
else
  GREP ?= grep
endif
```

or `SHELL` being set to `bash` here in [GNUmakefile : 5](https://github.com/weidai11/cryptopp/blob/master/GNUmakefile#L5):
```
# Must use Bash
SHELL = bash
```

The GNUmakefile docs recommend using `SHELL = /bin/sh` as a general convention in [section 16.1](https://www.gnu.org/software/make/manual/make.html#Makefile-Conventions), though I'm not sure that applies here. The relevant snippet:
```
Every Makefile should contain this line:

SHELL = /bin/sh

to avoid trouble on systems where the SHELL variable might be inherited from the environment. (This is never a problem with GNU make.) 
```

**Comment by noloader** [comment]
@coneiric,

> The GNUmakefile docs recommend using SHELL = /bin/sh as a general convention in section 16.1, though I'm not sure that applies here.

Yeah, this is one of those areas that confuses me with GNU philosophy. I thought the "freedom thing" meant we could do things like `SHELL=bash make -j 4`, but GNUmake does not seem to honor it.

I think we should be OK with the change:

```
$ git diff
diff --git a/GNUmakefile b/GNUmakefile
index 9e540d9..2cf7d8f 100755
--- a/GNUmakefile
+++ b/GNUmakefile
@@ -2,8 +2,9 @@
 #####        System Attributes and Programs           #####
 ###########################################################

-# Must use Bash
-SHELL = bash
+# https://www.gnu.org/software/make/manual/make.html#Makefile-Conventions
+SHELL = /bin/sh
+
 # If needed
 TMPDIR ?= /tmp
 # Used for ARMv7 and NEON.
```

It tested OK in my test environment. Mine includes Cygwin and MinGW, but I have not been able to duplicate the problems.

Is anyone available to test it on a misbehaving machine?

**Comment by noloader** [comment]
@coneiric, @anonimal ,

I added `SHELL = /bin/sh` as suggested at [Commit c16eddb40e3a](https://github.com/weidai11/cryptopp/commit/c16eddb40e3a). Lets see how it works out.

**Comment by anonimal** [comment]
>I added SHELL = /bin/sh as suggested at Commit c16eddb40e3a.

I now can't get past aria-simd compilation:

```
g++ -DNDEBUG -g2 -O3 -fPIC -pthread -pipe -c aria-simd.cpp
aria-simd.cpp: In function 'void CryptoPP::ARIA_ProcessAndXorBlock_Xor_SSSE3(const byte*, CryptoPP::byte*, const byte*, CryptoPP::word32*)':
aria-simd.cpp:122:76: warning: SSE vector return without SSE enabled changes the ABI [-Wpsabi]
  const __m128i MASK = _mm_set_epi8(12,13,14,15, 8,9,10,11, 4,5,6,7, 0,1,2,3);
                                                                            ^
In file included from C:/msys32/mingw32/lib/gcc/i686-w64-mingw32/6.2.0/include/pmmintrin.h:31:0,
                 from C:/msys32/mingw32/lib/gcc/i686-w64-mingw32/6.2.0/include/tmmintrin.h:31,
                 from aria-simd.cpp:14:
C:/msys32/mingw32/lib/gcc/i686-w64-mingw32/6.2.0/include/emmintrin.h:714:1: error: inlining failed in call to always_inline 'void _mm_storeu_si128(__m128i*, __m128i)': target specific option mismatch
 _mm_storeu_si128 (__m128i *__P, __m128i __B)
 ^~~~~~~~~~~~~~~~
aria-simd.cpp:144:65: note: called from here
    _mm_shuffle_epi8(_mm_load_si128(CONST_M128_CAST(rk)), MASK)));
                                                                 ^
In file included from C:/msys32/mingw32/lib/gcc/i686-w64-mingw32/6.2.0/include/pmmintrin.h:31:0,
                 from C:/msys32/mingw32/lib/gcc/i686-w64-mingw32/6.2.0/include/tmmintrin.h:31,
                 from aria-simd.cpp:14:
C:/msys32/mingw32/lib/gcc/i686-w64-mingw32/6.2.0/include/emmintrin.h:1286:1: error: inlining failed in call to always_inline '__m128i _mm_xor_si128(__m128i, __m128i)': target specific option mismatch
 _mm_xor_si128 (__m128i __A, __m128i __B)
 ^~~~~~~~~~~~~
aria-simd.cpp:142:18: note: called from here
  _mm_storeu_si128(M128_CAST(outBlock),
  ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
   _mm_xor_si128(_mm_loadu_si128(CONST_M128_CAST(outBlock)),
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    _mm_shuffle_epi8(_mm_load_si128(CONST_M128_CAST(rk)), MASK)));
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from C:/msys32/mingw32/lib/gcc/i686-w64-mingw32/6.2.0/include/pmmintrin.h:31:0,
                 from C:/msys32/mingw32/lib/gcc/i686-w64-mingw32/6.2.0/include/tmmintrin.h:31,
                 from aria-simd.cpp:14:
C:/msys32/mingw32/lib/gcc/i686-w64-mingw32/6.2.0/include/emmintrin.h:696:1: error: inlining failed in call to always_inline '__m128i _mm_loadu_si128(const __m128i*)': target specific option mismatch
 _mm_loadu_si128 (__m128i const *__P)
 ^~~~~~~~~~~~~~~
aria-simd.cpp:142:18: note: called from here
  _mm_storeu_si128(M128_CAST(outBlock),
  ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
   _mm_xor_si128(_mm_loadu_si128(CONST_M128_CAST(outBlock)),
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    _mm_shuffle_epi8(_mm_load_si128(CONST_M128_CAST(rk)), MASK)));
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from aria-simd.cpp:14:0:
C:/msys32/mingw32/lib/gcc/i686-w64-mingw32/6.2.0/include/tmmintrin.h:136:1: error: inlining failed in call to always_inline '__m128i _mm_shuffle_epi8(__m128i, __m128i)': target specific option mismatch
 _mm_shuffle_epi8 (__m128i __X, __m128i __Y)
 ^~~~~~~~~~~~~~~~
aria-simd.cpp:142:18: note: called from here
  _mm_storeu_si128(M128_CAST(outBlock),
  ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
   _mm_xor_si128(_mm_loadu_si128(CONST_M128_CAST(outBlock)),
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    _mm_shuffle_epi8(_mm_load_si128(CONST_M128_CAST(rk)), MASK)));
```

>$ echo $(g++ -xc -c /dev/null -Wa,-v -o/dev/null 2>&1 | grep -c -E "GNU assembler version (2\.2[4-9]|2\.[3-9]|[3-9])")
1

@noloader isn't this supposed to return 0? We're expecting 0 to enable `-DCRYPTOPP_DISABLE_SHA`, right?

**Comment by noloader** [comment]
>>      $ echo $(g++ -xc -c /dev/null -Wa,-v -o/dev/null 2>&1 | grep -c -E "GNU assembler version (2.2[4-9]|2.[3-9]|[3-9])")

> 
> @noloader isn't this supposed to return 0? We're expecting 0 to enable -DCRYPTOPP_DISABLE_SHA, right?

I think that is correct. Or at least it is correct on a few other machines.

We need Binutils 2.24 or above for SHA support. The expression with match `2.24`, `2.3x` and `3.x` (and above). Maybe that version of MinGW and BinUtils does not support SHA. Or maybe we are misdetecting GAS.

Debugging makefiles kind of sucks. About the best we have is `$(info $(var))`. After this block exectutes. Can you add this to your makefile after the variables are set:

```
$(info HAVE_GAS: $(HAVE_GAS))
$(info HAVE_GAS: $(GAS217_OR_LATER))
$(info HAVE_GAS: $(GAS218_OR_LATER))
$(info HAVE_GAS: $(GAS219_OR_LATER))
$(info HAVE_GAS: $(GAS224_OR_LATER))
```

**Comment by anonimal** [comment]
>Here is what I see on a modern Linux machine

Same here.

>Can you add this to your makefile after the variables are set. Somewhere around line 205 or 210 in the makefile

Strangely, I see no new output whatsoever.

**Comment by anonimal** [comment]
>We need Binutils 2.24 or above for SHA support.

```bash
$ pacman -Q mingw-w64-cross-binutils
mingw-w64-cross-binutils 2.25.1-1
```

**Comment by noloader** [comment]
> Strangely, I see no new output whatsoever.

That is weird. Is it the correct makefile? Are you using GNU make, or Posix make?

**Comment by anonimal** [comment]
>I also see it on my Cygwin and MinGW machines (which do not have the problem)

I can confirm on x86-64 that this produces the correct output.

What I did just notice now is version difference on x86-64:

```bash
$ pacman -Q mingw-w64-x86_64-binutils
mingw-w64-cross-binutils 2.28-2
```

Perhaps the win32 machine needs an upgrade? If so, then how could marcel reproduce? I'll do an upgrade and see where we stand.

**Comment by noloader** [comment]
@anonimal, @coneiric,

Could you use something like `$(info I'm HERE)` to get an idea where things are failing. Are we even entering the the block guarded with `ifneq ($(IS_X86)$(IS_X32)$(IS_X64),000)`? Or maybe, before the block, add:

```
$(info IS_X86: $(IS_X86))
$(info IS_X32: $(IS_X32))
$(info IS_X64: $(IS_X64))
```

It is an awful way to troubleshoot, but that's about all we have when debugging makefiles. It is what I have to use because `make -d` does not print line numbers or the statement being executed.

**Comment by noloader** [comment]
@anonimal,

I thought Pacman was a Arch or Gentoo package manager. What system are you working on?

I've been testing Cygwin and MinGW on Windows 7 and Windows 8. Maybe that is why I am having trouble duplicating it.

**Comment by anonimal** [comment]
>$(info IS_X86: $(IS_X86))
$(info IS_X32: $(IS_X32))
$(info IS_X64: $(IS_X64))

```
IS_X86: 0
IS_X32: 0
IS_X64: 0
```
>I thought Pacman was a Arch or Gentoo package manager.

[It features a package management system to provide easy installation of packages, Pacman.](http://www.msys2.org/)

>What system are you working on?

```bash
$ uname -a
MINGW32_NT-10.0 DESKTOP-7NB6IPI 2.6.0(0.304/5/3) 2016-09-07 21:23 i686 Msys
```

>Can you try dos2unix on GNUmakefile to see if it makes a difference?

No differences.

**Comment by noloader** [comment]
```
IS_X86: 0
IS_X32: 0
IS_X64: 0
```

That pushes us back to:

```
MACHINE := $(shell $(CXX) $(CXXFLAGS) -dumpmachine 2>/dev/null)
IS_X86 := $(shell echo "$(MACHINE)" | $(GREP) -v "64" | $(GREP) -i -c -E "i.86|x86|i86")
IS_X64 := $(shell echo "$(MACHINE)" | $(GREP) -i -c -E "(_64|d64)")
```

Do you feel like bisecting them?

**Comment by anonimal** [comment]
>Perhaps the win32 machine needs an upgrade?

The issue isn't resolved with a system update. The system was upgraded with https://github.com/monero-project/meta/issues/169 but now there are both `cross` and `i686` binutils packages on the system. I don't know if that could be related (see below).

>Do you feel like testing it to see what, exactly, is failing.

Yes. It's very slow for me to do testing because I can only RDP over Tor at the moment (no SSH either), otherwise I'd jump into issues like this quickly.

>$ gcc -dumpmachine 2>/dev/null
i686-pc-cygwin

```bash
$ gcc -dumpmachine 2>/dev/null
i686-w64-mingw32
```

Well this explains it: the problem being we're inverting against `64` in `w64` for x86 machines (which makes complete sense to do so, in a normal world). I don't know when mingw introduced `w64` in this context.

I'll test any patches you make which accommodate this new mingw "feature" as I don't want to break detection for other CPUs that I don't have access too.

**Comment by noloader** [comment]
I think we can special case MinGW like we do a few others:

```
$ git diff GNUmakefile
diff --git a/GNUmakefile b/GNUmakefile
index 2cf7d8f..0642d63 100755
--- a/GNUmakefile
+++ b/GNUmakefile
@@ -89,6 +89,11 @@ IS_X86 = 0
 IS_X64 = 0
 endif

+# Fixup MinGW
+ifeq ($(MACHINE),i686-w64-mingw32)
+IS_X86 := 1
+endif
+
 # Fixup SunOS
 ifeq ($(IS_SUN),1)
 IS_X86 := $(shell isainfo -k 2>/dev/null | $(GREP) -i -c "i386")
```

**Comment by noloader** [comment]
@anonimal, @coneiric,

I believe we cleared the misdetection at [Commit 69d5400b3fb0](https://github.com/weidai11/cryptopp/commit/69d5400b3fb0).

**Comment by anonimal** [comment]
Thank you @noloader, confirmed fix.

**Comment by loganblevins** [comment]
I've noticed this issue with building for iPhone Simulator using Xcode 9.4.1. Fortunately I was able to build for physical device (armv7|arm64) but cannot build for i386 or x86_64. 

Thoughts?

**Comment by noloader** [comment]
@loganblevins,

Apple removes the ISA from Xcode simulator builds. We have a tough time detecting the condition because an Xcode Simulator build looks like a regular i686 or x86_64 build.

For Simulator builds you will probably have to add `-DCRYPTOPP_DISABLE_SHA` manually.

**Comment by loganblevins** [comment]
@noloader Interesting, thanks for the quick reply. I noticed `-DCRYPTOPP_DISABLE_ASM` was in the iOS build script mentioned, although it seems I missed `-DCRYPTOPP_DISABLE_SHA`.

**Comment by noloader** [comment]
@loganblevins,

[Commit aa45eca5615a](https://github.com/weidai11/cryptopp/commit/aa45eca5615a) should clear the template warning. That was a recent change.

**Comment by loganblevins** [comment]
@noloader Looks like `-DCRYPTOPP_DISABLE_ASM` did the trick for simulator builds and recent change to master should clear many warnings. Thanks again for your help 🙂

**Comment by loganblevins** [comment]
@noloader Following up again on this - we're experiencing a linkage error with iPhoneSimulator11.4 for only i386 due to the need of compiler flag `-DCRYPTOPP_DISABLE_ASM`. 

```
Undefined symbols for architecture i386:
  "CryptoPP::AlignedDeallocate(void*)", referenced from:
      CryptoPP::AllocatorWithCleanup<unsigned char, true>::deallocate(void*, unsigned long) in lib<MyLib>.a(<MyLib>.cpp.1.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
INFO: clang++ exited with status 1
```

Linkage is successful with iPhoneSimulator11.4 for x86_64 and iPhoneOS11.4 arm64/armv7. It would be unfortunate to need to exclude i386 builds. Is there a known workaround for this architecture and SDK?

**Comment by noloader** [comment]
> Following up again on this - we're experiencing a linkage error with iPhoneSimulator11.4 for only i386 due to the need of compiler flag -DCRYPTOPP_DISABLE_ASM.

Yes, for the iOS simulators I believe we should build with `-DCRYPTOPP_DISABLE_ASM`. `CRYPTOPP_DISABLE_ASM` just means C++ code is used for the implementation. There's no need to build for a higher ISA like SSE4 or AES because the simulators don't need it, the simulators don't represent the hardware in the field, and we don't know what ISA's Apple is making available to them.

The devices are a different story. They should use the proper ISAs to support the hardware in the field.

**Comment by loganblevins** [comment]
@noloader Right - that's how I built i386 simulator. Although it will not link like the rest of the architectures. It seems that disabling ASM should correct this, although that isn't the case.

**Comment by noloader** [comment]
@loganblevins,

I think I am not fully understanding some of the interactions among the pieces and that's why you are still having trouble. My apologies for that.

Let me take you through the logic and maybe you can point out the sore spot. First, for the Android and iOS Simulators we don't want the ASM so we use `CRYPTOPP_DISABLE_ASM`.

When `CRYPTOPP_DISABLE_ASM` is in effect we hit this in `config.h` around line 790:

```
// Nearly all Intel's and AMD's have SSE. Enable it independent of SSE ASM and intrinscs
#if (CRYPTOPP_BOOL_X86 || CRYPTOPP_BOOL_X32 || CRYPTOPP_BOOL_X64 || CRYPTOPP_BOOL_PPC32 || CRYPTOPP_BOOL_PPC64) && !defined(CRYPTOPP_DISABLE_ASM)
	#define CRYPTOPP_BOOL_ALIGN16 1
#else
	#define CRYPTOPP_BOOL_ALIGN16 0
#endif
```

For the simulators `CRYPTOPP_BOOL_ALIGN16 == 0` so this declaration is never seen in `misc.h` around line 1385:

```
#if CRYPTOPP_BOOL_ALIGN16
CRYPTOPP_DLL void* CRYPTOPP_API AlignedAllocate(size_t size);
CRYPTOPP_DLL void CRYPTOPP_API AlignedDeallocate(void *ptr);
#endif // CRYPTOPP_BOOL_ALIGN16
```

And then the bodies are skipped in `misc.cpp` around line 280:

#if CRYPTOPP_BOOL_ALIGN16

void * AlignedAllocate(size_t size)
{
   ...
}

void AlignedDeallocate(void *p)
{
   ...
}

#endif // CRYPTOPP_BOOL_ALIGN16

That is the way things are supposed to happen.

Do you see where things are breaking down?

**Comment by loganblevins** [comment]
Yes - it appears the `config.h` is different in 5.6.5. Maybe that is the issue. We use 5.6.5 elsewhere so I reverted from 7.0.0 to 5.6.5.
