### ISSUE TITLE
Rollup of errata items to be fixed before release

### ISSUE THREAD

**Issue by noloader** [weidai11/cryptopp#58]
These are the issues we are aware that should be fixed prior to 5.6.3 release. They were reported after RC6 (give or take...). We are tracking them under a single bug report.

* Guard `CRYPTOPP_CXX11_ALIGNOF` on MSC `1900`
* `cryptest.exe tv all` does not run HKDF tests. Need to add `hkdf.txt` to `all.txt`.
* *"... to the ABI and ABI"* → *"... to the ABI and API"* in `Readme.txt`.
* MinGW and *`error: 'memcpy_s' was not declared in this scope`*.  Cleared with a `using CryptoPP::memcpy_s;`
* MinGW and `rdrand` detection. Investigating.
* Remove unneeded `-Wno-unused-function -Wno-unused-parameter -Wno-unused-variable` from `GNUmakefile-cross`.
* Change `GNUmakefile`'s `make docs` recipe to use `ref<Version>` as the output directory.
* Change `GNUmakefile`'s to avoid `-fPIC` for MinGW.
* Remove `CRYPTOPP_DISABLE_SHA_ASM` from `sha.h` and `sha.cpp`. Its an artifact from earlier testing.
* [Issue 64: PolynomialMod2::operator<<= Bug](http://github.com/weidai11/cryptopp/issues/64) - fixed the `reg.Grow(...)` logic
* [Issue 24: Compiler warnings on GCC and MinGW]() - cleared the longmp warning

**Comment by Zireael-N** [comment]
I don't think these two are worth a bug report of their own:

**misc.h** needs a `s/Desitnation/Destination/g` & `s/satsify/satisfy/g`:
[misc.h#L220](https://github.com/weidai11/cryptopp/blob/48809d4e85c125814425c621d8d0d89f95405924/misc.h#L220)
\+ the same comment in `memmove_s()` @ [L249](https://github.com/weidai11/cryptopp/blob/48809d4e85c125814425c621d8d0d89f95405924/misc.h#L249).

**Comment by noloader** [comment]
If those are the only two you found, then I'm happy :)

My spelling and grammar is horrible at times....

**Comment by Zireael-N** [comment]
Also noticed the need of `s/desination/destination/g` at [L207](https://github.com/weidai11/cryptopp/blob/48809d4e85c125814425c621d8d0d89f95405924/misc.h#L207), [L208](https://github.com/weidai11/cryptopp/blob/48809d4e85c125814425c621d8d0d89f95405924/misc.h#L208), [L236](https://github.com/weidai11/cryptopp/blob/48809d4e85c125814425c621d8d0d89f95405924/misc.h#L236) and [L237](https://github.com/weidai11/cryptopp/blob/48809d4e85c125814425c621d8d0d89f95405924/misc.h#L237).

I wasn't really looking for typos, it's just #28 made me spend a lot of time around `memcpy_s()`. :S

**Comment by noloader** [comment]
@Zireael-N, Have you spotted anything else that needs attention?

I'm getting ready to test RDRAND and RDSEED changes. Once they are successful, then the roll-up will be checked in.

**Comment by Zireael-N** [comment]
> Have you spotted anything else that needs attention?

No, I haven't.

**Comment by noloader** [comment]
Cleared at check-in d2fda9b

**Comment by noloader** [comment]
Cleared at check-in d2fda9b
