### ISSUE TITLE
Provide Conan package

### ISSUE THREAD

**Issue by Lyberta** [weidai11/cryptopp#581]
[Conan](https://www.conan.io/) is the most popular C++ package manager which allows libraries to be consumed very easily. It is build system agnostic so you can still build Crypto++ using Make but Conan will generate necessary glue for other build systems such as CMake.

You only need to create `conanfile.py` with instructions how to build and consume the library. The tutorial is [here](http://docs.conan.io/en/latest/creating_packages.html).

A stretch goal would be getting Crypto++ into [conan-center](https://bintray.com/conan/conan-center) which will allow all Conan users to install and use Crypto++ with just a few lines of code.

**Comment by noloader** [comment]
@Lyberta,

I don't know anything about Conan. If you supply a Pull Request then we can look into merging it.

Please make a PR, and ping me at *noloader, gmail* account. The email is in case we need to have a sidebar conversation.

**Comment by noloader** [comment]
I'm probably not going to have time for this request. If we get a PR in the future then we will resurrect this issue.
