### ISSUE TITLE
LINK : fatal error LNK1181: cannot open input file 'cryptlibd.lib'

### ISSUE THREAD

**Issue by bluetiger30** [weidai11/cryptopp#583]
System : WIndows 10 Home x64
Crypto++ : Crypto++ 6

I built the library using by running the cryptest.sln which was successful by using MS VS community 2017 15.5.6.

All what I want to do is to run the [CCM example file ](https://www.cryptopp.com/w/images/9/98/CCM-AE-Test.zip) which was provided [here ](https://www.cryptopp.com/wiki/CCM_Mode).

So I opened the project and added the path to V++ directories : 

![image](https://user-images.githubusercontent.com/35257997/35808664-6f414e20-0a7e-11e8-9401-354da9ecff55.png)

I also added the path here :
![image](https://user-images.githubusercontent.com/35257997/35809455-8e999622-0a80-11e8-84ce-77335704b360.png)

when building the project I get the following  error :

LINK : fatal error LNK1181: cannot open input file 'cryptlibd.lib'

I checked everywhere for cryptlibd.lib ( within the project, and the cryptopp600 directory ) , I only found cryptlib.lib (not cryptlibd.lib) in C:\Users\blue_\Downloads\cryptopp600\Win32\Output\Debug .

can you kindly tell me how to resolve this ? and why its asking for cryptlibd instead on cryptlib ?

**Comment by noloader** [comment]
Please ask questions on the [Crypto++ Mailing Lists](https://cryptopp.com/#lists).

The bug reporter is for bugs, not questions.
