### ISSUE TITLE
Compiler warning due to different string alignments in mqueue.cpp code

### ISSUE THREAD

**Issue by oPaveo** [weidai11/cryptopp#591]
I use Visual Studio 2017 (msvc15) under Windows 10 and Crypto++ 6.10.
I get the following linker warning:

```
Warning C4742: '`string'' has different alignment in '\cryptopp\mqueue.cpp' and 'foo\bar.cpp': 1 and 2
```

I know that is the Microsoft compiler problem and I reported it to them.
But I also know why It occures and there is a very simple way to avoid it.

In your code, in `mqueue.cpp` we have

`return Output(1, (const byte *)"\0", 1, 0, blocking) != 0;`

The string `"\0"` is actually a two-element array of two zero bytes - exactly the same as `L""`. So the problem is whether it is a 1-length char* or an empty wide string.

Maybe you can write
`return Output(1, (const byte *)"\0\0", 1, 0, blocking) != 0;`
or
`return Output(1, (const byte *)"", 1, 0, blocking) != 0;`

Both codes works the same way and without linker warnings.

P.S. Older versions of Crypto++ give the same effect, of course.

**Comment by noloader** [comment]
Thanks @oPaveo.

It looks like you are taking about this function:

```
bool EqualityComparisonFilter::HandleMismatchDetected(bool blocking)
{
	m_mismatchDetected = true;
	if (m_throwIfNotEqual)
		throw MismatchDetected();
	return Output(1, (const byte *)"\0", 1, 0, blocking) != 0;
}
```

And `Output` from [`filters.h`](https://github.com/weidai11/cryptopp/blob/master/filters.h#L87)

```
size_t Output(int outputSite, const byte *inString, size_t length, int messageEnd, bool blocking, const std::string &channel=DEFAULT_CHANNEL);
```

How do you feel about doing away with the string literal altogether. Maybe something like:

```
bool EqualityComparisonFilter::HandleMismatchDetected(bool blocking)
{
	m_mismatchDetected = true;
	if (m_throwIfNotEqual)
		throw MismatchDetected();

        // https://github.com/weidai11/cryptopp/issues/591
        const byte b[1] = {0};
	return Output(1, b, 1, 0, blocking) != 0;
}
```

**Comment by oPaveo** [comment]
Hello,
Your solution looks very well. I tested it and it is also warning free :-)
Thanks.

**Comment by noloader** [comment]
Thanks @oPaveo,

Do you want to make a PR, or would you like us to handle it?

**Comment by oPaveo** [comment]
I prefer to leave it to you.

**Comment by noloader** [comment]
Thanks again @oPaveo.

Cleared at [Commit 53ccd310b8b3](https://github.com/weidai11/cryptopp/commit/53ccd310b8b3).
