### ISSUE TITLE
cryptest: segfault which pointed to 'dynamic_cast'

### ISSUE THREAD

**Issue by shinchiro** [weidai11/cryptopp#593]
I'm cross-compiling `CRYPTOPP_6_1_0` tarball on mingw-w64. Everything compiled successfully. But when I try lauching cryptest.exe, it just give segfault at `dynamic_cast` which pointed to this file:
https://github.com/weidai11/cryptopp/blob/53ccd310b8b3ce1b1cc79d125b85420bfb7c8682/test.cpp#L154-L156

I compiled with gcc 7.3.0
```
CXX=x86_64-w64-mingw32-g++ CC=x86_64-w64-mingw32-gcc AR=x86_64-w64-mingw32-ar RANLIB=x86_64-w64-mingw32-ranlib make -j$(nproc)
```

**Comment by noloader** [comment]
Thanks @shinchiro.

The Linux on Windows gear gives us a fair amount of trouble. It is not tested as well as it should be, but I think the problem lies elsewhere for this one.

Can you show a typical compile command, and show the link command. The same basic options ar eused with all source files, so we only need to see one - like `cryptlib.cpp`. And a back trace might be helpful to see if `GlobalRNG()` is returning a `NULL` object.

If `GlobalRNG()` is returning `NULL` before the cast then it is probably [Static Initialization Order Fiasco](https://cryptopp.com/wiki/Static_Initialization_Order_Fiasco). We will need to look further to understand why.

**Comment by noloader** [comment]
Thanks @shinchiro. @MarcelRaad,

Have you experienced a similar issue on Windows with MinGW gear?

This looks unusual:

```
(gdb) bt full
#0  0x0000000000792717 in __dynamic_cast () at pubkey.h:255
...
```

That's because `pubkey.h : 255` is the return for `MaxPlaintextLength`:

```
template <class BASE>
class CRYPTOPP_NO_VTABLE PK_FixedLengthCryptoSystemImpl : public BASE
{
public:
	virtual ~PK_FixedLengthCryptoSystemImpl() {}

	size_t MaxPlaintextLength(size_t ciphertextLength) const
		{return ciphertextLength == FixedCiphertextLength() ? FixedMaxPlaintextLength() : 0;}
	size_t CiphertextLength(size_t plaintextLength) const
		{return plaintextLength <= FixedMaxPlaintextLength() ? FixedCiphertextLength() : 0;}

	virtual size_t FixedMaxPlaintextLength() const =0;
	virtual size_t FixedCiphertextLength() const =0;
};
```

**Comment by MarcelRaad** [comment]
Everything worked fine for me last time I ran the tests with MinGW-w64, but I tried only on Windows then.
@shinchiro You said you're cross-compiling. That's probably from Windows to Linux? What Linux distribution are you using?

**Comment by shinchiro** [comment]
This is getting weird. I managed to compile release 5.6.5 previously on gcc 7.2.0 (can run cryptest without crash) but now it's getting same crash as this which used gcc 7.3.0. Probably, there's regression in gcc 7.3 or mirror/mingw-w64@3f31320

Feel free to close this if it's become unrelated

**Comment by noloader** [comment]
@shinchiro,

> Feel free to close this if it's become unrelated

Ack, thanks. I don't want to do that just yet. I want to ensure we are not seeing [Static Initialization Order Fiasco](https://cryptopp.com/wiki/Static_Initialization_Order_Fiasco). I also want to ensure (1) `NO_VTABLE` is not causing problems for you, and (2) Undefined Behavior is not causing problems (like a missing virtual destructor somewhere).

**Comment by shinchiro** [comment]
Should note that this crash happen when compiled on AMD Ryzen. On other my intel haswell laptop, no crash happen. Both of them using gcc 7.2 & mingw-w64 (git)

**Comment by shinchiro** [comment]
Welp..finally I can confirm the segfault came from using binutils 2.30. With binutils 2.29.1, no segfault occured on my AMD Ryzen
