### ISSUE TITLE
Error: 'forward': use of dependent type name must be prefixed with 'typename'

### ISSUE THREAD

**Issue by mersadk** [weidai11/cryptopp#599]
I'm trying to include Crypto++ headers to my static lib project, but as soon as I include any of them I get an error during compiling.

> Error C7510 'forward': use of dependent type name must be prefixed with 'typename' in file secblock.h line 82.

I've downloaded Crypto++ 6.1 and use Visual Studio 2017 on Windows 10 x64.

**Comment by noloader** [comment]
Thanks @mersadk,

Well, that's a new one to me. Jonathon Wakely helped with that code several years ago. He is the GCC stdlibc++ maintainer.

Here is the signature:

```
template<typename U, typename... Args>
    void construct(U* ptr, Args&&... args) {::new ((void*)ptr) U(std::forward<Args>(args)...);}
```
 I'm guessing Visual Studio may want:

```
template<typename U, typename... Args>
    void construct(U* ptr, Args&&... args) {::new ((void*)ptr) U(std::forward<typename Args>(args)...);}
```

Can you test things to see what accommodates Visual Studio?

**Comment by mersadk** [comment]
@noloader 
That code didn't help, but it did help to turn off "Conformance mode" option in project properties (Project properties -> C/C++ -> Language).

As I'm more C# developer than C++ I'm not sure what is happening here, but I got the idea from this blog post, maybe it will make more sense to you: 
https://blogs.msdn.microsoft.com/vcblog/2016/11/16/permissive-switch/

**Comment by noloader** [comment]
@MarcelRaad,

Are you able to duplicate the issue?

**Comment by rocksonhead** [comment]
We do not have any issues compiling 6.1 using Visual Studio 2017 x64.
Note though Microsoft are pretty active updating the toolsets, so to be specific VS2017 15.6 does not produce any errors. There have been numerous compile issues with previous versions and fixes made .....

**Comment by mersadk** [comment]
I also use latest VS2017 15.6.2 and I can compile 6.1 solution from source code.
This error occurs when I include header aes.h in my project.

To reproduce error, I've tried creating new Console and static library projects, including that header file. Both compiled without problems, so I'm not sure what is happening.

In following blog post MS states that  two-phase name lookup is a work in progress and that it can cause this error message to appear, so they will probably solve it in the future.
https://blogs.msdn.microsoft.com/vcblog/2017/09/11/two-phase-name-lookup-support-comes-to-msvc/

For now turning off Conformance mode works.

**Comment by noloader** [comment]
@mersadk ,

According to the Microsoft blog a diagnostic is printed in addition to the error.

Can you provide the entire output, including the part when MSC wants `typename` applied?

**Comment by mersadk** [comment]
@noloader 

When I set "MSBuild project build output verbosity" to Diagnostic I get following output and nothing else.

```
secblock.h(89): warning C4003: not enough actual parameters for macro 'U'
secblock.h(89): warning C4003: not enough actual parameters for macro '_XPLATSTR'
secblock.h(82): error C7510: 'forward': use of dependent type name must be prefixed with 'typename'
secblock.h(82): note: This diagnostic occurred in the compiler generated function 'void CryptoPP::AllocatorBase<T>::construct(U *,Args &&...)'
secblock.h(118): note: see reference to class template instantiation 'CryptoPP::AllocatorBase<T>' being compiled
```

**Comment by noloader** [comment]
Maybe you can try:

```
AllocatorBase<T>::construct(typename U *,typename Args &&...)
```

It would be nice to know how to side step the problem without changing compiler options.

**Comment by mersadk** [comment]
I can't find that code. Output above says that it compiler generated function.

I tried with following but it didn't help (line 82)
`void construct(typename U* ptr, typename Args&&... args)`

**Comment by MarcelRaad** [comment]
@mersadk That's strange, I'm also compiling with latest VS 2017 and all conformance options set and I don't get that error. Could you share the whole template instantiation stack?

**Comment by mersadk** [comment]
@MarcelRaad I'm not sure how to do that.

After commenting line by line, I figured out this happens only if I include cpprest/http_client.h (I installed [cpprest](https://github.com/Microsoft/cpprestsdk) using vcpkg) before cryptopp headers. If I reverse them (first cryptopp headers) then it will compile normally.

It even happens in that empty console application if I include cpprest header before cryptopp headers.

**Comment by noloader** [comment]
@mersadk 

I wonder if this has something to do with it:

```
secblock.h(89): warning C4003: not enough actual parameters for macro 'U'
secblock.h(89): warning C4003: not enough actual parameters for macro '_XPLATSTR'
```

Is `cpprest` using a macro named `U` or providing a macro named `_XPLATSTR`? Do you know if `cpprest` is even compatible with the version of Windows and the Visual Studio you are using?

Maybe you can side-step the problem with the following (assuming `cpprest` is not using a `UU` macro):

``
template<typename UU, typename... Args>
    void construct(UU* ptr, Args&&... args) {::new ((void*)ptr) UU(std::forward<Args>(args)...);}
``

**Comment by mersadk** [comment]
@noloader 

You are correct, cpprest uses U to define wide strings (std::wstring), for example U("My string").

#define U(x) _XPLATSTR(x)

**Comment by noloader** [comment]
Does this fix the problem in `secblock.h` for you:

```
template<typename V, typename... Args>
    void construct(V* ptr, Args&&... args) {::new ((void*)ptr) V(std::forward<Args>(args)...);}
```

If `V` is OK, let's bump from `U` to `V` so no one else has trouble with it.

**Comment by mersadk** [comment]
@noloader 
V did help. There is also destroy() function few lines below which also use U so I've updated that as well.

**Comment by noloader** [comment]
Thanks @mersadk,

Do you want to make a Pull Request, or would you like us to check it in?

**Comment by mersadk** [comment]
@noloader 

It would be best if you do it, as VS2017 is asking me to re-target solution to Windows SDK v10.

**Comment by noloader** [comment]
Thanks again @mersadk.

Cleared at [244abbe41c6e](https://github.com/weidai11/cryptopp/commit/244abbe41c6e).
