### ISSUE TITLE
simple_ptr should be non-copyable

### ISSUE THREAD

**Issue by jwakely** [weidai11/cryptopp#6]
{
      simple_ptr<int> p1(new int);
      simple_ptr<int> p2(p1);
    } // double delete, undefined behaviour

**Comment by jwakely** [comment]
And the comment:

    // set m_p to NULL so double destruction (which might occur in Singleton) will be harmless

is highly concerning. Decent compilers will eliminate writes to a member variable in a destructor because the member can't be accessed again, so this attempt at working around buggy code that destroys objects twice won't work. Fix the bug that results in double destruction instead of trying to render the symptoms harmless.

**Comment by noloader** [comment]
Made smart_ptr non-copyable.

There's some more goodness going on that needs to be examined. I'll get to them when potential ODR violations are examined.
