### ISSUE TITLE
rdrand.cpp causes the library to fail to compile when using MinGW-w64

### ISSUE THREAD

**Issue by Zireael-N** [weidai11/cryptopp#60]
* Version: 5.6.3 RC6
* Error message:
```
g++ -DNDEBUG -g2 -O2 -fPIC -march=native -pipe -c rdrand.cpp
rdrand.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 // rdrand.cpp - written and placed in public domain by Jeffrey Walton and Uri Blumenthal.
 ^
rdrand.cpp:435:5: error: #error "Please report on the Crypto++ user group"
 #   error "Please report on the Crypto++ user group"
     ^
GNUmakefile:449: recipe for target 'rdrand.o' failed
make: *** [rdrand.o] Error 1
```
* Preprocessor's defines: https://gist.github.com/Zireael-N/694402a705830b0e6723
* g++ --version: `g++.exe (Rev4, Built by MSYS2 project) 5.2.0`

**Comment by noloader** [comment]
Let's clear the `-fPIC` eyesore warning first... Here it is:

    # Add -fPIC for x86_64, but not X32, Cygwin or MinGW
    ifneq ($(IS_X86_64),0)
      IS_X32 := $(shell $(CXX) -dM -E - < /dev/null 2>&1 | $(EGREP) -c "ILP32")
      ifeq ($(IS_X32),0$(IS_CYGWIN)$(IS_MINGW),000)
      ifeq ($(findstring -fPIC,$(CXXFLAGS)),)
        CXXFLAGS += -fPIC
      endif
      endif
    endif

**Comment by Zireael-N** [comment]
> Let's clear the -fPIC eyesore first...

Yep, does the job.
But I think `ifeq ($(IS_X32),0$(IS_CYGWIN)$(IS_MINGW),000)` is supposed to be `ifeq ($(IS_X32)$(IS_CYGWIN)$(IS_MINGW),000)`. Notice the `,0` before checking for Cygwin.

**Comment by noloader** [comment]
@Zireael-N,

Add the following to see the string it produces:

    $(info MASHUP: $(IS_X32),0$(IS_CYGWIN)$(IS_MINGW))

Then, perform a `make`.

**Comment by Zireael-N** [comment]
`MASHUP: 0,001`

**Comment by noloader** [comment]
> > Notice the ,0 before checking for Cygwin
>
> Forgive my ignorance... I'm not quite following the logic.

My bad, I see. I *thought* you were suggesting that. Yes, you are right.

**Comment by noloader** [comment]
@Zireael-N - I'm getting ready to check-in the rollups. They include the open items from the last check-in, Coverity findings, and this item.

I tried to test MinGW on 2 different machines, but I encountered MinGW problems on both machines. I got that same problem of "g++: not found". I even drilled into the `msys` directly and launched the batch file by hand. I also tried a reinstall which did not help the issue. So MinGW and RDRAND/RDSEED is untested...

**Comment by Zireael-N** [comment]
Is there anything I can help you with?

**Comment by noloader** [comment]
OK, can you test the d2fda9b check-in?

**Comment by Zireael-N** [comment]
Getting this:
```
g++ -DNDEBUG -g2 -O2 -fPIC -march=native -pipe -c rdrand.cpp
rdrand.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 // rdrand.cpp - written and placed in public domain by Jeffrey Walton and Uri Blumenthal.
 ^
rdrand.cpp: In member function 'virtual void CryptoPP::RDRAND::GenerateBlock(byte*, size_t)':
rdrand.cpp:299:16: error: 'HasRDRAND' was not declared in this scope
  if(!HasRDRAND())
                ^
rdrand.cpp: In member function 'virtual void CryptoPP::RDSEED::GenerateBlock(byte*, size_t)':
rdrand.cpp:470:16: error: 'HasRDSEED' was not declared in this scope
  if(!HasRDSEED())
                ^
GNUmakefile:449: recipe for target 'rdrand.o' failed
make: *** [rdrand.o] Error 1
```

**Comment by noloader** [comment]
> Getting this:
>
>     g++ -DNDEBUG -g2 -O2 -fPIC -march=native -pipe -c rdrand.cpp

It looks like more Git problems. Man I hate this f**k'ing tool... It only checked in 15 files, and they did not include the `GNUmakefile` changes.

I had to go through and do a `git add` after fetching in an effort to get Git to check them back in. This tool is about as useful as MinGW...

**Comment by Zireael-N** [comment]
Alright, got rdrand.o to build, but I'm back to #28 with `memcpy_s` issues. Did you forget to apply the changes or did you not push them?

**Comment by noloader** [comment]
> Did you forget to apply the changes or did you not push them?

I used the wrong `#define`: `__MINGW__` instead of `__MINGW32__`.

Sorry about that.

**Comment by Zireael-N** [comment]
Yep, that was it.

Well, everything's fine now: it builds and passes all the tests.

**Comment by noloader** [comment]
> Yep, that was it.

Nice. As soon as some OS X users test the Clang changes, I'm going to ask the board to release 5.6.3. (I do most of the coding work, so I cannot perform a release without authorization. Someone else has to do it or instruct me to do it to ensure a separation of duties).

Thanks for all your help.
