### ISSUE TITLE
Incorrect result when using Integer::ModInverse

### ISSUE THREAD

**Issue by noloader** [weidai11/cryptopp#602]
This issue was privately reported in an email:

```
$ cat test.cxx
#include "integer.h"
#include "nbtheory.h"
#include <iostream>

int main(int argc, char* argv[])
{
    using namespace CryptoPP;

    Integer a("0x2F0500010000018000000000001C1C000000000000000A000B0000000000000000000000000000FDFFFFFF00000000");
    Integer b("0x3D2F050001");

    Integer x = a.InverseMod(b);
    std::cout << std::hex << x << std::endl;

    return 0;
}
```

Crypto++ result:

```
$ ./test.exe
342188107fh
```

Botan and OpenSSL result:

```
0x3529E4FEBC
```

-----

Here is [Integer::InverseMod](https://github.com/weidai11/cryptopp/blob/master/integer.cpp#L4378):

```
Integer Integer::InverseMod(const Integer &m) const
{
	if (IsNegative())
		return Modulo(m).InverseMod(m);

	if (m.IsEven())
	{
		if (!m || IsEven())
			return Zero();	// no inverse
		if (*this == One())
			return One();

		Integer u = m.Modulo(*this).InverseMod(*this);
		return !u ? Zero() : (m*(*this-u)+1)/(*this);
	}

	SecBlock<word> T(m.reg.size() * 4);
	Integer r((word)0, m.reg.size());
	unsigned k = AlmostInverse(r.reg, T, reg, reg.size(), m.reg, m.reg.size());
	DivideByPower2Mod(r.reg, r.reg, k, m.reg, m.reg.size());
	return r;
}
```

**Comment by denisbider** [comment]
Python agrees with OpenSSL and Botan when using [this one-liner](https://stackoverflow.com/a/29762148) for the modular multiplicative inverse:

    >>> a = 0x2F0500010000018000000000001C1C000000000000000A000B0000000000000000000000000000FDFFFFFF00000000
    >>> b = 0x3D2F050001
    >>> MMI = lambda A, n,s=1,t=0,N=0: (n < 2 and t%N or MMI(n, A%n, t, s-A//n*t, N or n),-1)[n<1]
    >>> m = MMI(a, b)
    >>> hex(m)
    '0x3529e4febcL'

**Comment by noloader** [comment]
Thanks @denisbider, @mouse07410, @MarcelRaad,

So it looks like two problems. First is a memory error due to:

```
SecBlock<word> T(m.reg.size() * 4);
Integer r((word)0, m.reg.size());
unsigned k = AlmostInverse(r.reg, T, reg, reg.size(), m.reg, m.reg.size());
DivideByPower2Mod(r.reg, r.reg, k, m.reg, m.reg.size());
```

After clearing the memory error:

```
$ git diff
diff --git a/integer.cpp b/integer.cpp
index e9846bd..b9b4215 100644
--- a/integer.cpp
+++ b/integer.cpp
@@ -4393,8 +4393,9 @@ Integer Integer::InverseMod(const Integer &m) const
                return !u ? Zero() : (m*(*this-u)+1)/(*this);
        }

-       SecBlock<word> T(m.reg.size() * 4);
-       Integer r((word)0, m.reg.size());
+       unsigned int t = STDMAX(m.WordCount(), WordCount()) * 4;^M
+       SecBlock<word> T(t);^M
+       Integer r((word)0, t);^M
        unsigned k = AlmostInverse(r.reg, T, reg, reg.size(), m.reg, m.reg.size());
        DivideByPower2Mod(r.reg, r.reg, k, m.reg, m.reg.size());
        return r;
```

We have the second problem, which is the same incorrect result.

**Comment by noloader** [comment]
The fix and the missing tests are being tested on [Noloader | GitHub](https://github.com/noloader/cryptopp/commit/e322e4b9687b).

**Comment by noloader** [comment]
The fix and the missing tests are being tested on [Noloader | GitHub](https://github.com/noloader/cryptopp/commit/406ea5852399).

**Comment by noloader** [comment]
Cleared at [Commit ](https://github.com/weidai11/cryptopp/commit/ff82b5a886d3).

**Comment by noloader** [comment]
Cleared at [Commit ff82b5a886d3](https://github.com/weidai11/cryptopp/commit/ff82b5a886d3).

**Comment by noloader** [comment]
Cleared at [Commit ff82b5a886d3](https://github.com/weidai11/cryptopp/commit/ff82b5a886d3) and [Commit 932f392b2d33](https://github.com/weidai11/cryptopp/commit/932f392b2d33).

The ff82b5a886d3 commit cleared the bulk of the problems, including the memory error.

The 932f392b2d33 commit cleared a corner case. It looked to be fairly obscure. Most runs were OK. About 1 in 16 runs produced 1 failed result. `cryptest.sh` caught the problem during comprehensive testing. 90 configuration produced 7 failures.

**Comment by denisbider** [comment]
Thanks for this fix,  Jeff. :) This explains a mystery that's been on the back of my mind for perhaps 15 years, that I never quite figured out previously. :D

**Comment by noloader** [comment]
@denisbider, @mouse07410, @MarcelRaad,

I think I should summarize the fix here since the first check-in was incomplete, and we needed a second check-in.

Here was the original code causing problems:

```
Integer Integer::InverseMod(const Integer &m) const
{
	if (IsNegative())
		return Modulo(m).InverseMod(m);

	if (m.IsEven())
	{
		if (!m || IsEven())
			return Zero();	// no inverse
		if (*this == One())
			return One();

		Integer u = m.Modulo(*this).InverseMod(*this);
		return !u ? Zero() : (m*(*this-u)+1)/(*this);
	}

	SecBlock<word> T(m.reg.size() * 4);
	Integer r((word)0, m.reg.size());
	unsigned k = AlmostInverse(r.reg, T, reg, reg.size(), m.reg, m.reg.size());
	DivideByPower2Mod(r.reg, r.reg, k, m.reg, m.reg.size());
	return r;
}
```

Here is the fixed code. We kept the recursion but we split it into a first/next call. The "first" part validates/fixes the parameters. The "next" part applies the algorithm without the parameter fixes/validations:

```
Integer Integer::InverseMod(const Integer &m) const
{
	CRYPTOPP_ASSERT(m.NotNegative());
	CRYPTOPP_ASSERT(m != 0);

	if (IsNegative())
		return Modulo(m).InverseModNext(m);

	// http://github.com/weidai11/cryptopp/issues/602
	if (*this > m)
		return Modulo(m).InverseModNext(m);

	return InverseModNext(m);
}

Integer Integer::InverseModNext(const Integer &m) const
{
	CRYPTOPP_ASSERT(m.NotNegative());
	CRYPTOPP_ASSERT(m != 0);

	if (m.IsEven())
	{
		if (!m || IsEven())
			return Zero();	// no inverse
		if (*this == One())
			return One();

		Integer u = m.Modulo(*this).InverseModNext(*this);
		return !u ? Zero() : (m*(*this-u)+1)/(*this);
	}

	// AlmostInverse requires a 4x workspace
	IntegerSecBlock T(m.reg.size() * 4);
	Integer r((word)0, m.reg.size());
	unsigned k = AlmostInverse(r.reg, T, reg, reg.size(), m.reg, m.reg.size());
	DivideByPower2Mod(r.reg, r.reg, k, m.reg, m.reg.size());
	return r;
}
```

The modular reduction in `InverseMod` fixed the memory error. Once `*this` was reduced, the wild read and write was not a problem because the `a` in `(a ^ -1) mod n` was small enough.

The code also moved to `IntegerSecBlock`. This was a small cosmetic change. The rest of `Integer` class used `IntegerSecBlock` and the consistency makes it easier to audit the class for {un}aligned access.
