### ISSUE TITLE
WindowsPipeReceiver/Sender inherit a pure virtual function but do not override it

### ISSUE THREAD

**Issue by Zireael-N** [weidai11/cryptopp#62]
https://github.com/weidai11/cryptopp/blob/48809d4e85c125814425c621d8d0d89f95405924/winpipes.h#L60

They inherit `virtual HANDLE GetHandle() const =0;` from `WindowsPipe`.

It is then called in `WindowsPipeReceiver::Receive()`, `WindowsPipeReceiver::GetReceiveResult()`, `WindowsPipeSender::Send` and `WindowsPipeSender::GetSendResult()`:
https://github.com/weidai11/cryptopp/blob/48809d4e85c125814425c621d8d0d89f95405924/winpipes.cpp#L94

At this state: https://github.com/weidai11/cryptopp/tree/8a02fe1787e62fb14f90650dee57024920c83adb
Compilation of `cryptest.exe` failed because of this:
```
g++ -o cryptest.exe -DNDEBUG -g2 -O3 -fPIC -march=native -Wall -Wextra -Wno-type-limits -Wno-unknown-pragmas -pipe bench.o bench2.o test.o validat0.o validat1.o validat2.o validat3.o adhoc.o datatest.o regtest.o fipsalgt.o dlltest.o ./libcryptopp.a  -lws2_32
./libcryptopp.a(winpipes.o): In function `ZN8CryptoPP19WindowsPipeReceiver16GetReceiveResultEv':
C:\GitHub\cryptopp/winpipes.cpp:131: undefined reference to `non-virtual thunk to CryptoPP::WindowsPipeSource::GetHandle() const'
C:\GitHub\cryptopp/winpipes.cpp:131: undefined reference to `non-virtual thunk to CryptoPP::WindowsPipeSource::GetHandle() const'
./libcryptopp.a(winpipes.o): In function `ZN8CryptoPP19WindowsPipeReceiver7ReceiveEPhj':
C:\GitHub\cryptopp/winpipes.cpp:94: undefined reference to `non-virtual thunk to CryptoPP::WindowsPipeSource::GetHandle() const'
C:\GitHub\cryptopp/winpipes.cpp:94: undefined reference to `non-virtual thunk to CryptoPP::WindowsPipeSource::GetHandle() const'
collect2.exe: error: ld returned 1 exit status
```

After you pushed 5.6.3 RC6, these errors do not appear anymore. But I guess that's because these classes are not tested? Because you still have a pure virtual function that isn't overridden.

**Comment by Zireael-N** [comment]
Here's a commit with my guess as to what these functions are supposed to be overridden with: https://github.com/Zireael-N/cryptopp/commit/77405024c81ec714db4ff35ef74cda3bd6e4b598
Just prefer to get a confirmation before making a pull request.

That fixed the compilation failure at pre5.6.3-RC6 state.

**Comment by noloader** [comment]
> Just prefer to get a confirmation before making a pull request.

Yeah, that looks about right.

I wonder why it did not produce a problem under Windows proper... Let me run it through a smoke test under Windows 7 and Visual Studio. If it checks out, I'll ping you for the request.

BTW, its been that way for years: [Crypto++ 5.6.1 winpipes.h](http://cryptopp.com/docs/ref561/winpipes_8h_source.html).

**Comment by noloader** [comment]
> But I guess that's because these classes are not tested? Because you still have a pure virtual function that isn't overridden.

Yeah, I have basically have given up on MinGW. Its got to get more stable, and it has to work out of the box. Otherwise, I'm just spending my time fixing their problems instead our problems.

**Comment by noloader** [comment]
@Zireael-N 

OK, the change looks good. I was never able to reproduce the error. But adding an errant `XXX` caused a compile failure:

    operator HANDLE() { XXX return m_h;} 

While you are at it, would you mind const-ifying the returned `GetHandle()`:

    const HANDLE h = GetHandle();

I have already verified it, so it should not be wasted energy.
Thanks.

**Comment by Zireael-N** [comment]
> would you mind const-ifying

Done. Made a pull request.

**Comment by noloader** [comment]
> Done. Made a pull request.

OK, thanks.

I'm going to pull it with the `RDRAND` fix, and then unleash them together. It may be a day or two.
