### ISSUE TITLE
Unable to build CrypoPP in release in Xcode 9.3

### ISSUE THREAD

**Issue by SeanAsby** [weidai11/cryptopp#635]
When trying to build CryptoPP 6.1.0 as part of a static library in Xcode 9.3 I get the error message: `Invalid operand for instruction`.  ( `sha.cpp`, lines 1005, 1008, 1039, 1050 )

This happens when building for the Simulator with release configuration and deployment target set to iOS 10.0 or below. 

I'm running macOS 10.13.4

Please see attached test case
[CryptoppTest.zip](https://github.com/weidai11/cryptopp/files/1879331/CryptoppTest.zip)

**Comment by noloader** [comment]
Hmmm... It sounds like the simulator lacks the ISA support.

Looking at Travis [iPhoneSimulator build](https://travis-ci.org/noloader/cryptopp/jobs/362500857) it looks like the job fails but it reports success. iPhoneSimulator is Job 28 in the build.

The Travis job failed at SSSE3, so it looks like we are going to have to add `-DCRYPTOPP_DISABLE_SSSE3` to the build options for iPhoneSImulator. Android gets similar options for i686 and x86_64 builds.

Let me test the change and report back.

**Comment by noloader** [comment]
The job is running at [build 362565717](https://travis-ci.org/noloader/cryptopp/builds/362565717). The iPhoneSimulator job is the last job on the list. It will take an hour or two to get to it.

**Comment by noloader** [comment]
This should be cleared at [Commit 37d723e6802a](https://github.com/weidai11/cryptopp/commit/37d723e6802a).
