### ISSUE TITLE
CLang support for android

### ISSUE THREAD

**Issue by strentler** [weidai11/cryptopp#637]
Clang is now the default NDK compiler for Android. Support for GCC has stopped.

Looking at [Android (Command Line)](https://www.cryptopp.com/wiki/Android_(Command_Line)), it looks like there is no support to compile Crypto++ for Android using Clang. `setenv-android.sh` should support compiling with Clang.

Also see [Android NDK, Revision 16b (December 2017)](https://developer.android.com/ndk/downloads/revision_history.html).

**Comment by strentler** [comment]
Clang is now the default ndk compiler for android.
Support for gcc has stopped:

Android NDK, Revision 16b (December 2017):
https://developer.android.com/ndk/downloads/revision_history.html

**Comment by KayEss** [comment]
Android is now switching over to cmake, which I guess is both good and bad for this. I've made a [stab at something for this](https://github.com/KayEss/fost-crypto/blob/master/CMakeLists.txt). ARM builds seemed to work fine (there are some settings needed in the cmake configuration in gradle to go with it too). The latest NDK seems to have broken x86. Maybe it just needs the right compile option?

For crypto++ 7.0 I needed to patch `pwdbased.h` and add an include:

    #include "algparam.h"

For x86_64 I get the following error though. I wonder if this is because an architecture flag is missing. The ones I'm setting so far are `-maes -mpclmul -msha -msse4.1 -msse4.2 -mssse3`. I'm afraid the GNU make stuff is totally impenetrable for me.

    FAILED: /home/kirit/tmp/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++  --target=i686-none-linux-android --gcc-toolchain=/home/kirit/tmp/Android/Sdk/ndk-bundle/toolchains/x86-4.9/prebuilt/linux-x86_64 --sysroot=/home/kirit/tmp/Android/Sdk/ndk-bundle/sysroot   -I../../../../src/main/cpp/fost-android-ndk/crypto/. -I/home/kirit/tmp/Android/Sdk/ndk-bundle/sources/android/cpufeatures -isystem /home/kirit/tmp/Android/Sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include -isystem /home/kirit/tmp/Android/Sdk/ndk-bundle/sources/android/support/include -isystem /home/kirit/tmp/Android/Sdk/ndk-bundle/sources/cxx-stl/llvm-libc++abi/include -isystem /home/kirit/tmp/Android/Sdk/ndk-bundle/sysroot/usr/include/i686-linux-android -D__ANDROID_API__=14 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -mstackrealign -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -std=c++14 -DBOOST_VERSION_MAJOR=65 -O0 -fno-limit-debug-info    -fPIC -maes -mpclmul -msha -msse4.1 -msse4.2 -mssse3 -MD -MT src/main/cpp/fost-android-ndk/crypto/CMakeFiles/crypto++.dir/crypto++/sha.cpp.o -MF src/main/cpp/fost-android-ndk/crypto/CMakeFiles/crypto++.dir/crypto++/sha.cpp.o.d -o src/main/cpp/fost-android-ndk/crypto/CMakeFiles/crypto++.dir/crypto++/sha.cpp.o -c /home/kirit/Projects/bundler-dev/android-bundle-viewer/app/src/main/cpp/fost-android-ndk/crypto/crypto++/sha.cpp
    /home/kirit/Projects/bundler-dev/android-bundle-viewer/app/src/main/cpp/fost-android-ndk/crypto/crypto++/sha.cpp:1005:5: error: invalid operand for instruction
        ASJ(    jnz,     0, b)
        ^
    /home/kirit/Projects/bundler-dev/android-bundle-viewer/app/src/main/cpp/fost-android-ndk/crypto/crypto++/cpu.h:623:23: note: expanded from macro 'ASJ'
            #define ASJ(x, y, z) GNU_ASJ(x, y, z)
                                ^
    /home/kirit/Projects/bundler-dev/android-bundle-viewer/app/src/main/cpp/fost-android-ndk/crypto/crypto++/cpu.h:617:27: note: expanded from macro 'GNU_ASJ'
            #define GNU_ASJ(x, y, z) #x " " #y #z ";" NEW_LINE
                                    ^
    <scratch space>:207:2: note: expanded from here
    "jnz"
    ^
    <inline asm>:80:1: note: instantiated into assembly here
    jnz 0b;
    ^
    /home/kirit/Projects/bundler-dev/android-bundle-viewer/app/src/main/cpp/fost-android-ndk/crypto/crypto++/sha.cpp:1008:5: error: invalid operand for instruction
        ASJ(    jne,     0, b)
        ^
    /home/kirit/Projects/bundler-dev/android-bundle-viewer/app/src/main/cpp/fost-android-ndk/crypto/crypto++/cpu.h:623:23: note: expanded from macro 'ASJ'
            #define ASJ(x, y, z) GNU_ASJ(x, y, z)
                                ^
    /home/kirit/Projects/bundler-dev/android-bundle-viewer/app/src/main/cpp/fost-android-ndk/crypto/crypto++/cpu.h:617:27: note: expanded from macro 'GNU_ASJ'
            #define GNU_ASJ(x, y, z) #x " " #y #z ";" NEW_LINE
                                    ^
    <scratch space>:214:2: note: expanded from here
    "jne"
    ^
    <inline asm>:83:1: note: instantiated into assembly here
    jne 0b;
    ^
    /home/kirit/Projects/bundler-dev/android-bundle-viewer/app/src/main/cpp/fost-android-ndk/crypto/crypto++/sha.cpp:1039:5: error: invalid operand for instruction
        ASJ(    jnz,     1, b)
        ^
    /home/kirit/Projects/bundler-dev/android-bundle-viewer/app/src/main/cpp/fost-android-ndk/crypto/crypto++/cpu.h:623:23: note: expanded from macro 'ASJ'
            #define ASJ(x, y, z) GNU_ASJ(x, y, z)
                                ^
    /home/kirit/Projects/bundler-dev/android-bundle-viewer/app/src/main/cpp/fost-android-ndk/crypto/crypto++/cpu.h:617:27: note: expanded from macro 'GNU_ASJ'
            #define GNU_ASJ(x, y, z) #x " " #y #z ";" NEW_LINE
                                    ^
    <scratch space>:306:2: note: expanded from here
    "jnz"
    ^
    <inline asm>:128:1: note: instantiated into assembly here
    jnz 1b;
    ^
    /home/kirit/Projects/bundler-dev/android-bundle-viewer/app/src/main/cpp/fost-android-ndk/crypto/crypto++/sha.cpp:1050:5: error: invalid operand for instruction
        ASJ(    jne,     1, b)
        ^
    /home/kirit/Projects/bundler-dev/android-bundle-viewer/app/src/main/cpp/fost-android-ndk/crypto/crypto++/cpu.h:623:23: note: expanded from macro 'ASJ'
            #define ASJ(x, y, z) GNU_ASJ(x, y, z)
                                ^
    /home/kirit/Projects/bundler-dev/android-bundle-viewer/app/src/main/cpp/fost-android-ndk/crypto/crypto++/cpu.h:617:27: note: expanded from macro 'GNU_ASJ'
            #define GNU_ASJ(x, y, z) #x " " #y #z ";" NEW_LINE
                                    ^
    <scratch space>:5:2: note: expanded from here
    "jne"
    ^
    <inline asm>:134:1: note: instantiated into assembly here
    jne 1b;
    ^
    4 errors generated.

**Comment by KayEss** [comment]
Just in case it's of use to anybody, this is the android build file that we were using with `ndk-build`. That was for crypto 5.6.2.

https://github.com/KayEss/fost-android-ndk/blob/a17746cfc5bc517229083d370f59b77ef13a2567/crypto%2B%2B.mk

**Comment by noloader** [comment]
@KayEss, @strentler,

I was able to use `ndk-build` with the latest NDK to get the updated `CXXFLAGS`. They were added to [Android (Command Line) | Clang CXXFLAGS](https://www.cryptopp.com/wiki/Android_(Command_Line)#Clang_CXXFLAGS) on the wiki.

I made some modifications to our current script but things are failing pretty bad. I'll keep chiseling away at the problems.

**Comment by Skycoder42** [comment]
What is the current status for this? I can't seem to find a setenv-android-clang.sh in the repository or n the wiki? 

Also, with NDK v18, gcc has completely been removed and was replaced with a bash script that simply invokes clang, which means it is currently impossible to compile cryptopp for android with the recent NDK

**Comment by Skycoder42** [comment]
I also can extract compiler flags from Qt as well, if you need more examples, as Qt managed to completly port to clang.

**Comment by KayEss** [comment]
We have a cmake config that works for Android, Linux and Mac OS: https://github.com/KayEss/fost-crypto/blob/master/CMakeLists.txt

**Comment by Skycoder42** [comment]
@KayEss Thank you! I was able to create an qmake pro file based on your example that compiles successfully on all platforms I care for (including the arm64_v8a, armv7 and x86 android architectures). (See https://github.com/Skycoder42/QtDataSync/blob/master/src/3rdparty/cryptopp/cryptopp.pro).

**Comment by noloader** [comment]
@strentler,

I'm going to close this report because we are working Issue 763, [Building for Android using NDK not supported on Windows hosts](https://github.com/weidai11/cryptopp/issues/763). The 763 issue has an improved script that should close the gaps for compilers like Clang and GCC, and platforms like Linux and Windows.
