### ISSUE TITLE
Compilation through g++ form MinGW and editing data for AEAD AES-256-GCM. 

### ISSUE THREAD

**Issue by shalec** [weidai11/cryptopp#638]
I'm trying to compile this test:
https://www.cryptopp.com/w/images/3/3a/GCM-AEAD-Test.zip

**Information for my directory**
C(dir)
---cryptopp_include(dir)
------ all *.h from version 7.0
------gcm_test(dir)
--------- stdatfx.h and targetver.h
---lib(dir)
------- libcryptopp.a (buildwith gcc 5.6 on Ubuntu 16.0.4 LTS)
makefile
aes.cc

**Build with**
> g++ -W -O3 aes.cc -o"aes.exe" -L./lib/ -lcryptopp

(aes.cc contains the "driver" decryption stuff. 

**Questions**
Problem 1: Compilation through MinGW doesnt work.
Problem 2: Can't modify "AAD" or the Ciphertext.

**Edit: (partly)Solution for Problem 1**
Compiling through Ubuntu in VM. We need to erase the call for "windows.h" and "tchar.h" (since it is windows only..) with a further typedef of byte (which is missing). (typedef unsigned char byte;)
Compiling will be done through g++ from paket "build_essential" from source "install". (sudo apt-get install build_essential). 

**Edit2: Problem2 is open**
It is compilable, as I described before. But, if I enter an 16-Byte hex string (32 letters) it fails. So I need a "how to" for filling in data different from 0. How about the vector 4? 
>VEC 0004
>KEY fb7615b23d80891dd470980bc79584c8b2fb64ce60978f4d17fce45a49e830b7
>IV  dbd1a3636024b7b402da7d6f
>PTX a845348ec8c5b5f126f50e76fefd1b1e
>CTX 5df5d1fabcbbdd051538252444178704
>TAG 4c43cce5a574d8a88b43d4353bd60f9f

**Comment by noloader** [comment]
Thanks @shalec,

Yeah, that sounds about right for MinGW. It is not well supported. The samples are usually written for and tested against Linux and Windows. MinGW users will usuallly have to do something special.
