### ISSUE TITLE
AES-256-GCM: How to fill in other Test-Examples

### ISSUE THREAD

**Issue by shalec** [weidai11/cryptopp#639]
Lets assume, we want to test vector nr 5 given in https://www.cryptopp.com/w/images/3/3a/GCM-AEAD-Test.zip

>KEY 404142434445464748494a4b4c4d4e4f505152535455565758595a5b5c5d5e5f
>IV  101112131415161718191a1b
>HDR 000102030405060708090a0b0c0d0e0f10111213
> PTX 202122232425262728292a2b2c2d2e2f3031323334353637
> CTX 591b1ff272b43204868ffc7bc7d521993526b6fa32247c3c
> TAG 7de12a5670e570d8cae624a16df09c08

How to modify the "driver.cpp" file, to just DECODE the CTX and (possibly) test against given PTX?

I just entered Key and IV as "byte" and AAD, Cipher, GHASH as "string"
```
byte key[ 32] = {
    0x40, 0x41, 0x42, 0x43, 0x44, 0x45, 0x46, 0x47, 0x48, 0x49, 0x4a, 0x4b, 0x4c, 0x4d, 0x4e, 0x4f, 0x50, 
    0x51, 0x52, 0x53, 0x54, 0x55, 0x56, 0x57, 0x58, 0x59, 0x5a, 0x5b, 0x5c, 0x5d, 0x5e, 0x5f
		};
byte iv[ 12] = {
    0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b
		};
	//*/
string adata = "000102030405060708090a0b0c0d0e0f10111213"; 
//Problem: This are 40 letters ~ 40 Bytes, not 20 Bytes, as suggested.
string enc = "591b1ff272b43204868ffc7bc7d521993526b6fa32247c3c";
string mac = "7de12a5670e570d8cae624a16df09c08"; // 32 Byte, instead of 16
```

But this encurages alot of errors.

**Edit**
If someone needs to split those hex-strings, here is a small Sagemath snippet
```
string = "7de12a5670e570d8cae624a16df09c08"
out=""
for i in range(len(string)/2):
    if(i!=0):
        out += ", "
    out += "0x" + string[2*i] + string[2*i+1]
print out + "\n"
print len(string)
```

**Comment by noloader** [comment]
@shalec ,

Thanks for the hints. Would you mind editing the wiki page rather than putting notes in the bug tracker?

We like to use the bug tracker for library bugs.
