### ISSUE TITLE
PolynomialMod2::operator<<= Bug

### ISSUE THREAD

**Issue by apatryda** [weidai11/cryptopp#64]
When using PolynomialMod2 shift left operator, the most significant word
is lost when shifting by more than WORD_BITS bits.

In "gf2n.c" the line 349 states:

     reg[reg.size()-1] = carry;

it should be:

     reg[reg.size()-shiftWords-1] = carry;

**Comment by noloader** [comment]
@apatryda - Please forgive my ignorance. Can you provide a test case and point out the issue?

I appear to be getting expected results from the program below:

    $ ./mod2.exe
    WORD_BITS: 64
    0:
      11111111,11111111,11111111,11111111,11111111,11111111,11111111,11111111b
    1:
      1,11111111,11111111,11111111,11111111,11111111,11111111,11111111,11111110b
    2:
      11,11111111,11111111,11111111,11111111,11111111,11111111,11111111,11111100b
    3:
      111,11111111,11111111,11111111,11111111,11111111,11111111,11111111,11111000b
    ...
    128:
      11111111,11111111,11111111,11111111,11111111,11111111,11111111,11111111,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000b

 In addition, `valgrind ./mod2.exe` doe snot produce any Valgrind findings:

    $ valgrind ./mod2.exe
    ==43598== Memcheck, a memory error detector
    ==43598== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
    ==43598== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
    ==43598== Command: ./mod2.exe
    ==43598== 
    WORD_BITS: 64
    0:
      11111111,11111111,11111111,11111111,11111111,11111111,11111111,11111111b
    ....
    128:
      11111111,11111111,11111111,11111111,11111111,11111111,11111111,11111111,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000b

    ==43598== 
    ==43598== HEAP SUMMARY:
    ==43598==     in use at exit: 62,726 bytes in 351 blocks
    ==43598==   total heap usage: 670 allocs, 319 frees, 84,783 bytes allocated
    ==43598== 
    ==43598== LEAK SUMMARY:
    ==43598==    definitely lost: 0 bytes in 0 blocks
    ==43598==    indirectly lost: 0 bytes in 0 blocks
    ==43598==      possibly lost: 0 bytes in 0 blocks
    ==43598==    ...
    ==43598== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

Thanks.

----------

    $ cat mod2.cxx
    #include <iostream>
    #include "gf2n.h"

    int main()
    {
        cout << "WORD_BITS: " << WORD_BITS << endl;
        word v = SIZE_MAX;

        PolynomialMod2 mod(v);
        unsigned int i = 0;

        for (i=0; i <= 2*WORD_BITS; i++)
        {
            cout << i << ":" << endl;
            cout << "  " << mod << endl;
            mod <<= 1;
        }
    
        return 0;
    }

----------

**Comment by noloader** [comment]
Confirmed there's some wonkiness going on. Crossing the boundary from 64-bits to 65-bits produces:

    63:
      1111111,11111111,11111111,11111111,11111111,11111111,11111111,11111111,10000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000b
    64:
      11111111,11111111,11111111,11111111,11111111,11111111,11111111,11111111,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000b
    65:
  1010000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,11111111,11111111,11111111,11111111,11111111,11111111,11111111,11111110,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000b
    66:
      11111111,11111111,11111111,11111111,11111111,11111111,11111111,11111100,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000b

-----

    $ cat mod2.cxx 
    #include <iostream>
    #include "gf2n.h"

    int main()
    {
        cout << "WORD_BITS: " << WORD_BITS << endl;
        word v = SIZE_MAX;

        const PolynomialMod2 mod(v);
        unsigned int i = 0;

        for (i=WORD_BITS - 8; i <= WORD_BITS + 8; i++)
        {
            cout << i << ":" << endl;
            cout << "  " << (mod << i)  << endl;
        }

        return 0;
    }

**Comment by noloader** [comment]
@apatryda - Here you go. Thanks for reporting.

Have you checked the other mod arithmetic classes? If you have not, then we'll audit them.

Maybe we need a few test cases added....

    @@ -320,6 +325,11 @@
 
     PolynomialMod2& PolynomialMod2::operator<<=(unsigned int n)
     {
    +#if !defined(NDEBUG)
    +	int x; CRYPTOPP_UNUSED(x);
    +	assert(SafeConvert(n,x));
    +#endif
    +
     	if (!reg.size())
     		return *this;
 
    @@ -348,8 +358,8 @@
     		return *this;
     	}
 
    -	int shiftWords = n / WORD_BITS;
    -	int shiftBits = n % WORD_BITS;
    +	const int shiftWords = n / WORD_BITS;
    +	const int shiftBits = n % WORD_BITS;
 
     	if (shiftBits)
     	{
    @@ -365,8 +375,9 @@
     
     	if (carry)
     	{
    -		reg.Grow(reg.size()+shiftWords+1);
    -		reg[reg.size()-1] = carry;
    +		const size_t carryIndex = reg.size();
    +		reg.Grow(reg.size()+shiftWords+!!shiftBits);
    +		reg[carryIndex] = carry;
     	}
     	else
     		reg.Grow(reg.size()+shiftWords);

**Comment by noloader** [comment]
@apatryda - I wanted to give you a heads up here... I was testing under X32, and here's the result:

    Testing PolynomialMod2 bit operations...

    passed    1 shifted over range [0,129]
    FAILED    0xffffffff shifted over range [0,129]
    passed    random values shifted over range [0,129]

I'm getting ready to put it under the debugger.
