### ISSUE TITLE
scrypt: unnecessary memory allocation

### ISSUE THREAD

**Issue by fxha** [weidai11/cryptopp#641]
First of all, thank you very much for your great work. I found a performance issue in your scrypt implementation. If you run with multiple threads but set `parallelization` to 1 (parallelization < threads), OpenMP will allocate unnecessary memory. The problem is that you spawn x threads with `#pragma omp parallel ` and use only `parallel` (variable) many threads for work. That means you have `(blockSize * 256U + blockSize * cost * 128U) * max{0, threads - parallelization}`  unnecessary memory allocated.

**Source:**

https://github.com/weidai11/cryptopp/blob/bdd0f02867ff843be25c284258d3256a48e41cb1/scrypt.cpp#L249

#### Example

```
$ OMP_NUM_THREADS=1 ./scrypt_bench -i 20 -m 8 -p 1
Scrypt::DeriveKey
  Enter omp parallel
    Enter omp for
2.610s

$ OMP_NUM_THREADS=8 ./scrypt_bench -i 20 -m 8 -p 1
Scrypt::DeriveKey
  Enter omp parallel
  Enter omp parallel
  Enter omp parallel
  Enter omp parallel
  Enter omp parallel
  Enter omp parallel
  Enter omp parallel
  Enter omp parallel
    Enter omp for
3.664s
```

### Information

- Fedora 27 x64
- g++ 7 with OpenMP v4.5
- Crypto++ v7.1 (master)

**Comment by fxha** [comment]
Regarding the stackoverflow question (http://stackoverflow.com/q/49604260/608639):

The problem of the **thread private** segfault is a null pointer access [here](https://github.com/weidai11/cryptopp/blob/bdd0f02867ff843be25c284258d3256a48e41cb1/scrypt.cpp#L123). `dest` parameter in `BlockCopy` is null. Maybe OpenMP has problems to allocate/deallocate `SecByteBlock`. And **Hoist out of loop** is a data race condition - you access the same memory.

I think you cannot calculate scrypt in parallel without extra memory. So there are two solutions for the problem above.

1. Move buffers into for loop. As in your SO question because this is the same as current solution without unnecessary memory allocation.

2. Allocate more memory and share buffer. Not nice code and it will "break" usage without OpenMP, but you will understand what I mean.
```
  size_t availableThreads = min{ parallel, OpenMP threads }
  AlignedSecByteBlock XY(static_cast<size_t>(blockSize * 256U) *
                         availableThreads);
  AlignedSecByteBlock V(static_cast<size_t>(blockSize * cost * 128U) *
                        availableThreads);

  // 2: for i = 0 to p - 1 do
  #pragma omp parallel for shared(XY) shared(V)
  for (size_t i = 0; i < static_cast<size_t>(parallel); ++i) {
    // 3: B_i <-- MF(B_i, N)
    const ptrdiff_t offset = static_cast<ptrdiff_t>(blockSize * i * 128);
    Smix(B + offset, static_cast<size_t>(blockSize), cost,
         V + static_cast<size_t>(blockSize * cost * 128U) * i,
         XY + static_cast<size_t>(blockSize * 256U) * i);
  }
```

And this leads to another problem: high memory usage and out of memory segfaults

**Comment by noloader** [comment]
Thanks @fxha,

This is kind of an interesting report in a morbid sort of way. We kind of predicated the implementation on using OMP with a `parallelization` greater than 1 (and closer to the number of cores).

I spent the morning thinking about it, and about the only place I got was (1) competing requirements, and (2) I don't know what to do about it. Let me think about it some more.

In the meantime, do you mind adding a section about it in the wiki at [Scrypt](https://www.cryptopp.com/wiki/Scrypt)?

**Comment by fxha** [comment]
> Do you think a call to mp_set_num_threads would be helpful to reduce the wasted memory?

I think that would be perfect. E.g:

```
#ifdef _OPENMP
word64 availableThreads = static_cast<word64>(STDMAX(omp_get_max_threads(), 1));
#else
word64 availableThreads = 1;
#endif
#pragma omp parallel num_threads(STDMIN(parallel, availableThreads))
{
    // Each thread gets its own copy
    AlignedSecByteBlock XY(static_cast<size_t>(blockSize * 256U));
    AlignedSecByteBlock  V(static_cast<size_t>(blockSize * cost * 128U));

    // 2: for i = 0 to p - 1 do
    #pragma omp for
    for (size_t i = 0; i < static_cast<size_t>(parallel); ++i)
    {
        // 3: B_i <-- MF(B_i, N)
        const ptrdiff_t offset = static_cast<ptrdiff_t>(blockSize*i*128);
        Smix(B+offset, static_cast<size_t>(blockSize), cost, V, XY);
    }
}
```

Another solution would be to use `firstprivate`, but it has a bad performance.

>  firstprivate: Specifies  that each thread should have its own instance of a variable, and that  the variable should be initialized with the value of the variable,  because it exists before the parallel construct.

> In the meantime, do you mind adding a section about it in the wiki at Scrypt?

Do you mean memory usage? I think it's a good idea to add a note that parallelization with OpenMP will consume (a lot) more memory.

**Comment by noloader** [comment]
Thanks again @fxha.

How does this patch look to you? It is you patch smashed down to a one-liner.

```
$ git diff
diff --git a/scrypt.cpp b/scrypt.cpp
index 5a53ca1..2e3f30c 100644
--- a/scrypt.cpp
+++ b/scrypt.cpp
@@ -245,6 +245,11 @@ size_t Scrypt::DeriveKey(byte*derived, size_t derivedLen, const byte*secret, siz
     // 1: (B_0 ... B_{p-1}) <-- PBKDF2(P, S, 1, p * MFLen)
     PBKDF2_SHA256(B, B.size(), secret, secretLen, salt, saltLen, 1);

+    #ifdef _OPENMP^M
+    omp_set_num_threads(^M
+       STDMIN<int>(omp_get_max_threads(), static_cast<int>(parallel)));^M
+    #endif^M
+^M
     // http://stackoverflow.com/q/49604260/608639
     #pragma omp parallel
     {
```

It produces the following results using the program at [Crypto++ Wiki | OpenMP | Sample Program](https://www.cryptopp.com/wiki/OpenMP#Sample_Program). I know we are handling paralellization threads correctly. I'm less sure if we cleared the problem you reported.

```
$ time ./scrypt.exe
Threads: 4
Key: 6B6473DB521479C4CA5B68981F5EFC41...

real    0m5.219s
user    0m18.355s
sys     0m2.075s
skylake:cryptopp$ time OMP_NUM_THREADS=1 ./scrypt.exe
Threads: 1
Key: 2A7A73D3CE8EFE87B8D2D58379E36EEB...

real    0m18.393s
user    0m17.890s
sys     0m0.474s
```

**Comment by noloader** [comment]
Cleared at [Commit edc7689a7fa4](https://github.com/weidai11/cryptopp/commit/edc7689a7fa4).

**Comment by noloader** [comment]
Cleared at [Commit edc7689a7fa4](https://github.com/weidai11/cryptopp/commit/edc7689a7fa4).

**Comment by fxha** [comment]
>  I'm less sure if we cleared the memory problem you reported.

Yeah, now it works as expected. Thanks!
