### ISSUE TITLE
Memory leak in ValidateRSA()

### ISSUE THREAD

**Issue by irwir** [weidai11/cryptopp#642]
* Windows 8.1 x64, Windows Server 2016
*  Crypto++ library - Master
* Visual Studio 2017 
* Running _crypttest_ after building the provided solution, `Debug|Win32` configuration

After executing the first block in `ValidateRSA()` (lines 292-324) heap profiler showed 2 heap allocations still not freed.

Another application also warned about a memory leak when exiting (using CRT heap debug),

Block allocation number suggested that the problem could originate in pubkey.cpp, lines 98, 114:
`const MessageEncodingInterface &encoding = GetMessageEncodingInterface();`
The object created with this call would never be deleted.

**Comment by noloader** [comment]
> After executing the first block in ValidateRSA() (lines 292-324) heap profiler showed 2 heap allocations still not freed.

Yeah, I think that's about right. I believe it is due to the Singleton pattern around [`integer.cpp : 4820`](https://github.com/weidai11/cryptopp/blob/master/integer.cpp#L4820) (and friends):

```
const Integer &Integer::Zero()
{
#if defined(CRYPTOPP_CXX11_DYNAMIC_INIT)
	static Integer s_zero(0L);
	return s_zero;
#elif defined(HAVE_MSC_INIT_PRIORITY) && defined(USE_MSC_INIT_PRIORITY)
	return g_zero;
#else
	return Singleton<Integer, NewInteger<0L> >().Ref();
#endif
}
```

You have several choices. First, switch to a Microsoft platform that supports [Dynamic Initialization and Destruction with Concurrency](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2008/n2660.htm). I believe that requires VS2017 (and above and Windows 10 (and above).

Second, use Microsoft's `init_seg()`. You can do that by *uncommenting* the `#define USE_MSC_INIT_PRIORITY 1` around the top of `integer.cpp`.

Third, you can change the definition of `Integer::Zero()` (and friends) to return a new object for the integers. For example:

```
const Integer &Integer::Zero()
{
    return Integer(0);
}
```

**Comment by noloader** [comment]
> Adding a pointer member to the classes such as RSASSA_PKCS1v15_MD2_Signer or ...Verifier to clean up in destructors should work, but there could be better solutions.

Yes, that sounds like a good approach. Do you want to make a PR? I can test it this week. Otherwise I may not get to it until the weekend.

**Comment by irwir** [comment]
Ritht now my understanding of the library code is too superficial for a decent PR.
While everything created with the `new` operator must be deleted eventually, usage of templates and hidden static pointers complicates the matter.
By the way, `init_seg(lib)` is not going very well with the CRT heap debugger; because the tool would report memory leaks. It could be false positives, but that would be non-trivial to verify.

**Comment by irwir** [comment]
From brief reading of the sources it could be seen that automatic desturction was expected.
Apparently, `smiple_ptr` does not behave up to the expectations.
https://github.com/weidai11/cryptopp/blob/63b655d7ee77724cba0c6918a0f9971639f5bda1/misc.h#L337

**Comment by noloader** [comment]
Thanks @irwir.

Yeah, that particular code path will leak. When I say "that code path" I am talking about the Singleton code you are referring to. See the head notes on the function for the reason why.

What I am less sure about is, can we do away with the singleton-like pattern for RSA in this area.

**Comment by irwir** [comment]
> What I am less sure about is, can we do away with the singleton-like pattern for RSA in this area.

Memory leaks are not RSA-only feature.
Another run of the test program with heap profiling.
Calling `bool ValidateAll(bool thorough)` ends up with 249 unreleased heap blocks, 28.89KB in total.

The textbook example of singleton class, widely quoted in the net, has a built-in memory leak.
A library's own implementation of `unique_ptr` might be considered, and it should be highly portable.
More direct approach, would be to replace singletons with private members. Also that might end up with smaller binary code size.

**Comment by irwir** [comment]
I did more low-level tracing, and will close this as non-issue.
`static simple_ptr` objects are destroyed on program exit, as static objects should.
CRT heap debugger would not catch that, and even the latest VS profiler does not make that tracing trivial.
