### ISSUE TITLE
Access modifier in SIMON and SPECK

### ISSUE THREAD

**Issue by Blacktempel** [weidai11/cryptopp#643]
OS: Win 8.1 Pro 64-bit
Crypto++ Version: 7.0 / current master

The issue I see is in the block cipher algorithms SIMON and SPECK.

Here are 'ProcessAndXorBlock' and 'AdvancedProcessBlocks' inside the protected modifier of the class.
IMO this should be public instead like in the class 'BlockTransformation'.

**Comment by noloader** [comment]
Cleared at [Commit 63b655d7ee77](https://github.com/weidai11/cryptopp/commit/63b655d7ee77724cba0c6918a0f9971639f5bda1).
