### ISSUE TITLE
Build failure on Android

### ISSUE THREAD

**Issue by haoshuwen3** [weidai11/cryptopp#645]
I follow the guide of cross-compiling Crypto++ on the command line for Android. https://www.cryptopp.com/wiki/Android_(Command_Line), But I couldn't build successfully.
Here's the errors.

```
In file included from /opt/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/postypes.h:40:0,
                 from /opt/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/char_traits.h:40,
                 from /opt/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/string:40,
                 from stdcpp.h:14,
                 from cryptlib.h:103,
                 from cryptlib.cpp:18:
/opt/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/cwchar:44:19: fatal error: wchar.h: No such file or directory
 #include <wchar.h>
```

System (Centos 7 x64)
Version (6.1.0)

**Comment by noloader** [comment]
What version of Crypto++ are you using, and where did `setenv-android.sh` come from? Also, which compiler are you using?

**Comment by haoshuwen3** [comment]
@noloader Thank you for your help. I had solved the issue by upgrade NDK to the latest r16. The comand lines works fine now, however it couldn't compile by NDK-10 yet. 
The issue could be closed now.

**Comment by noloader** [comment]
> however it couldn't compile by NDK-10 yet.

I'm thinking you may have better luck with r10e by using [`TestScripts/setenv-android-old.sh`](https://github.com/weidai11/cryptopp/blob/master/TestScripts/setenv-android-old.sh).

The current `setenv-android.sh` was rewritten for the latest NDKs recently. Also see [Commit 7aa3377bbdfa](https://github.com/weidai11/cryptopp/commit/7aa3377bbdfa), where we stashed the old  `setenv-android.sh`  away under the name `setenv-android-old.sh` .
