### ISSUE TITLE
Unused parameter in Singleton

### ISSUE THREAD

**Issue by irwir** [weidai11/cryptopp#648]
https://github.com/weidai11/cryptopp/blob/55071c49c1dfdbc0b85a1c604bcd2298f92fa61d/misc.h#L290
https://github.com/weidai11/cryptopp/blob/55071c49c1dfdbc0b85a1c604bcd2298f92fa61d/misc.h#L311
https://github.com/weidai11/cryptopp/blob/55071c49c1dfdbc0b85a1c604bcd2298f92fa61d/misc.h#L312

The third parameter `instance` is never used in the library and could be removed.
Compilation and test run were successful.

**Comment by noloader** [comment]
I've thought about removing the instance parameter for several years. I think the potential problem with removing the parameter is non-library code may be using it in a nifty-counter.

**Comment by irwir** [comment]
Initially this parameter could be deprecated, and removed later.

**Comment by noloader** [comment]
@irwir,

Thanks again. I'm going to close this issue for now. If we move on something we will reference the this issue.
