### ISSUE TITLE
Recipe to not install test program and test data

### ISSUE THREAD

**Issue by alonbl** [weidai11/cryptopp#653]
Hi,

Can you please add conditional to the build system to avoid installing the test program and the test data?

The use case should be:
1. build
2. test
3. install (optional test prog/data)
4. test (if test prog/data is available)

In most cases downstream runs the check during build and these files are not required at root filesystem.

Thanks!

**Comment by alonbl** [comment]
thanks!

**Comment by gcsideal** [comment]
As Jeffrey (@noloader) noted, Debian compiles cryptest.exe as-is only the name is changed to cryptestcwd.exe . It can be used for testing before the actual installation.
Then it's compiled with the additional -DCRYPTOPP_DATA_DIR='"/usr/share/crypto++/"' to g++ leaving its filename intact and installed to the system. To be honest, the (cryptest.exe) system wide installation happens due to historical purposes. I have doubts anyone or anything uses that after compilation.

**Comment by noloader** [comment]
@gcsideal,

> To be honest, the (cryptest.exe) system wide installation happens due to historical purposes. I have doubts anyone or anything uses that after compilation.

Lol... I've wondered that myself. In the years (decades?) I have been following the library I don't recall anyone using it like, say, `openssl`. Or I don't recall seeing a question on it.

@alonbl, @gcsideal, @MarcelRaad, @mouse07410,

Is anyone aware of a standard target that installs the library only, and not the library and test program? I did not see one listed at [GNU Coding Standards | Standard Targets](https://www.gnu.org/prep/standards/html_node/Standard-Targets.html).

In the absence of a standard target, how does `install-lib` sound? It will copy the headers, the static archive (if present) and the dynamic library (if present)?

**Comment by alonbl** [comment]
The build system of your library is non-standard, proprietary and hard to maintain. The absent of standard build system that GNU is using (Autotools) or even cmake is obvious. This is why I was very much surprised that you chose GNU as a reference for that question.

The best practice would have a configure script in which one can specify how build system should behave, including, and not limited to, installing test programs, also obviously toolchain setting (CXX, AR...), location of directories (bindir, libdir) and features (enable-asm).

The build sequence should be as simple as:
```
./configure <options>
make
make check
make install DESTDIR=...
```

You can have custom configure script if you hate autotools, but the logic behind the build system is that you state what you need, then build (make) respect that.

Let's take the simple example of the pkg-config target you recently added after long time that it was asked... now it is yet another target of Makefile, I totally missed that since there is no way to extract the options using `./configure --help`, one of the users reported that so we have now two targets... actually three as we need all, shared, libcryptopp.pc.

**Comment by alonbl** [comment]
Deja-vu #327 :)

**Comment by noloader** [comment]
Cleared at [Commit a07a0e5e5f5f](https://github.com/weidai11/cryptopp/commit/a07a0e5e5f5f).

The old behavior for `make install` is still in tact. Issuing `make install` installs `cryptest.exe`, `libcryptopp.a` and `libcryptopp.so`. The new target is `install-lib`, and it installs only `libcryptopp.a` and `libcryptopp.so`.

**Comment by mouse07410** [comment]
P.S. I support `install-lib` target.

**Comment by gcsideal** [comment]
@noloader, Python has a not too much up-to-date configuration and build tools list: https://wiki.python.org/moin/ConfigurationAndBuildTools
You may check out SCons if you look for a popular Python based build tool: http://www.scons.org/

**Comment by alonbl** [comment]
I hear that Meson[1] is the new trend in python.

[1] http://mesonbuild.com/
