### ISSUE TITLE
Cryptopp 7.0.0 and gcc 8.1.0 - two issues

### ISSUE THREAD

**Issue by vgfl** [weidai11/cryptopp#657]
I found two issues compiling Cryptopp 7.0.0 with gcc 8.1.0. Maybe I did not choose the right compilation options?

The first one is in `rdrand.cpp`, there are two sections like this that 8.1.0 does not like:

```
#elif defined(GCC_RDRAND_ASM_AVAILABLE) && (CRYPTOPP_GCC_VERSION >= 40700)
    __asm__ __volatile__
    (
        INTEL_NOPREFIX
        ASL(1)
        AS1(rdrand rax)
        ASJ(jnc,   1, b)
        ATT_NOPREFIX
        : "=a" (*reinterpret_cast<word64*>(output))
        : : "cc"
    );
```

I commented them out to fall back on the old code for gcc, and compilation is fine.

The second issue is in pwdbased.h, which is not self contained any longer. It uses `ConstByteArrayParameter`, which is defined in `algparam.h`. `algparam.h` is not included in `pwdbased.h`.

**Comment by noloader** [comment]
Thanks @vgfl,

What distro are you using for GCC 8.10? Fedora is still using 7.3.1. (We had access to GCC 8, but it was on PowerPC, which did not exercise i686/x86_64 code paths).

**Comment by vgfl** [comment]
Yes, I am on 8.1.0.

**Comment by noloader** [comment]
@vgfl,

> Yes, I am on 8.1.0.

How did you get GCC 8.10. I want to duplicate the issues but I don't have an x86_86 machine with the compiler?

**Comment by vgfl** [comment]
Sorry, I saw my answer was dumb, I updated it with the right information… :-)

**Comment by noloader** [comment]
@vgfl,

Does this look about right for the `pwdbased.h` issue:

```
$ git diff
diff --git a/pwdbased.h b/pwdbased.h
index 20828a9..a27550a 100644
--- a/pwdbased.h
+++ b/pwdbased.h
@@ -12,6 +12,7 @@
 #include "hrtimer.h"
 #include "integer.h"
 #include "argnames.h"
+#include "algparam.h"^M
 #include "hmac.h"
```

It smoke tested OK.

**Comment by vgfl** [comment]
Yes! Thanks.

**Comment by noloader** [comment]
Thanks @vgfl,

The `pwdbased.h` issue was cleared at [Commit 4fc0fefc6e45](https://github.com/weidai11/cryptopp/commit/4fc0fefc6e45).

I'm going to close this since we are tracking the RDRAND issue at  [Issue 636](https://github.com/weidai11/cryptopp/issues/636) and [Pull Request 640](https://github.com/weidai11/cryptopp/issues/636).
