### ISSUE TITLE
Memory access violation (SIGSEGV) when try to call SHA512::Restart with dynamic linked library

### ISSUE THREAD

**Issue by asbai** [weidai11/cryptopp#661]
Linux / gcc 4.5.2 / x64. Crypto++ 7.0.0  build with -O3 -fPIC -msse4 -maes -mpclmul --param inline-unit-growth=200.

To reproduce this bug, run code:

```
CryptoPP::SHA512* p = new CryptoPP::SHA512
p->Restart(); // SIGSEGV here. The "state" argument of SHA512::InitState is 0x10 (wild pointer)!
```

If I build it as a static library, then everything is fine. If we rollback to the old 5.6.5 version, then the dynamic library the static library both working fine too.

I've been fight with it for a while, if I find more clues, I will append them here.

PS: SHA384 has the same problem, I guess all SHA2 family algorithms both have this issue. Other Hash algorithms such as MD5, WHIRLPOOL and RIPEMD just works fine.

**Comment by asbai** [comment]
I found it: some of our pre-defined macros will disturb the cryptopp7's Judging on the SHA_X86_ALIGN16 Macro. Put `#include <cryptlib.h>` on the first line of the precompiled header will fix it.

**Comment by noloader** [comment]
> some of our pre-defined macros will disturb the cryptopp7's Judging on the SHA_X86_ALIGN16 Macro.

Hmmm... Ideally the library will be hardened so that a user project is less sensitive than when building the library.

Let me see if there's something we can do, like move the `OptimalDataAlignment()` into a source (*.cpp) file so it is not sensitive to what the headers see or don't see.

**Comment by asbai** [comment]
But these changes may slightly drop the performance? I think performance is the first thing of a cryptographic library. :-)

More detail: As far as I understand, the root problem of this issue is: The memory layout of the SecBlock object is changed across different compilation unit.

For example: the address of its m_ptr (&m_ptr) of the same object (the this pointer is exactly same) is different between interhash.cpp and our test.cpp (8 bytes difference).

**Comment by anonimal** [comment]
>I think performance is the first thing of a cryptographic library

I'll opt for security / proper implementation as a first (not that this is the issue at hand though).

**Comment by noloader** [comment]
We are going to remove `SHA_X86_ALIGN16` and make the alignment full-time. That will fix your issue (effectively different compiler options) and clear an unaligned access problem on Sparc ([Issue 689](https://github.com/weidai11/cryptopp/issues/689)). I suspect the unaligned access problem affects MIPS too, but I have not been able to tickle it (yet).

**Comment by noloader** [comment]
Cleared at [Commit 45ffb7e82794](https://github.com/weidai11/cryptopp/commit/45ffb7e82794).
