### ISSUE TITLE
kalyna.h missing public access to Kalyna512_Info

### ISSUE THREAD

**Issue by clementmartin971** [weidai11/cryptopp#662]
line 166 there is missing "public" for Kalyna512_Info access
class Kalyna512 : Kalyna512_Info --> class Kalyna512 : public Kalyna512_Info

**Comment by noloader** [comment]
Thanks again @clementmartin971.

It looks like another copy/paste oversight.

**Comment by noloader** [comment]
Thanks again @clementmartin971.

It looks like another copy/paste oversight.

Cleared at [Commit 1543de863c57](https://github.com/weidai11/cryptopp/commit/1543de863c57).
