### ISSUE TITLE
Crypto++ 7 threefish.h Threefish512 and Threefish1024 potential trouble on declaration

### ISSUE THREAD

**Issue by clementmartin971** [weidai11/cryptopp#663]
```
line 116 class CRYPTOPP_NO_VTABLE Threefish512 : public Threefish_Base<32>
line 160 class CRYPTOPP_NO_VTABLE Threefish1024 : public Threefish_Base<32>
```

looking at declaration of Threefish256

```
line 72 class CRYPTOPP_NO_VTABLE Threefish256 : public Threefish_Info<32>
```

it seems Threefish512 and Threefish1024 should be derivated of Threefish_Info instead of Threefish_Base

May declaration should be

    class CRYPTOPP_NO_VTABLE Threefish512 : public Threefish_Info<64>

and 

    class CRYPTOPP_NO_VTABLE Threefish1024 : public Threefish_Info<128>

**Comment by noloader** [comment]
Also see [Commit d286f89b3f4d4a9a](https://github.com/weidai11/cryptopp/commit/d286f89b3f4d4a9a).
