### ISSUE TITLE
Threefish512::BLOCKSIZE and Threefish1024::BLOCKSIZE are not accessible

### ISSUE THREAD

**Issue by clementmartin971** [weidai11/cryptopp#664]
#issue #663 point another trouble than only size, it's the class derived by Threefish512 and Threefish1024. It should derive from `Threefish_Info` instead of `Threefish_Base` else `Threefish512::BLOCKSIZE` and `Threefish1024::BLOCKSIZE` are not accessible.

```
line 72:   class CRYPTOPP_NO_VTABLE Threefish256 : public Threefish_Info<32>
line 116:  class CRYPTOPP_NO_VTABLE Threefish512 : public Threefish_Base<64>
line 160:  class CRYPTOPP_NO_VTABLE Threefish1024 : public Threefish_Base<128>
```

**Comment by noloader** [comment]
Cleared at [Commit f320e7d92a33](https://github.com/weidai11/cryptopp/commit/f320e7d92a33).

**Comment by noloader** [comment]
Thanks again @clementmartin971.

**Comment by noloader** [comment]
Thanks again @clementmartin971.

Cleared at [Commit f320e7d92a33](https://github.com/weidai11/cryptopp/commit/f320e7d92a33).
