### ISSUE TITLE
SHA256 x64 code is 25% slower in version 7.0.0 than 5.6.5 built with MS VS2017/VS2015 Windows

### ISSUE THREAD

**Issue by tesbayda** [weidai11/cryptopp#674]
### Crypto++ Issue Report

I noticed that SHA256 hashing is much *slower* in 7.0.0 than 5.6.5.  

Overview of performance difference when hashing 512 MB block of memory with Intel Core i7-5820K Haswell-E with **SHA256 algorithm**:

lib version | elapsed tm | throughput
------------|------------|-----------
cryptlib.lib 5.6.5 x64 | 2.0 seconds | 290 MB/sec
cryptlib.lib 7.0.0 x64 | 2.7 seconds | 215 MB/sec
cryptlib.lib 5.6.5 x86 | 2.0 seconds | 290 MB/sec
cryptlib.lib 7.0.0 x86 | 2.0 seconds | 290 MB/sec

The 32-bit (x86) build of 7.0.0 runs quickly (2.0 seconds & 290 MB/sec).  It's the **64-bit x64** 7.0.0 library that is slower.

I suspect the performance drop was introduced with library version 6.0.0 that has the SIMD rewrite in `"sha-simd.cpp"`.  It looks like the older 5.6.5 used sha256 assembly code in `"x64dll.asm"`.

The output executable sizes compiled by MS VS2017 and shows the test file linked with v7.0.0 is about half the size:

    hash_benchmark565_x64.exe  423,424 bytes
    hash_benchmark700_x64.exe  219,648 bytes

GCC executable file sizes:

    -rwxrwxr-x.  1 johndoe johndoe 11624294 Jun 28 14:56 hash_bench_cryptopp565
    -rwxrwxr-x.  1 johndoe johndoe 13022276 Jun 28 14:57 hash_bench_cryptopp700

This performance difference appears to be a Windows specific issue. I also tried GCC on Linux 64-bit (CentOS) and the performance looks the same for both 5.6.5 and 7.0.0.  The GCC output executables for 5.6.5 and 7.0.0 are roughly the same -- and in fact -- the v7.0.0 is *larger* instead of smaller.  Therefore, maybe there's a missing/errant C++ preprocessor conditional compile that's affecting the x64 MSVC compilation in v7.0.0.

###### test code

```cpp

// x64 compiler:  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\bin\Hostx64\x64\cl.exe
// cl hash_benchmark.cpp cryptlib.lib /Fehash_benchmark565_x64 /O2 /GL /MT /INCREMENTAL:NO /I Y:\cryptopp565_VS2017 /link /LIBPATH:"Y:\cryptopp565_VS2017\x64\Output\Release"
// cl hash_benchmark.cpp cryptlib.lib /Fehash_benchmark700_x64 /O2 /GL /MT /INCREMENTAL:NO /I Y:\cryptopp700_VS2017 /link /LIBPATH:"Y:\cryptopp700_VS2017\x64\Output\Release"
// x86 compiler:  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\bin\Hostx86\x86\cl.exe
// cl hash_benchmark.cpp cryptlib.lib /Fehash_benchmark700_w32 /O2 /GL /MT /INCREMENTAL:NO /I Y:\cryptopp700_VS2017 /link /LIBPATH:"Y:\cryptopp700_VS2017\win32\Output\Release"
// cl hash_benchmark.cpp cryptlib.lib /Fehash_benchmark565_w32 /O2 /GL /MT /INCREMENTAL:NO /I Y:\cryptopp565_VS2017 /link /LIBPATH:"Y:\cryptopp565_VS2017\win32\Output\Release"

// GCC 64-bit compile and did not use CFLAGS -m32 to build a 32-bit binaries
// g++ -std=c++11 hash_benchmark.cpp -I ~/cryptopp700 -L ~/cryptopp700 -l cryptopp -o hash_bench_cryptopp700

#include <iostream>

#include "sha.h"

typedef unsigned char       BYTE;

void Testgroup(const BYTE *BufInput, const int iBuffersize, const char* szDesc = NULL)
{
  BYTE pbOutputBuffer[CryptoPP::SHA256::DIGESTSIZE];
  CryptoPP::SHA256 hash;
  hash.Restart();
  hash.Update(BufInput, iBuffersize);
  hash.Final(pbOutputBuffer);
}

int main(int argc, char* argv[])
{
  const size_t iBuffersize = (1048576L * 512L);
  auto *BufInput = new BYTE[iBuffersize];

  Testgroup(BufInput, iBuffersize, "test sha256");

  delete[] BufInput;
}
```

**Comment by noloader** [comment]
Thanks @tesbayda.

Yeah, It looks  like I broke it around BASE+SIMD]().

I think it is cleared at [Commit e18de4d5f996](https://github.com/weidai11/cryptopp/commit/e18de4d5f996). I know the SSE2 ASM code path is engaged. I don't know the performance numbers, though.

**Comment by tesbayda** [comment]
Ok, it looks like your commit fixed the performance for the x64 build.  I retested my benchmarks with the latest clone of the repo (`#define CRYPTOPP_VERSION 710`) and the sha256 performance is back to a throughput of 290 MB/sec like the 5.6.5 release.  Thanks for the quick fix!
