### ISSUE TITLE
AutoSeededRandomPool::GenerateBlock causes Segmentation Fault/Freeze

### ISSUE THREAD

**Issue by eriknellessen** [weidai11/cryptopp#68]
We noticed problems with CryptoPP when testing our eIDClientCore software (which uses CryptoPP as a shared library).

We created a minimal example, which could reproduce the problem on our systems.
Makefile:
```
PREFIX ?=$(shell pwd)
CRYPTOPP ?= cryptopp

all: cryptopp test_rand run

cryptopp:
	git clone https://github.com/weidai11/cryptopp.git $(CRYPTOPP)
	make -C $(CRYPTOPP) all libcryptopp.so
	make -C $(CRYPTOPP) install PREFIX=$(PREFIX)

test_rand: test_rand.cpp
	g++ -Iinclude -Llib -lcryptopp -lpthread -o test_rand test_rand.cpp

run: test_rand
	$(PREFIX)/test_rand
```
test_rand.cpp:
```
#include <cryptopp/osrng.h>
#include <cryptopp/secblock.h>
#include <iostream>
/*
 * http://www.cryptopp.com/wiki/RandomNumberGenerator#AutoSeededRandomPool
 */

int main(int argc, char* argv[]){
	// Scratch Area
	const unsigned int BLOCKSIZE = 16 * 8;
	CryptoPP::SecByteBlock scratch( BLOCKSIZE );

	// Construction
	CryptoPP::AutoSeededRandomPool rng;

	// Random Block
	std::cout<<"Before rng.GenerateBlock\n"<<std::flush;
	rng.GenerateBlock( scratch, scratch.size() );
	std::cout<<"After rng.GenerateBlock\n"<<std::flush;
	return 0;
}
```
The line
```
std::cout<<"After rng.GenerateBlock\n"<<std::flush;
```
is never reached. On OpenSUSE 32bit
```
3.16.7-29-desktop #1 SMP PREEMPT Fri Oct 23 00:46:04 UTC 2015 (6be6a97) i686 i686 i386 GNU/Linux
```
we got a segmentation fault. On OpenSUSE 64bit
```
3.16.7-29-desktop #1 SMP PREEMPT Fri Oct 23 00:46:04 UTC 2015 (6be6a97) x86_64 x86_64 x86_64 GNU/Linux
```
the program is stuck.

**Comment by noloader** [comment]
Forgive my ignorance... Is this the page I want to duplicate the OpenSUSE environment with 3.16.7-29-desktop?

 *  [Download openSUSE Leap 42.1](https://software.opensuse.org/421/en)

**Comment by eriknellessen** [comment]
To be honest, I am not sure, but I think it is the correct page.

By the way, I could not reproduce the problem on my Debian Jessie 32bit,
```
3.16.0-4-686-pae #1 SMP Debian 3.16.7-ckt11-1+deb8u6 (2015-11-09) i686 GNU/Linux
```

**Comment by noloader** [comment]
I cannot duplicate under Leap 42.1, x86_64. Here's what I did:

1) Git clone
2) `make static dynamic test` (all tests pass)
3) `rm libcryptopp.a` (force dynamic linking)
3) `touch tt.cxx`
4) paste your program into tt.cxx
5) compile with `g++ tt.cxx -o tt.exe ./libcryptopp.so -lpthread`

It results in:

    cryptopp-git> ./tt.exe 
    Before rng.GenerateBlock
    After rng.GenerateBlock

------

For completeness, I followed with:

    cryptopp-git> make static dynamic test
    cryptopp-git> sudo make install PREFIX=/usr

And then:

    cryptopp-git> make distclean (clean all artifacts, use stuff in /usr)
    cryptopp-git> g++ -Iinclude -Llib -lcryptopp -lpthread -o tt.exe tt.cxx

Oops:

    cryptopp-git> ./tt.exe 
    ./tt.exe: error while loading shared libraries: libcryptopp.so: cannot open shared object file: No such file or directory

It looks like the library is there:

    cryptopp-git> ls /usr/lib | wc -l
    293
    cryptopp-git> ls /usr/lib | grep libcryptopp.so
    libcryptopp.so

I have to admit I know nothing about Gentoo and OpenSUSE.

-----

Here's the GCC version on this machine:

    cryptopp-git> g++ --version
    g++ (SUSE Linux) 4.8.5
    Copyright (C) 2015 Free Software Foundation, Inc.
    ...

------

If I had to guess (and its purely a guess), I'd guess there's a Crypto++ already installed, and something is being mixed and matched with the one you cloned locally.

**Comment by noloader** [comment]
@erik - were you able to make any progress on diagnosing the cause? Can you provide me with remote access so I can look at things?

**Comment by noloader** [comment]
@erik - were you able to isolate the issue here? or can you provide steps on how to reduce this to a testable case for me? (or perhaps you can give me access to the machine in question)?

**Comment by eriknellessen** [comment]
I will be able to provide more information on Wednesday. I will then have access to the machine on which the error occurred and I will try to track down the error/make it reproducible for you.

**Comment by eriknellessen** [comment]
Today, I could do some further testing. It turned out that
LD_LIBRARY_PATH=$(PREFIX)/lib/ $(PREFIX)/test_rand
runs without problems, while
$(PREFIX)/test_rand
still fails. I think, that your guess is right. When building, the freshly cloned CryptoPP headers are used. When running, the linker takes the shared object files of the already installed version of CryptoPP.

We never noticed this, because the installed version and the version we installed from source were the same/worked with each other. The problem came with the new updates for 5.6.3, probably it was 025337a94aceb75d188149db70c2094673772816.

We now tell the linker explicitly which shared object file to use and everything works fine. So from my side, this issue can be closed.

**Comment by noloader** [comment]
Ah, OK very good. Thanks for getting back to us.

Sorry about causing you grief. We are strengthening polices and procedures to avoid accidental breaks to master in the future. See, for example, [Botched 5.6.3 Check-in](https://groups.google.com/d/msg/cryptopp-users/JLuTifAuv0M/tFbbP8tbBAAJ) and the result: [Crypto++ Release Process](https://cryptopp.com/wiki/Release_Process#The_Process).
