### ISSUE TITLE
NuGet: Package is out of date. Current newest available version is 5.6.5.4

### ISSUE THREAD

**Issue by wbbarnes** [weidai11/cryptopp#692]
Not sure I'd really call this a direct issue. However with the NuGet version stuck on 5.6.5.4 stable, I think it's safe to say that other issue corrections and enhancements between then and the current version are not there. ( Two NuGet links: One credited to Scott Lee (cryptopp), and one by Dmitry Katkevich (cryptopp.v140.windesktop.dyn.rt-static). Both link here for License, Project URL, and Report Abuse links.)

To be honest this may not even belong here. (if not please forward to the right people and go ahead and close this ticket.)

**Comment by noloader** [comment]
Thanks @wbbarnes.

We don't package for NuGet; someone else does. I can't find the fellow's name and email address at the moment.

**Comment by wbbarnes** [comment]
Sent a message via the NuGet site to Dmitry katkevich (katkevich), and Scott Lee (smasherprog) and included a link to this ticket.  Hopefully this will help get this out.
