### ISSUE TITLE
'D': unreferenced local variable (VS 2017)

### ISSUE THREAD

**Issue by irwir** [weidai11/cryptopp#693]
https://github.com/weidai11/cryptopp/blob/5ea410c1d33e4201c24e52b343110b90a3d9f85e/sha.cpp#L1189

**Comment by noloader** [comment]
Thanks @irwir.

That was part of some Sparc testing a couple of weeks ago. It should have been removed at [Commit 4aafb0e6a3c3](https://github.com/weidai11/cryptopp/commit/4aafb0e6a3c3).

Do you want to clear it?

In the future just send the PR. We merge it as soon as it lands.
