### ISSUE TITLE
ChaCha20-Poly1305 support

### ISSUE THREAD

**Issue by xdqi** [weidai11/cryptopp#697]
Thanks for your hard work on this library!

ChaCha20-Poly1305 is a modern, high-performance cipher working in AEAD mode.
I've noticed that cryptopp has support for original chacha20 only.

Would you implement the original ChaCha20-Poly1305([link])?

[link]: https://download.libsodium.org/doc/secret-key_cryptography/original_chacha20-poly1305_construction.html

**Comment by noloader** [comment]
The library provides both ChaCha20 and Poly1305.

I guess we need a wiki page on combining them from primitives.
