### ISSUE TITLE
Remove MAINTAIN_BACKWARDS_COMPATIBILITY_562

### ISSUE THREAD

**Issue by noloader** [weidai11/cryptopp#70]
Crypto++ 5.6.3 cleared a number of issues uncovered by analysis and testing tools. To maintain compatibility with Crypto++ 5.6.2, `MAINTAIN_BACKWARDS_COMPATIBILITY_562` was introduced. It allowed us to clear _most_ of the findings while maintaining compatibility. If `MAINTAIN_BACKWARDS_COMPATIBILITY_562` was not defined, then _all_ the issues were mitigated.

Future version of Crypto++ will not need `MAINTAIN_BACKWARDS_COMPATIBILITY_562` because compatibility with 5.6.2 is not a concern. That is, Crypto++ 5.7 or 6.0 will not need it because advancement is expected, and there are no guarantees. Also see [Release Versioning](http://cryptopp.com/wiki/Release_Versioning) on the Crypto++ Wiki.

Distributions, like Debian and Fedora, are currently incorporating 5.6.3. In about 30 days, we should remove `MAINTAIN_BACKWARDS_COMPATIBILITY_562` so GitHub users enjoy the most stable code.

---

We should also remove warning suppression of C4505 from `config.h`:

```
#pragma warning(disable: 4127 4231 4250 4251 4275 4505 4512 4660 4661 4786 4355 4910)
```

**Comment by DevJPM** [comment]
>In about 30 days

We're now approaching the 60 days post release of 5.6.3. Should we remove the `MAINTAIN_BACKWARDS_COMPATIBILITY_562`?

(just bumping)

**Comment by noloader** [comment]
> We're now approaching the 60 days post release of 5.6.3. Should we remove the MAINTAIN_BACKWARDS_COMPATIBILITY_562?

Yeah, I did not want to jump the gun and yank it too soon. I was concerned we may have to [unexpectedly] release a 5.6.4, which would have needed it, too.

Do you want to make a Pull Request?

**Comment by noloader** [comment]
Do you think `CRYPTOPP_MAINTAIN_BACKWARDS_COMPATIBILITY` should be removed, too?

I'm not sure it should occur at minor version bump since its removing symbols. It should probably wait until 6.0.

```
$ grep CRYPTOPP_MAINTAIN_BACKWARDS_COMPATIBILITY *.h *.cpp | grep -v 562
config.h:// #define CRYPTOPP_MAINTAIN_BACKWARDS_COMPATIBILITY
cryptlib.h:#ifdef CRYPTOPP_MAINTAIN_BACKWARDS_COMPATIBILITY
cryptlib.h:#ifdef CRYPTOPP_MAINTAIN_BACKWARDS_COMPATIBILITY
cryptlib.h:#ifdef CRYPTOPP_MAINTAIN_BACKWARDS_COMPATIBILITY
cryptlib.h:#ifdef CRYPTOPP_MAINTAIN_BACKWARDS_COMPATIBILITY
cryptlib.h:#ifdef CRYPTOPP_MAINTAIN_BACKWARDS_COMPATIBILITY
cryptlib.h:#ifdef CRYPTOPP_MAINTAIN_BACKWARDS_COMPATIBILITY
cryptlib.h:#ifdef CRYPTOPP_MAINTAIN_BACKWARDS_COMPATIBILITY
cryptlib.h:#ifdef CRYPTOPP_MAINTAIN_BACKWARDS_COMPATIBILITY
cryptlib.h:#ifdef CRYPTOPP_MAINTAIN_BACKWARDS_COMPATIBILITY
cryptlib.h:#ifdef CRYPTOPP_MAINTAIN_BACKWARDS_COMPATIBILITY
eccrypto.h:#ifdef CRYPTOPP_MAINTAIN_BACKWARDS_COMPATIBILITY
filters.h:#ifdef CRYPTOPP_MAINTAIN_BACKWARDS_COMPATIBILITY
gfpcrypt.h:#ifdef CRYPTOPP_MAINTAIN_BACKWARDS_COMPATIBILITY
modes.h:#ifdef CRYPTOPP_MAINTAIN_BACKWARDS_COMPATIBILITY
```

**Comment by DevJPM** [comment]
> Do you want to make a Pull Request?

No. My fork is currently messed up a little (as you may have noted with the integer patch). So please just go ahead and apply the recommended config settings (from my point).

-----
> Do you think `CRYPTOPP_MAINTAIN_BACKWARDS_COMPATIBILITY` should be removed, too?

Hard to say. It should definitely be removed when we get to 6.0.
It's an unfortunate state that so many functions are hidden behind the `CRYPTOPP_MAINTAIN_BACKWARDS_COMPATIBILITY` (which defaults to "not defined"). 

I think we should wait until 6.0 to remove it.

After all, 6.0 is scheduled to be released soon(tm) (e.g. this or next year I hope) and so the define can wait a little more in our code (and doesn't actually cause us pain anywhere).

**Comment by noloader** [comment]
`MAINTAIN_BACKWARDS_COMPATIBILITY_562` mostly guards virtual destructors. According to [Exceptions across binary boundary](http://stackoverflow.com/a/10962454/608639), the virtual destructor should be the first virtual function of a class:

> I had similar problems with gcc < 4.5 with RTTI symbols used across shared library boundaries, but not with gcc 4.6. However, you might still find the following information useful.
>
> As already mentioned, the vtable (containing an entry to the typeinfo object) for EException seems to be duplicated in some translation units which was definitely a problem with gcc < 4.5 (well, it is an issue of libsupc++, as far as I know, not merging the type_info objects). Anchoring the vtable of EException by defining a virtual out-of-line destructor (it must be the first virtual function declaration in the header) in A did the trick for me.

**Comment by noloader** [comment]
This was cleared in `config.h` at [Commit f57c4dced5bfbcd1](http://github.com/weidai11/cryptopp/commit/f57c4dced5bfbcd10d0883ae7161833a70eff268). It effectively puts the library in a good state out-of-the-box.

We still have to remove the use of `MAINTAIN_BACKWARDS_COMPATIBILITY_562` preprocessor macro. That will occur at Crypto++ 5.7 or 6.0. Man, I can't wait...

**Comment by noloader** [comment]
Cleared at [Commit 40230dd3bf54](http://github.com/weidai11/cryptopp/commit/40230dd3bf5400ec3fda20cc791fb05c7a1c5b62).
