### ISSUE TITLE
Redefinition wanings in aria.cpp

### ISSUE THREAD

**Issue by irwir** [weidai11/cryptopp#702]
Two identical warnings in VS 2017 while compiling the library.
```
Severity	Code	Description	Project	File	Line
Warning	C4456	declaration of 'block' hides previous local declaration	cryptlib	cryptopp\aria.cpp	151
Warning	C4456	declaration of 'block' hides previous local declaration	cryptlib	cryptopp\aria.cpp	156
```
For a fix, renaming `block` in lines 141 and 142 might be slightly cheaper compared to changing in two diagnosed location (4 lines to change).

**Comment by noloader** [comment]
In the future just send the PR. We merge it as soon as it lands.
