### ISSUE TITLE
PEM Pack missing support for PKCS#8 Private Key

### ISSUE THREAD

**Issue by avalon1610** [weidai11/cryptopp#706]
Download PEM pack from [wiki](https://www.cryptopp.com/wiki/Pem_pack). 
but it is missing support for PKCS#8 private key, which begin with `-----BEGIN PRIVATE KEY-----`.
I looked the source then found:
```
PEM_Type PEM_GetType(const SecByteBlock& sb)
{
    SecByteBlock::const_iterator it;

    it = Search(sb, SBB_PUBLIC_BEGIN);
    if(it != sb.end())
        return PEM_PUBLIC_KEY;

   /* missing branch of SBB_PRIVATE_BEGIN here */

    // RSA key types
    it = Search(sb, SBB_RSA_PUBLIC_BEGIN);
    if(it != sb.end())
        return PEM_RSA_PUBLIC_KEY;
 
   ......
```

**Comment by noloader** [comment]
Thanks @avalon1610. What do you suggest here?

The way the classes are setup you need to know the key type in advance. Something like:

```
RSA::PrivateKey key;
PEM_Load(bt, key);
```

Should we try to parse it as a RSA key (or whatever key is used by the caller) and allow the machinery to throw a `BERDecode` error?

**Comment by avalon1610** [comment]
In my opinion, when it's pkcs#8 key, we should check the oid first, then advance to the `PrivateKey` , which will be 26bytes in RSA PrivateKey (24bytes in RSA PublicKey), then parse it as a pkcs#1 RSA key
```
PrivateKeyInfo ::= SEQUENCE {
    version         Version,
    algorithm       AlgorithmIdentifier,
    PrivateKey      BIT STRING
}

AlgorithmIdentifier ::= SEQUENCE {
    algorithm       OBJECT IDENTIFIER,
    parameters      ANY DEFINED BY algorithm OPTIONAL
}
```

**Comment by noloader** [comment]
@avalon1610,

I move the PEM files to a GitHub to make it easier to manage changes. Also see [cryptopp-pem](https://github.com/noloader/cryptopp-pem).

Do you want collaborator role?

**Comment by avalon1610** [comment]
I have tried this commit, it works. Good job!

BTW, since pem pack files will be putted into cryptopp project and compile together, it will need add precompiled header at the beginning of files (#include “pch.h").

**Comment by noloader** [comment]
> it will need add precompiled header at the beginning of files (#include “pch.h").

Yeah, that should be OK.
