### ISSUE TITLE
Compiling without RTTI support

### ISSUE THREAD

**Issue by k15tfu** [weidai11/cryptopp#712]
I have a project with disabled RTTI and I was planning to compute sha512 using cryptopp, and but it turned out that it uses typeid() in a few places.

After some investigation I have realized that these functions (which referencing typeid()) are not used when computing sha512, and the library can be compiled with MSVC on Windows (because templates are not instantiated) but not on Linux with GCC/Clang (godbolt: https://godbolt.org/z/Zqsau8).

Is there a way (without redefinition of typeid) to compile with RTTI switched off?  May be it would be possiable to add ifdef guard to cut typeid related methods off?

**Comment by noloader** [comment]
> Is there a way (without redefinition of typeid) to compile with RTTI switched off? May be it would be possible to add ifdef guard to cut typeid related methods off?

Probably not. Most of the library depends on passing arbitrary parameters through [`NameValuePairs`](https://www.cryptopp.com/wiki/NameValuePairs), and `NameValuePairs` depends on `typeid`.

The big offender is [`algparam.h`](https://github.com/weidai11/cryptopp/blob/master/algparam.h) and `GetValueHelperClass`. That's where arbitrary values are read and written.

**Comment by noloader** [comment]
> I was planning to compute sha512 using cryptopp, and but it turned out that it uses typeid() in a few places.

For this piece, I may be able to help you get a stand-alone SHA512 without the need for Botan, Crypto++, OpenSSL, etc. Crypto++ has a C++ and SSE2 implementation. Do they fit you your needs? You will have to wire-up checks like `HasSSE2()`.

**Comment by k15tfu** [comment]
Yes I think

**Comment by noloader** [comment]
Closing issue.
