### ISSUE TITLE
LegacyDecryptor and LegacyDecryptorWithMAC use wrong MAC

### ISSUE THREAD

**Issue by noloader** [weidai11/cryptopp#714]
Crypto++ 6.0 changed `DefaultDecryptor` and `DefaultDecryptorWithMAC` to use modern algorithms. Also see [Issue 345](https://github.com/weidai11/cryptopp/issues/345).

At that time we also provided `LegacyDecryptor` and `LegacyDecryptorWithMAC` for folks who needed interop with the older algorithm. We botched the interop by using the new MAC (SHA256-based) instead of the old MAC (SHA1-based). Also see [Update DefaultEncryptor, DefaultEncryptorWithMAC and friends](https://groups.google.com/d/msg/cryptopp-users/epq6IjEKwLY/3Y0HY3y-BwAJ).

This ticket will track the change to `LegacyDecryptor` and `LegacyDecryptorWithMAC` for SHA1-based MACs.

**Comment by noloader** [comment]
Cleared at [Commit 590f8573c4ed](https://github.com/weidai11/cryptopp/commit/590f8573c4ed).

**Comment by AndiDog** [comment]
Can this make it into a release soon? This has been wrong all the way between [6.0.0, 7.0.0] and without the patch, we cannot safely replace existing code to use the legacy algorithms.

**Comment by noloader** [comment]
@AndiDog,

Right now we are blocking on https://github.com/weidai11/cryptopp/issues/649 .

I wanted to get a few more things added before the next release but I have not had time. I think its time to shit or get off the pot. We'll release as soon as we clear the AES problems on Windows.
