### ISSUE TITLE
TLS Certificate of www.cryptopp.com expired - please renew!

### ISSUE THREAD

**Issue by iromeister** [weidai11/cryptopp#715]
When trying to update cryptopp on my Gentoo Linux system, I ran into the message that the certificate for www.cryptopp.com just expired, which prevented emerge from downloading the package.

Please renew your certificate ASAP! This should not happen at all with the website of a crypto library...

**Comment by noloader** [comment]
Thanks @iromeister,

Yeah, we have been trying to renew it since last week. Also see [Installing new certificate](https://groups.google.com/d/msg/cryptopp-users/w7j2lTHtK6E/A2xszlqNCAAJ) on the mailing list.

**Comment by noloader** [comment]
So there seems to be a problem with our Common Name. We attempted to Use ***Crypto++ Project***.

Both the CA/Browser Baseline Requirements and RFC 5280 deprecate and discourage use of a hostname in the Common Name. The Baseline Requirements goes further and says hostname or nothing. We selected nothing.

Two requests have been made to use a CSR without a Common Name to ensure we comply with the CA/Browser Baseline Requirements and RFC 5280. We have to make manual requests and wait for support because the Comodo web form has a bug in it and won't let us upload the CSR.

**Comment by noloader** [comment]
We got the Let's Encrypt software agent problems worked out when using Red Hat's Software Collections (SCL). The certificate was installed this morning.

**Comment by EduardoMiravalls** [comment]
I know this was a closed issue, but as of today, the certificate is expired again. This error affects the wiki as well.
Maybe the auto-renewal process failed?

**Comment by noloader** [comment]
Thanks @EduardoMiravalls,

My bad, I knew it was expiring soon. I should have got to it sooner. Let me tend to it now. (I'm neck deep in x25519 and ed25519 atm).

> Maybe the auto-renewal process failed?

Yeah, it has problems on our VM. Our machine is CentOS 7, but it has the SCL repos enabled so we can get an updated web server and php. Some of the commands used by certbot assume old paths of `/usr`, and it has problems with components located in `/opt/rh`.

```
[root@ftpit html]# ls /opt/rh
httpd24  python27  rh-php71
```

**Comment by EduardoMiravalls** [comment]
That's ok, now it works. Thank you!

**Comment by noloader** [comment]
@EduardoMiravalls,

No problems, and thanks for pointing it out.

I uploaded the instructions for updating the certifcate to the website's GitHub. It is in Wei's GitHub next to Crypto++ at [cryptopp-website](https://github.com/weidai11/website):

```
$ cat letsencrypt.txt
1. Log-in to VM, su to root.
   CD to root's home.
   An existing CSR using the existing key is in Home

2. Open a second terminal, su to root
   CD to cd /var/www/html/.well-known/acme-challenge/
   Remove past challenges
 
3. letsencrypt --manual --csr ~/cryptopp-com.req.pem auth
   This terminal is now occupied by LE client.
   LE client will send requests and receive responses.
   You will create the nessary files in the second terminal
   Once the challenges have been accepted client will download new cert.

4. Once the certifcate issues, copy it to cryptopp-com.pem
   # cp 0003_chain.pem /etc/pki/tls/certs/cryptopp-com.pem
   cp: overwrite ‘/etc/pki/tls/certs/cryptopp-com.pem’? y

----------

# find /etc/ -name 'cryptopp*.pem'
/etc/pki/tls/private/cryptopp-com.key.pem
/etc/pki/tls/certs/cryptopp-com.pem
/etc/pki/tls/certs/cryptopp-com.chain.pem
```

**Comment by Genocidicbunny** [comment]
Seems the certificate has expired again.

**Comment by noloader** [comment]
Thanks @Genocidicbunny. I rewed the certificate.
