### ISSUE TITLE
Windows compile problem

### ISSUE THREAD

**Issue by mq1n** [weidai11/cryptopp#717]
Hello, When I try compile my project with cryptopp static library there are happens some compile problems. I've tried on current master branch version.

Warning	C4003	not enough arguments for function-like macro invocation 'F'	NM_Engine	d:\workspace\anti\current projects\nomercy\extern\cryptopp\misc.h	294	
Error	C2760	syntax error: unexpected token ')', expected 'expression'	NM_Engine	d:\workspace\anti\current projects\nomercy\extern\cryptopp\misc.h	294	
Error	C2059	syntax error: ')'	NM_Engine	d:\workspace\anti\current projects\nomercy\extern\cryptopp\misc.h	294	
Error	C1903	unable to recover from previous error(s); stopping compilation	NM_Engine	d:\workspace\anti\current projects\nomercy\extern\cryptopp\misc.h	301	

![Image](https://vgy.me/ZZfvcu.png)

IDE: Visual studio 2017(17134 SDK toolset), c++17 enabled.

**Comment by noloader** [comment]
Please see [Visual Studio](https://www.cryptopp.com/wiki/Visual_studio) on the Crypto++ wiki.

**Comment by Scui1** [comment]
I get the same issues, have you found a fix in the meantime?

**Comment by noloader** [comment]
@Scui1 ,

Sorry, no fixes. I have not encountered the problem.

Also see [Bug Report](https://cryptopp.com/wiki/Bug_Report) on the Crypto++ wiki.

**Comment by Scui1** [comment]
> 
> 
> @Scui1 ,
> 
> Sorry, no fixes. I have not encountered the problem.
> 
> Also see [Bug Report](https://cryptopp.com/wiki/Bug_Report) on the Crypto++ wiki.
Sry that was totally my bad. I compared my solution file to the crypto++ solution file and found out I turned off / didn't have the preprocessor flag "USE_PRECOMPILED_HEADERS" set. What I've also encountered issues in is when you use any encryption method you should turn off all optimizations. At least for me that caused different results when encrypting with optimization on and off. Hope I could help anyone that came here by google searching.
