### ISSUE TITLE
clang compilation error on cpu.cpp

### ISSUE THREAD

**Issue by gvisol** [weidai11/cryptopp#72]
Dear all,
Please take note of this source code compiling error:

Platform:
    OSX 10.10

Compiler clang
  Version:
    Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
    Target: x86_64-apple-darwin14.4.0
    Thread model: posix

Command:
    /usr/bin/clang++ -arch i386 -DCRYPTOPP_DISABLE_ASM  cpu.cpp

Error:
   cpu.cpp:104:4: error: register %rbx is only available in 64-bit mode
                        "pushq %%rbx; cpuid; mov %%ebx, %%edi; popq %%rbx"
                        ^
<inline asm>:1:8: note: instantiated into assembly here
        pushq %rbx; cpuid; mov %ebx, %edi; popq %rbx
              ^~~~~
cpu.cpp:104:4: error: register %rbx is only available in 64-bit mode
                        "pushq %%rbx; cpuid; mov %%ebx, %%edi; popq %%rbx"
                        ^
<inline asm>:1:42: note: instantiated into assembly here
        pushq %rbx; cpuid; mov %ebx, %edi; popq %rbx
                                                ^~~~
2 errors generated.

Note:
   In clang600.0.57 did not appear such error, but rbx is not a 32 bit register.

Thank you in advance,

Gabriel Solsona

**Comment by noloader** [comment]
>     :1:8: note: instantiated into assembly here
>     pushq %rbx; cpuid; mov %ebx, %edi; popq %rbx
>     ^~~~~
>     cpu.cpp:104:4: error: register %rbx is only available in 64-bit mode
>     "pushq %%rbx; cpuid; mov %%ebx, %%edi; popq %%rbx"

This is interesting in a morbid sort of way... The code above if for X32 (not X86, and not X64). X32 is 32-bit integers, longs and pointers. When using X32, we must push and pop 64-bit registers. 

According to the [System V Application Binary Interface, AMD64 (With LP64 and ILP32 Programming Models)](http://sites.google.com/site/x32abi/documents/abi.pdf), `__ILP32__` and ` _ILP32` are the two ways to detect it in the preprocessor. The code is activated when the preprocessor defines `__ILP32__`.

Now:

    $ clang++ --version
    clang version 3.6.0 (tags/RELEASE_360/final)
    Target: x86_64-apple-darwin12.6.0
    Thread model: posix

And:

    $ clang++ -arch i386 -dM -E - < /dev/null | egrep -i "(86|64|ilp)" | egrep -v "(FAST|LEAST|INT)"
    #define _ILP32 1
    ...
    #define __ILP32__ 1
    ...
    #define __i386 1
    #define __i386__ 1
    #define i386 1

This looks like a Clang bug to me. I don't believe it should be defining ILP32. Or if it does, it should allow us to push/pop 64-bit registers.

Let me talk with the Clang devs to formulate a work-around.

**Comment by noloader** [comment]
Thanks for the patience Gabriel.

I moved the conversation to the [CFE Dev list](http://lists.llvm.org/pipermail/cfe-dev/2015-December/046300.html). The Clang devs recommend using both  `__ILP32__` and `x86_64` to detect X32. I was leaning towards the same, but wanted a recommendation since this could affect other platforms, like AARCH64/ARM64.

I plan on checking in something like the following once it is tested:

    $ git diff config.h 
    diff --git a/config.h b/config.h
    index 638bc3c..50e34cf 100644
    --- a/config.h
    +++ b/config.h
    @@ -468,8 +468,9 @@ NAMESPACE_END
     #endif
        
     // Linux provides X32, which is 32-bit integers, longs and pointers on x86_64 u
    -// Detect via __ILP32__ (http://wiki.debian.org/X32Port). Both GCC and Clang pr
    -#if ((__ILP32__ >= 1) || (_ILP32 >= 1))
    +// Detect via __ILP32__ (http://wiki.debian.org/X32Port). However, __ILP32__ sh
    +// the System V ABI specs calls out, like on just about any 32-bit system with 
    +#if ((__ILP32__ >= 1) || (_ILP32 >= 1)) && defined(__x86_64__)
            #define CRYPTOPP_BOOL_X32 1
     #else
            #define CRYPTOPP_BOOL_X32 0

We will also be adding some more test cases for both GCC and Clang to detect this sort of thing in the future. For Clang on OS X, we will use both `-arch i386` and `-arch x86_64`. For GCC and Clang, we will use both `-m32` and `-mx32`.

**Comment by gvisol** [comment]
Dear Jeffrey, thank you to you indeed for being so diligent!

Tell me if you want to check something in my system in order to help you in assuring a stable modification.

I am at your disposal.

Cheers,

Gabriel Solsona

**Comment by noloader** [comment]
Fixed at commit [c08cac0cd151a0af](https://github.com/weidai11/cryptopp/commit/c08cac0cd151a0afc616c38189ce9d7025145b96). I could not complete Debian 8/X32 testing. It looks like something is bent in their infrastructure.

**Comment by noloader** [comment]
@Gabriel,

> Tell me if you want to check something in my system in order to help you in assuring a stable modification.

How did you make out with this fix?

The `cryptest.sh` was also updated to include testing for breaks like this. If you have 3 to 4 hours to kill, you can run a `./cryptest.sh`. I should come back with no errors as detailed at [Release Process | Test Script](https://cryptopp.com/wiki/Release_process#Test_Script) on the wiki.
