### ISSUE TITLE
Build for Android: #include <string>

### ISSUE THREAD

**Issue by damaex** [weidai11/cryptopp#74]
- New virtual machine (android-ndk in home dir)
- Pulled the sources directly from git
- got the setenv-android.sh from the wiki

- Building like
```
AOSP_API="android-8" . ./setenv-android.sh
make -f GNUmakefile-cross static dynamic cryptest.exe
```

It looks like the setenv.sh sets everything right, cause the used compiler is already the right one (arm-linux-adroideabi-g++) but unfortunately the environment doesn't get the include path for the stl-classes.

```
stdcpp.h:9:18: fatal error: string: No such file or directory
#include <string>
```

If i check the environment value AOSP_STL_INC, it is set to an existing path (from the android-ndk).
```
AOSP_STL_INC: /home/user/android-ndk-r10e/sources/cxx-stl/stlport/stlport/
```

So, is it my fault it's not running like this?

**Comment by noloader** [comment]
> got the setenv-android.sh from the wiki

You also need the updated `GNUmakefile-cross`.

> So, is it my fault it's not running like this?

No, we changed things on you. They are waiting to be checked-in.

**Comment by damaex** [comment]
Oh my...
That really kicked it going, thanks a lot!

**Comment by noloader** [comment]
@damaex - yeah, sorry about things.... I'm going to update the `setenv-android.sh` script to export the old and new variables. It should get others past this issue (but it won't save you from the aggravation :)

**Comment by noloader** [comment]
@damaex - We are now tracking this at [Add setenv scripts for Makefile based cross-compiles](https://github.com/weidai11/cryptopp/issues/76).

It was planned, but I think its better to formally track it.

**Comment by noloader** [comment]
@damaex - we checked-in the updated [GNUmakefile-cross](https://github.com/weidai11/cryptopp/blob/master/GNUmakefile-cross) at [5703c85d2dfd](https://github.com/weidai11/cryptopp/commit/5703c85d2dfdb01e4d3f46743f388db77866600a).

You still need the `setenv-android.sh` script, but things should "just work" for you again. I still need to test the `CXXFLAGS` for MIPS, MIPS64 and NEON. Once I do, I'll ask for approval to commit the script for the upcoming 5.7/6.0.
