### ISSUE TITLE
Typo on HexDecoder help wiki page

### ISSUE THREAD

**Issue by adityapk00** [weidai11/cryptopp#740]
### Crypto++ Issue Report
On the HexDecoder wiki page - https://www.cryptopp.com/wiki/HexDecoder
Section **"Decoding a String (Filter)"**
Code example is missing the `true /*pumpAll*/` as the second argument. Because of that, the code sample doesn't work. It should read:

```
StringSource ss(encoded, true /* pumpAll */,
    new HexDecoder(
        new StringSink(decoded)
    ) // HexDecoder
); // StringSource
```

**Comment by noloader** [comment]
Yeah, looks like a copy/paste typo on two of the decoder pages.

Fixed, and thanks.
