### ISSUE TITLE
Make-based cpu feature tests and language

### ISSUE THREAD

**Issue by noloader** [weidai11/cryptopp#741]
While working [Issue 656](https://github.com/weidai11/cryptopp/issues/656) it suddenly occurred to me... This *"bad result"* is not internationalized (from [GNUmake, around line 100](https://github.com/weidai11/cryptopp/blob/master/GNUmakefile#L102)):

```
BAD_RESULT="fatal|error|unknown|unrecognized|illegal|ignored|incorrect|not found|not exist|
  cannot find|not supported|not compatible|no such instruction|invalid mnemonic"
```

At this time we seem to have been running between the cracks. It seems we have been using English testers and modern Linux systems that have all the feature support. I think we need to fix the gap before it becomes a widespread problem.

We have several choices:

1. Revert to toolchain version numbers

2. Require folks to perform an English compile

3. Add international language support

4. Use output artifact as the gate

5. Use a "clean compile" as the gate

All of the choices are pretty shitty except (4) and (5). Item (4) may be a good choice as it proves the toolchain can consume the options and produce an artifact like `a.out`.

Item (5) may be a good choice long as we stay warning-free, which is what we do anyways. For example, here is the SSE2 test under normal conditions. Notice there are no messages, and we can deduce the option was accepted:

```
skylake:cryptopp$ g++ -DNDEBUG -g2 -O0 -msse2 TestPrograms/test_x86_sse2.cxx
skylake:cryptopp$
```

And here's what happens when the compiler cannot handle an option. Notice the presence of output when things go sideways.

```
$ g++ -DNDEBUG -g2 -O0 -mXXX TestPrograms/test_x86_sse2.cxx
g++: error: unrecognized command line option ‘-mXXX’
```

We may be able to combine options (4) and (5).

The caveat I am aware for option (5) is, some OS X compilers generate a warning stating *`-pthreads have no effect, passing to the linker`* (or similar). In this case we would reject a valid option.

We'll keep this report open to solicit ideas and gather feedback.

**Comment by noloader** [comment]
We started testing the "clean compile as the gate" at [Commit 1ac7207545f3 ](https://github.com/weidai11/cryptopp/commit/1ac7207545f3). 1ac7207545f3 is limited to PowerPC at the moment.

It is testing as well as the English-language only version we are using from Master. It outperforms the past version that relied on toolchain versions.

The new feature test version is very robust. It only accepts clean compiles, and it always rejects problems. It does not matter what combinations of toolchain and hardware we try to use. This method exceeds the `BAD_RESULT` version because `BAD_RESULT` required us to prime the system with strings:

```
BAD_RESULT="fatal|error|unknown|unrecognized|unexpected|illegal|ignored|incorrect|
  not found|not exist|cannot find|not supported|not compatible|no such instruction|invalid mnemonic"
```

**Comment by ernsteiswuerfel** [comment]
re-built cryptopp on my G5 from master which went fine.

**./cryptest.exe** errors out now at:

SIMON validation suite running...

Testing SymmetricCipher algorithm SIMON-64/ECB.
Ungültiger Maschinenbefehl (Speicherabzug geschrieben)

**Comment by mouse07410** [comment]
Could you perhaps put it on a separate branch for now? I'd like to pull that branch and try it on MacOS and a couple of Linux systems.

Also, I'd like you to take a look at GNUmakefile in my fork: I found it necessary for Macports GCC to add all the assembly flags, and disable the unavailable instructions via defines like -DCRYPTOPP_DISABLE_SSE2 and such. The current master was not detecting features properly for me.

**Comment by ernsteiswuerfel** [comment]
Built git-master from today with the CXXFLAGS you suggested.

Now the tests error out at:
Testing MessageDigest algorithm SM3.
..............................................................
Tests complete. Total tests = 62. Failed tests = 0.

BLAKE2s validation suite running...

passed   algorithm name
Ungültiger Maschinenbefehl (Speicherabzug geschrieben)

**Comment by noloader** [comment]
@ernsteiswuerfel,

We changed the Altivec flag to use only `-maltivec`, instead of `-mcpu=power4 -maltivec`. If that's not it, then I am out of ideas. We will need to see a disassembly around where the `SIGILL` occurs.

**Comment by noloader** [comment]
The Makefile has been cut-over. Closing this issue.
