### ISSUE TITLE
AES CBC Decrypt crashes on some machines

### ISSUE THREAD

**Issue by alfacheetos2throwaway** [weidai11/cryptopp#746]
* Windows 10, 1803, Russian language
* Latest stable version of Crypto++
* built using VS2017

```
std::string decrypt(const std::string& str_in, const std::string& key, const std::string& iv)
{
	std::string str_out;
	CryptoPP::CBC_Mode<CryptoPP::AES>::Decryption decryption((byte*)key.c_str(), key.length(), (byte*)iv.c_str());
	CryptoPP::StringSource decryptor(str_in, true,
		new CryptoPP::Base64Decoder(
			new CryptoPP::StreamTransformationFilter(decryption,
				new CryptoPP::StringSink(str_out)
			)
		)
	);
	return str_out;
}
```

Code works on multiple machines but fails on some computers very rarely. Tests have been done and I'm 100% sure that it is a fault in the Crypto++ lib.

Given the same key, iv, encrypted message 90% of the computers will decrypt the message fine. But for the 10% the application crashes at the decrypt() function.

**Comment by noloader** [comment]
We will need a reproducer to isolate the issue.

**Comment by noloader** [comment]
Closing until we can get more information.
