### ISSUE TITLE
ED25519 API design

### ISSUE THREAD

**Issue by KayEss** [weidai11/cryptopp#750]
We've been using the new ED25519 support on Crypto++, but unfortunately had to fork the files involved due to some API issues.

Right now the only way to derive the public key from the private one is with the [`crypto_sign_keypair`](https://github.com/weidai11/cryptopp/blob/master/tweetnacl.cpp#L739) function, which always pulls new random data for the private key. We need an API that allows us to provide the 32 byte private key and derive the public key from it.

If I make some changes here and open a PR is this something that would be considered?

If so, then the first step would be to work out the new API that we want, whilst presumably keeping backward compatibility on the existing one.

**Comment by noloader** [comment]
Thanks  @KayEss.

> Right now the only way to derive the public key from the private one is with the crypto_sign_keypair function, which always pulls new random data for the private key. We need an API that allows us to provide the 32 byte private key and derive the public key from it.

We added `crypto_sign_sk2pk` for Monero at [Commit d8946df8eb34](https://github.com/weidai11/cryptopp/commit/d8946df8eb34). It creates a public key from a private key without the randomness. It was copied/pasted from `crypto_sign_keypair`, but the calls for the random bytes were removed.

Will that be helpful to you, or do you need something else?

-----

Related, we need to shit or get off the pot with Bernstein's gear. We cut-in the tweet library for testing only. It was intended to cross-check the real gear based on Bernstein's optimized code. But we still don't have Bernstein's optimized code cut-in.

I've got some stuff on my testing branch but the integration is awful. I've talked with a few other devs and they've had the same experience. An ugly integration may be the best we can hope for.

**Comment by KayEss** [comment]
> Will that be helpful to you, or do you need something else?

That commit looks [pretty much identical to what I did](https://github.com/KayEss/fost-base/blob/master/Cpp/fost-crypto/ed25519.cpp#L19).

I'll just wait for next release and then just switch over :-)

**Comment by noloader** [comment]
> That commit looks [pretty much identical to what I did](https://github.com/KayEss/fost-base/blob/master/Cpp/fost-crypto/ed25519.cpp#L19).

Yeah, that looks about right for the task at hand.
