### ISSUE TITLE
Argument declaration and definition mismatch.

### ISSUE THREAD

**Issue by irwir** [weidai11/cryptopp#773]
https://github.com/weidai11/cryptopp/blob/a79fe3a826727bb3bdb2c8d1e035335fe655ebca/osrng.h#L237
Declaration has more informative `additionalEntropy` instead of `input`.

https://github.com/weidai11/cryptopp/blob/a79fe3a826727bb3bdb2c8d1e035335fe655ebca/smartptr.h#L146
Declaration has `p` instead of `r` for a reference argument.

**Comment by noloader** [comment]
Please provide a pull request.
