### ISSUE TITLE
Crypto++ yields build linker error on Windows

### ISSUE THREAD

**Issue by robinwassen** [weidai11/cryptopp#781]
Builds on Windows seems to fail with an linker error when in recent versions of Crypto++, I have read the README.txt and could not find any further instructions on how to build it. As far as I know there my VS 2017 C++ setup is as standard as you can get.

* Windows 10.0.15063
* Building in Visual Studio 2017 15.9.5 using the provided solution file
* Affected Crypto++ versions: 8.0, 7.0, 6.0
* Working Crypto++ version:  5.6.5

**Steps to reproduce:**

1. Download and unzip source for one of the affected Crypto++ versions
2. Open cryptest.sln in VS 2017
3. Rebuild the solution (or just cryptlib project), build configuration does not matter

**Expected result:** The solution should build as intended

**Actual result:**
The solution fail to build with the error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'stddef.h': No such file or directory	cryptlib	c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\cstddef	7	
```

**Comment by robinwassen** [comment]
I found one instance where someone else reported this: https://github.com/weidai11/cryptopp/issues/606#issuecomment-433915470

**Comment by robinwassen** [comment]
The issue above was on my work machine - tested to build Crypto++ 8.0 on my personal machine using the same steps and it worked as intended.

Will look into what difference there is between the setups.

**Comment by robinwassen** [comment]
I found the solution to the problem - Windows Universal CRT SDK must be installed.

**Steps to fix the problem:**
- Modify the Visual Studio 2017 installation
- Install `Individual Component -> Windows Universal CRT SDK`

**Comment by noloader** [comment]
Thanks @robinwassen,

That's kind of a weird build error in 2019. It does not seem like you should need a SDK to build with a standard header like `<stddef.h>`. `<stddef.h>` is [Posix](http://pubs.opengroup.org/onlinepubs/009695299/basedefs/stddef.h.html), and it provides `size_t`, `ptrdiff_t` and a few other types.

I wonder if there's anything we can do to avoid the build failure.

**Comment by robinwassen** [comment]
@noloader I am not sure it's worth mitigating this in Crypto++ when I saw what the solution was, if someone else bumps into this problem I guess this issue will show up on Google which should be enough.

But I agree that it's really odd that those header files was inaccessible, because I have built a lot of other C++ projects on the same machine.

**Comment by noloader** [comment]
It looks like someone else is having trouble: [Compiling Crypto++ Library on Visual Studio 2017 Targeting Windows 10](https://stackoverflow.com/q/54502541/608639)

**Comment by Skuamato** [comment]
@noloader Still had the same issue. After changing Visual Studio Installation as @robinwassen suggested the bug was fixed. So your fix didn't work for me (Win7, VS2017).

**Comment by alexcodergit** [comment]
I had similar issue when installing botan crypto library on Windows. I solved the problem by setting %INCLUDE% environment variable for every header location that could not be found from command line tool  like this:
set include=C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include
set include=%include%;C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt
