### ISSUE TITLE
scrypt needs OpenMP 3, MSVC only supports OpenMP 2

### ISSUE THREAD

**Issue by smessmer** [weidai11/cryptopp#787]
The scrypt implementation uses OpenMP 3 features, but the MSVC compiler for Windows only supports OpenMP 2. This causes key derivation for [CryFS](https://github.com/cryfs/cryfs) on Windows to take quite a long time because it is only using one core. Is it possible to change the scrypt implementation to use OpenMP 2 features only?

see also this thread where this was briefly discussed: https://github.com/cryfs/cryfs/issues/157

**Comment by noloader** [comment]
@smessmer,

> Is it possible to change the scrypt implementation to use OpenMP 2 features only?

Yes, sounds reasonable.

Do you have a patch?

**Comment by smessmer** [comment]
No, I'm not very familiar with OpenMP. For now, mounting CryFS on Windows 
is just slow ;)
If somebody has time to fix this, I'd appreciate it. If not, I can take a 
look, but that's not likely to happen anytime soon.

**Comment by smessmer** [comment]
Cool, that was fast. Thank you :)
I saw your diff now uses a normal for loop instead of `#pragma omp simd` when on MSVC, does this impact performance? Does it parallelize less on Windows than on Linux? I saw the `numeric_limits<int>` comment, but that'd be large enough to not matter.
