### ISSUE TITLE
[OSX] Incorrect install_name for dynamic library

### ISSUE THREAD

**Issue by cawka** [weidai11/cryptopp#80]
When compiling dynamic version of crypto++ library, it uses `install_name` parameter equal to `libcryptopp.dylib`.  Effectively, if the library is installed, the programs will be able to compile against it, but the at the runtime the library will not be found.

I believe, the default should be `$PREFIX/lib/libcryptopp.dylib`, however there could be other options depending on how the library is used.

(I came across this issue with MacPorts.  It was fixed prior to 5.6.3 update, but now broken again.)

**Comment by noloader** [comment]
Here some background... when we added the additional options on OS X, we did so for versioning requirements as called out at [Dynamic Library Design Guidelines](https://developer.apple.com/library/mac/documentation/DeveloperTools/Conceptual/DynamicLibraries/100-Articles/DynamicLibraryDesignGuidelines.html). Providing ***just*** the library name meant we were honoring a user's choice with a *"regular dependent library"* as described at [Run-Path Dependent Libraries](https://developer.apple.com/library/mac/documentation/DeveloperTools/Conceptual/DynamicLibraries/100-Articles/RunpathDependentLibraries.html).

It sounds like you are asking for the [run-path install names](https://developer.apple.com/library/mac/documentation/DeveloperTools/Conceptual/DynamicLibraries/100-Articles/RunpathDependentLibraries.html). If that's the case, then I think we should take it to the user list for vote. If that's not the case, then can you give us an example of what you would like done (i.e., a diff of the change you are proposing, like using the makefile rule).

**Comment by cawka** [comment]
Thanks for pointers.  I have read them before and reread again.  Unless I have missed it, I didn't see any use case which does not specify absolute name for the install path in some form: real absolute name, with `@executable_path`, `@loader_path`, or `@rpath` (you can check https://wincent.com/wiki/@executable_path,_@load_path_and_@rpath that explains differences).

Which exactly `install_path` is suitable for an application, really depends on the application.  For OSX gui apps and frameworks (that are packaged in .app and .framework folders), `install_path` needs to get properly set for this application, as it depends on where the library is put in the bundle, and there are tools to modify it.   For other apps that just use the shared library installed somewhere, the straightforward way is to specify the absolute path as `install_path`, something like this change:

```patch
diff --git a/GNUmakefile b/GNUmakefile
index d2f5404..1bef87e 100755
--- a/GNUmakefile
+++ b/GNUmakefile
@@ -388,7 +388,7 @@ libcryptopp.so: public_service | $(LIBOBJS)
        $(CXX) -shared -o $@ $(CXXFLAGS) $(GOLD_OPTION) $(LIBOBJS) $(LDLIBS)

 libcryptopp.dylib: $(LIBOBJS)
-   $(CXX) -dynamiclib -o $@ $(CXXFLAGS) -install_name "$@" -current_version "$(LIB_MAJOR).$(LIB_MINOR).$(LIB_PATCH)" -compatibility_version "$(LIB_MAJOR).$(LIB_MINOR)" $(LIBOBJS)
+ $(CXX) -dynamiclib -o $@ $(CXXFLAGS) -install_name "$(PREFIX)/lib/$@" -current_version "$(LIB_MAJOR).$(LIB_MINOR).$(LIB_PATCH)" -compatibility_version "$(LIB_MAJOR).$(LIB_MINOR)" $(LIBOBJS)

 cryptest.exe: public_service | libcryptopp.a $(TESTOBJS)
        $(CXX) -o $@ $(CXXFLAGS) $(TESTOBJS) ./libcryptopp.a $(LDFLAGS) $(GOLD_OPTION) $(LDLIBS)
```
A little more complicated is to use `@rpath/libcryptopp.dylib` and then additionally specify `-rpath "$(PREFIX)/lib/"` linker option.

I would also like to add a few examples of build systems, building shared libraries:
- autoconf/automake/libtool uses an absolute path of the library as `install_path`
- cmake uses path that includes `@rpath` (I'm not expert in cmake, so could be mistaken)
- waf build system uses an absolute path of the library as install_path
- boost build (b2) sets an absolute path

I want to highlight my motivation for this proposal.  When my app is compiled against macports version of cryptopp library, it is effectively broken (https://trac.macports.org/ticket/49987).

**Comment by cawka** [comment]
I'll drop in this page http://matthew-brett.github.io/docosx/mac_runtime_link.html that gives additional explanation and examples.

**Comment by noloader** [comment]
> + $(CXX) -dynamiclib -o $@ -install_name "$(PREFIX)/lib/$@"

OK, the problem here is `PREFIX` is not available until `make install`, and it may not be available then. That is, users are conditioned to perform:

    $ unzip -aoq cryptoppXXX.zip -d cryptopp
    $ cd cryptopp
    $ make static dynamic test
    $ sudo make install [PREFIX=/usr/local]

*If* `PREFIX` is not available during *both* the invocations to `make`, then `-install_name` will evaluate to  `/lib/libcryptopp.dylib`. In this case, we are just creating more trouble for users.

------

I think we should drop the `-install_name` altogether. That's based on the fact that (1) adding `-install_name` caused harm (i.e., it broke things for you), and (2) requiring `PREFIX` will cause more harm (users forget to use it).

What do you think?

**Comment by cawka** [comment]
Are you sure about PREFIX being unavailable?  My read of the makefile tells me (and I also tested my patch) that the default is set to `/usr`.  However, I agree that users don't normally specify the right PREFIX variable until the install phase.

I just checked that not specifying `install_name` has exactly the same effect as what is specified right now. So, it wouldn't be a solution.

I have an alternative proposal, which should address issue of unknown path at the build time:

```patch
diff --git a/GNUmakefile b/GNUmakefile
index d2f5404..1741015 100755
--- a/GNUmakefile
+++ b/GNUmakefile
@@ -363,6 +363,7 @@ install:
        -$(CHMOD) 755 $(PREFIX)/bin/cryptest.exe
 ifneq ($(IS_DARWIN),0)
        -$(CP) libcryptopp.dylib $(PREFIX)/lib
+ -install_name_tool -id $(PREFIX)/lib/libcryptopp.dylib $(PREFIX)/lib/libcryptopp.dylib
        -$(CHMOD) 755 $(PREFIX)/lib/libcryptopp.dylib
 else
        -$(CP) libcryptopp.so $(PREFIX)/lib
```

This way, the correct path is set during the install phase, while the library is compiled without the absolute path in `install_path` during the build.

**Comment by noloader** [comment]
> This way, the correct path is set during the install phase, while the library is compiled without the absolute path in install_path during the build.

I like that one much better. So I'm clear... We add the version info during 'make', and we add the install name during 'make_install' Is that correct? If so, can you work up a pull request so you can get credit for it?

I'm going to put it on the list to make sure we are not missing something obvious.

**Comment by noloader** [comment]
> However, I agree that users don't normally specify the right PREFIX variable until the install phase.

This should be a separate discussion. We should have had it a long time ago.

You spotted one problem with the default of `/usr`. Another one is it breaks on some of the BSDs. For some reason, you ***cannot*** install C++ libraries and headers into `/usr`. The OpenBSD compiler provides *always* treats them like C headers. You can imagine how that ends...

The only work around I know is to install into `/usr/local`. I think its a better default choice.

**Comment by cawka** [comment]
Yes. Adding the version during the build and then "fixing" `install_path` during the install. I will submit a pull request shortly.

**Comment by cawka** [comment]
> For some reason, you cannot install C++ libraries and headers into /usr

To add more. In OSX 10.11 you also cannot install anything to /usr/bin, /usr/lib, even if you have root privileges (https://en.wikipedia.org/wiki/System_Integrity_Protection).

**Comment by noloader** [comment]
> To add more. In OSX 10.11 you also cannot install anything to /usr/bin, /usr/lib,

We should handle it before it becomes a major problem. How about working up a separate pull request for this one?

**Comment by cawka** [comment]
Here is the commit https://github.com/cawka/cryptopp-1/commit/acd9ae052f5c10ef42c8b20e705586809d4e1c0b  (I don't like pull requests too much)

After everything is checked for correctness, you can use these command to merge:

```bash
git fetch https://github.com/cawka/cryptopp-1 issue-80
git merge FETCH_HEAD   # or cherry-pick
```

**Comment by noloader** [comment]
@Alex - can you make one more change to this....

Add `-Wl,-headerpad_max_install_names` flag to OS X's `libcryptopp.dylib` recipe? That should make room for a long pathname, if required. We should be able to pull it after that since I have not seen any objections.

**Comment by noloader** [comment]
Merged at https://github.com/weidai11/cryptopp/commit/5170f3e1f7da78bc32410bae217a8d1605282935 .
