### ISSUE TITLE
The old ChaCha8, ChaCha12 and ChaCha20 is better then current ChaCha with "Rounds" parameter

### ISSUE THREAD

**Issue by asbai** [weidai11/cryptopp#800]
### Crypto++ 8.0 Issue Report
I think the old ChaCha8, ChaCha12 and ChaCha20 is better then current ChaCha with "Rounds" parameter, because: 

1. New API need to setting up the rounds on every key reset. This usage is neither natural nor convenient, since the rounds is itself a fixed part of the algorithm, it is usually not modified when changing the key. In essence, different rounds can actually be seen as completely different algorithms. Setting the number of rounds from 8 to 20 is like switching the encryption algorithm from DES to AES. The new API forces us to remember its rounds and specify it each time we reset the password.

2. Template parameters are known constants at compile time, and I guess using template parameters allows some compilers to better optimize their generated code.

**Comment by noloader** [comment]
>     1. New API need to setting up the rounds on every key reset...

Yeah, that's bullshit. Let me get that fixed.

That's going to affect, Salsa, ChaCha, XChaCha and a few others.

>     2. Template parameters are known constants at compile time, and I guess using template parameters allows some compilers to better optimize their generated code.

This does not matter much in practice. I used to favor the `consexpr` hoping it made a difference. I found the difference won't be measurable or will be trivial under benchmarks.

**Comment by asbai** [comment]
Great, thanks @noloader 
:-D

**Comment by noloader** [comment]
Cleared at [Commit e499131ea6ba](https://github.com/weidai11/cryptopp/commit/e499131ea6ba).
