### ISSUE TITLE
Missing method "AlgorithmProvider" on class "PanamaHash"

### ISSUE THREAD

**Issue by asbai** [weidai11/cryptopp#801]
### Crypto++ 8.0 Issue Report

A method:
```C++
std::string AlgorithmProvider() const {return Panama<B>::AlgorithmProvider();}
```
Need to be added to the PanamaHash class, otherwise following code will produce a few of compiler errors:
```C++
HMAC<CryptoPP::Weak::PanamaHash<LittleEndian> > testL;
// or
HMAC<CryptoPP::Weak::PanamaHash<BigEndian> > testB;
```

**Comment by noloader** [comment]
Thanks @asbai,

Yeah, the Panama class gave me a few problems trying to add `AlgorithmProvider`. In hindsight I should have left things alone and let it report "C++".

Do you feel like making a pull request?

**Comment by asbai** [comment]
OK, here is it: https://github.com/weidai11/cryptopp/pull/803
:-)

**Comment by noloader** [comment]
Thank you very much.
