### ISSUE TITLE
Build fails on fedora30+ (CPU features miss-detected)

### ISSUE THREAD

**Issue by kwizart** [weidai11/cryptopp#812]
Using Fedora 30, I cannot update to cryptopp 8.0.0/8.1.0
Seems like CPU features are miss-detected as I cannot see any ASM_FLAGS been used in "some" cases.

Build attempt for f31,f29, f28
https://koji.fedoraproject.org/koji/taskinfo?taskID=33066081
https://koji.fedoraproject.org/koji/taskinfo?taskID=33066857
https://koji.fedoraproject.org/koji/taskinfo?taskID=33067570

I'm using the default GNUMake files to build using:
%make_build -f GNUmakefile \
  CXXFLAGS="-DNDEBUG %{optflags} -fPIC -DPIC" \
  LDFLAGS="%{?__global_ldflags}" \
  shared cryptest.exe

**Comment by noloader** [comment]
Thanks @kwizart.

Interesting in a morbid sort of way... I use Fedora as my primary workstation, and we specifically [test using Fedora's build flags](https://github.com/weidai11/cryptopp/blob/master/cryptest.sh#L2178).

The symptom is the following taken from the [task 33066120 build.log](https://kojipkgs.fedoraproject.org//work/tasks/6120/33066120/build.log):

```
g++ -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -DPIC -c aria_simd.cpp
BUILDSTDERR: In file included from aria_simd.cpp:14:
BUILDSTDERR: /usr/lib/gcc/x86_64-redhat-linux/9/include/tmmintrin.h: In function 'void CryptoPP::ARIA_ProcessAndXorBlock_SSSE3(const byte*, CryptoPP::byte*, const byte*, CryptoPP::word32*)':
BUILDSTDERR: /usr/lib/gcc/x86_64-redhat-linux/9/include/tmmintrin.h:136:1: error: inlining failed in call to always_inline '__m128i _mm_shuffle_epi8(__m128i, __m128i)': target specific option mismatch
BUILDSTDERR:   136 | _mm_shuffle_epi8 (__m128i __X, __m128i __Y)
BUILDSTDERR:       | ^~~~~~~~~~~~~~~~
```

The makefile should be adding `-mssse3` for `aria_simd.cpp` and other cpu-specific flags for other `*_simd.cpp` files. For example `rijndael_simd.cpp` gets `-msse4.1 -maes` on x86 machines.

Reproducing it with:

```
skylake:cryptopp$ export CXXFLAGS=" -DNDEBUG -O2 -g -pipe -Wall -Werror=format-s
ecurity -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-p
rotector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened
-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchr
onous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -DPIC"
skylake:cryptopp$ g++ $CXXFLAGS TestPrograms/test_x86_ssse3.cxx
In file included from TestPrograms/test_x86_ssse3.cxx:2:
/usr/lib/gcc/x86_64-redhat-linux/8/include/tmmintrin.h: In function ‘int main(int, char**)’:
/usr/lib/gcc/x86_64-redhat-linux/8/include/tmmintrin.h:185:1: error: inlining failed in call to always_inline ‘__m128i _mm_alignr_epi8(__m128i, __m128i, int)’: target specific option mismatch
 _mm_alignr_epi8(__m128i __X, __m128i __Y, const int __N)
 ^~~~~~~~~~~~~~~
TestPrograms/test_x86_ssse3.cxx:6:19: note: called from here
  x=_mm_alignr_epi8(x,x,2);
    ~~~~~~~~~~~~~~~^~~~~~~
In file included from TestPrograms/test_x86_ssse3.cxx:2:
/usr/lib/gcc/x86_64-redhat-linux/8/include/tmmintrin.h:185:1: error: inlining failed in call to always_inline ‘__m128i _mm_alignr_epi8(__m128i, __m128i, int)’: target specific option mismatch
 _mm_alignr_epi8(__m128i __X, __m128i __Y, const int __N)
 ^~~~~~~~~~~~~~~
TestPrograms/test_x86_ssse3.cxx:6:19: note: called from here
  x=_mm_alignr_epi8(x,x,2);
    ~~~~~~~~~~~~~~~^~~~~~~
```

Let me see which switch is giving our Makefile the trouble.

**Comment by noloader** [comment]
I believe an underlying ARMEL issue was cleared at [Commit 84ab1f3c66a5](https://github.com/weidai11/cryptopp/commit/84ab1f3c66a5).

But I am not sure if it will help Fedora becuase it appears a different makefile is being used.

**Comment by kwizart** [comment]
Seems most arches are now fixed but aarch64.
https://koji.fedoraproject.org/koji/taskinfo?taskID=33100404

About https://www.cryptopp.com/wiki/Static_Initialization_Order_Fiasco
Does it means I need to build with -j1 ?

**Comment by noloader** [comment]
> Seems most arches are now fixed but aarch64.
https://koji.fedoraproject.org/koji/taskinfo?taskID=33100404

From the [33100407 build log](https://kojipkgs.fedoraproject.org//work/tasks/407/33100407/build.log), it looks like we have another mis-detection. The first is actually `aria_simd.cpp` again though it does not cause a compile failure:

```
...
g++ -DNDEBUG -O2 -g -pipe ... -fPIC -DPIC -c aria.cpp
g++ -DNDEBUG -O2 -g -pipe ... -fPIC -DPIC -c aria_simd.cpp
g++ -DNDEBUG -O2 -g -pipe ... -fPIC -DPIC -c ariatab.cpp
```

Here's what it looks like when working as expected. Notice the addition of `-march=armv8-a`:

```
...
g++ -DNDEBUG -g2 -O3 -fPIC -pthread -pipe -c aria.cpp
g++ -DNDEBUG -g2 -O3 -fPIC -pthread -pipe -march=armv8-a -c aria_simd.cpp
g++ -DNDEBUG -g2 -O3 -fPIC -pthread -pipe -c ariatab.cpp
```

So it looks like we are not setting `IS_ARMV8` correctly in the [GNUmakefile](https://github.com/weidai11/cryptopp/blob/master/GNUmakefile) for Fedora:

```
HOSTX := $(shell $(CXX) $(CXXFLAGS) -dumpmachine 2>/dev/null | cut -f 1 -d '-')
...
IS_ARMV8 := $(shell echo "$(HOSTX)" | $(GREP) -i -c -E 'aarch32|aarch64|arm64|armv8')
```

Later we use it to add the appropriate flags in [GNUmakefile](https://github.com/weidai11/cryptopp/blob/master/GNUmakefile). Something like this:

```
ifneq ($(IS_ARM32)$(IS_ARMV8),00)
    ...
    ifneq ($(IS_ARMV8),0)
        # Do ARMv8 tests
        TPROG = TestPrograms/test_arm_asimd.cxx
        TOPT = -march=armv8-a
        HAVE_OPT = $(shell $(CXX) $(CXXFLAGS) $(ACLE_FLAG) $(ZOPT) $(TOPT) $(TPROG) -o $(TOUT) 2>&1 | tr ' ' '\n' | wc -l)
        ifeq ($(strip $(HAVE_OPT)),0)
            ASIMD_FLAG = -march=armv8-a
            ARIA_FLAG = -march=armv8-a
            ...
        endif
    endif
endif
```

What does `g++ -dumpmachine` output on the Fedora build machine?

-----

> About https://www.cryptopp.com/wiki/Static_Initialization_Order_Fiasco
Does it means I need to build with -j1 ?

No. It means we (Crypto++) needs to build and link the objects in a specific order to avoid initialization problems.

**Comment by noloader** [comment]
@kwizart,

Feel free to email me at *noloader, gmail* account. You are free to file bug reports, but you might find it easier to contact me via email.

**Comment by kwizart** [comment]
$ c++ -dumpmachine
aarch64-redhat-linux

I'm testing with export CXXFLAGS instead of passing flags with make -f GNUMake CXXFLAGS="-DNDEBUG %{optflags}"
For aarch64 I now have DCRYPTOPP_DISABLE_ASM set (so the build succeed)
But for others arches, everything is built with the appropropriate ASM when relevant.

**Comment by noloader** [comment]
> I'm testing with export CXXFLAGS instead of passing flags with `make -f GNUMake CXXFLAGS="-DNDEBUG %{optflags}"`


Yeah, you usually don't want this when running make:

```
make CXXFLAGS="..."
```

That says, don't use project `CXXFLAGS`. It effectively makes `CXXFLAGS` read only for the makefile. When GNU make encounters it it will ignore things like:

```
CXXFLAGS += "<some project flag>"
```

Usually you want this:

```
 CXXFLAGS="..." make
```

That allows us to add to your `CXXFLAGS`, and this liek this will work"

```
CXXFLAGS += "<some project flag>"
```

**Comment by kwizart** [comment]
Okay I think I got it:
c++ ${CXXFLAGS} -DCRYPTOPP_ARM_ACLE_AVAILABLE=1  -march=armv8-a -O0 -o TestPrograms/test_arm_asimd TestPrograms/test_arm_asimd.cxx
In file included from /usr/include/bits/libc-header-start.h:33,
                 from /usr/include/stdint.h:26,
                 from /usr/lib/gcc/aarch64-redhat-linux/8/include/stdint.h:9,
                 from /usr/lib/gcc/aarch64-redhat-linux/8/include/arm_neon.h:33,
                 from TestPrograms/test_arm_asimd.cxx:1:
/usr/include/features.h:381:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
 #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)

I'm testing with using ZOPT='' instead because it overrides our default CXXFLAGS in an incompatible way.
But is it relevant to keep it ?

**Comment by noloader** [comment]
> I'm testing with using ZOPT='' instead because it overrides our default CXXFLAGS in an incompatible way.
>
> But is it relevant to keep it ?

For testing features only, we remove `-Wp,-D_FORTIFY_SOURCE=2` from `CXXFLAGS. That's be cause of `-O0` and the error you see. (We also remove some others during feature testing, like `-Werror`). You can see it here around [line 115 in the Makefile](https://github.com/weidai11/cryptopp/blob/master/GNUmakefile#L117):

```
# Strip out -Wall, -Wextra and friends for feature testing
ifeq ($(DETECT_FEATURES),1)
  TCXXFLAGS := $(filter-out -Wall -Wextra -Werror% -Wunused -Wconversion -Wp%, $(CXXFLAGS))
  ifneq ($(strip $(TCXXFLAGS)),)
    $(info Using testing flags: $(TCXXFLAGS))
  endif
  #TPROG = TestPrograms/test_cxx.cxx
  #$(info Testing compile... )
  #$(info $(shell $(CXX) $(TCXXFLAGS) $(ZOPT) $(TOPT) $(TPROG) -o $(TOUT) 1>/dev/null))
endif
```

We use `TCXXFLAGS` (test `CXXFLAGS`) to test for options like `-march=armv8-a`.

When we build the library we use your full `CXXFLAGS` with nothing removed.

**Comment by kwizart** [comment]
Ok, using ZOPT='' cleared the issue, the build are optimized (even on aarch64).

Okay I've understood the idea about the test flags. I've found the root cause.
(PR in a few).

**Comment by noloader** [comment]
Thanks @kwizart.

Man, was I wrong about this:

> We use `TCXXFLAGS` (test `CXXFLAGS`) to test for options like `-march=armv8-a`.

Sorry about that.

**Comment by noloader** [comment]
@kwizart,

Here is a related commit for the PR you just made: [Commit 08b9e21e5a43](https://github.com/weidai11/cryptopp/commit/08b9e21e5a43). I don't believe you need it, but I mention it for completeness.
