### ISSUE TITLE
GNUmakefile needs to use separate variable for CXXFLAGS

### ISSUE THREAD

**Issue by noloader** [weidai11/cryptopp#814]
This is a side/tangential issue from [Issue 812](https://github.com/weidai11/cryptopp/issues/812#issuecomment-468215577). Here is the relevant information from the 812 issue:

-----

You actually tickled a bug in our Makefile. I've known about it for several years, but I never addressed it. The problem is, we don't build correctly when make is invoked like below because make overrides the flags we would add.

```
make CXXFLAGS="..."
```

Here's the reason it happens. It is our default recipe:

```
# We determine we need some flag, but CXXFLAGS is
#   read-only due to 'make CXXFLAGS="..."'
CXXFLAGS += <some flag>
...

%.o : %.cpp
    $(CXX) $(strip $(CXXFLAGS) -c) $<
```

This is what we should be doing. It is textbook Stallman from the GNU Make manual:

```
# We determine we need some flag
OUR_CXXFLAGS += <some flag>
...

%.o : %.cpp
    $(CXX) $(strip $(OUR_CXXFLAGS) $(CXXFLAGS) -c) $<
```

Now it does not matter how you invoke make. Things just work for you. And it follows Stallman's freedom philosophy. The user's `CXXFLAGS` always takes precedence over `OUR_CXXFLAGS`.

Since someone tickled it in the field I am going to get it fixed.

**Comment by tanzislam** [comment]
GNU Make also has the [`override` directive](https://www.gnu.org/software/make/manual/html_node/Override-Directive.html) for this. So you can say:

```
override CXXFLAGS += <some flag>
```

inside the `GNUmakefile`.

**Comment by noloader** [comment]
Cleared at [Commit fd52848c04e2](https://github.com/weidai11/cryptopp/commit/fd52848c04e2).
