### ISSUE TITLE
compile error  when building version 810

### ISSUE THREAD

**Issue by icylord** [weidai11/cryptopp#818]
GCC version: gcc version 4.4.6 20110731 (Red Hat 4.4.6-4) (GCC)
run make command and compile fail, below is the last message:

g++ -DNDEBUG -g2 -O3 -DCRYPTOPP_DISABLE_AVX2 -fPIC -pthread -pipe -c seed.cpp
g++ -DNDEBUG -g2 -O3 -DCRYPTOPP_DISABLE_AVX2 -fPIC -pthread -pipe -c serpent.cpp
g++ -DNDEBUG -g2 -O3 -DCRYPTOPP_DISABLE_AVX2 -fPIC -pthread -pipe -c sha.cpp
g++ -DNDEBUG -g2 -O3 -DCRYPTOPP_DISABLE_AVX2 -fPIC -pthread -pipe -c sha3.cpp
g++ -DNDEBUG -g2 -O3 -DCRYPTOPP_DISABLE_AVX2 -fPIC -pthread -pipe -c sha_simd.cpp
g++ -DNDEBUG -g2 -O3 -DCRYPTOPP_DISABLE_AVX2 -fPIC -pthread -pipe -c shacal2.cpp
g++ -DNDEBUG -g2 -O3 -DCRYPTOPP_DISABLE_AVX2 -fPIC -pthread -pipe -c shacal2_simd.cpp
g++ -DNDEBUG -g2 -O3 -DCRYPTOPP_DISABLE_AVX2 -fPIC -pthread -pipe -c shake.cpp
In file included from shake.cpp:21:
shake.h: In constructor 'CryptoPP::SHAKE128::SHAKE128(unsigned int)':
shake.h:128: error: class 'CryptoPP::SHAKE128' does not have any field named 'SHAKE_Final'
shake.h: In constructor 'CryptoPP::SHAKE256::SHAKE256(unsigned int)':
shake.h:158: error: class 'CryptoPP::SHAKE256' does not have any field named 'SHAKE_Final'
make: *** [shake.o] Error 1

**Comment by noloader** [comment]
Yeah, this surfaced with older versions of GCC. It looks like I did not check-in the fix yet.

Hang tight.

**Comment by noloader** [comment]
Please test this on the Red Hat machine:

```
$ git diff > shake.diff
$ cat shake.diff
diff --git a/shake.h b/shake.h
index a615b573..37cb8274 100644
--- a/shake.h
+++ b/shake.h
@@ -125,7 +125,7 @@ public:
     ///   requires the output size in advance because the algoirthm uses
     ///   output size as a parameter to the hash function.
     /// \since Crypto++ 8.1
-    SHAKE128(unsigned int outputSize) : SHAKE_Final(outputSize) {}
+    SHAKE128(unsigned int outputSize) : SHAKE_Final<128>(outputSize) {}
 };

 /// \brief SHAKE256 message digest
@@ -155,7 +155,7 @@ public:
     ///   requires the output size in advance because the algoirthm uses
     ///   output size as a parameter to the hash function.
     /// \since Crypto++ 8.1
-    SHAKE256(unsigned int outputSize) : SHAKE_Final(outputSize) {}
+    SHAKE256(unsigned int outputSize) : SHAKE_Final<256>(outputSize) {}
 };

 NAMESPACE_END
```

**Comment by noloader** [comment]
Cleared at [Commit fc3b16e3a39d](https://github.com/weidai11/cryptopp/commit/fc3b16e3a39d).
