### ISSUE TITLE
VS2013 compile error

### ISSUE THREAD

**Issue by TyrionZK** [weidai11/cryptopp#819]
### Crypto++ Issue Report

Thanks for taking the time to report an issue. Reporting issues helps us improve stability and reliability for all users, so it is a valuable contribution.

Please do not ask questions in the bug tracker. Please ask questions on the Crypto++ Users List at http://groups.google.com/forum/#!forum/cryptopp-users.

There is a wiki page with information on filing useful bug reports. If you have some time please visit http://www.cryptopp.com/wiki/Bug_Report on the wiki. The executive summary is:

* State the operating system and version (Ubutnu 17 x86_64, Windows 7 Professional x64, etc)
* State the version of the Crypto++ library (Crypto++ 5.6.5, Master, etc)
* State how you built the library (Makefile, Cmake, distro, etc)
* Show a typical command line (the output of the compiler for cryptlib.cpp)
* Show the link command (the output of the linker for libcryptopp.so or cryptest.exe)
* Show the exact error message you are receiving (copy and paste it); or
* Clearly state the undesired behavior (and state the expected behavior)

win7
cryptopp 8.1.0
vs2013

When I compile the project cryptlib, an error appears.
"error: Element <EnableEnhancedInstructionSet>  has an invalid value of Advancedvectorextensions2."

Why? How can I solve it?
Thanks.

**Comment by noloader** [comment]
> Why? How can I solve it?

It sounds like you are missing Visual Studio 2013 updates. You should update Visual Studio. Also see [AVX2 Support in Visual Studio C++ Compiler](https://devblogs.microsoft.com/cppblog/avx2-support-in-visual-studio-c-compiler/).

**Comment by charelstoncrabb** [comment]
@noloader 

I am also currently running in to this issue running on Windows Server 2016 using VS2013.  I have tried all combinations of setting/not setting the `/arch:AVX2` and `CRYPTOPP_DISABLE_AVX2` flag (I assume "disable AVX2 by setting `CRYPTOPP_DISABLE_AVX2`" means adding it as preprocessor definition).

Having neither/xor/both flags set all results in the same 'invalid value of "AdvancedVectorExtensions2"' error.  I am using the latest release version 8.8.0, so maybe the prepro flag is different from when this solution was published (4+ years ago)?  As a debug step I'll try and grab whatever the latest version in Mar 2019 was and try the same approach.
