### ISSUE TITLE
Add Debian-style Data Directory patch

### ISSUE THREAD

**Issue by noloader** [weidai11/cryptopp#82]
Distro maintainers currently have it rough. They install `cryptest.exe` into `/usr/bin`, `TestVectors` and `TestData` into `/usr/share`, and everything breaks because the library presumes a location relative to `cryptest.exe`.

We have a [DataDir](https://www.cryptopp.com/wiki/DataDir) patch, but its a bit complicated. Its probably more complicated than needed. It also requires a user to `make PREFIX=...`, which is unusual in the Crypto++ build procedure workflows.

The distros currently use a Debian patch provided. Whenever we add a new set of test vectors, the distros must apply their patch or endure breaking when a new data set is added, like those for HKDF.

The Debian patch has two parts. First, it adds a macro prefix to the relevant files. For example, the following change is made:

    - FileSource keys("TestData/rsa512a.dat", true, new HexDecoder);
    + FileSource keys(PACKAGE_DATA_DIR "TestData/rsa512a.dat", true, new HexDecoder);

Then, the distros build with:

    CXXFLAGS = $(CXXFLAGS) -DPACKAGE_DATA_DIR='"/usr/share/crypto++/"'

-----

I had the opportunity to speak with two of our package maintainers, László (Debian) and Morten (Fedora). We have hashed out the following changes:

    // config.h
    #ifndef CRYPTOPP_DATA_DIR
    #  define CRYPTOPP_DATA_DIR "./"
    #endif

Then, we will apply the changes following Debian's lead with:

    - FileSource keys("TestData/rsa512a.dat", true, new HexDecoder);
    + FileSource keys(CRYPTOPP_DATA_DIR "TestData/rsa512a.dat", true, new HexDecoder);

The changes above will preserve exiting behavior, and allow distros to continue modifying it as required.

In the future, when we add files, they will always have the prefix applied, so the distros won't need to manage it.

-----

The discussion is available at [Debian-style Data Directory patch](http://groups.google.com/d/msg/cryptopp-users/q1o808taOKA/ztZleJFLCgAJ).

**Comment by GamePad64** [comment]
Well, then one will have to "make install", and then "make test". This order is a bit strange.

**Comment by noloader** [comment]
> Well, then one will have to "make install", and then "make test". This order is a bit strange.

Oh, I parsed that wrong the first time... My apologies.

Our [DataDir]() patch handles that situation by checking in PWD first (this is current behavior), and then checking in `CRYPTOPP_DATA_DIR` (this is new behavior). Her's what it looks like in code:

```
std::string DataDirHelper(const std::string& file) {

#ifndef CRYPTOPP_DATA_DIR
    return file;
#else
    std::string dataDir("" CRYPTOPP_DATA_DIR);

    if(dataDir.empty()) { dataDir = "./"; }
    else if(*(dataDir.end() - 1) != '/') { dataDir += "/"; }

    std::ifstream fs;
    fs.open((dataDir + file).c_str());
    if(fs.is_open()) {
        fs.close();
        return dataDir + file;
    }

    fs.open((std::string("./") + file).c_str());
    if(fs.is_open()) {
        fs.close();
        return std::string("./") + file;
    }

    // Its not in the data directory, and its not relative to PWD.
    //   Return whatever was passed in. Returning whatever was passed
    //   ensures the Crypto++ Exception is accurate.
    return file;
#endif
}
```

It was intended to be called like:

    FileSource keys(DataDir("TestData/rsa512a.dat"), true, new HexDecoder);

I asked the Debian folks about it on their mailing list, and they sated they did ***not*** want that behavior. I'm not going to [bikeshed](http://bikeshed.com/) over it. Its their platform, and they are free to do what they want with it. Also see [How to accommodate test files that move after installation?](https://lists.debian.org/debian-mentors/2015/09/msg00623.html) for the discussion.

**Comment by noloader** [comment]
Committed at a0b078543abdfb5a508ff75dcd5865c4d6401085 .
