### ISSUE TITLE
shake.h not compatible for the NaCl cimpiler (gcc) 

### ISSUE THREAD

**Issue by asbai** [weidai11/cryptopp#820]
crypto++ 8.1: shake.h

The Google Native Client compiler complain something like: "SHACK128: there is no field named SHAKE_Final", we must use the **full template name** to fix it:
```C++
// ...
SHAKE128(unsigned int outputSize) : SHAKE_Final<128>(outputSize) {} // NaCl compiler fix
// ...
SHAKE256(unsigned int outputSize) : SHAKE_Final<256>(outputSize) {} // NaCl compiler fix
```

**Comment by noloader** [comment]
Also see [Commit fc3b16e3a39d](https://github.com/weidai11/cryptopp/commit/fc3b16e3a39d).
