### ISSUE TITLE
Compiler warning in hmac.h

### ISSUE THREAD

**Issue by CelticMinstrel** [weidai11/cryptopp#821]
Including `"hmac.h"` yields the following compiler warning when compiling with cl.exe (2017 version):

```
...\cryptopp\seckey.h(172): warning C4296: '>=': expression is always true
  ...\cryptopp\hmac.h(17): note: see reference to class template instantiation 'CryptoPP::VariableKeyLength<16,0,2147483647,1,4,0>' being compiled
```

I'm compiling on Windows 10 with cryptopp version 8.1.0.

**Comment by noloader** [comment]
Cleared at [Commit b16d37e3471a](https://github.com/weidai11/cryptopp/commit/b16d37e3471a).
