### ISSUE TITLE
SKIPJACK encryption gives wrong result

### ISSUE THREAD

**Issue by Zungong** [weidai11/cryptopp#824]
```
    std::string result_str;
    CryptoPP::CBC_Mode<CryptoPP::SKIPJACK>::Encryption e;
    CryptoPP::byte key[10] = { 0x00, 0x99, 0x88, 0x77, 0x66, 0x55, 0x44, 0x33, 0x22, 0x11 };
    CryptoPP::byte plain[8] = { 0x33, 0x22, 0x11, 0x00, 0xdd, 0xcc, 0xbb, 0xaa };
    d.SetKey(key, sizeof(key));
    std::string input(reinterpret_cast<char*>(plain), 8);
    CryptoPP::StringSource s(input, true, 
      new CryptoPP::StreamTransformationFilter(e,
        new CryptoPP::StringSink(result_str)
      ) // StreamTransformationFilter
    ); // StringSource

    std::string hex_result;
    CryptoPP::StringSource(result_str, true,
      new CryptoPP::HexEncoder(
        new CryptoPP::StringSink(hex_result)
      ) // HexDecoder
    ); // StringSource
    std::cout<<hex_result<<std::endl;
```
I know that correct result cipher should be "2587CAE27A12D30069E1B7CA26BD2646".
But above code is giving me "C3069674579678B3864BEBE40220757B", which is quite different.
I am using Crypto++ 8.0 version now.

**Comment by noloader** [comment]
> I know that correct result cipher should be "2587CAE27A12D30069E1B7CA26BD2646".
> But above code is giving me "C3069674579678B3864BEBE40220757B", which is quite different.

You need to set an IV with CBC mode.

**Comment by noloader** [comment]
No, it looks like something is wrong here. Reopening.

**Comment by noloader** [comment]
OK, after some research:

1. Schneier has page on SKIPJACK at https://www.schneier.com/crypto-gram/archives/1998/0715.html#skip
2. Schneier says ref impl at ftp://ftp.funet.fi/pub/crypt/cryptography/symmetric/skipjack
3. Ref impl has an original/unoptimized version at ftp://ftp.funet.fi/pub/crypt/cryptography/symmetric/skipjack/skipjack-orig.c
4. Ref impl has an optimized version at ftp://ftp.funet.fi/pub/crypt/cryptography/symmetric/skipjack/skipjack.c
5. NIST no longer provides encryption transform at https://csrc.nist.gov/projects/cryptographic-algorithm-validation-program/block-ciphers#Skipjack
6. NIST provides decryption transform for interop at https://csrc.nist.gov/projects/cryptographic-algorithm-validation-program/block-ciphers#Skipjack

I've tested (a) Crypto++, (b) Botan, (c) Ref Impl (original) and (d) Ref Impl (optimized). All of them arrive at different results.

I think the way forward is, find which algorithm arrives at the NIST test vector and use it. I suspect it is going to be Ref Impl (original). I know shortly.

**Comment by noloader** [comment]
> I think the way forward is, find which algorithm arrives at the NIST test vector and use it. I suspect it is going to be Ref Impl (original). I will know shortly.

So it looks like Crypto++ arrives at the Known Answers from [SP800-17](https://csrc.nist.gov/publications/detail/sp/800-17/archive/1998-02-01) (in particular, Table 6, pp. 140-42).

Here's the first test vector from the table

```
key: 80 00 00 00 00 00 00 00 00 00
plain: 00 00 00 00 00 00 00 00
cipher: 7a 00 e4 94 41 46 1f 5a
```

I'm going to close this report.

If you need to add the block cipher with Panu Rissanen's implementation, then copy/paste the code in `skipjack.h` and `skipjack.cpp`. Give it a new class name like `SkipjackOrig`. Then, copy-in Rissanen's code.

**Comment by noloader** [comment]
@Zungong,

I added a new wiki page at [SKIPJACK](https://www.cryptopp.com/wiki/SKIPJACK).

If you figure out the difference in implementations, then please let me know. I will add it to the wiki article. I asked a question at [Difference in SKIPJACK algorithms](https://crypto.stackexchange.com/q/70105/10496), but it may go unanswered.
