### ISSUE TITLE
static lib can't work good

### ISSUE THREAD

**Issue by a188037445** [weidai11/cryptopp#832]
I built a statis lib but it could't work, I got an incorrent result(using CRC32, MD5 or SHA1), but I run the cryptest.exe well, it showed all test passed.
And this problem doesn't exists in my server machine.
my local machine runs windows 10 2019 LTSC(64Bit), and my server machine runs windows 10 2016 LTSB((64Bit)), the cryptopp version is the lasted version 8.2.

**Comment by noloader** [comment]
https://cryptopp.com/wiki/Main_Page
