### ISSUE TITLE
Possible divide by zero

### ISSUE THREAD

**Issue by netsurf916** [weidai11/cryptopp#855]
There is an issue reported by static analysis in `pwdbased.h` where not checking the results of the hmac processing can lead to a divide by zero.

Here is the hmac portion:

    HMAC<T> hmac(secret, secretLen);
    SecByteBlock buffer(hmac.DigestSize());

If `hmac.DigestSize()` returns 0, then this subsequent call can result in a divide by zero:

    timeInSeconds = timeInSeconds / ((derivedLen + buffer.size() - 1) / buffer.size());

I haven't observed this issue in practice, but it may be useful to check the hmac results since this flow is possible.

**Comment by noloader** [comment]
Thanks @netsurf916.

I think the analysis tool's conclusion is a bit far fetched. I'm not aware of any hashes or hmac's that provide a 0-sized digest.

`DigestSize()` is a virtual function and it can be overridden in derived classes. However, its default value is the constant `DIGESTSIZE`, and it's value is at least 16 (MD5), and usually greater than 20 (SHA-1) and 32 (SHA-256).

With that said... I am a big fan of dark and silent cockpits. The tools should be quiet. What is it going to take to silence the tool? Can we do something like:

```
ThrowIfInvalidDerivedLength(derivedLen);
if (HMAC<T>::DIGESTSIZE == 0)
    throw InvalidParameter(...);
...
```

A good optimizing compiler should be able to deduce `DIGESTSIZE` is not 0 and remove the code.

What is it going to take to silence the tool?

**Comment by netsurf916** [comment]
I agree with you that it's somewhat far fetched.  It turns out, however, that the bit of code it's ultimately complaining about is in trunhash.h:

```
	unsigned int DigestSize() const
		{return 0;}
```
I suggest an easy fix could be to have it return a constant instead, but I haven't looked at the purpose for returning 0 in this case.  Otherwise, since there is a defined return of 0, it probably makes sense to add a check as you suggested.

**Comment by noloader** [comment]
Thanks again @netsurf916,

Two questions. First, which tool is producing the finding. Second, do you have a reproducer?

We should have experienced this long before it hit a user like you. That tells me we are missing a test case somewhere.

**Comment by netsurf916** [comment]
This only occurred as part of the analysis, not any test cases we're using.  The tool in this case is Coverity.

**Comment by noloader** [comment]
Thanks @netsurf916,

I'm not quite following. Coverity analyses compiled code. Something has to be using the code to produce the finding.

**Comment by netsurf916** [comment]
You're correct.  There is compiled code which references DeriveKey(), but we haven't seen this issue in practice except for the Coverity report.

Honestly, after digging into this a bit more, it could be a case of Coverity getting confused over templates.  The issue really comes down to it inferring the use of NullHash when we're actually using SHA512 when we call PBKDF2 functions.
