### ISSUE TITLE
ECIES and GetSymmetricKeyLength no longer uses MAC::DEFAULT_KEYLENGTH

### ISSUE THREAD

**Issue by noloader** [weidai11/cryptopp#856]
As discussed on the mailing list at [ECIES with no HMAC](https://groups.google.com/forum/#!topic/cryptopp-users/csUq-DqdWa8). Back around Crypto++ 5.6.5 we changed ECIES to align with Botan and Bouncy Castle. The change was mostly without incident...

However, it looks like `GetSymmetricKeyLength` took a change (also see [diff bcbf19315873](https://github.com/weidai11/cryptopp/compare/CRYPTOPP_5_6_4...CRYPTOPP_6_0_0#diff-bcbf193158734eaa1daf3c464a1e95b1)):

    - size_t GetSymmetricKeyLength(size_t plaintextLength) const
    -     {return plaintextLength + MAC::DEFAULT_KEYLENGTH;}
    + size_t GetSymmetricKeyLength(size_t plaintextLength) const
    +     {return plaintextLength + static_cast<size_t>(MAC::DIGESTSIZE);}

But `void SymmetricEncrypt(...)` did not change. It still uses `MAC::DEFAULT_KEYLENGTH`:

    const byte *cipherKey = NULLPTR, *macKey = NULLPTR;
    if (DHAES_MODE)
    {
        macKey = key;
        cipherKey = key + MAC::DEFAULT_KEYLENGTH;
    }
    else
    {
        cipherKey = key;
        macKey = key + plaintextLength;
    }

The problem did not surface under normal circumstances because `MAC::DIGESTSIZE` and `MAC::DEFAULT_KEYLENGTH` are the same under most circumstances. However, OP is using a Null hash and `MAC::DIGESTSIZE` is 0.

This will track what happens with ECIES.

**Comment by mouse07410** [comment]
@rectalogic thanks for contributing. Your fix is correct, and has been merged.

*Sotto voce: I still think null hash is a bad idea.* :-)
