### ISSUE TITLE
Incorrect paths for AdditionalLibraryDirectories in msvc for dll generation

### ISSUE THREAD

**Issue by cstamatopoulos** [weidai11/cryptopp#86]
The input lib is set to 				AdditionalLibraryDirectories="$(PlatformName)\DLL_Output\$(ConfigurationName) $(NOINHERIT)"
 however the .cryptopp.lib is output over at $(PlatformName)\Output\etc...

**Comment by DevJPM** [comment]
What is the exact problem you're having or are your proposing a cosmetic change?
Did you try the proposed change (on a local copy) and did it fix your problem?

Does it prevent you from compiling the DLL or does it prevent you from using the DLL?

**Comment by cstamatopoulos** [comment]
It is not a cosmetic change. Prevents me from building the dll.
The dll linking phase does not succeed since it cannot find the .lib.
The reason is because it is searching over at the DLL_Output folder when the static lib is output in the Output folder.

I did try the proposed changed on my local machine and all is good. I could submit a pull request by my version of msvc is 2015

**Comment by DevJPM** [comment]
So, if you clear all intermediate files a single "Batch Build -> Select All -> Build" works flawlessly? That would actually be quite nice :)

Currently you can build every project in Crypto++ by simply applying the above procedure *twice*  where 20/24 project-configurations build in the first run and the last four project-configurations build in the second run.

**Comment by cstamatopoulos** [comment]
I am not sure I got what you are trying to say but the way it is currently set up, if you build the cryptest.sln solution the only 2 projectS that are built are cryptest and cryptlib. The other 2, cryptdll and dlltest are not setup to be built at all.

However if you want to build cryptdll lets say it will fail. I just cant get it to built, unless
1) $(Platform)\Output\$(Configuration) $(NOINHERIT);%(AdditionalLibraryDirectories) 
2) Change the ${TargetName} to cryptopp so that the post build step that you have finds the dll

The 2. is probably related to the newer version of msvc and they way that it handles the namings.

With these 2 changes(of course have to build applied for every configuration) I can build all projects

**Comment by DevJPM** [comment]
Did you apply the VS2010.zip patch delivered with the library? If you did this everything *should* work out of the box (thanks to build dependencies and such) and did so (at least for me and some others) if doing a "Build -> Batch Build -> Select All -> Build" twice.

Could you upload a fork with the patch applied to GitHub so @noloader and I can test if it breaks anything VS related (VS2005 - VS 2015)?

**Comment by cstamatopoulos** [comment]
Ok, that works now I did not pay attention to the zip file.. I saw the solution and used that.

But yeah if I enable the cryptdll build in the solution, clean all-> build solution the I get everything.

**Comment by noloader** [comment]
> The input lib is set to `AdditionalLibraryDirectories="$(PlatformName)\DLL_Output$(ConfigurationName) $(NOINHERIT)"`
> however the .cryptopp.lib is output over at $(PlatformName)\Output\etc...

This could be an issue. `cryptopp.lib` should be in the `DLL_Output` folder only. It has the algorithms available for the FIPS DLL.

`cryptlib.lib` is output to both folders, depending on the configuration. For the list of configurations, see [Visual Studio | Projects and Configurations](http://www.cryptopp.com/wiki/Visual_Studio#Projects_and_Configurations) on the wiki.

I think we'll need to look into it some more.

-----

> The dll linking phase does not succeed since it cannot find the .lib.

When we were investigation this in the past, I seem to recall there was a problem expressing the intra-project dependencies. The DLL gear had requirements not present in the regular lib project.

Again, I think we'll need to look into it some more.

**Comment by noloader** [comment]
We might be making Visual Studio 2010 the default sometime after the first of the year. See [Make VS2010 default sometime in 2016?](https://groups.google.com/d/msg/cryptopp-users/vCYAEj3OI8g/BPxFrKedDgAJ). The community has to approve it, however. If the community does not approve, then we don't have authority to act.

**Comment by noloader** [comment]
@ cstamatopoulos  - I'm going to close this bug report. I don't believe there's anything we can do to fix Microsoft's ***`VCUpgrade`***. I have even tried to figure out ways to work *with* `VCUpgrade` by, say working from the command line and providing options to drive the upgrade. Unfortunately, the tool is poorly documented, and we can't seem to improve the situation for users.

I even went through the VS2005 project and added explicit paths and libraries for the linker hoping `VCUpgrade` would use them for the upgraded project files. That proved to be a waste of time because `VCUpgrade` still did what it wanted to do.

As you now know, we do provide a pre-converted ***`vs2010.zip`***. That seems to be the best we can do at this point.
