### ISSUE TITLE
CRYPTOPP_ARM_CRC32_AVAILABLE is set even when +crc is not set in march

### ISSUE THREAD

**Issue by sobczyk** [weidai11/cryptopp#868]
### Crypto++ Issue Report

Cross compiling on ubuntu 18.04 for aarch64 (just armv8-a)

Cryptopp 8.0, built using custom buildsystem

```.sh
aarch64-linux-gnu-g++ -MMD -MF obj/deps/build/cryptlib/cryptlib/crc_simd.o.d -DNDEBUG -I../../../deps/build/cryptlib -Wall -Werror -fopenmp -fno-strict-aliasing -funwind-tables -fPIC -pipe -fdiagnostics-color -fstack-protector-strong -pthread -O3 -fno-ident -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g2 -fvisibility=hidden -Wno-attributes -fvisibility-inlines-hidden -std=c++17 -c ../../../deps/build/cryptlib/crc_simd.cpp -o obj/deps/build/cryptlib/cryptlib/crc_simd.o
```

```
In file included from ../../../deps/build/cryptlib/crc_simd.cpp:24:0:
/usr/lib/gcc-cross/aarch64-linux-gnu/7/include/arm_acle.h: In function ‘bool CryptoPP::CPU_ProbeCRC32()’:
/usr/lib/gcc-cross/aarch64-linux-gnu/7/include/arm_acle.h:77:1: error: inlining failed in call to always_inline ‘uint32_t __crc32w(uint32_t, uint32_t)’: target specific option mismatch
 __crc32w (uint32_t __a, uint32_t __b)
 ^~~~~~~~
../../../deps/build/cryptlib/crc_simd.cpp:98:11: note: called from here
         w = __crc32w(w,x);
         ~~^~~~~~~~~~~~~~~
In file included from ../../../deps/build/cryptlib/crc_simd.cpp:24:0:
/usr/lib/gcc-cross/aarch64-linux-gnu/7/include/arm_acle.h:71:1: error: inlining failed in call to always_inline ‘uint32_t __crc32h(uint32_t, uint16_t)’: target specific option mismatch
 __crc32h (uint32_t __a, uint16_t __b)
 ^~~~~~~~
../../../deps/build/cryptlib/crc_simd.cpp:99:11: note: called from here
         w = __crc32h(w,y);
         ~~^~~~~~~~~~~~~~~
In file included from ../../../deps/build/cryptlib/crc_simd.cpp:24:0:
/usr/lib/gcc-cross/aarch64-linux-gnu/7/include/arm_acle.h:41:1: error: inlining failed in call to always_inline ‘uint32_t __crc32b(uint32_t, uint8_t)’: target specific option mismatch
 __crc32b (uint32_t __a, uint8_t __b)
 ^~~~~~~~
../../../deps/build/cryptlib/crc_simd.cpp:100:11: note: called from here
         w = __crc32b(w,z);
         ~~^~~~~~~~~~~~~~~
In file included from ../../../deps/build/cryptlib/crc_simd.cpp:24:0:
/usr/lib/gcc-cross/aarch64-linux-gnu/7/include/arm_acle.h:59:1: error: inlining failed in call to always_inline ‘uint32_t __crc32cw(uint32_t, uint32_t)’: target specific option mismatch
 __crc32cw (uint32_t __a, uint32_t __b)
 ^~~~~~~~~
../../../deps/build/cryptlib/crc_simd.cpp:101:11: note: called from here
         w = __crc32cw(w,x);
         ~~^~~~~~~~~~~~~~~~
In file included from ../../../deps/build/cryptlib/crc_simd.cpp:24:0:
/usr/lib/gcc-cross/aarch64-linux-gnu/7/include/arm_acle.h:53:1: error: inlining failed in call to always_inline ‘uint32_t __crc32ch(uint32_t, uint16_t)’: target specific option mismatch
 __crc32ch (uint32_t __a, uint16_t __b)
 ^~~~~~~~~
../../../deps/build/cryptlib/crc_simd.cpp:102:11: note: called from here
         w = __crc32ch(w,y);
         ~~^~~~~~~~~~~~~~~~
In file included from ../../../deps/build/cryptlib/crc_simd.cpp:24:0:
/usr/lib/gcc-cross/aarch64-linux-gnu/7/include/arm_acle.h:47:1: error: inlining failed in call to always_inline ‘uint32_t __crc32cb(uint32_t, uint8_t)’: target specific option mismatch
 __crc32cb (uint32_t __a, uint8_t __b)
 ^~~~~~~~~
../../../deps/build/cryptlib/crc_simd.cpp:103:11: note: called from here
         w = __crc32cb(w,z);
         ~~^~~~~~~~~~~~~~~~
```

**Comment by sobczyk** [comment]
I'm not sure if `__ARM_FEATURE_CRC32` is defined on MS compiler.
The fix is different for some cases

**Comment by sobczyk** [comment]
I just found out that `CRYPTOPP_ARM_PMULL_AVAILABLE` suffers the same issue, it is set without `+crypto`

**Comment by noloader** [comment]
Related, see [BASE+SIMD](https://www.cryptopp.com/wiki/BASE%2BSIMD) on the wiki.

The build system you are using needs to set the appropriate arch flags for source files or `-DCRYPTOPP_DISABLE_ASM`. Most of them are listed under [Arch Options](https://www.cryptopp.com/wiki/BASE%2BSIMD#Arch_Options).

Also see [Variables for Specifying Commands](https://www.gnu.org/prep/standards/html_node/Command-Variables.html) in the GNU manual. The arch options fall under:

> If there are C compiler options that must be used for proper compilation of certain files, do not include them in CFLAGS. Users expect to be able to specify CFLAGS freely themselves. Instead, arrange to pass the necessary options to the C compiler independently of CFLAGS, by writing them explicitly in the compilation commands or by defining an implicit rule ...

**Comment by sobczyk** [comment]
Why not change
```c++
#if !defined(CRYPTOPP_ARM_CRC32_AVAILABLE) && !defined(CRYPTOPP_DISABLE_ASM)
# if defined(__aarch32__) || defined(__aarch64__) || defined(_M_ARM64)
#  if defined(__ARM_FEATURE_CRC32) || (CRYPTOPP_GCC_VERSION >= 40800) || \
      (CRYPTOPP_LLVM_CLANG_VERSION >= 30300) || (CRYPTOPP_MSC_VERSION >= 1916)
#   define CRYPTOPP_ARM_CRC32_AVAILABLE 1
#  endif  // Compilers
# endif  // Platforms
#endif
```
to
```c++
#if !defined(CRYPTOPP_ARM_CRC32_AVAILABLE) && !defined(CRYPTOPP_DISABLE_ASM)
# if defined(__aarch32__) || defined(__aarch64__) || defined(_M_ARM64)
#  if defined(__ARM_FEATURE_CRC32) || (CRYPTOPP_MSC_VERSION >= 1916)
#    if (CRYPTOPP_GCC_VERSION >= 40800) || (CRYPTOPP_LLVM_CLANG_VERSION >= 30300)
#     define CRYPTOPP_ARM_CRC32_AVAILABLE 1
#    endif  // Compilers
#  endif  // MSVC/ Feature
# endif  // Platforms
#endif
```
That'd reduce the number of arguments for the compiler.

**Comment by noloader** [comment]
> That'd reduce the number of arguments for the compiler.

`CRYPTOPP_ARM_CRC32_AVAILABLE` depends on compiler support for the crc instruction. If `That'd reduce the number of arguments for the compiler.` is _not_ defined, then the code paths are disabled. Nothing interesting in this case...

However, if the compiler supports crc, then we need to signal in both `crc.cpp` (without arch flags) and `crc_simd.cpp` (with arch flags). That's because `crc.cpp` has to call the SIMD version. `crc.cpp` does something like this (with some hand waiving):

```
#if (CRYPTOPP_ARM_CRC32_AVAILABLE)
if (HasCRC32())
{
    CRC32_ARMV8(s, n, m_crc);
}
else
#endif 
{
    CRC32_CXX(s, n, m_crc);
}
```

**Comment by sobczyk** [comment]
My bad, I should just remove `(CRYPTOPP_GCC_VERSION >= 40800) || (CRYPTOPP_LLVM_CLANG_VERSION >= 30300)`

clang & gcc define macro `__ARM_FEATURE_CRC32` so no version check is required there, and we assume the proper version of msvc supports crc32

**Comment by noloader** [comment]
> clang & gcc define macro __ARM_FEATURE_CRC32 so no version check is required there

Oh, it gets worse... It does not hold for older GCC, and it does not hold on platforms like Android.

Clang and GCC have made an absolute mess out of this simple task.

**Comment by sobczyk** [comment]
They just pulled up to properly support ACLE, which microsoft does not care for
https://developer.arm.com/docs/101028/latest/feature-test-macros

**Comment by noloader** [comment]
> They just pulled up to properly support ACLE

Lol... Don't get me started on Clang and GCC honoring the [ACLE](http://infocenter.arm.com/help/topic/com.arm.doc.ihi0053c/IHI0053C_acle_2_0.pdf) and doing things like defining `__ARM_ACLE` as specified in ARM docs (not that Microsoft is much better). Ignoring ARM's guidance is the reason for the compile test to determine if we can include `<arm_acle.h>`, and the define `CRYPTOPP_ARM_ACLE_AVAILABLE`.

**Comment by sobczyk** [comment]
so define the defaults safely, and enable if checks pass?
If acle defines are there it will be fine, if they are missing additional checks are required for enabling these features,
so that minimal compiler flag count will compile the sources.

**Comment by sobczyk** [comment]
`The feature test macros allow programmers to determine the availability of ACLE or *subsets* of it`
some featurea get deprecated in newer acle versions, if gcc/clang decided for defining `__ARM_ACLE` they'd need to disable some, maybe they decided it's not worth the hassle and just stick to feature macros

**Comment by noloader** [comment]
> maybe they decided it's not worth the hassle and just stick to feature macros

When Clang and GCC (and Microsoft) (and Android and iOS since it depends on the platform, too) don't define `__ARM_ACLE` properly, we have a hard time figuring out when to `#include <arm_acle.h>`. When `<arm_acle.h>` is missing but it is needed, the CRC, AES and SHA declarations go missing and it breaks the compile. And if `<arm_acle.h>` is not needed but we include it, it also breaks the compile.

But that boat has already sailed. We were fucked years ago.

**Comment by noloader** [comment]
You best bet - with the custom build system but without using arch options - is probably going to be, maintain a `cryptopp.patch`. Apply it after unpacking the zip or after a `git pull` to put the header file in a good state for you.

I've got a collection of custom patches for other projects at [Noloader | Build-Scripts](https://github.com/noloader/Build-Scripts/tree/master/patch). I fix the projects after unpacking the tarballs.

**Comment by sobczyk** [comment]
I see this is a ~~clusterf...~~ bad situation, backward compatibility does not make it simpler.

arm_acle.h from new clang actually checks for the `__ARM_ACLE` macro 🤦‍♂

**Comment by noloader** [comment]
Do you need anything else @sobczyk ? If not, then I'd like to close the report.

**Comment by sobczyk** [comment]
No, though I'd be great to mention these fails in some document with easily grepable keywords,
so the next person that hits this problem does not search too long.
