### ISSUE TITLE
Size cannot be zero

### ISSUE THREAD

**Issue by irwir** [weidai11/cryptopp#875]
https://github.com/weidai11/cryptopp/blob/8130bd7a2405dbf889b8a0e3baa54ace7b630afc/secblock.h#L208

The condition `size == 0` was already checked five lines above.

**Comment by noloader** [comment]
Thanks @irwir. Cleared at [Commit b444c02886dc](https://github.com/weidai11/cryptopp/commit/b444c02886dc).

**Comment by noloader** [comment]
Thanks @irwir. Cleared at [Commit b444c02886dc](https://github.com/weidai11/cryptopp/commit/b444c02886dc).
