### ISSUE TITLE
Regression in Elliptic Curve Operation on brainpoolP256r1

### ISSUE THREAD

**Issue by noloader** [weidai11/cryptopp#878]
As reported on the mailing list by Philippe Antoine at [Regression in Elliptic Curve Operation on brainpoolP256r1](https://groups.google.com/d/msg/cryptopp-users/RfAFR3_y1sI/qYH2rTavBQAJ):

```
...
I have been doing differential fuzzing about elliptic curve cryptography with different libraries including cryptopp.

On August the 6th, oss-fuzz found the first regression after about one year.
I think this is dut to commit https://github.com/weidai11/cryptopp/commit/c9ef9420e762b91cc06463d349cf06e04c749b9d

My output is the following

point=04202020202020ffffff2020202020200020ffffffff20202020ff20ff20ff200104c8423eb699c3ace2e623855cb9238cb43971464f4b6686765c46ed4ce035dc

bignum=000000000000000000000000000000000000000000000000000000000000000a

mbedlts:045de6bae41907dbe3f0aa32b272add6b92fb2b79fdc49af35fb844be1c4c629e899295109c41cfe76a9c06c23d95b2d4be3b6f61a476acf1a67a0d848abba89e1

libecc:045de6bae41907dbe3f0aa32b272add6b92fb2b79fdc49af35fb844be1c4c629e899295109c41cfe76a9c06c23d95b2d4be3b6f61a476acf1a67a0d848abba89e1

libecc:045de6bae41907dbe3f0aa32b272add6b92fb2b79fdc49af35fb844be1c4c629e899295109c41cfe76a9c06c23d95b2d4be3b6f61a476acf1a67a0d848abba89e1

openssl:045de6bae41907dbe3f0aa32b272add6b92fb2b79fdc49af35fb844be1c4c629e899295109c41cfe76a9c06c23d95b2d4be3b6f61a476acf1a67a0d848abba89e1

gcrypt:045de6bae41907dbe3f0aa32b272add6b92fb2b79fdc49af35fb844be1c4c629e899295109c41cfe76a9c06c23d95b2d4be3b6f61a476acf1a67a0d848abba89e1

cryptopp:0407f16bad8b16f5441f1a15f8e7eca364d97bb3a3c09b320bb9807ee26857b66f882ba526e55ebbf22342ae5a0186ed0ca1db8870fd001c63ae36dc72ee15f6e7


That means when I multiply by 10 the point on the curve brainpoolP256r1

x = 202020202020ffffff2020202020200020ffffffff20202020ff20ff20ff2001

y = 04c8423eb699c3ace2e623855cb9238cb43971464f4b6686765c46ed4ce035dc

I get a different result than all the other libraries.
```

**Comment by catenacyber** [comment]
The temporary fix makes it work again even if I guess it is a regression on #869 

For the self tests, I can share the fuzzer generated corpus so as to find out if there are more interesting cases missing in cryptopp tests

**Comment by catenacyber** [comment]
The fix does not seem complete finally.

Here is another reproducer found by oss-fuzz

```
Integer x("0x20ffff2020ff000020ff2020202020ff20ff20ff202020ffffff20200020ffff");
Integer y("0xba1a84de8fe276f1d082e3e7c10f35e0baca90baca7c9502044854dba0ecdebc");
Integer s("0x0000000000000000000000000000000000000000000000000000000000000007");

GroupParameters params(ASN1::brainpoolP256r1());
ECP::Element p(x, y);

ECP::Element t = params.GetCurve().ScalarMultiply(p, s);
std::cout << std::hex << t.x << std::endl;
std::cout << std::hex << t.y << std::endl;
```

Result should be
04a171dbcb9c038c01ebd7635e4302f87d38c5cc3babb819239b52572d6fb4490804ed340e0d0f7a2e47cf1f48273dc2d40434c295254c55ae420912e4d2c5be02

Instead, we get
0400000000000000000000000000000000000000000000000000000000000000003238e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e06aa8539

**Comment by noloader** [comment]
Thanks again @ catenacyber. This is worse than I thought. Even Crypto++ 5.6.3 is producing incorrect results. And it is producing different results than Crypto++ 8.2/8.3 on the same machine.

For example, for Crypto++ 5.6.3:

```
git checkout CRYPTOPP_5_6_3
make -j 8
# fix a few compile errors

g++ -o test.exe test.cxx ./libcryptopp.a
 ./test.exe 
5de6bae41907dbe3f0aa32b272add6b92fb2b79fdc49af35fb844be1c4c629e8h
99295109c41cfe76a9c06c23d95b2d4be3b6f61a476acf1a67a0d848abba89e1h
```

And Master on the same machine:

```
$ ./test.exe 
7f16bad8b16f5441f1a15f8e7eca364d97bb3a3c09b320bb9807ee26857b66fh
882ba526e55ebbf22342ae5a0186ed0ca1db8870fd001c63ae36dc72ee15f6e7h
```

-----

```
$ cat test.cxx
#include "osrng.h"
#include "eccrypto.h"
#include "oids.h"
#include <iostream>

int main (int argc, char* argv[])
{
  using namespace CryptoPP;

  typedef DL_GroupParameters_EC<ECP> GroupParameters;

  Integer x("0x202020202020ffffff2020202020200020ffffffff20202020ff20ff20ff2001");
  Integer y("0x04c8423eb699c3ace2e623855cb9238cb43971464f4b6686765c46ed4ce035dc");
  Integer s("0x000000000000000000000000000000000000000000000000000000000000000a");

  GroupParameters params(ASN1::brainpoolP256r1());
  ECP::Element p(x, y);

  ECP::Element t = params.GetCurve().ScalarMultiply(p, s);
  std::cout << std::hex << t.x << std::endl;
  std::cout << std::hex << t.y << std::endl;
	
  return 0;
}
```

This is really bad...

**Comment by noloader** [comment]
@ catenacyber ,

This is worse than I expected. Your second test case, `x=0x20ffff2020ff000020ff...`, produces incorrect results using Crypto++ 5.6.2. (The first case is OK under Crypto++ 5.6.2).

The Crypto++ 5.6.2 result is like a punch in the gut. it means I did not break it, so there's no easy fix via a revert.

Can you tell me all the bad curves you have identified since the patch that fixed your first test case? I'm trying to determine the breadth of the problem.

**Comment by catenacyber** [comment]
> produces incorrect results using Crypto++ 5.6.2

Did you try other versions ?
Was 5.6.2 the first one to support elliptic curves ?

> Can you tell me all the bad curves you have identified since the patch that fixed your first test case? 

Running version at commit 7b0ec4d4a68ef8d089dee4f87db9e1b88b66b79b, I get the following outputs with different results :

curve=27 brainpool384r1
point=047346e17c5dc09256f0a69081af1abe21191ed84966cbf9791a8259e68148cd5c532c58d66ee3200e78b8feecd6f813ad88c6fbe606671fddd8ebf20b5a2805f970c4790417db8968de40e9028a4512c3e3cb0bcd8d363d4a1b0b7f0b49a97ec6
bignum=00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001b

curve=26 brainpool256r1
point=040000ffffffffffffff000000000000002100000000002f80000000d33513c92fa353bb7f1fab465c435e8aef29e96bc117be66647c4eb9fa55971ec54d58eb2e
bignum=000000000000000000000000000000000000000000000000000000000000001a

curve=27 brainpool384r1
point=04800000000000008000000000000100002e4e49535420502d3338310000ffde7fffffff0000003a7fffffff000800000039bb9ba98a34892c7e94b35bfb50b5c942c7c201b17b582fd9bb98352a8affa38ebae2e37703716a687481714f232736
bignum=00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001b

curve=26 brainpool256r1
point=0400000000000000000300ffffdfdf8000ff0001ff000006003a0000000126000038c7fc28fc2547cc80fd1e95436a3f8b80e996172d92a1e4c25e90d3c2dd1dda
bignum=0000000000000000000000000000000000000000000000000000000000000006

curve=28 brainpool512r1
point=040000f808ffff00637261696e706f6f6ccccccc0000000110312e322e36353533372e3130302e3100ffff000000000000000000ff000000000000000042000000a22b7ea3d332d4a3601d1a2da159f673a9ccae7ea17e7607ae4f9d192d32eeb5e9298a820b995d9ef1972d1ff74a13a9f850ca1cba1e472842bec9cfc6dbf9bf
bignum=00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000017

curve=26 brainpool256r1
point=0413fffffffffffffffffffffffffbff7cffff0000000cbfff6bc900000000000040520c7b5d9b600bb6008693ed8d27b6b0e497bfdccec2c48dab87e4c55ceb5c
bignum=000000000000000000000000000000000000000000000000000000000000000c

curve=26 brainpool256r1
point=04000000000000000000000000000c0013ffffffffffffffff00000000000000007dda47bde6511090fc4e184ac5a319674893ddff7eb8e781e2032369ae2ab85c
bignum=0000000000000000000000000000000000000000000000000000000000000002

curve=26 brainpool256r1
point=040000ffffffffffffff000000000000002100000000002f80000000d33413c92f7a067afcc5915d9c761b7fa0e2da7d9cee3ed2505732e2686beb3a3ada802a96
bignum=000000000000000000000000000000000000000000000000000000000000001a

curve=26 brainpool256r1
point=0400000001000000000400f200ef00ff0b0000006b65796c65ff6e236dffff000081b2a07e0ab470694b38cf91600ee8826666fba214af49e6d138a30dc75f57f6
bignum=0000000000000000000000000000000000000000000000000000000000000004

curve=26 brainpool256r1
point=04000000000000000000000000000000000000000000000000000000000000000109e0e9e8d98fb89da2a32b2c7618b26bb99b920f02a5e831a142e6c8673110cd
bignum=000000000000000000000000000000000000000000000000000000000000000f

curve=26 brainpool256r1
point=0400000000000000000800ffffdfdf8000ff0001ff000000063a00000001260000224e2dcfef02f48245383aa9bcd4eb7f32cc0886fff2e70d27fb3c9defed46f0
bignum=0000000000000000000000000000000000000000000000000000000000000006

curve=26 brainpool256r1
point=0400000000000000000300ffffdfdf8000ff0001ff000000063a00000001260000795ba051cd7a7c32917c33056da45a42b4472ae4e5921dc41d83ef3c959ac13c
bignum=0000000000000000000000000000000000000000000000000000000000000006

**Comment by noloader** [comment]
> Did you try other versions ?
> Was 5.6.2 the first one to support elliptic curves ?

No, EC was supported earlier than 5.6.2. The significance of 5.6.2 is, it is the last version of Crypto++ Wei released. After that he turned the library over to the community. (Usually we break things. It is rare to find a Wei bug. They are kind of like Knuth bugs).

-----

> I get the following outputs with different results :

```

> curve=27 brainpool384r1
> point=047346e17c5dc09256f0a69081af1abe21191ed84966cbf9791a8259e68148cd5c532c58d66ee3200e78b8feecd6f813ad88c6fbe606671fddd8ebf20b5a2805f970c4790417db8968de40e9028a4512c3e3cb0bcd8d363d4a1b0b7f0b49a97ec6
> bignum=00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001b
```

OK, that's very helpful. Thanks.

It is helpful because it is helping me separate my bug (broken NIST) from Wei's bug (broken Brainpool).

**Comment by catenacyber** [comment]
You can try to find the step (add or double) where the computation gets wrong

**Comment by randombit** [comment]
The second test case doesn't seem to be valid - Y as given is larger than brainpool256r1's prime. And even if Y is reduced modulo p, the point does not satisfy the curve equation. I don't understand how you would see consistent results between impls with an invalid point.

**Comment by catenacyber** [comment]
How so :
```
curve=26 brainpool256r1
point=040000ffffffffffffff000000000000002100000000002f80000000d33513c92fa353bb7f1fab465c435e8aef29e96bc117be66647c4eb9fa55971ec54d58eb2e
bignum=000000000000000000000000000000000000000000000000000000000000001a
```
Means
```
x=0000ffffffffffffff000000000000002100000000002f80000000d33513c92f
y=a353bb7f1fab465c435e8aef29e96bc117be66647c4eb9fa55971ec54d58eb2e
```

and brain pool has `p =
      A9FB57DBA1EEA9BC3E660A909D838D726E3BF623D52620282013481D1F6E5377`

so a3 is lesser than a9

**Comment by catenacyber** [comment]
Ok, this one was about secp256k1, ant not brainpool

**Comment by noloader** [comment]
@catenacyber ,

I have some time coming up and I want to loop back around to this issue.

I don't have good data from your testing results. I'm not sure about this set. What is curve 26? And what is the result?

```
curve=26 brainpool256r1
point=040000ffffffffffffff000000000000002100000000002f80000000d33513c92fa353bb7f1fab465c435e8aef29e96bc117be66647c4eb9fa55971ec54d58eb2e
bignum=000000000000000000000000000000000000000000000000000000000000001a
```

Would you please email me the data in this format. My email address is *noloader, gmail* account.

* curve
* x coordinate
* y coordinate
* scalar multiplier
* expected result

**Comment by catenacyber** [comment]
> What is curve 26?

This is TLS curve ID
26 is defined here https://tools.ietf.org/html/rfc7027 as brainpoolP256r1

The point is in some TLS format as well where 04 means uncompressed, and then you get x and y coordinates.

Is this good enough or should I send you the details ? (it will take more time for me)

**Comment by catenacyber** [comment]
I have been working on my fuzzer.
This includes fuzzing not only scalar multiplication, but points addition as well.

And I get to this failure 
```
curve=20 secp224k1
point=04b50a000a00391439001439430a390a000000391439001439430a390a5a7480b19f40f66928f6d5407e1d56aef05751df3e87240c71d5fcdf
point2=04390a14393900000014b5b5143400143939001439390a39390a0000b54c510cffdd6bfb7c4f1a058d13102de6e796754eb6aafd8de2559c10
mbedlts:046e7dc792ce81b54d1ad10fb0ec3024c969869fa8d4bc36719fc2943495563306ef7e45d8eca0f1866c94602e3bd74ca38acad570050b1d55
openssl:046e7dc792ce81b54d1ad10fb0ec3024c969869fa8d4bc36719fc2943495563306ef7e45d8eca0f1866c94602e3bd74ca38acad570050b1d55
cryptopp:04d3954560425d9ebe6ac8e988319cbe43d60b94481981b1763de5d81d21d5a6485b717a130b4b8c7aad56619a28fa2d0267377a767ab8a20a
Module cryptopp and openssl returned different points for test 0
fail for secp224k1
fail for cryptopp
```
Is this helpful ?

**Comment by noloader** [comment]
Cleared with Crypto++ 8.3 release under [Issue 869](https://github.com/weidai11/cryptopp/issues/869).

**Comment by catenacyber** [comment]
Which was the commit fixing this ?

**Comment by catenacyber** [comment]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=21097 is still open with revision Cryptopp: ebf9e2e4acc329e2ee223e1efb54dbfc2bf7d8ac

**Comment by noloader** [comment]
> https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=21097 is still open with revision Cryptopp: ebf9e2e

Sorry, I'm not familiar with what is going on at Chromium bugs.

**Comment by catenacyber** [comment]
The point is just the link where you can download a reproducer case for the elliptic differential fuzzer.
Do you want me to run it ?

**Comment by catenacyber** [comment]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=21097 got finally verified with Cryptopp with commits https://github.com/weidai11/cryptopp/compare/38cff9aa59f299f7d1e802e614edc205ee2965fb...5dfc7e1c27d2d3225257f1458f0a5b3e623d08e7

So all ok for me, thanks :-)
