### ISSUE TITLE
Project structure re-organisation

### ISSUE THREAD

**Issue by KayEss** [weidai11/cryptopp#879]
I'm just wondering if there's any appetite for this really. Right now internal headers, public headers, implementation and test files are all piled together into a jumbled mess.

Would it not be much better to clean this up? I'd be happy to help with this effort

I think it would also make things much simpler with respect to other build systems. I maintain a cmake build file for the project and I keep getting odd regressions due to not knowing which files I need for the build and which ones are part of the testing and benchmarking.

**Comment by noloader** [comment]
> Would it not be much better to clean this up?

This was (is?) a design decision. The flat directory structure means GDB can find symbols for object files immediately after a build.

If object files and symbols were scattered then we would be fielding mailing list messages and bug reports.

**Comment by KayEss** [comment]
I talked to the developer of libpqxx as he also uses make (albeit with autoconf) and he thinks this used to be much more of a problem on earlier versions. For me, I've never seen gdb fail to find the source or anything (but I build using bjam or now, cmake).

Is there some half way thing here? Split out the headers, or at least organise some more of the tests or performance benchmarking? There's also an odd instruction to specify the link order with a certain set of files first -- there are ways around this in C++.

**Comment by ciklysta** [comment]
> If source files, object files and symbols were scattered then we would be fielding mailing list messages and bug reports.

Do you think this still applies in 2020? We've been using cmake and out of source builds for many years without problem.

I would also vote for separating api headers to an `include` directory, and so on. Also willing to help with it. IMO by such separation you clearly say what is what in the most simple way - using a file hierarchy. As @KayEss mentioned - that helps when building with alternative ("modern") build systems.

If interested, I can prepare a pull request and @noloader will try it on multiple compilers/debuggers and see if there is any problem he is worried about.

**Comment by AraHaan** [comment]
tbh I would love if there was 3 versions of crypto++, 1st version is how it is now, 2nd version is header only, 3rd version using c++ modules in c++ 20.
