### ISSUE TITLE
msvc instant crash in debug build

### ISSUE THREAD

**Issue by mq1n** [weidai11/cryptopp#881]
* State the operating system and version (Ubutnu 17 x86_64, Windows 7 Professional x64, etc)
Windows 10 RS5 x64
* State the version of the Crypto++ library (Crypto++ 5.6.5, Master, etc)
Tried on master and 8.1.0
* State how you built the library (Makefile, Cmake, distro, etc)
VS solution
* Show a typical command line (the output of the compiler for cryptlib.cpp)
Have not any warning or error
1>cryptlib.vcxproj -> C:\Users\Administrator\Desktop\cryptopp-CRYPTOPP_8_1_0\Win32\Output\Debug\cryptlib_debug.lib
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========
* Show the link command (the output of the linker for libcryptopp.so or cryptest.exe)
Default
* Show the exact error message you are receiving (copy and paste it); or
Call stacks;
http://i.koray.cc/feb7dde5b60fdbd8f25690d6e32c649e.png
http://i.koray.cc/6601228dd0901cb65234983666882dc2.png
* Clearly state the undesired behavior (and state the expected behavior)
When I link cryptopp static library in debug build mode to another 3rd app, the app instant crash before than their entrypoint when I launch.

**Comment by noloader** [comment]
It looks like you have a memory error. Based on the information you provided, I am probably not going to be able to help. If you put your code on GitHub I can take a look at it.
