### ISSUE TITLE
Unable to locate program input point GetLogicalProcesserInformation

### ISSUE THREAD

**Issue by Guozht** [weidai11/cryptopp#882]
In Windows XP SP2 or lower
cannot locate program input points  GetLogicalProcesserInformation()
![1569424587(1)](https://user-images.githubusercontent.com/31638230/65614950-20ac9280-dfeb-11e9-8104-cd6a9cadc52e.png)

**Comment by noloader** [comment]
`GetLogicalProcesserInformation` not being used by Crypto++:

```
cryptopp$ grep -IR  GetLogicalProcesserInformation
cryptopp$
```

**Comment by noloader** [comment]
This appears to be a problem with the application, not the library.
