### ISSUE TITLE
Tiny issue with extra semicolons and gcc-9.2.0 in pedantic mode

### ISSUE THREAD

**Issue by vgfl** [weidai11/cryptopp#889]
gcc-9.2.0 in pedantic mode complains about extra semicolons here:

```
keccak.h:104:49: warning: extra ';' [-Wpedantic]
  104 | DOCUMENTED_TYPEDEF(Keccak_Final<28>, Keccak_224);
      |                                                 ^
keccak.h:108:49: warning: extra ';' [-Wpedantic]
  108 | DOCUMENTED_TYPEDEF(Keccak_Final<32>, Keccak_256);
      |                                                 ^
keccak.h:112:49: warning: extra ';' [-Wpedantic]
  112 | DOCUMENTED_TYPEDEF(Keccak_Final<48>, Keccak_384);
      |                                                 ^
keccak.h:116:49: warning: extra ';' [-Wpedantic]
  116 | DOCUMENTED_TYPEDEF(Keccak_Final<64>, Keccak_512);
      |                                                 ^
```

**Comment by noloader** [comment]
Thanks @vgfl.

This happens all the time `CRYPTOPP_CONSTANT` and `DOCUMENTED_TYPEDEF`. They are defines declared like so:

```
#define CRYPTOPP_CONSTANT(X, N) enum {X = N};
```

I think we should drop the semicolon from the define, so we can write code normally:

```
CRYPTOPP_CONSTANT(Foo, 10);
```

@mouse07410 , @MarcelRaad , do you guys have any thoughts on this?

**Comment by noloader** [comment]
OK, so I checked in a change to switch patterns: the define no longer adds the semicolon.

I used sed for the change to both `CRYPTOPP_CONSTANT` and `DOCUMENTED_TYPEDEF`. It may have cast too wide a net. A test compile did not generate any warnings.

```
ed -i '/DOCUMENTED_TYPEDEF/ s/$/;/' *.h
ed -i '/DOCUMENTED_TYPEDEF/ s/$/;/' *.cpp
ed -i '/DOCUMENTED_TYPEDEF/ s/$/;/' *.cxx
# manually fix typedef in config_misc.h and config_ns.h
unix2dos *.h *.cpp *.cxx
```

**Comment by noloader** [comment]
OK, so I checked in a change to switch patterns: the define no longer adds the semicolon.

I used sed for the change to both `CRYPTOPP_CONSTANT` and `DOCUMENTED_TYPEDEF`. It may have cast too wide a net. A test compile did not generate any warnings.

```
ed -i '/DOCUMENTED_TYPEDEF/ s/$/;/' *.h
ed -i '/DOCUMENTED_TYPEDEF/ s/$/;/' *.cpp
ed -i '/DOCUMENTED_TYPEDEF/ s/$/;/' *.cxx
# manually fix typedef in config_misc.h and config_ns.h
unix2dos *.h *.cpp *.cxx
```

**Comment by noloader** [comment]
OK, so I checked in a change to switch patterns: the define no longer adds the semicolon. See [Commit 589c25264a3b](https://github.com/weidai11/cryptopp/commit/589c25264a3b).

I used sed for the change to both `CRYPTOPP_CONSTANT` and `DOCUMENTED_TYPEDEF`. It may have cast too wide a net. A test compile did not generate any warnings.

```
ed -i '/DOCUMENTED_TYPEDEF/ s/$/;/' *.h
ed -i '/DOCUMENTED_TYPEDEF/ s/$/;/' *.cpp
ed -i '/DOCUMENTED_TYPEDEF/ s/$/;/' *.cxx
# manually fix typedef in config_misc.h and config_ns.h
unix2dos *.h *.cpp *.cxx
```

**Comment by noloader** [comment]
OK, so I checked in a change to switch patterns: the define no longer adds the semicolon. See [Commit 589c25264a3b](https://github.com/weidai11/cryptopp/commit/589c25264a3b).

I used sed for the change to both `CRYPTOPP_CONSTANT` and `DOCUMENTED_TYPEDEF`. It may have cast too wide a net. A test compile did not generate any warnings.

```
ed -i '/DOCUMENTED_TYPEDEF/ s/$/;/' *.h
ed -i '/DOCUMENTED_TYPEDEF/ s/$/;/' *.cpp
ed -i '/DOCUMENTED_TYPEDEF/ s/$/;/' *.cxx
# manually fix typedef in config_misc.h and config_ns.h
unix2dos *.h *.cpp *.cxx
```
