### ISSUE TITLE
Two files for Buildroot: Config.in, libcryptopp.mk

### ISSUE THREAD

**Issue by jhealyt** [weidai11/cryptopp#913]
I'm working on a embedded Linux project, using "Buildroot" to put my operating system together along with packages. Buildroot comes with loads of packages already built-in, but it also gives you the option of adding in your own.

I have added libcryptopp to my Buildroot. Before doing this, I searched the web to see if anyone had done it before, and all I could find was two incomplete sets of files.

So I've put together my own. They're not perfect and I might tweak them in future, but here's what I've got so far:

Config.in:
```
config BR2_PACKAGE_LIBCRYPTOPP
	bool "libcryptopp"
	help
	  An advanced C++ encryption library (AES, Twofish, TripleDES)

	  http://www.cryptopp.com/
```

libcryptopp.mk:
```
################################################################################
#
# libcryptopp
#
################################################################################

LIBCRYPTOPP_VERSION = 8.2.0
LIBCRYPTOPP_SOURCE = cryptopp$(subst .,,$(LIBCRYPTOPP_VERSION)).zip
LIBCRYPTOPP_SITE = $(TOPDIR)/board/abc/xyz/distfiles
LIBCRYPTOPP_SITE_METHOD = file
LIBCRYPTOPP_INSTALL_STAGING = YES
LIBCRYPTOPP_INSTALL_TARGET = NO
LIBCRYPTOPP_INSTALL_HOST = NO
LIBCRYPTOPP_DEPENDENCIES = 
LIBCRYPTOPP_PATCH_DIR = $(TOPDIR)/board/abc/xyz/patches/libcryptopp

# Set the compiler flags for where to look for header files (.h), shared static libraries (.a), shared dynamic libraries (.so).
# Use the "--sysroot" flag instead of -I$(STAGING_DIR)/usr/include -L$(STAGING_DIR)/usr/lib

define LIBCRYPTOPP_EXTRACT_CMDS
	unzip $(DL_DIR)/libcryptopp/$(LIBCRYPTOPP_SOURCE) -d $(@D)
endef
 
define LIBCRYPTOPP_BUILD_CMDS
	$(TARGET_MAKE_ENV) $(MAKE1) static --file=GNUmakefile-cross -C $(@D) \
	$(TARGET_CONFIGURE_OPTS) \
	CXXFLAGS+=--sysroot=$(STAGING_DIR) \
	LDFLAGS+=--sysroot=$(STAGING_DIR) \
	CXXFLAGS+='-D__always_inline__=__unused__'
	# The above line is needed to suppress errors about inability to inline certain functions
endef

define LIBCRYPTOPP_INSTALL_STAGING_CMDS
	$(INSTALL) -D -m 0755 $(@D)/libcryptopp.a $(STAGING_DIR)/usr/lib/libcryptopp.a
endef

$(eval $(generic-package))
```

**Comment by noloader** [comment]
Please setup a separate GitHub project. Fork it from Wei's GitHub (https://github.com/weidai11/cryptopp). I'll add a wiki page on your build system.

What we have found is, these build systems are like religions. Everyone want's their favorite one added. Then, when things break, we have to fix it. We no longer add additional build systems.

Here are examples of [Autotools](https://www.cryptopp.com/wiki/Autotools) and [CMake](https://www.cryptopp.com/wiki/CMake).
