### ISSUE TITLE
Compiler flag to omit the PRNG

### ISSUE THREAD

**Issue by jhealyt** [weidai11/cryptopp#914]
I'm working on an embedded security device, and I have to remove all software-based pseudo-randomness generators. I have removed three so far:

(1) The Intel Rdrand engine inside OpenSSL
(2) The DBRG randomness generator built into OpenSSL
(3) The simulator engine for the TPM2 chip

There's only one software random number generator left, and it's inside the Linux kernel. I will look into removing this one at a later date.

I have recently added libcryptopp to my project, and I see that it has a PRNG. Is it possible to use a compiler switch to to omit the PRNG? If not, I think this feature should be implemented.

**Comment by noloader** [comment]
You should define `NO_OS_DEPENDENCE`.
