### ISSUE TITLE
Tiger official test vectors fail

### ISSUE THREAD

**Issue by SanderBouwhuis** [weidai11/cryptopp#915]
OS = Windows 10 x64
Compiler = Visual Studio 2017
Version = CryptoPP v8.2.0

I created my own independent implementation for the Tiger hash on Windows with Visual Studio. Unfortunately, it fails some of the test vectors. I compiled and ran the ValidateTiger() function of CryptoPP v8.2.0 with some of the official test vectors and CryptoPP fails with the exact same hashes as my implementation. In fact, CryptoPP and my own implementation agree 100% of the time!

I added this test to the ValidateTiger() function:
`HashTestTuple("A...Za...z0...9", "\x8d\xce\xa6\x80\xa1\x75\x83\xee\x50\x2b\xa3\x8a\x3c\x36\x86\x51\x89\x0f\xfb\xcc\xdc\x49\xa8\xcc")
`

CryptoPP and my implementation both return 8623ee15cec8cca7552b4dcbdf76133a34b837e10d7f22d8, but the creators of Tiger claim it should be 8dcea680a17583ee502ba38a3c368651890ffbccdc49a8cc

Can someone who has compiled CryptoPP please try the above test?

**Comment by noloader** [comment]
I think the original Tiger hash had a padding bug. I think the authors fixed it in a revision.

See [Tiger: A Fast New Cryptographic Hash Function](http://www.cs.technion.ac.il/~biham/Reports/Tiger/). And Ross Anderson's homepage [Ross Anderson](https://www.cl.cam.ac.uk/~rja14/), where the two implementations are provided.

**Comment by SanderBouwhuis** [comment]
No, that is not it. There seems to be a difference between compiling it with GCC and with Visual Studio. So, now every Tiger implementation (like CryptoPP) that compiles with Visual Studio gives a DIFFERENT hash back than the original authors claim.
I contacted Eli Biham (one of the creators) and he simply said, "I do not use that compiler".

Is there anyone here who has compiled with Visual Studio and gotten the correct hashes?
Alternatively, is there anyone here who has compiled with GCC and gotten the correct hashes?
This, so I can do a step-by-step comparison of the internal state to see where the compilers diverge. The fact that this has not worked properly since 1995 is just plain ridiculous!
