### ISSUE TITLE
Tiger official test vectors fail

### ISSUE THREAD

**Issue by SanderBouwhuis** [weidai11/cryptopp#916]
> I think the original Tiger hash had a padding bug. I think the authors fixed it in a revision.
> 
> See [Tiger: A Fast New Cryptographic Hash Function](http://www.cs.technion.ac.il/~biham/Reports/Tiger/). And [Ross Anderson's homepage](https://www.cl.cam.ac.uk/~rja14/), where the two implementations are provided.
> _Originally posted by @noloader in https://github.com/weidai11/cryptopp/issues/915#issuecomment-560031163_

No, that is not it. There seems to be a difference between compiling it with GCC and with Visual Studio. So, now every Tiger implementation (like CryptoPP) that compiles with Visual Studio gives a DIFFERENT hash back than the original authors claim.
I contacted Eli Biham (one of the creators) and he simply said, "I do not use that compiler".

Is there anyone here who has compiled with Visual Studio and gotten the correct hashes?
Alternatively, is there anyone here who has compiled with GCC and gotten the correct hashes?
This, so I can do a step-by-step comparison of the internal state to see where the compilers diverge. The fact that this has not worked properly since 1995 is just plain ridiculous!

**Comment by randombit** [comment]
The problem is you are misinterpreting the test input "A...Za...z0...9"

The Tiger hash of literal "A...Za...z0...9" is 8623EE15CEC8CCA7552B4DCBDF76133A34B837E10D7F22D8

The Tiger hash of "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789" is 8DCEA680A17583EE502BA38A3C368651890FFBCCDC49A8CC
