### ISSUE TITLE
Expose Blake2b Compression function for Ethereum Clients

### ISSUE THREAD

**Issue by ehildenb** [weidai11/cryptopp#917]
The Ethereum network recently went through a hardfork which allows users to call the Blake2b compression function `F` directly in their smart contracts (to offer better interoperability with ZCash network). See details of the EIP here, including a link to the specification of the function `F` in question: https://eips.ethereum.org/EIPS/eip-152

Currently all the clients are rolling their own implementation of function `F` because no libraries expose this one directly. We develop [KEVM](https://github.com/kframework/evm-semantics), a K implementation of the EVM, and rely on cryptopp for several other cryptographic primitives.

For now, we will roll our own implementation of `F` as well, but this is a shame because it means that all the clients are not benefiting from having a single well-tested implementation of this function, even though the function already exists (for the most part).

The function in question in this library is the following: https://github.com/weidai11/cryptopp/blob/90d957c09b6c19027ce96288c42e70fee32b3621/blake2.cpp#L717

One key difference is that the exposed `F` needed by Ethereum clients must be parametric in the number of rounds run, whereas the implementation here hardcodes 12 rounds.

Is it possible to expose (in the header) an implementation of `F` which Ethereum clients can use (must be parametric in the number of rounds)? If people are agreeable to this, we can offer to make the implementation/PR ourselves and submit it here.

**Comment by ehildenb** [comment]
Pinging @dwightguth and @gtrepta for visibility.

**Comment by noloader** [comment]
@ehildenb, @dwightguth and @gtrepta,

Yeah, we should be able to supply the function stand-alone with adjustable rounds. Give me a few days to look into the changes.

Many of the hashes provided by Crypto++ used a static transform, and derive from a class [`IteratedHashWithStaticTransform`](https://github.com/weidai11/cryptopp/blob/master/iterhash.h). I never much liked those particular base classes so I avoided them. One of the problems with them is they only operate on one block at a time. But they served the purpose you are seeking.

So I am clear, you want something like this. The declaration for `BLAKE2b_State` is in [`blake2.h](https://github.com/weidai11/cryptopp/blob/master/blake2.h#L193).

```
void BLAKE2b::Compress(BLAKE2b_State* state, const byte *input, unsigned int rounds) 
```

Is that correct?

**Comment by ehildenb** [comment]
@noloader I think this signature should be OK, we can build a `BLAKE2b_State` ourselves, but I don't think you can assume that `R % 12 == 0` is true. Different protocol interops require different numbers of rounds. I'm not exactly an expert here on the intended use cases.

Another option would be to expose just 1 round of the Compress function, which you then can re-use/inline in your implementation of the 12-round one, and we can write a simple wrapper which makes in parametric in the number of rounds. My main goal here is to make sure we're not introducing bugs by hand-rolling our own compression algorithm.

**Comment by ehildenb** [comment]
Was just informed that a single-round option is not feasible because of setup/teardown that needs to happen before/after rounds. So I guess the only thing I have to add to your description is that `R % 12 == 0` is not an assumption you can make.

**Comment by gtrepta** [comment]
In the implementations I've seen, and in the one I made for KEVM, it is assumed that `R % 10 == 0`. If you take a close look at the Sigma table for blake2b, you will see that rows 11 and 12 are equivalent to rows 1 and 2, respectively.

**Comment by gtrepta** [comment]
Just to be clear, the number of rounds can be any arbitrary integer (1, 12, 17, 1200, etc). So, when I said `R % 10 == 0` I was meaning to say that for whichever round you're on, you need to mod it by 10 to get the row index for the Sigma table.

**Comment by noloader** [comment]
I think we are going to pass. The arbitrary rounds complicates things too much.
