### ISSUE TITLE
Build failed for android NDK r20

### ISSUE THREAD

**Issue by lzy1g1225** [weidai11/cryptopp#920]
Using Cryptopp 8.2, building with setenv-android-gcc.sh on android NDK r20 failed. 
Environment
Ubuntu(WSL)
Android SDK with NDK r20.
Looks like the latest ndk changes directories, the setenv-android-gcc.sh is unable to set properly.

**Comment by noloader** [comment]
Yeah, the Android script was broken for a while. It was fixed recently.  You want to use the `setenv-android.sh` that is in Master.

Maybe do something like:

```sh
rm -f setenv-*.sh
curl -O https://raw.githubusercontent.com/weidai11/cryptopp/master/TestScripts/setenv-android.sh
```

Also see [Android (Command Line)](https://www.cryptopp.com/wiki/Android_(Command_Line)#NDK_r19_flags) on the wiki.
