### ISSUE TITLE
Blake2b implementation: Salt has no effect and produces an incorrect digest.

### ISSUE THREAD

**Issue by skypemesm** [weidai11/cryptopp#921]
Crypto++ 8.2 has a bug in its Blake2b implementation. The output digest values are the same whether a salt is used or not. 
I changed the test code in validat5.cpp:2149 to verify this. Passing in a salt doesn't have any effect on the output digest. I used the pyblake2 module to verify that the digest values should be different (of course). Let me know if you would like any more information on this.

**Comment by noloader** [comment]
Thanks @skypemesm.

Would you try this patch, please.

```
skylake:cryptopp$ git diff > blake2.diff
skylake:cryptopp$ cat blake2.diff
diff --git a/blake2.cpp b/blake2.cpp
index 4bf09a26..49ca52b3 100644
--- a/blake2.cpp
+++ b/blake2.cpp
@@ -494,9 +494,7 @@ void BLAKE2s::Restart(const BLAKE2s_ParameterBlock& block, const word32 counter[

     // We take a parameter block as a parameter to allow customized state.
     // Avoid the copy of the parameter block when we are passing our own block.
-    if (block.data() == m_block.data())
-        m_block.Reset(m_digestSize, m_keyLength);
-    else
+    if (block.data() != m_block.data())
     {
         std::memcpy(m_block.data(), block.data(), m_block.size());
         m_block.m_data[BLAKE2s_ParameterBlock::DigestOff] = (byte)m_digestSize;
@@ -527,9 +525,7 @@ void BLAKE2b::Restart(const BLAKE2b_ParameterBlock& block, const word64 counter[

     // We take a parameter block as a parameter to allow customized state.
     // Avoid the copy of the parameter block when we are passing our own block.
-    if (block.data() == m_block.data())
-        m_block.Reset(m_digestSize, m_keyLength);
-    else
+    if (block.data() != m_block.data())
     {
         std::memcpy(m_block.data(), block.data(), m_block.size());
         m_block.m_data[BLAKE2b_ParameterBlock::DigestOff] = (byte)m_digestSize;
```

I still need to track down some official test vectors.

**Comment by noloader** [comment]
@skypemesm,

BLAKE2 should be fixed now. Thanks again for the report.

**Comment by noloader** [comment]
@skypemesm,

BLAKE2 should be fixed now.

The modified BLAKE2 test programs were checked in on my GitHub with modified reference implementations at [Commit 8ae857fc3d83](https://github.com/noloader/cryptopp-test/commit/8ae857fc3d83653266c21fcf670c313d06603b82).

Thanks again for the report.
