### ISSUE TITLE
MSVC version documentation inconsistencies

### ISSUE THREAD

**Issue by rm046e** [weidai11/cryptopp#922]
The readme mentions compatibility for Visual Studio 2003 - 2017.
Yet the readme sports instructions for compiling MSVC 2003 - 2015.
Moreover, the site (https://www.cryptopp.com/) mentions compatibility up to 2019.

My immediate question is: Are the compilation instructions valid for 2017?

**Comment by noloader** [comment]
Thanks.

**Comment by noloader** [comment]
Thanks. Cleared at [Commit f619ad4b69eb](https://github.com/weidai11/cryptopp/commit/f619ad4b69eb).
