### ISSUE TITLE
BLAKE2b Collision

### ISSUE THREAD

**Issue by redmany** [weidai11/cryptopp#923]
I may have found some collisions in BLAKE2b-32 and they are listed below.
**Data:0x13A50A7FCDCF49DFE5
Hash:0x12345678
Data:0x4B10E44FD2
Hash:0x1234567B
Data:0xAAD63D4CF4
Hash:0x12345678
Data:0xF47560ED9C
Hash:0x12345678**

**Comment by noloader** [comment]
Forgive my ignorance... What is the Crypto++ bug here?
