### ISSUE TITLE
Need a Code Coverage tool added to the Release Process

### ISSUE THREAD

**Issue by noloader** [weidai11/cryptopp#93]
We have a pretty good release process located at [Release](https://www.cryptopp.com/wiki/Release_process). However, a postmortem analysis of [Issue 92](https://github.com/weidai11/cryptopp/issues/92) revealed we don't know what code *lacks* a test case.

**Comment by randombit** [comment]
On Linux is pretty easy to produce a code coverage result with gcov and lcov. http://ltp.sourceforge.net/coverage/lcov.php

There is also the (free for open source) site codecov.io which can collect and display lcov results produced by a CI system like Travis.

**Comment by noloader** [comment]
> On Linux is pretty easy to produce a code coverage result with gcov and lcov. http://ltp.sourceforge.net/coverage/lcov.php

Thanks Jack. I think it would be wise to use a tool like this.

> There is also the (free for open source) site codecov.io which can collect and display lcov results produced by a CI system like Travis.

This is another pain point. We need to start automating some of these processes.

**Comment by GamePad64** [comment]
Well, I like Travis too. And codecov.io looks convenient for me. I made a branch with Travis and Codecov.io enabled and can file a PR, if you like.

**Comment by noloader** [comment]
> Well, I like Travis too. 

I think we need Travis CI badly. I think the things holding us up are: (1) my ignorance and (2) lack of cycles to integrate into the service. (1) is mine alone, but (2) applies to everyone.

**Comment by GamePad64** [comment]
Well, okay :)

**Comment by noloader** [comment]
> I think we need Travis CI badly....

Now see [Issue 97: Continuous integration and testing](https://github.com/weidai11/cryptopp/issues/97).

**Comment by noloader** [comment]
We added lcov on Linux. Microsoft appears to have something in Visual Studio, but it also appears folks need to purchase an appropriate VS edition.
