### ISSUE TITLE
GCM wiki documentation error/inconsistency with regard to: iv size in bytes.

### ISSUE THREAD

**Issue by grantrostig** [weidai11/cryptopp#930]
Wiki documentation error in 8.2.0. [GCM Mode](https://www.cryptopp.com/wiki/GCM_Mode) states:

```
byte iv[ AES::BLOCKSIZE * 16 ];
```

Should be:
```
byte iv[ AES::BLOCKSIZE ];
```

This apparent typo confused me since the referenced zip file is also different in several ways and uses the number 12. Note `AES::BLOCKSIZE` is 16, which could work.  However, `16*16` bytes is more than the desired 96, or 128 bits.

**Comment by noloader** [comment]
```
byte iv[ AES::BLOCKSIZE * 16 ];
```

That is actually OK. For GCM mode the IV can be any size upto 2<sup>64</sup>-1 (in multiples of 8). 

NIST SP800-38D recommends a 96-bit IV for interoperability.  And Microsoft's implementation limits IV's to 96 or 128 bits, if I recall correctly.

**Comment by grantrostig** [comment]
Yes, it is within spec., but is it a good example?  I also note that the wiki text example is different in multiple ways from the downloadable ZIP example.  I'm not in charge but I am struggling with the various examples and inconsistencies in other examples too.  I might be able to help with significant guidance, but I'm new to this.  Even the api documentation is not providing the insights I need.  The RFCs, FIPS, and NIST docs are of some help.

**Comment by noloader** [comment]
We changed the declaration to `AES::BLOCKSIZE`.

**Comment by grantrostig** [comment]
Thank you for you efforts with regard to documentation.  I'm not qualified to say what is correct yet.
