### ISSUE TITLE
Macro name conflict with 3rd party library

### ISSUE THREAD

**Issue by scherepanov** [weidai11/cryptopp#934]
I am compiling CryptoPP with 3rd party library. And, it happens to have macro Divide, that is defined in CryptoPP as well. Fortunately, one had 4 parameters, other 5, and failing compile. Otherwise I would die to find what is wrong - code would compile but use wrong macro from another library.

I have non-trivial imports of CryptoPP and 3rd party libraries, in h and cpp files.
Though I managed to make it working, it is not trivial. Undefining macro from one library makes it not working for another, macros override each other etc. It is a BIG MESS, requiring unnecessary imports in one places and reordering of imports in another. I think it is not possible to make working in more complex cases.

So...
CryptoPP do use namespace CryptoPP to insulate from name conflicts.
There are no namespaces for macros. Macros from all libraries are sharing same namespace.

Direct answer to macros name conflict - prepend CryptoPP macro names with prefix, like "CryptoPP_".
That will work similar to namespace for classes/functions etc.

I can submit a PR, if you want. Changes are trivial.

**Comment by noloader** [comment]
On Fri, Feb 28, 2020 at 11:53 AM scherepanov <notifications@github.com>
wrote:

> I am compiling CryptoPP with 3rd party library. And, it happens to have
> macro Divide, that is defined in CryptoPP as well. Fortunately, one had 4
> parameters, other 5, and failing compile. Otherwise I would die to find
> what is wrong - code would compile but use wrong macro from another library.
>
> I have non-trivial imports of CryptoPP and 3rd party libraries, in h and
> cpp files.
> Though I managed to make it working, it is not trivial. Undefining macro
> from one library makes it not working for another, macros override each
> other etc. It is a BIG MESS, requiring unnecessary imports in one places
> and reordering of imports in another. I think it is not possible to make
> working in more complex cases.
>
> So...
> CryptoPP do use namespace CryptoPP to insulate from name conflicts.
> There are no namespaces for macros. Macros from all libraries are sharing
> same namespace.
>
> Direct answer to macros name conflict - prepend CryptoPP macro names with
> prefix, like "CryptoPP_".
> That will work similar to namespace for classes/functions etc.
>

I can't find a macro named divide, Divide, DIVIDE, etc in Crypto++.

Where are you experiencing it?

$ grep -i Divide *.h *.cpp | grep define
$

Jeff

**Comment by noloader** [comment]
On Fri, Feb 28, 2020 at 11:53 AM scherepanov <notifications@github.com>
wrote:

> I am compiling CryptoPP with 3rd party library. And, it happens to have
> macro Divide, that is defined in CryptoPP as well. Fortunately, one had 4
> parameters, other 5, and failing compile. Otherwise I would die to find
> what is wrong - code would compile but use wrong macro from another library.
>
> I have non-trivial imports of CryptoPP and 3rd party libraries, in h and
> cpp files.
> Though I managed to make it working, it is not trivial. Undefining macro
> from one library makes it not working for another, macros override each
> other etc. It is a BIG MESS, requiring unnecessary imports in one places
> and reordering of imports in another. I think it is not possible to make
> working in more complex cases.
>
> So...
> CryptoPP do use namespace CryptoPP to insulate from name conflicts.
> There are no namespaces for macros. Macros from all libraries are sharing
> same namespace.
>
> Direct answer to macros name conflict - prepend CryptoPP macro names with
> prefix, like "CryptoPP_".
> That will work similar to namespace for classes/functions etc.

I can't find a macro named divide, Divide, DIVIDE, etc in Crypto++.
```
$ grep -i Divide *.h *.cpp | grep define
$
```

Where are you experiencing it?

**Comment by scherepanov** [comment]
Re-checking code again
It appears that third-party library have Divide macros, and it is interfering with CryptoPP Divide function declaration.
It is a third-party library fault. CryptoPP is perfectly fine.
I should do better investigation before opening issue.
