### ISSUE TITLE
Is there any document on how to use  Crypto++ library ?

### ISSUE THREAD

**Issue by tianchao-haohan** [weidai11/cryptopp#935]
### Crypto++ Issue Report
* The operating system and version (Centos7 x86_64, Windows 10 Professional x64, etc)
* The version of the Crypto++ library (The latest Crypto++ 8.20)
* How you built the library (Makefile, Cmake, Visual Studio 2017)

I'd like to use Crypto++ in my project. And there will be two output related to Crypto++ in my project, one is static library (lib) and another is binary (exe). Both of the lib and the exe will reference Crypto++ functions. 
So, is there any document or link on how to create a new project (visual studio 2017 and Linux, need to cross platform) to reference the  Crypto++ functions?
I tried it myself and meet the error below:
![image](https://user-images.githubusercontent.com/8639363/75606421-81567300-5b27-11ea-8b5e-9856f76b5386.png)

It seems that the Crypto++ project is different with other Visual project. Is there any useful suggestions or link for me?

**Comment by adisib** [comment]
You need to specify the `CryptoPP` namespace for Crypto++ identifiers.

**Comment by noloader** [comment]
Please ask questions on the mailing list.

Also see the Crypto++ [wiki](https://www.cryptopp.com/wiki/Main_Page).
