### ISSUE TITLE
CMake-based build toolchain

### ISSUE THREAD

**Issue by yuchdev** [weidai11/cryptopp#939]
As per 5.6.4 version Crypto++ supported CMake, however, in the current version CMakeLists.txt is not available.
CMake is an industry standard, and most of build systems use it. The most excluding it affects solutions which attempt to upgrade to a newer version of Crypto++, causing deadlines delay and forcing to use older, potentially vulnerable versions of the library.

**Comment by noloader** [comment]
Please see [CMake](https://www.cryptopp.com/wiki/CMake) on the wiki.

Supplying CMake files was a failed experiment.

**Comment by 01e9** [comment]
Can be used in CMake as External Project

```cmake
include(ExternalProject)

include(ProcessorCount)
ProcessorCount(CPU_COUNT)
MATH(EXPR CPU_COUNT "${CPU_COUNT}-2")

set(EXTERNAL_PROJECTS_DIR "${CMAKE_BINARY_DIR}/external-projects")
set(EXTERNAL_PROJECTS_INSTALL_DIR "${EXTERNAL_PROJECTS_DIR}/installed")

add_custom_target(external_all)
set_target_properties(external_all PROPERTIES EXCLUDE_FROM_ALL TRUE)

# THIS
ExternalProject_Add(external_cryptopp
	PREFIX ${EXTERNAL_PROJECTS_DIR}
	CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${EXTERNAL_PROJECTS_INSTALL_DIR}
	URL "https://github.com/weidai11/cryptopp/archive/refs/tags/CRYPTOPP_8_9_0.tar.gz"

	CONFIGURE_COMMAND ""
	BUILD_COMMAND make -j ${CPU_COUNT}
	BUILD_IN_SOURCE true
	INSTALL_COMMAND make PREFIX=${EXTERNAL_PROJECTS_INSTALL_DIR} install
)
add_dependencies(external_all external_cryptopp)
```

Usage:
1) Build `external_all` (once)
2) Reload CMake
3) Build your app
