### ISSUE TITLE
CFB_ModePolicy Android

### ISSUE THREAD

**Issue by eschriek** [weidai11/cryptopp#94]
Hi there,

I have cross-compiled cryptopp for Android using the provided makefile. However, the linker complains about a specific class, see [linker_errors.txt](https://github.com/weidai11/cryptopp/files/73329/linker_errors.txt). Other pieces of code, such as SHA256 and RandomPool link correctly. 

The code im trying to compile is:

    CryptoPP::AES::Encryption                     aes(m_bufSeed,m_bufSeed.size());
    CryptoPP::CFB_Mode_ExternalCipher::Decryption decryptor(aes,m_bufIV);
    decryptor.ProcessString(pData,dwSize);

I am using the GCC 4.9 toolchain targeting platform version 19, armeabi-v7a. My cflags are
    "-std=c++11", "-frtti", "-mfloat-abi=softfp",
                         "-fexceptions", "-g2", "-gdwarf-2" , "-funwind-tables" , "-Wl,--fix-cortex-a8",
                         "-DANDROID", "-fpermissive", "-Wall"

I assume I am either missing something critical something here, or it is a bug on Android?

Thanks

**Comment by noloader** [comment]
Thanks Edwin. This is kind of tricky for us because shared object exports.

I think you have three options:

* wrapper shared object that links to `libcryptopp.a`. Your shared object will export what it needs.
* use `CFB_mode< AES >::Decryption`rather than `CFB_Mode_ExternalCipher::Decryption`. This may suffer the same issue (I don't recall because I use a different mode and use the wrapper DLL approach).
* modify the source code and export what you need with `CRYPTOPP_DLL_TEMPLATE_CLASS`. I beleve there are examples of it in [modes.h, around line 315](https://www.cryptopp.com/docs/ref/modes_8h_source.html#l00314).

**Comment by eschriek** [comment]
Thanks for your answer,

Unfortunatly, I'm required to use CFB, so using a different mode is not an option. The third option produces the same errors.

I rather not link the static library as well, because of its size. I am linking several libraries to my application, therefore I would like to keep the .apk size as small as possible.

The fourth option appears the most viable for me, I'll give that a spin.

Thanks

**Comment by dirvine** [comment]
>I rather not link the static library as well, because of its size. I am linking several libraries to my application, therefore I would like to keep the .apk size as small as possible.

I don't think you should worry about that. Your application will only link in the parts you use. The size of the library should not make a difference here.

**Comment by noloader** [comment]
@eschriek  - how did you make out?

**Comment by eschriek** [comment]
@noloader I just tried the 4th approach, but that does not compile at all due to CFB_Encryption and CFB_Decryption being undefined.

To be honest, I am kind of lost in understanding the source of modes.h as an effect of all the templates.

**Comment by eschriek** [comment]
@noloader Just created a test application from a clean slate, in which it links and functions correctly. So it seems there is something odd going on in my original project.

Anyways, thanks for the help.

**Comment by noloader** [comment]
@eschriek - very good. You were next on my TODO list. Sorry I could not get to it sooner.
