### ISSUE TITLE
Use of uncaught_exception

### ISSUE THREAD

**Issue by KayEss** [weidai11/cryptopp#946]
The use of `std::uncaught_exception` has been deprecated in favour of `std::uncaught_exceptions` (note extra 's'). https://en.cppreference.com/w/cpp/error/uncaught_exception

I can do a quick PR for this. I guess it would need to switch based on the C++ language version (17 and later using the new API). I've not looked at the code yet, just seen the deprecation warnings, but I assume this is going to be a rather straight forward fix.

**Comment by noloader** [comment]
Thanks @KayEss.

It looks like we have some basic support for `std::uncaught_exceptions`. I'm guessing its a problem with mis-detecting the platform:

```
$ grep -IR uncaught_exceptions *.h *.cpp
algparam.h:             if (std::uncaught_exceptions() == 0)
config_cxx.h:// this file. At the moment it should only affect std::uncaught_exceptions.
config_cxx.h:// C++17 uncaught_exceptions: MS at VS2015 (19.00); GCC at 6.0; Clang at 3.5; Intel 18.0.
config_cxx.h:#  if __cpp_lib_uncaught_exceptions
config_cxx.h:      (CRYPTOPP_GCC_VERSION >= 60000) || (__cpp_lib_uncaught_exceptions)
config_cxx.h:#endif // uncaught_exceptions compilers
```

**Comment by KayEss** [comment]
Ah, interesting. I would have just used the language versions rather than look for specific compilers. AFAIK at least clang will do different things for different language versions you tell it to compile against not just which version of clang you have.

[https://en.cppreference.com/w/User:D41D8CD98F/feature_testing_macros](According to this) the feature test macro I see there is correct. I'll take a look at the actual code when it's not so late and see if I can work out what's going wrong.

Maybe it won't be so trivial :-)

**Comment by KayEss** [comment]
Looks like a red herring. Our CMake build script wasn't setting `CRYPTOPP_CXX17_EXCEPTIONS` which was causing it to use the old code path. Fixed now and no more warnings.

Sorry about the noise.
