### ISSUE TITLE
Undersized SipHash key leads to buffer out-of-bounds read

### ISSUE THREAD

**Issue by guidovranken** [weidai11/cryptopp#947]
```cpp
#include <seckey.h>
#include <siphash.h>

int main(void)
{
    const uint8_t key[3] = { 0 };
    ::CryptoPP::SipHash<2, 4, false> siphash(key, sizeof(key));
    return 0;
}
```

I think it would be more appropriate to throw an exception in this case?

**Comment by noloader** [comment]
Thanks @guidovranken.

Can you give [Commit d6a5b7664bde](https://github.com/weidai11/cryptopp/commit/d6a5b7664bde) a try?

**Comment by guidovranken** [comment]
Thank you, confirmed fixed.
