### ISSUE TITLE
Problem building cryptopp library for IOS

### ISSUE THREAD

**Issue by danielseow-simplify** [weidai11/cryptopp#948]
- Cryptopp version 8.2.0 release version downloaded from github release
- MAC OS: Catalina Version 10.15.4

Following the exact steps from documentation but end up having errors
![image](https://user-images.githubusercontent.com/57748006/81280753-8554c300-908b-11ea-8384-aaa56cb9911e.png)
![image](https://user-images.githubusercontent.com/57748006/81280876-b3d29e00-908b-11ea-814d-0e0c7ff6715f.png)

and finally 
`fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [integer.o] Error 1`

**Comment by danielseow-simplify** [comment]
Sorry.. i just figured out it should be x86_64 architecture for simulator and using bash command i be able to build the library now

**Comment by noloader** [comment]
You need to `source` the `setenv-ios.sh` scripts.
