### ISSUE TITLE
Can't compile on Android due to wrong evaluation of CRC support

### ISSUE THREAD

**Issue by FreddieOliveira** [weidai11/cryptopp#950]
Please, see https://github.com/cryfs/cryfs/issues/345

**Comment by noloader** [comment]
Thanks @FreddieOliveira 

Yeah, our various `config_xxx.h` sometimes gets things wrong because it relies on preprocessor macros and compiler version numbers. To date you would have to hand edit the config file to fix it.

I think what we really need is a way to write the config information dynamically when the current method using preprocessor macros fail.

I checked in a script to do that: [36e0721f141b](https://github.com/weidai11/cryptopp/commit/36e0721f141b). You should be able to use it for past releases, too (as long as they have `config_xxx.h`). Could you try:

```
cd cryptopp
wget -O configure.sh https://raw.githubusercontent.com/weidai11/cryptopp/master/TestScripts/configure.sh
./configure.sh
make -j 4 && make check
```

**Comment by FreddieOliveira** [comment]
Hey, thanks for looking into this. The idea of generating the macros at build time is great, but the `TestPrograms/test_arm_crc.cxx` has a major problem, it checks for the very same macro that are still to be generated before including its header:

```
#include <arm_neon.h>
#include <stdint.h>

// test_acle.h determines if this is available. Then,
// -DCRYPTOPP_ARM_ACLE_HEADER=0 is added to CXXFLAGS
// if the ACLE header is not available.
#if (CRYPTOPP_ARM_ACLE_HEADER)
#  include <arm_acle.h>
#endif

int main(int argc, char* argv[])
{
	uint32_t w=0xffffffff;

	w = __crc32w(w,w);
	w = __crc32h(w,w);
	w = __crc32b(w,w);
	w = __crc32cw(w,w);
	w = __crc32ch(w,w);
	w = __crc32cb(w,w);

	return 0;
}
```

Since `CRYPTOPP_ARM_ACLE_HEADER` still doesn't exist, the `arm_acle.h` header isn't included and the code fails for using the `__crc32` functions without it.

Actually, all test programs behave like that, but that's not a problem for them, because the functions they use are declared in the correctly included `arm_neon.h`.

My suggestion for this problem is to include only the very necessary headers in the test programs without any check. That means excluding the

```
#if (CRYPTOPP_ARM_ACLE_HEADER)
#  include <arm_acle.h>
#endif
```

portion from the tests that don't need it and including the header without the `#if (CRYPTOPP_ARM_ACLE_HEADER)` check in the tests that need it

**Comment by noloader** [comment]
Thanks @FreddieOliveira,

Let's give this a try: [Commit f8efb43a88f8](https://github.com/weidai11/cryptopp/commit/f8efb43a88f8).

That will probably break some early Linaro compilers. The early GCC and GCC-based compilers gave us a lot of problems. They were missing some defines, and then added defines for features they did not implement.

The early compilers are why we hacked-in the test programs. We simply could not determine features based on macros and compiler versions.

**Comment by FreddieOliveira** [comment]
Cool, that worked. Here's a screenshot:

![Screenshot_20200728-234542_Termux](https://user-images.githubusercontent.com/9597536/88750762-b94cfb00-d145-11ea-950b-52cd6bdb2245.png)

**It needs just a final adjustment:** actually, the only test program that needs the `arm_acle.h` is the `test_arm_crc.cxx`, so I highly recommend including it only there.  Otherwise, a processor that doesn't support the arm_acle will fail at every test, even the ones that don't use it. Also, the `test_arm_crc.cxx` doesn't need the `arm_neon.h`, so I recommend removing its inclusion from there for the same reason.

I have two questions:

1. Will you eventually incorporate the execution of this script into the Makefile, or it'll always be supposed to be ran manually? I'm asking this because the projects that use cryptopp, like [cryfs](https://github.com/cryfs/cryfs), will have to update their building steps to match these changes.

1. Why is the Android blacklisted in the original `config_asm.h` file?
```
// Disable for Android
#if defined(__ANDROID__) || defined(ANDROID)
# undef CRYPTOPP_ARM_CRC32_AVAILABLE
# undef CRYPTOPP_ARM_PMULL_AVAILABLE
# undef CRYPTOPP_ARM_AES_AVAILABLE
# undef CRYPTOPP_ARM_SHA1_AVAILABLE
# undef CRYPTOPP_ARM_SHA2_AVAILABLE
# undef CRYPTOPP_ARM_SHA3_AVAILABLE
# undef CRYPTOPP_ARM_SHA512_AVAILABLE
# undef CRYPTOPP_ARM_SM3_AVAILABLE
# undef CRYPTOPP_ARM_SM4_AVAILABLE
#endif
```

```
#  if !defined(__ANDROID__) && !defined(ANDROID) && !defined(__APPLE__)
#   define CRYPTOPP_ARM_ACLE_HEADER 1
#  endif
```

**Comment by noloader** [comment]
> the only test program that needs the arm_acle.h is the test_arm_crc.cxx ...

The [ARM ARM C Language Extensions 2.0 Architecture specification](https://developer.arm.com/documentation/ihi0053/c/) doc says CRC and Crypto need `arm_acle.h`. Moreover, to get the declarations for types like `uint64x2_t`, you need to include `arm_neon.h` even on ARMv8.

> Will you eventually incorporate the execution of this script into the Makefile, or it'll always be supposed to be ran manually?

I planned on letting folks run it manually if the defaults in `config_xxx.h` were off. With that said, it should always be safe to run `configure.sh`, so you can add it as a step in your build process if you like.

> Why is the Android blacklisted in the original config_asm.h file?

Android hardware compatibility. Android says the arm64-v8a ABI targets AArch64. AArch64 includes ASIMD (i.e., NEON) and nothing more. CRC and Crypto are optional extensions offered in armv8.1. Also see [Android ABI Guide](https://developer.android.com/ndk/guides/abis).

**Comment by noloader** [comment]
@FreddieOliveira,

And two other things about these headers...

First, the ARM ACLE document says to define `ARM_ACLE` macro to a version indicating compliance level. Early GCC would define it, but then fail to provide the damn `arm_acle.h` header.

Second, we also support Microsoft ARM and ARM64, so there's more hidden behind those macro gyrations than just Linux.

According to the ARM ACLE (page 16), this is all we should need to do:

```
#ifdef __ARM_ACLE
#include <arm_acle.h>
#endif /* __ARM_ACLE */

#ifdef __ARM_NEON
#include <arm_neon.h>
#endif /* __ARM_NEON */
```

But I can promise you that will cause a lot of failed compiles.

**Comment by FreddieOliveira** [comment]
Oh yeah, I totally agree that blindly trusting the preprocessor macros is not ideal, that's why the test programs are a great move.

> The ARM ARM C Language Extensions 2.0 Architecture specification doc says CRC and Crypto need arm_acle.h. 

I'm not sure if the Crypto functions need the `arm_acle.h` header. I couldn't find anything saying likewise in the ARM specification. Also, my toolchain declare the Crypto functions only in the `arm_neon.h`.

According to the specification (section 4.3), these functions are part of the NEON Intrinsics, which needs only the `arm_neon.h`. The `arm_acle.h` is used for the non-NEON Intrinsics.

My fear here is the scenario where the processor supports the Crypto functions, but doesn't support the `arm_acle.h`. This would lead to failure in the Crypto tests, like the SHA ones, because they unnecessarily include the not supported acle header.

> to get the declarations for types like uint64x2_t, you need to include arm_neon.h even on ARMv8

That's true, indeed. But these types are not necessary to use the CRC functions, which means the `arm_neon.h` is not needed to test the `__crc32` functions, only the `arm_acle.h` (section 9.7)

My fear here is similar, imagine a scenario where the processor supports the non-NEON intrinsics, thus supports the CRC. But, it doesn't support the `arm_neon.h`. Then, it would fail the crc test because it includes the unnecessary and not supported neon header.

Please, correct me if I'm wrong.

**Comment by noloader** [comment]
@FreddieOliveira,

> My fear here is the scenario where the processor supports the Crypto functions, but doesn't support the arm_acle.h ...

We actually have two different tests. The first tests for each header `arm_neon.h` and `arm_acle.h` header. The second tests for the intrinsics using the proper arch flag, like `-march=armv8-a+crc` or `-march=armv8-a+crypto`.

If an implementation wanders off the reservation and includes ACLE intrinsincs in a different header, like `arm_crc.h` or `arm_crypto.h`, then they are on their own. They need to follow the ACLE.

I think we will be OK. Or testing so far has not revealed any new problems.

**Comment by noloader** [comment]
@FreddieOliveira,

Forgive my ignorance... How is it Android has CRC, AES, PMULL and SHA available to them? The Android docs don't state the capabilities are available in the hardware list.

**Comment by noloader** [comment]
@FreddieOliveira,

It looks like Clang is broke again. It is advertising the wrong support in the compiler. According to the [Android ABI Guide](https://developer.android.com/ndk/guides/abis), Android only supports up to SSE4.2+POPCNT.

Clang should not be advertising support of AES, PCLMUL, RDRAND, RDSEED, SHA, AVX, AVX2 and Padlock. Padlock is an [old VIA technology](https://www.cryptopp.com/wiki/VIA_Padlock).

```
android:cryptopp$ source ./setenv-android.sh 28 x86_64
ANDROID_NDK_ROOT is /opt/android-ndk
ANDROID_TOOLCHAIN: /opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin
ANDROID_API: 28
ANDROID_CPU: x86_64
...

$ ./configure.sh 
Configuring for x86_64
Compiler: x86_64-linux-android28-clang++
Linker: x86_64-linux-android-ld

android:cryptopp$ cat config_asm.h
#ifndef CRYPTOPP_CONFIG_ASM_H
#define CRYPTOPP_CONFIG_ASM_H

// config_asm.h rewritten by configure.sh script
// Wed Jul 29 16:17:11 EDT 2020

#define CRYPTOPP_SSE2_INTRIN_AVAILABLE 1
#define CRYPTOPP_SSE3_AVAILABLE 1
#define CRYPTOPP_SSSE3_ASM_AVAILABLE 1
#define CRYPTOPP_SSSE3_AVAILABLE 1
#define CRYPTOPP_SSE41_AVAILABLE 1
#define CRYPTOPP_SSE42_AVAILABLE 1
#define CRYPTOPP_CLMUL_AVAILABLE 1
#define CRYPTOPP_AESNI_AVAILABLE 1
#define CRYPTOPP_RDRAND_AVAILABLE 1
#define CRYPTOPP_RDSEED_AVAILABLE 1
#define CRYPTOPP_SHANI_AVAILABLE 1
#define CRYPTOPP_AVX_AVAILABLE 1
#define CRYPTOPP_AVX2_AVAILABLE 1
#define CRYPTOPP_PADLOCK_RNG_AVAILABLE 1
#define CRYPTOPP_PADLOCK_AES_AVAILABLE 1
#define CRYPTOPP_PADLOCK_SHA_AVAILABLE 1
#define CRYPTOPP_DISABLE_MIXED_ASM 1

#endif
```

**Comment by FreddieOliveira** [comment]
Hmm, looks like your toolchain is different from mine: yours targets x86_64, while mine targets aarch64. I'm attaching my prerpocessor macros got with `clang -march=armv8-a+crc -x c /dev/null -dM -E`

[macros.txt](https://github.com/weidai11/cryptopp/files/4997723/macros.txt)

According to the Android ABI guide, it guarantees support for the NEON intrinsics. This includes the Cryptos (AES, SHA, pmull, etc). But it doesn't mention the non-NEON intrinsics, which includes the CRC support. 

So, I guess we can assume that Android has support for the Cryptos, but CRC support is optional.

**Comment by noloader** [comment]
> Hmm, looks like your toolchain is different from mine: yours targets x86_64, while mine targets aarch64. I'm attaching my prerpocessor macros got with clang -march=armv8-a+crc -x c /dev/null -dM -E

Yeah, I've been testing the different arches.

For Aarch64, the compiler should reject CRC and Crypto. Android docs state the base machine only, which is ASIMD/NEON.

**Comment by FreddieOliveira** [comment]
> Yeah, I've been testing the different arches.

Unfortunately I only have an arm64 device. I can't test cryptopp in other archs, but I can asure you it works flawless with the CRC and Crypto funcs in Android 10.

The [ABI guide](https://developer.android.com/ndk/guides/abis#arm64-v8a) says.

> You can use Neon intrinsics in C and C++ code

I think that includes the Crypto, since it is part of the NEON intrinsics

**Comment by noloader** [comment]
Thanks @FreddieOliveira,

> I think that includes the Crypto, since it is part of the NEON intrinsics

Yeah, this is where I am confused. The [ARM ACLE](https://developer.arm.com/documentation/ihi0053/c/) (page 41) says:

> [Chapter 8, Data-processing intrinsics]
> 
> The intrinsics in this section are provided for algorithm optimization.
> 
> The <arm_acle.h> header should be included before using these intrinsics.
>
> ... Section 8.8, CRC32 intrinsics ...

So they definitely are part of the ACLE. They are not part of NEON; and they are not part of Aarch64's base machine via ASIMD.

I'm not going to yank support for them. I just don't understand why folks like GCC and Clang make the shit up as they go. It causes a lot of confusion and problems like this.

**Comment by triplef** [comment]
I’d like to add here that building for macOS Apple Silicon (arm64) using the Xcode 12 beta also fails due to incorrect detection of `CRYPTOPP_ARM_CRC32_AVAILABLE`:

```
c++ -DNDEBUG -g2 -O3 -fPIC -arch arm64 -std=c++11 -stdlib=libc++ -mmacosx-version-min=10.11 -pthread -pipe -ffunction-sections -fdata-sections -march=armv8-a+crc -c crc_simd.cpp
crc_simd.cpp:123:13: error: use of undeclared identifier '__crc32b'
        c = __crc32b(c, *s);
            ^
crc_simd.cpp:126:13: error: use of undeclared identifier '__crc32w'
        c = __crc32w(c, *(const word32 *)(void*)s);
            ^
crc_simd.cpp:129:13: error: use of undeclared identifier '__crc32b'
        c = __crc32b(c, *s);
            ^
crc_simd.cpp:135:13: error: use of undeclared identifier '__crc32cb'
        c = __crc32cb(c, *s);
            ^
crc_simd.cpp:138:13: error: use of undeclared identifier '__crc32cw'
        c = __crc32cw(c, *(const word32 *)(void*)s);
            ^
crc_simd.cpp:141:13: error: use of undeclared identifier '__crc32cb'
        c = __crc32cb(c, *s);
            ^
```

I worked around this by adding `-DCRYPTOPP_ARM_CRC32_AVAILABLE=0` to CXXFLAGS.

**Comment by FreddieOliveira** [comment]
Did you try running the `configure.sh` script before `make`? If not, try this steps:

```
cp TestScripts/configure.sh .
./configure.sh
make
```

**Comment by noloader** [comment]
@triplef ,

Apple is a little trickier because Apple compilers are not accurate for `-dumpmachine`.

You need to do like @FreddieOliveira said, but you also need to set your `CXX` and relevant `CXXFLAGS`:

```
CXX=c++ CXXFLAGS="-arch arm64 -stdlib=libc++ -mmacosx-version-min=10.11" ./configure.sh
```

Also, are you sure about ` -mmacosx-version-min` for iOS? I think that should use `-miphoneos-version-min=6`. There's also `-miphonesimulator-version`, `-mappletvos-version-min`, `-mappletvsimulator-version-min`, `-mwatchos-version-min` and `-mwatchsimulator-version-min`.

**Comment by noloader** [comment]
@triplef, @FreddieOliveira,

I added a wiki page on [`configure.sh`](https://www.cryptopp.com/wiki/Configure.sh).

We are not going to run `configure.sh` in the makefile. But you are free to do so since it should always arrive at the right configuration, and not make things worse.

**Comment by noloader** [comment]
@triplef, @FreddieOliveira,

We improved the comments around the `#undefs` to explain why it was happening. We added the `configure.sh` tool to fix generic misdetections.

Is there anything more we need to do here?  Is it OK to close?

**Comment by FreddieOliveira** [comment]
Thank you @noloader 👍, for me it's ok. Since we haven't heard from @triplef I'm closing now. If the issue arises again we can further comment here or open a new issue.

**Comment by triplef** [comment]
Thanks @noloader! I didn’t know about `configure.sh`, but I appreciate the input and added wiki page. I’ll give this a try soon and let you know in case there are still any issues.

**Comment by smessmer** [comment]
Author of [cryfs](https://github.com/cryfs/cryfs) here. 
We're using [cryptopp-cmake](https://github.com/noloader/cryptopp-cmake). Will that run `configure.sh` for us?

**Comment by FreddieOliveira** [comment]
@noloader

**Comment by buffstop** [comment]
> @triplef, @FreddieOliveira,
> 
> I added a wiki page on [`configure.sh`](https://www.cryptopp.com/wiki/Configure.sh).
> 
> We are not going to run `configure.sh` in the makefile. But you are free to do so since the script should always arrive at the right configuration, and not make things worse.

I could not find `TestScripts/configure.s` in CRYPTOPP_8_2_0
