### ISSUE TITLE
Header and source files dependencies

### ISSUE THREAD

**Issue by ujos** [weidai11/cryptopp#951]
I use CryptoPP to calculate HMAC-SHA256 signature. My code is similar to this one:

```cpp
#include <string>
#include <string_view>

#include <cryptopp/filters.h>
using CryptoPP::StringSink;
using CryptoPP::StringSource;
using CryptoPP::HashFilter;

#include <cryptopp/hmac.h>
using CryptoPP::HMAC;

#include <cryptopp/sha.h>
using CryptoPP::SHA256;

std::string CalcHmacSHA256(std::string_view decodedSecretKey, std::string_view request)
{
    // Calculate HMAC
    HMAC<SHA256> hmac(reinterpret_cast<CryptoPP::byte const*>(decodedSecretKey.data()), decodedSecretKey.size());

    std::string calculated_hmac;
    auto sink = std::make_unique<StringSink>(calculated_hmac);

    auto filter = std::make_unique<HashFilter>(hmac, sink.get());
    sink.release();

    StringSource(reinterpret_cast<CryptoPP::byte const*>(request.data()), request.size(), true, filter.get()); // StringSource
    filter.release();

    return calculated_hmac;
}
```
In addition to code above I use Base 64 encoder/decoder from `cryptopp/base64.h` header file.

I'd like to add your library to my solution as a subproject (static library) and keep only header and source files that are related to HMAC calculation. I keep original files. The only thing I change is Visual Studio project file.

After few hours of investigation I've got following list of files that I'm not sure they have to be in the project. While from my point of view I do not need those files, I'm not able to compile project without adding those files because of "Unresolved symbol" linker errors.

Could you take a look to verify, is there some unnecessary dependency introduced? I'm not good in cryptography, but why do I need keccak or des?

```
asn.cpp
des.cpp
dessp.cpp
ec2n.cpp
ecp.cpp
eprecomp.cpp
fips140.cpp
fipsalgt.cpp
hex.cpp
keccak.cpp
keccak_core.cpp
keccak_simd.cpp
modes.cpp
neon_simd.cpp
oaep.cpp
osrng.cpp
pkcspad.cpp
pssr.cpp
rijndael.cpp
rijndael_simd.cpp
rng.cpp
rsa.cpp
sha3.cpp
sse_simd.cpp
strciphr.cpp
```

**Comment by ujos** [comment]
After I've disabled `CRYPTOPP_DEBUG` I've managed to minimize list of source files to 
```
asn.cpp
ec2n.cpp
ecp.cpp
eprecomp.cpp
fips140.cpp
fipsalgt.cpp
hex.cpp
modes.cpp
oaep.cpp
osrng.cpp
pkcspad.cpp
rijndael.cpp
rijndael_simd.cpp
rng.cpp
sse_simd.cpp
strciphr.cpp
```

**Comment by noloader** [comment]
It sounds like you have worked things outs.
