### ISSUE TITLE
[arm_simd.h] Failed to cross-compile from x64 to ARM64

### ISSUE THREAD

**Issue by arsdever** [weidai11/cryptopp#955]
Hi, guys having a problem when cross-compiling for WindowsStore (UWP) ARM64. The compiler shows the error shown below. Even if I create an empty file, which only includes the `pch.h` and the `arm_simd.h` files - it fails. I tried moving the `VEXT_U8` function from the `arm_simd.h` to the empty source file (this time without including `arm_simd.h`) it also fails with the exact same error. Here is my computer info

Windows 10 Enterprise 1909
Crypto++ 8.2.0
Visual Studio 2019
WinSDK 10.0.18362.0

The error message

```
2>C:\.conan\2b5915\1\cryptopp-CRYPTOPP_8_2_0\arm_simd.h(155,1): error C2057: expected constant expression
2>C:\.conan\2b5915\1\cryptopp-CRYPTOPP_8_2_0\arm_simd.h(155,1): error C2057:         vreinterpretq_u8_u64(a), vreinterpretq_u8_u64(b), c);
2>C:\.conan\2b5915\1\cryptopp-CRYPTOPP_8_2_0\arm_simd.h(155,1): error C2057: ^
```

The list of project preprocessor definitions
```
_DEBUG
_WINDOWS
USE_PRECOMPILED_HEADERS
WIN32
_WIN32_WINNT=0xA00
_WIN32_IE=0x0A00
WINAPI_FAMILY=WINAPI_FAMILY_APP
__WRL_NO_DEFAULT_LIB__
_VC80_UPGRADE=0x0710
_ARM64_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE=1
%(ClCompile.PreprocessorDefinitions)
```

**Comment by arsdever** [comment]
In case anybody meets this problem. After a day of trying to figure out what's wrong and how to overcome the problem, the following solution was applied.

Like you can see on [vcpkg](https://github.com/microsoft/vcpkg/tree/master/ports/cryptopp) repository, you should download `CMakeLists.txt` file for `cryptopp` from [here](https://github.com/noloader/cryptopp-cmake). Then **DON'T FORGET TO** use the following CMake definitions
```
        -DBUILD_SHARED=OFF
        -DBUILD_STATIC=ON
        -DBUILD_TESTING=OFF
        -DBUILD_DOCUMENTATION=OFF
        -DDISABLE_ASM=${CRYPTOPP_DISABLE_ASM}
```

Where `${CRYPTOPP_DISABLE_ASM} = ON` at least for `UWP`. And that's it.

**Comment by noloader** [comment]
@arsdever,

This define is new to me.  What does the define do? Do you know?

```c++
_ARM64_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE=1
```

Also see [cryptest.nmake](https://github.com/weidai11/cryptopp/blob/master/cryptest.nmake). I use it to test ARM builds from the command line.
