### ISSUE TITLE
Binary bloat

### ISSUE THREAD

**Issue by expnkx** [weidai11/cryptopp#956]
### Crypto++ Issue Report
https://github.com/expnkx/fast_io/blob/master/examples/0053.cryptopp/sha256_cryptopp.cc
https://github.com/expnkx/fast_io/blob/master/examples/0053.cryptopp/sha512_cryptopp.cc

The binary bloat of cryptopp is probably too large.

![image](https://user-images.githubusercontent.com/57303909/85546137-9bdabd80-b5ea-11ea-8839-c7a3658307b4.png)
libcryptopp.a takes over 100MB of binary size.
![image](https://user-images.githubusercontent.com/57303909/85546327-c6c51180-b5ea-11ea-8fa2-9b9598e9c3a6.png)

I think the problem is because of the heavily virtual function usages in this library. C++ compilers are generally very terrible at optimizing dead virtual functions away. Putting everything into the different translation units make the optimizations even harder.
Any possibility to fix this problem in the future? I guess it requires some part of revamping by avoiding OOP and embraced C++20 Concepts.

**Comment by noloader** [comment]
> Any possibility to fix this problem in the future?

There is no problem.

You should enable dead code stripping and garbage collection in your project. Also see discussions like https://www.cryptopp.com/wiki/Wrapper_DLL#Takeaways.
