### ISSUE TITLE
Performance of SHA512 of CryptoPP is slower than OpenSSL.

### ISSUE THREAD

**Issue by expnkx** [weidai11/cryptopp#957]
My operating system is Win10. MinGW-w64, GCC 11.0.1. X86-64. Amd Ryzen 3600

![image](https://user-images.githubusercontent.com/57303909/85707856-96947600-b6b1-11ea-920b-2c035a458ab1.png)

It looks like OpenSSL implements this with AVX instructions. Any possibilities to optimize it so It can be as fast as OpenSSL?

**Comment by lazka** [comment]
What is CryptoPP?

**Comment by noloader** [comment]
Please avoid discussions in the bug tracker. Please reserve the bug tracker for bugs. Please have discussions on the [mailing list](https://groups.google.com/forum/#!forum/cryptopp-users).
