### ISSUE TITLE
When using ECIES to decrypt, cryptopp takes longer to calculate than Bouncy Castle

### ISSUE THREAD

**Issue by ywhz** [weidai11/cryptopp#959]
I tested ecies decrypt api 10000 times, Cryptopp(c++) takes about 10s,  Bouncy Castle(java) takes about 3s,  eciespy(python) takes about 3s
I tested RSA decrypt api 10000 times, Cryptopp takes about 10s, Bouncy Castle takes about 10s

Does the decrypt api of ecies can be optimized？

**Comment by noloader** [comment]
You should probably move this to the mailing list.
