### ISSUE TITLE
Failure to set CRYPTOPP_CXX17_EXCEPTIONS with clang

### ISSUE THREAD

**Issue by rogerorr** [weidai11/cryptopp#960]
### Crypto++ Issue Report

* State the operating system and version (Ubutnu 17 x86_64, Windows 7 Professional x64, etc)
Red Hat Enterprise Linux Server release 7.7 (Maipo)

* State the version of the Crypto++ library (Crypto++ 7.0, Master, etc)
Master

* State how you built the library (Makefile, Cmake, distro, etc)
Building with CMake

* Show a typical command line (the output of the compiler for cryptlib.cpp)
`clang++    -std=c++17 -Og -ggdb -D_GLIBCXX_ASSERTIONS -fsanitize=address -DBOOST_USE_ASAN -fPIC   -DCRYPTOPP_DISABLE_MIXED_ASM -MD -MT CMakeFiles/cryptopp-object.dir/eprecomp.cpp.o -MF CMakeFiles/cryptopp-object.dir/eprecomp.cpp.o.d -o CMakeFiles/cryptopp-object.dir/eprecomp.cpp.o -c /src/libs/CryptoPP/CryptoPP/eprecomp.cpp`

`clang++ --version`
`clang version 10.0.0`

* Show the link command (the output of the linker for libcryptopp.so or cryptest.exe)
N/A

* Show the exact error message you are receiving (copy and paste it); or
```
src/libs/CryptoPP/CryptoPP/algparam.h:315:12: warning: 'uncaught_exception' is deprecated [-Wdeprecated-declarations]
                if (std::uncaught_exception() == false)
                         ^
```

* Clearly state the undesired behavior (and state the expected behavior)
There is code in config_cxx.h that attempts to set the pre-processor symbol `CRYPTOPP_CXX17_EXCEPTIONS` for the various compilers.
The section for clang looks like this:
```
#if defined(__clang__)
# if __EXCEPTIONS && __has_feature(cxx_exceptions)
#  if __cpp_lib_uncaught_exceptions
#   define CRYPTOPP_CXX17_EXCEPTIONS 1
#  endif
...
```

Unfortunately, `__cpp_lib_uncaught_exceptions` is only guaranteed to be defined if the header `<exception>` has been included, so `CRYPTOPP_CXX17_EXCEPTIONS ` is not being set (even though clang 10 does support this) - unless the source file happens to include `<exception>` before it includes `<config.h>`.

**Comment by noloader** [comment]
Thanks @rogerorr.

Ugh... It looks like two problems. First, the one you detail. The second is, `algparam.h` is using `std::uncaught_exception` but not including the proper header.

Wei tried to keep headers lean, and we try to carry on the tradition. So I'm hesitant to include standard headers in `config_*.h`. With that said, we can't break things either.

This may sidestep the first problem and fix the second problem:

```
$ git diff
diff --git a/algparam.h b/algparam.h
index 61783371..4fbe6b80 100644
--- a/algparam.h
+++ b/algparam.h
@@ -6,6 +6,11 @@
 #ifndef CRYPTOPP_ALGPARAM_H
 #define CRYPTOPP_ALGPARAM_H
 
+// https://github.com/weidai11/cryptopp/issues/960
+#include <string>
+#include <typeinfo>
+#include <exception>
+
 #include "config.h"
 #include "cryptlib.h"
```

Can you give it a try?

**Comment by rogerorr** [comment]
It is tricky ... which is why I ducked out of providing a proposed resolution :)

Sadly most of the CryptoPP source files seems to start by including `pch.h` which itself includes `config.h` so your proposed resolution isn't a complete solution.

**Comment by rogerorr** [comment]
As feared, this change appears to make little difference to the build of CryptoPP itself; for now I'm simply setting `-DCRYPTOPP_CXX17_EXCEPTIONS` externally.

**Comment by noloader** [comment]
Ack, let's try this: [Commit 445243a9d1ab](https://github.com/weidai11/cryptopp/commit/445243a9d1ab).

The rub (for me) is, the macros are supposed to be defined in every translation unit without the need for a header. Also see [C++ feature tests](https://en.cppreference.com/w/cpp/feature_test).

**Comment by rogerorr** [comment]
Ah - there are two type of feature test macros: Language features and Library features.
The compiler sets the Language feature ones.
The standard library _that you are using_ sets the library feature ones.
The library ones should all be defined in `<version>` as the cppreference pages says:
"The following macros are defined if the header `<version>` or any of the corresponding headers in the table below is included. "

**Comment by rogerorr** [comment]
The commit resolves the warnings in my use case; thank you :)

**Comment by AraHaan** [comment]
Has the issue with compile error from using ``uncaught_exception`` when in c++20 mode been fixed yet?
