### ISSUE TITLE
core occurs when using ECB to decrypt text with another key which is different from the encypt key.

### ISSUE THREAD

**Issue by fenglonz** [weidai11/cryptopp#963]
-Linux admired-pod-193.localdomain 4.15.0-109-generic #110-Ubuntu SMP Tue Jun 23 02:39:32 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
-cryptopp-CRYPTOPP_8_1_0

Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f41a1263700 (LWP 20417))]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f41a2f098b1 in __GI_abort () at abort.c:79
#2  0x00007f41a38fc957 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007f41a3902ae6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f41a3902b21 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007f41a3902d54 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x0000563d777b558e in CryptoPP::StreamTransformationFilter::LastPut (this=<optimized out>, inString=0x7f4194008450 "\332\344\340A$\033\035N\202j\326\tè\f@", length=<optimized out>) at filters.cpp:839
#7  0x0000563d777b491d in CryptoPP::FilterWithBufferedInput::PutMaybeModifiable (this=0x7f4194007230, inString=<optimized out>, length=<optimized out>, messageEnd=-1, blocking=<optimized out>, modifiable=<optimized out>)
    at filters.cpp:431
#8  0x0000563d7772d4ec in CryptoPP::BufferedTransformation::ChannelPut2 (this=0x7f4194007230, channel=..., inString=<optimized out>, length=<optimized out>, messageEnd=<optimized out>, blocking=<optimized out>)
    at cryptlib.cpp:468
#9  0x0000563d7772e682 in CryptoPP::BufferedTransformation::ChannelMessageEnd (blocking=true, propagation=<optimized out>, channel="", this=0x7f4194007230) at cryptlib.h:2156
#10 CryptoPP::BufferedTransformation::TransferMessagesTo2 (this=0x7f41a12622b0, target=..., messageCount=@0x7f41a126203c: 0, channel="", blocking=<optimized out>) at cryptlib.cpp:655
#11 0x0000563d7772f151 in CryptoPP::BufferedTransformation::TransferAllTo2 (this=0x7f41a12622b0, target=..., channel="", blocking=<optimized out>) at cryptlib.cpp:696
#12 0x0000563d774a7c0e in CryptoPP::SourceTemplate<CryptoPP::StringStore>::PumpAll2 (this=0x7f41a1262280, blocking=true) at ../third/build/cryptopp/include/filters.h:1378
#13 0x0000563d774a4c04 in CryptoPP::Source::PumpAll (this=0x7f41a1262280) at ../third/build/cryptopp/include/filters.h:1319
#14 0x0000563d774a4c4d in CryptoPP::Source::SourceInitialize (this=0x7f41a1262280, pumpAll=true, parameters=...) at ../third/build/cryptopp/include/filters.h:1354
#15 0x0000563d774a4d0d in CryptoPP::StringSource::StringSource (this=0x7f41a1262280, 
    string="\304ME\370eB\342\262\001\230!\340\360\262\366V-\253\367+\214\364\261\305\021˿\344\b\313>(Ύ\224toN\227Wz\347\372b\316nJ\327+\316\356a\276o\200&\330\346\324g\306\301\377,\231\310Rꦮ\301\203\241\220))?f\\\267\036\320\030V\262\374\302\017)\203B\263\373\216\261\222\\\200\006\216\030\v\326\313\321\347,x\002O#\372\r\270R\246\333e\305\342\210v\262\225\255 n\315\372\355\071\260i\001#\021\271y\035|\336\324Ϻ\332\344\340A$\033\035N\202j\326\tè\f@", pumpAll=true, attachment=0x7f4194007230) at ../third/build/cryptopp/include/filters.h:1420
#16 0x0000563d774a34ac in ECBSAes::Decrypt (this=0x7f41a12623b0, 
    strCipher="\304ME\370eB\342\262\001\230!\340\360\262\366V-\253\367+\214\364\261\305\021˿\344\b\313>(Ύ\224toN\227Wz\347\372b\316nJ\327+\316\356a\276o\200&\330\346\324g\306\301\377,\231\310Rꦮ\301\203\241\220))?f\\\267\036\320\030V\262\374\302\017)\203B\263\373\216\261\222\\\200\006\216\030\v\326\313\321\347,x\002O#\372\r\270R\246\333e\305\342\210v\262\225\255 n\315\372\355\071\260i\001#\021\271y\035|\336\324Ϻ\332\344\340A$\033\035N\202j\326\tè\f@") at common/ecbsaes.cc:82

**Comment by noloader** [comment]
I'm guessing you got this sorted out by now.

In the future, please ask questions on the mailing list.
