### ISSUE TITLE
Unable to build the Cryptopp library using Intel c++ compiler 19 

### ISSUE THREAD

**Issue by Aditya-11** [weidai11/cryptopp#971]
Build Error log :

```
Error	8	error : member "CryptoPP::AllocatorBase<T>::size_type [with T=CryptoPP::word64={unsigned __int64}]" is not a type name	C:\Users\Anant Devi\Desktop\Crypto-project\secblock.h	182	1	cryptlib
Error	7	error : member "CryptoPP::AllocatorBase<T>::size_type [with T=CryptoPP::word32={unsigned int}]" is not a type name	C:\Users\Anant Devi\Desktop\Crypto-project\secblock.h	182	1	cryptlib
Error	6	error : member "CryptoPP::AllocatorBase<T>::size_type [with T=CryptoPP::word16={unsigned short}]" is not a type name	C:\Users\Anant Devi\Desktop\Crypto-project\secblock.h	182	1	cryptlib
Error	5	error : member "CryptoPP::AllocatorBase<T>::size_type [with T=CryptoPP::byte={unsigned char}]" is not a type name	C:\Users\Anant Devi\Desktop\Crypto-project\secblock.h	182	1	cryptlib
Error	1	error : identifier "constexpr" is undefined	C:\Users\Anant Devi\Desktop\Crypto-project\secblock.h	72	1	cryptlib
Error	3	error : expected a ";"	C:\Users\Anant Devi\Desktop\Crypto-project\secblock.h	72	1	cryptlib
Error	10	error : expected a ";"	C:\Users\Anant Devi\Desktop\Crypto-project\secblock.h	311	1	cryptlib
Error	12	error : expected a ";"	C:\Users\Anant Devi\Desktop\Crypto-project\secblock.h	468	1	cryptlib
Error	15	error : expected a ";"	C:\Users\Anant Devi\Desktop\Crypto-project\secblock.h	665	1	cryptlib
Error	2	error : "size_type" has already been declared in the current scope	C:\Users\Anant Devi\Desktop\Crypto-project\secblock.h	72	1	cryptlib
Error	9	error : "size_type" has already been declared in the current scope	C:\Users\Anant Devi\Desktop\Crypto-project\secblock.h	311	1	cryptlib
Error	11	error : "size_type" has already been declared in the current scope	C:\Users\Anant Devi\Desktop\Crypto-project\secblock.h	468	1	cryptlib
Error	14	error : "size_type" has already been declared in the current scope	C:\Users\Anant Devi\Desktop\Crypto-project\secblock.h	665	1	cryptlib
```

**Comment by Aditya-11** [comment]
Build Error log :

Error	8	error : member "CryptoPP::AllocatorBase<T>::size_type [with T=CryptoPP::word64={unsigned __int64}]" is not a type name	C:\Users\Anant Devi\Desktop\Crypto-project\secblock.h	182	1	cryptlib
Error	7	error : member "CryptoPP::AllocatorBase<T>::size_type [with T=CryptoPP::word32={unsigned int}]" is not a type name	C:\Users\Anant Devi\Desktop\Crypto-project\secblock.h	182	1	cryptlib
Error	6	error : member "CryptoPP::AllocatorBase<T>::size_type [with T=CryptoPP::word16={unsigned short}]" is not a type name	C:\Users\Anant Devi\Desktop\Crypto-project\secblock.h	182	1	cryptlib
Error	5	error : member "CryptoPP::AllocatorBase<T>::size_type [with T=CryptoPP::byte={unsigned char}]" is not a type name	C:\Users\Anant Devi\Desktop\Crypto-project\secblock.h	182	1	cryptlib
Error	1	error : identifier "constexpr" is undefined	C:\Users\Anant Devi\Desktop\Crypto-project\secblock.h	72	1	cryptlib
Error	3	error : expected a ";"	C:\Users\Anant Devi\Desktop\Crypto-project\secblock.h	72	1	cryptlib
Error	10	error : expected a ";"	C:\Users\Anant Devi\Desktop\Crypto-project\secblock.h	311	1	cryptlib
Error	12	error : expected a ";"	C:\Users\Anant Devi\Desktop\Crypto-project\secblock.h	468	1	cryptlib
Error	15	error : expected a ";"	C:\Users\Anant Devi\Desktop\Crypto-project\secblock.h	665	1	cryptlib
Error	2	error : "size_type" has already been declared in the current scope	C:\Users\Anant Devi\Desktop\Crypto-project\secblock.h	72	1	cryptlib
Error	9	error : "size_type" has already been declared in the current scope	C:\Users\Anant Devi\Desktop\Crypto-project\secblock.h	311	1	cryptlib
Error	11	error : "size_type" has already been declared in the current scope	C:\Users\Anant Devi\Desktop\Crypto-project\secblock.h	468	1	cryptlib
Error	14	error : "size_type" has already been declared in the current scope	C:\Users\Anant Devi\Desktop\Crypto-project\secblock.h	665	1	cryptlib

**Comment by noloader** [comment]
I'm not sure which Intel compiler you are using, and I don't have a compiler to test with.

You should open `config_cxx.h` and undefine `CRYPTOPP_CXX11_CONSTEXPR`.

**Comment by Aditya-11** [comment]
I am using intel c++ 19 compiler. In the documentation it says it  supports from Intel 11 to Intel 16 compiler .

**Comment by noloader** [comment]
Intel compiler version 13.0 and 14.0 are supposed to support C++11 constexpr. See the _C++11 core language features_  chart at [cppreference.com](https://en.cppreference.com/w/cpp/compiler_support). If I recall, Intel 13.0 was a partial implementation, so we punted and enabled it for Intel 16.0 because Intel keeps botching the implementation. From `config_cxx.h`:

```
// constexpr: MS at VS2015 (19.00); GCC at 4.6; Clang at 3.1; Intel 16.0; SunCC 5.13.
// Intel has mis-supported the feature since at least ICPC 13.00
#if (__cpp_constexpr >= 200704) || __has_feature(cxx_constexpr) || \
	(CRYPTOPP_MSC_VERSION >= 1900) || (__INTEL_COMPILER >= 1600) || \
	(CRYPTOPP_GCC_VERSION >= 40600) || (__SUNPRO_CC >= 0x5130)
# define CRYPTOPP_CXX11_CONSTEXPR 1
#endif // constexpr compilers
```

If Intel C++ 19.0 compiler does not support `constexpr`, then you need to disable it like shown above.

**Comment by Aditya-11** [comment]
@noloader after commenting the CONSTEXPR macro as mentioned above , Some of the errors related to that resolved but some error still persists . Can you throw some light on that ? 

Before commenting the  CONSTEXPR 

Error	8	error : member "CryptoPP::AllocatorBase<T>::size_type [with T=CryptoPP::word64={unsigned __int64}]" is not a type name	C:\Users\Anant Devi\Desktop\Crypto-project\secblock.h	182	1	cryptlib
Error	7	error : member "CryptoPP::AllocatorBase<T>::size_type [with T=CryptoPP::word32={unsigned int}]" is not a type name	C:\Users\Anant Devi\Desktop\Crypto-project\secblock.h	182	1	cryptlib
Error	6	error : member "CryptoPP::AllocatorBase<T>::size_type [with T=CryptoPP::word16={unsigned short}]" is not a type name	C:\Users\Anant Devi\Desktop\Crypto-project\secblock.h	182	1	cryptlib
Error	5	error : member "CryptoPP::AllocatorBase<T>::size_type [with T=CryptoPP::byte={unsigned char}]" is not a type name	C:\Users\Anant Devi\Desktop\Crypto-project\secblock.h	182	1	cryptlib
Error	1	error : identifier "constexpr" is undefined	C:\Users\Anant Devi\Desktop\Crypto-project\secblock.h	72	1	cryptlib
Error	3	error : expected a ";"	C:\Users\Anant Devi\Desktop\Crypto-project\secblock.h	72	1	cryptlib
Error	10	error : expected a ";"	C:\Users\Anant Devi\Desktop\Crypto-project\secblock.h	311	1	cryptlib
Error	12	error : expected a ";"	C:\Users\Anant Devi\Desktop\Crypto-project\secblock.h	468	1	cryptlib
Error	15	error : expected a ";"	C:\Users\Anant Devi\Desktop\Crypto-project\secblock.h	665	1	cryptlib
Error	2	error : "size_type" has already been declared in the current scope	C:\Users\Anant Devi\Desktop\Crypto-project\secblock.h	72	1	cryptlib
Error	9	error : "size_type" has already been declared in the current scope	C:\Users\Anant Devi\Desktop\Crypto-project\secblock.h	311	1	cryptlib
Error	11	error : "size_type" has already been declared in the current scope	C:\Users\Anant Devi\Desktop\Crypto-project\secblock.h	468	1	cryptlib
Error	14	error : "size_type" has already been declared in the current scope	C:\Users\Anant Devi\Desktop\Crypto-project\secblock.h	665	1	cryptlib

After commenting CONSTEXPR macro 

Error	1	error : expected a type specifier	C:\Users\Anant Devi\Desktop\Crypto-project\secblock.h	484	1	cryptlib
Error	4	error : expected a type specifier	C:\Users\Anant Devi\Desktop\Crypto-project\secblock.h	678	1	cryptlib
Error	3	error : expected a ";"	C:\Users\Anant Devi\Desktop\Crypto-project\secblock.h	484	1	cryptlib
Error	6	error : expected a ";"	C:\Users\Anant Devi\Desktop\Crypto-project\secblock.h	678	1	cryptlib
Error	2	error #303: explicit type is missing ("int" assumed)	C:\Users\Anant Devi\Desktop\Crypto-project\secblock.h	484	1	cryptlib
Error	5	error #303: explicit type is missing ("int" assumed)	C:\Users\Anant Devi\Desktop\Crypto-project\secblock.h	678	1	cryptlib

**Comment by Aditya-11** [comment]
@noloader  I had to comment out the following macros in the config.h to compile using intel 19 c++ compiler : 

CRYPTOPP_CXX11_NOEXCEPT 
CRYPTOPP_CXX11_CONSTEXPR 
CRYPTOPP_CXX11_ALIGNOF
CRYPTOPP_CXX11_ALIGNAS
