### ISSUE TITLE
Unable to compile cryptlib

### ISSUE THREAD

**Issue by efmer** [weidai11/cryptopp#972]
Windows 10, using the latest Microsoft Visual Studio 2019.

Build cryptlib (cryptlib.vcxproj) fails:
```
1>cpu.cpp(314): error C3861: '_xgetbv': identifier not found
```

```
// Visual Studio 2010 and above, 32 and 64-bit
#if defined(_MSC_VER) && (_MSC_VER >= 1600)

314 >>>>	return _xgetbv(num);

// Visual Studio 2008 and below, 64-bit
#elif defined(_MSC_VER) && defined(_M_X64)

	return XGETBV64(num);

// Visual Studio 2008 and below, 32-bit
#elif defined(_MSC_VER) && defined(_M_IX86)
```

I changed it to return XGETBV64(num); in the 64 bit build that builds.

**Comment by efmer** [comment]
After an update linking the library Debug X64 works.

**Comment by noloader** [comment]
According to this [Mozilla bug](https://bugzilla.mozilla.org/show_bug.cgi?id=977829), it looks like Microsoft's `_xgetbv` intrinsic is available with VS20120 SP1.

I think we can do one of two things. First, key on VS2010 SP1. I normally try to use the readily available compiler support, like below.

```
diff --git a/cpu.cpp b/cpu.cpp
index 287d3a9a..ee042be7 100644
--- a/cpu.cpp
+++ b/cpu.cpp
@@ -308,8 +308,8 @@ extern bool CPU_ProbeSSE2();
 // https://gcc.gnu.org/bugzilla/show_bug.cgi?id=85684.
 word64 XGetBV(word32 num)
 {
-// Visual Studio 2010 and above, 32 and 64-bit
-#if defined(_MSC_VER) && (_MSC_VER >= 1600)
+// Visual Studio 2010 SP1 and above, 32 and 64-bit
+#if defined(_MSC_VER) && (_MSC_FULL_VER >= 160040219)

        return _xgetbv(num);

@@ -360,6 +360,8 @@ word64 XGetBV(word32 num)
                : "=a"(a), "=d"(d) : "c"(num) : "cc"
        );
        return (static_cast<word64>(d) << 32) | a;
+#else
+       # error "Need an xgetbv function"
 #endif
 }
```

Second, we can avoid `_xgetbv` intrinsic completely. 32-bit will use the inline ASM; and 64-bit will use `XGETBV64` which is [ASM in `x64dll.asm`](https://github.com/weidai11/cryptopp/blob/master/x64dll.asm#L1982).

Do you have a preference?

**Comment by noloader** [comment]
This should be cleared with [Commit ba286e6780aa](https://github.com/weidai11/cryptopp/commit/ba286e6780aa).

**Comment by noloader** [comment]
This should be cleared with [Commit ba286e6780aa](https://github.com/weidai11/cryptopp/commit/ba286e6780aa) and [Commit 38e6763249c7](https://github.com/weidai11/cryptopp/commit/38e6763249c7).

There were two commits because I forgot to transfer an updated `cpu.cpp` to my check-in machine after testing.

**Comment by wyattoday** [comment]
This commit has a bug. Namely, AMR64 target in MSVC compilers can't include that file.

```
#if !defined(_M_IX86) && !defined(_M_X64)
#error This header is specific to X86 and X64 targets
#endif
```

The fix, in cpu.cpp:

```
// For _xgetbv on Microsoft 32-bit and 64-bit platforms
// https://github.com/weidai11/cryptopp/issues/972
#if _MSC_VER >= 1600 && (CRYPTOPP_BOOL_X86 || CRYPTOPP_BOOL_X32 || CRYPTOPP_BOOL_X64)
# include <immintrin.h>
#endif
```

**Comment by noloader** [comment]
Thanks @wyattoday.

This should be cleared (again!) with [Commit 7177df3068b6](https://github.com/weidai11/cryptopp/commit/7177df3068b6).
