### ISSUE TITLE
Unable to run cryptest.exe on MinGW

### ISSUE THREAD

**Issue by brc-dd** [weidai11/cryptopp#973]
### Unable to run cryptest.exe on MinGW

* Operating System : Windows 10 (version 2004) x64 (also verified on Windows 7 x64, Windows 8.1 x64)
* Crypto++ Version : 8.2.0
* Used `mingw32-make` to build the library. 
* The output for `mingw32-make` command didn't showed any error.
* __Running `mingw32-make test` gave this error :__

  ```
  ./cryptest.exe v
  mingw32-make: *** [GNUmakefile:1147: test] Error -1073741511
  ```

* `g++` version : `10.2.0-3`
* `make` version : `4.3-1`

<hr>

Also, unable to use this package : [mingw-w64-crypto++](https://packages.msys2.org/package/mingw-w64-x86_64-crypto++).

Note that  in both the cases no compiler/linker error is thrown. Only the built programs are throwing exception(s) (noticed core dump and heap corruption) at runtime.

**Comment by noloader** [comment]
This is probably an issue with MinGW and `mingw-make`. See _"What's the difference between make and mingw32-make?"_ at the [MinGW FAQ](http://mingw.org/wiki/FAQ).

Maybe you can ask the MinGW folks what error `-1073741511` is.
