### ISSUE TITLE
BaseN_Decoder calling virtual function in constructor clang-tidy warning

### ISSUE THREAD

**Issue by ganibc** [weidai11/cryptopp#975]
Operating System : MacOS Catalina
Crypto++ Version : 8.2.0
Apple clang version 11.0.3 (clang-1103.0.32.29)

I wrote this code:
```
    Base64Decoder signatureDecoder;
    signatureDecoder.Put((CryptoPP::byte*)signatureString.data(), signatureString.size());
    signatureDecoder.MessageEnd();
    std::vector<CryptoPP::byte> signatureData(signatureDecoder.MaxRetrievable());
    signatureDecoder.Get(signatureData.data(), signatureData.size());
```
Build using clang and got warning from clang-tidy
```
basecode.h:81:3: warning: Call to virtual function during construction [clang-analyzer-optin.cplusplus.VirtualCall]
IsolatedInitialize(MakeParameters(Name::DecodingLookupArray(), lookup)(Name::Log2Base(), log2base));
```
I think the warning is pointing the wrong place because IsolatedInitialize is not a virtual function. 
But Detach function is virtual and it's called in the constructor.
Is this intentional? If yes, why? As far as I know, virtual function should never be called from constructor because virtual table is not filled yet.

**Comment by noloader** [comment]
Yes, it is intentional.

During construction, the virtual members are *not* invoked. That is standard C++. See https://isocpp.org/wiki/faq/strange-inheritance#calling-virtuals-from-ctors .
