### ISSUE TITLE
compilation failed if avx/avx2 disabled

### ISSUE THREAD

**Issue by dfleury2** [weidai11/cryptopp#976]
Debian, gcc 10.2, cryptopp 8.2.0
build using cmake

/opt/gcc-10.2/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/avxintrin.h:1278:1: error: inlining failed in call to ‘always_inline’ ‘__m256i _mm256_set_epi8(char, char, char, char, char, char, char, char, char, char, char, char, char, char, char, char, char, char, char, char, char, char, char, char, char, char, char, char, char, char, char, char)’: target specific option mismatch

and a warning

chacha_avx.cpp:69:47: warning: AVX vector return without AVX enabled changes the ABI [-Wpsabi]
   69 | inline __m256i RotateLeft<8>(const __m256i val)

**Comment by noloader** [comment]
Please ensure the build works as expected with the Makefile.

Also see https://www.cryptopp.com/wiki/CMake.

**Comment by dfleury2** [comment]
The compilation using Make works fine.
This is an issue with the CMakeLists.txt
