### ISSUE TITLE
TLS certificate chain on cryptopp.com website incomplete

### ISSUE THREAD

**Issue by sobukus** [weidai11/cryptopp#984]
This is kindof a meta-issue regarding cryptopp … I do not see an obvious webmaster contact. The site https://cryptopp.com has certificate validation issues. While Firefox does not complain, contacting the site via lynx fails:

```
SSL error:The certificate is NOT trusted. The certificate issuer is unknown. -Continue? (n)
```

More detail from curl:
```
$ curl https://cryptopp.com
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
```
Some more detail from openssl:

```
$ openssl s_client -connect cryptopp.com:443
CONNECTED(00000003)
depth=0 CN = cryptopp.com
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = cryptopp.com
verify error:num=21:unable to verify the first certificate
verify return:1
---
Certificate chain
 0 s:CN = cryptopp.com
   i:C = US, O = Let's Encrypt, CN = R3
 1 s:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIFMTCCBBmgAwIBAgISA7DHsPWZUKQK0eht0Nrt45RcMA0GCSqGSIb3DQEBCwUA
[…]
Wwab9I28rDJ/xQVhVpb19sSds9qEndRIS49yJlIK6J5O9D7/Kg==
-----END CERTIFICATE-----
subject=CN = cryptopp.com

issuer=C = US, O = Let's Encrypt, CN = R3

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 3216 bytes and written 430 bytes
Verification error: unable to verify the first certificate
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
```

I'm no expert on this, but I'm told that the reason is that the server doesn't serve the whole certificate chain, which you normally also get from the letsencrypt acme client script.

I guess it is good form for a crypto librarie's website to have a flawless crypto setup … I hope this report helps to achieve that. This was tested on Debian 10.7 and Ubuntu 20.04, as well as curl from pkgsrc using CentOS 7 root certificate set.

Right now, automated downloads in build scripts won't succeed unless certificate checking is disabled.

**Comment by noloader** [comment]
Thanks @sobukus.

I updated the website certificate last week.

> This is kind of a meta-issue regarding Crypto++… I do not see an obvious webmaster contact. 

Yeah, this or the mailing list is fine.

> SSL error:The certificate is NOT trusted. The certificate issuer is unknown. -Continue? (n)

Ugh... I experienced a similar problem on Monday downloading tarballs from GNU's ftp.gnu.org. It appears the Let's Encrypt intermediate CA changed on (or about) December 4. The old one was issued by Identitrust. The new one is issued by ISRG.

For the [build scripts I was having trouble with](https://github.com/noloader/Build-Scripts), I needed to use the CA called Let's Encrypt Authority R3 (the old one was Let's Encrypt Authority X3).

> but I'm told that the reason is that the server doesn't serve the whole certificate chain, which you normally also get from the letsencrypt acme client script.

Yeah, that sounds about right.

Here's the process we use to update the webserver's certificate: [lets-encrypt.ext](https://github.com/weidai11/website/blob/master/letsencrypt/letsencrypt.txt). The warez from Let's Encrypt is supposed to include the necessary intermediate CA's. 

Let me get get the CA chain updated on the web server. It sounds like it is not providing Let's Encrypt Authority R3. I think the update I performed last week happened before intermediate Let's Encrypt CA change, so the chain does not include the new intermediate CA.

> This was tested on Debian 10.7 and Ubuntu 20.04, as well as curl from pkgsrc using CentOS 7 root certificate set.

This is kind of interesting in a morbid sort of way... Testing using Firefox on Windows 8.1 and Ubuntu 18.04 is OK.

No big deal, though. We'll get the missing intermediate added.

**Comment by noloader** [comment]
@sobukus,

I added the Let's Encrypt Root R3 certificate to the chain.

Would you give things a try, please.

```
# cat /etc/pki/tls/certs/cryptopp-com.chain.pem
############################
# Let's Encrypt Authority R3
-----BEGIN CERTIFICATE-----
MIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw
TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjAwOTA0MDAwMDAw
WhcNMjUwOTE1MTYwMDAwWjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
RW5jcnlwdDELMAkGA1UEAxMCUjMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
AoIBAQC7AhUozPaglNMPEuyNVZLD+ILxmaZ6QoinXSaqtSu5xUyxr45r+XXIo9cP
R5QUVTVXjJ6oojkZ9YI8QqlObvU7wy7bjcCwXPNZOOftz2nwWgsbvsCUJCWH+jdx
sxPnHKzhm+/b5DtFUkWWqcFTzjTIUu61ru2P3mBw4qVUq7ZtDpelQDRrK9O8Zutm
NHz6a4uPVymZ+DAXXbpyb/uBxa3Shlg9F8fnCbvxK/eG3MHacV3URuPMrSXBiLxg
Z3Vms/EY96Jc5lP/Ooi2R6X/ExjqmAl3P51T+c8B5fWmcBcUr2Ok/5mzk53cU6cG
/kiFHaFpriV1uxPMUgP17VGhi9sVAgMBAAGjggEIMIIBBDAOBgNVHQ8BAf8EBAMC
AYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBIGA1UdEwEB/wQIMAYB
Af8CAQAwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYfr52LFMLGMB8GA1UdIwQYMBaA
FHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcw
AoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzAnBgNVHR8EIDAeMBygGqAYhhZodHRw
Oi8veDEuYy5sZW5jci5vcmcvMCIGA1UdIAQbMBkwCAYGZ4EMAQIBMA0GCysGAQQB
gt8TAQEBMA0GCSqGSIb3DQEBCwUAA4ICAQCFyk5HPqP3hUSFvNVneLKYY611TR6W
PTNlclQtgaDqw+34IL9fzLdwALduO/ZelN7kIJ+m74uyA+eitRY8kc607TkC53wl
ikfmZW4/RvTZ8M6UK+5UzhK8jCdLuMGYL6KvzXGRSgi3yLgjewQtCPkIVz6D2QQz
CkcheAmCJ8MqyJu5zlzyZMjAvnnAT45tRAxekrsu94sQ4egdRCnbWSDtY7kh+BIm
lJNXoB1lBMEKIq4QDUOXoRgffuDghje1WrG9ML+Hbisq/yFOGwXD9RiX8F6sw6W4
avAuvDszue5L3sz85K+EC4Y/wFVDNvZo4TYXao6Z0f+lQKc0t8DQYzk1OXVu8rp2
yJMC6alLbBfODALZvYH7n7do1AZls4I9d1P4jnkDrQoxB3UqQ9hVl3LEKQ73xF1O
yK5GhDDX8oVfGKF5u+decIsH4YaTw7mP3GFxJSqv3+0lUFJoi5Lc5da149p90Ids
hCExroL1+7mryIkXPeFM5TgO9r0rvZaBFOvV2z0gp35Z0+L4WPlbuEjN/lxPFin+
HlUjr8gRsI3qfJOQFy/9rKIJR0Y/8Omwt/8oTWgy1mdeHmmjk7j1nYsvC9JSQ6Zv
MldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqX
nLRbwHOoq7hHwg==
-----END CERTIFICATE-----

############################
# Let's Encrypt Authority X3
-----BEGIN CERTIFICATE-----
MIIEkjCCA3qgAwIBAgIQCgFBQgAAAVOFc2oLheynCDANBgkqhkiG9w0BAQsFADA/
MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
DkRTVCBSb290IENBIFgzMB4XDTE2MDMxNzE2NDA0NloXDTIxMDMxNzE2NDA0Nlow
SjELMAkGA1UEBhMCVVMxFjAUBgNVBAoTDUxldCdzIEVuY3J5cHQxIzAhBgNVBAMT
GkxldCdzIEVuY3J5cHQgQXV0aG9yaXR5IFgzMIIBIjANBgkqhkiG9w0BAQEFAAOC
AQ8AMIIBCgKCAQEAnNMM8FrlLke3cl03g7NoYzDq1zUmGSXhvb418XCSL7e4S0EF
q6meNQhY7LEqxGiHC6PjdeTm86dicbp5gWAf15Gan/PQeGdxyGkOlZHP/uaZ6WA8
SMx+yk13EiSdRxta67nsHjcAHJyse6cF6s5K671B5TaYucv9bTyWaN8jKkKQDIZ0
Z8h/pZq4UmEUEz9l6YKHy9v6Dlb2honzhT+Xhq+w3Brvaw2VFn3EK6BlspkENnWA
a6xK8xuQSXgvopZPKiAlKQTGdMDQMc2PMTiVFrqoM7hD8bEfwzB/onkxEz0tNvjj
/PIzark5McWvxI0NHWQWM6r6hCm21AvA2H3DkwIDAQABo4IBfTCCAXkwEgYDVR0T
AQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAYYwfwYIKwYBBQUHAQEEczBxMDIG
CCsGAQUFBzABhiZodHRwOi8vaXNyZy50cnVzdGlkLm9jc3AuaWRlbnRydXN0LmNv
bTA7BggrBgEFBQcwAoYvaHR0cDovL2FwcHMuaWRlbnRydXN0LmNvbS9yb290cy9k
c3Ryb290Y2F4My5wN2MwHwYDVR0jBBgwFoAUxKexpHsscfrb4UuQdf/EFWCFiRAw
VAYDVR0gBE0wSzAIBgZngQwBAgEwPwYLKwYBBAGC3xMBAQEwMDAuBggrBgEFBQcC
ARYiaHR0cDovL2Nwcy5yb290LXgxLmxldHNlbmNyeXB0Lm9yZzA8BgNVHR8ENTAz
MDGgL6AthitodHRwOi8vY3JsLmlkZW50cnVzdC5jb20vRFNUUk9PVENBWDNDUkwu
Y3JsMB0GA1UdDgQWBBSoSmpjBH3duubRObemRWXv86jsoTANBgkqhkiG9w0BAQsF
AAOCAQEA3TPXEfNjWDjdGBX7CVW+dla5cEilaUcne8IkCJLxWh9KEik3JHRRHGJo
uM2VcGfl96S8TihRzZvoroed6ti6WqEBmtzw3Wodatg+VyOeph4EYpr/1wXKtx8/
wApIvJSwtmVi4MFU5aMqrSDE6ea73Mj2tcMyo5jMd6jmeWUHK8so/joWUoHOUgwu
X4Po1QYz+3dszkDqMp4fklxBwXRsW10KXzPMTZ+sOPAveyxindmjkW8lGy+QsRlG
PfZ+G6Z6h7mjem0Y+iWlkYcV4PIWL1iwBi8saCbGS5jN2p8M+X+Q7UNKEkROb3N6
KOqkqm57TH2H3eDJAkSnh6/DNFu0Qg==
-----END CERTIFICATE-----
```

**Comment by sobukus** [comment]
Yep, it works nicely now. Thanks for the quick handling.

**Comment by noloader** [comment]
@sobukus,

Perfect, thanks.

**Comment by noloader** [comment]
@sobukus,

I removed the _Let's Encrypt Authority X3_ certificate. It was not needed and produced a finding for Qualsys' [SSL Server Test](https://www.ssllabs.com/ssltest/analyze.html?d=www.cryptopp.com). Everything should be OK after removal of the unneeded intermediate.

The website gets a B rating from Qualsys due to support for TLS 1.0 and TLS 1.1. We don't serve anything of value and give everything away, so there's nothing really to steal. Downloads, like a release tarball, have GnuPG signatures on them for folks paranoid about the TLS channel.

We don't support TLS 1.3 due to CentOS 7. Red Hat provides antique software. OpenSSL 1.0.2 (now EOL) does not support TLS 1.3. I wish our web server was running Fedora 33 server. We would not suffer the antique software problems.
