### ISSUE TITLE
Everything is being parsed incorrectly.

### ISSUE THREAD

**Issue by slzero-X** [weidai11/cryptopp#985]
I have the files already compiled, using msys64 with Code::Blocks IDE, however there is a problem.
The namespace type is not found despite it clearly being part of the C++ standard, and even if the version is from 2019 and msys64 is up to date, Code::Blocks struggles to parse the code correctly.

So I have a thought, is Crypto++ at all compatible with Code::Blocks? Its Mingw based so it shouldn't have any problems.

**Comment by noloader** [comment]
It sounds like a CodeBlocks problem. You should file a bug report against CodeBlocks, not Crypto++.
