### ISSUE TITLE
Followup to GH #982

### ISSUE THREAD

**Issue by dwmcrobb** [weidai11/cryptopp#988]
Having looked at this again, this code should never be used as is on any platform.  When `m_array` is not 16-byte aligned, it will return a pointer to memory not owned by `m_array`.  Leading to definite stack or heap corruption, depending on where the class template was instantiated.

https://github.com/weidai11/cryptopp/blob/23137bada3d31bae8333645a2301f968a73f809f/secblock.h#L519

This code appears to have been in place all the way back to 2007.  I can't say for certain why it wasn't reported before.  A big part of it is probably just the fact that the assertions didn't find the issue, plus the fact that the compilers on the most common platforms didn't see this code (`_M_X64` or `__x86_64__` was defined).  I had eliminated it by defining `CRYPTOPP_DISABLE_ASM` and fixing the check as in #982 as a cursory fix on the platforms where this code was used, without digging (I didn't have an isolated test for it, and when it appeared in my applications, it was corrupting the stack and hence making it more difficult to track down than I had time to allot to find it).  But now that I've looked at it closely, it's always been wrong.

The comment about stacks growing downward isn't relevant; the addresses of array elements ALWAYS grow upward with index, it's part of the language rules.  As far as I know, this has been true since the very inception of C, predating the first C standard.  It is of course codified in the language standards too.  Just as examples, see sections 6.5.6 and 6.5.8 of the C99 standard.  Or here for some of the relevant rules without purchasing one of the standards:

https://en.cppreference.com/w/c/language/operator_comparison
https://en.cppreference.com/w/c/language/operator_arithmetic

Stack _frame_ addresses usually grown downward, but there are exceptions.  But it's not relevant here.

I've implemented a correct version in my local repo.  Works with any alignment, not just 16, and hence the alignment could be pulled up to a class template parameter (perhaps replacing `T_Align16`).  I made it easy to do so; the alignment is a static const private class member that happens to be set to 16.  I don't have any code handy that will compile as C++03, but it's probably possible to write a test for it with C++03 in mind since my patched version doesn't use any C++11 features.

Given what this code is intended to do, I think the assertions should be in release builds, not just debug builds.  Since `S` is a required template parameter, all of the work could actually be done in construction, including the assertions.  Then store `p_array` as a private class member and just return it in `GetAlignedArray()`.

I can fork and issue a pull request if you'd like to review.

**Comment by noloader** [comment]
> This code appears to have been in place all the way back to 2007. I can't say for certain why it wasn't reported before. 

I _think_ the primary reason is, it is not frequently used and slipped under the radar for testing. I _think_ a secondary reason is, the library and testing framework usually use `new` and don't place objects on the stack. For example, a `new BLAKE2b` will get a heap alignment, not a stack alignment. Hence the reason the testing has been deficient.

The [incomplete] improvements happened after we added `BLAKE2`. I did not use `new`; rather I put the `BLAKE2s` and `BLAKE2b` objects on the stack. That caused random memory errors which led to addition of `CRYPTOPP_ASSERT(m_allocated)` at [line 432](https://github.com/weidai11/cryptopp/blob/master/secblock.h#L421). Investigating the assert led to the [incomplete] improvements I made.

I now regret trying to improve it. In hindsight I should have ripped it out and replaced it with heap allocations.

> Given what this code is intended to do, I think the assertions should be in release builds, not just debug builds.

No, we don't assert in production. See https://www.cryptopp.com/wiki/Assertions.

> I can fork and issue a pull request if you'd like to review.

Yes, sure.

If possible, don't remove `m_array` and `GetAlignedArray`. I want to release a Crypto++ 8.4 so I'd like to keep compatibility.

If we break the object layout then we need to move to Crypto++ 9.0, which I'm not ready to do at the moment.

**Comment by mouse07410** [comment]
Sorry, I'm a little squeezed right now time-wise.

Overall, I concur with @noloader conclusions and the action plan.

- I wonder whether it's better to shift more towards heap allocation, but I'm counted among the more adventurous, and I value compatibility with the (really) old software and hardware somewhat less. So, at this time I'd probably just dropped support for C++-03 and earlier...

**Comment by dwmcrobb** [comment]
> > This code appears to have been in place all the way back to 2007. I can't say for certain why it wasn't reported before.
> 
> I _think_ the primary reason is, it is not frequently used and slipped under the radar for testing. I _think_ a secondary reason is, the library and testing framework usually use `new` and don't place objects on the stack. For example, a `new BLAKE2b` will get a heap alignment, not a stack alignment. Hence the reason the testing has been deficient.

But the problem doesn't go away if the object is on the heap.  m_array is just a member within the instantiation of the class template; there is no guarantee that it's 16-byte aligned unless the toolchain lets us guarantee it (via alignas() or similar).  The best we can hope for with no alignas() or similar mechanism is whatever its natural alignment happens to be.

This is not a stack-specific issue.  `new BLAKE2b()` doesn't force m_array to be 16-byte aligned; it simply puts a BLAKE2b on the heap.  Yes, you could get lucky that the heap allocator puts the BLAKE2b at an address that results in m_array being 16-byte aligned, but... it's just happenstance.  No guarantee, and your odds are not good with many heap allocators if m_array's offset within the object isn't a multiple of 16 bytes.

> 
> The [incomplete] improvements happened after we added `BLAKE2`. I did not use `new`; rather I put the `BLAKE2s` and `BLAKE2b` objects on the stack. That caused random memory errors which led to addition of `CRYPTOPP_ASSERT(m_allocated)` at [line 432](https://github.com/weidai11/cryptopp/blob/master/secblock.h#L421). Investigating the assert led to the [incomplete] improvements I made, including the incorrect asserts.
> 
> I now regret trying to improve it. It was bad judgement on my part because I knew it was shady. In hindsight I should have ripped it out and replaced it with heap allocations.
> 
> > Given what this code is intended to do, I think the assertions should be in release builds, not just debug builds.
> 
> No, we don't assert in production. See https://www.cryptopp.com/wiki/Assertions.
> 
> If you want to fail the function, then throw an exception like `std::bad_alloc` or `std::runtime_error`.

Sorry, I should have been clearer... I wasn't specifying the means of asserting.  Just that some of the sanity checks need to be there in production code.  If it's wrong it's very bad; it writes to memory that's out of bounds.  Ideally it'd be a compile-time check, but I can't think of how to do that for the whole reason that this code exists: if we can't guarantee m_array's alignment to 16 bytes at compile time, we have to resort to a mechanism that forces us to use m_array's actual alignment at runtime.

I hadn't thought about throwing, in part because this code is called from destructors right now.  So if I throw from GetAlignedArray(), the end result would often (always?) be the same as abort() (no one to catch it, crash).  As a rule of thumb I don't throw in my own code that's executed from a destructor if I can avoid it, since it often eventually burns me in a stack unwinding exception scenario anyway.

We could do the work from the constructor and throw from there, I think that's a better idea but isn't in my first pass since I was trying to minimize the changes.  That would alleviate the risk in deallocate(), and hence the troublesome destructor paths that exist.  If p_array is a class member, we set it to point within m_array only in the constructor and from there out trust that if the constructor didn't blow up (throw or exit), p_array is safe.  But we still have the issue that it's not common to try/catch for construction of instances on the stack.

Right now, I just don't see a great exception path without more changes.  Has me thinking exit() is the right answer; it's a condition that only happens if the internal code is doing some incorrect arithmetic (not a typical runtime error nor a caller-induced error).  So theoretically, it should never occur (because the arithmetic is correct).  Thoughts?  For me, no harm in just waiting for some iterations to flesh things out.

> 
> > I can fork and issue a pull request if you'd like to review.
> 
> Yes, sure.
> 
> If possible, don't remove `m_array`, `m_allocated` and `GetAlignedArray`. Leave them as dead code. I want to release a Crypto++ 8.4 soon, so I'd like to keep compatibility.

My changes just modify the problematic GetAlignedArray() and tweak the calculation of PAD.  I don't have any AIX platforms these days so I didn't do anything special there.  I don't think it needs anything special with my changes, since my changes don't make any assumptions about the alignment of m_array.  But it'd be good to test it on multiple platforms, I'm human.

I don't want to hold up your release schedule, and it's holiday time for many of us.  But I'll put a first minimal pull request in and we can iterate.  If/when it looks good enough for release is obviously totally up to you.

> 
> If we break the object layout then we need to move to Crypto++ 9.0, which I'm not ready to do at the moment.
> 
> Also, you can browse the Crypto++ 5.6.2 source files online [here](https://github.com/weidai11/cryptopp/tree/789f81f048c9bc472c7e7596f49b02eadd6fc1fd). Anything that's broken on Crypto++ 5.6.3 and later happened on my watch and I am responsible.

Just to be clear from my side... we all make mistakes, and I'm not personally looking to blame anyone.  Just trying to help fix the issues I find, in the current code.  This one's pretty nasty if a user hits it, and is the kind that could be hard to notice (depends on what gets stomped on).  The only reason I went back in time in the code was just to help illuminate the scope (in time, not in number of users) of the issue.  I don't have any idea how many platforms or users are in the mix and I believe the macros to get to this code have changed a decent amount over time.  I had gone back to 5_5 just as a random choice, then stepped back to 5_4 and didn't see it there (but I just searched for the modulo operator, I didn't actually examine the 5_4 code).  It's that "subtract modulo 16 of m_array's address" line that is wrong.  If the modulo result is 0, no harm.  If it's not... harm.

I think if this is done correctly, it will simplify some things.  No need for the final #else fall through, and hence the calling code no longer needs to have alignment conditionals; the class template will do the right thing regardless of whether or not m_array itself is aligned.  And if T_Align16 is changed to a size_t that's the alignment request, it'll work for other alignments; the code isn't specific to 16-byte alignments.  But to me it's wiser to move toward just using alignas().  Any idea how many users are still in a situation where their toolchain doesn't support it?

**Comment by noloader** [comment]
>  But to me it's wiser to move toward just using alignas(). Any idea how many users are still in a situation where their toolchain doesn't support it?

Requiring `alignas` would cause problems. It will break about 1/3 of the machines on the compile farm. It will break a lot of OS X machines. It will also cause problems with some compilers, like some Intel ICC or Clang. It will also cause trouble for [legacy] code that's been certified, like developed for US Federal or Medical. The legacy code in federal or medical cannot simply be upgraded because that would trigger a re-certification, and that often takes months to years and costs a lot of money.

For example, this is from my Mac-mini running OS X 10.12 using the `/usr/bin/c++` compiler out of the box.

```
$ cd cryptopp
$ cp -p TestScripts/configure.sh .
$ ./configure.sh

$ cat config_cxx.h
// config_cxx.h rewritten by configure.sh script
// Thursday, December 24 2020, 10:31 AM
// Also see https://www.cryptopp.com/wiki/configure.sh

#ifndef CRYPTOPP_CONFIG_CXX_H
#define CRYPTOPP_CONFIG_CXX_H

// ***************** C++98 and C++03 ********************

// Ancient Crypto++ define, dating back to C++98.
#define CRYPTOPP_UNCAUGHT_EXCEPTION_AVAILABLE 1
#define CRYPTOPP_CXX98_UNCAUGHT_EXCEPTION 1

// ***************** C++11 and above ********************

// test_cxx11.cxx returned non-zero result
// #define CRYPTOPP_CXX11 1

#if defined(CRYPTOPP_CXX11)

// #define CRYPTOPP_CXX11_ATOMIC 1
// #define CRYPTOPP_CXX11_AUTO 1
#define CRYPTOPP_CXX11_SYNCHRONIZATION 1
// #define CRYPTOPP_CXX11_STATIC_INIT 1
// #define CRYPTOPP_CXX11_DYNAMIC_INIT 1
// #define CRYPTOPP_CXX11_DELETED_FUNCTIONS 1
// #define CRYPTOPP_CXX11_ALIGNAS 1
// #define CRYPTOPP_CXX11_ALIGNOF 1
// #define CRYPTOPP_CXX11_INITIALIZER_LIST 1
// #define CRYPTOPP_CXX11_LAMBDA 1
// #define CRYPTOPP_CXX11_NOEXCEPT 1
// #define CRYPTOPP_CXX11_VARIADIC_TEMPLATES 1
// #define CRYPTOPP_CXX11_CONSTEXPR 1
// #define CRYPTOPP_CXX11_STRONG_ENUM 1
#define CRYPTOPP_CXX11_NULLPTR 1
// #define CRYPTOPP_CXX11_ASSERT 1

#endif  // CRYPTOPP_CXX11

// ***************** C++14 and above ********************

// test_cxx14.cxx returned non-zero result
// #define CRYPTOPP_CXX14 1

#if defined(CRYPTOPP_CXX14)

// No dead bodies here. Move on...

#endif  // CRYPTOPP_CXX14

// ***************** C++17 and above ********************

// test_cxx17.cxx returned non-zero result
// #define CRYPTOPP_CXX17 1

#if defined(CRYPTOPP_CXX17)

// #define CRYPTOPP_CXX17_ASSERT 1
// #define CRYPTOPP_CXX17_UNCAUGHT_EXCEPTIONS 1

#endif  // CRYPTOPP_CXX17

// ***************** C++ fixups ********************

#if defined(CRYPTOPP_CXX11_NOEXCEPT)
#  define CRYPTOPP_THROW noexcept(false)
#  define CRYPTOPP_NO_THROW noexcept(true)
#else
#  define CRYPTOPP_THROW
#  define CRYPTOPP_NO_THROW
#endif // CRYPTOPP_CXX11_NOEXCEPT

// C++11 nullptr_t type safety and analysis
#if defined(CRYPTOPP_CXX11_NULLPTR) && !defined(NULLPTR)
#  define NULLPTR nullptr
#elif !defined(NULLPTR)
#  define NULLPTR NULL
#endif // CRYPTOPP_CXX11_NULLPTR

#endif  // CRYPTOPP_CONFIG_CXX_H
```

**Comment by noloader** [comment]
OK, so I think I fixed the assert at [Commit 5537d998a15b](https://github.com/weidai11/cryptopp/commit/5537d998a15b):

```diff
   // byte* p_array = reinterpret_cast<byte*>(m_array) ...
-  CRYPTOPP_ASSERT(p_array+S <= m_array+(S+PAD));
+  CRYPTOPP_ASSERT(p_array+S*sizeof(T) <= m_array+(S+PAD));
```

That lit-up AIX, which gets into the code path in question:

```bash
passed:  10240 generated bytes compressed to 10245 bytes by DEFLATE
Assertion failed: secblock.h(524): GetAlignedArray
Assertion failed: secblock.h(524): GetAlignedArray
Assertion failed: secblock.h(524): GetAlignedArray
Assertion failed: secblock.h(524): GetAlignedArray
Assertion failed: secblock.h(524): GetAlignedArray
Assertion failed: secblock.h(524): GetAlignedArray
Assertion failed: secblock.h(524): GetAlignedArray
Assertion failed: secblock.h(524): GetAlignedArray
passed:  IncorporateEntropy with 128 bytes
passed:  GenerateWord32 and Crop
passed:  DiscardBytes with 1024 bytes
Assertion failed: secblock.h(524): GetAlignedArray
Assertion failed: secblock.h(524): GetAlignedArray
```

**Comment by noloader** [comment]
OK, so I think I fixed the assert at [Commit 5537d998a15b](https://github.com/weidai11/cryptopp/commit/5537d998a15b):

```diff
   // byte* p_array = reinterpret_cast<byte*>(m_array) + ...
-  CRYPTOPP_ASSERT(p_array+S <= m_array+(S+PAD));
+  CRYPTOPP_ASSERT(p_array+S*sizeof(T) <= m_array+(S+PAD));
```

That lit-up AIX, which gets into the code path in question:

```bash
Testing RandomPool generator...

passed:  10240 generated bytes compressed to 10245 bytes by DEFLATE
Assertion failed: secblock.h(524): GetAlignedArray
Assertion failed: secblock.h(524): GetAlignedArray
Assertion failed: secblock.h(524): GetAlignedArray
Assertion failed: secblock.h(524): GetAlignedArray
Assertion failed: secblock.h(524): GetAlignedArray
Assertion failed: secblock.h(524): GetAlignedArray
Assertion failed: secblock.h(524): GetAlignedArray
Assertion failed: secblock.h(524): GetAlignedArray
passed:  IncorporateEntropy with 128 bytes
passed:  GenerateWord32 and Crop
passed:  DiscardBytes with 1024 bytes
Assertion failed: secblock.h(524): GetAlignedArray
Assertion failed: secblock.h(524): GetAlignedArray
...
```

**Comment by noloader** [comment]
@dwmcrobb,

This diff is against the tip of Master. Do you know how reliable `alignas` is? Especially around the time when C++11 was being implemented?

```diff
$ git diff
diff --git a/secblock.h b/secblock.h
index 0670c6ed..e2a008cf 100644
--- a/secblock.h
+++ b/secblock.h
@@ -486,7 +486,17 @@ public:

 private:

-#if CRYPTOPP_BOOL_ALIGN16 && (defined(_M_X64) || defined(__x86_64__))
+#if CRYPTOPP_BOOL_ALIGN16 && defined(CRYTPOPP_CXX11_ALIGNAS)
+       // If we have a functioning C++11 toolchain we can use alignas.
+       // CRYPTOPP_ALIGN_DATA(16) will expand to alignas(16).
+       // TODO: verify the linker honors the alignment.
+       T* GetAlignedArray() {
+               CRYPTOPP_ASSERT(IsAlignedOn(m_array, 16));
+               return m_array;
+       }
+       CRYPTOPP_ALIGN_DATA(16) T m_array[S];
+
+#elif CRYPTOPP_BOOL_ALIGN16 && (defined(_M_X64) || defined(__x86_64__))
        // Before we can add additional platforms we need to check the
        // linker documentation for alignment behavior for stack variables.
        // CRYPTOPP_ALIGN_DATA(16) is known OK on Linux, OS X, Solaris.
```

**Comment by noloader** [comment]
@dwmcrobb,

This diff is from my local machines. It is against the tip of Master. It adds `alignas` as the first use case, and moves the orignal use case down to the second case.

Do you know how reliable `alignas` is? Especially around the time when C++11 was being implemented? Is this safe to check-in?

The reason I ask is, I know there are some large gaps in C++11 support. The landscape is worse than painted at [C++ compiler support](https://en.cppreference.com/w/cpp/compiler_support).

```diff
$ git diff
diff --git a/secblock.h b/secblock.h
index 0670c6ed..e2a008cf 100644
--- a/secblock.h
+++ b/secblock.h
@@ -486,7 +486,17 @@ public:

 private:

-#if CRYPTOPP_BOOL_ALIGN16 && (defined(_M_X64) || defined(__x86_64__))
+#if CRYPTOPP_BOOL_ALIGN16 && defined(CRYTPOPP_CXX11_ALIGNAS)
+       // If we have a functioning C++11 toolchain we can use alignas.
+       // CRYPTOPP_ALIGN_DATA(16) will expand to alignas(16).
+       // TODO: verify the linker honors the alignment.
+       T* GetAlignedArray() {
+               CRYPTOPP_ASSERT(IsAlignedOn(m_array, 16));
+               return m_array;
+       }
+       CRYPTOPP_ALIGN_DATA(16) T m_array[S];
+
+#elif CRYPTOPP_BOOL_ALIGN16 && (defined(_M_X64) || defined(__x86_64__))
        // Before we can add additional platforms we need to check the
        // linker documentation for alignment behavior for stack variables.
        // CRYPTOPP_ALIGN_DATA(16) is known OK on Linux, OS X, Solaris.
```

**Comment by dwmcrobb** [comment]
Got it.  I'm not saying require alignas(); I'm saying use it (or equivalent) if it's available and does the right thing, else fall back to the mechanism that I've patched (which should work everywhere).  No falling back to "whatever the toolchain gave us" (the final #else).  So when instantiating the template, the user (in most/all cases, internal to the library?) gets what was requested, whether via alignas() or similar (meaning m_array can be aligned as requested) or via the patched mechanism.  Over time, more platforms will wind up with the alignas() solution by adding it or correcting it, without doing any additional work in the library.  Everyone else will still get what they requested, just via a different mechanism.  I'm using alignas() here as shorthand for whatever mechanism is provided that can guarantee 16-byte alignment.  Put it where it makes sense, make secblock.h a bit simpler to maintain.  Instead of this:

```
#if CRYPTOPP_BOOL_ALIGN16 && (defined(_M_X64) || defined(__x86_64__))
...
#else if CRYPTOPP_BOOL_ALIGN16
....
#else
...
#endif

```
I'm picturing something like this:

```
#if defined(CRYPTOPP_ALIGN_16)
    ....
    CRYPTOPP_ALIGN_16(T m_array[S]);
#else
   //  patched mechanism
#endif

```
CRYPTOPP_ALIGN_16(x) could just be a wrapper around CRYPTO_ALIGN_DATA(x), but needs to be undefined if there's no way for the platform to give us 16-byte alignment.  So today it's a special case since CRYPTO_ALIGN_DATA(x) today can be an empty macro (defined but provides no alignment).

Then I think all of the other `#if CRYPTOPP_BOOL_ALIGN16` can be removed from secblock.h and it goes back to just using the `T_Align16` template parameter.  CRYPTOPP_ALIGN_16 either exists and can align on 16 bytes via whatever mechanism works on the platform (alignas(), __attribute__((aligned)), et. al.), or doesn't exist because the toolchain doesn't provide a means of forcing 16-byte alignment.  Initially I thought we could just have a generic CRYPTO_ALIGN_DATA(x) but as you already know, some toolchains can align up to some small value and then can't align beyond that value.

alignas() is available on all of the platforms I have on hand at home but produces warnings and incorrect alignment on two for any request beyond a small amount (8 bytes for g++ 8.3.0 on Raspbian 10 32-bit on Pi 4, 16 bytes for g++ 9.2.0 on Gentoo 2.7 aarch64 on Pi 4).  However, on those I normally use clang and it produces the correct alignment for any reasonable power of 2.  I seem to recall that g++ was fixed for this upstream in a later release but the fix was not in the Raspbian 10 repositories the last I checked.  But I'm assuming that once Raspbian officially goes to 64 bit kernel and userland on Pi 4, g++ there will at least match Gentoo 2.7 aarch64 (can align to 16 bytes but not more).

My list from home machines is pretty small and I haven't checked all of them.  I've only checked FreeBSD 12.2-STABLE on amd64 (clang 10.0.1), macOS 10.14 (clang 10.0.0), macOS 10.15 (clang 12.0.0), Ubuntu 20.04 (g++ 9.3.0), Raspbian 10 on Pi 4 (g++ 8.3.0 fails above 8, clang 9.0.1 works), Gentoo 2.7 on Pi 4 (g++ 9.2.0 fails above 16, clang 9.0.1 works).  I haven't checked any of the Windows 10 amd64 instances or older Raspbian on the Pi3 (though for the latter I'd expect the same issues as Raspbian 10 on the Pi4, at best).

Raspbian 10 and Gentoo on Pi4 have been two of the platforms where I've had to work around issues (I'm not done, there are still some issues if I don't set CRYPTOPP_DISABLE_ASM).  Either of these in the compile farm?

**Comment by dwmcrobb** [comment]
> @dwmcrobb,
> 
> This diff is from my local machines. It is against the tip of Master. It adds `alignas` as the first use case, and moves the orignal use case down to the second case.
> 
> Do you know how reliable `alignas` is? Especially around the time when C++11 was being implemented? Is this safe to check-in?

It's not reliable on some platforms, including current ones with their readily-available compiler (Raspbian 10 32-bit on Pi 4, which has g++ 8.3.0 in the apt repo, for example).  Hence it's not good enough to check for its existence, unfortunately.  Have to check that it actually does what's asked.  On the platforms I have handy at home where it doesn't do what's asked, it at least produces a warning.  So a test could just escalate the warning to an error instead of trying to exhaustively ask for alignment of various things and checkin their alignment.

On Raspbian 10, I've been using clang for a while due to it being ahead of the readily available gcc.  It doesn't cure everything (Raspbian has some other issues due to the libs using an older ABI for some common standard C++ classes), but it's better for most of my work on Raspbian.

> 
> The reason I ask is, I know there are some large gaps in C++11 support. The landscape is worse than painted at [C++ compiler support](https://en.cppreference.com/w/cpp/compiler_support).
> 
> ```diff
> $ git diff
> diff --git a/secblock.h b/secblock.h
> index 0670c6ed..e2a008cf 100644
> --- a/secblock.h
> +++ b/secblock.h
> @@ -486,7 +486,17 @@ public:
> 
>  private:
> 
> -#if CRYPTOPP_BOOL_ALIGN16 && (defined(_M_X64) || defined(__x86_64__))
> +#if CRYPTOPP_BOOL_ALIGN16 && defined(CRYTPOPP_CXX11_ALIGNAS)
> +       // If we have a functioning C++11 toolchain we can use alignas.
> +       // CRYPTOPP_ALIGN_DATA(16) will expand to alignas(16).
> +       // TODO: verify the linker honors the alignment.
> +       T* GetAlignedArray() {
> +               CRYPTOPP_ASSERT(IsAlignedOn(m_array, 16));
> +               return m_array;
> +       }
> +       CRYPTOPP_ALIGN_DATA(16) T m_array[S];
> +
> +#elif CRYPTOPP_BOOL_ALIGN16 && (defined(_M_X64) || defined(__x86_64__))
>         // Before we can add additional platforms we need to check the
>         // linker documentation for alignment behavior for stack variables.
>         // CRYPTOPP_ALIGN_DATA(16) is known OK on Linux, OS X, Solaris.
> ```

Sorry we were typing responses at the same time, my previous response was written before I saw your latest.  I'll take a look at what you said.

**Comment by noloader** [comment]
> Sorry we were typing responses at the same time, my previous response was written before I saw your latest. I'll take a look at what you said.

Yeah, I went ahead and checked in the fix for the underrun.

You can grab just the updated `secblock.h` with Wget. It should be compatible with the version of Crypto++ you are using.

```
wget -O secblock.h https://raw.githubusercontent.com/weidai11/cryptopp/master/secblock.h
```

**Comment by noloader** [comment]
It looks like `secblock.h` in Master retained backwards compat with the version in Crypto++ 8.3. That's according to `cryptest-symbols.sh`, which links Crypto++ 8.3 `cryptest.exe` against Master's `libcryptopp,so`. That is, no symbols went missing and no memory errors surfaced.

That's a big relief.

**Comment by dwmcrobb** [comment]
See my last comment on the commit.  Note that CRYPTOPP_ALIGN_DATA(x) theoretically may do nothing at all (it could expand to nothing if you fall through to the last #else in config_align.h).  I'd prefer it works the way it is in my patch (which coincidentally essentially mirrors what you do in allocate.cpp): don't make any assumptions about what CRYPTO_ALIGN_DATA(x) does because it may do nothing.

**Comment by dwmcrobb** [comment]
Just duplicating what I commented for one of the commits...

This is the gist of my patch:

```
  T* GetAlignedArray() {
      size_t  alignoff = AL - ((size_t)(&(m_array[0])) % AL);
      char *p = (char *)(&(m_array[0])) + alignoff;
      T* p_array = reinterpret_cast<T*>(p);
      CRYPTOPP_ASSERT(IsAlignedOn(p_array, AL));
      //  Verify start of p_array is in bounds.
      CRYPTOPP_ASSERT(p_array >= &(m_array[0]));
      // Verify end of p_array is in bounds.
      CRYPTOPP_ASSERT((p_array + S) <= &(m_array[S+PAD]));
      return p_array;
  }

```

I have `AL` as a static const class member, it could easily be promoted to a template parameter, and need not be a power of 2 though there's no use case here for other alignments so I static_assert it if C++11 is in play.

```
    //  'AL' could be a template parameter.
    static const size_t  AL = 16;  // alignment, in bytes.
#if defined(CRYPTOPP_CXX11)
     static_assert((AL > 0) && !(AL & (AL - 1)),
                    "Alignment must be power of 2");
#endif
    static const size_t  Q = sizeof(T);
    static const size_t  PAD = ((AL + Q) / Q) > 1 ? ((AL + Q) / Q) : 1;

    CRYPTOPP_ALIGN_DATA(AL) T  m_array[S+PAD];

```

**Comment by noloader** [comment]
@dwmcrobb,

I tried to get a CVE for the memory error but Mitre has a broken web form at https://cveform.mitre.org/. I then tried to email Mitre for a CVE assignment at cve@mitre.org. The email bounced and told me to go to the broken web form.

I'm giving up on a CVE assignment.

If interested, I did some research... The issue affects Crypto++ 5.6.0 through 8.3.0. Crypto++ 5.5 and below were not affected because `FixedSizeAllocatorWithCleanup` did not have the `T_Align16` template parameter (yet).

**Comment by dwmcrobb** [comment]
Thanks much!

**Comment by noloader** [comment]
@dwmcrobb,

I started drafting the Crypto++ 8.4 release notes. You can find it [here](https://www.cryptopp.com/release840.html). We will release Crypto++ 8.4 in about 3 weeks.

Three weeks is the T+30 day release. We perform a scheduled release about a month after a big release (Crypto++ 8.3) to fix the stragglers bugs that were not reported during previous (8.3) testing. That gets the bugs off the books for everyone.

**Comment by noloader** [comment]
@dwmcrobb,

I started drafting the Crypto++ 8.4 release notes. You can find it [here](https://www.cryptopp.com/release840.html).

We will release Crypto++ 8.4 in about 3 weeks. Three weeks is the T+30 day release. We perform a scheduled release about a month after a big release (Crypto++ 8.3) to fix the stragglers bugs that were not reported during previous (Crypto++ 8.3) testing. That gets the bugs off the books for everyone.
