### ISSUE TITLE
MSVC2015 (win64) CMakeLists.txt issues

### ISSUE THREAD

**Issue by ZahlGraf** [weidai11/cryptopp#99]
Hi

first of all: Thanks for this great library, it helped me a lot in a current student project!

However there were some compile issues with msvc2015 and CMake:
- for MSVC some assembler sources must be add
- also Assembler must be enabled and correct flags must be set
- there was also another source winpipes.cpp missing

Furthermore the define CRYPTO_DATA_DIR needs quote symbols (for all compilers and systems)

I created a small patch, that works for me. Maybe this also helps other people out there.
I tested the patch for Win64 build (MSVC2015), Linux64 (GCC) build and Android (Android NDK r10e) build. In all builds the debug and release version works well. I did not test the shared libraries, since they are limited anyway. 
However currently I have no time to test Win32 builds or other compilers and systems like MacOSX and CLang. That's why I did not create a pull request.

This is the patch, have a lot of fun with it :)

```patch
From 1531ab255d84b5c774284031927293f18f7c0254 Mon Sep 17 00:00:00 2001
From: Andre Netzeband <there_is_no@mail.de>
Date: Fri, 1 Jan 2016 18:32:34 +0100
Subject: [PATCH] Corrected missing quote symbols for crypto-data-dir
 definition. Added special settings for MSVC: Enable Assembler, set assembler
 flags for 32bit and 64bit added missing assembler files and source files.

---
 CMakeLists.txt | 17 ++++++++++++++++-
 1 file changed, 16 insertions(+), 1 deletion(-)

diff --git a/CMakeLists.txt b/CMakeLists.txt
index 7ca9aea..8fa8631 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -48,13 +48,15 @@ if(DISABLE_AESNI)
 	add_definitions(-DCRYPTOPP_DISABLE_AESNI)
 endif()
 if(NOT CRYPTOPP_DATA_DIR STREQUAL "")
-	add_definitions(-DCRYPTOPP_DATA_DIR=${CRYPTOPP_DATA_DIR})
+	add_definitions(-DCRYPTOPP_DATA_DIR="${CRYPTOPP_DATA_DIR}")
 endif()
 
 #============================================================================
 # Sources & headers
 #============================================================================
 
+math(EXPR BITS "8*${CMAKE_SIZEOF_VOID_P}")
+
 # Library headers
 file(GLOB cryptopp_HEADERS *.h)
 
@@ -82,6 +84,19 @@ if(MINGW)
 	list(APPEND cryptopp_SOURCES ${CMAKE_CURRENT_SOURCE_DIR}/winpipes.cpp)
 endif()
 
+if(MSVC)
+    enable_language(ASM_MASM)
+	if (BITS EQUAL 32)
+	   SET(CMAKE_ASM_MASM_FLAGS "${CMAKE_ASM_MASM_FLAGS} /nologo /D_M_X86 /W3 /Cx /Zi /safeseh")
+	else ()
+	   SET(CMAKE_ASM_MASM_FLAGS "${CMAKE_ASM_MASM_FLAGS} /nologo /D_M_X64 /W3 /Cx /Zi")
+	list(APPEND cryptopp_SOURCES ${CMAKE_CURRENT_SOURCE_DIR}/x64dll.asm)
+	list(APPEND cryptopp_SOURCES ${CMAKE_CURRENT_SOURCE_DIR}/x64masm.asm)
+	endif ()
+	list(APPEND cryptopp_SOURCES ${CMAKE_CURRENT_SOURCE_DIR}/winpipes.cpp)
+	list(APPEND cryptopp_SOURCES ${CMAKE_CURRENT_SOURCE_DIR}/rdrand.asm)
+endif()
+
 #============================================================================
 # Compile targets
 #============================================================================
-- 
2.5.0.windows.1
```

**Comment by noloader** [comment]
Thanks. We [recently added Cmake support](https://github.com/weidai11/cryptopp/commit/f14c62b6e37fecd9587bd33a6315e7be2f519fc1). I'm beginning to think it was a bit premature, and we probably should have added it to out [Patch Page](https://www.cryptopp.com/wiki/Category:Patch) to allow it to mature a bit.

Let me think about how we should proceed.

**Comment by noloader** [comment]
>     +if(MSVC)

There are a bunch of preprocessor defines missing.

>     +   list(APPEND cryptopp_SOURCES ${CMAKE_CURRENT_SOURCE_DIR}/x64dll.asm)
>     +   list(APPEND cryptopp_SOURCES ${CMAKE_CURRENT_SOURCE_DIR}/x64masm.asm)

I believe you need `x64dll.asm` when building the [FIPS Validated DLL](https://www.cryptopp.com/wiki/FIPS_DLL), otherwise you need `x64masm.asm`. I'd have to check to be sure, but I'm not in front of a Windows machine.

**Comment by ZahlGraf** [comment]
Which preprocessor defines are missing, I thought they were set in the remaining part of the CMakeLists.txt?

I think fixing a non working CMakeLists.txt file is easier than build a new one. I'm a big fan of CMake, since it makes compiling so easy on different systems and with different compilers. So the existence of the CMakeLists.txt was on reason why I chose this lib :)

**Regarding both ASM-files:** Without both files I got link errors due to missing symbols. I just add both files without testing if x64masm.asm alone will also work. But I think both are necessary, since CMake builds here the static lib **and** the shared lib (dll) together in one run. So even if I don't use the DLL, I guess I would get linker errors for it, when I don't have the x64dll.asm inside the source.

However with the windows DLL build there are also some other things broken: For example the defines for the DLL exports are not set correctly. Since I don't need the DLL I just ignored it. I don't know if it is a good idea to have shared and static build in the same compile run for windows, since the defines for both are differently and it is easier in CMake to have the same defines for all build targets. But I think it is possible to manage it to have different defines for different targets. 

I wish I could help you more. My philosophy is, that when I take something from an open source project, I should also give something to it, to support it :) However at the moment my student project is very time demanding and I must fully concentrate on it, to get it running until I have to show it my Prof.

**Comment by noloader** [comment]
> Which preprocessor defines are missing, I thought they were set in the remaining part of the CMakeLists.txt?

Well, I'm not really sure. I know what looks right from looking at the project's property pages under VS.

One of the things I don't like about Cmake is its hard to audit. I used to have to ask the devs to send me their build logs so I could inspect their build settings.

```
$ grep 'PreprocessorDefinitions' cryptlib.vcproj | grep -v 'PreprocessorDefinitions=""'
	PreprocessorDefinitions="NDEBUG;_WINDOWS;USE_PRECOMPILED_HEADERS;WIN32"
	PreprocessorDefinitions="NDEBUG;_WINDOWS;USE_PRECOMPILED_HEADERS;WIN32"
	PreprocessorDefinitions="NDEBUG;_WINDOWS;USE_PRECOMPILED_HEADERS;WIN32;CRYPTOPP_IMPORTS"
	PreprocessorDefinitions="NDEBUG;_WINDOWS;USE_PRECOMPILED_HEADERS;WIN32;CRYPTOPP_IMPORTS"
	PreprocessorDefinitions="_DEBUG;_WINDOWS;USE_PRECOMPILED_HEADERS;WIN32"
	PreprocessorDefinitions="_DEBUG;_WINDOWS;USE_PRECOMPILED_HEADERS;WIN32"
	PreprocessorDefinitions="_DEBUG;_WINDOWS;USE_PRECOMPILED_HEADERS;WIN32;CRYPTOPP_IMPORTS"
	PreprocessorDefinitions="_DEBUG;_WINDOWS;USE_PRECOMPILED_HEADERS;WIN32;CRYPTOPP_IMPORTS"
...
```

And:

```
$ grep 'PreprocessorDefinitions' cryptdll.vcproj | grep -v 'PreprocessorDefinitions=""'
	PreprocessorDefinitions="NDEBUG;WIN32;_WINDOWS;_USRDLL;CRYPTOPP_EXPORTS;CRYPTOPP_ENABLE_COMPLIANCE_WITH_FIPS_140_2=1;USE_PRECOMPILED_HEADERS"
	PreprocessorDefinitions="NDEBUG"
	PreprocessorDefinitions="NDEBUG;WIN32;_WINDOWS;_USRDLL;CRYPTOPP_EXPORTS;CRYPTOPP_ENABLE_COMPLIANCE_WITH_FIPS_140_2=1;USE_PRECOMPILED_HEADERS"
	PreprocessorDefinitions="NDEBUG"
	PreprocessorDefinitions="_DEBUG;WIN32;_WINDOWS;_USRDLL;CRYPTOPP_EXPORTS;CRYPTOPP_ENABLE_COMPLIANCE_WITH_FIPS_140_2=1;USE_PRECOMPILED_HEADERS"
	PreprocessorDefinitions="_DEBUG"
	PreprocessorDefinitions="_DEBUG;WIN32;_WINDOWS;_USRDLL;CRYPTOPP_EXPORTS;CRYPTOPP_ENABLE_COMPLIANCE_WITH_FIPS_140_2=1;USE_PRECOMPILED_HEADERS"
	PreprocessorDefinitions="_DEBUG"
...
```

**Comment by ZahlGraf** [comment]
In my projects I have also a print-cmake-script that prints out all important settings from the project. It helps a lot while debugging. Furthermore there is the `-LH` command line option for cmake, to print all CMake-Settings like compiler flags and option settings. With both together I can easily debug my projects when they fail at the CI server.

Thanks for printing the defines. I'm so sorry that I did not had the idea to simply grep the VS projects :)

So the defines from above (non dll project) are set automatically by CMake (NDEBUG, _DEBUG, WIN32) except USE_PRECOMPILED_HEADERS. Maybe this definition is set anywhere else in the CMakeLists.txt I did not look. But it is not critical, it simply helps to speed up the build, when you build the library several times.

From the dll-project the CRYPTOPP_EXPORTS is not set correctly, this I already saw, since the DLL link library was missing. So I guess the other defines are also not set like CRYPTOPP_ENABLE_COMPLIANCE_WITH_FIPS_140_2=1. But the standard defines (_DEBUG, NDEBUG, _USRDLL, WIN32) are set automatically by CMake again.

By the way: I did not generate visual studio project files with CMake, I generated NMake-Makefiles to build on command line only. But I think when these settings are not in the command line build, they will also not be inside the generated project files.

**Comment by ZahlGraf** [comment]
This is an example how the output of the cmake-print-script looks like in one of my projects:
```
-- The following settings have been applied:
--  -> Dependencies found:
--     * Boost:    TRUE
--     * Cryptopp: TRUE
--
--  -> Optional dependencies found:
--     * Doxygen:  YES
--
--  -> Options set:
--     * Build static lib:             ON
--     * Install media files:          ON
--     * Build tests:                  ON
--     * Build examples:               ON
--
--  -> Compiler settings:
--     * GCC like compiler:            OFF
--     * MSVC like compiler:           ON
--     * C++ Compiler flags:            /DWIN32 /D_WINDOWS /W3 /GR /EHsc /bigobj
--     * C++ Compiler flags (release): /MD /O2 /Ob2 /D NDEBUG
--     * C++ Compiler flags (debug):   /D_DEBUG /MDd /Zi /Ob0 /Od /RTC1
--     * C Compiler flags:              /DWIN32 /D_WINDOWS /W3
--     * C Compiler flags (release):   /MD /O2 /Ob2 /D NDEBUG
--     * C Compiler flags (debug):     /D_DEBUG /MDd /Zi /Ob0 /Od /RTC1
--     * Linker flags (executable):     /machine:x64
--     * Linker flags (module):         /machine:x64
--     * Linker flags (static lib):
--     * Linker flags (shared lib):     /machine:x64
--     * Use define: _SCL_SECURE_NO_WARNINGS
--     * Use define: _CRT_SECURE_NO_WARNINGS
--     * Use define: _MYSAFE_STATIC_LIB_
--     * Use define: CPPUTEST_USE_MEM_LEAK_DETECTION=0
--
--  -> Install Path: D:/Projects/CPP/Projects/mySafe/mySafeCore/install/msvc2015-win64/debug/static
--
--  -> Configure examples:
--     * Configure: mysafe...
--
--  -> Configure all tests:
--     * Configure: UnitTests...
--     * Configure: UI_UnitTests...
--     * Configure: JSON_Tests...
--     * Configure: HashLib_Tests...
```

**Comment by DevJPM** [comment]
Am 01.01.2016 um 18:44 schrieb ZahlGraf:
>
> Hi
>
> first of all: Thanks for this great library, it helped me a lot in a
> current student project!
>
> However there were some compile issues with msvc2015 and CMake:
>
>   * for MSVC some assembler sources must be add
>   * also Assembler must be enabled and correct flags must be set
>   * there was also another source winpipes.cpp missing
>
> Furthermore the define CRYPTO_DATA_DIR needs quote symbols (for all
> compilers and systems)
>
Maybe that's me:
How did you generate your msvc2015 project files?

Did you apply some tool at the provided solution files?

In this case you may want to consider applying the VS-2010.zip patch
(coming with the library) if you didn't already do this, as the missing
ASM files looks oddly familiar to a similar issue I had with VS2015.

Sorry if this doesn't apply to your issue.

BR

JPM

**Comment by ZahlGraf** [comment]
@DevJPM
I did not use any of the pre delivered VS2010 project files. I just used CMake to generate NMake Makefiles for Windows and Unix Makefiles for Linux/Android.

**Comment by noloader** [comment]
I don't believe you need these:

```
--     * Boost:    TRUE
--     * Use define: _SCL_SECURE_NO_WARNINGS
--     * Use define: _CRT_SECURE_NO_WARNINGS
```

We cleared the `*_SECURE_NO_WARNINGS`  because they are a C&A item. That is, some folks use them as a security gates, and they can't use software that depends upon them.

You may need `*_SECURE_NO_WARNINGS` for Boost. If so, you should should probably file a bug report against them.

**Comment by ZahlGraf** [comment]
Oh, sorry for confusion, the printed output from above is just an example output from my project to show you how a printed CMake-Summary could look like. Of course your library don't need these defines... however another library I'm using need it. This library is not stated in the print-text, since it is a simple embedded source library, so it is compiled together with my source.

**Comment by GamePad64** [comment]
Well, I've added this patch in #96, but I have no means to test it in Windows environment right now.

**Comment by noloader** [comment]
I sent this to a few folks who are more familiar with Cmake then me.

```
On Wed, Jun 22, 2016 at 9:09 AM, Jeffrey Walton <noloader@gmail.com> wrote:
> http://github.com/weidai11/cryptopp/issues/99
>
> Any thoughts? Should it be closed now?
>
> Or, does something else need to be done?
>
> If someone makes a PR, then I'd be happy to apply it.
```

**Comment by noloader** [comment]
According to Геннадий Забула, the issues have been resolved in the latest set of PRs for Cmake. Here are the PRs:

* http://github.com/weidai11/cryptopp/pull/201
* http://github.com/weidai11/cryptopp/pull/200

The 200 PR cleared three bug reports, and I suspect it cleared this issue, too. If needed, please open another report.
