### ISSUE TITLE
This change breaks compilation on MacOS

### ISSUE THREAD

**Issue by mouse07410** [weidai11/cryptopp#991]
MacOS 10.15.7, Xcode-12.3. Env var `AS_INTEGRATED_ASSEMBLER=1` is set.

https://github.com/weidai11/cryptopp/blob/d555d072c959c2beb65a7737309530d2e038e554/config_asm.h#L50

Here's what that line looks like in my fork:
```c++
#if defined(__clang__) || (defined(__APPLE__) && defined(__GNUC__)) || defined(__SUNPRO_CC)
```

**Comment by noloader** [comment]
Thanks @mouse07410,

I'm guessing that broke before PR #990.

I don't have access to Xcode  12.3. Do you feel like checking in a fix? I'll ping you if something goes sideways on my test gear.

**Comment by mouse07410** [comment]
Sure. Thanks.

**Comment by mouse07410** [comment]
Should be done now. @noloader after the CI completes, would you mind closing this issue if everything finishes OK? Thanks!
