### ISSUE TITLE
Broken elliptic curve identities

### ISSUE THREAD

**Issue by mkskeller** [weidai11/cryptopp#994]
It seems that c9ef9420e762b91cc06463d349cf06e04c749b9d breaks basic elliptic curve identities. The following outputs three times 1 before and three times 0 after:

```c++
#include "eccrypto.h"
#include "oids.h"
#include <iostream>

int main()
{
  using namespace CryptoPP;
  auto params = DL_GroupParameters_EC<ECP>(ASN1::secp256k1());
  auto id = params.ExponentiateBase(0);
  std::cout << (id == params.GetCurve().Add(id, id)) << std::endl;
  auto gen = params.ExponentiateBase(1);
  std::cout << (gen == params.GetCurve().Add(id, gen)) << std::endl;
  std::cout << (params.ExponentiateBase(2) == params.GetCurve().Add(gen, gen)) << std::endl;
  return not (id == params.GetCurve().Add(id, id));
}
```

I'm using Ubuntu 20.04 with the system GCC.

**Comment by noloader** [comment]
Ugh, thanks @mkskeller.

I'm going to back out most of the constant-time changes. My thinking is, the lesser of the two evils is the timing leak. The worse case is arriving at an incorrect result, and that is what currently happens.

Ping @mouse07410 .

**Comment by noloader** [comment]
Distro maintainers,

Here is the patch needed to back-out the broken code. It can be applied against Crypto++ 8.3.0 release. [cryptopp-gh994-fix.diff.zip](https://github.com/weidai11/cryptopp/files/5753823/cryptopp-gh994-fix.diff.zip)

**Comment by mouse07410** [comment]
I concur.
