### ISSUE TITLE
setenv-android.sh sed: 1: "cpu-features.c": command c expects \ followed by text

### ISSUE THREAD

**Issue by lordadamson** [weidai11/cryptopp#995]
### Crypto++ Issue Report

when running setenv-android.sh on macos it gives the following error:

```
sed: 1: "cpu-features.c": command c expects \ followed by text
```

* State the operating system and version
macOS 11.1 (Big Sur)
* State the version of the Crypto++ library
Master
* State how you built the library (Makefile, Cmake, distro, etc)

```
export ANDROID_API="23"
export ANDROID_CPU="armv8"

source TestScripts/setenv-android.sh
```

* Show a typical command line (the output of the compiler for cryptlib.cpp)
N/A
* Show the link command (the output of the linker for libcryptopp.so or cryptest.exe)
N/A
* Show the exact error message you are receiving (copy and paste it); or Clearly state the undesired behavior (and state the expected behavior)

```
sed: 1: "cpu-features.c": command c expects \ followed by text
```

**Comment by noloader** [comment]
Thanks @lordadamson,

I forgot how lame some of the tools are on OS X.

Cleared at [Commit 64baae056c7c](https://github.com/weidai11/cryptopp/commit/64baae056c7c).

**Comment by lordadamson** [comment]
ok awesome 👍
