### ISSUE TITLE
iOS: Should we compile with bitcode enabled by default?

### ISSUE THREAD

**Issue by lordadamson** [weidai11/cryptopp#997]
I think we should have bitcode enabled by default because Apple is pushing too hard that they'll make your life miserable if you don't have it. It's not even optional on watchOS and tvOS, Apple just won't accept your binaries unless they have bitcode embedded.

The way I did it for now:

```
export CXXFLAGS="-DNDEBUG -g2 -O3 -fPIC -pipe -fembed-bitcode"
make -f GNUmakefile-cross
```

If you think enabling bitcode support by default is good idea I'll make a PR.

If you see that there are backward compatibility issues with this change that we must be concerned about let me know and I probably would still make a PR that enables bitcode by passing some flag or setting some environment variable.

**Comment by noloader** [comment]
> I think we should have bitcode enabled by default because Apple is pushing too hard that they'll make your life miserable if you don't have it.

You can have bitcode but it will break the library.

The only way I know to use bitcode is to add `-DCRYPTOPP_DISABLE_ASM` to the command line.

**Comment by lordadamson** [comment]
Oh wow, I didn't know that. Thanks for the heads up 😄 

I'll recompile with `-DCRYPTOPP_DISABLE_ASM` then.

**Comment by lordadamson** [comment]
though I imagine, there's gonna be a performance hit or something right?

**Comment by noloader** [comment]
> there's gonna be a performance hit or something right?

Yes.
