### ISSUE TITLE
Visual studio 2019 support

### ISSUE THREAD

**Issue by gaborgsomogyi** [weidai11/cryptopp#999]
The webpage states the following:
`Visual Studio 2003 - 2019`

`cryptest.sln` contains the following:
```
Microsoft Visual Studio Solution File, Format Version 11.00
# Visual Studio 2010
```

Visual studio 2019 generated solution file contains the following:
```
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio Version 16
```

It would be good to open it with Visual studio 2019 and commit the changed solution and project files.

* OS: Win 10 pro X64
* Version: Crypto++ 8.4.0
* Build tool: Visual studio 2019

**Comment by noloader** [comment]
Visual Studio is forward compatible. Opening a VS2010 project will convert to VS2019.

If we set it to VS2019, then the project will fail to open for VS201, VS2012, VS2013, VS2015 and VS2017.

**Comment by gaborgsomogyi** [comment]
Tried it out and works like that, closing. Thanks for taking a look.
